### ISSUE TITLE
combine_sample_regions error

### ISSUE THREAD

**Issue by danhalligan** [chapmanb/bcbio-nextgen#1002]
I recently attempted to run a variant calling pipeline, but it failed at the combine_sample_regions stage. bcbio_nextgen.py version 0.9.2.

STDOUT:

    [2015-09-05T06:51Z] multiprocessing: combine_sample_regions
    Traceback (most recent call last):
      File "/xxx/bin//bcbio_nextgen.py", line 226, in <module>
        main(**kwargs)
      File "/xxx/bin//bcbio_nextgen.py", line 43, in main
        run_main(**kwargs)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
        fc_dir, run_info_yaml)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
        for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 150, in run
        samples = run_parallel("combine_sample_regions", [samples])
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
        return run_multicore(fn, items, config, parallel=parallel)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
        for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 657, in __call__
        self.dispatch(function, args, kwargs)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 404, in dispatch
        job = ImmediateApply(func, args, kwargs)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 142, in __init__
        self.results = func(*args, **kwargs)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 49, in wrapper
        return apply(f, *args, **kwargs)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 182, in combine_sample_regions
        return callable.combine_sample_regions(*args)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 412, in combine_sample_regions
        analysis_file, no_analysis_file = _combine_sample_regions_batch(batch, items)
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 454, in _combine_sample_regions_batch
        nblock_regions = reduce(operator.add, bed_regions).saveas(
      File "/xxx/bcbio/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 1006, in __add__
        return result
    UnboundLocalError: local variable 'result' referenced before assignment

Config template yaml file:

    details:
      - analysis: variant2
        genome_build: hg38
        algorithm:
          aligner: bwa
          mark_duplicates: true
          recalibrate: false
          realign: false
          variantcaller: freebayes
          effects: false
          tools_off: 
            - gemini

Sample csv file:

    samplename,description,lane,batch
    sample1_exome_CGTACTAG_L004_R1_001.fastq.gz,sample1_L4,4,batch1
    sample1_exome_CGTACTAG_L004_R2_001.fastq.gz,sample1_L4,4,batch1
    sample1_exome_CGTACTAG_L005_R1_001.fastq.gz,sample1_L5,5,batch1
    sample1_exome_CGTACTAG_L005_R2_001.fastq.gz,sample1_L5,5,batch1
    sample2_exome_GGACTCCT_L004_R1_001.fastq.gz,sample2_L4,4,batch1
    sample2_exome_GGACTCCT_L004_R2_001.fastq.gz,sample2_L4,4,batch1
    sample2_exome_GGACTCCT_L005_R1_001.fastq.gz,sample2_L5,5,batch1
    sample2_exome_GGACTCCT_L005_R2_001.fastq.gz,sample2_L5,5,batch1
    sample3_exome_TAGGCATG_L004_R1_001.fastq.gz,sample3_L4,4,batch1
    sample3_exome_TAGGCATG_L004_R2_001.fastq.gz,sample3_L4,4,batch1
    sample3_exome_TAGGCATG_L005_R1_001.fastq.gz,sample3_L5,5,batch1
    sample3_exome_TAGGCATG_L005_R2_001.fastq.gz,sample3_L5,5,batch1
    sample4_exome_TCCTGAGC_L004_R1_001.fastq.gz,sample4_L4,4,batch1
    sample4_exome_TCCTGAGC_L004_R2_001.fastq.gz,sample4_L4,4,batch1
    sample4_exome_TCCTGAGC_L005_R1_001.fastq.gz,sample4_L5,5,batch1
    sample4_exome_TCCTGAGC_L005_R2_001.fastq.gz,sample4_L5,5,batch1
    sample5_exome_AGGCAGAA_L004_R1_001.fastq.gz,sample5_L4,4,batch1
    sample5_exome_AGGCAGAA_L004_R2_001.fastq.gz,sample5_L4,4,batch1
    sample5_exome_AGGCAGAA_L005_R1_001.fastq.gz,sample5_L5,5,batch1
    sample5_exome_AGGCAGAA_L005_R2_001.fastq.gz.sample5_L5,5,batch1
    sample6_exome_TAAGGCGA_L004_R1_001.fastq.gz,sample6_L4,4,batch1
    sample6_exome_TAAGGCGA_L004_R2_001.fastq.gz,sample6_L4,4,batch1
    sample6_exome_TAAGGCGA_L005_R1_001.fastq.gz,sample6_L5,5,batch1
    sample6_exome_TAAGGCGA_L005_R2_001.fastq.gz,sample6_L5,5,batch1

I hope this represents a bug and helps improve this tool, rather than just me making a configuration error again :-). If I get chance I'll see if I can get a fix and I'll issue a pull request...

**Comment by schelhorn** [comment]
Provided that you have the latest `pybedtools`, that looks like a possible `pybedtools` error to me. The function where the error is raised looks like this:

```python
    def __add__(self, other):
        try:
            result = self.intersect(other, u=True)
        except BEDToolsError:
            # BEDTools versions <2.20 would raise BEDToolsError
            if (self.file_type == 'empty') or (other.file_type == 'empty'):
                result = pybedtools.BedTool("", from_string=True)
        return result
```

So if an exception is raised and the condition in the `except` clause is not met, `result` will be undefined and your error will be the result. Even if the main error is with bcbio somewhere, the `pybedtools` code is a bit sloppy in this particular method, IMO. So it might be best to escalate this upstream unless @chapmanb has a suggestion for debugging.

**Comment by danhalligan** [comment]
I can (and will) post this bug to pybedtools, and agree that that is the root cause of this issue. However, I guess there's also a chance that the arguments being provided to the function by bcbio are somehow garbled, in which case, it might also point to a bug in bcbio perhaps?

**Comment by chapmanb** [comment]
Dan;
Thanks for this report and pushing the report upstream. Sven-Eric, thanks for that suggestion.

I'm agreed that this is probably something we could handle/detect in bcbio. Practically it's trying to merge together intersecting regions where there is no mapping from the batches. I didn't think this could fail with empty BED files since we should always have places without mapping (Ns and what not) but maybe hg38 is really that good.

To debug a bit more, do all of the nblock files for the samples look okay?
```
ls -lh align/*/*nblocks.bed
```
Are there any empty files or otherwise very different samples that might indicate a problem?

Sorry to not have a better immediate suggestion but hopefully with some clues we'll be able to sort out ideas to reproduce this. Thanks much.

**Comment by danhalligan** [comment]
Hi Brad,

As far as I can tell the nblocks.bed files look OK, there is some variation in size but no major differences:

    [07:01 work]$ ls -lh align/*/*nblocks.bed
    -rw-r--r--. 1 dan dan 156M Sep  5 01:10 align/sample1_L4/4_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 156M Sep  5 01:42 align/sample1_L5/5_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 154M Sep  5 02:15 align/sample2_L4/4_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 154M Sep  5 02:46 align/sample2_L5/5_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 157M Sep  5 03:19 align/sample3_L4/4_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 157M Sep  5 03:53 align/sample3_L5/5_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 154M Sep  5 04:30 align/sample4_L4/4_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 154M Sep  5 05:07 align/sample4_L5/5_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 145M Sep  5 05:43 align/sample5_L4/4_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 145M Sep  5 06:17 align/sample5_L5/5_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 165M Sep  5 06:50 align/sample6_L4/4_2015-09-04_desc-sort-callable-nblocks.bed
    -rw-r--r--. 1 dan dan 165M Sep  5 07:26 align/sample6_L5/5_2015-09-04_desc-sort-callable-nblocks.bed

**Comment by chapmanb** [comment]
Dan;
I finally figured out the underlying issue here and it should now be fixed in the latest development version if you update with:
```
bcbio_nextgen.py upgrade -u development
```
The problem was that bedtools complained about HLA names in hg38, raising a naming check error. This error was swallowed by pybedtools and I didn't identify the bedtools intersection call since it was wrapped in the operator.add convenience function. The fix calls intersection explicitly and passes nonamecheck to avoid the issue.

Sorry it took me so long to wrap my head around the problem, and hope this fixes it for you.

**Comment by danhalligan** [comment]
Hi Brad - thanks so much for getting to the bottom of this. I haven't had chance to re run the pipeline here yet, but I'll try to pull the latest version and double check it all runs OK as soon as I get chance. Cheers!
