### ISSUE TITLE
Batch SA730 requires both tumor and normal BAM files for VarScan cancer calling

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#1003]
I'm seeing the error:
Batch SA730 requires both tumor and normal BAM files for VarScan cancer calling

I have all my libraries listed as tumor (they are cell lines).

**Comment by chapmanb** [comment]
Tyler;
Sorry about the issue. VarScan isn't a great choice for tumor-only calling as it really doesn't have a mode where it is calling somatic samples without matched normals.

We can feed tumor-only samples into VarScan germline calling, so I pushed a fix to make that happen so it won't error out. 

Practically, I'd call tumor-only with a different caller like VarDict or FreeBayes. Or use MuTect with a normal panel (the `background` option https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#variant-calling) if you have something suitable. Hope this helps.
