### ISSUE TITLE
Resource request for alignment part of RNASeq workflow does not include samtools

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1006]
I may be mistaken with this, but in the RNASeq pipeline in the alignment section, resources are only specified for the aligner (STAR in my case) and picard:

```python
with prun.start(_wres(parallel, ["aligner", "picard"],
                              ensure_mem={"tophat": 8, "tophat2": 8, "star": 2}),
```

However, when looking at what actually gets executed on the nodes during STAR alignment, it is obvious that STAR [pipes directly into samtools for sorting](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/star.py#L68). However, since the samtools memory is not specified to the parallel environment of the ipython cluster manager in the code shown above, running the workflow may result in terminated jobs if the cluster nodes do not have sufficient memory to also deal with the (unforeseen) samtools part of the pipe.

**Comment by schelhorn** [comment]
On second thought, bcbio may somehow incorporate that somewhere [here in the memory sharing hack for pipes](https://github.com/chapmanb/bcbio-nextgen/blob/c3e20b8c4baad46e938776ec30eb6490c217f793/bcbio/ngsalign/postalign.py#L43). But wouldn't that still affect STAR memory allocation since STAR requires a constant 30GB, independent of number of cores? I'd appreciate an explanation since I would like to hone in on what resources this step actually needs, and how that depends on the number of cores for STAR and samtools sorting.

**Comment by schelhorn** [comment]
Anyways, my STAR alignment jobs run over memory specs due to the missing samtools part and terminate, so the memory sharing hack does not seem to work well with STAR.

**Comment by schelhorn** [comment]
Alright, as a temporary fix I will increase the STAR memory reqs in my bcbio_system.yaml all so that it includes the factor 2 downscaled samtools memory reqs.

**Comment by roryk** [comment]
Hi @schelhorn,

Yeah, the calculation for when we're doing two things in the same step that might be memory intensive is not too smart. It figures out what each tool wants independently and picks whatever needs the largest amount of memory.  Increasing the memory requirement in STAR seems to make sense, it is just that the resulting value means the amount of memory STAR + whatever needs, rather than just STAR alone.

**Comment by roryk** [comment]
I added samtools to the aligner section for RNA-seq. I know it doesn't address the underlying issue but it is at least represented there now.

**Comment by schelhorn** [comment]
That'll be fine, thanks!
