### ISSUE TITLE
BAM sorting seems to run with default memory, resulting in significant performance loss

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1010]
It appears as if [BAM sorting](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/__init__.py#L341) currently runs with only the default memory of the respective binaries (`samtools` or `sambamba`, the latter of which usually has somewhat better performance). For `sambamba`, this default means only `512MB` summed over all threads, although the `samtools` resource environment with which both binaries run in bcbio usually allows `2GB` per thread (user configurable of course) - it's only that the binaries never get to learn this. This appears to be wasteful since `sambamba` (and perhaps `samtools`, too) are able to sort the whole BAM in-memory if enough memory is specified to them, with significant performance gains. 

Adding the memory reqs in the code linked above would be trivial using the `-m <MEM>G` flag for both binaries, IMO. One thing to watch out for is the different interpretation of memory flags for the two binaries: for `samtools`, memory is specified _per thread_, while for `sambamba`, memory is specified _summed over all threads_. Since the bcbio internal functions usually report memory per thread, this number would have to be multiplied by the number of threads for use in `sambamba` first.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the heads up. We can definitely add in respecting memory. For testing purposes -- are you running into slowdowns during disambiguation, or during RNA-seq? The variant calling alignment does use memory but is piped so is separate from this function, so we'd want to make sure the fix helps with your specific case. Thanks again.

**Comment by schelhorn** [comment]
During disambiguation within RNASeq, actually :) I hardcoded the memory reqs in, and it seems too make a noticeable difference.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks again for identifying the issue. I pushed a fix which should correctly use the memory specification for sorting here. Let us know if you run into any other problems. Thanks again.

**Comment by schelhorn** [comment]
Thanks, Brad - much appreciated.
