### ISSUE TITLE
sort problem

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1017]
I'm running centos 7.1 and it seems that with the version of coreutils (8.22) included sort is not working properly, bed files cannot be tabix-indexed. Bcbio-nextgen also gets it trouble for this reason when it makes use of the target.bed file. 

I'm reluctant to update coreutils to a newer version since it is not supported. However, running sort -V seems to solve the problem. If it does not break things in other systems, perhaps a good modification to bcbio-nextgen?

**Comment by parlar** [comment]
backported sort from coreutils 8.24, seems to work.

**Comment by chapmanb** [comment]
Pär;
Sorry about the issue, I believe there is a bug in sort in coreutils 8.22. There is more detail in this previous issue: #624 Unfortunately `-V` isn't supported widely on older coreutils so we can't use that as a workaround.

That's a bummer this is the default on CentOS 7.1. Do you know if it's going to be locked to this version of coreutils? If so, we could add a workaround when sort is used to specifically add `-V` if we find this version. Thanks much for the report on this.

**Comment by parlar** [comment]
Should make a bug report to redhat. I guess that they'll fix it eventually, the question is only how long it will take. 

Given the rigorous testing that rhel undergoes it's odd that this bug slipped through.

**Comment by chapmanb** [comment]
Pär;
Thanks for sending the bug report upstream. As a workaround for the current situation, I pushed a fix to use version-sort (`-V`) when available in the version of sort. This will provide better sorting and behanvior for recent sort versions and avoid the issue in 8.22. Thanks again.

**Comment by mdshw5** [comment]
I can confirm that this is still an issue for sort 8.4, but the -V flag works fine.

**Comment by chapmanb** [comment]
Thanks Matt. Hopefully we should be doing the right thing in bcbio now, thanks for letting us know about the scope of the issue.
