### ISSUE TITLE
Test_run / downsampeling parameter not picked up from sample yaml 

### ISSUE THREAD

**Issue by WimS83** [chapmanb/bcbio-nextgen#1019]
Hi, 

I am trying do to a test run on 60 paired end sequenced samples. 
bcbio accepts the sample yaml file below. But does not pick up on the test_run: true argument. 

If I cat the  /log/bcbio-nextgen-commands.log file I see in the bwa command that the original  files are being aligned.
/data/Projects/bcbio/workdir13/input/SAMPLE1_CGATGT_L002_R1_001.fastq.gz
/data/Projects/bcbio/workdir13/input/SAMPLE1_CGATGT_L002_R2_001.fastq.gz

And read alignment takes longer than expected for just 500.00 reads. I tried to specify test_run: true with upper case and lower case first letter (true or True). Both did not work. I tried to specify the test_run: true argument in other places of the yaml file, but this prevented bcbio from starting as it did not accept the yaml file. 

Is there something that I am missing / doing wrong? Or is there another way that I can do to make bcbio run in a test run / down-sampling mode? (without manual down sampling )

The input fastq.gz files are symlinked to another location.  

My samples yaml file looks like:

test_run: true
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    realign: false
    recalibrate: false
    variantcaller: freebayes
  analysis: variant2
  description: SAMPLE1_CGATGT_L002
  files:
  - /data/Projects/bcbio/workdir13/input/SAMPLE1_CGATGT_L002_R1_001.fastq.gz
  - /data/Projects/bcbio/workdir13/input/SAMPLE1_CGATGT_L002_R2_001.fastq.gz
  genome_build: GRCh37
- algorithm:
    aligner: bwa
    mark_duplicates: true
    realign: false
    recalibrate: false
    variantcaller: freebayes
  analysis: variant2
  description: SAMPLE1_TGACCA_L002
  files:
  - /data/Projects/bcbio/workdir13/input/SAMPLE2_TGACCA_L002_R1_001.fastq.gz
  - /data/Projects/bcbio/workdir13/input/SAMPLE2_TGACCA_L002_R2_001.fastq.gz
  genome_build: GRCh37
fc_date: '2015-09-16'
fc_name: project1
upload:
  dir: ../final

**Comment by chapmanb** [comment]
Sorry about the confusion. Unfortunately this parameter only works for RNA-seq runs, so you'd have to manually downsample for testing variant calling runs with small inputs. Hope that works for you.

@roryk, I know this option is useful for you -- what do you think the best long term strategy is? My preference would be to just remove this entirely to keep things simpler, but alternatively we could either document what pipelines it works with or try and also apply it to variant calling and small RNA analysis. Happy to do whatever you think works.

**Comment by roryk** [comment]
Thanks @chapmanb and @WimS83,

I agree Brad about simplifying, I removed the `test_run` option here: 5d6c53eb5f1db

Thanks!
