### ISSUE TITLE
rna-seq transcript fasta duplicated 

### ISSUE THREAD

**Issue by kspham** [chapmanb/bcbio-nextgen#1023]
in /bcbio/genomes/Hsapiens/GRCh37/rnaseq/tophat/GRCh37_transcriptome.fa
the transcript ENST00000361547 is duplicated multiple times.

**Comment by roryk** [comment]
Thanks @kspham,

Yup, you are right-- there are a couple of other transcripts that are duplicated as well. The Ensembl GTF file has some non-standard entries that I think are causing problems. Those entries are like this:

```
19	protein_coding	Selenocysteine	48283989	48283991	.	+	.	gene_id "ENSG00000178980"; transcript_id "ENST00000601048"; gene_name "SEPW1"; gene_source "ensembl_havana"; gene_biotype "protein_coding"; transcript_name "SEPW1-001"; transcript_source "havana"; tag "CCDS"; ccds_id "CCDS59402"; tag "seleno";
```

I have fixed the genome preparation script to remove these which should fix the issue, but it will be a little bit until the RNA-seq files get updated.

**Comment by roryk** [comment]
Hi @kspham,

I updated the GRCh37 RNA-seq files which fixes this issue. Thanks!
