### ISSUE TITLE
Why is the  --keep-geno argument given to vcfallelicprimitives? It leads to invalid vcf files?

### ISSUE THREAD

**Issue by WimS83** [chapmanb/bcbio-nextgen#1025]
Hi, 

Why is the  --keep-geno argument given to vcfallelicprimitives? 

The vcfallelicprimitives specifies that this is not the default behavior and that it  could lead to invalid vcf files.

-g, --keep-geno         Maintain genotype-level annotations when decomposing.  Similar
                            caution should be used for this as for --keep-info.

If I post process a vcf file using the same post processing tools / commands as bcbio does  I get an invalid vcf file.
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L108

The error I get by using vcf-validator from vcftools is:

Sample_03 at Chr_01:2068400 .. FORMAT tag [GL] expected different number of values (expected 3, found 10),FORMAT tag [AO] expected different number of values (expected 1, found 3),FORMAT tag [QA] expected different number of values (expected 1, found 3)

And this seems to be related to that the GL, AO and QA fields of the samples don't correspond anymore to the number of alternative alleles present in the ALT column.  

The original variant was 
Chr_01  2068400        .       ATGTTTTTC       CTATTGTTT,CTATTGTTC,ATATTGTTC
and after vcfallelicprimitives the variant is 
Chr_01  2068400        .       A       C
but the genotypes GL, AO and QA values don't correspond anymore. 

Or does bcbio do something more downstream to bring the genotype values in correspondence with the variant alleles again?

**Comment by chapmanb** [comment]
Thanks for the details writeup about the issues you're running into. We use `--keep-geno` as an imperfect choice when trying to decompose larger variants. Without it we lose all genotype annotations, which isn't great, and with it you have the possibility of getting incorrect decomposition. We haven't been running into issues with the bcbio output so happy to try and dig into this.

Are the problem variants you ran into out of bcbio, or a separate custom pipeline? Are downstream tools complaining about them, or were you just checking the VCF with vcf-validator? Sometimes with VCF it's worth being practical as trying to bring everything into perfect spec can be a lot of work. If you can put together an example of an input and problem output we could try to dig more. Hope this helps.

**Comment by WimS83** [comment]
For now I ran the Freebayes command and the post processing steps outside of bcbio. 

The original variant and the first two samples were
Chr_01 2068400 . ATGTTTTTC CTATTGTTT,CTATTGTTC,ATATTGTTC

GT:GQ:DP:RO:QR:AO:QA:GL   .       

1/3:1.26014e-09:22:4:148:9,4,4:332,147,148:-10,0,-10,-10,-0.0911111,-10,-10,0,-10,-10

1/2:135.313:28:3:111:12,9,4:442,320,148:-10,-10,-10,-10,0,-10,-10,-10,-10,-10


After vcfallelicprimitives with --keep-geno the (first) variant is 
Chr_01 2068400 . A C

GT:GQ:DP:RO:QR:AO:QA:GL

.:.:.:.:.:.:.:.

1|0:1.26014e-09:22:4:148:9,4,4:332,147,148:-10,0,-10,-10,-0.0911111,-10,-10,0,-10,-10


After vcfallelicprimitives without --keep-geno the (first) variant is 

Chr_01  2068400        .       A       C       

GT 
    
.   
  
1|0       


So the trade made here is that you still have a usable GQ:DP:RO:QR fields, but that the AO:QA:GL fields are some what  invalid after specifying --keep-geno as an argument. 

We make use downstream of the AO values (alternative allele counts).

For variants converted to primitives we now can't depend anymore on that the number of alternative alleles is equal to the number of alternative allele counts. 

At least I know understand the imperfect choice made and we will see if we can find a work around. 

Thanks!

**Comment by chapmanb** [comment]
Thanks for the details. If we can find tools that do a better job of this allelic primitive decomposition while maintaining all of the fields correctly I'd be happy to test and sub them in. Glad you can find a workaround downstream and thanks again.

**Comment by NeillGibson** [comment]
Hi Brad,

Could you please pass the -t argument to vcfallelicprimitives in the freebayes variant calling pipe:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L125

This will tag the decomposed variants and make it easier to handle them correctly downstream.  I guess an info field will be created. 

```
vcfallelicprimitives -h
usage: vcfallelicprimitives [options] [file]

options:
    -m, --use-mnps          Retain MNPs as separate events (default: false).
    -t, --tag-parsed FLAG   Tag records which are split apart of a complex allele with this flag.
    -L, --max-length LEN    Do not manipulate records in which either the ALT or
                            REF is longer than LEN (default: 200).
    -k, --keep-info         Maintain site and allele-level annotations when decomposing.
                            Note that in many cases, such as multisample VCFs, these won't
                            be valid post-decomposition.  For biallelic loci in single-sample
                            VCFs, they should be usable with caution.
    -g, --keep-geno         Maintain genotype-level annotations when decomposing.  Similar
                            caution should be used for this as for --keep-info.
```

Thank you !
