### ISSUE TITLE
eXpress is forced to sort BAM with single core in RNA-Seq pipeline

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1028]
In the RNA-Seq pipeline in the step [`rnaseqcount-singlethread`](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/main.py#L322), the parallel environment is forced to operate on a single core only (`max_multicore=1`). However, the eXpress module which is active under that parallel environment will then inherit the latter for [BAM sorting](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/express.py#L78), which then will happen with using only a single core (and the corresponding low amount of RAM). For larger input files, this is now a limiting step in running eXpress. It would be very convenient if we somehow could move that eXpress BAM sorting back into a multicore environment, perhaps by placing it into the parallel workflow step before (since if the file is already existing then bcbio will not sort it again in the later workflow step).

**Comment by roryk** [comment]
Hi @schelhorn,

Good catch, I'm doing some maintenance on the RNA-seq stuff and I'll fix this when I'm doing that this week. Thanks for all of your feedback, it is so awesome.

**Comment by schelhorn** [comment]
Great, thanks a lot!

**Comment by schelhorn** [comment]
I had a look at this issue again and the solution seems to be even simpler. Since running `eXpress` requires [transcriptome alignment](https://github.com/chapmanb/bcbio-nextgen/blob/bf6185d1edc6be491219c059747fbd4b00aae49e/bcbio/ngsalign/bowtie2.py#L132), and transcriptome alignment is only required by `eXpress` and no other tool in bcbio, we could just make queyrname-sorted BAM output the default for transcriptome alignment (perhaps even as part of the piped command line linked above in order to avaoid the temporary file). Since transcriptome alignment in the `rnaseq` workflow already is part of a multicore parallel environment which includes samtools this should work just fine. Also, the [code running `eXpress`](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/express.py#L78) won't sort again if the input already is queryname-sorted, so we wouldn't even need to do any other changes to the `eXpress` code. Does that make sense?

**Comment by schelhorn** [comment]
Found another issue with eXpress, and a solution. Perhaps you could also look into that, @roryk. When re-running bcbio from a stopped run, the gtf-to-fasta processing is redone everytime even if the eXpress outputs are already existing. There is a simple solution, however: just put the line

```python
gtf_fasta = gtf.gtf_to_fasta(dd.get_gtf_file(data), dd.get_ref_file(data))
```

in [express.py](https://github.com/chapmanb/bcbio-nextgen/blob/30c48f194a2031986b57cf210cc2e37fea9ae2c0/bcbio/rnaseq/express.py#L21) under the `if not file_exists(out_file):` condition a few line below.

**Comment by schelhorn** [comment]
One last issue with `rna-seq` workflow: right now, only a limited number of `qc` results are generated for it, in contrast to `variant2` where the `bamtools` `qc` step adds some important information, such as the number of reads analyzed and so forth. This is a result of the fact that for `wna-seq`, `qualimap` runs in rnaseq mode which seems to include fewer statistics. So I added bamtools stats to `rnaseq` `qc` to add the missing stats. There practically is no overhead, so I suggest it make sense to make this modification the default in [qcsummary.py](https://github.com/chapmanb/bcbio-nextgen/blob/0e70b301248c1acb4675832c6173dd10bc40e961/bcbio/pipeline/qcsummary.py#L114):

```python
if data["analysis"].lower().startswith("rna-seq"):
        to_run.append(("qualimap", _rnaseq_qualimap))
        to_run.append(["bamtools", _run_bamtools_stats])
```

**Comment by roryk** [comment]
Thanks @schelhorn,

Sorry for the delay in getting to this. Your suggestions were right on, thanks so much. We take pull requests too-- for so many of your awesome suggestions you do all of the work to implement them, might as well get proper github credit. :)

**Comment by schelhorn** [comment]
Excellent, @roryk, thank you very much.

I'd love to make your work easier by submitting PRs since I test most suggested changes in our setup first anyway and have some other shiny add-ons to bcbio that I would love to share. However I am currently unable to do so due to internal processes within my organization. I assume that will change in the near future, but until then I have to do QC this way and pester you with bug reports.

**Comment by roryk** [comment]
haha-- gotcha, I was wondering.
