### ISSUE TITLE
Is it possible to run a mapping only, or variant calling only pipeline?

### ISSUE THREAD

**Issue by WimS83** [chapmanb/bcbio-nextgen#1030]
Hi,

The freebayes variant call pipeline by default does mapping and variant calling when applied to a set of fastq files. 

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/freebayes-variant.yaml

Is it possible to run the freebayes germline variant calling pipeline up to and including the step of of mark duplicate reads?

I deleted the 
variantcaller: freebayes
entry from the freebayes template yaml file but this led to gatk being chosen as the default variant caller. 

Should I specify something like
variantcaller: None
or 
variantcaller: false

Or do something else?

I could not find any mapping only template yaml file. Or something else to refer to in the analysis section:
analysis: variant2

I also have a  related question. Is it possible to start with a set of (duplicates marked) bam files and just run the variant calling part of the freebayes pipeline (ie distributed variant calling + post processing + merge)?

Or will this convert the bam files first to fastq files and start the whole alignment + variant calling pipeline?

Thanks!

**Comment by chapmanb** [comment]
You can skip steps in the pipeline by setting the tools to false. So to do without variantcalling:
```
variantcaller: false
```
and without alignment:
```
aligner: false
```
There is more documentation on using pre-aligned BAMs here:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#alignment

Hope this helps
