### ISSUE TITLE
LB tag for Readgroups

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1032]
Maybe this is a non-offcial @RG tag, but I was wondering if there was any way of adding 'LB' through bcbio alignment? I work with a number of smaller targeted capture DNA-seq projects and would usually include an design identifier in the readgroups. I did not see an option for this in the documentation. 
Could I modify the PU tag as well? The default behavior Im seeing is to set PU to the sample id, but perhaps I have my yamls set up oddly. Thank you

**Comment by chapmanb** [comment]
Brad;
Thanks for the suggestion. I pushed updates to the latest development version that support setting LB and PU through fields in the `metadata` section. I updated the documentation here to provide more clarity about the settings and how they change read groups:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#sample-information

Please let us know if you run into any issues and thanks again.
