### ISSUE TITLE
Suitability for non-human and non-model organisms?

### ISSUE THREAD

**Issue by travc** [chapmanb/bcbio-nextgen#1033]
Apologies for the very general question, but before I start really digging into bcbio-nexgen I really want to know...
How suitable is it for non-model organisms or even just non-human?

I find myself re-inventing the wheel too often, and would like to use more-or-less standardized tools and pipelines.  But very often find that there are embedded (often implicit) assumptions which restrict their applicability.

**Comment by chapmanb** [comment]
Travis;
Absolutely, we'd love to have more contributors using bcbio on non-human/non-model organisms. Practically most of the work our group does is on human, mouse, rat so tools definitely gets the most attention and testing on those genomes. However, there is no attempt to limit analyses to human only and we'd be happy to merge fixes if you find issues on other genomes. We include several other genomes as well as a script to add new organisms:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/code.html#adding-new-organisms

and I know have users doing processing on non-human samples.

Thanks for considering using bcbio. It's great to have a diversity of contributors and makes the analysis tools better.

**Comment by mjafin** [comment]
Hi Travis,
I've used bcbio with Mfascicularis for which there is basically just the assembly (with thousands and thousands of unlocalised etc contigs that can give you a headache in some of the tools) and snpeff. To make bcbio work I had to forge a false, empty dbsnp vcf file and that was pretty much it. I also of course built the bwa and STAR indices and for the STAR index I downloaded the gene gtf that's available.

**Comment by roryk** [comment]
@travc, you can install any genome and annotation and use it with bcbio-nextgen, though there may be some trickiness with the genome like @mjafin mentioned. You can make the indices and install the genomes with the `bcbio_setup_genome.py` script here:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#adding-custom-genomes

**Comment by travc** [comment]
Thanks for the info.  It looks promising enough to dig into. 

That said... I'm not expecting to be able to just 'turn the crank'.
We done even have gene annotations in some cases, so obviously that rules out snpEff and a lot of other analyses.  To run those species, I'll probably have to disable big chunks of the workflow and tweak other bits to run in a more naive mode.  Also, our 'good' reference is actually from a hybrid of two species, and portions map much better to one or the other but not both.  It is pretty much a mess.

**Comment by roryk** [comment]
Hi @travc,

Thanks, hope this got you started. Closing this for now just to clean up our issue list. Feel free to reopen if you run into any issues.
