### ISSUE TITLE
run MutusigCV and inVEx in bcbio

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1036]
Hi Brad, I have one question, Do you plan to add MutsigCV and/or InVEx in the variant call pipeline?

as an alternative would be possible to run MuTect with the option --coverage_file example.coverage.wig.txt so that the coverage file required by InVEx and MutsigCV is generated?

Thanks!

Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks much for the discussion. We don't have plans to incorporate these right now. They're both useful tools but MutsigCV is Matlab based so not a great target for automated runs, and InVEx has a non-commercial restricted distribution license which makes it a challenge to integrate.

If you'd like wig coverage output from MuTect we could add a `tools_on: [mutect_coverage]` flag that adds this option. The wig file will likely be quite large so we wouldn't want to add it by default. If you'd be willing to tackle this we'd be happy to pull in a PR for it. Thanks again for all the ideas.

**Comment by apastore** [comment]
Sure You are definitive right. I will see how to integrate the mutect coverage file.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
