### ISSUE TITLE
amplicon deep-seq and mark duplicate

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1038]
Hi, have a question is possible to skip the mark duplicate step with amplicon seq in the Variant2 pipeline?

I would like to compare the call with and without duplicate flag.

Thanks!

**Comment by chapmanb** [comment]
Yes absolutely, you want to add `mark_duplicates: false` to your configuration file:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#variant-calling

Hope this helps.
