### ISSUE TITLE
FreeBayes: {opts} needs to be before {input_bams}

### ISSUE THREAD

**Issue by nh13** [chapmanb/bcbio-nextgen#1040]
Given the command line usage shown in freeBayes, I think some of the command line options are never being given to freebayes correctly.  See https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L108
Currently:
```            cmd = ("{freebayes} -f {ref_file} {input_bams} {opts} | "```
Should be:
```            cmd = ("{freebayes} -f {ref_file} {opts} {input_bams} | "```

**Comment by chapmanb** [comment]
Nils -- thanks for this. I don't believe FreeBayes is sensitive to input order here, since `{inputs_bams}` are also specified with options (`-b file.bam`) but I agree that it's good practice to put the options first. Thanks again.
