### ISSUE TITLE
Python function os.rename() leads to [Errno 18] Cross-device link on certain file systems such as encrypted devices

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1047]
We recently started to encrypt the node-local `/tmp` devices for regulatory compliance (speed loss is minimal) on our Ubuntu Linux nodes. This leads to some issues with the use of `os.rename()` in bcbio, which isn't able to "rename" (i.e., move) files across certain devices, encrypted ones being one of them. In these cases, a `[Errno 18] Cross-device link` exception is raised. In particular, I get failures in the [callable regions calculations](https://github.com/chapmanb/bcbio-nextgen/blob/27efc75d07045af837342528a21b173320262929/bcbio/bam/callable.py#L66), but `os.rename()` is used all over the place. 

Depending on the setup, bcbio users may have different file systems for local `/tmp` and the global working directory for all manner of reasons, and these file systems may or may not be different devices from the perspective of `os.rename()`.

A simple way out of this is by using `shutil.move()` as a drop-in replacement for `os.rename()`. `shutil.move()` is smarter and more robust and emulates the actions of the `mv` command on the shell, while `os.rename()` does not.

From the Python 2.7 docs:

> `os.rename()`: Rename the file or directory src to dst. If dst is a directory, OSError will be raised. On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. **The operation may fail on some Unix flavors if src and dst are on different filesystems.**

>  `shutil.move()`: If the destination is an existing directory, then src is moved inside that directory. If the destination already exists but is not a directory, it may be overwritten depending on os.rename() semantics. **If the destination is on the current filesystem, then os.rename() is used. Otherwise, src is copied to dst using copy_function and then removed.**

I therefore strongly suggest that bcbio uses `shutil.move()` instead of `os.rename()` _globally_ in the source code. The only thing to watch out for in principle is that if the destination is a directory,  `os.rename()` will raise an exception while `shutil.move()` will silently move the file into that existing directory. However, since `os.rename()` did not fail due to existing directories before I assume that does not pose a problem anywhere in bcbio and replacing `os.rename()` with `shutil.move()` is semantically safe.

**Comment by roryk** [comment]
Thanks @schelhorn, good catch, you are right. I replaced all os.rename calls with shutil.move. Thanks so much.

**Comment by schelhorn** [comment]
Great, thanks!

**Comment by schelhorn** [comment]
@roryk, bcbio.bam.callable.py still contains a os.rename()...

**Comment by guillermo-carrasco** [comment]
I was with my hands on the keyboard just now. I pushed a fix @schelhorn :)

**Comment by schelhorn** [comment]
Thanks!

**Comment by roryk** [comment]
Thanks @guillermo-carrasco
