### ISSUE TITLE
samtools error on CentOS bcbio 0.9.4a

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1063]
Hi I had to upgrade to the develop version of bcbio since I was interested in SV calling and now I am getting this error. Do you have any suggestions? (I have recompile samtools from github and is working fine)

Thanks!
-bash-4.1$ samtools
samtools: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by samtools)
samtools: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by samtools)

-bash-4.1$ cat /etc/*-release
CentOS release 6.4 (Final)
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
CentOS release 6.4 (Final)
Rocks release 6.1 (Emerald Boa)
CentOS release 6.4 (Final)

**Comment by chapmanb** [comment]
Sorry about the issues. I re-built the samtools and bcftools conda packages, from the `bioconda` repository we're switching over to and they should now be compatible with CentOS. If you do `bcbio_nextgen.py upgrade --tools` or `/path/to/bcbio/anaconda/bin/conda install -c bioconda samtools bcftools` to get the latest packages. Hope this fixes it for you.
