### ISSUE TITLE
dbsnp reference file download fails

### ISSUE THREAD

**Issue by sidiropoulos** [chapmanb/bcbio-nextgen#1066]
Hi,

I'm installing bcbio_nextgen using the "Isolated installations" instructions (https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations).
The genome installation for either GRCh37 or hg19 produces the following error:

[localhost] local: mkdir -p /home/people/nikossi/software/bcbio_nextgen/genomes/Hsapiens/hg19/variation
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/home/people/nikossi/tmp/cloudbiolinux/6621947b-0955-3422-a9da-44e4cd2046d9'
[localhost] local: wget --continue --no-check-certificate -O dbsnp_138.hg19.vcf.gz 'ftp://gsapubftp-anonymous:@ftp.broadinstitute.org/bundle/2.8/hg19/dbsnp_138.hg19.vcf.gz'
--2015-10-19 15:55:40--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/hg19/dbsnp_138.hg19.vcf.gz
           => 'dbsnp_138.hg19.vcf.gz'
Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ...
Login incorrect.

Warning: local() encountered an error (return code 6) while executing 'wget --continue --no-check-certificate -O dbsnp_138.hg19.vcf.gz 'ftp://gsapubftp-anonymous:@ftp.broadinstitute.org/bundle/2.8/hg19/dbsnp_138.hg19.vcf.gz''

Happens both when I ran:
python bcbio_nextgen_install.py /path_to_bcbio --tooldir=/path_to_bcbio --isolate \
   --genomes GRCh37 --aligners bwa --aligners bowtie2 --aligners rtg --distribution centos 

and later when I installed without the '--genomes' parameter:

bcbio_nextgen.py upgrade --genomes hg19 (or GRCh37)

Do you have any ideas on how to work around it?

Bests,
Nikos

**Comment by chapmanb** [comment]
Nikos;
Sorry about the problem. The download is trying to retrieve files from the Broad GATK server and it looks like right now it has too many users. Unfortunately the FTP only allows 25 concurrent users. You can see more details here:

http://gatkforums.broadinstitute.org/discussion/1215/how-can-i-access-the-gsa-public-ftp-server

My best suggestion is to wait a bit and retry and hopefully it'll be available. You can just retry the wget command (or click on the link on the GATK page above) to test, and then re-run the install command whenever it works again. Sorry to not have a better solution than waiting and checking but hope this helps.

**Comment by sidiropoulos** [comment]
It is very helpful indeed, I wouldn't have guessed it otherwise. 
Thank you!
