### ISSUE TITLE
Failed to open BAM file stdin

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1071]
Hi,

When I was running bcbio tumor-normal paired pipline for exom-seq data, there was the following error. Can you help me to debug it? I was using cluster HPC computers.
Thank you.

[2015-10-21T09:25Z] *.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; ./bcbio/bin/sambamba view -F 'mapping_quality > 0' -L ./project/work/align/sample1/9_2015-10-20_project-merged-sort-callable-split/9_2015-10-20_project-merged-sort-GL000207.1-callable-coverageregions.bed -f bam -l 1 ./project/work/align/sample1/9_2015-10-20_project-merged-sort.bam | ./bcbio/anaconda/bin/bedtools genomecov -split -ibam stdin -bga -g ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa.fai > ./project/work/align/sample1/9_2015-10-20_project-merged-sort-callable-split/tx/tmpAcnZ89/9_2015-10-20_project-merged-sort-GL000207.1-callable-genomecov.bed
/util/opt/lmod/lmod/init/bash: fork: retry: Resource temporarily unavailable
/util/opt/lmod/lmod/init/bash: fork: retry: Resource temporarily unavailable
/util/opt/lmod/lmod/init/bash: fork: retry: Resource temporarily unavailable
/util/opt/lmod/lmod/init/bash: fork: retry: Resource temporarily unavailable
/util/opt/lmod/lmod/init/bash: fork: Resource temporarily unavailable
sambamba-view: Error creating thread
Failed to open BAM file stdin
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issues. It looks like you're running out of available file handles on the compute node so bcbio is unable to get resources for running the piped command line. The best way to fix this is to increase the available file handles on the machine. More details are available in the docs here:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html#open-file-handles

Hope this helps.

**Comment by pengxiao78** [comment]
Hi,
I ran the ulimit -a in the slurm file in our cluster computer and found the following statistics. Actually, we have open file limits of 16384. Is that still not enough? Could you give me a large enough number? Or there is other problem?
Thank you.
Peng

core file size (blocks, -c) 0
data seg size (kbytes, -d) unlimited
scheduling priority (-e) 0
file size (blocks, -f) unlimited
pending signals (-i) 2065825
max locked memory (kbytes, -l) unlimited max memory size (kbytes, -m) 2097152 open files (-n) 16384 pipe size (512 bytes, -p) 8 POSIX message queues (bytes, -q) 819200 real-time priority (-r) 0 stack size (kbytes, -s) unlimited cpu time (seconds, -t) unlimited max user processes (-u) 1024 virtual memory (kbytes, -v) unlimited file locks (-x) unlimited

**Comment by chapmanb** [comment]
Thanks for the details. It looks like your `-n` setting for open files is fine -- that should be plenty of available file handles. The one issue I can spot from this is `ulimit -u` -- This is set to 1024 which can be limiting. The docs have a bit more details but you could check `ulimit -Hu`. bcbio tries to increase the limit to avoid problems but if you hard limit is also set at 1024 this can be an issue. If that's the case, increasing the hard limit would let bcbio adjust it and avoid problems. Hope this helps.

**Comment by pengxiao78** [comment]
Could you also give me an idea of a specific hard limit number that we can increase to avoid problems? Thank you!

**Comment by chapmanb** [comment]
bcbio tries to set it to 10240, which seems to work well for most runs. Hope this helps.

**Comment by pengxiao78** [comment]
I have updated bcbio into 0.9.4 and also increased the hard limit into 4224 but found the following error. Should I further increase the limit or is this the new problem? Thank you.
 
Index BAM file: 3_2015-10-20_project-merged-sort-1_142545271_173563443-prep.bam
2015-10-26 23:28:37.131 [IPClusterStop] Using existing profile dir: u'./project/work/log/ipython'
2015-10-26 23:28:37.140 [IPClusterStop] Stopping cluster [pid=3900] with [signal=2]
2015-10-26 23:28:38.299 [IPClusterStop] Using existing profile dir: u'./project/work/log/ipython'
2015-10-26 23:28:38.307 [IPClusterStop] Stopping cluster [pid=3900] with [signal=2]

0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
2 Engines running
Sending a shutdown signal to the controller and engines.

0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
0 Engines running
96 Engines running
Sending a shutdown signal to the controller and engines.
Traceback (most recent call last):
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 80, in _run_toplevel
    for xs in pipeline.run(config, run_info_yaml, parallel, dirs, samples):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 160, in run
    samples = region.parallel_prep_region(samples, run_parallel)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/region.py", line 127, in parallel_prep_region
    "piped_bamprep", _add_combine_info, file_key, ["config"])
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 59, in parallel_split_combine
    split_output = parallel_fn(parallel_name, split_args)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 135, in run
    for data in view.map_sync(fn, items, track=False):
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 353, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-140>", line 2, in map
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 54, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-139>", line 2, in map
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 39, in save_ids
    ret = f(self, *args, **kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1119, in map
    return pf.map(*sequences)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 268, in map
    ret = self(*sequences)
  File "<decorator-gen-119>", line 2, in __call__
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 75, in sync_view_results
    return f(self, *args, **kwargs)
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 251, in __call__
    return r.get()
  File "./bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 104, in get
    raise self._exception
ipyparallel.error.CompositeError: one or more exceptions from call to method: piped_bamprep
[Engine Exception]EngineError: Engine '52424b70-60dd-48b6-942a-a82160b9996b' died while running task '9e5bab1d-b11c-4444-b2f7-a35b0fa02d77'
Exception in thread Thread-1 (most likely raised during interpreter shutdown):

**Comment by chapmanb** [comment]
Sorry about the continued problems. It's not possible to diagnose the underlying issue from this traceback since it only tells us something failed during one of the `piped_bamprep` steps. The actual error is hopefully present in `log/bcbio-nextgen.log` and would provide more information about what is failing so we can determine if it's the same issue or something different. Thanks for helping to debug.

**Comment by pengxiao78** [comment]
Unfortunately, I checked both bcbio-nextgen.log and bcbio-nextgen-debug.log files and did not find any error information.

**Comment by chapmanb** [comment]
Sorry about the lack of useful error messages. If you re-run with a single core (`bcbio_nextgen.py -n 1`) does it produce a useful error or run cleanly? It's possible you ran into one off memory issues or something else, but it's hard to guess without being able to find the underlying error. Fingers crossed that a re-run works cleanly or provides more information.

**Comment by pengxiao78** [comment]
After a re-run, I found the following error in bcbio-nextgen.log. Is it be helpful?

[2015-10-31T17:37Z] *.edu: Unexpected error
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 44, in _setup_logging
    yield config
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 260, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 252, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 78, in run_vardict
    assoc_files, region, out_file)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/vardict.py", line 283, in _run_vardict_paired
    do.run(cmd.format(**locals()), "Genotyping with VarDict: Inference", {})
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; export VAR_DICT_OPTS='-Xms750m -Xmx3000m -XX:+UseSerialGC -Djava.io.tmpdir=./project/work/vardict/16/tx/tmpSPkvPZ' && vardict-java -G ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 10823FFPE -b "./project/work/bamprep/10823FFPE/16/3_2015-10-29_project-merged-sort-16_0_31019432-prep.bam|./project/work/bamprep/10823Germ/16/4_2015-10-29_project-merged-sort-16_0_31019432-prep.bam" -c 1 -S 2 -E 3 -g 4 ./project/work/vardict/16/batch15-16_0_31019432-raw-regions-regionlimit.bed | testsomatic.R | var2vcf_paired.pl -M -P 0.9 -m 4.25 -f 0.1  -N "10823FFPE|10823Germ" | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null |  ./bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")' | sed 's/\\.*Somatic\\/Somatic/' | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/' | ./bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' |  awk -F$'\t' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}' | ./bcbio/bin/vcfstreamsort | bgzip -c > ./project/work/vardict/16/tx/tmpSPkvPZ/batch15-16_0_31019432-raw.vcf.gz
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
/bin/bash: line 1: 43551 Done                    vardict-java -G ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -f 0.1 -N 10823FFPE -b "./project/work/bamprep/10823FFPE/16/3_2015-10-29_project-merged-sort-16_0_31019432-prep.bam|./project/work/bamprep/10823Germ/16/4_2015-10-29_project-merged-sort-16_0_31019432-prep.bam" -c 1 -S 2 -E 3 -g 4 ./porject/work/vardict/16/batch15-16_0_31019432-raw-regions-regionlimit.bed
     43552                       | testsomatic.R
     43553                       | var2vcf_paired.pl -M -P 0.9 -m 4.25 -f 0.1 -N "10823FFPE|10823Germ"
     43554                       | bcftools filter -m '+' -s 'REJECT' -e 'STATUS !~ ".*Somatic"' 2> /dev/null
     43555 Segmentation fault      | ./bcbio/anaconda/bin/py -x 'bcbio.variation.vardict.depth_freq_filter(x, 0, "bwa")'
     43556                       | sed 's/\\.*Somatic\\/Somatic/'
     43557                       | sed 's/REJECT,Description=".*">/REJECT,Description="Not Somatic via VarDict">/'
     43558                       | ./bcbio/anaconda/bin/py -x 'bcbio.variation.freebayes.call_somatic(x)'
     43559                       | awk -F'	' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}'
     43560                       | awk -F'	' -v OFS='\t' '$1!~/^#/ && $4 == $5 {next} {print}'
     43561 Aborted                 | ./bcbio/bin/vcfstreamsort
     43562                       | bgzip -c > /project/work/vardict/16/tx/tmpSPkvPZ/batch15-16_0_31019432-raw.vcf.gz
' returned non-zero exit status 134

**Comment by chapmanb** [comment]
Thanks for following up with more details. This looks like a separate error that occurs during variant calling. Perhaps your previous error was non-reproducible, which can happen with network/filesystem/memory strangeness. 

Practically, this current error is also often a one-off errors caused by Java segfaulting or being unhappy.  If you re-run does it fail at the same point consistently?

Sorry to not have better answers than "please try running it again" but sometimes that's unfortunately the best answer. Hopefully a re-run gets your analysis finished cleanly.

**Comment by pengxiao78** [comment]
Yes, re-run did work. The running has finished successfully. Thanks!
