### ISSUE TITLE
left align

### ISSUE THREAD

**Issue by hurchu** [chapmanb/bcbio-nextgen#1072]
Hi, I'm wondering how you perform left align to normalize the vcf files, GATK or bcftools.
For example, in GATK, there are two options to split and trim. 

--splitMultiallelics / -split
Split multiallelic records and left-align individual alleles
If this argument is set, split multiallelic records and left-align individual alleles. If this argument is not set, multiallelic records are not attempted to left-align and will be copied as is.

--trimAlleles / -trim
Trim alleles to remove bases common to all of them
If this argument is set, bases common to all alleles will be removed, leaving only their minimal representation.

Thank you very much!

Best

**Comment by chapmanb** [comment]
Thanks for the question. We use `vt normalize` to normalize and left align calls:

http://genome.sph.umich.edu/wiki/Variant_Normalization
http://genome.sph.umich.edu/wiki/Vt#Normalization

Some callers, like GATK HaplotypeCallers do this internally as part of the process but we apply it for those that don't. Hope this helps.

**Comment by hurchu** [comment]
Thanks!

On Thu, Oct 22, 2015 at 1:35 PM, Brad Chapman <notifications@github.com>
wrote:

> Thanks for the question. We use vt normalize to normalize and left align
> calls:
>
> http://genome.sph.umich.edu/wiki/Variant_Normalization
> http://genome.sph.umich.edu/wiki/Vt#Normalization
>
> Some callers, like GATK HaplotypeCallers do this internally as part of the
> process but we apply it for those that don't. Hope this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chapmanb/bcbio-nextgen/issues/1072#issuecomment-150332318>
> .
>



-- 
Junfei Zhu
