### ISSUE TITLE
Installation failed because of metadata 404 error

### ISSUE THREAD

**Issue by chdem** [chapmanb/bcbio-nextgen#1074]
Hello,

I have pretty the same error than the #528 issue but I can't resolve it.

Using the last installation script version, I've got this error :
```
Fetching package metadata: ...Error: HTTPError: 404 Client Error: NOT FOUND: https://conda.binstar.org/bioconda/linux-64/
```
Link is broken. seems to be https://conda.anaconda.org/bioconda/linux-64 now

In 528 issue, a sed command on /usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bcbio/install.py seems to be enought.
Unfortunatly, I do not have any file like this !
:(

**Comment by chapmanb** [comment]
Sorry about the problems. What version of bcbio are you running? They recently switched from binstar.org to anaconda.org and we should have removed all of the references to the latest release. Does running:
```
bcbio_nextgen.py upgrade -u development
````
fix the issue? If not, could you provide the full traceback? That would help isolate the source of the problem and I might be able to suggest a workaround.

**Comment by chdem** [comment]
I was able to install by changing the line 204 in bcbio_nextgen_install.py :
```
channels = ["-c", "https://conda.anaconda.org/bcbio", "-c", "https://conda.anaconda.org/bioconda"]
```
Don't know if it was a good way to make a correction but it works !


Everything's good for the installation. I've problems with genome downloading now but it will be a new issue !

Thank you Brad !

**Comment by chapmanb** [comment]
Glad it's working now. Those fixes should be in the latest bcbio_nextgen_install.py for any future installations. Thanks much for letting us know about the solution.
