### ISSUE TITLE
Test suite errors

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1077]
Hi,
I ran the test suite by the following three commands in the version 0.9.3,
$ git clone https://github.com/chapmanb/bcbio-nextgen.git
$ cd bcbio-nextgen/tests
$ ./run_tests.sh
and found the following two errors after running. Could you give me any suggestions to fix them?
Thank you.

======================================================================
ERROR: Test variant calling with GATK pipeline.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bcbio/bcbio-nextgen/tests/test_automated_analysis.py", line 273, in test_1_variantcall
    subprocess.check_call(cl)
  File "./bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bcbio_nextgen.py', './bcbio/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', './bcbio/bcbio-nextgen/tests/data/automated/../100326_FC6107FAAXX', './bcbio/bcbio-nextgen/tests/data/automated/run_info-variantcall.yaml']' returned non-zero exit status 1

======================================================================
ERROR: Allow BAM files as input to pipeline.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bcbio/bcbio-nextgen/tests/test_automated_analysis.py", line 285, in test_5_bam
    subprocess.check_call(cl)
  File "./bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['bcbio_nextgen.py', './bcbio/bcbio-nextgen/tests/test_automated_output/bcbio_system.yaml', './bcbio/bcbio-nextgen/tests/data/automated/run_info-bam.yaml']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 11 tests in 266.138s

FAILED (errors=2)

**Comment by chapmanb** [comment]
Sorry about the error problems. Unfortunately there isn't enough information in these error messages to diagnose the underlying issue. We'd need to be able to see the traceback from where the individual tests failed during the run.

Practically, the tests track the latest releases and development. My suggestion would be to upgrade to the latest release:
```
bcbio_nextgen.py upgrade -u stable --tools --data
```
which will hopefully resolve the problem. Hope this fixes it for you.

**Comment by pengxiao78** [comment]
Hi,
I used the command 
bcbio_nextgen.py upgrade -u stable --tools --data
to upgrade bcbio but found the follow error. Could you help me to debug it?
Thanks.

Running GGD recipe: sranseq
Traceback (most recent call last):
  File "./bcbio/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 98, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 257, in upgrade_bcbio_data
    cbl_deploy.deploy(s)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
    configure_instance(options, actions)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
    setup_biodata(options)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
    install_proc(options["genomes"], ["ggd", "s3", "raw"])
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 350, in install_data
    _prep_genomes(env, genomes, genome_indexes, ready_approaches)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 477, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 767, in _install_with_ggd
    ggd.install_recipe(env.cwd, recipe_file)
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"])
  File "./bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "./bcbio/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', './bcbio/genomes/Mmusculus/mm10/txtmp/ggd-run.sh']' returned non-zero exit status 4

**Comment by lpantano** [comment]
Hi,

it seems there is an error with the srnaseq annotation data.
Could you try to run that command alone to see if you get some error?

`bash ./bcbio/genomes/Mmusculus/mm10/txtmp/ggd-run.sh`

**Comment by pengxiao78** [comment]
Hi,
I ran this command alone and it was successful. Then should I re-run the 
bcbio_nextgen.py upgrade -u stable --tools --data
command?
Thank you.

**Comment by lpantano** [comment]
I would try, maybe was some network problem with some of the files...

let me know if you get the same error. I would remove anything inside `genome/Mmusculus/mm10/srnaseq` if there is anything.

**Comment by pengxiao78** [comment]
Yes, I got the same error. But now it returned non-zero exit status 1 instead of 4 as previous. In the notice 
Running GGD recipe: sranseq
, there may be a typo. Should it be "sranseq" or "srnaseq"? Is this the reason for the error?
Thanks.

**Comment by lpantano** [comment]
Hi,

I saw the typo, but is only the name. I will fix that, thanks.
If you run again the BASH script it finishes without problems? or you have an errors as well.

If it finished and you see the `srnaseq` folder I can tell you how to hack the installation so it will skip that.

Is there any temporary file inside `genomes/Mmusculus/mm10` folder? liek `tx` or `tmp` or anything that can trace to files that you see in the BASH file?

So sorry about that, I am trying to think in an alternative to skip this.

**Comment by pengxiao78** [comment]
I ran the bash command alone 
bash ./bcbio/genomes/Mmusculus/mm10/txtmp/ggd-run.sh 
was successful and all the files were generated successful under srnaseq folder. 
There are no tx or tmp folders. 
However, when I re-ran
bcbio_nextgen.py upgrade -u stable --tools --data
The error appeared again.

**Comment by lpantano** [comment]
It appears any message when it run, or you don't get anything else? Sometimes I get error if there is these files already exists when running again the installation because the bash script gives some messages.

A way to skip this is to hack the files.

You need this folders inside mm10
```
 ls ~/soft/bcbio/genomes/Mmusculus/mm10/
rnaseq/            rtg/               srnaseq/
rnaseq-2014-07-14/ seq/               versions.csv
```

and the `version.csv` should be:

```
cat ~/soft/bcbio/genomes/Mmusculus/mm10/versions.csv
sranseq,20151014
```

**Comment by pengxiao78** [comment]
I just re-run the update command again and it was successful. You may have changed something. So I do not need to hack the installation anymore. Thank you.

**Comment by pengxiao78** [comment]
I also re-ran the test suite and it was all okay with any error. Thank you.
