### ISSUE TITLE
Sample configuration should warn about samples present in CSV but not in files

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1079]
Use case: two analyses I ran today failed due to a missing paired samples because I had forgot to put them in the right directory, but I didn't get any warning when configuring.

**Comment by lpantano** [comment]
Thanks for the tip. I tried to fix this here: 489c3753f239c58f43ddf5ceecd91168cb7b5642

hopefully now helps to avoid further issues.

cheers
