### ISSUE TITLE
bcbio_vm.py installation with http:proxy connexion : VEP error

### ISSUE THREAD

**Issue by chdem** [chapmanb/bcbio-nextgen#1080]
I'm using an http:proxy at work and I'm encountered VEP installation error during bcbio_vm.py execution :
```
ERROR: Could not connect to FTP host ftp.ensembl.org
Net::FTP: connect: Connection timed out
```

Downloading VEP files in a folder and installing VEP with the -u option, I was able to execute bcbio_nextgen_install.py on an another computer (see issue #818 ).

Unfortunately, I don't know how to do that with the vm way because I can not install VEP manually and I don't know how to change VEP installation script calling in order to add the -u option.

**Comment by chapmanb** [comment]
Thanks for the heads up and sorry about the proxy issues. It would make sense to add this workaround into bcbio itself to avoid needing to change it. Sorry, but I'm a bit inexperienced with proxy settings. Could you provide a little more detail about how you set -u? Is it the same as any of the proxy variables like `HTTP_PROXY`? We pass those variables into the Docker container so could set this automatically if present. Thanks for any details to help resolve this.

**Comment by chdem** [comment]
I'm planning to use bcbio for diagnostic in a cluster configuration, so I need to make tests before. 

I'm working in an hospital environment, so I need to use http_proxy and all /etc/bash.bashrc of our computers contains these lines :
```
http_proxy=http://10.50.2.2:3128;
HTTP_PROXY=$http_proxy
https_proxy=$http_proxy
HTTPS_PROXY=$http_proxy
ftp_proxy=$http_proxy
FTP_PROXY=$http_proxy
all_proxy=$http_proxy
ALL_PROXY=$http_proxy
rsync_proxy=$http_proxy
RSYNC_PROXY=$http_proxy
ftp_proxy=$http_proxy
FTP_PROXY=$http_proxy

export http_proxy
export https_proxy
export ftp_proxy
export HTTP_PROXY
export HTTPS_PROXY
export FTP_PROXY
```

On a first computer, I've tried to install bcbio in the 'classic' way, running this command :
```
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa --aligners bowtie2 --sudo
```

I've encountered an error with VEP installation :
```
subprocess.CalledProcessError: Command '/usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/vep
Getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Net::FTP: connect: Connection timed out
' returned non-zero exit status 110
' returned non-zero exit status 1
```

This is a known error for VEP installation on systems using http_proxy. Net::FTP perl's module is not able to correctly manage http_proxy. For the moment (I wish that Ensembl will do something for us), the only way to install VEP correctly is to download manually datafiles with wget (which well manage http_proxy), put them in a folder, and give the folder path to vep installation script with the -u option. This is what I've done :
```
cd ~/.vep
wget ftp://ftp.ensembl.org/pub/release-81/variation/VEP/homo_sapiens_vep_81_GRCh37.tar.gz
/usr/local/bin/vep_install.pl -a c -s homo_sapiens_vep_81_GRCh37 -c /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/vep -u ~/.vep/
```

After that, I launched again vep_install.pl and everything was correct !


Few days after, I was reading a bit more documentation of bcbio and I discovered that docker installation way was much more easier ! So I tried to install bcbion_vm on an another computer ! And I encountered the same VEP Net::FTP error ! But this time, I'm not able to install VEP manually, as Docker environment is quite different !

We could tried to download VEP file with wget in Docker container and change vep_install.pl call adding the -u option ?

What do you think ?

**Comment by chapmanb** [comment]
Thanks much for the detailed description. That's a great workaround and I added the explicit wget and `-u` approach into the standard installation so it'll work cleanly on systems behind proxies without any changes. It'll work now if you update to the development version (`bcbio_nextgen.py upgrade -u development`) and I'll plan to push a new Docker image this weekend if things test out cleanly for you.

Regarding the bcbio_vm install, if you specify `--tools` it will re-download and upgrade the Docker container. Leaving that flag off will skip the download, so no need to specify it if you have an up to date container. We hope to move over to using the Docker registry and automated builds, which would manage resolution of the Docker images. Thus far we've had issues with the size of the image but will keep testing as the index improves.

Thanks again for all the thoughts and suggestions.
