### ISSUE TITLE
Report is not generated (should it be?) with tumor-normal analyses

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1082]
I noticed in the `work` directory a `report` folder containing the report in Rmarkdown, at the end of a paired tumor-normal run. However the report was not generated at all. Trying to do so locally yielded several errors about ``row.names`` being duplicate, and I noticed my normal samples being in twice. 

Anything I can do to further debug the issue?

**Comment by lpantano** [comment]
Hi,

sorry about this. Will try to reproduce and see that is the main problem there. I remember that maybe for that case is not totally compatible the way samples are stored in variables, but will look at it.

**Comment by lpantano** [comment]
Hi,

You meant that there is not HTML file there? We are not currently render that. But I know what you mean about duplicate samples. If samples are used more than once in the config file, they will be there that many times.
I removed duplicated samples (b6fc26652a5f44410f89d7d36f6bac7023ebe8ad), and at least that should be ok.

Let me know if you have more issues rendering the Rmd file.

**Comment by lbeltrame** [comment]
I've also noticed (sorry, I didn't have time to test yet) that the report stays in the `work` directory and thus might be overlooked. Shouldn't it be moved to wherever `upload` in the configuration file says?

**Comment by lpantano** [comment]
Hi,

i moved the report folder to final, and is running for tumor-normal pipeline removing duplicates.

Will close, but feel free to re-open if there is still any problem.
