### ISSUE TITLE
Install: R errors are silent

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1083]
While upgrading the pipeline, I noticed that a few R packages failed to install (glibc version mismatch), but the installation went on nevertheless. Like all the other steps, install failures should abort the install / upgrade.

**Comment by chapmanb** [comment]
Luca -- apologies for the confusion. The R packages are in flux as we move over to installing R along with bcbio, and some of the more difficult experimental packages like BubbleTree don't install cleanly on some platforms. We'll definitely work on fixing this as we improve support for these but it's currently expected to not abort as we don't want to stop the install for work in progress. Thanks much for the report.
