### ISSUE TITLE
GATK haplotype caller and UnifiedGenotyper for InDels only

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1086]
I am wondering if is possible to keep only the indel call from GATK caller. I have realized that otherwise I get a large number of SNPs gremline events.  

variantcaller: [gatk,gatk-haplotype,varscan,mutect,freebayes]
      ensemble:
       numpass: 2

I am also wondering why the -nWayOut parameter in not set for IndelRealigner Tumor Normal pair?

Thanks a lot !
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
We don't have an option to only call indels in bcbio. The best approach is to subset your calls after they come out of bcbio with bcftools:
```
bcftools view -v indels
```
We haven't implemented pooled realignment as part of bcbio, as our validations haven't found much value in doing this (http://bcb.io/2013/10/21/updated-comparison-of-variant-detection-methods-ensemble-freebayes-and-minimal-bam-preparation-pipelines/). In the next release we plan to default to not doing recalibration and realignment.

Practically if you're doing somatic calling, you'll likely want to stick with callers that handle lower frequency mutations. I'd suggest:
```
variantcaller: [vardict, freebayes, mutect]
```
if you want multiple callers, or only vardict if you'd like a single caller. It does local rearrangement so especially avoids the need for seperate realignment. Here is an in-progress writeup with the latest validations of callers (https://github.com/bcbio/bcbio.github.io/blob/master/_posts/2015-10-05-vardict-filtering.md). Hope this helps.

**Comment by apastore** [comment]
Thanks as usual for your exhaustive replay!
