### ISSUE TITLE
Improving performance of bedtools jobs for coverage calculation

### ISSUE THREAD

**Issue by WimS83** [chapmanb/bcbio-nextgen#1088]
Hi, 

How fast should creating the coverage bed files be after the read mapping stage for a bwa + freebayes pipeline? Say percentage wise of the total workflow.

In my experience this is now taking longer than the mapping stage, and maybe even as long or longer than the mapping + variant calling stages combined. And increasing the the total number of  available of slots that can be used does not help much, or even hurts the  coverage calculation speed. 

Are there known things that I can look in to for speeding up this bedtools coverage calculation stage ? Did much change for this bedtools stage in recent bccbio releases?

Maybe lowering the cpu per bedtools job? Or lowering the total amount of cpu for all bedtool jobs?

Any tips for fixing or trouble shooting this performance issue are welcome. 

Thanks.

**Comment by WimS83** [comment]
The issue seems to be related to a set of our nodes.

**Comment by chapmanb** [comment]
Thanks for reporting the issue, and following up with the system specific details. Although this was related to specific hardware here, we do appreciate the general issue. This set of steps is more IO intensive, so will tend to bottleneck on disk or shared filesystem throughput.

I pushed some changes that will avoid doing the callability calculations on the smaller chromosomes (all of the alternative alleles and extra chromosomes for human), which will hopefully somewhat mitigate the problem by doing less work. Hope this helps some and thanks again for the report.
