### ISSUE TITLE
Number of parallel analysis blocks lower than number of available cpu on cluster. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1097]
Hi, 

In a mapping plus variant calling analysis  I see that variant calling will be done on 149 parallel analysis blocks. These analysis blocks are contiguous regions that have sufficient coverage in one or more samples I believe. Is this correct?

Identified 149 parallel analysis blocks

Resource requests: freebayes, gatk, picard; memory: 3.50, 3.50; cores: 1, 1, 1
Configuring 185 jobs to run, using 1 cores each with 3.50g of memory reserved for each job

The number of cpu on our cluster a multiple of 150. Am I correct that all 149 blocks will be variant called using a single freebayes process? 

Would it be possible to split the parallel analysis blocks to smaller  (and thus more ) analysis blocks? 

Or use freebayes parallel to variant call each block using multiple cpu?
https://github.com/ekg/freebayes/blob/master/scripts/freebayes-parallel

This to speed up variant calling on large sets of samples regardless of the coverage distribution over the reference genome.  

The current method of doing variant calling in parallel is maybe more applicable to some reference genomes than others, because it depend of the presence of a high number of different regions with coverage, and gaps with no coverage, between these regions. 

Neill

**Comment by chapmanb** [comment]
Neill;
You're right in the understanding of the block splitting. It will run 149 single core FreeBayes variant calls (times the number of samples/batches in your input configuration) in parallel. You can control the splitting to make it more aggressive if you want to optimize for use of more cores on a small number of samples by increasing `nomap_split_targets` and maybe decreasing `nomap_split_size` if you can't find enough regions to break into for your reference genome:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#parallelization

Hope this helps give you the parallelization you need to get your analysis done.

**Comment by NeillGibson** [comment]
Thank you Brad. I will try these parameters.
