### ISSUE TITLE
 _setup_resources() runs very long ...........

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1107]
Hi,

I sometimes see very long running scripts to get the resources of a large shared machine on which we run bcbio jobs.

My guess is that this job that I see on the machine is started by this step in the code:

https://github.com/chapmanb/bcbio-nextgen/blob/b6fc26652a5f44410f89d7d36f6bac7023ebe8ad/bcbio/pipeline/main.py#L49

How long should this step take? 

In my case this jobs run for hours or almost a day........

Does this step depend on some kind of settings (resource limits) for the machine on which it is trying to get the resources? 

the latest entry in the bcbio std out file is 
[2015-11-09T22:20Z] large_machine2: Filtering for sample_5, freebayes

the latest entry in the command log file is 
bcbio/tools/bin/tabix -f -p vcf  batch1-Chr_06_278427970_3936913250-raw.vcf.gz

the command I see running for very long on the server is
../bcbio/data/anaconda/bin/python -E -c import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 > else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from ipyparallel.apps.ipengineapp import launch_new_instance; launch_new_instance() --timeout=960 --IPEngineApp.wait_for_url_file=960 --EngineFactory.max_heartbeat_misses=120 --profile-dir=../work/log/ipython --cluster-id=fce7ccbd-1df6-43c6-a112-b8405319b858

Best Regards,

Neill

**Comment by chapmanb** [comment]
Neill;
Sorry about any confusion. The resources code you're looking at happens quickly at the start of all processes bcbio runs, so likely doesn't have anything to do with your long running process. You'll see that command for everything bcbio runs -- it's the servers used by IPython parallel for analysis.

The best way to debug what is going on is to restart the process, and then look in `log/bcbio-nextgen-commands.log` to determine what bcbio started. You could then ssh to machine that's running that job to try and debug what or why is happening. Apologies, this can be confusing if a job is long running but doesn't produce any stdout -- it's hard to identify exactly what it's doing even when processing is going on. Hope this helps.

**Comment by NeillGibson** [comment]
Hi Brad,

I stopped my current jobs on the cluster and the machine that I submitted from (with qdel and kill). 

Then I restarted bcbio with the same command that I used before. 

What I see in the new std out log is 
[2015-11-10T09:54Z] large_machine2: Filtering for sample-05, freebayes

The last entry in the command log is still the command from yesterday 2015-11-09 instead of 2015-11-10 (today)

tail -n 1 log/bcbio-nextgen-commands.log 
[2015-11-09T10:45Z] large_machine2: ../bcbio/tools/bin/tabix -f -p vcf ../work/freebayes/Chr_06/tx/tmpv5KiHr/batch1-Chr_06_278427970_3936913250-raw.vcf.gz

If I log in to the large_machine2 and do ps aux | grep myd, the only process I see, running also for large amount of time with close to 100% cpu,  is:

myid    190959 98.8  0.0 5103096 128732 ?      Rl   10:54  32:06 ../bcbio/data/anaconda/bin/python -E -c import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from ipyparallel.apps.ipengineapp import launch_new_instance; launch_new_instance() --timeout=960 --IPEngineApp.wait_for_url_file=960 --EngineFactory.max_heartbeat_misses=120 --profile-dir=../work/log/ipython --cluster-id=fc39b540-8c3c-4629-bc47-51fac08436f1

If I do a qstat I only see one executor job on the large machine and the controller job on a smaller machine in another queue. 

job-ID     prior   name       user         state submit/start at     queue                          jclass                         slots ja-task-ID
------------------------------------------------------------------------------------------------------------------------------------------------
   1908864 0.45117 bcbio-c    myid        r     11/10/2015 10:54:04 all@smaller_machine                                    1 1
   1908865 0.49403 bcbio-e    myid        r     11/10/2015 10:54:14 main3@large_machine2                                  10 1

We used the modification described here by schelhorn to make sure the that controller job runs on the queue with smaller machines. On the queue with the larger machines it sometimes timed out. 
https://github.com/chapmanb/bcbio-nextgen/issues/1048

So I am still worried that the issue is with the resource detection step taking much to long, not another step, because no new command was specified in the command log and the only thing I see running is the resource detection script. 

Neill

**Comment by chapmanb** [comment]
Neill;
Sorry it's still not providing good feedback on the current state. That is frustrating.

The process that's running on the machine is the IPython worker engine, not resource checking. It will always be present and long running as long as jobs are out.

In terms of debugging, I'm confused as to why the filtering step here would take a long time. For FreeBayes there's a processing step where it calculates depth for calls in the input VCF file that should be quick, and then it should run a filtering command with bcftools. I'm not sure why it would hang on the initial step.

My only thoughts to debug next would be to run in a single core (`-n 1`) to see if it also hangs there for a long time. If so, you could ctrl-C it and get a sense of what work it's doing that is causing all of the CPU usage.

Hope this helps some with debugging. Thanks for the patience working through it.

**Comment by NeillGibson** [comment]
On a single node with single cpu also no progress is made. I only see the main bcbio python script running with 100% cpu.  I now restarted the whole analysis on the cluster to see if the analysis finished with a fresh run.

**Comment by chapmanb** [comment]
Neill;
Thanks for the update. bcbio is working on something but it's not clear why it takes so long. Could you do a `ctrl-c` to interrupt when it's stuck at 100% CPU and post the traceback here? That would help give us an idea of where it's working and might give ideas for how to fix. Thanks much.

**Comment by NeillGibson** [comment]
The issue might be related to starting bcbio inside a nohup, and maybe (python)path variables being lost.  Before executing bcbio with nohup I export the bcbio  (tooldir) path variables. 

Running within a screen instead of a nohoub seems to fix the issue, at least when running single threaded outside the cluster. Hitting ctrl-c lead me to the vcfreader loop in this function. 
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/vfilter.py#L179

I will try to see if running bcbio on the cluster inside a screen instead of a nohup also fixes the bcbio execution on the cluster.

**Comment by chapmanb** [comment]
Neill;
Sorry, I don't have much experience with nohup so am not sure what to suggest there beyond using screen or tmux instead. Hopefully that's a reasonable workaround.

The ctrl-C output helps. It looks like it's working hard on the step where bcbio walks through the VCF file and calculates called depth. It's possible these files are extra big or wide, causing all the IO. I pushed a fix to development which uses the faster cyvcf2 parser instead of pyvcf, which I hope will resolve the issue. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
Hopefully it will avoid getting stuck here. Thanks again for the help debugging and hope this resolves it for you.

**Comment by NeillGibson** [comment]
Thank you you for the tips and the faster vcf parser.
