### ISSUE TITLE
Provide explanations for prioritize and priority_regions

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1115]
In several recent additions to the code base there were some parts that relate to variant prioritization, for both small and large genomic variants. These additions comprised prioritize* Python methods, cancer gene lists from CIViC and AZ, and the priority_regions YAML key). It would be great if someone could briefly explain what these are for, how users can provide their own, and espacially if these regions actually influence the results (e.g. by informing variant callers), or if they are mostly intended for coverage annotation in order to see which genomic regions were not sufficiently covered by reads to allow variant calling (known unknowns etc.). I briefly checked the docs and did not find anything (but I may have missed it). Thanks!

**Comment by mjafin** [comment]
Hi Eric,
This is part of our effort to better pull out structural variants that have an effect on transcripts (inv/dup/del/bnd that cause fusion transcripts). I think the idea was to only document it once we've ironed the bugs and issues out, of which there are aplenty still.

**Comment by schelhorn** [comment]
Great, thanks.

**Comment by mjafin** [comment]
Eric if you have any DNA data with structural variants you could have a go using lumpy and manta plus setting
```
svprioritize: cancer/az300
```
This'll produce -sv-prioritize.tsv files in the very latest developmental version with lines like this:
```
caller  sample  chrom   start   end     svtype  known   end_gene        lof     annotation      split_read_support  paired_end_support
lumpy   HDC134P      chr2    29224782        42297000     INV     ALK     AC083949.1,COX7A2L,EML4         INV|INTRON_VARIANT|ALK|ENST00000389048| 0       413
```
(ALK-EML4 inversion/fusion as an example)

We're working with Pablo Cingolani to get SnpEff annotate these better but in the meantime we're manually curating genes that are hit by the events.
