### ISSUE TITLE
rna-seq star/hg38 issue

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1118]
Hi,
I'm trying to run rna-seq using star and hg38 but I'm running in to trouble. 

First I get this error: 

<b>FATAL error, could not open file sjdbGTFfile=None

<b>Nov 24 17:05:57 ...... FATAL ERROR, exiting
<b>[E::hts_open] fail to open file '/home/zahra/rnaseq/151016_D00458_0118_AC7NCBANXX/calling/work/align/08-253/08-253_star/tx/tmpaYQDam/08-253.bam'

If I run the command and remove the "sjdbGTFfile=None" setting, I get this output:

<b>Transcriptome.cpp:13:Transcriptome: exiting because of *INPUT FILE* error: could not open input file /usr/local/share/bcbio/genomes/Hsapiens/hg38/star//transcriptInfo.tab
<b>Solution: check that the file exists and you have read permission for this file
<b>          SOLUTION: utilize --sjdbGTFfile /path/to/annotantions.gtf option at the genome generation step or mapping step

Should there be some annotations there? This is the first time running rna-seq, so this is all new to me. Sorry if the error is on me.

**Comment by parlar** [comment]
I should have mentioned that I'm running the latest development version of bcbio-nextgen

**Comment by roryk** [comment]
Hi Par,

Sorry-- we don't support hg38 yet for RNA-seq. The main issue is that there aren't any ready-to-go spliced aligners that are alt-aware. We have support in place for hisat2 which should be able to handle it, but we've been having troubles getting it to not hang during a run of any real data. We'll be putting up a stopgap in place of including hg38-noalt for RNA-seq soon. I'm just testing it to make sure it works.

**Comment by parlar** [comment]
Okay! Then I'll switch to hg19. Thanks for a fast reply!

**Comment by roryk** [comment]
Thanks, sorry it has taken us a while to get going on this. I'm going to close this issue, but I'll post in https://github.com/chapmanb/bcbio-nextgen/issues/817 when this is straightened out, so if you follow that issue you'll get updated.
