### ISSUE TITLE
GRCh37-rtg.tar.xz missing from S3 bucket?

### ISSUE THREAD

**Issue by yanickpouliot** [chapmanb/bcbio-nextgen#1119]
Howdy ya'll. I'm finding that bcbio_nextgen_install.py is aborting 'cause GRCh37-rtg.tar.xz doesn't appear to be in its S3 bucket. Could this be addressed?

Cheers,

Yannick

std out:

[localhost] local: wget --continue --no-check-certificate -O GRCh37-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz'
--2015-11-24 12:05:52--  https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.65.32
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.65.32|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-24 12:05:53 ERROR 404: Not Found.

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-rtg.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-rtg.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome GRCh37 with index rtg
INFO: Preparing genome GRCh37 with index rtg
[localhost] local: export RTG_JAVA_OPTS='-Xms1g' export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa
java is not Java 7 or later

Fatal error: local() encountered an error (return code 1) while executing 'export RTG_JAVA_OPTS='-Xms1g' export RTG_MEM=2g && rtg format -o rtg/GRCh37.sdf /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa'

Aborting.

**Comment by chapmanb** [comment]
Yannick;
Sorry about the issue. The missing rtg index is expected.  We don't create pre-finished rtg indexes because it builds quickly. The installer recovers fine from this, but fails when creating the index locally. The key error is:
```
java is not Java 7 or later
```
If you put Java 1.7 in your PATH it should hopefully work cleanly. Hope this helps.
