### ISSUE TITLE
Evaluate which paired callers should be incorporated

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#112]
#109 highlighted some issues: namely, which tools to support tumor/paired calls.

There is a comprehensive list on BioStars (http://www.biostars.org/p/19104/), so the plan would be to evaluate which ones to incorporate. This issue should track this effort. 

Ticked elements indicate that the tool was already evaluated.
- [x] MuTect: supported, only SNVs
- [x] VarScan2: supported
- [x] SomaticSniper: PR #109, support status unknown, depends on a fixed samtools version, only SNVs - tested - removed due to its reliance on old samtools
- [x] Strelka: unsuitable (uses Makefiles, integration into pipeline impossible)  - tested
- [x] EBcall: unsuitable, doesn't output VCF, updated not very frequently
- [ ] Seurat: last update June 7 2013, uses a modified GATK (very old), outputs a single sample VCF without sample name - tested
- [ ] Shimmer: Perl based, depends on R as well, outputs VCF 4.0 (not sure on what exactly is generated)
- [x] SNVmix: unsuitable, needs a proper model for best results (a standard model is supplied), doesn't output VCF
- [ ] SOAPsnv: Poorly documented, unsure if output is VCF
- [ ] Virmid: last update May 2013, Java based, outputs VCF containing somatic mutations in the tumor (i.e. single sample VCF) without sample name - tested
- [x] FreeBayes: Mature tool, outputs VCF, supported.

**Comment by lpantano** [comment]
Hi all,

I will close this guessing everything has evolved since then. It was an excellent discussion.

Thanks!
