### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by aaiezza** [chapmanb/bcbio-nextgen#1120]
So I realize many others may be far along into using bcbio, but I've been having trouble setting it up and using it. I installed it through pip and I have sample data ready to run through but I don't know what to do next.

Here is my working directory:
![image](https://cloud.githubusercontent.com/assets/8107121/11402428/dd86a0c0-9365-11e5-854b-7dcb567681e4.png)

Here are my reads:
![image](https://cloud.githubusercontent.com/assets/8107121/11402583/a2075a66-9366-11e5-9acb-901d86e3d3c3.png)
. . .
![image](https://cloud.githubusercontent.com/assets/8107121/11402644/ea98f8ca-9366-11e5-9d10-138a2091f99f.png)

Here is where my genome is:
![image](https://cloud.githubusercontent.com/assets/8107121/11402619/ca314f10-9366-11e5-8d6f-3d5969c07632.png)

All of the tools that I am trying to use are installed, working and exist in my PATH.
I'm running on a x64 Debian OS with 30Gb of RAM, 16 cores and the two drives above (athena & atlas) are RAID NFS shares.

Can anyone please help me?
Thank you,
Alex

**Comment by chapmanb** [comment]
Alex;
Thanks for trying out bcbio. Your best bet for getting up and running with bcbio is to use the automated installer:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#automated

which installs the tools and data as bcbio expects. Without this you're likely to be fighting with incompatible program versions and biological data. There are details in the docs about hooking up with the existing data, but you're likely to get the smoothest experience using this approach. As an example from your screenshots, your manually downloaded genomes look incorrect as you have a build 38 reference and build 37 GATK resources files.

To get a project setup, I'd suggest using the templating option to specify configuration for your files, letting bcbio build the sample file for you from a base definition:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#automated-sample-configuration

then you can run the analysis on your machine with:
```
bcbio_nextgen.py ../config/your_sample.yaml -n 16
```
Hope this helps.

**Comment by aaiezza** [comment]
Brad,
I appreciate your response! I see now the flaw in my reference incompatibility.
Unfortunately, I have been looking at that resource already that you provided the link for. Even after reading it I'm still confused on a few levels. For instance the project1.csv file.

Are there specific locations I should be running these bcbio commands?

Thanks,
Alex

**Comment by chapmanb** [comment]
Alex;
Sorry about the confusion. The installer will put all the tools, plus bcbio_nextgen.py, in one directory which you can add to your PATH. All of the templating and running commands use the single program `bcbio_nextgen.py`.

For the template CSV, what specifically are you stuck at? That should be a CSV file describing your sample names and any other parameters to tweak, like batches. It might help to understand what exactly you're trying to do (call germline variants? Batched together in one group?) and what error messages/setup issues you have to offer more specific advice.

Hope this helps.

**Comment by aaiezza** [comment]
Brad,

Thank you for your help this far. I wanted to let you know that the installer command:

python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa --distribution debian

Hangs up on ruby1.9.1-dev dependency.
I believe that is because I am using Debian Jessie and not wheezy so that package is not available.

Do you have a suggestion?

Thanks,
Alex

**Comment by chapmanb** [comment]
Alex;
Sorry about the issues with installation. Are you running the install command as root? I'm a bit confused why bcbio is trying to install system packages without the `--sudo` flag. In general your best bet is to run as a regular user (without root or sudo) and pre-install the base requirements for bcbio:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

I think this'll give you the best path, especially on Debian where it doesn't get as extensively tested for bootstrapping from scratch. Hope this helps get you going. If not, posting a traceback of the issue your seeing might give us more information to go from.

**Comment by aaiezza** [comment]
I was running as root. The problem I discovered was that the package ruby1.9.1-dev does not exist for Debian jessie, only wheezy. I found a workaround for this by simply adding the wheezy repository to my sources.list file. In the future maybe alter the installation script or something to only look for ruby-dev

**Comment by aaiezza** [comment]
Also the R package, devtools, does not exist for R 3.1.1
Should I be using a different version of R?

**Comment by chapmanb** [comment]
Alex;
Thanks much for the additional details. I wouldn't recommend running the script as root. Practically, your best approach is to chmod the directories you want to install into if you don't have user privileges there, then run the installer as your standard user.

For R, bcbio doesn't need an external R installation and should use a version of 3.2.2 installed with the conda installer. Is the installer trying to use an external version instead of this? If you could post the full traceback I might be able to come with ideas about why this is. Sorry again about the problems and hope this helps.

**Comment by lpantano** [comment]
Hi!

I will close this, since it seems you finally got it right!, please feel free to come again if there are more problems!

thanks!
