### ISSUE TITLE
Error for exon data 

### ISSUE THREAD

**Issue by gongxuesusan** [chapmanb/bcbio-nextgen#1121]
Dear There,

I tried to use bcbio_nextgen.py to detect mutation by four callers (mutect, varscan, freebayes, vardict) for exon sequencing data. But I ran into the below error.

##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1

Does anyone how to fix it? Thank you very much.

Xue

**Comment by chapmanb** [comment]
Xue;
Sorry about the issue. It looks like you have an older version of GATK (2.2) installed which does not support some of the options used in bcbio. If you want to use GATK for annotations of variant calls you can install the latest via the instructions here:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#gatk-and-mutect

Alternatively if you want to skip GATK, you can remove the 2.2 jar line (`gatk -> dir`) from your installed `/path/to/bcbio/galaxy/bcbio_system.yaml` file. Older versions of bcbio, if you've installed a while ago, used to install 2.2 but we now skip installing GATK completely unless you want to install it manually.

Hope this helps.

**Comment by lpantano** [comment]
Closing this since it seems it worked at the end. Let us know if there is any other issue.

thanks!
