### ISSUE TITLE
Custom genome resources  yaml file misses alias and ensembl keys, breaks qualimap . 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1125]
Hi, 

A line of code in qcsummary.py depends on there being an aliases block with an ensembl key and value in the genomes *resource.yaml file. 

https://github.com/chapmanb/bcbio-nextgen/blob/3fd7d3fa2b117b61a20c09e4888a2c8338b69a40/bcbio/pipeline/qcsummary.py#L586

This is not the case for custom genomes that were added with bcbio_setup_genome.py script. Which results in this error when running an analysis with qualimap enabled for mapping qc. 

```
Traceback (most recent call last):
  File "//bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 586, in _run_qualimap
    species = data["genome_resources"]["aliases"].get("ensembl", "").upper()
KeyError: 'aliases
```

For the newly added custom genomes the resource.yaml file only contains just. 

```
version: 1
```

I now manually create / copy a resources.yaml file for each new genome that looks like this

```
version: 1

aliases:
 human: false
 snpeff: None
 ensembl: None

variation:

rnaseq:

coverage:

```

Maybe it is possible to remove this dependance on the aliases and ensembl field for the qualimap analysis? Or add the aliases and ensembl information for every new custom reference genome?

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks much for the detailed report and diagnosis. I pushed a fix which should avoid this dependence. Sorry about the issue and please let us know if you run into anything else at all. Thanks again.

**Comment by NeillGibson** [comment]
I am happy to contribute. Thank you for the quick fix.
