### ISSUE TITLE
sailfish

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1130]
Hi, 
By default, sailfish quant seems to be running with the parameter -p 1 (1 thread). Should there be a setting for sailfish in the bcbio_system.yaml to bump up the no of threads?

**Comment by roryk** [comment]
Hi @parlar,

Hm, sailfish quant should be running with whatever the setting is for samtools in the bcbio_system.yaml, so it should definitely be running in parallel. I tested it and its definitely picking up the number of cores. I did notice though that you can create the index in parallel as well, so I added that.

**Comment by parlar** [comment]
Wierd, I'll check again. But it was definetly using one core, took ages... 


Skickat från Outlook Mobile






On Thu, Dec 3, 2015 at 1:33 PM -0800, "Rory Kirchner" <notifications@github.com> wrote:












Hi @parlar,



Hm, sailfish quant should be running with whatever the setting is for samtools in the bcbio_system.yaml, so it should definitely be running in parallel. I tested it and its definitely picking up the number of cores. I did notice though that you can create the index in parallel as well, so I added that.
