### ISSUE TITLE
ERROR: cannot verify s3.amazonaws.com's certificate

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#1133]
Upgrade command tries to download this file: 
https://s3.amazonaws.com/biodata/coverage/prioritize/prioritize-cancer-GRCh37-20151116.tar.gz
And gives me this error:
```
ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=VeriSign Class 3 Secure Server CA - G3,OU=Terms of use at https://www.verisign.com/rpa (c)10,OU=VeriSign Trust Network,O=VeriSign\\, Inc.,C=US’:
  Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
```
gist: https://gist.github.com/funnell/8802e06e60b9e9313a9a

Is there a way around this?

**Comment by chapmanb** [comment]
Tyler;
Sorry about the problem. It looks like older versions of wget are not resolving AWS certificates correctly. I added --no-check-certificate to the download recipes in CloudBioLinux which I hope will resolve this. If you remove your temporary install directory (`rm -rf tmpbcbio-install`) and re-run it should hopefully work now. Please let us know if you run into any other problems.
