### ISSUE TITLE
Newer GEMINI installer changed options

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1136]
And this makes installation fail:

````
/opt/bcbio/anaconda/bin/python -Es gemini_install.py --help
usage: gemini_install.py [-h] [--nodata] [--gemini-version GEMINI_VERSION]
                         tooldir datadir

Automated installer for gemini framework.

positional arguments:
  tooldir               Directory to install 3rd party software tools
  datadir               Directory to install anaconda python and gemini data
                        files

optional arguments:
  -h, --help            show this help message and exit
  --nodata              Do not install data dependencies
  --gemini-version GEMINI_VERSION
                        Install one specific gemini version with a fixed
                        dependency chain.
````

**Comment by chapmanb** [comment]
Luca;
Thanks much for reporting this and apologies about being slow in getting the GEMINI install up to date with the latest release. If you upgrade to the latest development it should now install cleanly. We're hoping to have a 0.9.5 release next week including this fix. We install the GEMINI code itself with conda now and then only install the data if requested. Please let us know if you run into any problems with installing/upgrading now.
