### ISSUE TITLE
Sharing tooldir between several users

### ISSUE THREAD

**Issue by callosciurus** [chapmanb/bcbio-nextgen#1137]
Just wondering if it's possible to share the same directory among several users, while each user maintains their own isolated installation (potentially different releases)?

**Comment by roryk** [comment]
Hi @callosciurus,

We have some documentation for doing something like that here: https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#local-private-bcbio-installation 

as a way to keep just the code different but re-use the same tools and data. On a couple of the Harvard clusters we have one master install with the tools and the data and then just the code is different between us while we work on it. Eventually things get out of sync and someone updates the main install and we go on from there. 

Practically, this might end up being more trouble than its worth, the results should remain similar between different versions of bcbio-nextgen, and you'll quickly get into situations where an old code base isn't compatible with newer tools and vice versa. 

In the past when folks have asked about this, it was over concern of not getting the exact same results from version to version. We think of reproducibility as the major results being reproducible and by that standard there shouldn't be much changing from version to version. 

Hope that helps, let me know if that isn't a satisfying enough answer.

**Comment by lpantano** [comment]
Hi,

I will close this. Feel free to come again if you have further question, hopefully Rory's advice worked for you!

**Comment by callosciurus** [comment]
This was very helpful. We ended up using separate installations, since that's easier to maintain as @roryk suggested. Thanks!
