### ISSUE TITLE
The current RNA-Seq workflow and read trimming

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1140]
Hello @roryk and crew, I was wondering whether the current RNA-Seq pipeline still is depending on quality/adapter/poly-a trimming or if this step could be left out (since it produces quite some extra storage and IO load). Sadly, the [best comparison paper](http://www.genomebiology.com/2015/16/1/150) for current expression callers does use pre-trimmed reads (i.e., removed poly-a and sequencing adapters also using cutadapt). However, I believe there is reason to assume that read trimming may not be strictly necessary anymore for all tools supported by bcbio.

- As far as I know, `star` does soft-clipped alignment and explicitly models qualities and poly-a tails. 
- `sailfish` is able to explicitly consider poly-a's using a command line parameter (currently not set in bcbio) and is robust wrt. to quality trimming according to the paper. It doesn't say anything about adapters. 
- `express` does not seem to consider poly-a's at all (based on the manual, the mailing list archive and the paper), but the reliance on a soft-skipped read mapper and the fragment-approach may make it robust with regard to such local alignment problems. Anyway, the `sailfish` paper seems to indicate that quality trimming prior to `express`  does not affect results. 
- `cufflinks` in assembly mode will probably have problems with poly-a's and adapters since it will screw up the assembly, but not many bcbio users seem to use it anyway (I may be wrong, and this may change with `stringtie`, don't know). 

So, what do you guys think, is read trimming useful at all if not doing assembly?

**Comment by roryk** [comment]
Hi @schelhorn,

I agree the the read trimming step is not as important as it once was; Tophat doesn't softclip so before it was important to try to clean up the reads before aligning them. I think we might be able to skip this step unless running Tophat or assembling without impacting the results too much.

**Comment by schelhorn** [comment]
Great; I'll ask on the Sailfish mailing list how much accuracy is lost by omitting trimming and will report back here.

**Comment by schelhorn** [comment]
Here's the reply I got from Rob:

> One of the benefits of the quasi-mapping approach taken by sailfish is that it is rather robust to quality and adapter trimming.  One way you can assess this is by looking at the mapping rate (i.e. the fraction of reads that are mapped) --- which appears in the comments of the main output file "quant.sf".  You may be able to recover a small fraction of extra reads with quality / adapter trimming, but generally this is not necessary for Sailfish to map reads accurately for quantification purposes.  It's also worth noting that the poly-A tail trimming is for trimming poly-A tails from the reference transcripts --- not the reads.  This is useful since reads coming from the poly-A region are inherently ambiguous, and not in a manner that assists quantification.  Thus, discarding the poly-A tails of transcripts (and, therefore, reads that derive from them), has the potential to improve both the speed and accuracy of the resulting quantification.

So I'd recommend we skip trimming by default, unless hisat2 requires it.

**Comment by roryk** [comment]
Thanks for looking into it @schelhorn, I stuck it on my list of stuff to implement after we push a release.

**Comment by schelhorn** [comment]
Great 👍
