### ISSUE TITLE
upgrade problem

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1143]
While trying to upgrade bcbio-nextgen to the latest devel version I get this error message:

```
Could not find a version that satisfies the requirement bcbreport>=0.99.14 (from bcbio-nextgen) (from versions: )
No matching distribution found for bcbreport>=0.99.14 (from bcbio-nextgen)
```

**Comment by parlar** [comment]
did manual installations of several python packages (bcbreport, azure ..) as a work-around

**Comment by chapmanb** [comment]
Pär;
Sorry about the upgrade problem. I'm trying to reproduce this but am not able to, so am not sure what to suggest. It looks like that's coming from pip, but the recent versions of bcbreport that satisfy this are available (https://pypi.python.org/pypi/bcbreport). Are you updating with `bcbio_nextgen.py upgrade -u development`, or some other way? Would you be able to post the full traceback? Thanks for the help debugging.

**Comment by parlar** [comment]
It was as if pip could not reach the repository if executed through the bcbio_nextgen.py script. After manual update of a number of python packages the upgrade worked. Yes, I ran ```upgrade -u developement``` . I'm afraid that I did not save the complete traceback unless there is a log somewere?  Now things work as they should, though,

**Comment by chapmanb** [comment]
Pär;
Thanks for following up and glad things work now. If you run into this problem again please do re-open and we can investigate further.
