### ISSUE TITLE
Enable multithreading for vardict-java

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1144]
I was wondering if we could make use of the `-th [numthreads]` parameter to parallelize `vardict` calling. For the DNA-Seq part, adding to `bcbio_system.yaml`:

```yaml
  vardict:
    jvm_opts: ["-Xms750m", "-Xmx4000m"]
    options: ["-th", "4"]
    cores: 4
```

should already enable multithreading. The same can be done for RNA-Seq variant calling using `vardict` by adding in [`bcbio.rnaseq.variation.rnaseq_vardict_variant_calling()`](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/variation.py#L127) after the definition of `opts`:

```python
resources = config_utils.get_resources("vardict", data["config"])
if resources.get("options"):
    opts += ' '.join(resources["options"]) + ' ' # Ugly but directly works with opts string
```

I believe that `vardict` memory requirements do not scale up with the number of cores, i.e. they are a constant. However, with my proposed solution the bcbio parallel environment of the workflow will multiply the memory requirement in `jvm_opts` by the number of cores, resulting in artifically inflated memory requirements for the parallel environment. These are not required for `vardict` operation and also not passed on to the actual `vardict` command which takes the `jvm_opts` verbatim from `bcbio_system.yaml` anyway.

May there be a way to turn of memory-upscaling for `vardict` and implement multithreading as proposed or did I miss something?

**Comment by mjafin** [comment]
@schelhorn I think this would be useful for the current RNA-seq implementation that doesn't parallelise by regions but for DNA-seq we should avoid this as parallelisation is already taken care of by splitting into smaller bed chunks. I may be making an oversight here so happy to be corrected.

**Comment by schelhorn** [comment]
I was wondering about DNA-Seq - wouldn't it make sense to multithread `vardict` within each BED chunk as well, given that we don't have to assign any extra memory when speeding up through multithreading? Assuming that speed improvements through multithreading are roughly linear, this seems to be a more efficient way for scaling up than using larger numbers of smaller BED chunks, since for each chunk we have to invest the full `vardict` memory requirement. Am I making sense here?

**Comment by chapmanb** [comment]
Sven-Eric and Miika -- thanks for the thoughts. It is normally advantageous to use multicore support over splitting, but the issue is generalizing to other callers. Most don't support multiple cores so we've settled on the more general approach even if it's less efficient. 

It makes sense to explore this with RNA-seq, although this does limit us to parallelization available on a single machine unless we invest the effort to support multi-machine parallelization by splitting on regions. Multicore could be a simple step in the direction of being faster without doing all that work and see how much improvement this gives us. Rory, what do you think?

**Comment by schelhorn** [comment]
Well, the default regions for RNA-Seq `vardict` calling are the transcript annotations in the RNA-Seq `gtf`, which is converted into a `bed`. So the split could reasonably be done based on that using the existing infrastructure. Personally I am happy with multithreading if the performance gain is approximately linear - 16 cores should be enough for RNA-Seq data.

**Comment by mjafin** [comment]
Based on some previous tests I did the performance gain is fairly weak and not quite linear unfortunately. If you want to do a few tests let us know how it looks on your side

**Comment by schelhorn** [comment]
It seems to look like it. Apparently I cannot scale it up to more than ~300% CPU use (tried with 4 and 8 threads, same results). The machine has 250GB of main memory and 36 cores, and the BAM is sitting on a local 24-disk RAID0 with 1GB/s throughput. So I guess it's a limitation of `vardict` and not of the system (barren some crazy random IO pattern of `vardict`, but that sounds unlikely). In light of that result perhaps it would make sense after all to split by region - once @roryk has time for that, which probably will take a while :)

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for testing this out. We've had similar results with GATK multi-threading. In some cases using more threads slowed things down, apparently due to thread deadlock. We'll think about some ways to move to the region based parallelization approach. Great to have a path forward, even if it's more work to do.

**Comment by schelhorn** [comment]
Great! That makes a lot of sense for RNA-Seq also because the the current `vardict` filtering approach makes use of single-core R process in the command pipe. That process is actually the limiting step since you can multithread `vardict` but then have to wait until the single-core filter chain has done its thing. Working with a single-core pipe and region-based parallelization is the way to go -- as you and @mjafin have rightly pointed out. Consequently, I'll close this issue for now but would appreciate it if you could add `vardict` RNA-Seq parallelization to your internal todo list.

**Comment by schelhorn** [comment]
Addendum: for RNA-Seq `vardict` mode, it may also help to get rid of the `teststrandbias.R` `R` process in the `vardict` pipe. This R process running a Fisher's exact test takes quite a bit from the overall runtime, and I believe strand bias is expected with RNA-Seq data anyway (or it depends on library prep, at least, and so may not be informative in the general case).
