### ISSUE TITLE
Fallback samtools BAM sort is broken

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1145]
The [fallback single-core `samtools` sorting](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/__init__.py#L363) in `bcbio.bam.sort()` seems to be broken. The block takes it arguments from the `locals()` environment which still has `cores` cores set from the previous attempts to generate and run command lines (and not one core as it should in the fallback). In addition, `mem` may be overwritten by a previous `sambamba` block (which may have failed, thus resulting in the fallback sorting). Crucially, `sambamba` `mem` isn't per-core as `samtools` expects it, but per-process as `sambamba` expects it. As a result, the fallback sorting may allocate both too many cores (it's supposed to be single-core) _and_ to much memory (in fact, `cores` times as much memory as expected). So the fallback option will almost always fail as well.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks much for catching this. I pushed a fix which does the lower memory single core sort to provide a more useful fallback. Thanks again for the heads up and clear details for fixing.
