### ISSUE TITLE
How to set the option for Qualimap to produce PDF mapping QC reports

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1146]
I tried to set the option for Qualimap to output PDF instead of html QC report in the YAML:

```
resources:
    qualimap:
        options: [-outformat PDF]
```

I am not sure if this output option is currently picked up by BCBio?

https://github.com/chapmanb/bcbio-nextgen/blob/3fd7d3fa2b117b61a20c09e4888a2c8338b69a40/bcbio/pipeline/qcsummary.py#L593

It would be nice to have the option to have Qualimap output PDF mapping QC reports.

**Comment by lpantano** [comment]
Hi @NeillGibson,

I will work on this feature next week after the release together with #1147.

Thanks for your feedback!

**Comment by NeillGibson** [comment]
@lpantano Thank you for picking this up!
