### ISSUE TITLE
Is it possible to run Qualimap on the full bam files? Not down sampleled? 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1147]
Is it possible to run Qualimap on the full bam files? Not on the down-sampled bam files? 

I know Qualimap is not very fast but I should run within acceptable amounts of time for smaller sets of samples and ofcourse smaller genomes. 

Are there other outputs in BCBio that give the coverage per sample? Or should I calculate this myself from the number of aligned reads and the genome size?

Thank you.

**Comment by roryk** [comment]
Hi @NeillGibson,

There isn't an option to run on the full BAM files but the statistics reported by qualimap should give a broad overview with the downsampled files. If you provide a BED file of regions you are interested in, the `coverage` module https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html?highlight=coverage#experimental-information will calculate coverage and completeness across those regions if there are particular areas you are interested in looking at.

**Comment by NeillGibson** [comment]
I am interested in the statistic and plots over all reads over the whole genome. 

For example average coverage of the whole genome. The percentage of the genome covered X times. The distribution of the coverage of the genome. 

And the insert size and quality distribution. These last two distribution I can get from the down sampled bam files, but the coverage information not.  

I can understand that running qualimap on entire BAM files is not a default option because of the time it takes for human sized genomes. But it would be nice if there was an option to run qualimap on the full bam files.

**Comment by lpantano** [comment]
Hi @NeillGibson,

I will check if there is an option to run it with full alignment file, and if not I will try to implement one.

**Comment by NeillGibson** [comment]
Thank you very much. By default Qualimap should support this, so it is just a matter of passing it the full BAM file.

**Comment by lpantano** [comment]
Hi, I added the two features you  miss in bcbio. Let me know if they work well. 

You need to use `tools_on: qualimap_full` to run in whole bam file. and to create the PDF, just what you tried inside `resources`. 

Be aware that if you create PDF report, in the final yaml file there won't be the qualimap statistics since we parse the HTML file to get them, but you will have the PDF file inside `qc/sample/qualimap` folder.

hope this suits you better.

**Comment by NeillGibson** [comment]
Hi thank you for the quick work! I look forward to testing it :)
