### ISSUE TITLE
matplotlib: axes.color_cycle is deprecated

### ISSUE THREAD

**Issue by diehlsa** [chapmanb/bcbio-nextgen#1148]
Whenever I run the latest stable or development version, I get the following warning:

    /path/to/bcbio-nextgen/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
      warnings.warn(self.msg_depr % (key, alt_key))

**Comment by chapmanb** [comment]
Sarah;
Thanks much for the heads up. This is a warning that comes from the seaborn library we use for plotting. It's fixed but not yet in a seaborn release:

https://github.com/mwaskom/seaborn/pull/739

So hopefully once they push a new release we'll get the update and this will go away. It's annoying but nothing to worry about in the meantime.

**Comment by diehlsa** [comment]
Ok, thanks for the info.

**Comment by lpantano** [comment]
Hi,

I will close this since it seems not to be a problem anymore, or will disappear soon. Thanks for the information!
