### ISSUE TITLE
RNA-SeQC?

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1149]
It is not entirely clear to me if / how RNA-SeQC can be run through bcbio-nextgen. Any info is appreciated (or is this tool obsolete?). Seems as if support for it is implemented in the pipeline..?

**Comment by roryk** [comment]
Hi Pär,

We don't run RNA-SeQC anymore, it was very slow. We replaced most of the functionality with qualimap and a set of custom tools as part of the QC process.

**Comment by roryk** [comment]
Ripped all of the code out and removed it from the docs. Thanks Pär.
