### ISSUE TITLE
Oncofuse supports hg38

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1150]
The current version of oncofuse installed by bcbio already supports `hg38`; in principle, it should just work if the bcbio `oncofuse` wrapper plays nice. The bcbio documentation still says that only `hg19/37` are supported. Obviously, `star` is not alt-aware, so that should be `hg38-noalt` internally. I am noting this here because we currently have no fusion calling on `hg38` until (and if) the `hisat2` + `manta` workflow to do this is implemented.

**Comment by roryk** [comment]
Hi Sven-Eric,

Thanks-- we're trying to deprecate `hg38-noalt` and just move forward with `hg38` so we don't have the maintenance overhead of two builds. Maybe we can feed `hisat2` alignments into `oncofuse`?

**Comment by schelhorn** [comment]
Yes, I believe that should work. `oncofuse` is primarly an annotation engine for called fusion events (analogous to `vep` for microvariants). For `hg38`, such calls would likely be produced by `manta` based on `hisat2` alignments (since I believe `hisat2` is not calling fusions or chimeras itself). I guess we could then just modify the eventual `manta` output in a format that can be digested by `oncofuse`.
