### ISSUE TITLE
tumor variants

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1151]
Hi, just a simple question: is it only mutect that supports tumor variant calling without normals? Principally, should not varscan, freebayes and perhaps also other tools be able to do this?

**Comment by schelhorn** [comment]
All of them work in tumor-only mode as far add I know. I recommend vardict.

**Comment by parlar** [comment]
great!

**Comment by chapmanb** [comment]
Sven-Eric is right on as usual. In addition, this post describes approaches we take to try and remove germline variants from tumor-only calls:

http://bcb.io/2015/03/05/cancerval/

Hope this helps.
