### ISSUE TITLE
how to troubleshoot 10 bwa alignment pipes (100 cpu) being idle ??

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1153]
Hi, 

I am trying to align and variant call a number of samples. 

To do this I am running bcbio via SGE on a single large machine with 100 of the 160 available cpu. 

There are 10 bcbio worker engines running 10 BWA alignment pipes where each pipe is running bwa with 10 cpu.

After around half a day and having processed a number of samples now all bwa alignment pipes are idle. `Top` show 0% percent usage of the machine.  

`ps aux | grep BWA` shows that there processes are still on the system. The BWA processes seem to be in a sleeping state. qstat also shows the slots on the machine still being used, though the job resource statistics are not changing anymore. 

No new log entry has been created in the bcbio log for over 24 hours. 

Somewhere these BWA pipes are waiting on a resource not available anymore, either at the input or output side. Or there is some sort of resource lock somewhere. 

Do you have any tips for troubleshooting these idle BWA alignment pipes? 

I thought it might be related to   /dev/fd/62 and  /dev/fd/63 outputstreams that samblaster opens in in the pipe. 

These I can't ls:
```
ls: cannot access /dev/fd/62: No such file or directory
ls: cannot access /dev/fd/63: No such file or directory
```

But a small test run with just 4 samples with 80.000 reads is now running on that same large machine with 2 bcbio workers running BWA alignment pipes with 10 cpu each. These also use samblaster and these /dev/fd/62 and /dev/fd/63 for output. 

```
[2015-12-11T12:15Z] large_machine: samblaster: Opening /dev/fd/62 for write.
[2015-12-11T12:15Z] large_machine: Opening /dev/fd/63 for write
```

So there is no global resource shortage on the large machine. There seems to be a resource problem / lock just with the 10 bcbio workers / bwa pipes from my first run. 

Any tips on how to troubleshoot this? Thank you!

**Comment by chapmanb** [comment]
Neill;
Sorry about the failures without useful error messages. It's tough to debug these remotely but from the description it sounds like the larger job is somehow triggering failures which are not reported to the shell and bcbio so it doesn't know they died.

Is it possible some system process is killing the bwa or samblaster jobs? If so, that might be reported in the SGE logs.

Practically, it can help to use `align_split_size` to limit the size of each bwa chunk that gets processed at a time. This lets you fail quicker, if you're having problems, and avoids needing bwa to run for a long time.

Hope one of these ideas helps with debugging and running.

**Comment by NeillGibson** [comment]
Hi issue seems to have been a restart of our sge submit node. The bcbio controller running there was therefore killed, and the worker engines / bwa pipes somehow stopped working by this after half a day. At least this seems to be most probable cause. 

This issue can be closed. The analysis is running again and will finish I hope.
