### ISSUE TITLE
ICGC WGS SNV/indel pipeline benchmark is out, including new references

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1155]
This may be very influential for Brad's validation effort. They found a lot of interesting facts (depth 100x, region filters, ensemble calling) and provide new manually curated tumor-normal reference data against which the callers are not overfit, yet ;)

http://www.nature.com/ncomms/2015/151209/ncomms10001/full/ncomms10001.html

**Comment by schelhorn** [comment]
Although they certainly have things to learn, too (like `rg`):

> A call was considered to be equal when both the position and the exact substitution reported were identical.

**Comment by schelhorn** [comment]
> The sequencing reads and curated Gold Set mutations described here are available to the research community through the ICGC DACO and the EGA to benchmark and calibrate their pipelines. (...) Sequence data for this study have been deposited in the European Genome-phenome Archive (EGA) under the accession number EGAS00001001539.

**Comment by schelhorn** [comment]
The optimized filter settings are located in http://www.nature.com/ncomms/2015/151209/ncomms10001/extref/ncomms10001-s1.pdf page 47.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much, this paper is a great resource. We'll definitely be incorporating these test sets in validations, and are also trying to get access to the AML31 data through dbGAP (http://aml31.genome.wustl.edu/). It's great to have so much work on this becoming available.

**Comment by schelhorn** [comment]
Great; closing then.

**Comment by lzy108** [comment]
I want to benchmark and calibrate the mutation calling pipeline in house. But I have no access to this benchmarking dataset (EGAS00001001539). How can I get the benchmarking dataset ?

**Comment by ohofmann** [comment]
@lzy108 They are part of the ICGC/TCGA dataset, You can request access at EGA, https://www.ebi.ac.uk/ega/datasets/EGAD00001001858 has details on what information the DACO needs.
