### ISSUE TITLE
Error installing dependencies with bcbio_nextgen.py?

### ISSUE THREAD

**Issue by TrentPrall** [chapmanb/bcbio-nextgen#1158]
Hi,

I am attempting to install bcbio using the supplied python script but keep running into this error. Any advice would be greatly appreciated. 

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

"The following packages have unmet dependencies:
 libpcre3-dev : Depends: libpcre3 (= 8.12-4) but 8.12-4ubuntu0.1 is to be installed
 openjdk-7-jre : Depends: openjdk-7-jre-headless (= 7u91-2.6.3-0ubuntu0.12.04.1)
E: Unable to correct problems, you have held broken packages.

Fatal error: local() encountered an error (return code 100) while executing 'apt-get -y --force-yes install fastx-toolkit last-align maq plink tabix openjdk-7-jdk openjdk-7-jre gsl-bin libatlas-base-dev libblas-dev libbz2-dev libc6-dev libcurl4-openssl-dev libeigen3-dev libgsl0-dev libgsl0ldbl liblapack-dev liblzma-dev libncurses5-dev libnetcdf-dev libpcre3-dev libpng12-dev libreadline-dev libssl-dev libxml2 libxml2-dev libxslt1-dev libxslt1.1 libzip-dev mime-support' "

**Comment by chapmanb** [comment]
Trent;
Sorry about the install issues. In the bcbio install, we're trying to move away from installing system packages with the installer. We've reduced the dependencies that bcbio doesn't handle to a few, documented here:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#automated

How are you running the installer? As a root user? If so, could you re-run as a standard user installing in a directory with privileges? Hopefully this will resolve the issue and get things running cleanly for you. Happy to help more if you get stuck again at any point.

**Comment by lpantano** [comment]
Hi!

I will close this since it seems you get it working? please, come again if you find more issues. Thanks a lot!
