### ISSUE TITLE
RNA seq output file docs

### ISSUE THREAD

**Issue by lindakohn** [chapmanb/bcbio-nextgen#1161]
Hi,

I'm new to RNA seq and have some questions about the RNA seq output files. Is there any documentation available describing what's in the different outputs. E.g. I wonder about the difference between the ready.bam file and transriptome.bam. It seems that ready.bam is generated by STAR and transcriptome.bam by SAILFISH?

Thanks!

**Comment by roryk** [comment]
Hi @lindakohn,

Thanks, sorry the output isn't clear, both of those are created by STAR. The `ready.bam` file are the alignments to the whole genome with STAR and the `transcriptome.bam` is just to the transcriptome. There are some downstream tools that need the transcriptome-only alignments so we generate those. For most experiments you'll be fine looking at the `combined.counts` file in the `final/your-project` directory and starting your analysis from there. We have a package [bcbio.rnaseq](https://github.com/roryk/bcbio.rnaseq) that you can use to summarize the results of the bcbio-nextgen run and generate a report with QC information and a preliminary analysis with DESeq2 automatically. We then load that report up into R and use it as a starting point for performing an analysis.

**Comment by lindakohn** [comment]
Hi again!
Can you get count info on how many reads that span introns? i.e. get splicing info..
Linda

**Comment by roryk** [comment]
Hi @lindakohn,

We recommend using the `sailfish` transcript-level counts and use those as input to [limma](https://www.bioconductor.org/packages/3.3/bioc/vignettes/limma/inst/doc/usersguide.pdf), (see section 18.2) to look at differential transcript expression. We also produce a file in the final directory that has counts that can be used as input to [DEXSeq](https://bioconductor.org/packages/release/bioc/html/DEXSeq.html). Other people might have other suggestions but those are the two we most commonly use.

**Comment by parlar** [comment]
Linda is a colleague of mine (she has gone home for the day I believe). I think what she after is a way to look at transcripts that, with certainty, have been spliced.

**Comment by lpantano** [comment]
Hi @lindakohn 

hope this helped you to get to the information you needed, if not feel free to coma back and we will happy to figure out something.

thanks
