### ISSUE TITLE
What annotation file is used for GRCh37?

### ISSUE THREAD

**Issue by lindakohn** [chapmanb/bcbio-nextgen#1162]
Hi!

What annotations is used in the RNA seq GRCh37 and hg38 pipelines? I.e. what's in the ref-transcripts.gtf?

**Comment by roryk** [comment]
Hi @lindakohn,

Thanks, sorry it is not clear. hg38 has the Ensembl release 78 and GRCh37 has Ensembl release 75.

**Comment by lindakohn** [comment]
Thanks!

Is the STAR alignment guided by the annotations or is it only used by SAILFISH?

**Comment by roryk** [comment]
STAR uses the annotations as well, it adds them on the fly before aligning.
