### ISSUE TITLE
fastqc heap space issue - add resource to command line

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1163]
At the moment, `fastqc` does not seem to take its memory resources from `bcbio_system.yaml`, in particular the java heap space vars (`xms`, `xmx`) are not incorporated into the `fastqc` command line at all. Unfortunately, I get `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space` for `fastqc` within a sample and I cannot fix this by increasing the memory resources for the process due to aforementioned issue. Would it be possible to add `fastqc` to the resource listing and let it use the java vars during command line call so that the heap space is correctly set?

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the report. I looked at the fastqc script and it didn't set the Java stack (`-Xms`) which might be causing this issue. Without -Xms set, Java often picks up a pretty big stack leading to issues on larger machines. I don't think fastqc itself uses much memory so this is my best guess at a cause. I patched the fastqc script we use and built a new version, so if you update `--tools` hopefully it'll run cleanly now without needing to adjust parameter settings.

**Comment by biomonika** [comment]
I am running into similar issues too:, when I ask for 18 processors I get:
FastQC_2/fastqc -t 18 K.fastq
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space

whereas when I ask for 19 processors I get:
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Requested array size exceeds VM limit

**Comment by chapmanb** [comment]
Are you running fastqc inside of bcbio or as a standalone program? We can try to offer help if within bcbio. If outside bcbio it's much harder to debug as we don't have a lot of details about your install. My guess is that you need to use less threads for your machine, as 18 * 250Mb/thread in the default fastqc script causes memory issues on the machine. Hope this helps.
