### ISSUE TITLE
ZeroMQ hang makes processes never complete

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1164]
Notice: this may not the right place to report this, but I'm trying to gather clues to see why things are not working.

Setup:

4 2U servers with 2 NICs. One NIC is connected to the institutional LAN, the other is reserved for SLURM. Each has 2 x 4 core AMD processors + 24G RAM

Sympthoms:

Certain pipeline steps like `piped_bamprep` or `prep_samples` hang with processes not completing and going on forever (and leaving loads of zombie processes on the nodes). It seems all processes are stuck in `epoll_wait` for some reason. 

I need to debug this further, but I'm running out of ideas....

**Comment by lbeltrame** [comment]
Possibly unrelated: all the processes run on all the nodes, but I get output on the log only for the process started from the node.

**Comment by schelhorn** [comment]
Just a guess, but `piped_bamprep` and `prep_samples` require quite some local disk IO (and network IO for the shared storage). Have you tried running bcbio in local (not ipython) mode on one of your machines, while tracking memory usage and storage IO?

**Comment by lbeltrame** [comment]
Hello Sven-Eric,

> running bcbio in local (not ipython) mode on one of your machines, while
> tracking memory usage and storage IO?

Those actually hang as well. I am not sure if it's a bcbio issue or the 
system's (Bio-Linux 8).

**Comment by chapmanb** [comment]
Luca and Sven-Eric;
Sorry about the issues and thanks for all the details. So, to confirm -- you're seeing bcbio hanging when running in local mode as well? In this case I'd second Sven-Eric's suggestion that there might be something problematic happening with the disk IO or networked filesystem. Does bcbio hang at a consistent point we could debug? If not, I guess it's some system specific filesystem issue but it's hard to guess exactly what could be causing it other than "too much disk activity." You could turn off recalibration/realignment which can help some with avoiding this as a practical workaround. Hope this helps.

**Comment by lbeltrame** [comment]
Hello Brad,

> case I'd second Sven-Eric's suggestion that there might be something
> problematic happening with the disk IO or networked filesystem. Does bcbio

The fact is - there's no disk I/O. I initally suspected the shared FS I'm 
testing bcbio on (RozoFS), but when the hang occurs, there's absolutely no 
disk activity. I've seen hangs also in `prep_align_inputs` where the check 
(command sent through subprocess.check_output) made whether to use bwa or bwa 
mem never returns.

In these cases, the command by itself works ("bash -c ..."), and also works 
inside a Python interpreter.

**Comment by chapmanb** [comment]
Luca;
Thanks for the details. I don't have any experience with RozoFS so not sure what exactly to suggest, but if it's intermittently failing looking at the filesystem is my best guess. All bcbio does is run those commands in subprocess, so nothing special is happening on our side. If they sometimes work and sometimes fail I'd assume you could see similar things if you run the commands outside of bcbio as well. If you can isolate to a single case where it fails regularly that might be useful to debug further. Hope this helps some.

**Comment by schelhorn** [comment]
You could try running a `strace` (as root) on the stalled process, ie. either the external command line call that bcbio issues or on the bcbio Python process itself if no external command line call is going on (check with `ps`). Also, running an interactive `python`shell and trying these commands may help find out if Python process forking is a problem in your system (since you mentioned `subprocess.check_output`, see also [here](https://github.com/chapmanb/bcbio-nextgen/blob/34e7e719f080ba080bcd898bc90c0585c111fc79/bcbio/ngsalign/bwa.py#L102)):

```python
import subprocess
subprocess.check_output(["which", "bwa"])
subprocess.check_output(["which", "bwa"], shell=True)
subprocess.check_output(["which", "bwa"], shell=True, executable="/bin/bash", stderr=open("/dev/null", "w"))
```

**Comment by lbeltrame** [comment]
To clarify what I said earlier in a more precise form:

- Launching processes by using the exact command from bash *works*;
- Using `subprocess` from an interactive Python interpreter *works*;
- Using it from bcbio *does not work*.

It's all like this (using `strace -ffp <pid>`):

````
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
[pid  3419] poll([{fd=7, events=POLLIN|POLLPRI}], 1, 0) = 0 (Timeout)
````

A check with `gdb` (unfortunately I have *no* idea how to install the Python extension for gdb using anaconda... any suggestions?) shows:

````
gdb) bt
#0  0x00007fbff1024ee9 in __libc_waitpid (pid=3593, stat_loc=0x7ffe25e5bac4, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00007fbff136ceca in posix_waitpid (self=<optimized out>, args=<optimized out>) at ./Modules/posixmodule.c:6261
#2  0x00007fbff132fe15 in call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5bbe8) at Python/ceval.c:4350
#3  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#4  0x00007fbff1330a2e in PyEval_EvalCodeEx (co=0x7fbfe70b01b0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=2, kws=0x7fbfa8007208, kwcount=0, defs=0x7fbfe70b5228, defcount=1, closure=0x0)
    at Python/ceval.c:3582
#5  0x00007fbff132fa55 in fast_function (nk=<optimized out>, na=2, n=<optimized out>, pp_stack=0x7ffe25e5be08, func=0x7fbfe70acb90) at Python/ceval.c:4446
#6  call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5be08) at Python/ceval.c:4371
#7  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#8  0x00007fbff1330a2e in PyEval_EvalCodeEx (co=0x7fbfe70b0230, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=2, kws=0x7fbfa8003170, kwcount=0, defs=0x7fbfe70b5268, defcount=1, closure=0x0)
    at Python/ceval.c:3582
#9  0x00007fbff132fa55 in fast_function (nk=<optimized out>, na=2, n=<optimized out>, pp_stack=0x7ffe25e5c028, func=0x7fbfe70acb18) at Python/ceval.c:4446
#10 call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5c028) at Python/ceval.c:4371
#11 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#12 0x00007fbff1330a2e in PyEval_EvalCodeEx (co=0x7fbfeb516430, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=1, kws=0x7fbfa8002bf8, kwcount=0, defs=0x7fbfeb519528, defcount=1, closure=0x0)
    at Python/ceval.c:3582
#13 0x00007fbff132fa55 in fast_function (nk=<optimized out>, na=1, n=<optimized out>, pp_stack=0x7ffe25e5c248, func=0x7fbfeb51c1b8) at Python/ceval.c:4446
#14 call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5c248) at Python/ceval.c:4371
#15 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#16 0x00007fbff1330a2e in PyEval_EvalCodeEx (co=0x7fbfd3693eb0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=9, kws=0x7fbff17d8068, kwcount=0, defs=0x0, defcount=0, closure=0x0) at Python/ceval.c:3582
#17 0x00007fbff12ac4a8 in function_call (func=0x7fbfd369c7d0, arg=0x7fbfc0a9f350, kw=0x7fbfc0c68280) at Objects/funcobject.c:526
#18 0x00007fbff127cd23 in PyObject_Call (func=0x7fbfd369c7d0, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#19 0x00007fbff132d797 in ext_do_call (nk=-1062603952, na=<optimized out>, flags=<optimized out>, pp_stack=0x7ffe25e5c538, func=0x7fbfd369c7d0) at Python/ceval.c:4663
#20 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3026
#21 0x00007fbff1330a2e in PyEval_EvalCodeEx (co=0x7fbfeb51b2b0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=1, kws=0x0, kwcount=0, defs=0x7fbfeb524168, defcount=1, closure=0x0) at Python/ceval.c:3582
#22 0x00007fbff12ac3a1 in function_call (func=0x7fbfeb525050, arg=0x7fbfc0c31510, kw=0x0) at Objects/funcobject.c:526
#23 0x00007fbff127cd23 in PyObject_Call (func=0x7fbfeb525050, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#24 0x00007fbff128f4bf in instancemethod_call (func=0x7fbfeb525050, arg=0x7fbfc0c31510, kw=0x0) at Objects/classobject.c:2602
#25 0x00007fbff127cd23 in PyObject_Call (func=0x7fbfc21dff50, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#26 0x00007fbff12e975c in slot_tp_call (self=0x7fbfc21ac190, args=0x7fbff17d8050, kwds=0x0) at Objects/typeobject.c:5455
#27 0x00007fbff127cd23 in PyObject_Call (func=0x7fbfc21ac190, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2546
#28 0x00007fbff132df54 in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7ffe25e5cb38, func=0x7fbfc21ac190) at Python/ceval.c:4568
#29 call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5cb38) at Python/ceval.c:4373
#30 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#31 0x00007fbff132fb95 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7ffe25e5cca8, func=0x7fbfd369c668) at Python/ceval.c:4436
#32 call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5cca8) at Python/ceval.c:4371
#33 PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:2987
#34 0x00007fbff132fb95 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=0x7ffe25e5ce18, func=0x7fbfd3627848) at Python/ceval.c:4436
#35 call_function (oparg=<optimized out>, pp_stack=0x7ffe25e5ce18) at Python/ceval.c:4371
````

I'm just noticing now it's also consuming 100% CPU... `iotop` gives no disk wites nor reads. For extra safety, I'll try running it on a local directory, off the RozoFS export.

**Comment by chapmanb** [comment]
Luca;
Sorry, I'm stuck here as to what to suggest. In bcbio we're not doing anything beyond calling out with subprocess so not sure why it would interact differently with your filesystem. Does bcbio consistently fail/hang, or fail at different points in the process? If the later, this suggests that you might be able to reproduce outside of bcbio by running more "real life" tests with loops accessing files multiple times. Sorry to not have better ideas but hope this helps.

**Comment by schelhorn** [comment]
Um, that is strange. Again, for clarification, you determined the exact point in the bcbio sources where the bcbio Python process stalls? And then started a Python shell with exactly the same python interpreter used by bcbio, and the same code that stalled in the bcbio process ran without problem in the interpreter, on the same host, and using the same shell and environment variables?

**Comment by lbeltrame** [comment]
> Um, that is strange. Again, for clarification, you determined the exact
> point in the bcbio sources where the bcbio Python process stalls? And then

After some review, I think the issue is somehow in the filesystem I'm using. 
When running off local disk, there is no such hang. However it always occurs 
when running on the network share.

**Comment by lbeltrame** [comment]
Closing. I'm fairly sure there's something else going on in my system, but finally I've been able to make a minimal, non-bcbio test case.

**Comment by lbeltrame** [comment]
For the record and for those who are interested: it was an issue in the distributed FS I was using: https://github.com/rozofs/rozofs/issues/112

**Comment by roryk** [comment]
Hi Luca,

That is some heroic bug reporting on your part, glad the issue got fixed.
