### ISSUE TITLE
Creating single sample VCF files slowest step in bcbio pipeline?

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1175]
Hi, 

I am trying to get an overview of the performance of the stages in the bcbio  BWA + freebayes pipeline. 

For 40 samples of a species that I am working with I get the following overview using x cpu on our cluster. I used the time stamps for different stages from the bcbio-debug.log to extract the time per stage. 

Analysis stage  | Total wall time (hh:mm) | Total wall time / nr samples (hh:mm)
------------- | -------------|--------------------|
BWA & Mark dups | 24:15| 00:36 |
Create coverage bed files  | 06:53|00:10|
Variant calling|17:11 |00:25|
Concat VCF files|04:40|00:07|
Post processing VCF|02:47|00:04
Split variants by sample|   48:00   | 01:12

To my surprise the "Split variants by sample" stage takes the longest of all stages, in total and per sample. 

The stage splits of single sample VCF files sequentially per sample. I only see 1 bcftools view command running sequentially for all samples in this stage. Can't this step be done in parallel?
I.e. creating a bcftools view command for each sample and run them in parallel on the cluster?

Or should this already be done in parallel and is there a cluster / bcbio setting that I should change at my side?

Another general thing to increase the performance might be to store the intermediate VCF files as BCF files. 

>HTSlib was designed with BCF format in mind. When parsing VCF files, all records are internally converted into BCF representation. Simple operations, like removing a single column from a VCF file, can be therefore done much faster with standard UNIX commands, such as awk or cut. Therefore it is recommended to use BCF as input/output format whenever possible to avoid large overhead of the VCF → BCF → VCF conversion. 
https://samtools.github.io/bcftools/bcftools.html

And only convert to vcf.gz for the final per sample and multi-sample VCF file. I once tried to split a large multi-sample VCF file per sample and having the multi-sample file in BCF format substantially increased the performance as the note also mentions. 

 The version of bcbio I am using is: 0.9.5a0

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks much for the benchmarking and great diagnosis. Apologies to have such a poor bottleneck slowing down these larger pooled analysis.

I think the right fix here is to avoid doing the sample extraction out of the pooled variant VCF. This isn't an essential step and most folks doing downstream analysis on larger populations will likely prefer to handle extraction of samples and regions of interest themselves in a way we can't automate.

I pushed a fix that should skip this for any population calls with more than 5 samples, which should eliminate this set of work. Hope this speeds up your analyses and please let us know if you run into any other issues at all. Thanks again.

**Comment by NeillGibson** [comment]
Hi Brad, 

I was hoping that a small change could be made to just run the single sample VCF extraction in parallel.

We very much like the feature of having both the multi-sample and single sample VCF files as the output.  For example some backup, integration and (IGV) visualization is easier to do with the single sample VCF files (by having a BAM and VCF per sample to expose). 

Only improvement we wanted is running the single sample extraction in parallel to (vastly) reduce the wall time needed.   

Could you reconsider to include the functionality to (optionally) extract single sample VCF files in parallel? 

Otherwise this is something that we (and probably other people/organizations) would develop our self as a add on functionality.

**Comment by chapmanb** [comment]
Neill;
Understood, apologies that doesn't do what you'd needed. I always like to solve problems by pulling out code but it this case it looks like we need to revisit. It will take a bit of work to revamp how this is done -- it currently doesn't parallelize well because it's happening at the level of the batch, not individual samples so needs to be reworked. I'll re-open and we'll revisit to work on that.

**Comment by NeillGibson** [comment]
Ok thank you! I understand that this might some time. I look forward to the feature being available.

**Comment by NeillGibson** [comment]
Hi Brad. For us it is probably also is easier to first do custom annotation on the multi-sample VCF and then split using an intermediary BCF file (for performance) to single sample VCF files. 

So never mind the request to reconsider. Having just the multi-sample VCF output is fine.

**Comment by chapmanb** [comment]
Neill;
Thanks for following up on this, that helps a lot. We'll avoid the extra work for now and only return the combined VCF and can revisit later if there is a lot of demand and consensus process to do this. Thanks again for all the feedback.
