### ISSUE TITLE
Multiple errors in running tumor-normal pipeline

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1177]
Hi Brad,
I found the following new multiple errors by using the same tumor-normal pipeline that I kept running successfully recently. In the slurm file, I used --retries 3 option. Could you please help me to debug them?
Thank you!

[2016-01-07T21:58Z] c4401.xxx.edu: Recalibrating ['', '11351tumor'] with GATK
[2016-01-07T22:07Z] c4314.xxx.edu: Assigned coverage as 'amplicon' with 6.9% genome coverage and 0.0% offtarget coverage
[2016-01-07T22:08Z] c4314.xxx.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cat /lustre/project/work/align/1049tumor/8_2016-01-05_project_1st-merged-sort-callable-callableblocks.bed | grep -v ^track | grep -v ^browser | grep -v ^# | ./bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /lustre/project/work/bedprep/tx/tmp5Eu_W3/8_2016-01-05_project_1st-merged-sort-callable-callableblocks.bed
cat: /lustre/project/work/align/1049tumor/8_2016-01-05_project_1st-merged-sort-callable-callableblocks.bed: Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    bcbio.variation.bedutils.remove_bad(x)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 70, in remove_bad
    if int(parts[2]) > int(parts[1]):
IndexError: list index out of range
' returned non-zero exit status 1
[2016-01-07T22:08Z] c4314.xxx.edu: Unexpected error
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 44, in _setup_logging
    yield config
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 133, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 164, in postprocess_alignment
    data = bedutils.clean_inputs(data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 106, in clean_inputs
    clean_vr = clean_file(utils.get_in(data, ("config", "algorithm", "variant_regions")), data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 49, in clean_file
    do.run(cmd.format(**locals()), "Prepare cleaned BED file", data)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cat /lustre/project/work/align/1049tumor/8_2016-01-05_project_1st-merged-sort-callable-callableblocks.bed | grep -v ^track | grep -v ^browser | grep -v ^# | ./bcbio/anaconda/bin/py -x 'bcbio.variation.bedutils.remove_bad(x)' | sort -V -k1,1 -k2,2n > /lustre/project/work/bedprep/tx/tmp5Eu_W3/8_2016-01-05_project_1st-merged-sort-callable-callableblocks.bed
cat: /lustre/project/work/align/1049tumor/8_2016-01-05_project_1st-merged-sort-callable-callableblocks.bed: Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    bcbio.variation.bedutils.remove_bad(x)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 70, in remove_bad
    if int(parts[2]) > int(parts[1]):
IndexError: list index out of range
' returned non-zero exit status 1
[2016-01-07T22:14Z] c4305.xxx.edu: Assigned coverage as 'amplicon' with 20.7% genome coverage and 0.0% offtarget coverage
[2016-01-07T22:15Z] c4305.xxx.edu: Recalibrating ['', '5001normal'] with GATK
[2016-01-07T22:24Z] c4415.xxx.edu: Assigned coverage as 'amplicon' with 6.9% genome coverage and 0.0% offtarget coverage
[2016-01-07T22:24Z] c4415.xxx.edu: Recalibrating ['', '1049tumor'] with GATK
[2016-01-07T23:21Z] c0905.xxx.edu: ipython: combine_sample_regions
[2016-01-07T23:44Z] c4308.xxx.edu: Identified 170 parallel analysis blocks
Block sizes:
  min: 4262
  5%: 27977.65
  25%: 163650.5
  median: 31018084.5
  75%: 31019594.25
  95%: 31024801.8
  99%: 39108842.99
  max: 58819774
Between block sizes:
  min: 259
  5%: 273.2
  25%: 329.5
  median: 423.0
  75%: 676.5
  95%: 1388.3
  99%: 4115.46
  max: 14211

[2016-01-07T23:44Z] c0905.xxx.edu: Timing: structural variation initial
[2016-01-07T23:44Z] c0905.xxx.edu: ipython: detect_sv
[2016-01-08T18:17Z] c0905.xxx.edu: Timing: alignment post-processing
[2016-01-08T18:17Z] c0905.xxx.edu: ipython: piped_bamprep
[2016-01-08T18:53Z] c4415.xxx.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; ./bcbio/bin/sambamba index -t 1 /lustre/project/work/bamprep/10132normal/4/tx/tmpYLFbC6/5_2016-01-05_project_1st-merged-sort-4_0_31019430-prep-prealign.bam
sambamba-index: Unable to write to stream
' returned non-zero exit status 1
[2016-01-08T18:53Z] c4415.xxx.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "./bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; java -Xms166m -Xmx1166m -XX:+UseSerialGC -Djava.io.tmpdir=/lustre/project/work/tx/tmp9PC3iD -jar ./bcbio/toolplus/gatk/3.4-46-gbc02625/GenomeAnalysisTK.jar -T PrintReads -L 7:155102739-159138663 -R ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /lustre/project/work/align/10132normal/5_2016-01-05_project_1st-merged-sort.bam -BQSR /lustre/project/work/align/10132normal/5_2016-01-05_project_1st-merged-sort.grp -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /lustre/project/work/bamprep/10132normal/7/tx/tmp2c1e4Y/5_2016-01-05_project_1st-merged-sort-7_155102738_159138663-prep-prealign.bam
INFO  12:53:07,427 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  12:53:07,429 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.4-46-gbc02625, Compiled 2015/07/09 17:38:12 
INFO  12:53:07,429 HelpFormatter - Copyright (c) 2010 The Broad Institute 
INFO  12:53:07,429 HelpFormatter - For support and documentation go to http://www.broadinstitute.org/gatk 
INFO  12:53:07,433 HelpFormatter - Program Args: -T PrintReads -L 7:155102739-159138663 -R ./bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /lustre/project/work/align/10132normal/5_2016-01-05_cowan_1st-merged-sort.bam -BQSR /lustre/project/work/align/10132normal/5_2016-01-05_project_1st-merged-sort.grp -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /lustre/project/work/bamprep/10132normal/7/tx/tmp2c1e4Y/5_2016-01-05_project_1st-merged-sort-7_155102738_159138663-prep-prealign.bam 
INFO  12:53:07,439 HelpFormatter - Executing as xxx@c4415.xxx.edu on Linux 2.6.32-504.23.4.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.7.0_85-mockbuild_2015_07_15_13_21-b00. 
INFO  12:53:07,440 HelpFormatter - Date/Time: 2016/01/08 12:53:07 
INFO  12:53:07,440 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  12:53:07,440 HelpFormatter - --------------------------------------------------------------------------------- 
INFO  12:53:07,566 GenomeAnalysisEngine - Strictness is SILENT 
INFO  12:53:08,465 ContextCovariate - 		Context sizes: base substitution model 2, indel substitution model 3 
INFO  12:53:08,528 GenomeAnalysisEngine - Downsampling Settings: No downsampling 
INFO  12:53:08,537 SAMDataSource$SAMReaders - Initializing SAMRecords in serial 
INFO  12:53:08,578 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 0.04 
INFO  12:53:08,596 IntervalUtils - Processing 4035925 bp from intervals 
INFO  12:53:08,666 GenomeAnalysisEngine - Preparing for traversal over 1 BAM files 
INFO  12:53:15,227 GATKRunReport - Uploaded run statistics report to AWS S3 
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the problems. The first issue with BED files looks like there might be empty or truncated lines in an input BED file. I'm not sure what happened there but pushed a fix to the BED file cleanup to try and resolve it. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
It should hopefully avoid that and work cleanly.

The second issue is Java complaining that it's unable to write to the temporary directory: `/lustre/project/work/tx/tmp9PC3iD` in this case. My guess is that this is a temporary issue due to shared filesystem weirdness and re-running with work cleanly. If you have consistent issues there it might be worth digging into why you'd have write permission issues there.

Hope this helps get your analyses moving.

**Comment by pengxiao78** [comment]
Thank you, Brad!

**Comment by pengxiao78** [comment]
Hi Brad,
When I was updating bcbio-nextgen, I found the following warning and error. Thank you for your help!


1.       ./bcbio/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
                warnings.warn(self.msg_depr % (key, alt_key))


2.       The following packages will be UPDATED:

    bamtools:                          2.4.0-0            --> 2.4.0-1                 (soft-link)
    bcbio-prioritize:                  0.0.2-0            --> 0.0.5-1                 (soft-link)
    bcftools:                          1.2-1              --> 1.3-0                   (soft-link)
    bcolz:                             0.11.0-py27_0      --> 0.12.1-np110py27_0      (soft-link)
    bio-vcf:                           0.9.0-0            --> 0.9.1-2                 (soft-link)
    cnvkit:                            0.7.4-py27_0       --> 0.7.4-py27_1            (soft-link)
    cufflinks:                         2.2.1-py27_0       --> 2.2.1-py27_1            (soft-link)
    cutadapt:                          1.8.3-py27_0       --> 1.9.1-py27_0            (soft-link)
    ete2:                              2.2.1072-py27_2    --> 2.3.10-py27_0           (soft-link)
    fastqc:                            0.11.4-1           --> 0.11.4-2                (soft-link)
    hisat2:                            2.0.0beta-py27_0   --> 2.0.1beta-py27_0        (soft-link)
    hmmlearn:                          20150818-py27_1    --> 20151031-py27_0         (soft-link)
    libtiff:                           4.0.6-0            --> 4.0.6-1                 (soft-link)
    metasv:                            0.4.0-py27_3       --> 0.4.0-py27_4            (soft-link)
    numexpr:                           2.4.4-np110py27_0  --> 2.4.6-np110py27_0       (soft-link)
    optitype:                          2015.10.20-py27_0  --> 2015.10.20-py27_1       (soft-link)
    pytabix:                           0.0.2-py27_0       --> 0.0.2-py27_1            (soft-link)
    r-curl:                            0.9.3-r3.2.2_0     --> 0.9.4-r3.2.2_0          (soft-link)
    r-mass:                            7.3_44-r3.2.2_0    --> 7.3_45-r3.2.2_0         (soft-link)
    r-mgcv:                            1.8_7-r3.2.2_0     --> 1.8_9-r3.2.2_0          (soft-link)
    r-rcpp:                            0.12.1-r3.2.2_0    --> 0.12.2-r3.2.2_0         (soft-link)
    r-rgl:                             0.95.1337-r3.2.2_0 --> 0.95.1367-r3.2.2_0      (soft-link)
    r-roxygen2:                        4.1.1-r3.2.2_0     --> 5.0.1-r3.2.2_0          (soft-link)
    r-stringi:                         0.5_5-r3.2.2_0     --> 1.0_1-r3.2.2_0          (soft-link)
    sailfish:                          0.7.6-0            --> 0.9.0-0                 (soft-link)
    samtools:                          1.2-1              --> 1.3-0                   (soft-link)
    simple_sv_annotation:              2015.11.05-py27_0  --> 2015.11.24-py27_0       (soft-link)
    singledispatch:                    3.4.0.3-py27_0     --> 3.4.0.3-py27_1          (soft-link)
    star:                              2.5.0a-0           --> 2.5.0c-0                (soft-link)
    stringtie:                         1.1.2-0            --> 1.2.0-1                 (soft-link)
    varscan:                           2.4.0-0            --> 2.4.0-1                 (soft-link)

Fetching packages ...
Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/bcbio/linux-64/rsa-3.1.4-py27_0.tar.bz2: https://conda.anaconda.org/bcbio/linux-64/rsa-3.1.4-py27_0.tar.bz2

Fatal error: local() encountered an error (return code 1) while executing '/lustre/work/unmc_gudalab/pxiao/parallel/bcbio/anaconda/bin/conda install -y -c bcbio -c bioconda -c r age-metasv bamtools bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.24.0 bio-vcf biobambam bowtie2 bwa bwakit cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt delly fastqc freebayes=0.9.21.26 gatk-framework gemini glpk grabix hall-lab-svtools hisat2 hmmlearn htseq htslib kraken lofreq lumpy-sv macs2 manta metasv mirdeep2 moreutils novoalign oncofuse optitype parallel pbgzip phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap razers3 rtg-tools sailfish sambamba samblaster samtools scalpel seqbuster seqtk sickle-trim simple_sv_annotation snpeff spades star stringtie subread svtyper tdrmapper theta2 tophat ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java variant-effect-predictor varscan vawk vcflib viennarna vt wham awscli p7zip s3gof3r perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.

**Comment by chapmanb** [comment]
Peng;
Sorry about the upgrade issues. We're currently fighting with an issue with anaconda installs. See #1179 for more details about the current issue. I've filed a bug upstream so hopefully the conda team will be able to resolve the underlying issue. Sorry to have you stuck right now with install problems.

**Comment by pengxiao78** [comment]
Brad,
Thank you for letting me know this. However, could you please expect when it will be solved? I am catching a deadline for the data analysis, which is on next week.
Thank you again!

**Comment by chapmanb** [comment]
Peng;
Sorry we're dependent on the anaconda folks for a real fix upstream but to get you going right away I posted a workaround here:

https://github.com/chapmanb/bcbio-nextgen/issues/1179#issuecomment-171413405

If you copy over the problem packages and re-start the upgrade it should hopefully finish cleanly for you. Hope this helps get you going.

**Comment by pengxiao78** [comment]
Brad,
I just ran the command that you posted. The packages were successfully downloaded and moved to the ./bcbio/anaconda/pkgs/
However, when I re-ran the command
bcbio_nextgen.py upgrade -u development
It still failed with the same error.
Thanks!
Peng

**Comment by chapmanb** [comment]
Peng;
I'm not positive what's going on with pulling in the rsa module from bcbio since that got removed from the repo to avoid these problems. Could you try removing the temporary cloudbiolinux install (`rm -rf tmpbcbio-install`) and re-running? You might have an older cached version pointing at the wrong place. Hope this gets it going for you.

**Comment by pengxiao78** [comment]
Brad,
I did what you said and re-ran the upgrade. Unfortunately, it still did not work. The same error.

Error: MD5 sums mismatch for download: https://conda.anaconda.org/r/linux-64/singledispatch-3.4.0.3-py27_1.tar.bz2 (d444d0a9302013abd789d18f56cd878e != 442c7a8232b2ebd4ee3dd127111827f1)
…
Aborting.

**Comment by chapmanb** [comment]
Peng;
The good news is you've moved on to a problem with a different package. This is one of the ones we should have been downloading with the workaround. This sounds like the files did not get copied to the right place. conda shouldn't try to re-download them if they're already present in ./bcbio/anaconda/pkgs. If you do `ls -lh ./bcbio/anaconda/pkgs/singledispatch*`, what do you see? There should be the downloaded `singledispatch-3.4.0.3-py27_1.tar.bz2` file from the workaround there. Hope this helps.

**Comment by pengxiao78** [comment]
Brad,
Yes, I saw singledispatch-3.4.0.3-py27_1.tar.bz2 under ./bcbio/anaconda/pkgs/
That MD5 sums mismatch error was generated after the file downloaded in the ./bcbio/anaconda/pkgs/.
It seems that conda did not skip the re-download step.
Thanks.
