### ISSUE TITLE
python-gulags MD5 error aws cluster start

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1178]
Hi, I am trying to configure a aws cluster but I am always getting this error.

Thanks for the support!
Alessandro

$ bcbio_vm.py aws cluster start

TASK: [Install bcbio_vm] ****************************************************** 
failed: [frontend001] => {"changed": true, "cmd": "~ubuntu/install/bcbio-vm/data/anaconda/bin/conda install --yes -c https://conda.binstar.org/bcbio bcbio-nextgen-vm", "delta": "0:00:24.102311", "end": "2016-01-11 21:20:56.354529", "rc": 1, "start": "2016-01-11 21:20:32.252218", "warnings": []}
stderr: Error: MD5 sums mismatch for download: https://conda.binstar.org/bcbio/linux-64/python-gflags-2.0-py27_0.tar.bz2 (4c890f4b2356dfedb1aaffd0928d4574 != f087a61b07d9285a03b8fc44ad0624ea)
stdout: Fetching package metadata: ......

**Comment by chapmanb** [comment]
Continuing discussion in #1179
