### ISSUE TITLE
aws cluster start md5 voluptuous

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1179]
Hi, I am getting this md5 mismatch with bcbio_vm.py aws cluster start.

Thanks!

TASK: [Install bcbio_vm] ****************************************************** 
failed: [frontend001] => {"changed": true, "cmd": "~ubuntu/install/bcbio-vm/data/anaconda/bin/conda install --yes -c https://conda.binstar.org/bcbio bcbio-nextgen-vm", "delta": "0:00:27.507556", "end": "2016-01-11 22:00:15.614711", "rc": 1, "start": "2016-01-11 21:59:48.107155", "warnings": []}
stderr: Error: MD5 sums mismatch for download: https://conda.binstar.org/bcbio/linux-64/voluptuous-0.8.5-py27_0.tar.bz2 (a64f06649f765402d3fdda6044ed6b7d != a110db3ff0a76d888eda085ddf504fb7)
stdout: Fetching package metadata: ......
Solving package specifications: .....................................................

**Comment by apastore** [comment]
also for pyasn1-modules and python-gulags I get the same error.

and the package rsa-3.1.4 can not be found.

Thanks!
failed: [frontend001] => {"changed": true, "cmd": "~ubuntu/install/bcbio-vm/data/anaconda/bin/conda install --yes -c https://conda.binstar.org/bcbio bcbio-nextgen-vm", "delta": "0:00:26.120759", "end": "2016-01-11 22:08:29.579439", "rc": 1, "start": "2016-01-11 22:08:03.458680", "warnings": []}
stderr: Error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/bcbio/linux-64/rsa-3.1.4-py27_0.tar.bz2: https://conda.binstar.org/bcbio/linux-64/rsa-3.1.4-py27_0.tar.bz2
stdout: Fetching package metadata: ......
Solving package specifications: .....................................................
Package plan for installation in environment /home/ubuntu/install/bcbio-vm/data/anaconda:

**Comment by chapmanb** [comment]
Alessandro;
Sorry about the problems. This looks like it might have been a temporary problem with anaconda.org package installation. I can download and install them all cleanly now. If you re-try do things work cleanly now? Please let us know if not and we can investigate further.

**Comment by apastore** [comment]
Hi Brand, now it look they have been removed from https://conda.anaconda.org/bcbio.

Thanks!

failed: [frontend001] => {"changed": true, "cmd": "~ubuntu/install/bcbio-vm/data/anaconda/bin/conda install --yes -c https://conda.binstar.org/bcbio bcbio-nextgen-vm", "delta": "0:00:11.332885", "end": "2016-01-12 18:08:05.013175", "rc": 1, "start": "2016-01-12 18:07:53.680290", "warnings": []}
stderr: Error: Could not find some dependencies for bcbio-nextgen-vm: elasticluster, voluptuous

Did you mean one of these?

    bcbio-nextgen-vm, bcbio-nextgen

Did you mean one of these?

    elasticluster, starcluster

You can search for this package on anaconda.org with

    anaconda search -t conda voluptuous

 (and similarly for the other packages)

You may need to install the anaconda-client command line client with

    conda install anaconda-client
stdout: Fetching package metadata: ......
Solving package specifications: ...........................

FATAL: all hosts have already failed -- aborting

**Comment by chapmanb** [comment]
Alessandro;
Sorry about the continued problems. It looks like there is some kind of issue with copied packages on anaconda.org. I removed the ones in bcbio to try and move it forward but am now stuck on ones in standard channels and submitted a report upstream to the continuum folks to see if they can identify the problem.

Practically, we migrated the packages over to the bioconda repository so the right install will now be:

conda install -c bioconda bcbio-nextgen-vm

once I can get the linked packages sorted out. I'll report back here and update the documentation when it works again. Thanks so much for the patience.

**Comment by apastore** [comment]
Thanks you so much for you continues Support !!
I was just testing the AWS/bcbio workflow nothing more!
Best,
Alessandro

**Comment by chapmanb** [comment]
Sorry, we're still waiting for a fix on this upstream but if you're stuck an immediate workaround is to manually download the packages and put them into the anaconda packages directory:
```
wget https://anaconda.org/asmeurer/ncurses/5.9/download/linux-64/ncurses-5.9-4.tar.bz2 \
     https://anaconda.org/asmeurer/nlopt/2.4.2/download/linux-64/nlopt-2.4.2-1.tar.bz2 \
     https://anaconda.org/asmeurer/glib/2.43.0/download/linux-64/glib-2.43.0-2.tar.bz2 \
     https://anaconda.org/asmeurer/singledispatch/3.4.0.3/download/linux-64/singledispatch-3.4.0.3-py27_1.tar.bz2 \
    && mv *.tar.bz2 /PATH/TO/BCBIO/data/anaconda/pkgs
```
and then restart the failing command. conda will use the pre-downloaded packages and should resolve everything else cleanly. Sorry again about the issues and hope this helps.

**Comment by chapmanb** [comment]
Alessandro;
This is fixed in anaconda.org now so install/upgrades should be working again. Thanks much for reporting it and sorry about the issues.
