### ISSUE TITLE
gatk / bcbio-nextgen compatibility?

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1181]
Quick question: is bcbio-nextgen compatible with the latest gatk, release 3.5? Or should I go for 3.4?

**Comment by chapmanb** [comment]
Pär;
I've tested small runs with 3.5 and the latest development version works cleanly. I haven't yet done a full whole genome validation run in comparison to 3.4 but I don't anticipate any issues with the latest version. Hope this helps.
