### ISSUE TITLE
Alignment error

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1185]
Hi Brad,
I moved the fastq files into another cluster computer with the successfully upgraded bcbio-nextgen development version and re-ran the tumor-normal variant calling pipeline. I found an error as follows, which stopped the running. Could you please help to figure it out?
Thanks!

[2016-01-14T10:39Z] c2713.xxx.edu: Aligning lane 30_2016-01-13_project-merged with bwa aligner
[2016-01-14T10:39Z] c2713.xxx.edu: Uncaught exception occurred
Traceback (most recent call last):
  File "/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/parallel/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /parallel/bcbio/anaconda/bin/bwa mem  -c 250 -M -t 16  -R '@RG\tID:30\tPL:illumina\tPU:30_2016-01-13_project-merged\tSM:11510tumor' -v 1 /parallel/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /lustre/project/work/align_prep/11510tumor_R1.trimmed.fastq.gz 220000001 229020936) <(grabix grab /lustre/project/work/align_prep/11510tumor_R2.trimmed.fastq.gz 220000001 229020936)  | /parallel/bcbio/anaconda/bin/samblaster --addMateTags -M --splitterFile >(/parallel/bcbio/anaconda/bin/samtools sort -@ 16 -m 682M -T /lustre/project/work/align/11510tumor/split/tx/tmpjQYaCN/30_2016-01-13_project-merged-sort-220000001_229020936-sorttmp-spl -o /lustre/project/work/align/11510tumor/split/tx/tmpYmjenK/30_2016-01-13_project-merged-sort-220000001_229020936-sr.bam /dev/stdin) --discordantFile >(/parallel/bcbio/anaconda/bin/samtools sort -@ 16 -m 682M -T /lustre/project/work/align/11510tumor/split/tx/tmpjQYaCN/30_2016-01-13_project-merged-sort-220000001_229020936-sorttmp-disc -o /lustre/project/work/align/11510tumor/split/tx/tmpGgd0uC/30_2016-01-13_project-merged-sort-220000001_229020936-disc.bam /dev/stdin) | samtools view -b -S -u - | sambamba sort -N -t 16 -m 682M --tmpdir /lustre/project/work/align/11510tumor/split/tx/tmpjQYaCN/30_2016-01-13_project-merged-sort-220000001_229020936-sorttmp-full -o /lustre/project/work/align/11510tumor/split/tx/tmpjQYaCN/30_2016-01-13_project-merged-sort-220000001_229020936.bam /dev/stdin
samblaster: Version 0.1.22
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Opening /dev/fd/62 for write.
samblaster: Opening /dev/fd/63 for write.
[grabix] requested lines exceed the number of lines in the file.
[W::bseq_read] the 2nd file has fewer sequences.
[W::bseq_read] the 2nd file has fewer sequences.
[gzclose] buffer error
samblaster: Loaded 84 header sequence entries.
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
It looks like something is problematic with your input fastq files -- the second pair has less reads than the first. If you do a line count on the original files, do the numbers match? Is it possible something happened during the transfer process? Hope this helps debug.

**Comment by pengxiao78** [comment]
I checked both lines and file sizes of the original fastq files. They are all the same, no changes during the transfer. Thanks.

**Comment by chapmanb** [comment]
Sorry, this is a bit tricky to offer more advice with the information I have. My only other thought is that something went wrong with the alignment preparation step and grabix indexing. You could check 
```
 /lustre/project/work/align_prep/11510tumor_R1.trimmed.fastq.gz
 /lustre/project/work/align_prep/11510tumor_R2.trimmed.fastq.gz
```
to be sure they're also okay and the same number of records. If so, maybe the corresponding grabix index files (.gbi) are different and need to be regenerated for one or both of the files? Hope one of these helps explain it.

**Comment by pengxiao78** [comment]
This is interesting. I did find the two .gbi files have different sizes and line accounts for 11510tumor_R1 and 11510tumor_R2. However, other samples have the same sizes and lines. How did this happen for bcbio? I never found such problem previously. How can I regenerate the correct .gbi files?
Thanks!

**Comment by chapmanb** [comment]
That's problematic. You would also want to check that the align_prep bgzipped files have identical counts as well, perhaps something happened there. To regenerate, just remove any problem `.gz` and `.gbi` files and bcbio will remake them. Hope this gets things going for you.

**Comment by lpantano** [comment]
Hi @pengxiao78 

I am closing this because it seems an old issue. Hopefully you got it working. Come back if you find other issues.

cheers

**Comment by SarahBeecroft** [comment]
This worked for me as well!
