### ISSUE TITLE
No module named singledispatch error during GATK install

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1186]
I just installed bcbio-nextgen, and had to manually download and copy the ncurses, glib and singledispatch packages, as shown [elsewhere](https://github.com/chapmanb/bcbio-nextgen/issues/1179). After that I tried to install GATK, with the

> /data/t-tcga/esebesty/bcbio/tool/bin/bcbio_nextgen.py upgrade --tools --toolplus gatk=/data/t-tcga/esebesty/install/GenomeAnalysisTK.jar`

command, but I'm getting the following error:

> /data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))
Traceback (most recent call last):
  File "/data/t-tcga/esebesty/bcbio/tool/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6a0', 'bcbio_nextgen.py')
  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 745, in run_script
    
>  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1670, in run_script
    
>  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6a0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 37, in <module>
    from bcbio.server import main as server_main
 > File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/server/main.py", line 3, in <module>
    import tornado.web
>  File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/tornado/web.py", line 84, in <module>
    from tornado import gen
 > File "/data/t-tcga/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 97, in <module>
    from singledispatch import singledispatch  # backport
ImportError: No module named singledispatch

I guess this is related to the anaconda md5 problem. Can I correct the `singledispatch` issue somehow manually, without a reinstall?

**Comment by chapmanb** [comment]
Sorry about the issue. I hope the underlying conda problem will be resolved soon so this isn't causing so much breakage. I'm not sure why you didn't get singledispatch installed as part of the process, but to fix you could try doing re-installing it cleanly:
```
/data/t-tcga/esebesty/bcbio/data/anaconda/bin/conda uninstall singledispatch
rm -rf /data/t-tcga/esebesty/bcbio/data/anaconda/pkgs/singledispatch*
wget https://anaconda.org/asmeurer/singledispatch/3.4.0.3/download/linux-64/singledispatch-3.4.0.3-py27_1.tar.bz2
mv singledispatch-3.4.0.3-py27_1.tar.bz2 /data/t-tcga/esebesty/bcbio/data/anaconda/pkgs
/data/t-tcga/esebesty/bcbio/data/anaconda/bin/conda install -c asmeurer singledispatch
```
Fingers crossed that fixes it for you.

**Comment by razZ0r** [comment]
It worked! Thanks and looking forward to using the pipeline.
