### ISSUE TITLE
report-ready.Rmd, reshape and offtarget_pct

### ISSUE THREAD

**Issue by przemekl** [chapmanb/bcbio-nextgen#1190]
While processing the report-ready.Rmd file noticed two problems.
Script include R 'reshape' library, but installed is 'reshape2'.
After manual install of 'reshape', script stop execution at lines 85-88 with message.
"object 'offtarget_pct' not found"

**Comment by lpantano** [comment]
Hi, 

sorry about the problem. 
could you tell me what analysis you ran? This may help me to debug the problem.

thanks!

**Comment by przemekl** [comment]
Thank you.
Error with offtarget_pct has been corrected after your latest commit to qc.Rmd but I have subsequent problem, this time with "nucleotide content section" from report-ready.Rmd file. Script stop execution complaining about "object 'nt' not found".

My file "Per_base_sequence_content.tsv" contains the header
"Base  G A T C sample"

I hope it will help debug the problem.

**Comment by lpantano** [comment]
Hi,

sorry about this. It seems a problem with reshape2. Any chance you can 
run the code step by step as bellow, and tell me what you have when you 
do head(dd).

qual  =  read.table(file.path(path_results,"fastqc","Per_base_sequence_content.tsv"),header=T,sep=  "\t",check.names  =  F,colClasses=list("sample"="character"))
qual$sample  =  as.character(qual$sample)

qual$Base  =  as.numeric(qual$Base)
dd  =  melt(qual,id.vars  =  c("Base","sample"),variable_name  =  c("nt"))



You will need to load all the libraries as you have in the report, and 
as well path_result should point to the files are.

As well can you copy here the output of sessionInfo()?

thanks a lot

**Comment by przemekl** [comment]
This is output from head(dd)
  Base sample variable    value
1    1  12691        G 21.07443
2    2  12691        G 23.18432
3    3  12691        G 23.50918
4    4  12691        G 23.84941
5    5  12691        G 24.26797
6    6  12691        G 24.48333

and from SessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
other attached packages:
 [1] dplyr_0.4.3        rmarkdown_0.8.1    reshape2_1.4.1     tidyr_0.3.1
 [5] knitr_1.11         RColorBrewer_1.1-2 gtools_3.5.0       gridExtra_2.0.0
 [9] scales_0.3.0       pheatmap_1.0.8     ggplot2_1.0.1
loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      magrittr_1.5     MASS_7.3-45      munsell_0.4.2
 [5] colorspace_1.2-6 R6_2.1.1         stringr_1.0.0    plyr_1.8.3
 [9] tools_3.2.2      parallel_3.2.2   grid_3.2.2       gtable_0.1.2
[13] DBI_0.3.1        htmltools_0.2.6  lazyeval_0.1.10  digest_0.6.8
[17] assertthat_0.1   stringi_1.0-1    proto_0.3-10

Hope this helps

**Comment by lpantano** [comment]
Hi, thanks. 

I think is a change in the parameter for reshape2. If you change to this:

dd = melt(qual, id.vars = c("Base", "sample"), variable.name = c("nt"))

does the render passes that point?

If you don't mind I will wait to push the version until we get the whole report working for you, it would help a lot to create a more stable report. If it is a big change I will update directly the package in bioconda. Meanwhile can you try to manually fix this line?

thanks a lot!

**Comment by przemekl** [comment]
Yes, renderer passes that line.
You should modify variable.name also at "Read nuceotide biases" section.

Thank you

**Comment by lpantano** [comment]
thanks for the feedback. Let me know if you find more issues.

**Comment by lfaller** [comment]
I am also encountering an issue with ```offtarget_pct``` in the ```report-ready.Rmd``` file (for the RNAseq pipeline).

R complains about not knowing what ```offtarget_pct``` is. It's in the section on "Offtarget reads" but it looks like it is never defined anywhere else in the file.

This is the piece of code:

``### Offtarget reads

ggplot(qc, aes(x=sample, y=offtarget_pct*100)) +
    geom_bar(stat = 'identity') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Do you have any ideas, Lorena?

Thanks a bunch!!
~Lina

**Comment by lpantano** [comment]
hum, i will look at it. this is for RNAseq pipeline or variant calling. If you want the basic stats for RNAseq you can remove this for now. Meanwhile i will work on that, I recently did a big change, and maybe I forgot to skip this some way. Thanks for the feedback.

**Comment by lpantano** [comment]
@lfaller, as well, i think you have an old version of the package. I updated that 12 days ago. Any chance you didn't update bcbio since then?

**Comment by lfaller** [comment]
Ah, good point. I installed it on 2/24, so it's a bit older. I'll update the code.

Is there shortcut to just regenerating the report, or should I just call the main bcbio script again?

Thanks!!

**Comment by lpantano** [comment]
you can remove the Rmd and run bcbio again. Should create the new Rmd quickly, it is just taking the template and copying there.  tell me if that fixes it, it would be that you have other problem since it was a moderate change. 

thanks!

**Comment by lfaller** [comment]
I upgraded bcbio using this command:

```
bcbio_nextgen.py upgrade -u stable --tools --data
```

And then reran the `bcbio_nextgen.py` script. It's taking a bit longer and I also got a new error message:

```
...
[2016-03-07T15:27Z] run local -- checkpoint passed: rnaseqcount-singlethread
[2016-03-07T15:27Z] Timing: estimate expression (single threaded)
[2016-03-07T15:27Z] multiprocessing: run_dexseq
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
[2016-03-07T15:27Z] DEXseq is not installed, skipping exon-level counting.
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
[2016-03-07T15:27Z] DEXseq is not installed, skipping exon-level counting.
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
[2016-03-07T15:27Z] DEXseq is not installed, skipping exon-level counting.
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
[2016-03-07T15:27Z] DEXseq is not installed, skipping exon-level counting.
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
[2016-03-07T15:27Z] DEXseq is not installed, skipping exon-level counting.
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
[2016-03-07T15:27Z] DEXseq is not installed, skipping exon-level counting.
[2016-03-07T15:34Z] Resource requests: gatk; memory: 3.50; cores: 1
[2016-03-07T15:34Z] Configuring 6 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2016-03-07T15:34Z] run local -- checkpoint passed: rnaseq-variation
[2016-03-07T15:34Z] Timing: RNA-seq variant calling
[2016-03-07T15:34Z] multiprocessing: run_rnaseq_variant_calling
[2016-03-07T15:34Z] multiprocessing: run_rnaseq_joint_genotyping
[2016-03-07T15:34Z] Resource requests: fastqc, gatk, kraken, qualimap, samtools; memory: 2.00, 3.50, 2.00, 8.00, 2.00; cores: 16, 1, 4, 1, 16
[2016-03-07T15:34Z] Configuring 1 jobs to run, using 4 cores each with 34.4g of memory reserved for each job
[2016-03-07T15:34Z] run local -- checkpoint passed: qc
[2016-03-07T15:34Z] Timing: quality control
[2016-03-07T15:34Z] multiprocessing: pipeline_summary
[2016-03-07T15:34Z] Generating summary files: UHRR_rep1
[2016-03-07T16:09Z] Generating summary files: HBRR_rep1
```

Once it's done with the run, I'll try to manually install `DEXSeq` . In the meantime, I took out the chunk that references `offtarget_pct`.

Thanks!

**Comment by lpantano** [comment]
Hi,

I think that DEXseq error should have been as well before. It is in case DEXSeq is not installed, so bcbio skip exon counting. I don’t know if bcbio should be using bcbio DEXseq installation or not, maybe @roryk knows better. Beside that, everything seems ok. Maybe it is taking longer because is not parallelizing now the last step, you could do this by removing qc.done inside checkpoints_parallel.

let me know what happens then! https://github.com/roryk/bcbio.rnaseq is the tool to use if you want a nice report for  RNAseq.

**Comment by lfaller** [comment]
Mysteriously, it didn't have DEXseq problems before... I found the following in my log file:

```
Counting exon-level counts with /home/lfaller/bioinfohd1/playground/rna_seq_example/seqc-test/seqc/work/align/UHRR_rep1/1_2016-02-25_seqc_tophat/UHRR_rep1.bam and /home/lfaller/local/share/bcbio/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.dexseq.gff3.
```

I'll look into it... Maybe I messed up something on my system between Thursday and today ;-)

`offtarget_pct` still isn't defined, but I just put an `eval=FALSE` into the chunk and that's fine for now.

Thanks for the pointer to Rory's rnaseq tool -- I'll check it out!

**Comment by lpantano** [comment]
That's weird. For some reason is not getting updating. In the new report there is no longer that variable :)
A way to force the update is to use conda command inside bcbio installation to update bcbreport like this:

`/path_to_bcbio/anaconda/bin/conda install bcbreport -c bioconda`

that should get you version 0.99.22, at least to confirm that this can be updated? thanks!

**Comment by lpantano** [comment]
as a side note, you need to remove the Rmd report in the work directory and the final directory if you are using the one in the final. I think that if it exists won't be updated the one in the final directory.

**Comment by lfaller** [comment]
I think that did it! The variable is gone :-) thanks!!
