### ISSUE TITLE
Error Downloading Genome Information

### ISSUE THREAD

**Issue by rb5000** [chapmanb/bcbio-nextgen#1193]
Hi,

I was able to install all packages successfully, but when trying to install the GRCh37 genome, I run into this error:

```
--2016-01-19 17:14:37--  http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/wgEncodeDacMapabilityConsensu
sExcludable.bed.gz
Resolving hgdownload.cse.ucsc.edu... 128.114.119.163
Connecting to hgdownload.cse.ucsc.edu|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

--2016-01-19 17:29:39--  (try: 2)  http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/wgEncodeDacMapabili
tyConsensusExcludable.bed.gz
Connecting to hgdownload.cse.ucsc.edu|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Retrying.

...

--2016-01-19 19:30:24--  (try:10)  http://hgdownload.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/wgEncodeDacMapabilityConsensusExcludable.bed.gz
Connecting to hgdownload.cse.ucsc.edu|128.114.119.163|:80... connected.
HTTP request sent, awaiting response... 
```
Everything else appears to have no errors.

The command I am running is:
```
bcbio_nextgen.py upgrade -u stable --tools --data --genomes GRCh37
```
Any suggestions?

Thanks,

Robert

**Comment by chapmanb** [comment]
Robert;
Sorry about the issues. This download works for me right now if I try it, so it might have been a temporary issue with UCSC downloads. Could you try running the same upgrade command to see if it finishes cleanly or still runs into issues? If it still fails, does the download work outside of bcbio on your machine, either via wget or a web browser. Happy to debug further if it fails but hopefully a re-run will fix it.

**Comment by rb5000** [comment]
Sorry for my delayed response,

Thank you so much for your help. I tried re-running it, and the download works outside of bcbio on the browser and through wget. Any suggestions?

Thanks,

Robert

**Comment by chapmanb** [comment]
Robert -- does it still fail if you re-run the same bcbio install command? I'm trying to understand if it consistently fails in bcbio, and works manually, or if it was a temporary issue. Hopefully re-running the upgrade command works.

**Comment by rb5000** [comment]
Yes, it still does. I tried rerunning both with an install and the upgrade.

Thanks again,

Robert

**Comment by chapmanb** [comment]
Robert;
Sorry about the continued problems. I'm confused as to why it would fail during the install but not externally. The installer (via CloudBioLinux) creates a little bash script that does a wget, so I'm not sure right now why that would work differently than externally calling wget:

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/GA4GH_problem_regions.yaml#L24

Are there firewalls or proxies or other differences which might not be getting passed through correctly during the call?

If you're totally stuck, you could run that command externally and put the resulting file into the work directory '/path/ot/bcbio/data/genomes/GRCh37/txtmp` as `coverage/problem_regions/ENCODE/wgEncodeDacMapabilityConsensusExcludable.bed` and then re-run. Sorry to not have a better idea of what is going on but hope this helps.

**Comment by cenielyj** [comment]
I have encounter the same issue, since outside US, the downloading is very slow and not very stable, it is better to download manually using some download software, I am using Thunder for instance. Also, if a FTP is provided it will much better, we can just download all the data and paste into the final path.

**Comment by chapmanb** [comment]
Non-US download discussion moved to #1211.

**Comment by rb5000** [comment]
Hi,

I ran the command externally and was able to get everything installed. 

Thank you!
