### ISSUE TITLE
STAR output files

### ISSUE THREAD

**Issue by zahrahaider** [chapmanb/bcbio-nextgen#1195]
Hi!

I am relatively new to RNA-seq analysis and was wondering if the output files from STAR aligner include .BED or .VCF files or file formats similar to insertions.bed and deletions.bed from TopHat. I would like to view insertions and deletions as separate tracks in IGV. 

Best Regards
Zahra

**Comment by roryk** [comment]
Hi Zahra,

STAR doesn't report files like those AFAIK, but you can call SNPs and indels from RNA-seq data with bcbio-nextgen if you turn on variant calling. Instructions on how to do that are here:

`https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#rna-sequencing`

If you set `variantcaller: [gatk]` in your YAML file, it will produce a set of combined variant calls for all of your samples.

Hope that helps.
