### ISSUE TITLE
Flag variants that were decomposed from complex variants (freebayes vcfallelicprimitives)

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1209]
Hi, 

Would it be possible to add / hard code the -t argument to vcfallelicprimitives in the freebayes variant calling pipe:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L125

This will tag the decomposed variants and make it easier to handle them correctly downstream. A True / False INFO field will be added to variants that were decomposed from complex variants by vcfallelicprimitives. 

```
vcfallelicprimitives -h
usage: vcfallelicprimitives [options] [file]

options:
    -m, --use-mnps          Retain MNPs as separate events (default: false).
    -t, --tag-parsed FLAG   Tag records which are split apart of a complex allele with this flag.
    -L, --max-length LEN    Do not manipulate records in which either the ALT or
                            REF is longer than LEN (default: 200).
    -k, --keep-info         Maintain site and allele-level annotations when decomposing.
                            Note that in many cases, such as multisample VCFs, these won't
                            be valid post-decomposition.  For biallelic loci in single-sample
                            VCFs, they should be usable with caution.
    -g, --keep-geno         Maintain genotype-level annotations when decomposing.  Similar
                            caution should be used for this as for --keep-info.

```
Thank you !

**Comment by chapmanb** [comment]
Neill -- thanks for the great suggestion. The latest development version now flags these with a `DECOMPOSED` tag that will hopefully help with identifying and post-processing them. Thanks again.

**Comment by NeillGibson** [comment]
Thank you Brad.
