### ISSUE TITLE
custom reference genome?

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1216]
Hi,

There used to be a script named genome_setup.py that allowed you to use custom genomes with the bcbio-nextgen pipeline. I cannot find this script now, is it possible still somehow to do this? We'd like to do somatic calling on a microbial genome.

//Pär

**Comment by roryk** [comment]
Hi Pär,

It is still there, it is called `bcbio_setup_genome.py`

**Comment by parlar** [comment]
Alright, super!
