### ISSUE TITLE
bcbio_setup_genome issue

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1218]
Hi,

I'm trying to run ```bcbio_setup_genome.py``` to enable/prepare a microbial genome for "somatic" variant calling. 

However, I get this error:

```
$ bcbio_setup_genome.py -f GCF_000008985.1_ASM898v1_genomic.fna -i bwa -n AJ749949.2 -b 2Cloning into 'cloudbiolinux'...
remote: Counting objects: 12125, done.
remote: Total 12125 (delta 0), reused 0 (delta 0), pack-reused 12125
Receiving objects: 100% (12125/12125), 7.90 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (6901/6901), done.
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_setup_genome.py", line 192, in <module>
    env.picard_home = config_utils.get_program("picard", config, ptype="dir")
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 186, in get_program
    return _get_program_dir(name, pconfig)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 237, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for picard
```

If using the ```--gff3``` flag I also get this error:

```
$ bcbio_setup_genome.py -f GCF_000008985.1_ASM898v1_genomic.fna --gff3 GCF_000008985.1_ASM898v1_genomic.gff -i bwa -n AJ749949.2 -b 2
usage: bcbio_setup_genome.py [-h] [-c CORES] -f FASTA [--gff3] [-g GTF] -n
                             NAME -b BUILD
                             [-i [{bowtie,bowtie2,bwa,novoalign,rtg,snap,star,ucsc,seq,hisat2} [{bowtie,bowtie2,bwa,novoalign,rtg,snap,star,ucsc,seq,hisat2} ...]]]
                             [--ercc] [--mirbase MIRBASE]
                             [--srna_gtf SRNA_GTF]
bcbio_setup_genome.py: error: unrecognized arguments: GCF_000008985.1_ASM898v1_genomic.gff
```

The data is downloaded from ncbi and the gff file is a gff-version 3 file (gff-sepc-version 1.21).

Any assistance is appreciated.

**Comment by roryk** [comment]
Hi Pär,

`--gff3` is a flag, so you pass the GFF3 file like this: `--gff3 -g GCF_000008985.1_ASM898v1_genomic.gff`

Let us know if you run into any troubles with the GFF3 file, we haven't used them much so you might run into an issue.

**Comment by parlar** [comment]
Thanks! 

The other error (the first) still persists though: ```ValueError: Could not find directory in config for picard``` .

**Comment by roryk** [comment]
Hi Pär,

Is `picard` in your path? It should be in the same directory that `bcbio_setup_genome.py` is installed, so something like `/usr/local/share/bcbio/bin/picard`.

**Comment by TakashiKoyama** [comment]
Hi,

I got same error for picard.
I made a symlink in my PATH.
```
$ LANG=C ls -al /usr/local/genome/bin/picard
lrwxrwxrwx. 1 root root 52 Feb  8 23:15 /usr/local/genome/bin/picard -> /home/samba/public/software/bcbio-nextgen/bin/picard
```
And got an error when execute bcbio_setup_genome.py.
```
$ bcbio_setup_genome.py -f mygenome.fasta -n myspecies -b mygenome -i bwa
Traceback (most recent call last):
  File "/usr/local/genome/bin/bcbio_setup_genome.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.6a0', 'bcbio_setup_genome.py')
  File "/home/samba/public/software/bcbio-nextgen/share/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
  File "/home/samba/public/software/bcbio-nextgen/share/anaconda/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script
  File "/home/samba/public/software/bcbio-nextgen/share/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.6a0-py2.7.egg-info/scripts/bcbio_setup_genome.py", line 192, in <module>
    env.picard_home = config_utils.get_program("picard", config, ptype="dir")
  File "/home/samba/public/software/bcbio-nextgen/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 185, in get_program
    return _get_program_dir(name, pconfig)
  File "/home/samba/public/software/bcbio-nextgen/share/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 236, in _get_program_dir
    raise ValueError("Could not find directory in config for %s" % name)
ValueError: Could not find directory in config for picard
```
Symlink doesn't work?

Takashi

**Comment by parlar** [comment]
Strangely, my ```bcbio/bin``` dir is not even there on this machine. On another machine, which was recently re-installed, a bcbio/bin dir is present and contains softlinks to various binaries, including picard.

I tried to add a ```bcbio/bin``` dir to the first machine and a softlink to the picard binary under the ```bcbio/anaconda/bin``` dir, but similar to Takashi's experience this did not work. There is a picard binary present in my users path ```/usr/local/bin/picard``` but this does not seem to be visible by the bcbio_setup_genome script.

**Comment by roryk** [comment]
Sorry about the problems, I fixed the issue, but also found another bug which I'm fixing now.

**Comment by parlar** [comment]
Great! Thanks.

**Comment by chapmanb** [comment]
Thanks all for the reports and sorry about the confusion. Rory, thanks for tracking this down. With your fixes, could we assume `picard` is on the PATH rather than looking up from the java directory? It should always get installed with conda and a wrapper script now, and I'd like to deprecate the old java directory structure. Thanks much.

**Comment by roryk** [comment]
@chapmanb, yup, that was the fix.

**Comment by roryk** [comment]
Thanks everyone, let me know if you run into other issues. Sorry about the problems.
