### ISSUE TITLE
Configuration settings and Qualimap

### ISSUE THREAD

**Issue by zahrahaider** [chapmanb/bcbio-nextgen#1219]
Hi!

Looking at the qualimap output, I notice that the strand specificity and the library design in the input settings is set to default. I was wondering why doesn´t the qualimap input inherit the settings defined in the configuration?

Regards
Zahra

**Comment by lpantano** [comment]
Hi @zahrahaider,

thanks a lot for the feedback. I added the option at 3dec798ba145de0fef00dc923cab8cd195fe63b6 commit. The last development version should have it.

cheers
