### ISSUE TITLE
CNVkit background

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1222]
I was using cnvkit to generate a CBS segmentation file on a Deep Sequence Tumor panel. Since the Sequencing Depth between Tumor and Normal was set different I have run CNVKit in no control sample mode. Now I have rerun the same config on and I have noticed the the call are shifted as the Background was not properly set, and all sample have amplification and no deletions (large part of the chromosome look reds)

I am just wondering if there were any change in bcbio cnvkit that could explain this behavior. 
I have seen that the background file in my  previous run old_background.cnn
and the new one new_background.cnn look different for both the segment size and the gene name annotations 

Thanks a lot!
Alessandro

-bash-4.1$ head old_background.cnn
chromosome  start   end gene    log2    gc  rmask   spread
chr1    10500   176917  Background  1.01548 0.42974 0.479687    1.04623
chr1    227917  267219  Background  0.063555    0.392423    0.515623    0.0723087
chr1    318219  470868  Background  0.894075    0.425827    0.561189    0.922026
chr1    521868  673077  Background  1.14295 0.429187    0.533923    1.17666
chr1    673077  824286  Background  0.332525    0.442904    0.433083    0.347496
chr1    824286  975495  Background  0.180345    0.607523    0.279844    0.191798
chr1    975495  1126705 Background  0.26128 0.610542    0.296898    0.274604
chr1    1126705 1277914 Background  0.17901 0.625168    0.235866    0.190432
chr1    1277914 1429123 Background  0.015875    0.577069    0.421152    0.0235265

-bash-4.1$ head new_background.cnn
chromosome  start   end gene    log2    gc  rmask   spread
chr1    10056   10261   DDX11L1 12.6344 0.502439    1   12.9265
chr1    10261   10467   DDX11L1 11.7777 0.543689    1   12.05
chr1    12927   13103   DDX11L1 0   0.613636    0   0
chr1    13949   14125   DDX11L1 0   0.5625  0   0
chr1    16678   16849   WASH7P  9.55285 0.637427    0.216374    9.77367
chr1    17406   17512   WASH7P  0   0.688679    0   0
chr1    18012   78104   Background  0.46391 0.408557    0.415846    0.474633
chr1    78604   78924   OR4F5   -9.73874    0.35625 1   9.96385
chr1    78924   79245   OR4F5   -9.73503    0.53271 1   9.96005

details:
- analysis: variant2
  genome_build: hg19
  algorithm:
    aligner: bwa
    mark_duplicates: true
    tools_off: [gemini]
    remove_lcr: true
    svcaller: cnvkit
    tools_on: svplots
    coverage_interval: regional

![screen shot 2016-02-10 at 5 33 20 pm](https://cloud.githubusercontent.com/assets/6528310/12964143/79236214-d01c-11e5-97dd-9a963f487522.png)

**Comment by chapmanb** [comment]
Alessandro;
Happy to try and help, but could you provide some details on what changed between your old_background and new_background runs? It's not totally clear to me: is one using the normal as a background and the other tumor only? Or are there different versions of bcbio and CNVkit? If so, which versions for each?

In general,  the things I can say:

- It looks like the old_background run used a target bed file and new_background does not.
- If you have matched normals you should use those as a background rather than a flat background. For capture/targeted experiments you're doing to get a lot of differential coverage due to the pull down/amplification differences, so having a process-matched normal helps a lot to reduce these.

Hope this helps

**Comment by apastore** [comment]
Hi Brad, Sorry to come on this just now.
I have run a new set of 3 paired matched Tumor Normal set using cnvkit on a large target panel. 
For some reason the base line look wrong on all sample (to low) and all chromosome are call amplified. My Aim would be to generate a segmantion file. Do you have an idea of what I am doing wrong?

Thanks!

[IM-pcnsl-250-M_IGO-sort-scatter_global.pdf](https://github.com/chapmanb/bcbio-nextgen/files/158901/IM-pcnsl-250-M_IGO-sort-scatter_global.pdf)


details:
- algorithm:
    aligner: bwa
    background: target.bed
    coverage_interval: regional
    ensemble:
      numpass: 2
    mark_duplicates: true
    min_allele_fraction: 5
    realign: gatk
    recalibrate: gatk
    remove_lcr: true
    svcaller: cnvkit
    tools_off:
    - gemini
    tools_on: svplots
    variant_regions: target.bed
    variantcaller:
    - vardict
    - freebayes
    - mutect2
  analysis: variant2
  description: IM-pcnsl-250-M
  files:

  genome_build: hg19
  metadata:
    batch: IM-pcnsl-250
    phenotype: tumor

**Comment by chapmanb** [comment]
Alessandro;
Thanks for the additional details. From the bcbio side everything you're doing looks good. I'd have to call in @etal to see if he has good suggestions about how best to debug when the output doesn't right. My first thought would be that something is wrong with you normal data. If you look at it manually in IGV or another tool, do you see similar levels of voerage in your target regions? Hope this helps some for debugging.

**Comment by etal** [comment]
Is new_background.cnn the CNVkit reference (called cnv_reference.cnn by default)? Or is it a copy/concatenation of the `*.targetcoverage.cnn` and `*.antitargetcoverage.cnn` files?

The targetcoverage.cnn and antitargetcoverage.cnn files (output from `cnvkit.py coverage`) show the bin-level coverage depths in log2 scale without median-centering. In older versions of CNVkit, these files were median-centered, but now the centering happens in the `reference` command instead. So in either case the generated reference should be median-centered, and the `log2` values should be a mix of positive and negative values centered around 0. For a target panel sequenced with hybridization selection, the reference `.cnn` file should also show bins with the gene name "Background" as well as the targeted gene names.

If you have paired tumor/normal data, it doesn't matter if the tumor and normal samples were sequenced to different depths; CNVkit will correct for that. It's best to tell bcbio about all tumor and normal samples so CNVkit can build a pooled normal reference.

CNVkit's centering method changed slightly within the last two weeks or so, and it's possible you could see a difference if the majority of targeted regions had essentially no coverage. I can check this if you send me the targetcoverage.cnn and antitargetcoverage.cnn files.

On another note, to view these files in IGV it's best to finish the CNVkit pipeline through segmentation,  export the segmented .cns file to SEG format using `cnvkit.py export seg`, and load that output SEG file in IGV as text data.

**Comment by apastore** [comment]
Hi Brad, Hi Etal,
Thanks for your answer. The Tumor normal are sequence at the same High coverage > 500X 
I just include the output of one work cnvkit folder. This is a complete new set of samples, independent from the previous sets. 

I am generating the seg file using the svplots option of bcbio tools_on. 

how you generate a pool normal reference for cnvkit in bcbio?
Thanks!
[cnvkit.zip](https://github.com/chapmanb/bcbio-nextgen/files/159491/cnvkit.zip)

**Comment by etal** [comment]
Thanks for the test data. It looks like the majority of targeted bins have no coverage, while the rest have coverages clustering around 1x (typical off-target coverage) or 300-500x (typical on-target coverage) -- are you sure you used the right target BED file?

Given this input, when CNVkit runs its automated bias corrections it essentially re-centers the targets at the no-coverage default log2 value of -20, so the targets that did have coverage now have log2 values > +20 or so. Segmentation sees these values and includes them in the segment mean log2 value, so the segments have high log2 ratios overall. You can mitigate that problem by either skipping the bias corrections (in CNVkit v0.7.8), or by deleting the target rows in the .cnr file with log2 value above +5 or so.

But first I recommend checking the target BED issue to see why you have so many targets with no or very low coverage. I'll also see about adapting CNVkit to handle this situation better.

**Comment by apastore** [comment]
Thanks for the head up! I will check if something is off on the bed file and report!

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
