### ISSUE TITLE
Manually troubleshoot freebayes slow genomic region

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1226]
Hi, 

I am trying to run a freebayes joint variant calling on 200 samples and specified that the genome should be split in 3000 regions (nomap_split_targets). 

One genomic region is not progressing. I tried to restart variant calling but this did not fix the issue.  The Freebayes thread is still running at 100% and not making any noticeable progress. 

Would the BCBio pipeline accept the output of running the freebayes command with less high quality setting outside of the bcbio pipeline?

This by just putting the VCF.gz and tbi  file in the correct place with the correct name? Or is there another ledger some where that tracks which genomic regions still need to be processed? 

I don't want to restart the whole BCBio run but I am afraid that I maybe need to further chunking or reduce the freebayes setting for this single region. 

Thank you for your thoughts on this.

**Comment by chapmanb** [comment]
Neill;
Sorry about the trouble with calling. Manually running and putting it in the right place will work perfect. There is no extra trickiness and all bcbio does is check for the existence of the output vcf.gz and can pick up processing from there. Hope this gets you going.

If you're able to identify the underlying issue happy to file a bug report with the FreeBayes team or put a workaround in place in bcbio to avoid it in the future.

**Comment by NeillGibson** [comment]
Ok thank you for the information Brad. I'll try to manually run freebayes with the same command on smaller chunks, bcftools concat the resulting vcf.gz files and then put the resulting vcf.gz at the expected location and restart bcbio. 

I am not sure if this is a bug or just a region with a lot of different alleles/ genotypes (=computational complex). If I find a bug I will report it to you or the freebayes team.

**Comment by NeillGibson** [comment]
I could narrow the issue down to a 10 kb region and a quick look in IGV shows peaks with 2000x coverage per sample instead of the expected 40x. 

I am now trying some of the recommended freebayes options for performance tuning / input filtering.

**Comment by NeillGibson** [comment]
The region causing the issue was a small region right next to a region of a couple of million bases without aligned reads (large NNN reference stretch). Freebayes probably got hung up in that large empty region.

Removed the record specifying his region from the bcbio generated bed file and restarted the bcbio run. It now processed the rest of the region specified in the bed file and after that started merging all vcf files. 

We probably have to exclude this region from variant calling for this species.

**Comment by chapmanb** [comment]
Neill;
Thanks for following up. Which organism are you seeing these issues with? We see this in human with collapsed repeats near the centromeres in hg19 and use the ENCODE blacklist to identify regions not found with high coverage filters in bcbio:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/shared.py#L183

If you can find similar resources for your species we could include them in bcbio as part of standard calling. Thanks again.
