### ISSUE TITLE
Oncofuse

### ISSUE THREAD

**Issue by sluke123** [chapmanb/bcbio-nextgen#1227]
I have an error running bcbio 0.9.5 for RNA-Seq, when including Oncofuse in the pipeline. The error is 
 _Could not find java jar Oncofuse in /apps/bcbio-nextgen/0.9.5/rhel6-x64/share/java/oncofuse _
 It seems the Oncofuse file is in /apps/bcbio-nextgen/0.9.5/rhel6-x64/bin/oncofuse and not in java share.
 Please can you investigate?
 Thanks.

**Comment by roryk** [comment]
Hi Sally,

Thanks for posting about the issue, we don't do too much fusion calling so this one slipped by. We swapped over to using wrappers for JAR files so oncofuse gets called with `oncofuse` and not `java -jar path-to-oncofuse-jar`, but we forgot to swap this call over.

I swapped it over and ran our tests and it seems to be fixed.
