### ISSUE TITLE
Cosmic manual installation

### ISSUE THREAD

**Issue by dezzan** [chapmanb/bcbio-nextgen#1230]
Hello!

I know that Cosmic introduced some limitations on distribution of the database since version 72, so I guess it couldn't be added to standard distribution of bcbio. Nevertheless, Cosmic is updating it's database extensively, so it would be really-really helpful, if one could tell bcbio to take "raw" Cosmic files (CosmicCodingMuts.vcf.gz and CosmicNonCodingVariants.vcf.gz) and use them for bcbio itself, VEP, Gemini and may be other tools.

I guess that shouldn't be too complicated, since there's a wonderful script like that:
https://github.com/chapmanb/cloudbiolinux/blob/master/utils/prepare_cosmic.py

And the probable way to do this is to use bcbio_nextgen.py with --toolplus specifying path to the local data. I would love to hear your thoughts about it and would be happy to help with the code.

**Comment by chapmanb** [comment]
Konstantin;
Thanks for the thoughts. You're right that we haven't been updating COSMIC due the redistribution licensing restrictions and this is a good suggestion to allow folks with licenses to use the latest. We're currently working on updating the install to be more modular so will work on incorporating this as part of the improvements. We'd be happy to get contributions here and can circle back on this thread when the updated install approach is in place.

In the short term, you can manually prepare a cosmic download with the script you mentioned, copy into `/path/to/bcbio/genomes/Hsapiens/GRCh37/variation` and edit `/path/to/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37-resources.yaml` to point to the updated cosmic file. Hope this helps.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
