### ISSUE TITLE
feature: option for adding read sponge to the reference

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1234]
On the lines of the decoy.
http://nar.oxfordjournals.org/content/early/2015/07/09/nar.gkv671.full

**Comment by chapmanb** [comment]
Daryl;
Thanks for the feature request. We've focused our efforts on supporting and moving to human build 38, which resolves a lot of reference genome issues. The hg38 build we use also contains these decoys:

ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/README.20150309.GRCh38_full_analysis_set_plus_decoy_hla

Would moving to build 38 be an option for your analysis? We definitely see the value in these but I'm concerned that sinking more effort into build 37 and complicating the install process with more install targets isn't as useful as testing and transitioning to the new build.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
