### ISSUE TITLE
snpEffectPredictor.bin is not compatible with this program version

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1235]
Hey,
I'm getting the following error when running the pipeline using bcbio-vm.
Any clue? I saw that there is a recent commit which should have solved this issue

subprocess.CalledProcessError: Command 'set -o pipefail; /usr/local/bin/snpEff -Xms750m -Xmx6g -Djava.io.tmpdir=/mnt/work/freebayes/tx/tmpSYTyHv/tmp eff -dataDir /mnt/work/inputs/data/genomes/hg19/snpeff -formatEff -classic -noLog -i vcf -o vcf -s /mnt/work/freebayes/sample2245-effects-stats.html hg19 /mnt/work/freebayes/sample2245.vcf.gz | /usr/local/bin/pbgzip -n 2  -c > /mnt/work/freebayes/tx/tmpSYTyHv/sample2245-effects.vcf.gz
/usr/local/bin/snpEff: line 6: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
java.lang.RuntimeException: Database file '/mnt/work/inputs/data/genomes/hg19/snpeff/hg19/snpEffectPredictor.bin' is not compatible with this program version:
	Database version : '4.1'
	Program version  : '4.2'
Try installing the appropriate database.

**Comment by deber1980** [comment]
Forgot to mention that the reference used is hg19.

**Comment by chapmanb** [comment]
Sorry about the issue. You need to also update the bcbio data to get the latest versions of the snpEff databases:
```
bcbio_vm.py upgrade --data
```
We recently switched over to snpEff 4.2 to resolve some issues with 4.1, which requires the snpEff database upgrade. Hope this gets everything working cleanly for you.

**Comment by deber1980** [comment]
Hi Brad,

Thanks for the quick response. 

This is a new cluster that I started from scratch i.e. ran _"bcbio run ..."_ as described [here](https://bcbio-nextgen.readthedocs.org/en/latest/contents/cloud.html#running-an-analysis) which installs the data as part of the run. So, the data should be already up to data and I'm not sure it would help...
Anyway, I'll try it.
Thanks again

**Comment by chapmanb** [comment]
Sorry, I'd missed this was on AWS. Apologies, that's my mistake. We need to referesh the pre-prepared data download on AWS to have the latest snpEff, which is causing the problem. A manual update on the cluster would fix it for your specific run, but the real fix is to refresh those data downloads. I'll re-open this and do that as soon as I can.

**Comment by deber1980** [comment]
Thanks Brad

**Comment by chapmanb** [comment]
Sorry for the delay in finalizing this. We'd been putting a new data installation infrastructure in place to be more flexible going forward and wanted to get these uploaded with that in place. There are now new pre-prepped S3 genomes for GRCh37, hg19 and mm10 which have the latest snpEff version and should work correctly. Thanks again for reporting this and hope all works cleanly for you now.
