### ISSUE TITLE
scalpel output vcf with inconsistent reference

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1237]
GATK complains about an inconsistent reference in the scalpel output. Detailed error is [here](https://gist.github.com/razZ0r/3b25a35edb06c9caed83).

The problematic lines seem to be:

>GL000225.1      206     .       CT      C       0.87    LowVafTumor;HighVafNormal;HighAltCntNormal;LowFisherScore;CHI2FILTER    ALTCOV=357;AVGCOV=7;BESTSTATE=11/11;CHI2=336.54;COVRATIO=0.02;COVSTATE=143,346/4,7/0,11;FISHERPHREDSCORE=0.87;INH=contamination;MINCOV=7;ZYG=het        GT:AD:DP        0/1:143,4:147   0/1:346,7:364
>GL000225.1      206     .       GC      G       16.4    LowVafTumor;CHI2FILTER  ALTCOV=353;AVGCOV=11;BESTSTATE=21/01;CHI2=321.33;COVRATIO=0.03;COVSTATE=143,346/0,11/4,7;FISHERPHREDSCORE=16.4;INH=no;MINCOV=11;ZYG=het;SOMATIC GT:AD:DP        0/0:143,0:147   0/1:346,11:364

Any ideas about the problem? Never used scalpel before.

**Comment by chapmanb** [comment]
Endre;
Thanks for the report. I haven't seen this before but as a workaround pushed a fix to avoid running scalpel on the alt and patch chromosomes since that seems to be the cause of the issue here. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run hopefully it'll skip this and finish cleanly. Thanks again.

**Comment by razZ0r** [comment]
Thanks for the quick fix. I'll try to dig up a reproducible example, and will report back.

**Comment by razZ0r** [comment]
Created a reproducible example, with bam, bed, output, etc files [here](https://www.dropbox.com/s/cx2tg4bnkt9cfza/scalpel_error_example_20160223.tgz?dl=0). Also reported on [sourceforge](https://sourceforge.net/p/scalpel/bugs/7/).

**Comment by chapmanb** [comment]
Endre -- thanks much for putting this example together. We can update to a new version of scalpel once Giuseppe and the scalpel folks have a chance to look at it. Much appreciated.

**Comment by razZ0r** [comment]
Giuseppe is wondering if the same reference sequence was used for aligning and calling the reads. As I only had to specify genome_build: GRCh37 in the config file, this shouldn't be the case. 

Also, he can't reproduce the error with my example. Is there any chance that the reference fasta used during mutation calling and the bwa index used during alignment have differences?

I can't think of any other possible source of error. However, I had to restart the pipeline multiple times. Maybe something happened there?

**Comment by chapmanb** [comment]
Endre;
Thanks for following up on this. I get the same result you do when running your shell script -- the problematic mis-matching variant calls at position 206. I tried upgrading to scalpel 0.5.3 and also get the same problem in `out/main/somatic.indel.vcf`.

We use the same reference for alignment, and these haven't changed in quite a while so I'm not sure how they could have got out of sync. I'm also a bit confused as to why that would cause this error since scalpel is doing local re-alignment and assembly relative to the reference.

Sorry I wish I had some ideas but am totally confused how Giuseppe doesn't see the error when re-running your shell script. Maybe we could try to sync up the reference files and be sure what he puts in matches what bcbio uses, which is from the broad bundle:

ftp://gsapubftp-anonymous:none@ftp.broadinstitute.org/bundle/2.8/b37/

Hope this helps some.

**Comment by razZ0r** [comment]
OK, so Giuseppe still can't reproduce the bug. Additionally, if I download scalpel 0.5.1 from sourceforge, compile it, and run it with exactly the same parameters, even using the reference fasta from the bcbio data dir, I can't reproduce it either!

The vcf now contains:

<pre>
GL000225.1      546     .       GA      G       0.75    LowVafTumor;HighVafNormal;HighAltCntNormal;LowFisherScore       AVGCOV=8.0;MINCOV=8;ALTCOV=101;ZYG=het;COVRATIO=0.07;CHI2=79.35;FISHERPHREDSCORE=0.75;INH=contamination;BESTSTATE=11/11;COVSTATE=51,101/6,8/0,0       GT:AD:DP        0/1:51,6:57     0/1:101,8:109
</pre>

However, one thing I discovered that when I'm running scalpel from a local install, I get a line like this in the log:

<pre>
Loading targets from BED file...1 targets (filtered 0 overlapping).
Loading genome from FASTA file...84 sequences.
Assembly Exons
</pre>

In the bcbio scalpel run only this:

<pre>
Loading targets from BED file...1 targets (filtered 0 overlapping).
Assembly Exons
</pre>

Something might be happening here?

**Comment by razZ0r** [comment]
There is a difference in the FindVariants.pl script between the original and bcbio version. If I revert the bcbio script back to the original one, everything runs correctly. 

<pre>
diff --git a/tmp/scalpel/scalpel-0.5.1/FindVariants.pl b/biodata/bcbio/data/anaconda/share/scalpel-0.5.1-3/FindVariants.pl
index 331c20a..c56c96a 100755
--- a/tmp/scalpel/scalpel-0.5.1/FindVariants.pl
+++ b/biodata/bcbio/data/anaconda/share/scalpel-0.5.1-3/FindVariants.pl
@@ -219,7 +219,7 @@ sub run {
 	}
 	
 	# decide if loading genome from fasta or use samtools faidx
-	if (-e "$bedfile") { $USEFAIDX = 0; }
+	if (-e "$bedfile") { $USEFAIDX = 1; }
 	elsif ($bedfile =~ m/(\w+):(\d+)-(\d+)/) { 
 		#parse region
 		my ($chr,$interval) = split(':',$bedfile);
</pre>

**Comment by chapmanb** [comment]
Endre;
Thanks for the detective work and identifying the underlying problem. We do change this and the underlying reason was to avoid high memory usage pulling the entire genome into memory:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/scalpel/build.sh#L4

I believe this was an optimization from @mjafin initially but might no longer be necessary in recent versions of scalpel. We could pull this out and resolve the underlying issue and revisit if we start to run into memory issues using the default.

**Comment by razZ0r** [comment]
This would solve the issue I guess, but still won't explain, **why** the use of samtools leads to the errors in the tumor/normal vcfs.

The correct normal variants.indel.vcf for my test case contains:

<pre>
GL000225.1      546     .       GA      G       .       HighChi2score   AVGCOV=6.0;MINCOV=6;ALTCOV=51;ZYG=het;COVRATIO=0.11;CHI2=35.53;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTATE=na
GL000225.1      1877    .       AG      A       .       LowAltCnt       AVGCOV=2.0;MINCOV=2;ALTCOV=22;ZYG=het;COVRATIO=0.08;CHI2=16.67;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTATE=na
</pre>

The incorrect one, based on the bcbio modified scalpel run:

<pre>
GL000225.1      199     .       CA      C       .       HighChi2score   AVGCOV=8.0;MINCOV=8;ALTCOV=148;ZYG=het;COVRATIO=0.05;CHI2=125.64;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTATE=na
GL000225.1      199     .       CAG     C       .       HighChi2score   AVGCOV=10.0;MINCOV=10;ALTCOV=146;ZYG=het;COVRATIO=0.06;CHI2=118.56;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTATE=na
GL000225.1      205     .       GC      G       .       LowVaf;HighChi2score    AVGCOV=5.0;MINCOV=5;ALTCOV=141;ZYG=het;COVRATIO=0.03;CHI2=126.68;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTA
GL000225.1      206     .       CT      C       .       LowAltCnt;LowVaf;HighChi2score  AVGCOV=4.0;MINCOV=4;ALTCOV=143;ZYG=het;COVRATIO=0.03;CHI2=131.44;FISHERPHREDSCORE=0;INH=na;BESTSTATE=n
GL000225.1      546     .       GA      G       .       HighChi2score   AVGCOV=6.0;MINCOV=6;ALTCOV=51;ZYG=het;COVRATIO=0.11;CHI2=35.53;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTATE=na
GL000225.1      1877    .       AG      A       .       LowAltCnt       AVGCOV=2.0;MINCOV=2;ALTCOV=22;ZYG=het;COVRATIO=0.08;CHI2=16.67;FISHERPHREDSCORE=0;INH=na;BESTSTATE=na;COVSTATE=na
</pre>

The tumor variants.indel.vcf  files have similar differences and this leads to the inconsistent output vcf.

**Comment by razZ0r** [comment]
https://sourceforge.net/p/scalpel/bugs/7/#5b81

> Maybe scalpel's code does not handle properly patch chromosomes names (e.g., GL000225.1) when loading the BED/FASTA files (which happens when setting $USEFAIDX=1). I will do some additional investigation in the future, but it is not high prioprity for me at this time.
