### ISSUE TITLE
hg38 disambiguation fails for bwa due to missing AS tag

### ISSUE THREAD

**Issue by mjafin** [chapmanb/bcbio-nextgen#1239]
For book keeping and awareness, hg38 (full) doesn't work at the moment when combined with disambiguation as the alt-alignments do not contain AS tags. Will look into what's the most reasonable solution. 

Additionally and unrelatedly, split reads do not get disambiguated at the moment as their name is changed in the bam files (underscore and 1 or 2 added to read name).

**Comment by mjafin** [comment]
This seems to happen in both `0.9.5` and `0.9.6`. Odd that we haven't run into this before. Here is a read pair that causes the pattern:
https://gist.github.com/mjafin/5b4608d7249cf06a4205

**Comment by mjafin** [comment]
The two alignments from bwa are
```
NB501188:6:H3THMAFXX:1:11101:1023:15032 73      chr17   46245214        0       151M    =       46245214        0       GCAAATGCAGTTTATTGTAATATATGGGATTAGATTCATCTATGGAGGGCAGAGTGGGCTGCATGGGGATTGGGAGCGACAGGGCTTGGGGAGCAGGTCTCTGGCAGAGAAGGTTGTCCGTTCCAGGAGCTCACGGCCATGCCCAATGCTG AAAA/EE/EEEEEA6//AE/E6EEEEAA/E/E6//EEAEAEE6//AE//E<EE6E6///E//////E/EEEE//EE//E/////////<A/EA////<//<A//6/E/E/////E//A6<EEEAEA/////<<6/AE6/6//A//<A//<<     NM:i:7  MD:Z:62C13G36A16A7C5C2C3        AS:i:119        XS:i:119        RG:Z:1  XA:Z:chr11,+45905888,151M,7;chr17,-45600552,151M,7;chr17_GL000258v2_alt,-542161,151M,7;chr17_KI270908v1_alt,+947636,151M,7;chr17_GL000258v2_alt,+1188126,151M,7;chr17_KI270908v1_alt,-302693,151M,7;chr17_GL000258v2_alt,+1461570,151M,7;
NB501188:6:H3THMAFXX:1:11101:1023:15032 133     chr17   46245214        0       *       =       46245214        0       GGGGAAACCAGAAGCCAGAAACCCCCCGGCAGAGACACGGCGGGTACGGAACCGAAGTGGGGGGGGCCGTTGACTGAGGAAAGAACCAGCAAAGAAGAAAAAGAAACTACAACAAAAAGCAGAACCGCGCAAACCCCACCCACCCCCAAA  ///6/E/////////E//A/////E////E///////////////A////////////E///AE//EA///<//////////A//</E/<AA///////////<////////A////////////////A////////6<//<A//////      AS:i:0  XS:i:0  RG:Z:1
```
(which are fine)
and then bwakit adds a third:
```
NB501188:6:H3THMAFXX:1:11101:1023:15032 2121    chr17_KI270908v1_alt    947636  0       151M    chr17   46245214        0       GCAAATGCAGTTTATTGTAATATATGGGATTAGATTCATCTATGGAGGGCAGAGTGGGCTGCATGGGGATTGGGAGCGACAGGGCTTGGGGAGCAGGTCTCTGGCAGAGAAGGTTGTCCGTTCCAGGAGCTCACGGCCATGCCCAATGCTG AAAA/EE/EEEEEA6//AE/E6EEEEAA/E/E6//EEAEAEE6//AE//E<EE6E6///E//////E/EEEE//EE//E/////////<A/EA////<//<A//6/E/E/////E//A6<EEEAEA/////<<6/AE6/6//A//<A//<<     NM:i:7  lt:Z:chr17,46245212,46245363,+; RG:Z:1
```
which causes the problem, as the alignment doesn't have `AS`

**Comment by chapmanb** [comment]
Miika;
Thanks for digging into the issue. We might have not hit reads with alts assigned by bwakit before. Is this something we could fix in disambiguation?  Ideally, we could skip reads if they don't an `AS` tag would . This would, at least for the moment, not disambiguate on alt assignments but would be an easier fix than trying to get something upstream to bwakit.

**Comment by mjafin** [comment]
Yes I can make it skip these reads - ideally I think they'd have an adjusted `AS` tag to reflect alternative haplotype alignments (if `AS` is expected to depend on alts)

**Comment by mjafin** [comment]
Did a pull request for the hack. Do you think it's worth pinging Heng Li about the missing tag?

**Comment by chapmanb** [comment]
Miika -- awesome, thank you. It's definitely worth reporting to Heng as well -- treating alts as first class citizens going forward will help with build 38 adoption and correct characterization of complex mappers. At least we can understand how it's meant to work with bwakit. Thanks again for getting the immediate fix in place.
