### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 188: ordinal not in range(128)

### ISSUE THREAD

**Issue by xbioinfo** [chapmanb/bcbio-nextgen#1247]
File "/home/xxx/install/bc/anaconda/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 298, in priority_coverage
    line_batch += str(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 188: ordinal not in range(128)

**Comment by lpantano** [comment]
Hi,

sorry about the problem.
It could be you have some weird character in the `svprioritize` bed file?

**Comment by xbioinfo** [comment]
thanks Ipantano, but the pipeline should expect some weird characters right ? some unicode

**Comment by lpantano** [comment]
Hi,

well, the bed file you use in svpriority is the one used in this chunk of code. The bed file should be plain text, only character and numbers there. It seems in some line there is some weird character there. So if that file is ok, then I can try to look into other errors.

cheers

**Comment by xbioinfo** [comment]
yeah, that file is ok, but after running gemini, it add some contents seems

**Comment by chapmanb** [comment]
Sorry about the issues. We're happy to help but would need a bit more information about your underlying setup to be able to diagnose:

- What does your bcbio sample YAML file look like? We're especially interested in, as Lorena mentioned, your `svprioritize` BED file (https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#structural-variant-calling). The error looks like there are unicode or other unexpected control characters in it. It should be a plain text file.
- I'm confused about your follow up message about GEMINI. What issues specifically are you seeing?

Thanks much.

**Comment by xbioinfo** [comment]
1. yaml is almost the same with the teaching yaml, only changed to gatk. [file link](https://gist.github.com/xbioinfo/0b89dd360c1838ab6554)
no, actually it seems to be the coverage bed file, not the svprioritize bed: '**report/coverage/syn3-tumor_priority_total_coverage.bed**'

problematic lines:
[u'chr1', u'114704469', u'114716894', u'{:support {:url "https://civic.genome.wustl.edu//#/events/genes/36/summary", :variant-groups (), :origin #{"civic"}, :drugs #{"RO4987655" "Cetuximab" "Temozolomide\xa0" "Everolimus" "MEK162"
 "17-AAG" "Vemurafenib"}}, :name #{"NRAS"}}']
[u'chr9', u'4985033', u'5128183', u'{:support {:url "https://civic.genome.wustl.edu//#/events/genes/28/summary", :variant-groups (), :origin #{"civic"}, :drugs #{"Pegylated IFN-\u03b1\u20132a" "TG101348"}}, :name #{"JAK2"}}']

after cleaning (i try to changed the source code to drop the problematic unicode chars): first 2 lines of '**report/coverage/syn3-tumor_priority_total_coverage.bed**':

chrom chromStart      chromEnd        F3      F4      F5      F6      F7      F8      F9      F10     F11     F12     F13     F14     F15     F16     F17     F18     F19     F20     readCount       meanCoverage    percentage10 percentage20     percentage30    percentage40    percentage50    percentage60    percentage70    percentage80    percentage90    percentage100   sampleName
chr1    114704469       114716894       {:support {:url "https://civic.genome.wustl.edu//#/events/genes/36/summary", :variant-groups (), :origin #{"civic"}, :drugs #{"RO4987655" "Cetuximab" "Temozolomide " "Everolimus" "MEK162" "17-AAG" "Vemurafenib"}}, :name #{"NRAS"}}        0       0       0       0       0       0       0       0       0       0       0       0       syn3-tumor

2. i see this error probably just after gemini. sorry about the confusion.

**Comment by lpantano** [comment]
Hi,

I think @roryk and I have some clue about was going on. We expected for that section to have a BED file, but you are using `cancer/civiv` that is correct, but we forgot to adapt it. @chapmanb, I guess this options is to find all the BED files inside those folders, right? 

I added a fix b93b054da81cb95243144bb0273ea07a3720c58c  to make sure is a bed file, but the proper way it should be merge all bed files from that folder. 

you will need to update to development version, and hopefully this will fix it.

**Comment by chapmanb** [comment]
Lorena and Rory -- thanks for looking at this. The BED file here should be present as bcbio looks this up from the standard install location when parsing the configuration, so I think we'll still have the issue (although this isn't a bad check to have in place).

The proper fix is to not have unicode characters in the civic BED file or to handle them here with an explicit decode. I'm working on replicating this now and can push a fix soon.

@xbioinfo, for an immediate fix remove this line from your configuration:
```
svprioritize: cancer/civic
```
Also, what type of analysis are you running? This is setup for cancer calling so GATK HaplotypeCaller isn't the right choice for that. The teaching example is meant to be comprehensive so it might make sense to start from this page:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/pipelines.html

and pick a template based on the type of analysis you're looking to run. Hope this helps until we can get a proper fix in place for the updated version of CIViC. Thanks for all the patience debugging.

**Comment by chapmanb** [comment]
Thanks again for all the debugging and help with this. I pushed a small fix that only uses chromosome start and end coordinates to avoid potential issues with characters in the name field. If you update your local bcbio with:
```
bcbio_nextgen.py upgrade -u development
```
it should now work cleanly and finish the test example without any problems. Hope this helps and sorry again about the problems.

**Comment by xbioinfo** [comment]
thank you all, for this issue :+1: 

@chapmanb for the type of analysis, thanks for pointing it out. i was just want to run through the pipeline with gatk after first installing the pipeline, try to get familiar with the pipeline, not special purpose currently.
