### ISSUE TITLE
hg19 seq seems to be broken on s3

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1251]
Hello,
I'm running an analysis on a new machine I install on aws and it failed. It seems that the reason is that hg19-seq.tar.gz on s3 was recently changed and it contains a truncated hg19.fa file that only includes chromosome 1-10. This is the file path in s3
 s3://biodata/prepped/hg19/hg19-seq.tar.gz

Am I missing something or there is a problem there?

Thank you

**Comment by chapmanb** [comment]
Sorry about the problem. We did update the data indices for AWS to include the new snpEff version (4.2). I'm not sure what might have went wrong with the hg19.fa file but will take a look and upload a fixed version. Thanks much for the heads up.

**Comment by chapmanb** [comment]
I regenerated the hg19 sequence tarball and uploaded to s3 after double checking the new version has a full sequence file. Apologies, I'm not sure what happened on the first preparation that caused this. That's frustrating, but hopefully the new version gets you going cleanly.

**Comment by deber1980** [comment]
Thanks Brad!
