### ISSUE TITLE
bcbio_vm, error on HLA region in subset_variant_regions()

### ISSUE THREAD

**Issue by xbioinfo** [chapmanb/bcbio-nextgen#1252]
I use docker. and running the teaching example. error below, any reasons ?

```
/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.pyc in subset_variant_regions(variant_regions='/mnt/work/bedprep/NGv3-chr6-hg38-merged.bed', region='HLA-A*01:01:01:01', out_file='/mnt/work/align/syn3-tumor/2_2015-11-18_syn3-csh...-18_syn3-cshl-sort-HLA-A*01:01:01:01-callable.bed', items=None, do_merge=True)
    244     if region is None:
    245         return variant_regions
    246     elif variant_regions is None:
    247         return region
    248     elif not isinstance(region, (list, tuple)) and region.find(":") > 0:
--> 249         raise ValueError("Partial chromosome regions not supported")
    250     else:
    251         merge_text = "-unmerged" if not do_merge else ""
    252         subset_file = "{0}".format(utils.splitext_plus(out_file)[0])
    253         subset_file += "%s-regions.bed" % (merge_text)

ValueError: Partial chromosome regions not supported
___________________________________________________________________________
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Sorry about the problem with running this in Docker. How did you install the `bcbio/bcbio` Docker container? This looks like you have an older version of bcbio as recent versions should avoid trying to process and call on HLAs to avoid this. The latest available instance from Docker hub:
```
docker pull bcbio/bcbio
```
should work cleanly on this. Are there any other changes to the teaching YAML configuration file in your run which might be triggering something I missed? Happy to try and debug more with additional information. Thanks again.

**Comment by xbioinfo** [comment]
i just install it with docker about 3 days ago, and i'm think it should be the latest.
no change to the teaching YAML.
I'll check if there's other information indicating potential problems.

**Comment by xbioinfo** [comment]
$ docker pull bcbio/bcbio
```
Using default tag: latest
latest: Pulling from bcbio/bcbio
8387d9ff0016: Already exists 
3b52deaaf0ed: Already exists 
4bd501fad6de: Already exists 
a3ed95caeb02: Already exists 
8fb916d0adac: Already exists 
Digest: sha256:b8eb9d7c1c6f342501d5461078900268e940ce2cb4d4f9b02cb19c7dc16dbc2e
Status: Image is up to date for bcbio/bcbio:latest
```

**Comment by xbioinfo** [comment]
any progress ? or should I check if anything wrong with my procedure ?
Thanks.

**Comment by chapmanb** [comment]
Apologies to be slow. I haven't had a chance to replicate and try to debug. If you're trying to use bcbio-vm and Docker you could avoid using hg38 in the short term to work around this issue. I'll definitely try to replicate and see if I can identify the issue but hope this at least keeps you moving on other analyses.

**Comment by xbioinfo** [comment]
ok, i understand and appreciate. 
thanks.

**Comment by chapmanb** [comment]
Thanks for the patience. I've been working to replicate this and haven't been able to get the same error. I can find a couple of issues later in the teaching example (MuTect is not included in the Docker image) but it gets past this step without any issues. This is with a brand new instance on AWS. Your error still looks like an older version of bcbio that did not correctly handle hg38 contigs, but I'm not able to explain how you got this version or why I can't replicate it. Do you have any other information about how you installed and ran this that might help me understand what is causing it? Thanks much for the patience debugging.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
