### ISSUE TITLE
RADAR-GRCh37

### ISSUE THREAD

**Issue by tanglingfung** [chapmanb/bcbio-nextgen#1260]
there appears to have a problem in running GGD recipe

**Comment by chapmanb** [comment]
Paul;
Thanks for the report. What type of errors are you getting? The install of this recipe runs cleanly for me, although is a bit slow pulling in the original file from the Stanford website. @rory, do you think the RADAR files are one we should pre-prepared, bgzip and store in S3 to avoid needing to pull directly?

**Comment by rory** [comment]
@chapmanb Think you have the wrong rory

**Comment by chapmanb** [comment]
Apologies, I meant to ping @roryk for his opinion.

**Comment by razZ0r** [comment]
The RADAR-GRCh37 recipe fails when trying to download the [remap_url](http://raw.githubusercontent.com/dpryan79/ChromosomeMappings/master/GRCh37_UCSC2ensembl.txt) file. 

<pre>
wget -qO- $remap_url | awk '{if($1!=$2) print "s/^"$1"/"$2"/g"}' > remap.sed
</pre>

if I turn off -q fails with:

<pre>
[esebesty@node001 ~/tmp/editing]$ wget -O- http://raw.githubusercontent.com/dpryan79/ChromosomeMappings/master/GRCh37_UCSC2ensembl.txt
--2016-03-14 19:00:21--  http://raw.githubusercontent.com/dpryan79/ChromosomeMappings/master/GRCh37_UCSC2ensembl.txt
Resolving raw.githubusercontent.com... 185.31.17.133
Connecting to raw.githubusercontent.com|185.31.17.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/dpryan79/ChromosomeMappings/master/GRCh37_UCSC2ensembl.txt [following]
--2016-03-14 19:00:21--  https://raw.githubusercontent.com/dpryan79/ChromosomeMappings/master/GRCh37_UCSC2ensembl.txt
Connecting to raw.githubusercontent.com|185.31.17.133|:443... connected.
ERROR: certificate common name “www.github.com” doesn’t match requested host name “raw.githubusercontent.com”.
To connect to raw.githubusercontent.com insecurely, use ‘--no-check-certificate’.
</pre>

**Comment by roryk** [comment]
Thanks, sorry about that. I added the --no-check-certificate flag to the formula, so hopefully it should install cleanly now.

**Comment by tanglingfung** [comment]
Thanks, I am sorry for my late reply. my installation went ok on another day, so, I am not really sure where the problem was.
