### ISSUE TITLE
Memory requirements for RNAseq analysis

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1261]
Hi all,

I want to use bcbio-nextgen to analyze human RNAseq data. I have two conditions that I want to compare and 10 samples for each (total of 20 samples).

I currently have a 12 core machine with 36 Gb of RAM but it's a virtual machine and I may be able to reallocate some extra resources temporarily. The server that runs the VM actually has a total of 24 cores and ~130 GB RAM.

I don't want to completely starve the other VMs on this system, but does anyone have thoughts on what a reasonable memory/hardware setup for that kind of experiment (20 RNAseq samples) could look like? 

Thanks for any input you might have!
~Lina

**Comment by roryk** [comment]
Hi Lina,

That should be enough machine to run your analysis in a reasonable amount of time, as long as the samples aren't super super deep. STAR will need about 40 GB to run each alignment, so the alignments will happen one at a time, running with 12 cores each. There are some steps that run serially, so those will run 12 at a time using 1 core each.

**Comment by lfaller** [comment]
Ok great -- thanks for the input!
