### ISSUE TITLE
pexpect error 

### ISSUE THREAD

**Issue by GregSilverman** [chapmanb/bcbio-nextgen#1263]
Getting the error:

``
 File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pexpect' distribution was not found and is required by ipython
``

But, this exists: 

```
gms@iznej:~/development/mpi$ls  /usr/local/lib/python2.7/dist-packages/pexpect*
/usr/local/lib/python2.7/dist-packages/pexpect:
ANSI.py   exceptions.py   expect.pyc	 FSM.py       __init__.pyc     pty_spawn.py   pxssh.pyc     run.py     screen.pyc     utils.py
ANSI.pyc  exceptions.pyc  fdpexpect.py	 FSM.pyc      popen_spawn.py   pty_spawn.pyc  replwrap.py   run.pyc    spawnbase.py   utils.pyc
async.py  expect.py	  fdpexpect.pyc  __init__.py  popen_spawn.pyc  pxssh.py       replwrap.pyc  screen.py  spawnbase.pyc

/usr/local/lib/python2.7/dist-packages/pexpect-4.0.1-py2.7.egg-info:
dependency_links.txt  PKG-INFO	requires.txt  SOURCES.txt  top_level.txt

```

I am trying to execute the following command:  `mpiexec -f machinefile -n 10 ipython test.py` ... this works fine using just python, so not sure what the problem is. I've uninstalled/reinstalled ipython to no avail (I initially did `pip install ipython[all]`).

Any ideas would be most welcome.

**Comment by roryk** [comment]
Hi Greg, what are you trying to run when you get that error?

**Comment by GregSilverman** [comment]
test.py is just the following: 

# test_mpi.py
import os
import socket
from mpi4py import MPI

```
MPI = MPI.COMM_WORLD

print("{host}[{pid}]: {rank}/{size}".format(
    host=socket.gethostname(),
    pid=os.getpid(),
    rank=MPI.rank,
    size=MPI.size,
))
```

Note, that this did work, but then I realized I had a mixed ipython environment (installed both through apt-get and pip). I was trying to unravel these, and in the course, ran into this error, so I am not sure if it is exactly a bug. I am going to try running my mpi4py/ipython stuff in a virtualenv to isolate this from any possible residual conflicts. I will let you know the outcome.

**Comment by roryk** [comment]
Hi Greg,

Sorry, not sure how much we can help. Do you have the right repository?

**Comment by GregSilverman** [comment]
Obviously not! I thought this was the ipython repo! Never mind!

**Comment by roryk** [comment]
It looks like you are running the Python installed on your machine-- we really like using anaconda which has nice pre-built libraries for IPython and what not which often irons out these types of issues:

http://conda.pydata.org/miniconda.html

That gives you your own isolated Python and makes it super easy to install new libraries.

**Comment by GregSilverman** [comment]
Thanks, I'll give that a whirl.

**Comment by GregSilverman** [comment]
No go. Can't install Anaconda on a ARM processor.

**Comment by GregSilverman** [comment]
Not true. Just found this: https://www.continuum.io/content/conda-support-raspberry-pi-2-and-power8-le ... in the meantime, I got ipython working fine with mpi in a standard virtualenv. Sorry for the confusion and posting in the wrong repo!
