### ISSUE TITLE
--datatarget option not recognized

### ISSUE THREAD

**Issue by sib-bcf** [chapmanb/bcbio-nextgen#1264]
Hello,
I've just installed the latest stable version of bcbio-nextgen with --nodata option. Then, I would like to install only rnaseq reference files in order to save disk space. I've tried the --datatarget option (which seems to me very useful), but is not recognized by bcbio_nextgen.py:

root@30e4274eff2a:/# bcbio_nextgen.py upgrade -u stable --datatarget rnaseq --genomes GRCh37 --aligners hisat2
usage: bcbio_nextgen.py [-h] {upgrade} ...
bcbio_nextgen.py: error: unrecognized arguments: --datatarget rnaseq

I had a look at the bcbio_nextgen.py script, and indeed "--datatarget" is not present anywhere in the script.

Thank for your help,
Paolo

**Comment by chapmanb** [comment]
Paolo;
Sorry about the confusion. The `--datatarget` feature was added in the current development version so you can do: 
```
bcbio_nextgen.py upgrade -u development
bcbio_nextgen.py upgrade --datatarget rnaseq --genomes GRCh37 --aligners hisat2
```
We're running validations now for a new release so hopefully will have a stable version with this functionality soon. Hope this works for you.

**Comment by sib-bcf** [comment]
Thank you Brad,
I've seen the option in the online documentation, and I thought it was 
already available in the stable version.
I'll switch to the development as you suggested.

Best regards,
Paolo
