### ISSUE TITLE
sambamba-sort error

### ISSUE THREAD

**Issue by tombair** [chapmanb/bcbio-nextgen#1269]
I get the following error on some fastq.gz inputs but not others. The error seems to be repeatable for a given input ie if it happens it always happens. The error is:

```
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 6414)
[M::mem_pestat] mean and std.dev: (1138.23, 877.84)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 8396)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (732, 1292, 2208)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 5160)
[M::mem_pestat] mean and std.dev: (1203.17, 826.00)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6636)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[main] Version: 0.7.12-r1039
[main] CMD: /Shared/Bioinformatics/data/bcbio/bin/bwa mem -c 250 -M -t 10 -R @RG\tID:1\tPL:illumina\tPU:1_2016-03-13_K00275a\tSM:NA12878_1463_0261814aliqout -v 1 /Shared/Bioinformatics/data/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align_prep/NA12878_1463_02__6_18_14aliqout_R1.fastq.gz /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align_prep/NA12878_1463_02__6_18_14aliqout_R2.fastq.gz
[main] Real time: 33262.925 sec; CPU: 331711.946 sec
samblaster: Output 6865556 discordant read pairs to /dev/fd/62
samblaster: Output 11615606 split reads to /dev/fd/63
samblaster: Marked 44390933 of 368860943 (12.03%) read ids as duplicates using 5909892k memory in 13M59S(839.432S) CPU seconds and 9H14M23S(33263S) wall time.
sambamba-sort: Error reading BGZF block starting from offset 218076356: wrong BGZF magic
' returned non-zero exit status 1

```

Any idea how to debug further, I have checked the fastq files, R1 and R2 have the same number of entries, end with the same identifier and with small subsets (10% or so ) they seem to work fine, it just errors out with the full  30G input. Is it a memory issue?

The command that fails is:

`/Shared/Bioinformatics/data/bcbio/bin/bwa mem  -c 250 -M -t 10  -R @RG\tID:1\tPL:illumina\tPU:1_2016-03-13_K00275a\tSM:NA12878_1463_0261814aliqout -v 1 /Shared/Bioinformatics/data/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align_prep/NA12878_1463_02__6_18_14aliqout_R1.fastq.gz /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align_prep/NA12878_1463_02__6_18_14aliqout_R2.fastq.gz  | /Shared/Bioinformatics/data/bcbio/bin/samblaster --addMateTags -M --splitterFile >(/Shared/Bioinformatics/data/bcbio/bin/samtools sort -@ 10 -m 8G -T /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/tx/tmpscgNAd/1_2016-03-13_K00275a-sort-sorttmp-spl -o /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/tx/tmpIzyAvQ/1_2016-03-13_K00275a-sort-sr.bam /dev/stdin) --discordantFile >(/Shared/Bioinformatics/data/bcbio/bin/samtools sort -@ 10 -m 8G -T /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/tx/tmpscgNAd/1_2016-03-13_K00275a-sort-sorttmp-disc -o /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/tx/tmp4237kx/1_2016-03-13_K00275a-sort-disc.bam /dev/stdin) | samtools view -b -S -u - | sambamba sort  -t 10 -m 8G --tmpdir /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/tx/tmpscgNAd/1_2016-03-13_K00275a-sort-sorttmp-full -o /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/tx/tmpscgNAd/1_2016-03-13_K00275a-sort.bam /dev/stdin
`

Thanks

**Comment by chapmanb** [comment]
Tom;
Thanks for the detailed report. It looks like it might be a memory issue, as you're asking all of the sort commands for a lot of memory. The memory specifications in bcbio_system.yaml are per-core, so your commands:
```
sambamba sort -t 10 -m 8G
samtools sort -@ 10 -m 8G
```
each are allowed to use 80G of memory. These should do fine with 2G of memory here. Hopefully changing that will resolve the problem.

**Comment by tombair** [comment]
The machines have 250G, so I think 80G should be ok. 

 I looked though the code and found the by changing the config yaml file for samtools changes sambamba (I think that is right anyway) so I upped it from the default to the current state, but I was having the problem before I made the change, ie  I made the change to try and solve the problem.

 I can't remember though if the default was at 16 cores at 2 or 4G willing to try lower if you think it might solve the problem though

**Comment by chapmanb** [comment]
Tom;
Thanks for the additional details. If you were having problems with the previous setting, it sounds like I was sending you down the wrong path to debug. Sorry about that. Could you try setting `align_split_size: 10000000` in your input file? This will split the initial fastq file up into chunks, align each independently, and then merge and de-duplicate them in a final step:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#alignment

We typically use this once file sizes get bigger and would help differentiate if there is a problem with the initial fastq inputs at some point versus something happening during the run process with memory. Hope this helps get it working for you.

**Comment by tombair** [comment]
I will give it a try. Thanks for the help, it takes a while to fail, so it is a frustrating process to debug.

**Comment by schelhorn** [comment]
Don't know if it helps, but there used to be a problem with sorting if the sort process is part of the alignment pipe (i.e. streaming sort). In that case the available memory for the sorting was implicitly halved by bcbio under certain circumstances (to fit into the parallel resource environment I guess). I used to have failed sorts in these cases. You can check for this by looking at the shell command that is actually called and how much memory it sets for the sorting process (see bcbio command logs). I believe I solved the issue by assigning more memory to alignment and sort.

**Comment by tombair** [comment]
Setting align_split_size: 10000000 sped up the process, so probably a good option to set, but it still failed 

The command run was
`/Shared/Bioinformatics/data/bcbio/bin/bwa mem  -c 250 -M -t 10  -R @RG\tID:1\tPL:illumina\tPU:1_2016-03-13_K00275a\tSM:NA12878_1463_0261814aliqout -v 1 /Shared/Bioinformatics/data/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa <(grabix grab /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align_prep/NA12878_1463_02__6_18_14aliqout_R1.fastq.gz 200000001 240000000) <(grabix grab /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align_prep/NA12878_1463_02__6_18_14aliqout_R2.fastq.gz 200000001 240000000)  | /Shared/Bioinformatics/data/bcbio/bin/samblaster --addMateTags -M --splitterFile >(/Shared/Bioinformatics/data/bcbio/bin/samtools sort -@ 10 -m 8G -T /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/split/tx/tmp6zIcZ9/1_2016-03-13_K00275a-sort-200000001_240000000-sorttmp-spl -o /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/split/tx/tmp3r1BU9/1_2016-03-13_K00275a-sort-200000001_240000000-sr.bam /dev/stdin) --discordantFile >(/Shared/Bioinformatics/data/bcbio/bin/samtools sort -@ 10 -m 8G -T /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/split/tx/tmp6zIcZ9/1_2016-03-13_K00275a-sort-200000001_240000000-sorttmp-disc -o /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/split/tx/tmp1f86Mu/1_2016-03-13_K00275a-sort-200000001_240000000-disc.bam /dev/stdin) | samtools view -b -S -u - | sambamba sort -N -t 10 -m 8G --tmpdir /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/split/tx/tmp6zIcZ9/1_2016-03-13_K00275a-sort-200000001_240000000-sorttmp-full -o /Shared/Bioinformatics/data/validation_study/K00275a/K00275a/work/align/NA12878_1463_0261814aliqout/split/tx/tmp6zIcZ9/1_2016-03-13_K00275a-sort-200000001_240000000.bam /dev/stdin`

The error given was:

`[M::mem_pestat] low and high boundaries for proper pairs: (1, 5260)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (236, 283, 338)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (32, 542)
[M::mem_pestat] mean and std.dev: (289.16, 75.58)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 644)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[main] Version: 0.7.12-r1039
[main] CMD: /Shared/Bioinformatics/data/bcbio/bin/bwa mem -c 250 -M -t 10 -R @RG\tID:1\tPL:illumina\tPU:1_2016-03-13_K00275a\tSM:NA12878_1463_0261814aliqout -v 1 /Shared/Bioinformatics/data/bcbio/genomes/Hsapiens/GRCh37/bwa/GRCh37.fa /dev/fd/63 /dev/fd/62
[main] Real time: 902.246 sec; CPU: 8954.656 sec
samblaster: Output 184202 discordant read pairs to /dev/fd/62
samblaster: Output 308754 split reads to /dev/fd/63
samblaster: Marked 934860 of 10000000 (9.35%) read ids as duplicates using 170444k memory in 21.136S CPU seconds and 15M2S(902S) wall time.
sambamba-sort: Error reading BGZF block starting from offset 307706091: wrong BGZF magic
' returned non-zero exit status 1`

I had a couple of thoughts:
1. I ran these samples with a similar workflow on stable, these are being run on devel, only major difference in the workflows is different variant calling (which should not matter, I think) and these are using the validation flags to compare against genome in a bottle (which I also think shouldn't matter).

2. Should I try increasing memory for samtools, and by extension sambamba? is the best way to do this in bcbio_system.yaml? What would be good values for 250G nodes?

Any ideas for what to try next, I have a couple nodes I can dispatch on so I can try a couple of options.

Thank you for all the help

**Comment by chapmanb** [comment]
Tom;
Sorry that's still failing on you. I wonder if there is something problematic about that group of reads, since it looks like a single analysis block of reads fails -- is that right? From your comments, did you say you ran these same samples successfully before? This run looks like you're using the stable version, not the latest development, but I don't think anything has changed here to recently to effect this.

A couple of thoughts:

- I'm worried about the high memory specifications since you're using 80Gb for multiple concurrent sort programs. Could you try reducing this to 2Gb/core for samtools/sambamba to see if that improves the situation?
- Could you run with a single machine multi-core (say 'bcbio_nextgen.py your_config.yaml -n 10`) to see if you get any other warnings or error messages? I wonder if there is something failing reading or aligning the input files that we're missing because of multiple processes running concurrently.

Hope one of these helps get us further along. Thanks for all the patience and work debugging.

**Comment by tombair** [comment]
I was able to resolve this thanks to your suggestions. Turned out to be a corrupted genomic index. I did do some subsequent testing and found that memory values from 2G to 20G all worked so, if anyone googles this error up in the future memory is probably not the road to go down.

Thanks

**Comment by chapmanb** [comment]
Tom;
Thanks much for following up and glad you got it solved. Out of curiosity, what genome index got corrupted that caused this issue? We're hoping to move to md5 checksummed downloads using conda installs as a way to avoid partial downloads and other issues that might cause this, so hopefully that'll help in the future.

**Comment by tombair** [comment]
I think it happened when I was moving from one install location to another, I used rsync, but I also tried updating and doing some efforts to save downloads, your point that I was not using devel, which I thought I was lead me to believe I had gotten a hybrid of some sort. So pretty sure this is not  a  bcbio error instead a user error.
