### ISSUE TITLE
How can I use bcbio to perform chip-seq analysis?

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#1271]
Dear Brad,

I noticed that bcbio 0.9.6 could perform chip-seq analysis now, but there is little explaination for the options, and the demo script is incomplete, so could pls tell me more about it? especially for the macs2 option.

Thanks so much!

**Comment by lpantano** [comment]
Hi @junchend,

Sorry about the little documentation.
What are the parameters you want to use to run macs2?

for sample preparation you can use the template https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/illumina-chipseq.yaml and use a sample file where each sample has the `phenotype` and `batch` metadata. For instance, if you have two samples, one is the control input and the other is the chip sample, you just need to have a file like this:

```
samplenames,description,batch,phenotype
chip_1.fastq.gz,chip_1,group1,chip
input_1.fastq.gz,input_1,group1,input
```

That will make that chip_1 is used as the chip sample and input_1 as the input sample during macs2 analysis.

Is this better?

Then, if you want to add specific parameters you need to change `resources` in your template YAML file. In the link before, for instance, macs2 will be run using a broad peak and a q-value threshold of 0.05. If you want for instance default, you can remove that section for the template.

cheers

**Comment by junchend** [comment]
Dear lpantano,

Thanks for your response!

I have five samples:

sample1: input
sample2: groupA
sample3: groupA
sample4: groupB
sample5: groupB

as your suggestion:

samplenames,description,batch,phenotype
sample1.fastq.gz,chip_1, [group1,group2],input
sample2.fastq.gz,chip_1,group1,chip
sample3.fastq.gz,chip_1,group1,chip
sample4.fastq.gz,chip_1,group2,chip
sample5.fastq.gz,input_1,group2,chip

Is it OK? If yes, I will combine it with the demo yaml and have a test.

Besides peak calling, is there other analysis pipeline available for the following analysis?

Thanks again!

**Comment by junchend** [comment]
samplenames,description,batch,phenotype
sample1.fastq.gz,sample1, [group1,group2],input
sample2.fastq.gz,sample2,group1,chip
sample3.fastq.gz,sample3,group1,chip
sample4.fastq.gz,sample4,group2,chip
sample5.fastq.gz,sample5,group2,chip

**Comment by lpantano** [comment]
yeah, that would be. let me know if you have errors because i didnt test it using the same input for many samples although it should work. 

thanks!

sent not from my computer

**Comment by junchend** [comment]
Dear lpantano,

Thanks for your suggestion, it can be worked, I will check the detailed results.

**Comment by lpantano** [comment]
Hi,
I am closing this, but feel free to re-open if you have any issue.

thanks!

**Comment by ajitjohnson** [comment]
Hi @lpantano, what should the yaml look like if I want to run without the 'input' file? (i.e. to call peaks on all samples without the 'input' file)? Thank you.

**Comment by lpantano** [comment]
Hi,

we are supporting this now only for ATACseq, is this the case? or it is a
normal chipseq (TF or histone modification)?

Thanks

**Comment by ajitjohnson** [comment]
Ah okay. It is a normal ChIPseq experiment. Thank you.
