### ISSUE TITLE
Malformated combined.sf file 

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1272]
Hi @roryk, in my last analysis run I got a malformated combined.sf file. The headers of that file are `name, name, length, tpm, numreads, sample, Id`. Notice the duplication of the name field. The actual content of the lines is `name, length, effective_length, tpm, numreads, sample, Id`.

**Comment by lpantano** [comment]
thanks for catching that. Fixed here: fa6fd6b3b5a8505a6d810e3f0c46827374a9d5a8

**Comment by roryk** [comment]
Thanks Sven-Eric and Lorena.
