### ISSUE TITLE
bowtie (1) pipeline breaks with gzipped FASTQ files

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1274]
Apparently bowtie isn't able to cope with them and aborts. This likely warrants piping them through zcat or equivalent for aligning.

**Comment by chapmanb** [comment]
Luca -- thanks for the heads up on this. The latest development version now supports these inputs for bowtie and bowtie2, allowing them to be used in these standard pipelines. Let us know if you run into any problems at all with the latest version.
