### ISSUE TITLE
RNA-Seq results for TPM

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#1275]
Dear Brad,

I used new version of bcbio to do RNA-seq analysis, sailfish software was instead to generate tpm files, combined.isoform.sf.tpm file looks good, however, combined.gene.sf.tpm looks weird, something like: ENSMUSG00000000028      19.854706.87498 for one sample, could you please tell me how to use the value?

Thanks so much!

**Comment by roryk** [comment]
Hi @junchend,

Could you post up the file that looks corrupted?

**Comment by junchend** [comment]
Dear roryk,

gene_id 029     039     078     094     097     1       101     102     110     118     12      122     
ENSMUSG00000000001      57.7601 3.95423 0       136.086 0.0586557       18.4339 0.344596        0.027933
ENSMUSG00000000003      00      00      00      00      00      00      00      00      00      00      
ENSMUSG00000000028      000     000     000     000     01.446090       6.8305403.21153 01.308990       
ENSMUSG00000000031      24.77270.96821743.9258060.3871  00.363455000    00000   00000   00000   00000   
ENSMUSG00000000037      0002.23046000   000011.858700   0000000 00.027639900000 0000000 7.650650.8137020
ENSMUSG00000000049      0000    0000    0000    0000    00.54151100     0000    0000    0000    49.87480
ENSMUSG00000000056      50.373200       3.0369100       000     000     0.80150300      8.5990500       
ENSMUSG00000000058      000     000     000     000     000     000     000     000     000     000     
ENSMUSG00000000078      220.113 0.459013        0       0       0       0.430423        0       0.021279
ENSMUSG00000000085      000000027.97005.97610.36167900.0743007  00000000003.100490037.1765      00000000
ENSMUSG00000000088      426.431 64.1853 0.25249 2319.28 2036.37 1033.36 1299.94 1209.98 661.754 2681.82 
ENSMUSG00000000093      28.3272 0       0       0       0       0       0       0       0       0       
ENSMUSG00000000094      000     000     0.043990200     000     0.032108600     000     5.1488100       
ENSMUSG00000000103      0       0       0       0       0       0       0       0       0       0       
ENSMUSG00000000120      0       0.417192        0       0       0       0       0       0       0       
ENSMUSG00000000125      0       0       0       0       0       0       0       0       0       0       
ENSMUSG00000000126      00      00      00      00      00.80269        00      00      00      00      
ENSMUSG00000000127      00      4.743060        00      00      8.815750        21.1270 49.55110.145326 
ENSMUSG00000000131      000000000000000000.02422010     0001.3783900003.7528700.03761790010.282500000   
ENSMUSG00000000134      00000002.933750000.40601400     00000000.02501670000.63796500   00000.0503117000
ENSMUSG00000000142      0000000 0000000 0000000 000.7702890000  2.83859000000   0000000 000.4163080000  
ENSMUSG00000000148      000000  0003.1687300    000000  000000  3.9360300000    0000.039054400.163626   
ENSMUSG00000000149      0       0.565131        0       11.1113 0.955896        15.9036 0.596267    

I pasted some of the gene.tpm results, the number connected together, I don't know why.

Thanks!

**Comment by roryk** [comment]
Is that the raw text file? Are you sure it is actually connected together? Some of the rows have numbers in scientific notation which might be messing up what you are pasting them into.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
