### ISSUE TITLE
KeyError: 'fasta'

### ISSUE THREAD

**Issue by tanglingfung** [chapmanb/bcbio-nextgen#1277]
Hi Brad,

After upgrading the pipeline, I have the following error when I start a run. Where should I be looking for the configuration file? 

Paul

  File "/media/bigdata/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 179, in _check_ref_files
    for contig in ref.file_contigs(ref_info["fasta"]["base"], data["config"]):
KeyError: 'fasta'

**Comment by chapmanb** [comment]
Paul;
Sorry about the confusing error message. I was able to replicate this error if you don't add a `genome_build` to your configuration. I updated the configuration checking to identify this and provide a more useful message. Hopefully this explains the problem and once adding it you can get things running cleanly. Thanks again for the feedback.

**Comment by tanglingfung** [comment]
Thanks Brad. I just found that my .yaml file is truncated where the
genome_build is taken off for the last sample. Thanks for digging into the
issue.
