### ISSUE TITLE
(p)bgzip and multithreading/indexing

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1278]
Bcbio currently tries to do parallel bgzip by using the pbgzip binary and running grabix afterwards for the index. However, the vanilla bgzip version that is installed by bcbio (bgzip 1.3) now also seems to support multithreading (however, with the -@ parameter which is different from the one used in pbgzip). Also, it allows index creation at the same time as compression using the -i parameter. This generated a .gzi file that may be related to the .gbi file made by grabix. Would it make sense then to only support bgzip and make direct use of its multithreading and indexing capabilities?

**Comment by guillermo-carrasco** [comment]
Oh, that indeed sounds interesting... any thoughts @chapmanb ? I can give it a try if you want :-)

**Comment by chapmanb** [comment]
Sven-Eric -- thanks so much for the heads up. I'd missed this new option. Guillermo, if you are able to benchmark this versus pbgzip that would be awesome. Great to see this making it into the main bgzip distribution.

There don't appear to be many docs on the .gzi index but it doesn't look like that replicates what we're getting with .gbi and grabix, which is direct access to specific lines in the file so we can chunk inputs. It looks like it can help with starting at specific blocks but in a more low-level way.

Thanks again.

**Comment by guillermo-carrasco** [comment]
Hi, not very exhaustive, but I did some tests that seem to reveal that `pbgzip` is quite a lot faster than `bgzip` in multithreading. Test is basicalli compressing a ~150GB FASTQ file.

Compression time with 8 threads with the new version of `bgzip`:

```
 login01 ~/tests/pbgzip/input ~> /usr/bin/time bgzip -@ 8 NA12878_PG_1.fastq
12270.31user 357.43system 41:25.91elapsed 507%CPU (0avgtext+0avgdata 541408maxresident)k
414995840inputs+103508808outputs (3major+100140817minor)pagefaults 0swaps
```

Compression time with the same number of threads for `pbgzip`

```
login01 ~/tests/pbgzip/input ~> /usr/bin/time pbgzip -t 8 NA12878_PG_1.fastq
21012.17user 2110.01system 25:38.68elapsed 1502%CPU (0avgtext+0avgdata 498096maxresident)k
414989208inputs+89481480outputs (4major+427842383minor)pagefaults 0swaps
```

Should we better keep using `pbgzip` until `bgzip`'s algorithm is improved?

**Comment by schelhorn** [comment]
In that case, let's leave it how it is :) Thanks for checking. Closing.
