### ISSUE TITLE
bammerge stuck in qsub interactive session

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1279]
I started using bcbio the following way, as there are issues with using pbspro (https://github.com/chapmanb/bcbio-nextgen/issues/1276).

I started up an interactive qsub job, with 10 cores and 70Gb memory reserved, and running bcbio with the `-t local -n 8` option. It converts the bam files to fastq, indexes them, etc and does the bwa alignment. However, when the bammerge step starts, the process is stuck at the `flushing read ends lists...done.` message, and the final bam file has 0 size, nothing gets written.

I tried to increase reserved memory size, number of cpus, but that didn't help. Also, I have enough space, and I have no quota on the scratch disk where I have the work dir. Any ideas on what might be the problem?

**Comment by chapmanb** [comment]
Endre;
Sorry about the issue. This is a frustrating one as that's not giving us much to go on. If you look in the temporary directories (`tx/tmp*` in `align/your_sample`) is anything getting written? The bammerge pipes into bamsomadup so will be writing temporary files there before anything gets written to the final output directory.

My guess is that it's making something unhappy with IO on your shared filesystem. If so, you could set a temporary directory to something local (if you have big local storage) to see if that helps it proceed. Add a `resources: tmp: dir` statement to the top level of your sample.yaml file to try this:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory

Hope this helps some.

**Comment by razZ0r** [comment]
For whatever reason, the merge started working now, when I reran the pipeline to start debugging.
