### ISSUE TITLE
Looking for summary.pdf and error rendering R report

### ISSUE THREAD

**Issue by pfujita** [chapmanb/bcbio-nextgen#1282]
Hello bcbio team,

Thank you for your excellent work on this resource. We are in the process of updating to the latest stable version of bcbio (0.9.6) and have most of it working. I am seeing two issues with our installation which I'm hoping are related. 

The old version we were running generates a summary pdf in the main results folder - typically [samplename]-summary.pdf. Our test runs seem to complete successfully, with one small R rendering error (the vcfs and bams look fine and other files are as expected). I'm wondering if that R error is precluding generation of this pdf, or, if things have changed enough since the old version that this pdf is no longer a part of the final results directory, or has been deprecated?

The R report rendering error - which may also be related to #1122 - is as follows:

Quitting from lines 54-158 (report-ready.Rmd)
Error in file(file, "rt") : cannot open the connection
Calls: render ... withCallingHandlers -> withVisible -> eval -> eval -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/test_dir/report/metrics/metrics.tsv': No such file or directory

Execution halted
' returned non-zero exit status 1

The file: /test_dir/report/metrics/metrics.tsv does exist though, so I'm not sure why it's complaining. I also tried rerunning report-ready.Rmd outside bcbio but I get the same error. Any ideas? Could this be fixed by updating to the most recent dev version?

Thanks for your help,

Pauline

**Comment by lpantano** [comment]
Hi @pfujita 

sorry about the problems. Indeed the last development version should have this fixed. It was an error in the order of the things done in the coverage report. (0a1ce99a486f290d3d925dcdfe5d1a6c61b7418f)

But, I am confused because if you run the script after bcbio ended should be fine, maybe another error appears, but this one shouldn't be there. I will try to replicate anyway.

Where is the path where the report Rmd file is? Is the same than `/test_dir/report/`?

About the PDF file, I am nor sure, these two shouldn't be related since be allow the R report to fail since it is not in its stable version yet. I will try to look into this as well.

**Comment by lpantano** [comment]
Hi,

we have made some changes to the report, and since is in dev version, we don't run it any more automatically. This report is mainly useful when using `coverage` option in the YAML file. We will work on that, and hopefully in one month we can get the RMD report done.

About the PDF file, It seems that only happens if the method for upload is galaxy.  Is it something that you need? or were you just checking?

thanks!

**Comment by pfujita** [comment]
Hi @lpantano,

Sorry for the delay. Thanks for the prompt feedback on everything - very useful. 

1. For the RMD stuff - here are the contents of my report dir:

fastqc
metrics
qc-coverage-report-run.R
report-ready.Rmd
variants

And here are the contents of qc-coverage-report-run.R:

$ cat qc-coverage-report-run.R 
library(rmarkdown)
render("/test_dir/report/report-ready.Rmd")

If I go into R and run those commands it runs for the first part of the file then ends with the following error:

[...]
  |..................                                               |  28%
label: table (with options) 
List of 1
 $ results: chr "asis"

Quitting from lines 55-159 (report-ready.Rmd) 
Error in if (!all(cuts == sort(cuts))) stop("'cuts' must be sorted increasingly") : 
  missing value where TRUE/FALSE needed

In case it's helpful we did have trouble getting pandoc installed (had to install it as a one-off as it wasn't getting installed along with everything else using the install script), but the pandoc missing error I'd been seeing went away so I think it's working now.

2. For the pdf, our customers use the contents of that *summary.pdf as metrics for the success of the pipeline run so we need it. We don't upload to galaxy as we're running sensitive data, but do want the pdf to be generated. Is its generation is disabled by default in the absence of galaxy upload? And if so, is there a way (maybe some setting in one of the yaml files or a minor code edit?) to get it to generate the pdf even though we don't plan to upload to galaxy?

Thanks so much for your help!

**Comment by chapmanb** [comment]
Pauline;
Apologies, in your back and forth with Lorena I missed the questions about the summary.pdf file. You must have been upgrading from a much older release -- those were removed a couple of years ago in favor of using external tools for QC:

https://github.com/chapmanb/bcbio-nextgen/commit/0b6eaafaf0e85f6dca80624705f16c3c16db174d#diff-7ee8c61b5ce1e5f1c6740d0007ea6111

So there is no error or configuration setting -- we don't have those reports in the current bcbio. There should be a lot of metrics available in the `qc` directory of the output and we're actively working to produce a MultiQC report (https://github.com/ewels/MultiQC) as part of the output. Lorena is up to date on the status of all this but hopefully it'll provide a helpful replacement for the older summary reports. Hope this helps.

**Comment by lpantano** [comment]
For now, multiqc only runs if you put in the YAML file `tools_on: [multiqc]` but I will change to run by default next week, now that we had a new stable release.

**Comment by pfujita** [comment]
@chapmanb - thank you! That was exactly the info I needed. I see now I should have checked the [version history](https://github.com/chapmanb/bcbio-nextgen/blob/master/HISTORY.md)! We are indeed updating from an old version. Thanks to both of you - this information is incredibly helpful. We'll update to the newest stable release and try out that multiqc setting in our YAML files.

**Comment by pfujita** [comment]
Hi again @lpantano, 

I upgraded to 0.9.7 and I tried adding this line (do I have the syntax correct?) to my sample.yaml: 

tools_on: [multiqc]

but I'm getting an error when it gets to the multiqc processing step:

...
[2016-04-04T19:05Z] multiprocessing: coverage_report
[2016-04-04T19:05Z] multiprocessing: qc_report_summary
[2016-04-04T19:05Z] copy qsignature
[2016-04-04T19:05Z] summarize fastqc
[2016-04-04T19:05Z] summarize metrics
[2016-04-04T19:05Z] multiprocessing: qsignature_summary
[2016-04-04T19:05Z] multiprocessing: multiqc_summary
Traceback (most recent call last):
```javascript
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==0.9.7', 'bcbio_nextgen.py')
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.2.2-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 39, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 82, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 184, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 49, in generate_parallel
    multiqc_info = run_parallel("multiqc_summary", [samples])
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 143, in multiqc_summary
    return qcsummary.multiqc_summary(*args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 878, in multiqc_summary
    multiqc = config_utils.get_program("multiqc", samples[0][0]["config"])
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 184, in get_program
    return _get_program_cmd(name, pconfig, config, default)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 210, in wrap
    raise CmdNotFound(" ".join(map(repr, (fn.func_name, name, pconfig, default))))
bcbio.pipeline.config_utils.CmdNotFound: '_get_program_cmd' 'multiqc' {} None
```


I have 2 other samples that have similar sample.yaml files but don't have the multiqc line and they completed without error. As you can see from the beginning of the stack trace we're running 0.9.7(stable), it looks like there were fairly recent multiqc related commits - if I upgraded to pull in [these changes](https://github.com/chapmanb/bcbio-nextgen/commit/2b3bdcbe368b6206cc1223859ce25ff2b5768931) would it end up fixing this issue I'm seeing? Or am I maybe not enabling multiqc with the correct flags/options?

Thanks again for all your help!

**Comment by lpantano** [comment]
Hi sorry about that.

Did you updated the tools as well? I added the tool at the same time, so need to be installed.

i would try `bcbio_nextgen.py upgrade -u skip --tools`

If not you can install multiqc yourself using the conda command lines that is located in the sample place the anaconda path for bcbio. 

`$PATH_TO_BCBIO_ANACONDA/conda install multiqc -c bioconda`

hope this help.

**Comment by pfujita** [comment]
Sorry for not thinking of that. Updating the tools fixed it and we are now happily running multiqc. Thanks again!!

**Comment by lpantano** [comment]
If you have any further problem, let us know. 

I am working to migrate everything to multiqc, so probably in the next release it would be much more complete.

thanks

**Comment by pfujita** [comment]
Hi again,

One more quick question. We have this running now with multiqc using multiple callers and joint calling. In the final "report" directory we get a subdirectory called variants, but it is empty. We are wondering what is supposed to end up in this directory and/or if we are doing something wrong that's causing this directory to be unpopulated. Our runs finish without error, but as we're doing variant calling, this directory looks it might have key qc/stats files of interest.

thanks again,

Pauline

**Comment by lpantano** [comment]
I would need to check this specific case.

Inside qc/report/metrics, do you have variants stats in the file that is called metrics.txt?

**Comment by pfujita** [comment]
I'm not sure if you mean the report directory, or the qc directory. Hopefully one of these outputs is helpful. Our report directory contains the following:

$ ls -1 report/*
report/qc-coverage-report-run.R
report/report-ready.Rmd

report/fastqc:
Per_base_N_content.tsv
Per_base_sequence_content.tsv
Per_base_sequence_quality.tsv
Per_sequence_GC_content.tsv
Per_sequence_quality_scores.tsv
Per_tile_sequence_quality.tsv
Sequence_Length_Distribution.tsv

report/metrics:
metrics.tsv
tx

report/variants:


And our qc directory looks like:
$ ls -1 qc/[samplename]/*
qc/[samplename]/fastqc:
fastqc_data.txt
fastqc_report.html
Per_base_N_content.tsv
Per_base_sequence_content.tsv
Per_base_sequence_quality.tsv
Per_sequence_GC_content.tsv
Per_sequence_quality_scores.tsv
Per_tile_sequence_quality.tsv
[samplename].zip
Sequence_Length_Distribution.tsv

qc/[samplename]/qsignature:

qc/[samplename]/samtools:
[samplename].txt
tx

qc/[samplename]/tx:

And if I do a search for metrics.* across all the dirs produced by our run I only see 2 files getting produced (no .txt):

$ find . -name "metrics.*" -print
./report/metrics/metrics.tsv
./[flowcell id]/report/metrics/metrics.tsv

**Comment by lpantano** [comment]
this one:

report/metrics:
metrics.tv

do you see inside that file stats related to variants?like total variants..etc?

**Comment by pfujita** [comment]
Yes - this has stats, with the following columns:

head -1 report/metrics/metrics.tsv 
%GC	
Average_insert_size	
Duplicates	
Duplicates_pct	Mapped_reads	
Mapped_reads_pct	Name	
Quality_format	Sequence_length	
Sequences_flagged_as_poor_quality	
Total_reads	
Transition/Transversion	
Variations_heterozygous	
Variations_homozygous	
Variations_in_dbSNP	
Variations_in_dbSNP_pct	
Variations_total	
mapped	
offtarget	
offtarget_pct	
avg_coverage_per_region	
sample

**Comment by lpantano** [comment]
thanks, will try to find the problem then. Can you paste here the template yaml file you used, so I can try to replicate? thanks a lot

**Comment by pfujita** [comment]
Thank you for looking into it. Here is the sample.yaml we're using:
<pre>
fc_date: 20HHFLHB
fc_name: HHFLHBCXX
upload:
  dir: samplename 
details:
  - files: [samplename/samplename_R1.fastq, samplename/samplename_R2.fastq]
    description: samplename_kapa-NGv3-PE100-NGv3
    analysis: 'variant2'
    genome_build: GRCh37
    lane: samplename
    algorithm:
      aligner: bwa
      trim_reads: false
      recalibrate: gatk
      realign: gatk
      variantcaller: [gatk, gatk-haplotype, platypus, vardict]
      tools_on: [multiqc]
      coverage_interval: regional
      coverage_depth: high
      variant_regions: /reference_data/capture_regions/xgen-exome-research-panel-targets.bed
      clinical_reporting: true
</pre>

**Comment by lpantano** [comment]
hi, you need to add to the yams file a:

coverage: bed_file_region_of_interest

to get the main part of the report folder populated. I understand that maybe this case I could separate, so will work on that. You could use the same bed file that you have for variant_regions.

cheers

**Comment by pfujita** [comment]
Hi again,

I'm not sure if this belongs in a new ticket - let me know if I should put this in a new thread.

Now we're looking to run the same set of callers through joint/pooled sample calling. To this end it looks like this isn't possible with vardict ([line 355](https://github.com/chapmanb/bcbio-nextgen/blob/a5e4134094010d2f8486bad7c3695f01dc14c604/bcbio/pipeline/run_info.py))? We're wondering if there's a way to configure the sample.yaml file to run vardict as a single sample job, while running the same sample + an additional pool of samples as a pooled samples job for the other callers? (we're guessing not, but it's worth asking) 

Finally, if we were to run the same sample twice - once with a sample.yaml that runs a single sample vardict job, and once with a sample.yaml that runs a pooled sample job with gatk and platypus, would it be possible to still make use of bcbio's ensemble calling to fold all the vcfs into a single ensemble vcf?

Thanks for any insight you might have to offer. We can think of ways to hack this, but we're hoping there's a way to do this more cleverly via the bcbio code as-is.

Best regards,

Pauline

**Comment by chapmanb** [comment]
Pauline;
Thanks for the thoughts on this. Unfortunately there isn't an easy way to use bcbio to do either of these things right now. I can definitely see how it would be useful but haven't coded up an easy path to do it. I think the best approach might be to have the VarDict code process each sample independently within a batch so that the current setup works even if it doesn't get pooled calling underneath.

This is definitely something we can take on but will be a bit of a project so I can't offer anything right now. It might be good to create a new ticket and we can track progress there.

Sorry to not have an approach right now but hope this helps.
