### ISSUE TITLE
Paralleization of callable.py

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#1286]
I've noticed that[ this part](https://github.com/chapmanb/bcbio-nextgen/blob/80deb4b7a2018786e6f3bad48821cf720ac0fd2e/bcbio/bam/callable.py) is not well configured on my machine - it could be parallelized much more. I have looked at the `parallel_callable_loci` method, but I do not quite understand from which part of the configuration file it does get the number of parallel jobs from. 

Could somebody help me out with this?

Here is the function:

```
def parallel_callable_loci(in_bam, ref_file, data):
    config = copy.deepcopy(data["config"])
    num_cores = config["algorithm"].get("num_cores", 1)
    data = {"work_bam": in_bam, "config": config,
            "reference": data["reference"]}
    parallel = {"type": "local", "cores": num_cores, "module": "bcbio.distributed"}
    items = [[data]]
    with prun.start(parallel, items, config, multiplier=int(num_cores)) as runner:
        split_fn = shared.process_bam_by_chromosome("-callable.bed", "work_bam", remove_alts=True)
        out = parallel_split_combine(items, split_fn, runner,
                                     "calc_callable_loci", "combine_bed",
                                     "callable_bed", ["config"])[0]
```

Thanks much
Michael

**Comment by chapmanb** [comment]
Michael;
The callable calculations run multicore for each sample and should use the same number of cores allocated for alignment for the sample. How are you running your analysis, on a single machine or over a cluster? Practically, it'll take the total available nodes from the `-n` argument to bcbio_nextgen.py and the number of cores for alignment from `default -> cores`, balanced by memory estimation:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/bcbio_system.yaml#L21

If you can describe your analysis, how you're running it, and what you're seeing happy to try and provide more direct suggestions. Hope this helps.

**Comment by mpschr** [comment]
Hi Brad

Thanks for your answer - for some reason I had a 2 in the default line, because I thought it will make multiple jobs each using up to two cores each. So I understand it is better to specify a high number in the default section?

I am running the variant2 pipeline on one machine (locally) that can spare 20 cores for the pipeline.

**Comment by mpschr** [comment]
I think in order to be able to configure well the bcbio_system, it would be useful to have a documentation file which states the if a tool is multithreaded (and is run only few times per sample/genome) or single-threaded (and many little jobs are run)

Then one could derive:
- The tool is being run for many chunks of the genome:  therefore it would be better to specify few cores so multiple jobs can run in parallel for each little junk
- The tool is run few times for a whole sample / sample group but has multicore support: Therefore it is better to assign more cores to that tool

**Comment by chapmanb** [comment]
Michael;
Sorry about the confusion. Generally with a single machine and a few samples you're best off giving all of the cores to the default. bcbio should parallelize the single core chunk regions (variant calling) by region and the other parts (which can use multiple cores) as cores, processing individual samples. I'd be happy to add more details on this in the docs. Would a section in the "Installation" part of the document be the most obvious place to put these recommendations to make it more explicit? Thanks much for the help and suggestions.

**Comment by mpschr** [comment]
Hi Brad

I guess this section would be the one I would have checked first: http://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html

**Comment by chapmanb** [comment]
Michael;
Thank you. I added details on setting cores here:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html#tuning-core-and-memory-usage

Definitely let us know if any other information would help to make this clear. Hopefully things are running smoothly for you now and thanks again for the helpful thoughts.

**Comment by mpschr** [comment]
Hi Brad;

Great - that is actually a very helpful section!

Thanks very much
Michael
