### ISSUE TITLE
User experience; Reference upgrading without bowtie2

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1289]
First, I try to upgrade with this command.
`$ bcbio_nextgen.py upgrade --genomes hg38 --aligners hisat2`

![2016-03-25 09 19 25](https://cloud.githubusercontent.com/assets/4966343/14035250/7322b3f4-f26f-11e5-9ff8-b199769655ea.png)

 
This error occurred due to absence of bowtie2.
so, I run this command and it is ok.
`$ bcbio_nextgen.py upgrade --aligners bowtie2
`
If you want to improvment of user experience in bcbio, consider this pattern.

Thanks in advance!

**Comment by chapmanb** [comment]
Hyunmin;
Sorry about the issue. There was a temporary problem with the bowtie2 install, which was missing some of the binaries. This was broken about 3 days ago and fixed yesterday so if you had an install or upgrade within that 2 day window that would explain the missing binary and error message you saw.

Hopefully this should be fixed now if you do an upgrade and add `--tools` to the command line. Thanks again for reporting it.
