### ISSUE TITLE
More convenient variant_regions descriptions

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1290]
Let's assume I want to call small variations in a WGS sample in coding regions only. May I specify `variant_regions: transcripts1e5` as I can with the `sv_regions` parameter or do I _have_ to specify a BED file here?

**Comment by chapmanb** [comment]
Sven-Eric;
Right now it doesn't have the convenience settings, so you have to specify a BED file. It would be useful to enable this and also provide BED files for standard captures to try and make that easier as well. Thanks for the nice ideas, we'll add it to the list of things to work on.

**Comment by schelhorn** [comment]
Great, thanks. Closing.
