### ISSUE TITLE
Incorrect logon for Broad resource: mills_indels

### ISSUE THREAD

**Issue by 6C3C41** [chapmanb/bcbio-nextgen#1291]
# Incorrect logon for Broad resource: mills_indels

Thanks for looking at this! Looks like a hardcoded credential is not correct. Thanks, Andrew

## Error

> Running GGD recipe: mills_indels
> --2016-03-29 10:42:05--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
>            => ‘-’
> Resolving ftp.broadinstitute.org (ftp.broadinstitute.org)... 69.173.80.251
> Connecting to ftp.broadinstitute.org (ftp.broadinstitute.org)|69.173.80.251|:21... connected.
> Logging in as gsapubftp-anonymous ...
> Login incorrect.

## Traceback

> gzip: stdin: unexpected end of file
> Traceback (most recent call last):
>   File "/home/ubuntu/bcbio/bin/bcbio_nextgen.py", line 207, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/home/ubuntu/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 91, in upgrade_bcbio
>     upgrade_bcbio_data(args, REMOTES)
>   File "/home/ubuntu/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 267, in upgrade_bcbio_data
>     cbl_deploy.deploy(s)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
>     configure_instance(options, actions)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
>     setup_biodata(options)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
>     install_proc(options["genomes"], ["ggd", "s3", "raw"])
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
>     _prep_genomes(env, genomes, genome_indexes, ready_approaches)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 474, in _prep_genomes
>     retrieve_fn(env, manager, gid, idx)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 796, in _install_with_ggd
>     ggd.install_recipe(env.cwd, recipe_file)
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
>     recipe["recipe"]["full"]["recipe_type"])
>   File "/home/ubuntu/bcbio/genomes/Mmusculus/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
>     subprocess.check_output(["bash", run_file])
>   File "/home/ubuntu/bcbio/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['bash', '/home/ubuntu/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1

**Comment by 6C3C41** [comment]
Now working. (?)

**Comment by chapmanb** [comment]
Sorry about the problems. The Broad FTP server can get overloaded and reports a variety of errors when this happens, including the login problem. Unfortunately the current solution is, as you found out, to wait and try again. Thanks for the patience and glad it's now working for you.

**Comment by 6C3C41** [comment]
Thanks, sorry about the premature issue. Naturally it worked ten minutes after posting.
