### ISSUE TITLE
Specific if jvm_opts sets memory usage per core or per virtual machine

### ISSUE THREAD

**Issue by 6C3C41** [chapmanb/bcbio-nextgen#1292]
It is not clear to me in the documentation how `jvm_opts` is passed to the jvm. How should I set this option with respect to my total core and memory availability?

Thank you!
Andrew

**Comment by chapmanb** [comment]
Andrew;
The memory specifications are per-core and automatically get scaled to the cores allocated to a process. Sorry this was not more clear -- I added additional documentation on it:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html#tuning-core-and-memory-usage

Let us know if you have any other questions and thanks much for the helpful feedback.
