### ISSUE TITLE
sailfish - missing shared object

### ISSUE THREAD

**Issue by kdaily** [chapmanb/bcbio-nextgen#1294]
When I try to run sailfish, I get the following:

```
# sailfish 
sailfish: error while loading shared libraries: libboost_iostreams.so.1.57.0: cannot open shared object file: No such file or directory
```
```
# which sailfish
/opt/bcbio/bin/sailfish
```
```
# find / -type f -name 'libboost_iostreams.so*'
/usr/lib64/libboost_iostreams.so.5
/opt/bcbio/anaconda/pkgs/boost-1.60.0-py27_0/lib/libboost_iostreams.so.1.60.0
/opt/bcbio/anaconda/lib/libboost_iostreams.so.1.60.0
```

Seems like a mismatch?

**Comment by roryk** [comment]
Sorry about that, the formula needs to get fixed. In the meantime you can fix this by doing:

```
/opt/bcbio/anaconda/bin/conda install -c bioconda boost=1.57.0
```

**Comment by kdaily** [comment]
Thanks @roryk - confirm that fixes. It did downgrade from the installed 1.6.0 version - are there other things that may depend on this and be broken (or, how might I check for that)?

**Comment by lpantano** [comment]
i think for now that is. If you have any further problem let us know. Hopefully @chapmanb and @roryk fixed this. Thanks!
