### ISSUE TITLE
bcbio_nextgen.py upgrade does not upgrade to the latest version (0.9.7)

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1296]
Maybe it's just a matter of conda lagging, but:

```
bcbio_nextgen.py --version                   
0.9.6

bcbio_nextgen.py upgrade -u stable
Fetching package metadata: ......
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /opt/bcbio/anaconda:
#
bcbio-nextgen             0.9.6                    py27_0    bioconda
Upgrade of bcbio-nextgen code complete.
Installing additional tools
Upgrade completed successfully.
```

**Comment by lbeltrame** [comment]
I was able to workaround the problem with

```
conda install -c bioconda bcbio-nextgen=0.9.7
```

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue. Unfortunately the install wasn't cleaning up a locally downloaded `conda-requirements.txt` file (in the directory you run the update from). So if you have that from a previous upgrade it'll use the old version. I pushed a fix for this but that won't get in until the next release:

https://github.com/chapmanb/bcbio-nextgen/commit/856f8e721fd79106c7002d13b9dfcca24500e442

So the workaround is to `rm conda-requirements.txt` and it'll get the latest. Thanks much for the report.

**Comment by lpantano** [comment]
I hoped that trick did the job, feel free to re-open if it happens again.

thanks a lot!
