### ISSUE TITLE
How can I handle the memory size with RTG tools?

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1298]
cd work
bcbio_nextgen.py ../config/T1208D0213-illumina.yaml

> subprocess.CalledProcessError: Command 'set -o pipefail; export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=2g && rtg vcfeval --threads 1 -b /TBI/People/tbi/brandon/BioResources/giab/grch37/validation/giab-NA12878/truth_small_variants.vcf.gz --bed-regions /TBI/People/tbi/brandon/Project/bcbio/T1208D0213-wgs/work/validate/T1208D0213/freebayes/T1208D0213-sort-callable_sample-T1208D0213-freebayes-wrm.bed -c /TBI/People/tbi/brandon/Project/bcbio/T1208D0213-wgs/work/freebayes/T1208D0213-effects-ploidyfix-filter.vcf.gz -t /TBI/People/tbi/brandon/BioTools/bcbio/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/rtg/GRCh37.sdf -o /TBI/People/tbi/brandon/Project/bcbio/T1208D0213-wgs/work/validate/T1208D0213/freebayes/rtg --vcf-score-field='QUAL'
> 
> Error: There was not enough memory available for the task. Try increasing allocated memory or adjusting command parameters to reduce memory requirements.

Where is config file or is there method?

Thanks in advance!

**Comment by hmkim** [comment]
I found the memory configuration in below script.

/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py

```
190         if os.path.isfile(rtg_ref):
191             rtg_ref = os.path.dirname(rtg_ref)
192         threads = min(dd.get_num_cores(data), 6)
193         mem = "%sg" % max(threads, 2)
194         cmd = ["rtg", "vcfeval", "--threads", str(threads),
195                "-b", rm_file, "--bed-regions", interval_bed,
196                "-c", vrn_file, "-t", rtg_ref, "-o", out_dir]
197         cmd += ["--vcf-score-field='%s'" % (_pick_best_quality_score(vrn_file))]
198         mem_export = "export RTG_JAVA_OPTS='-Xms1g' && export RTG_MEM=%s" % mem
199         cmd = mem_export + " && " + " ".join(cmd)
200         do.run(cmd, "Validate calls using rtg vcfeval", data)


```

**Comment by chapmanb** [comment]
Hyunmin;
Thanks for the report and sorry about the issue. We should have supplied a standard way to adjust this memory via the standard resource mechanism:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html#tuning-core-and-memory-usage

and I pushed a fix now which respects this. If you update to the latest development (`bcbio_nextgen.py upgrade -u development`) it'll do this correctly without needing to manually change the code. Hope this helps get your analysis finished.

**Comment by hmkim** [comment]
Thanks for your update. I finished the validation job with correction of memory size using RTG.
