### ISSUE TITLE
Coverage calculation for the report fails with file not found

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1299]
Apparently it tries to load a file that's not there:

```
[2016-04-01T12:18Z] Run coverage for 20724-IL-LY
[2016-04-01T12:18Z] sambamba-depth: couldn't open file /scratch/bcbiotx/f183f606-f6f3-4979-a04b-8dfcc65ac580/tmp06vMsc/0425761_Covered.bed or find reference /scratch/bcbiotx/f183f606-f6f3-4979-a04b-8dfcc65ac580/tmp06vMsc/0425761_Covered.bed
```
There are no references to that file in the `-commands.log` save for what I wrote, so I guess that's either not created, or deleted in the transaction before it's actually used.

EDIT: In fact, I think that file is not even created. I wiped the `/scratch/bcbiotx` directory before, and no subfolders are being created when that command is run.

**Comment by lbeltrame** [comment]
The reason is absolutely not obvious, and looks like a bug in `sambamba-depth`. If the BED contains track information (`browser position` etc) which are conformant to the specification, `sambamba-depth` errors out with "file not found".

And all I can think is that a result can be True, False, or [FileNotFound](http://thedailywtf.com/articles/What_Is_Truth_0x3f_) ;)

**Comment by lpantano** [comment]
Sorry about that @lbeltrame, I was thinking in that, but I remembered @chapmanb added something. Will check the code again, because that for sure is not obvious at all.

thanks!

**Comment by lpantano** [comment]
I checked and right now can detect '#' commented lines. I added the UCSC header keywords as well.

thanks
