### ISSUE TITLE
bcbio fail to pickup the process at the failed point

### ISSUE THREAD

**Issue by John-cgr** [chapmanb/bcbio-nextgen#1301]
Hi,

I am trying to identify CNV and SNP from some samples. Bcbio failed due to issues of disk space. To get more disk space, I removed the "align_prep" folder to another drive. This turned out to be a silly mistake since bcbio restarted from scratch after re-run. Then I moved back the "align_prep" folder. However,  bcbio still tried to start the process from the very beginning, and failed to pickup the process at the failed point (in the middle of mutect). How to fix this problem? Thanks.

John

**Comment by chapmanb** [comment]
John;
Sorry about the issues. We'd need more detailed information to tell you exactly what to look at in terms of re-use. Practically, bcbio determines re-use for looking at the presence of files and timestamps, only re-running steps if the inputs changed. What process is bcbio re-running that it shouldn't? Can you provide a listing of the inputs/outputs to that step in your work directory to see if we can spot what is happening? Hope this helps.

**Comment by lpantano** [comment]
Hi @John-cgr 

I am closing this because it seems that maybe it was solved at some point.

Come back if you have more issues

cheers
