### ISSUE TITLE
Express binary not found

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1304]
I just did a clean install of bcbio and the express binary wasn't part of the install, so adding `express` to the expression callers in the config resulted in an error by `_get_program_cmd`. I checked in the bcbio `bin` and `anaconda/bin` directories and couldn't find it there. Manually running the CBL formula for express_binary seemed to do the trick. Did anything happen to the CBL reqs of the express formula in bcbio?

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the problem. I added express in as a conda install so it should now be available if you do an `upgrade --tools` run. @roryk I had some notes that we were deprecating express but not sure about the current status with sailfish and friends. We could remove it if you have a better plan in place for this functionality going forward.

**Comment by schelhorn** [comment]
Yes, deprecating seems to be an option for the near future, however usage of combined quasi-alignment indexes has not yet been validated for disambiguated samples. So I would like to test first if sailfish generates about the same results as express in that setting.

**Comment by roryk** [comment]
Thanks Sven-Eric, sorry about the express issue. We won't turn it off until we know it looks good.

**Comment by schelhorn** [comment]
To report again on this issue: I investigated eXpress vs sailfish PDX analyses for RNA-Seq quantitation, basically looking at linear correlation and RSME of the TPM values for both methods on the gene level. The benchmark data set consisted of 30 pancreas models with significant stromal conflagration that had been deeply sequenced (50M reads). Quantitated genes were categorized by homology to mouse, paralogy to other human genes, GC content, mapability, low complexity regions, and difficulty wrt. expression quantitation based on a recent paper. 

Concerning the genes of interest that had only human-mouse homomogy as confounds (so none of the other categories), the linear correlation was >0.94, which seems to indicate to me that both methods are reporting sufficiently similar results for for disambiguated samples. 

So deprecating eXpress should be fine in my view. We still need STAR plus disambiguation for detecting transcript fusion events, unfortunately.
