### ISSUE TITLE
Order of Tumor and Normal Sample change in vcf from different caller

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1305]
Hi Brad, 
This is probably non a major Issues but, I have noticed for pair Tumor/Normal pair some caller first place the Normal and other Place the Tumor sample in the vcf.

Freebayes, Mutect2, vardict have Tumor sample at first position.
GATK-HC, mutest, varscan have Normal sample as position.
ensemble is inconsistent depending on samples. 

Thanks!
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks for asking about this. It's definitely annoying but not something we're likely to tackle in bcbio as it would require doing a lot of work re-writing VCF files. Generally it's best to assume nothing about the order of samples and to reference them based on sample names. Hopefully that works for your downstream processing.
