### ISSUE TITLE
Error related to salifish with RNAseq workflow

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1306]
/TBI/People/tbi/brandon/BioTools/bcbio/usr/local/share/bcbio/galaxy/../anaconda/bin/sailfish: **error while loading shared libraries: libboost_iostreams.so.1.57.0: cannot open shared object file: No such file or director**

I attched my log files.

I'll try to fix this error with recompile or supply the library for salifish.

Anyone could you solve this problem?

Thanks in advance!

[bcbio_log.zip](https://github.com/chapmanb/bcbio-nextgen/files/203498/bcbio_log.zip)

**Comment by chapmanb** [comment]
Hyunmin;
Sorry about the problem. Could you try updating to the latest set of bcbio tools?
```
bcbio_nextgen.py upgrade --tools
```
When libboost updated sailfish and salmon got out of date but we rebuilt them with the latest version. You should get `0.9.0-1` as the updated version. Hope this fixes it for you, feel free to reopen this if not.

**Comment by hmkim** [comment]
I solved it with your suggestion. Thanks.
