### ISSUE TITLE
multiqc report in RNA-Seq workflow

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1307]
Multiqc is a very nice addition for looking at many samples at once, thanks for adding. However, at least for RNA-Seq it seems as if the generated multiqc HTML report and associated data files are not copied to the output directory (even if multiqc is in `tools_on`). Could we get that enabled, please?

**Comment by lpantano** [comment]
thanks yes sorry about that, i have a commit for that, will do it today.

thanks!

sent not from my computer

**Comment by lpantano** [comment]
I think it should work now. And now,multiqc runs by default since it is pretty fast.
thanks!

**Comment by schelhorn** [comment]
Thanks a bunch!

**Comment by ewels** [comment]
This is great! Thanks @lpantano, let me know if I can be of any help.
