### ISSUE TITLE
gatk-variant template 's recalibrate step before realign step?

### ISSUE THREAD

**Issue by plsysu** [chapmanb/bcbio-nextgen#1309]
Hello,

I tested bcbio on exome data. And there's a some difference on GATK's best pratice 's recommendation. 

One is that the base quality score recalibratation step, in bcbio, it's earlier than realignment. Is this appropriate?

 I have compared my own 's shell scripts' results with bcbio's results, bcbio called more variants.

**Comment by chapmanb** [comment]
Peng;
Thanks for the questions on the bcbio implementation. You're right that we do BQSR prior to realignment, which is not the latest GATK recommendation. Doing realignment first creates a more complex computational setup and our validations have found that BQSR and realignment don't provide a big improvement in sensitivity and precision:

http://bcb.io/2013/10/21/updated-comparison-of-variant-detection-methods-ensemble-freebayes-and-minimal-bam-preparation-pipelines/

We typically leave these steps out of our analysis pipelines now so haven't had much focus on tweaking them.

Practically, we'd love to see validation comparisons that show a large improvement using BQSR and indel realigner, or improvements with indel realigner prior to BQSR and would be happy to revisit implementing these. Thanks again for the discussion.

**Comment by lpantano** [comment]
Hi @plsysu 

I will close this guessing you got it working. Let us know if you find more issues.

Thanks!
