### ISSUE TITLE
multisample joint calling

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1310]
Hi Bcbio group,

Thank you for providing a packing like this, which extremely helps researchers to do their down stream analysis. We are interested in  doing mutlisample joint calling for our germ line samples. I would like to know few things about running this. From the documentation it is not clear how would I proceed with this kind of template. 

1) Should I be using a sample.yaml file? If so how do I list my files? It looks like you can give not more than 2 files (_R1, _R2.fastq.) in this template. I see that I can mention the batch name in the metadata field.  But let suppose i want to run this setup against one sample(kid from the trio) vs to all other normal samples(5). How would I list all these in a single sample.yaml file?

2) If I had to use the metadata file (.csv). Is the parameter Phenotype required. As we run this for germ line samples there is no normal or tumor in these cases. How should be dealing with this? Also can I write the entire path for the .fastq file in the sample name field?

Should I be using bcbio_nextgen.py  ./bcbio.sh (the shell script has yaml files path) along with the metadata file? 

Thank you,

Diya

**Comment by chapmanb** [comment]
Diya;
For multisample joint calling you want to have a sample YAML file with multiple samples where you set the same batch names for all samples to run together:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/pipelines.html#population-calling

The templating functionality, as you mention, helps set this up in a standard way. The phenotype column is not required, and this is only an example. You only need to set the attributes you need:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#automated-sample-configuration

You want `samplename` to be only the base file name, not the full path, as we don't currently resolve that. Having unique base file names makes it easier to resolve pairs automatically from your list of file.

Hope this helps.

**Comment by DiyaVaka** [comment]
thank you. It worked.
