### ISSUE TITLE
Question about fragment lengths

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1312]
Hi all,

I am new to RNAseq analysis and I ran bcbio-nextgen on a set of 11 case and 11 control datasets. I used bcbio.rnaseq summarize to generate a report.

I noticed that I have zeros for the fragment.length.mean values in the table for almost all my samples (5 out of my 22 samples have a value ranging from 77 to 101).

Since I have paired-end reads, I expected there to be non-zero values. I am also a bit confused as to why some samples have values and most don't.

Do I need to be concerned about the zero fragment-lengths? If yes, how do I go about diagnosing this?

Thanks for any advice you may have!
~Lina

**Comment by lpantano** [comment]
Hi Lina,

I am looking into the code. It seems we check that internally. 

I would make sure that in the project-summary.yaml file the numbers are the same. Maybe the error is in the parsing?

If not, we get the first 1000 reads, and calculate the median. Can you take one of those samples with  0 and check the first reads of the BAM file to see if those reads has paired reads mapped?

In case, you see reads where their pairs are not mapped, you can look at the samtools stats inside the QC folders for each sample and check the first lines to see if you can note some difference in the stats related to paired reads.

let's see if that helps us to know what is going one.

cheers

**Comment by lfaller** [comment]
Hi Lorena,

Thanks for the quick reply!

I checked the project-summary.yaml file and the parsing looks ok (i.e. the values in that file correspond to the table I got in the summary report).

Then I went ahead and truncated the bam file for one of the "zero-fragment-length" samples to the first 1000 alignments and ran samtools flagstat on it:

```
1000 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 duplicates
1000 + 0 mapped (100.00%:-nan%)
1000 + 0 paired in sequencing
666 + 0 read1
334 + 0 read2
448 + 0 properly paired (44.80%:-nan%)
1000 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:-nan%)
421 + 0 with mate mapped to a different chr
4 + 0 with mate mapped to a different chr (mapQ>=5)
```

I also found this file: **final/13_D/qc/bamtools/bamtools_stats.txt**

```
cat bamtools_stats.txt

**********************************************
Stats for BAM file(s): 
**********************************************

Total reads:       79531382
Mapped reads:      79531382     (100%)
Forward strand:    39771278     (50.007%)
Reverse strand:    39760104     (49.993%)
Failed QC:         0    (0%)
Duplicates:        0    (0%)
Paired-end reads:  79531382     (100%)
'Proper-pairs':    59129662     (74.3476%)
Both pairs mapped: 79531382     (100%)
Read 1:            39765691
Read 2:            39765691
Singletons:        0    (0%)
Average insert size (absolute value): 287031
Median insert size (absolute value): 181
```

Are the average and/or median insert sizes related to the fragment lengths, or are these completely different values?

**Comment by lpantano** [comment]
It should be median. Maybe you have overlapped reads then. Can you check some of the reads manually to see if the two reads overlaps? maybe is that. i can check further the function.

**Comment by lfaller** [comment]
What's the best way to check if they overlap? (sorry, total n00b here :-P)

Can I determine this from samtools view output?

**Comment by lpantano** [comment]
yep!

just samtools view and you will see where the paired reads is mapped in the same line. I think column9 is the one we use.

**Comment by lfaller** [comment]
Ok! Here is some (truncated) samtools view output:

```
NS500401:21:HMNK2BGXX:1:12104:11946:14608       385     1       11695   1       75M     2       114358998       0       AGTGATTTGGGCTGGGGCCTGGCCATGTGTATTTTTTTAAATTTCCACTGATGTTTTTGCTGCATGGCCG
NS500401:21:HMNK2BGXX:1:21203:18510:19986       129     1       11869   50      75M     2       114359007       0       GTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAGCCCA
NS500401:21:HMNK2BGXX:2:11210:15503:19135       417     1       11891   3       75M     =       12033   216     CTTTGACCTCTTCTTTCTGTTCATGTGTATCTGCTGTCTCTTAGCCCAGACTTCCCGTGTCCTTTCCACTGGGCC
NS500401:21:HMNK2BGXX:4:23404:6980:4808 355     1       11900   3       75M     =       12030   204     CTTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGG     AAAAAE
NS500401:21:HMNK2BGXX:2:12105:16535:5164        419     1       11913   1       75M     =       12033   194     ATGTGTATTTGCTGTCTCTTAGCCCAGACTTCCCGTGTCCTTTCCACCGGGCCTTTGAGAGGTCACAGGGTCTTG
NS500401:21:HMNK2BGXX:1:23306:13958:14563       99      1       11981   3       75M     =       12041   135     GGTCTTGATGCTGTGGTCTTCATCTGCAGGTGTCTGACTTCCAGCAACTGCTGGCCTGTGCCAGGGTGCAAGCTG
NS500401:21:HMNK2BGXX:4:23404:6980:4808 403     1       12030   3       74M     =       11900   -204    GCTGGCCTGTGCCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGG      EEEEEE
NS500401:21:HMNK2BGXX:2:11210:15503:19135       337     1       12033   3       74M     =       11891   -216    GGCCTGTGCCAGGGTGGAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGAT
NS500401:21:HMNK2BGXX:2:12105:16535:5164        339     1       12033   1       74M     =       11913   -194    GGCCTGTGCCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGAT
NS500401:21:HMNK2BGXX:1:23306:13958:14563       147     1       12041   3       75M     =       11981   -135    CCAGGGTGCAAGCTGAGCACTGGAGTGGAGTTTCCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGGGCCATTG
NS500401:21:HMNK2BGXX:4:13410:7058:9240 385     1       12067   0       75M     =       21547051        21535054        GGAGTTTTCCTGTGGAGAGGAGCCATGCCTAGAGTGGGATGGGCCATTGTTCATCTTCTGGCCCCTGTTG
NS500401:21:HMNK2BGXX:4:21511:16851:11242       385     1       12173   0       55M385N19M      2       114357705       0       GAAAGATTGGAGGAAAGATGAGTGACAGCATCAACTTCTCTCACAACCTAGGCCAGTGTGTG
NS500401:21:HMNK2BGXX:4:21511:16851:11242       385     1       12173   0       55M385N19M      15      102517859       0       GAAAGATTGGAGGAAAGATGAGTGACAGCATCAACTTCTCTCACAACCTAGGCCAGTGTGTG
NS500401:21:HMNK2BGXX:4:21511:16851:11242       417     1       12173   0       55M385N19M      =       13237   1139    GAAAGATTGGAGGAAAGATGAGTGACAGCATCAACTTCTCTCACAACCTAGGCCAGTGTGTGGTGATGCC
NS500401:21:HMNK2BGXX:4:21511:16851:11242       417     1       12173   0       55M385N19M      16      62918   0       GAAAGATTGGAGGAAAGATGAGTGACAGCATCAACTTCTCTCACAACCTAGGCCAGTGTGTGGTGATGCC
NS500401:21:HMNK2BGXX:1:11206:13796:19415       99      1       12569   1       75M     =       12635   141     GTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGTCTCCCCCCAGGTGTGTGGTGATGCCAGGCATGCCCTTCCCC
NS500401:21:HMNK2BGXX:4:21503:9214:6192 65      1       12596   1       70M     12      92865   0       CTCCTGTCTCCCCCCAGGTGTGTGGTGATGCCAGGCATGCCCTTCCCCAGCATCAGGTCTCCAGAGCTGC  AAAAAEEEEEEEEE
NS500401:21:HMNK2BGXX:1:11206:13796:19415       147     1       12635   1       75M     =       12569   -141    CCCTTCCCCAGCATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCC
NS500401:21:HMNK2BGXX:2:22307:3091:9114 129     1       12647   0       73M     2       114357694       0       ATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCCAGTGTTGCAG
NS500401:21:HMNK2BGXX:2:22307:3091:9114 385     1       12647   0       73M     12      92291   0       ATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCCAGTGTTGCAG       AAAAAE
NS500401:21:HMNK2BGXX:2:22307:3091:9114 385     1       12647   0       73M     15      102517848       0       ATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCCAGTGTTGCAG
NS500401:21:HMNK2BGXX:2:22307:3091:9114 417     1       12647   0       73M     =       13250   676     ATCAGGTCTCCAGAGCTGCAGAAGACGACGGCCGACTTGGATCACACTCTTGTGAGTGTCCCCAGTGTTGCAG       AAAAAE
NS500401:21:HMNK2BGXX:4:23509:2921:1600 433     1       12828   3       72M     =       87491341        87478588        TGATCTTCCCTGTGATGTCATCTGGAGCCCTGCTGCTTGCGGTGGCCTATAAAGCCTCCTAGTCTGGCTC
NS500401:21:HMNK2BGXX:4:21511:16851:11242       337     1       13237   0       75M     =       12173   -1139   CCAAAGGGATTCTGCCAGCATAGTGCTCCTGGACCAGTGATACACCCGGCACCCTGTCCTGGACATGCTGTTGGC
```

Some of the values in column 9 are zeros. Is that ok?

**Comment by lpantano** [comment]
I see,

It seems that when the read is in another chromosome then the TLEN is set to 0 and then if we calculate the median, it goes down. In the previous report you can see that 50% of them are in different chromosome, at least for the first 1000. I would do `samtools stats BAM` of the whole bam to check if this is only on the top or not.

I think the solution would be to ignore the 0 when calculating. As well, when is spliced the value is super high, so not realistic, should be ignored as well.
 
Maybe something happened with those samples? the counts distribution are the same? or any other metric in the report that makes then be together?

I will change this in the code. So for now, you can ignore the ones that says 0 or super big, and look at the other values. It seems like 150-200

**Comment by lfaller** [comment]
Ok! Thanks for helping me out! I will ignore the fragment lengths for now.

I am just now going through the report and trying to understand every part of it ;-)

I think the counts distributions look pretty similar across the samples. Is this the figure you are thinking of?

![screen shot 2016-04-06 at 3 15 38 pm](https://cloud.githubusercontent.com/assets/7854149/14329693/bb6189e8-fc0a-11e5-8ce7-007d4a3f00d4.png)

What other plots could I look at to try and see if the samples look ok?

**Comment by lpantano** [comment]
As a side note, we are moving to another way to give basic QC metrics with multiqc, but this is happening in the devel version. ")

About the boxplot, yest, that's fine for raw counts before normalization.

**Comment by lfaller** [comment]
Ok cool, I'll definitely check out the new QC metrics once they are live :)

Thanks!!

**Comment by lpantano** [comment]
I modified bcbio.rnaseq to use the samtools value, hope this helps in the future.

**Comment by lfaller** [comment]
great, thanks!!
