### ISSUE TITLE
How does bcbio-nextgen resume an interrupted case?

### ISSUE THREAD

**Issue by sxv** [chapmanb/bcbio-nextgen#1313]
How does bcbio resume a case that was interrupted? I've noticed that sometimes a case will continue where it left off while other times it will jump back to the alignment step. Is there any documentation or code I can review to see the details of this logic?

Example: Let's say I've run a case all the way until the "upload samples" stage but then realize there was a typo in the config file's "upload/dir". If I re-write the config file and then run the case will it resume at the upload stage?

Example 2: Let's say I've completed variant calling with 3 out of 4 specified callers and the run is interrupted during the fourth. If I resume will the case continue at the beginning of the variant calling step or at the fourth caller?

Thanks.

**Comment by chapmanb** [comment]
sujay;
Thanks for the questions and sorry about the confusing restart behavior. bcbio should always pick up where you left off. It checks for the presence of the generated output files for each step and skips the step if they are present (and up to date with the inputs in some cases). For example, here is the logic for bwa alignment: 

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/bwa.py#L139

So in all your cases it should pick up where it left off.

When you saw it not have this behavior and re-do alignment did anything change in the configuration or file system? Were the expected outputs present? Happy to debug where it fails to restart at the current stage if you can provide more details.

Hope this helps.

**Comment by lpantano** [comment]
Closing this since it seems it was solved. Let us know if there is any issue.

thanks!
