### ISSUE TITLE
shutil.copytree fails with certain filesystems

### ISSUE THREAD

**Issue by sxv** [chapmanb/bcbio-nextgen#1314]
When specifying our network attached storage (NAS) device in the bcbio config file as the upload location, the upload step partially works but then fails (Errno 1: Operation not permitted). It appears that shutil's copytree function [is known to fail](http://stackoverflow.com/questions/10539724/problems-with-shutil-copytree) with some filesystems.

If a fix for this issue is worthy of implementing, I can submit a pull request to use shutil.copyfile or a more fault-tolerant "copytree". Please advise, thanks.

**Comment by roryk** [comment]
Hi Sujay,

Sorry for the troubles and thanks for a) figuring out the issue and b) offering to fix it. A pull request would be great!

**Comment by sxv** [comment]
My suggestion would be to replace these lines
```
if os.path.exists(out_dir):
    shutil.rmtree(out_dir)
shutil.copytree(finfo["path"], out_dir)
and
`shutil.copy(finfo["path"], out_file)`
with a system call (using os.subprocess) of bash `cp` command. Any reason not to do this or should I pull request?

**Comment by sxv** [comment]
OK, I've narrowed this down to a permissions issue on the NAS storage device which prevents my client user from modifying file properties (access time, modify time, etc.) after transferring them to the NAS. Since I'm able to overcome this by running as root, I believe I will eventually solve this by adjusting my client / server permissions. Thanks.

**Comment by sxv** [comment]
For future troubleshooters:

The problem was that os.copytree first copies files and directories with os.copy2 and then calls os.copystat which fails to update file access and modified time via os.utime, due to conflicting UIDs/GIDs on the client and server. What worked for me was adding the `noperm` option in /etc/fstab to mount the CIFS NAS drive.

**Comment by chapmanb** [comment]
Thanks much for following up and for the fix. We're also starting to move away from using directories with copytree to having explicit specification of files to copy, so hopefully longer term we can remove this requirement. Glad you found a solution that works.
