### ISSUE TITLE
Problem with Samtools and coverage computations 

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1316]
I am running `bcbio.variation.coverage` computations on a WGS sample with a region BED file that contains all human genes. My intention is to get the coverage report for my priority regions (which happen to be all genes) with annotation of difficult regions. In the `priority_coverage` function of that module, in line `311`, `samtools` is called with the coordinates of all regions in the command line call. That fails with a broken pipe error from samtools, probably because the commend line gets too long (it seems to contain all regions of at least one chromosome). `samtools` also allows specifying these regions by a BED file using the `-L` command. Would that be a more robust option?

**Comment by schelhorn** [comment]
Other options would be to directly use bedtools for selecting the regions by specifying the BAM as input (if bedtools uses the BAM index, that is), or continue specifying the regions as command line parameters but going through the regions in batches and call samtools for each batch separately, concatenating the outputs later on.

**Comment by schelhorn** [comment]
Sorry, now that I'm looking at the function I see that you already are batching the regions. I will investigate wether smaller batches solve my issue.

**Comment by schelhorn** [comment]
Got it, it's the changed bedtools syntax. Bcbio installed bedtools 2.24.0, and there the syntax should be `-b BEDFILE -abam stdin` instead of `-a BEDFILE -b -`. In the bedtools documentation it says that the syntax changed from 2.24.0 on.

**Comment by schelhorn** [comment]
So I believe that the bcbio code would have to be fixed here.

**Comment by schelhorn** [comment]
Um, I might be wrong again. It seems as if the bcbio syntax is semantically correct after all, but somehow it doesn't work in my installation. I will investigate.

**Comment by schelhorn** [comment]
Alright, found it. Some of the gene models I got from UCSC where really large, which somehow got bedtools to choke. When I removed them everything seems to run great again. Sorry for the confusion. The `-sorted` options could still be worthwhile, however, since it seems to address the sorting of the BAM file, not the BED file as I wrongly assumed before. Since that is always sorted it may make sense to set it in order to save RAM.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks so much for all the debugging on this. I added the `-sorted` option here to improve memory usage going forward. Let us know if there's anything else we can do to help with this case and hope you're getting useful coverage reports now.
