### ISSUE TITLE
No regular file! (wget -N -c )

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1317]
I ran this command.
`$ bcbio_nextgen.py upgrade --data --aligners rtg
`

> wget -N -c http://downloads.sourceforge.net/project/adamajava/qsignature.tar.bz2
> 
>   Content-Length: 52328
>   X-Content-Type-Options: nosniff
> Length: 52328 (51K) [text/html]
> Saving to: `download?use_mirror=ufpr.html'
> 
> 100%[======================================================================================================================================================================================================================================>] 52,328      73.4K/s   in 0.7s
> 
> Last-modified header missing -- time-stamps turned off.
> 2016-04-07 18:23:40 (73.4 KB/s) - `download?use_mirror=ufpr.html' saved [52328/52328]
> 
> tar (child): qsignature.tar.bz2: Cannot open: No such file or directory
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> Traceback (most recent call last):
>   File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 4, in <module>
>     __import__('pkg_resources').run_script('bcbio-nextgen==0.9.7', 'bcbio_nextgen.py')
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 719, in run_script
> 
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/setuptools-20.6.7-py2.7.egg/pkg_resources/__init__.py", line 1483, in run_script
> 
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio_nextgen-0.9.7-py2.7.egg-info/scripts/bcbio_nextgen.py", line 207, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 91, in upgrade_bcbio
>     upgrade_bcbio_data(args, REMOTES)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 267, in upgrade_bcbio_data
>     cbl_deploy.deploy(s)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
>     configure_instance(options, actions)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
>     setup_biodata(options)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
>     install_proc(options["genomes"], ["ggd", "s3", "raw"])
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 345, in install_data
>     _prep_genomes(env, genomes, genome_indexes, ready_approaches)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 474, in _prep_genomes
>     retrieve_fn(env, manager, gid, idx)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 796, in _install_with_ggd
>     ggd.install_recipe(env.cwd, recipe_file)
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
>     recipe["recipe"]["full"]["recipe_type"])
>   File "/BiO/BioPeople/brandon/test_bcbio/smrna/input/mirqc_bcbio/work/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
>     subprocess.check_output(["bash", run_file])
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['bash', '/BiO/BioTools/bcbio/data/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 2
> 

so, I thinks this comamnd will not make the "qsignature.tar.bz2"  in this shell file. (/BiO/BioTools/bcbio/data/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh)

`$ wget -N -c http://downloads.sourceforge.net/project/adamajava/qsignature.tar.bz2
`
please check this issue.

**Comment by chapmanb** [comment]
Hyumin;
Sorry about the issue. I can't replicate this problem now so it might have been a temporary problem with sourceforge downloads. If you remove the temporary directory and retry the run:
```
rm -rf /BiO/BioTools/bcbio/data/genomes/Hsapiens/GRCh37/txtmp/
bcbio_nextgen.py upgrade --data
```
Hopefully it'll work cleanly for you. Please re-open the issue if you have any problems with a retry.
