### ISSUE TITLE
Question about mapping rates

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1319]
Hi all,

I am using bcbio-nextgen to look at a set of 11 case and 11 control datasets. I used bcbio.rnaseq summarize to generate a report.

I noticed that I have a mapping rate of 1.0 for all samples. I heard this might happen sometimes if the sequences are pre-filtered, but in my case, the samples came straight off the NextSeq and I have not done any filtering other than what is included with bcbio-nextgen.

I checked the project-summary.yaml file and the mapping rates are all 1.0 (so it isn't a problem with the parsing in the report).

I aligned against GRCh37 and I am worried that a mapping rate of 1.0 is maybe a bit too good to be true.

Thanks for any advice you may have!
~Lina

**Comment by lpantano** [comment]
You can check inside the QC folder in each sample. The bamtools or samtools. There you should see the real % of mapped reads. I am assuming you used STAR to align? I don’t know if using tophat can do that the tool filter the BAM file it self.

let me know what you find.

**Comment by lfaller** [comment]
I ran TopHat but I did find the following files: **<SAMPLE>/qc/bamtools/bamtools_stats.txt**

```
grep "Mapped reads" */qc/bamtools/*txt
11_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      84968618 (100%)
13_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      79531382 (100%)
15_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      95201426 (100%)
16_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      26780684 (100%)
17_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      26216756 (100%)
18_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      41080482 (100%)
19_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      43021292 (100%)
1_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      23927588  (100%)
20_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      94779590 (100%)
2_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      21883926  (100%)
3_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      23081398  (100%)
45_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      200700722        (100%)
46_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      25897588 (100%)
47_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      121783456        (100%)
48_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      100465004        (100%)
4_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      18245428  (100%)
52_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      26499658 (100%)
53_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      41688464 (100%)
54_D/qc/bamtools/bamtools_stats.txt:Mapped reads:      102836570        (100%)
5_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      28280324  (100%)
7_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      121712320 (100%)
9_H/qc/bamtools/bamtools_stats.txt:Mapped reads:      12601538  (100%)
```

Do you think it's real?

**Comment by lpantano** [comment]
it could be the output of tophat is having only the mapped reads. I don’t use tophat, so don’t know if maybe inside log-bcbio-debug.txt have the info tophat print while mapping, and then maybe you have better information?

I am almost sure, is that. You can run manually the FASTQC of one sample using the FASTQ files. bcbio uses the BAM file, so won’t be useful. Then you can compare numbers.

**Comment by lfaller** [comment]
So the tophat run produces a file called **align_summary.txt**:

``` cat align_summary.txt 
Left reads:
          Input     :  44022318
           Mapped   :  39094351 (88.8% of input)
            of these:   1330877 ( 3.4%) have multiple alignments (26454 have >20)
Right reads:
          Input     :  44022318
           Mapped   :  39094351 (88.8% of input)
            of these:   1330877 ( 3.4%) have multiple alignments (26454 have >20)
88.8% overall read mapping rate.

Aligned pairs:  39094351
     of these:   1330877 ( 3.4%) have multiple alignments
                 1137562 ( 2.9%) are discordant alignments
86.2% concordant pair alignment rate.
```

I assume the "concordant pair alignment rate" is the same as the mapping rate? Then that's probably more accurate. I will look at these values instead of the mapping rate as reported in the project-summary.yaml file.


By the way, since you mentioned you don't use Tophat, do you recommend the STAR aligner over TopHat?

Thanks!!

**Comment by lpantano** [comment]
nice!

yep, that value is ok to get the right idea.

We use STAR, because is faster, and get better alignments, and we can avoid trimming. The downside is that need 40G of memory RAM.

**Comment by lfaller** [comment]
Ok cool, thanks!

40G of RAM is a downside right now... :-P I'll have to look to see if I can get more RAM.

Thanks!!

**Comment by lpantano** [comment]
if you have further question, feel free to ask again.

cheers
