### ISSUE TITLE
Pipeline tries to index fastq.gz files with grabix and likely hangs

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1325]
I'm still not sure if it's just taking a long time, but these fastq files I am using are *not* bgzipped. I think it's just https://github.com/arq5x/grabix/issues/17 instead (fixed, but no release with a fix).

I'll investigate further to check if it's a real issue or not.

**Comment by lbeltrame** [comment]
*All* indices have so far 0 bytes in length (max 2), with last modification more than 1 hour ago, so I'm thinking it's that bug.

**Comment by lbeltrame** [comment]
The "grabix index" run on these WES files (~5G each) has been running (single core) for about 2 hours or so on my cluster nodes. Is this expected? If so, probably having a way to turn it off would help as it'd be a large performance hit.

**Comment by lbeltrame** [comment]
I hacked the align prep functions to return `False` and force the compression with `pbgzip` to determine if the situation changes (treating files as bgzip even if they aren't) or not (simply slow).

**Comment by lbeltrame** [comment]
Update: if I make https://github.com/chapmanb/bcbio-nextgen/blob/86c28ff96e0fabac1cc0bc9b73e2e2c88f6696d8/bcbio/ngsalign/alignprep.py#L220 return `False` as previously stated, the files are correctly bgzipped and grabix completes in a few minutes. 

Currently it only checks the extension, and with the defaults, it will always return `True` (at least on my system), causing grabix to choke on the fastq files afterwards. Is there absolutely no magic number or anything else that could be used to check if a gzipped file is bgzipped?

**Comment by chapmanb** [comment]
Luca;
Sorry about the problems and thank you for the report and detailed debugging. This was a problem with the latest development version from yesterday. We're moving to set `align_split_size` automatically so were more aggressively indexing to support then, so should have converted these to bgzip first, as you identified. I pushed a fix to resolve these in the latest development -- please let me know if you run into any other problems at all and thanks again.
