### ISSUE TITLE
Can WGrS, Exome and Amplicon data be variant called together? Large difference in callable regions + number variants on including amplicon samples. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1326]
Hi, 

Is it possible to variant call sequencing data generated from different methods together using bcbio? I am using the freebayes workflow. 
For instance WGrS + Exome + amplicon sequencing data?

I get very different numbers of callable regions and variants after variant calling an amplicon sample together with WGrS samples.  Compared to just variant calling the WGrS samples. 

This makes me kind of worry that the bcbio callable regions functionality excludes regions for variant calling (for all samples) based on just 1 sample having no data in a region. 

Which you of course expect a lot lot with Amplicon and Exome samples and for a smaller part even between WGrS samples. 

I just loaded the regions/{project}-analysis_blocks.bed  in IGV and indeed halve of the regions missing for the amplicon sample haven't been variant called for the total set of samples. All of the WGrS samples have data in the vast majority of these regions. 

Is it intended that the callable regions functionality excludes regions where just a single sample has no data?

Or is this issue specific for the combination of WGrS + amplicon data?  
Is there a way to exclude the amplicon / exome  samples from the calculation of the callable regions? 

Thank you.

**Comment by NeillGibson** [comment]
The calculation of the callable regions seems also to be sample order dependent. 
The issue does not seem to happen if a WGrS sample is the first sample in the YAML file. 
Having an amplicon sample specified later in the YAML file does not seems to have the an effect on the callable regions.

**Comment by chapmanb** [comment]
Neill;
Thanks for the detailed report and sorry for the problems. That is unexpected and I'd like to fix whatever is going on. Callable calculations should be independent unless the samples are being called together in the sample `metadata -> batch`. Are you trying to call these independently, or as part of a single batch? If so, calling them separately should have the callable regions calculations happen independently. If not, would you be able to post your sample YAML and I'll try to reproduce and debug. Thanks much.

**Comment by NeillGibson** [comment]
Hi Brad, 

I have set the batch name to the same value for all samples. The main reason for putting all the samples of different types in the same batch is to get a square genotype matrix over all samples, even if the Exome and amplicon samples will be missing for many / most positions.

Splitting the samples to multiple batches would create an incomplete genotype matrix (after merging)?
Therefore I rather include all samples in the same batch  (= population). 

I hope that having the Exome / amplicon samples behind the WGrS samples in the YAML is already a good work around. I should be able to test this later this week. 

But it would be nice to have a more robust solution that does not depend on sample order.  

I still don't understand why the order of the samples matters. I was hoping the callable regions are calculated per sample and then the callable regions of the batch/population is the bedtools merge of  all of the per sample callable regions.
http://bedtools.readthedocs.org/en/latest/content/tools/merge.html

Minus maybe again the excessive depth regions. This should be robust to starting with the callable regions of an amplicon sample.


If still use full I  think I can share the YAML file. I'll look it up tomorrow.

**Comment by chapmanb** [comment]
Neill;
Thanks so much for the additional details. This helps a lot and is definitely worth supporting. I dug into the code and believe I've isolated the source of the problem -- we were using the `-u` flag when collapsing the possible splitting regions. Each of the samples has callability calculated independently but then in the step where we combine into a single set of regions to work with for the batch, the bedtools intersect command created an implicit order dependence by using `-u`. 

If you update to the latest development version, then remove the generated collapsed regions for your batch (`rm -rf regions`) and re-run, it should hopefully have better behavior.

Please let us know if this does not fix the problem and happy to dig further. Thanks again for identifying this.

**Comment by NeillGibson** [comment]
Thank you Brad for fixing the issue. I'll see if it now works and will report back if it doesn't.

**Comment by NeillGibson** [comment]
Hi @chapmanb .  The commit https://github.com/chapmanb/bcbio-nextgen/commit/3023f2d0ee6369613e6c6f1641f70d57671c4814 seems to have fixed the calculation of the callable regions. 

But the Freebayes raw-regions.bed (and raw-regions-glimit.bed)  now only include the amplicon regions for variant calling. This is the bed file that Freebayes actually uses. 

See the attached IGV screenshot of the related BAM, BED and VCF file. 

So somewhere downstream of calculating the callable regions  a bedtools (like) operation still goes wrong when trying to variant call WGS + amplicon samples. 

In the command log file I  can not find how the `raw-regions.bed` file is created. 
Only the command that uses this file to create the `raw-regions-glimit.bed` file. 

```
grep PROJECT-123_minimal_WGS_AMPLICON-Chr_01_0_902691-ra
![callable_regions_ok_freebayes_call_region_only_amplicon_igv](https://cloud.githubusercontent.com/assets/15608993/15249366/7432804a-191f-11e6-8590-ad646d190aa6.png)
w-regions.bed log/bcbio-nextgen-commands.log

[2016-05-11T15:11Z] node20: bedtools subtract -nonamecheck -a /data/Projects/species/PROJECT-123/test_single_WGrS_single_AMPLICON/PROJECT-123_minimal_WGS_AMPLICON/work/freebayes/Chr_01/PROJECT-123_minimal_WGS_AMPLICON-Chr_01_0_902691-raw-regions.bed -b /data/Projects/species/PROJECT-123/test_single_WGrS_single_AMPLICON/PROJECT-123_minimal_WGS_AMPLICON/work/freebayes/Chr_01/tx/tmpxfRGZW/PROJECT-123_minimal_WGS_AMPLICON-Chr_01_0_902691-raw-regions-glimit-all-sort.bed > /data/Projects/species/PROJECT-123/test_single_WGrS_single_AMPLICON/PROJECT-123_minimal_WGS_AMPLICON/work/freebayes/Chr_01/tx/tmpxfRGZW/PROJECT-123_minimal_WGS_AMPLICON-Chr_01_0_902691-raw-regions-glimit.bed
```

There are also no other bed files named  `*01_0_902691* `  in the work of final directory. 

Do you maybe know  which step downstream of calculating the callable regions might be causing this issue?

Or how to get the command  (and bed files) that are used to create the the `raw-regions.bed` file(s)?
`PROJECT-123_minimal_WGS_AMPLICON-Chr_01_0_902691-raw-regions.bed`

Thank you!

**Comment by NeillGibson** [comment]
![callable_regions_ok_freebayes_call_region_only_amplicon_igv](https://cloud.githubusercontent.com/assets/15608993/15249397/9dd8e3e4-191f-11e6-8bf8-cf3c6be8f1e8.png)

**Comment by chapmanb** [comment]
Neill;
Sorry about the continued problems with these samples and thanks for all the details. Reading the code, it looks like we are implicitly assuming that samples have relatively even coverage (or pre-defined `variant_regions`) and pick the first to call variants on. This causes confusing behavior for batches like this where the coverage is very different between samples.

I changed the code to explicitly pick the sample with the most coverage, using this as the baseline for defining callable regions. This should identify the WGS sample from your group and process on that region instead of the first in a batch.

Could you test the latest development (`bcbio_nextgen.py upgrade -u development`) on the samples? You should be able to upgrade, remove the problematic variant calls, and then re-run only on variant calling since the upstream steps will not change. I hope this will give you the right behavior.

Thanks again for all the work and patience on this and let us know if you run into anything else at all.

**Comment by NeillGibson** [comment]
Hi Brad. Thank you very much for looking at the issue and upgrading / improving  the code.  
I will try to test the new code this weekend or early next week and report back the results.

**Comment by NeillGibson** [comment]
Hi Brad.

It took a bit longer to check this but I am very happy that I can confirm that I now get variants and genotypes genome wide.

Processing WGS + Exome + amplicon samples now seems to work :)

**Comment by chapmanb** [comment]
Brilliant -- thanks so much for following up and glad it's working. Thanks for all the patience and back and forth testing this.
