### ISSUE TITLE
How to disable GATK call home feature in bcbio

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1327]
Hi!
I've installed bcbio and gatk and now I'm trying to run example 'exome with validation against reference materials' pipeline. On our cluster computing nodes don't have internet connection,
so GATK fails to call home and exits. To avoid this, I usually use -et NO_ET -K file.key parameters for GATK. How to pass this parameters to GATK in bcbio? I've tried via jvm_opts for gatk in bcbio_system.yaml, but without success.
Thanks, Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for trying out bcbio. There is a `keyfile` argument under `gatk` in the `resources` section where you can specify this and we'll pass it to GATK:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html?highlight=keyfile#resources

Let us know if you run into any problems at all. Thanks again.
