### ISSUE TITLE
LUMPY deduplication

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1330]
I'm testing Lumpy for sv calling using data from an amplicon-based panel (truesight). I notice, however, that a deduplication step is performed using sambamba before Lumpy is run, despite the fact that `mark_duplicates: false` is set in the config file. Is this correct? 

I wish to test if Lumpy can help identify certain somatic indels.

cheers,
Pär

**Comment by chapmanb** [comment]
Pär;
The lumpy implementation is pretty dependent on running samblaster to extract split and discordant reads (https://github.com/GregoryFaust/samblaster) which is likely what you're seeing. I honestly have no intuition for how lumpy would do on amplicon data but it should still run cleanly for you with this step to at least give calls. Are you running into errors, or just worried about the samblaster step in lumpy preparation? Thanks for the discussion.

**Comment by mjafin** [comment]
There will be virtually no data left after marking duplicates in (PCR?) amplicon panel data so I wouldn't be surprised if there is no output either

**Comment by parlar** [comment]
Fast responses as always! 

In just noticed the output below. Given the long time lumpy is taking to process the data, however, perhaps it does not discard the "duplicated" reads? I was worried the deduplication process might cause it to fail since I'm using an amplicon-based panel, without having finished a run ...

Thanks!

```
[2016-04-13T07:17Z] samblaster: Version 0.1.22
[2016-04-13T07:17Z] samblaster: Inputting from stdin
[2016-04-13T07:17Z] samblaster: Outputting to stdout
[2016-04-13T07:17Z] samblaster: Opening /dev/fd/62 for write.
[2016-04-13T07:17Z] samblaster: Opening /dev/fd/63 for write.
[2016-04-13T07:18Z] [bam_sort_core] merging from 3 files...
[2016-04-13T07:18Z] samblaster: Loaded 93 header sequence entries.
[2016-04-13T07:18Z] samblaster: Output 7863 discordant read pairs to /dev/fd/62
[2016-04-13T07:18Z] samblaster: Output 14920 split reads to /dev/fd/63
[2016-04-13T07:18Z] samblaster: Marked 1790272 of 1801500 (99.38%) read ids as duplicates using 1980k memory in 5.236S CPU seconds and 1M30S(90S) wall time.
```

**Comment by chapmanb** [comment]
Pär;
Thanks for the additional details. I'm not totally sure how lumpy deals with duplicated data, since as Miika guess, the majority of this are duplicates. The calling is primarily based on split and discordant reads, but lumpy does calculate baselines of paired end metrics from the standard data. It might be worth asking @ryanlayer and @arq5x if there is any hope of getting reasonable calls from amplicon data based on the assumptions in lumpy. Happy to try and tweak to handle this case if there is a way to do so.

**Comment by arq5x** [comment]
If the amplicon contains the SV breakpoint there is hope of capturing it with split reads. Support from discordant pairs is suspect simply because of the skewed insert size distribution from which the decision of discordant/concordant is made.

**Comment by lpantano** [comment]
Hi all,

I will close this because it seems the discussion is staled. 

Thanks!
