### ISSUE TITLE
clean_chipseq_alignment gets the core configuration wrong

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1331]
cc @LMannarino

This is from an install with the latest stable version:

```
[2016-04-13T09:15Z] Timing: disambiguation
[2016-04-13T09:15Z] multiprocessing: clean_chipseq_alignment
[2016-04-13T09:15Z] Resource requests: macs2; memory: 1.00; cores: 1
[2016-04-13T09:15Z] Configuring 0 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
````

In turn, this leads to either errors with multiprocessing (Parallel complains that it gets passed a number of jobs = 0) or with the cluster (0 engines running).

For the record, the machine where this was run  has 32G of memory and 8 cores, and it had no significant load or memory usage.

**Comment by lbeltrame** [comment]
From what I've seen, the problem lies in https://github.com/chapmanb/bcbio-nextgen/blob/c6f577d198e62a8d37cfac518d955e28393446b3/bcbio/chipseq/peaks.py#L70

In this run, we have 4 samples (2 input, 2 chip):

1. to_process starts equal to 1
2. 2 more samples are added -> to_process is equal to 3
3. 3 samples over a total samples of 4 -> 0.75 -> 0 cores

It looks like some calculations are wrong here: shouldn't it be 

```python
return total_samples / to_process
```

**Comment by lbeltrame** [comment]
@lpantano If my explanation is correct, I can make a PR to fix it.

**Comment by lpantano** [comment]
hi, sorry about this. i recall that problem but now is working for me with 4 samples as u have.

the number should be lower that 1 because it is the multiplier for the number of hobs. Since we need to configure less jobs than samples, because only some are Chip, then need to multiply the number of sample by a number lower than 1. I will check the code again and do more test and see what happens. I don't know if you can test devel version here? 

sorry about that, is annoying.

sent not from my computer

**Comment by lbeltrame** [comment]
In data mercoled� 13 aprile 2016 05:50:25 CEST, Lorena Pantano ha scritto:

> the number should be lower that 1 because it is the multiplier for the
> number of hobs. Since we need to configure less jobs than samples, because

The problem may be that the number is an integer in 0.9.7, hence Python does 
floor division and you get an integer (0).

> lower than 1. I will check the code again and do more test and see what
> happens. I don't know if you can test devel version here?

I can't quite upgrade that system, unfortunately. I'll check the code in the 
released and devel version.

**Comment by lbeltrame** [comment]
It looks like we were caught up in #1296 and the pipeline wasn't fully up to date. Sorry for the noise!

**Comment by lpantano** [comment]
Glad it worked. thanks for checking. Always good to have people running pipelines.
