### ISSUE TITLE
Improvement of cancer workflow in bcbio (GATK behavior)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1336]
Do you have the planing of the improvement of cancer workflow in bcbio? 

I reviewing the GATK co-realignment step.

please check this document.

https://www.broadinstitute.org/gatk/events/slides/1506/GATKwr8-S-1-Intro_to_somatic_variant_discovery.pdf

 
![2016-04-14 15 43 44](https://cloud.githubusercontent.com/assets/4966343/14519197/4be27b00-0258-11e6-80ae-7a7bf04ded31.png)

**Comment by ohofmann** [comment]
You mean the co-realignment? I haven't seen any test data that shows a large improvement, and variant callers such as VarDict perform it during the SNP/InDel calling step. We will be looking into contamination filters once it's clear what approach ICGC/PCAWG settles on and code becomes available.

**Comment by hmkim** [comment]
Yes, I mean the co-realignment.  I also haven't seen any document about the co-realignment, except for attached link by me.

Thanks for your reply!
