### ISSUE TITLE
dependency on scikit-learn, but not using it?

### ISSUE THREAD

**Issue by amueller** [chapmanb/bcbio-nextgen#1337]
According to your requirements.txt, you're depending on scikit-learn. But I couldn't find any use of it in the package (or rather github couldn't).

**Comment by chapmanb** [comment]
Andreas;
Thanks much for the heads up. We were using scikit-learn previously for the WHAM structural variant caller but that dependency has been removed so you're right that we can get rid of this. We also now use conda for requirements so I cleaned up the requirements.txt (which is only there for updating from old instances) to avoid confusion and pushed a new bcbio conda without scikit. Thanks again for spotting this.
