### ISSUE TITLE
AssertionErrror multisample joint calling

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1340]
Hi Brad and group,

Recently we did a run bcbio on  multisample joint calling and its failing. When we do single sample joint calling it works. Attached are the sample yaml and bcbio error files. Its complaining about coordinates, but I am not sure how did it work for single sample.

Attached are the bcbio err file and sample file.

Thanks,

[bcbio.stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/221486/bcbio.stderr.txt)
[sample.yaml.txt](https://github.com/chapmanb/bcbio-nextgen/files/221487/sample.yaml.txt)

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. I believe the parallelization code is getting a bit confused because you're using a mix of joint calls (`gatk-haplotype` and `platypus`) and pooled calls (`gatk`):
```
     variantcaller: [gatk,gatk-haplotype,platypus]
      jointcaller: [gatk-haplotype-joint, platypus-joint]
```
Practically, you don't need joint calling here. It's typically used only when memory requirements for pooled calling are too high because of a large number of samples (250+). I'd suggest changing to:
```
     variantcaller: [gatk,gatk-haplotype,platypus]
```
and removing the joint caller line, and things should work cleanly. It will call your three samples together based on the shared `batch` name in the `metadata` section.

Hope this helps get things running. If you run into any issues please do re-open and we can investigate more.

**Comment by DiyaVaka** [comment]
The reason we wanted to do joint calling is because we are not 100% sure that some of the rare calls on the proband can be called. So we wan to use 48 normal samples so that we can catch these rare variants. 

How can we achieve our goal without using joint calling?

**Comment by chapmanb** [comment]
Having the same metadata/batch for the samples will ensure they are called together and take advantage of having multiple samples. Batches of 48 samples can be called together without large memory requirements. Joint calling is only needed with bigger sample sizes and is a different approach (call samples individually, then combine together into one call set):

http://bcbio-nextgen.readthedocs.org/en/latest/contents/pipelines.html#population-calling

Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

I started our 2nd joint calling test run with 56 control samples. I am getting an error in prep_data method of multi.py Attached is the bcbio.stderr for it.  I can send you the yaml file too if that helps.

Thanks.
[bcbio.stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/399992/bcbio.stderr.txt)

**Comment by chapmanb** [comment]
Diya;
This error looks like you have `jointcaller` set in your configuration but not `variantcaller`. Is that possible? If so, setting both (http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#population-calling) and re-running in place should hopefully get things working.

**Comment by DiyaVaka** [comment]
Hi Brad,

As we use the control samples for every flowcell is there a way that we can run these control samples only once and store the data in temp location and just run the new samples every time. Can we have a set up in yaml where we can list bam files inplace of fastq's and have bwa to be false for those?

**Comment by chapmanb** [comment]
Diya;
Thanks for the question. I'm a bit confused as what you mean. If you're running controls on flowcells don't you want to align and process those reads as well? If you don't want to process them you can either leave them off the YAML or turn alignment off. I'm not sure I understand why you'd want to sub in BAMs (from previous runs?) for the controls.

Practically any sort of specification you want is possible since this is a bit outside of bcbio and up to you as long as you give it the right YAML. Hope this helps.

**Comment by DiyaVaka** [comment]
Brad,

Sorry for not writing it in detail. We sequence control samples only once and sequence clinical samples every week. We want to run controls + clinical samples for every set. So we dont want to use resources to rerun the same control everytime in the bcbio pipeline, instead I want to somehow turn them off after initial run and use its alignment results for the next set so that I can just use joint calling on controls+clinical samples on every new set.

please let me know if its not clear.

**Comment by chapmanb** [comment]
Diya;
Thanks for the explanation. You can do this in bcbio by passing the BAM file of the control as `files` and setting `aligner: false` in the `algorithm` configuration:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

Hope that provides what you need to do this. If you want to use a single template for the whole thing you can adjust the parameter for just the control in the template CSV to set aligner as false for those control samples. Hope this helps.

**Comment by DiyaVaka** [comment]
Awesome brad. Great that it takes bam files as input and we can give alignment to be false for those. Will try it and let you know if any issue arises

**Comment by DiyaVaka** [comment]
Hi Brad,

Recently we are experiencing time lags for gatk-haplotype. It took almost 2 weeks to run gatk-haplotype on 56 control samples. For joint calling can we give the gvcf's from control files so that we can run it only on our experiment samples and save time there

**Comment by chapmanb** [comment]
Diya;
We don't have a way in bcbio to take in pre-created gVCFs and feed them into joint calling. It's a great idea to work on we only haven't had the opportunity to implement it. Sorry to not have anything you can use right now.

**Comment by DiyaVaka** [comment]
thank you..

**Comment by DiyaVaka** [comment]
Hi Brad,

We have a researcher who has 204 samples run at our core facility and she is interested in joint calling. They anticipate more samples in the near future and think running joint calling in n mode makes more sense. I would like to know how much resources does this kind of set up need and also can you give a rough estimate of how long this run can take.  We will be using only gatk and gatk-haplotype. Attached is my test yaml for this project. 
[sample.yaml.txt](https://github.com/chapmanb/bcbio-nextgen/files/1140050/sample.yaml.txt)

**Comment by chapmanb** [comment]
Diya;
Thanks for the question. Below is the configuration I'd suggest for doing gVCF based calling. There is no reason to use GATK UnifiedGenotyper as it's not nearly as good as HaplotypeCaller. You can also skip realignment with HaplotypeCaller and can generally skip recalibration unless you have read quality issues:
```
    algorithm:
      aligner: bwa
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      tools_on: [qualimap_full]
      coverage: /mnt/speed/qc/sequencing/biodata/capture_regions/ExV3_151111_HG19_HIVresevoirV1_EZ_HX1_primary_targets_nochr.bed
      coverage_interval: regional
      coverage_depth: high
      variant_regions: /mnt/speed/qc/sequencing/biodata/capture_regions/ExV3_151111_HG19_HIVresevoirV1_EZ_HX1_primary_targets_nochr.bed
      clinical_reporting: true
```
It's a bit hard to estimate read times but exomes are normally not excessively long. Hope this helps.

**Comment by DiyaVaka** [comment]
Thank you Brad. Can you please tell the pros and cons of N calling vs N+1 calling. We are interested in doing joint calling for 202 clinical cases and would like to know which procedure you think should we proceed with.

**Comment by chapmanb** [comment]
Diya;
Generally we prefer joint calling (N+1 calling) since it gives more flexibility than pooled calling and scales well. Our validation work showed that both work well:

http://bcb.io/2014/10/07/joint-calling/

For 202 samples you're starting to get into larger size for batch (N) calling, so I'd use a joint calling approach. Hope this helps.

**Comment by DiyaVaka** [comment]
Thank you. We are running this model for the first time. How could we make sure what ever we do is actually correct? Are there any checks at each point to ensure this?

**Comment by chapmanb** [comment]
Diya -- I'm not sure what to suggest other than sanity checking outputs. bcbio tries to do the right thing and warn you with errors if something is wrong in general. Hopefully things work out cleanly for you.

**Comment by DiyaVaka** [comment]
Hi Brad,

Our joint calling stuff is complete. It stopped at qc stage but as we have already qc complete for single sample calling we did not continue the run.

There is gatk-haplotype folder, gatk-haplotype-joint folder which will have the vcf files. Will this method also produce any single vcf file which has all the samples in it?

**Comment by chapmanb** [comment]
Diya -- the gatk-haplotype-joint folder should have the joint called multisample VCF (`joint/gatk-haplotype-joint/batchname/batchname-joint.vcf.gz`). If you can figure out he QC errors the final outputs should also have this file along with the individual gVCF files from each sample. Hope this helps.

**Comment by DiyaVaka** [comment]
thanks for the quick response. based on the template you mentioned above I did not use batch. Without this we won't have the batch file? also we used n+1 model. Will this change things?

**Comment by chapmanb** [comment]
Diya -- sorry for any confusion. You do need the samples specified in the same batch to get a multiple sample VCF output. The batch parameter is how bcbio knows which samples to analyze together. Without this you'll get single sample gVCF and VCF outputs.

If you don't want most of the QC in bcbio you can do:
```
qc: [samtools]
```
which will only run the more minimal samtools QC step. Hope this helps for getting your data analyzed.

**Comment by DiyaVaka** [comment]
Thank you Brad. Just to understand better, running it in Batch mode performs calls differently than the single gvcfs? Or batch will just concatenate all the gvcfs into one big file?

**Comment by chapmanb** [comment]
That's right, in batch mode GenotypeGVCFs gets called with all samples in the batch simultaneously so can take advantage of information from other samples -- so this is really joint calling. Without a batch it's calling only on the individual samples so is essentially single sample calling with a gVCF intermediate. How much the joint calling helps versus single sample is not an easy thing to answer generally and will depend on the depth; joint calling helps more the lower the depth is. Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

we spent one month for running the above setup on 200+ samples. I did not provide the Batch mode information. When I look at the outputs i see a gatk-haplotype folder and it has 202 samples with the gatk-halotype calls for each of them. I also see there is gatk-haplotype-joint folder which has 202 sample folders each which name joint (1010-Ngv3-joint) and it has the following files

1010-NGv3-joint-joint-effects-stats.genes.txt  
1010-NGv3-joint-joint-effects-stats.html
1010-NGv3-joint-joint-effects-filterSNP-filterINDEL-gatkclean.vcf.gz 
1010-NGv3-joint-joint-effects.vcf.gz           
1010-NGv3-joint-joint-effects-filterSNP-filterINDEL-gatkclean.vcf.gz.tbi 
1010-NGv3-joint-joint-effects.vcf.gz.tbi     
1010-NGv3-joint-joint-effects-filterSNP-filterINDEL.vcf.gz  
1010-NGv3-joint-joint-files.list              
1010-NGv3-joint-joint-effects-filterSNP-filterINDEL.vcf.gz.tbi      
1010-NGv3-joint-joint.vcf.gz                 
1010-NGv3-joint-joint-effects-filterSNP.vcf.gz                          
1010-NGv3-joint-joint.vcf.gz.tbi              
1010-NGv3-joint-joint-effects-filterSNP.vcf.gz.tbi                      

So will the batch files be different than above?Does it mean the joint files did not use the pooled samples information to make these files?Your comment above says that providing batch will again make calls and this will be another month of work.

**Comment by chapmanb** [comment]
Diya -- sorry about the confusion and problems. Without batch information they did not use pooled information to make the call, you have 202 samples with individual genotyping. The good news is that you can edit your sample YAML file to add batch information now, remove the `checkpoints_parallel` directory and re-run. That will re-use the existing single sample gVCF files and only re-do the final joint genotyping, resulting in a joint called file which should be much faster than re-running from scratch. Hope this works to get you the analysis you wanted.

**Comment by DiyaVaka** [comment]
Hi Brad,

Its been 2 weeks its still running after updating the script with Batch information. Lat 2 times it failed with the following error. Can you please help?

/mnt/speed/qc/sequencing/ihg-pipeline/sulggi/joint/gatk-haplotype-joint/Batch1/Y/Batch1-Y_0_15523052-b97.vcf.gz --variant /mnt/speed/qc/sequencing/ihg-pipeline/sulggi/joint/gatk-haplotype-joint/Batch1/Y/Batch1-Y_0_15523052-b98.vcf.gz --variant /mnt/speed/qc/sequencing/ihg-pipeline/sulggi/joint/gatk-haplotype-joint/Batch1/Y/Batch1-Y_0_15523052-b99.vcf.gz --variant /mnt/speed/qc/sequencing/ihg-pipeline/sulggi/joint/gatk-haplotype-joint/Batch1/Y/Batch1-Y_0_15523052-b100.vcf.gz --dbsnp /mnt/speed/qc/sequencing/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-147.vcf.gz -nt 8 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
' returned non-zero exit status 134

**Comment by chapmanb** [comment]
Diya;
Sorry about the issue. Would you be able to share more of the log file and traceback as a gist (https://gist.github.com/)? This tells me the command failed but doesn't give any information about what happened so I'm not sure what to suggest. The useful error message is usually at the start of the error traceback. It might be running into memory or other limitations but I can be more specific with additional information. Thanks much for the help debugging.

**Comment by DiyaVaka** [comment]
Thanks Brad,
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00002b31359800ed, pid=7544, tid=47774041732864
#
# JRE version: OpenJDK Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 )
# Problematic frame:
# V  [libjvm.so+0x9490ed]  ContiguousSpace::prepare_for_compaction(CompactPoint*)+0x15d
#
# Core dump written. Default location: /mnt/speed/qc/sequencing/ihg-pipeline/sulggi/core or core.7544
#
# An error report file with more information is saved as:
# /mnt/speed/qc/sequencing/ihg-pipeline/sulggi/hs_err_pid7544.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/

This is my structure for system.yaml

gatk:
    dir: /mnt/speed/qc/sequencing/bcbio/toolplus/gatk/2015.1.1-3.4.46-0-ga8e1d99
    jvm_opts:
    - -Xms500m
    - -Xmx40g
  gatk-haplotype:
    jvm_opts:
    - -Xms500m
    - -Xmx40g
  gatk-vqsr:
    jvm_opts:
    - -Xms500m
    - -Xmx40g
  hisat2:
    cores: 16
    memory: 2G
  kraken:
    cores: 4
    memory: 2g
  macs2:
    cores: 1
    memory: 8g
  miraligner:
    jvm_opts:
    - -Xms750m
    - -Xmx4500m
Should I give more memory. Its running on 8 cores.

**Comment by chapmanb** [comment]
Diya;
Thanks for the additional details and the segfault. I'm a bit confused where this call is coming from. I read through the code and am not sure where we allow use of `-nt 8`. This option often causes problems so we've turned it off in a lot of places. What version of bcbio are you running? Would you be able to share a more full error log so I can see the full command line to know where the call comes from?

I checked in some speculative fixes based on other segfaults we've seen but am not sure if they'll fix the issue based on not being able to trace it back. You could test these or provide more information and we can continue to dig.

For the memory specifcations, the `jvm_opts` should be specified per-core so look much too high. If you've got 8 cores and 40G of memory per machine you'd want `jvm_opts: [-Xms500m, -Xmx5g]` and bcbio automatically scales up in relation to cores when running.

Hope this helps.

**Comment by DiyaVaka** [comment]
Attached are the bcbio.sh and std.err files.
[bcbio_stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/1428184/bcbio_stderr.txt)
[bcbio_sh.txt](https://github.com/chapmanb/bcbio-nextgen/files/1428185/bcbio_sh.txt)

**Comment by chapmanb** [comment]
Diya -- thanks for the details. I'm still a bit confused as we should have disabled `-nt` usage for GenotypeGVCFs with version 0.9.3 (https://github.com/chapmanb/bcbio-nextgen/commit/c55b02341388f5c89c3583a3c3fa7346d13c3057) due to some GATK3 bugs with GenotypeGVCFs. My best guess is that you're hitting something like that with the version of GATK3 you're running and might want to edit your local version of the install to not use `-nt` and see if that resolves the issue. Hope this helps get it running for you.

**Comment by DiyaVaka** [comment]
So you want me to comment this line below in gatkjoint.py script?

params += ["-nt", str(min(6, cores))]

**Comment by chapmanb** [comment]
That's right, although I suspect yours may be different somehow since it's allowing more than 6 cores. Hopefully you can find the point in your code base and adjust. Fingers crossed this fixes it.

**Comment by DiyaVaka** [comment]
Thank you. One thing which crossed my mind is the whole reason we eliminated Batch pooling and were interested in n+1 mode.but currently using Batch information what is it doing is similar to the pooling stuff. Just making sure we are indeed doing this correctly.

**Comment by chapmanb** [comment]
Diya -- all of the grouped strategies require analyzing all samples in a batch together. In pooled calling this needs all BAMs present and calls together from those BAMs. In joint calling we first call to generate gVCFs, then combine those gVCFs for the final calls. The advantage is that if you add a new sample you only need to repeat the final gVCF genotyping, not the initial calls. More details are here: https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#population-calling

The step that's failing here in the combined gVCF joint calling step for your batch. Hope this helps provide context and matches what you're looking for.

**Comment by DiyaVaka** [comment]
Thank you for the details. I hope it runs this time. Another quick question I compared the gvcfs to the gatk-haplotype calls and they differ huge in the number of rows. Aren't they supposed to be same other than format change?

**Comment by DiyaVaka** [comment]
Hi Brad,

As per your suggestion I commented the in the code and rerun it, still getting the same error. Attached
[hs_err_pid75099_log.txt](https://github.com/chapmanb/bcbio-nextgen/files/1444774/hs_err_pid75099_log.txt)
 is the error log. Can you please help?

**Comment by chapmanb** [comment]
Diya;
Thanks for debugging and sorry that you're still hitting the same issue. Unfortunately the java core dump file doesn't give me any extra information to go on, so some thoughts to try and help:

- Did your change remove `-nt` from the command line you see running? I'm still not exactly sure where this gets generated in the older bcbio code but I want to make sure we've actually changed something.
- Can you replicate by running the failed command outside of bcbio?
- If so, can you tweak by removing `-XX:+UseSerialGC` from the command line to see if that fixes it. We've used this to fix java core dumps on some multicore processes in recent versions of bcbio, but not sure if it's the same error.
- Do you have the option of trying an up to date install of bcbio and GATK for this step? If so, it would be helpful to see if the latest release (1.0.6) and recent GATK 3.8 fix the problem and help you get through it.

Hope this helps.

**Comment by DiyaVaka** [comment]
Thanks Brad. I talked to the investigator and she says that may be its the chr Y which is having a issue. In your experience did you see any issues with 'Y' chr.

**Comment by DiyaVaka** [comment]
Hi Brad,

I cannot upgrade the version of the bcbio pipeline because its our clinical licensed version. I tried running the command that failed, outside of the pipeline but it still failed. At this point what i have is a Batch folder with all chr split into 100 sub vcfs.gz files. Can you please help me understand what happens in the background as we are failing to run this step through the version of bcbio that we are using. 

Here is what I am planning to do. Please correct me if this is what not happens through the pipeline. Merge the 100 sub vcf files for each chr to one vcf file and then concatenate all these single vcf files from each chr to one big giant vcf.  Will this procedure do the same stuff that bcbio does?

Thanks,

**Comment by chapmanb** [comment]
Diya;
Thanks for following up on this. It's useful that you can replicate outside of bcbio. Would it be possible to use an updated version of GATK just for this merge step to determine if it's a bug in your version or something fundamentally problematic about the data? If it worked then you could plug that into the right place in bcbio and use it to do the rest of the calling and merging.

You're right that those the commands bcbio is automating, but I'm not sure how running them outside of bcbio, with the same versions will help. Won't you hit the same underlying issue? Is there anything bcbio is doing you can tweak to help resolve the issue?

Thanks much for the patience debugging this.

**Comment by DiyaVaka** [comment]
Hi Brad,

I am running things outside of bcbio and when I do the same for chr X. I get this error

The list of input alleles must contain <NON_REF> as an allele but that is not the case at position 200860; please use the Haplotype Caller with gVCF output to generate appropriate records

Attached is the script.
[X_prep_sh.txt](https://github.com/chapmanb/bcbio-nextgen/files/1480186/X_prep_sh.txt)

**Comment by DiyaVaka** [comment]
Also I tried to update to new verison of GATK 3.8 and updated the system.yaml file. Now it gives me this error below. We already have samtools and GRCh in place

[2017-11-16T21:05Z] Checking sample YAML configuration: /mnt/speed/qc/sequencing/ihg-pipeline/sulggi/sample.yaml
[2017-11-16T21:05Z] Downloading GRCh37 samtools from AWS
Traceback (most recent call last):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 120, in variant2pipeline
    [x[0]["description"] for x in samples]]])
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 300, in organize_samples
    return run_info.organize(*args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 66, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 158, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 207, in get_refs
    galaxy_config, data)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 159, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 280, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file GRCh37 samtools
[sequencing@ihg-node-47 sulggi]$ ls /mnt/speed/qc/sequencing/bcbio/
anaconda/                 bin/                      external_programs/        gemini_data/              local_install/            run_tests.log
bcbio_nextgen_install.py  cloudbiolinux/            galaxy/                   GenomeAnalysisTK.jar      manifest/                 share/
bcbio_nextgen.py          cloudbiolinux-master/     gatk.license              genomes/                  requirements-conda.txt    tmpbcbio-install/
bcbiotx/                  config/                   gemini-config.yaml        git/                      run_tests.err             toolplus/
[sequencing@ihg-node-47 sulggi]$ ls /mnt/speed/qc/sequencing/bcbio/genomes/
Hsapiens
[sequencing@ihg-node-47 sulggi]$ ls /mnt/speed/qc/sequencing/bcbio/genomes/Hsapiens/
GRCh37  K03455_manual
[sequencing@ihg-node-47 sulggi]$ ls /mnt/speed/qc/sequencing/bcbio/genomes/Hsapiens/

**Comment by chapmanb** [comment]
Diya;
Glad you're making some progress with this. In bcbio the SerialGC command gets added here:

https://github.com/chapmanb/bcbio-nextgen/blob/38301f71f35f64725184a5c6306ca828e2191442/bcbio/broad/__init__.py#L34

You'll have to trace back some to where it is in your older version but hopefully commenting it out there will let you proceed without core dumps.

For the batching, bcbio batches joint calling with more than 200 samples into chunks based on GATK3 recommendations. You can adjust how bcbio does this using the `joint_group_size` parameter, which defaults to 200:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html?highlight=joint_group_size#variant-calling

Hope this helps.

**Comment by DiyaVaka** [comment]
Thank you. I will do that. For research pipelines I want to go with new version of bcbio but I am getting these errors

[localhost] local: /home/sequencing/bcbio/anaconda/bin/conda info --envs --json
[localhost] local: /home/sequencing/bcbio/anaconda/bin/conda create -y --name samtools0
Error: too few arguments, must supply command line package specs or --file

You can specify one or more default packages to install when creating
an environment.  Doing so allows you to call conda create without
explicitly providing any package names.

To set the provided packages, call conda config like this:

    conda config --add create_default_packages PACKAGE_NAME


Fatal error: local() encountered an error (return code 1) while executing '/home/sequencing/bcbio/anaconda/bin/conda create -y --name samtools0'

Aborting.
Traceback (most recent call last):
  File "./bcbio-nextgen/scripts/bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio-nextgen/scripts/bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/envs/sequencing/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/sequencing/bcbio', '--genomes=GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Diya;
Sorry about the install problem, I pushed a fix that should resolve this if you remove any temporary CloudBioLinux download directories (`rm -rf tmpbcbio-install`) and re-run the install/upgrade command you previously ran. It should pick off where it left off and provide an initial package for this environment. Thanks for catching this and hope it gets things cleanly installed for you.

**Comment by DiyaVaka** [comment]
hi Brad,

Thank you. Now I am having one more issue

[localhost] local: /home/sequencing/bcbio/anaconda/bin/conda info --envs --json
[localhost] local: /home/sequencing/bcbio/anaconda/bin/conda create -y --name python3 python=3
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - samtools0

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            


Fatal error: local() encountered an error (return code 1) while executing '/home/sequencing/bcbio/anaconda/bin/conda create -y --name python3 python=3'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/envs/sequencing/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/sequencing/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/sequencing/bcbio', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
You have new mail in /var/spool/mail/sequencing

**Comment by chapmanb** [comment]
Diya;
Thanks for the report and sorry about the problems. I'm confused as to what is going on here, `samtools0` is the name of the next environment to create and I don't see it in the command line that fails so I'm not sure how it causes this failure. I can't reproduce this hear so am totally confused.

At this point, I'd try removing the existing half finished install and re-start to see if that clears up the problem. Sorry to not have a better clue but hope this avoids the issue and gets your install finished.

**Comment by DiyaVaka** [comment]
As per your suggestion i wiped off all the directories and downloaded the install script and restarted things from scratch. Still I got the same error. I can try do it it again but I am pretty sure it will end up with same error message

**Comment by chapmanb** [comment]
Diya;
I'm really confused as I can't replicate this with updates or clean installs on my side. Is it possible you have an old problematic download directory? If so, doing `rm tmpbcbio-install` and running should download the latest and hopefully work. Apologies for not knowing what is happening here but hope this helps.
