### ISSUE TITLE
Preparing Illumina exome target file

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1341]
Hi!

Thanks for the great pipeline!

When calling variants with exome data, to have a proper coverage report 
it is necessary to provide the bed file with coordinates of exons.
I've downloaded it from the Illumina site. However it requires some parsing before run.  Exome variant calling with Illumina seems to be the frequent use case, maybe it is worth to include this into the docs if not to the data bundle? Otherwise the workflow for the new user may turn to be: 
1) run with default bed; 
2) fix chr issue and re-run; 
3) fix MT issue and re-run; 
4) delete bed_prep directory and re-run.

`wget http://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/samplepreps_nextera/nexterarapidcapture/nexterarapidcapture_exome_targetedregions_v1.2.bed`
`cat nexterarapidcapture_exome_targetedregions_v1.2.bed | sed s/chr//g | sed s/M/MT/g > nexterarapidcapture_exome_targetedregions_v1.2.no_chr.MT.bed`

Best,
SN

**Comment by chapmanb** [comment]
Thanks much for the helpful feedback. It's so helpful to have suggestions for improving the documentation. I added a section on using sed and awk to remap coordinates using an approach from @roryk that also handles the haplotype chromosomes:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#input-file-preparation

Thank you again.
