### ISSUE TITLE
small rna seq analysis using bcbio (parameter duplicating)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1343]
Hi

I'm testing the small rna seq workflow using bcbio.

I checked cutadapt command in below.

> bcbio-nextgen-commands.log:[2016-04-08T16:53Z] /BiO/BioTools/bcbio/data/anaconda/bin/cutadapt --adapter=TGGAATTCTCGGGTGC **--minimum-length=8** --untrimmed-output=/BiO/BioPeople/brandon/test_bcbio/smrna/mirqc_bcbio/work/trimmed/miRQC_B_rep2/SRR950879.fragments.fastq.gz -o /BiO/BioPeople/brandon/test_bcbio/smrna/mirqc_bcbio/work/trimmed/miRQC_B_rep2/tx/tmpa7_6O7/SRR950879.clean.fastq.gz **-m 17** --overlap=8 /BiO/BioPeople/brandon/test_bcbio/smrna/raw/SRR950879.fastq.gz --too-short-output /BiO/BioPeople/brandon/test_bcbio/smrna/mirqc_bcbio/work/trimmed/miRQC_B_rep2/SRR950879.short.fastq.gz

According to description in cutadapt..
    -m LENGTH, --minimum-length=LENGTH
                        Discard trimmed reads that are shorter than LENGTH.
                        Reads that are too short even before adapter removal
                        are also discarded. In colorspace, an initial primer
                        is not counted (default: 0).

Is it duplicate?

**Comment by lpantano** [comment]
Hi,

I am not sure to understand the problem. 

I want to discard any sequence is smaller than 17 after or before adapter removal. Can you explain further what you need or the problem?
You talk about colorspace, right now this pipeline is adapter to illumina data, or fastqc with sanger phred scores.

cheers

**Comment by chapmanb** [comment]
Lorena;
I think the worry is that we're passing the minimum-length argument two times on the command line, once with a short option and once with a long, with two different values: 8 and 17.

**Comment by lpantano** [comment]
Thanks @chapmanb is smarter than me.
sorry about the confusion. You are right, the parameter is duplicated.

thanks for looking into that.

**Comment by hmkim** [comment]
Thanks :D
