### ISSUE TITLE
QC Report generation issue with GC coverage

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1346]
I wonder if this has to do with the DP issue reported last week.

```
label: variants-coverage-gc (with options) 
List of 2
 $ fig.width : num 15
 $ fig.height: num 15

Quitting from lines 379-403 (report-ready.Rmd) 
Error in ifelse(!is.na(self$limits), self$limits, self$range$range) : 
  replacement has length zero
Calls: render ... <Anonymous> -> f -> expand_range -> <Anonymous> -> f -> ifelse
```

**Comment by lbeltrame** [comment]
I confirm it's the case, all these files are with "." DP.

**Comment by lpantano** [comment]
I fixed that, but I am worry about having these values there. I was expecting some of them, but to get this error, it seems all your values are `.`

Whenever you can confirm, please let me know.
