### ISSUE TITLE
Why qualimap may request 117G heap?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1349]
Hi, Brad!

Thanks again for the excellent pipeline!

I'm trying to run variant calling on exome data.
Pipeline is crashing almost in the end on report generation - qualimap. 
It is trying to request 117G of ram for java - which is too much. The node has 120G of RAM,
it seems that the program is trying to allocate all the available memory.

bcbio-nextgen.log
>[2016-04-18T19:53Z]
>  Timing: quality control
> [2016-04-18T19:53Z] multiprocessing: pipeline_summary
> [2016-04-18T19:53Z] Generating summary files: SRR1976040
> [2016-04-18T19:53Z] Uncaught exception occurred
>

> 
> Traceback (most recent call last):
>   File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
>     _do_run(cmd, checks, log_stdout)
>   File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; unset DISPLAY && /home/naumenko/work/tools/bcbio/anaconda/bin/qualimap bamqc -bam /hpf/largeprojects/ccmbio/naumenko/bcbio_test_exome/work/align/SRR1976040/SRR1976040-sort-downsample.bam -outdir /hpf/largeprojects/ccmbio/naumenko/bcbio_test_exome/work/qc/SRR1976040/qualimap -nt 16 --java-mem-size=117g  -gff /hpf/largeprojects/ccmbio/naumenko/bcbio_test_exome/work/qc/SRR1976040/qualimap/nexterarapidcapture_exome_targetedregions_v1.2.no_chr.MT-merged-bed6.bed
> Java memory size is set to 117g
> Launching application...
> 

bcbio-nextgen-debug.log

> [2016-04-18T19:53Z] Java memory size is set to 117g
> [2016-04-18T19:53Z] Launching application...
> [2016-04-18T19:53Z] 
> [2016-04-18T19:53Z] Error occurred during initialization of VM
> [2016-04-18T19:53Z] Unable to allocate 3839168KB bitmaps for parallel garbage collection for the requested 122853376KB heap.
> [2016-04-18T19:53Z] Uncaught exception occurred
> Traceback (most recent call last):
>   File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
>     _do_run(cmd, checks, log_stdout)
>   File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; unset DISPLAY && /home/naumenko/work/tools/bcbio/anaconda/bin/qualimap bamqc -bam /hpf/largeprojects/ccmbio/naumenko/bcbio_test_exome/work/align/SRR1976040/SRR1976040-sort-downsample.bam -outdir /hpf/largeprojects/ccmbio/naumenko/bcbio_test_exome/work/qc/SRR1976040/qualimap -nt 16 --java-mem-size=117g  -gff /hpf/largeprojects/ccmbio/naumenko/bcbio_test_exome/work/qc/SRR1976040/qualimap/nexterarapidcapture_exome_targetedregions_v1.2.no_chr.MT-merged-bed6.bed
> Java memory size is set to 117g
> Launching application...
> 

I use memory settings:
in project.yaml
> resources:
>   default:
>     memory: 2G
>     cores: 16
>     jvm_opts: ["-Xms750m", "-Xmx2000m"]
>

in bcbio/galaxy/bcbio_system.yaml
>  qualimap:
>     memory: 8g
> 

Any ideas?  In the project config file I use:
>  effects: vep
>  tools_on: [svplots, qualimap]

Thanks!
SN

**Comment by chapmanb** [comment]
SN;
Sorry about the issues. It's trying to use most of the machine for running qualimap -- all 16 cores plus the majority of the memory leaving some for the OS. The memory specifications in bcbio_system.yaml are per core, so it does 8g * 16 then adjusts to the available memory. If you want to use less, you can decrease the value specified under qualimap and it should scale accordingly. @lpantano I saw you set this as 8g/core default. Is that much required for qualimap, or could we reduce the default value?

**Comment by lpantano** [comment]
Hi,

I have used as much as 4 cores, so maybe that is the problem. You can try to reduce to get a total of 24G or so. It is difficult to predict how much it would need for bamqc because we had problems with memory and time in the past. Let’s know if reducing the memory works fine, or maybe reduce the number of max cores to use as well to 8. We can change the default for sure.

**Comment by naumenko-sa** [comment]
Thanks @chapmanb and @lpantano ,
I used  
```
qualimap:
    memory: 2g
```
in the bcbio/galaxy/bcbio_system.yaml and it finished correctly.
From the debug.log:
```

Qualimap: SRR1976040
Java memory size is set to 30g
...
QualiMap

Available memory (Mb): 33
Max memory (Mb): 28633
```
So in my case 30g for this step were enough.
