### ISSUE TITLE
I can't found the information (merge_bamprep in configuration)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1350]
I can't found the description of this variable in configuration.

merge_bamprep

please, add the description on this document (right?)

https://github.com/chapmanb/bcbio-nextgen/blob/master/docs/contents/configuration.rst

**Comment by lbeltrame** [comment]
I think `merge_bamprep` has been deprecated in future versions of the pipeline, and outright removed as an option.

**Comment by hmkim** [comment]
Thanks for youre reply!
