### ISSUE TITLE
Small RNAseq pipeline (miraligner)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1357]
```

species found
Go to mapping...
Mismatches: 1
Trimming: 3
Addition: 3
Species: hsa
Sun Apr 24 01:42:58 KST 2016

Reading reads
Number of reads to be mapped: 349468
Searching in precursors
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
        at miraligner.map.alignment(map.java:476)
        at miraligner.map.align3end(map.java:441)
        at miraligner.map.align2(map.java:422)
        at miraligner.map.readseq(map.java:198)
        at miraligner.Main.main(Main.java:85)
' returned non-zero exit status 1
```

Could you check this error?

I can't find the solution of this problem.

**Comment by lpantano** [comment]
hi,

sorry about this. Is happening with all samples? sometimes I have seen this when the java version is not 1.7

you can check the binary, just read the miraligner exec file and check what java version is using. If it is 1.7, then i would need the input file to debug further. 



sent not from my computer

**Comment by lpantano** [comment]
You can try to run the command using the JAR file to make sure if with java 1.7 works or not lie this:

`java -Xms512m -Xmx8g -jar $JAR_DIR/miraligner.jar`

JAR_DIR, should be inside the conda bcbio installation something like `share/java/seqbuster-2.3-3`, if that is not the problem, it would be good to send me the fastq file so I can debug further.

cheers

**Comment by hmkim** [comment]
Thanks for your reply.

I solve this issue with changing the java version (1.8 -> 1.7)

If you can, please consider the higher java version (>= 1.7)

Thanks.

**Comment by lpantano** [comment]
awesome, i will work around this problem. Or will try to create compatible jar files with 1.8


sent not from my computer
