### ISSUE TITLE
About DEXSeq in bcbio_setup_genome.py

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1359]
bcbio_setup_genome.py -f U00096.3.txt -g U00096.3.gtf -n Ecoli -b MG1655 -i bowtie2

```
2016-04-25 13:41:29,891 - INFO - Creating relations(child) index
2016-04-25 13:41:29,927 - INFO - Creating features(featuretype) index
Writing out merged GTF file to /BiO/BioTools/bcbio/data/genomes/Ecoli/MG1655/tmpcbl/ref-transcripts.gtf.
Error in find.package("DEXSeq") : there is no package called ‘DEXSeq’
Execution halted
Creating gffutils database for /BiO/BioTools/bcbio/data/genomes/Ecoli/MG1655/tmpcbl/rRNA.gtf.
2016-04-25 13:41:40,624 - INFO - Committing changes: 0 features
2016-04-25 13:41:40,625 - INFO - Populating features table and first-order relations: 332 features
2016-04-25 13:41:40,626 - INFO - Creating relations(parent) index
```

Hi,

When I preparing the bacterial genome in bcbio, I got the error about the DEXSeq.

What is function of DEXSeq with setting genome in bcbio?

In sure, this script well finished except for DEXSeq.

Thanks!

---

I recognize the DEXSeq. I think this tool not porting in bcbio now.

**Comment by roryk** [comment]
Hi @hmkim,

DEXseq is used to look at splicing differences, which you won't have to deal with using ecoli so it is okay for it to be missing. The setup script will use whatever R is in your path, so if the bcbio-nextgen R isn't in your path then it won't pick up the DEXSeq package. Hope that helps!
