### ISSUE TITLE
Paralel processing with/without iPython parallel

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1361]
Hi,

I am little bit confused about the contrast between ``` bcbio_nextgen.py -n [NUMBER] bcbioconf.yaml ``` and ipython parallel. Although, I have read your article for **Variant calling – benchmarking AWS versus local**, I could comprehend well. Sorry.

My aim is to do this process as fast as possible. (Amazon stuff did not go as expected so try to build bcbio in local hpc of university).

My university will allocate ~150 cores to this process. so we are thinking about running 5 x 30 cores at the same time. ( 5 different bcbioruns with different samples in one big cluster).

To understand better I have these following questions;
1. If I use bcbio_nextgen.py with only ```-n [NUMBER]``` option. Will bcbio still execute in parallel fashion.
2. If I run the same process with all the same options but ipython on, will I gain time ?
3. What would be the benefit of the ipython? ( forgive my ignorance)
4. Would you guide me to the way to get best performance ?(with/without ipython)

Thank you for the valuable information,

Best regards,

Tunc.

**Comment by chapmanb** [comment]
Tunc;
Running with ipython allows you to parallelize a run over multiple machines. If you run with `-n` only in local mode it can still parallelize, but over the cores available on a single machine. It sounds like if you're on a compute cluster and have 5 30 core machines you want to use ipython to make use of all 150 cores. The documentation has more details about parallelization:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html

Hope this helps.
