### ISSUE TITLE
trying to write to non-writable IO device

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#1364]
Dear Brad,

An error occurred when I using:

/public/home/bcbio_install/anaconda/bin/bcbio_nextgen.py ../config/WGS.yaml -t ipython -n 100 -s torque -q high

The error seems occurred in the process of bamprepare.

CalledProcessErrorESC[0m: Command 'set -o pipefail; /public/home/bcbio_install/anaconda/bin/sambamba view -f bam -L /public2/WGS_p1/work/regions/WGS_p1-noanalysis_blocks.bed /public2/WGS_p1/work/align/WGC071511/WGC071511-sort.bam | /public/home/bcbio_install/anaconda/bin/bedtools intersect -abam - -b /public2/WGS_p1/work/regions/LC_WGS2016_p1-noanalysis_blocks.bed -f 1.0 -nonamecheck> /public2/WGS_p1/work/bamprep/WGC071511/noanalysis/tx/tmpDeNYg1/WGC071511-sort-noanalysis-prep.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
sambamba-view: unable to write to stream
/bin/bash: line 1: 10291 Exit 1                  /public/home/juncheng/bcbio_install/anaconda/bin/sambamba view -f bam -L /public2/WGS_p1/work/regions/LC_WGS_p1-noanalysis_blocks.bed /public2/LC_WGS_p1/work/align/WGC071511/WGC071511-sort.bam
     10292                (core dumped) | /public/home/bcbio_install/anaconda/bin/bedtools intersect -abam - -b /public2/WGS_p1/work/regions/WGS_p1-noanalysis_blocks.bed -f 1.0 -nonamecheck > /public2/WGS_p1/work/bamprep/WGC071511/noanalysis/tx/tmpDeNYg1/WGC071511-sort-noanalysis-prep.bam
' returned non-zero exit status 134

Why there is "non-writable IO device"?

Could you help me check it ?

Thanks so much!

**Comment by chapmanb** [comment]
Sorry about the issue. This typically indicates a problem writing to a shared filesystem and can happen if the filesystem is busy or under load. What type of filesystem is:
```
/public2/LC_WGS_p1/work
```
You could try re-running to determine if it's a reproducible error. If it is the next step might be to use a temporary directory on local disk instead of a shared filesystem to avoid the problem:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory

bcbio would copy the files back to the shared filesystem directories after writing them. Hope this helps.

**Comment by junchend** [comment]
Hi Brad,

Thanks for the suggestion, I changed the tmp location at a local position, but the error is the same:

Command 'set -o pipefail; /public/home/bcbio_install/anaconda/bin/sambamba view -f bam -L /public2/WGS_p1/work/regions/WGS_p1-noanalysis_blocks.bed /public2/WGS_p1/work/align/WGC071499/WGC071499-sort.bam | /public/home/juncheng/bcbio_install/anaconda/bin/bedtools intersect -abam - -b /public2/WGS_p1/work/regions/WGS_p1-noanalysis_blocks.bed -f 1.0 -nonamecheck> /public/tmp/bcbiotx/d8ff76ca-6536-44c5-b302-bb5ddc39e629/tmpDnYoPM/WGC071499-sort-noanalysis-prep.bam
terminate called after throwing an instance of 'std::runtime_error'
  what():  BgzfStream::Write() - trying to write to non-writable IO device
sambamba-view: unable to write to stream

but if I just ran:

/public/home/bcbio_install/anaconda/bin/sambamba view -f bam -L /public2/WGS_p1/work/regions/WGS_p1-noanalysis_blocks.bed /public2/WGS_p1/work/align/WGC071499/WGC071499-sort.bam | /public/home/juncheng/bcbio_install/anaconda/bin/bedtools intersect -abam - -b /public2/WGS_p1/work/regions/WGS_p1-noanalysis_blocks.bed -f 1.0 -nonamecheck> **/public/tmp/bcbiotx/WGC071499-sort-noanalysis-prep.bam**

It will generate the bam file.

You mean this is the error for the cluster system? but the previous steps were all right, the alignment is ok.

**Comment by chapmanb** [comment]
Thanks for helping debug this. Is `/public` also a shared filesystem like `/public2`? If so, I'd expect it to have similar types of issues under load. It looks like you're running realignment in your workflow, is that right? If so, that's a very IO intensive step so will stress the filesystem more than the alignment step. I wouldn't expect single individual command lines run separately to stress it out, but that you'd see this issue intermittently under load when running in parallel.

Practically you could turn off recalibration and realignment:
```
algorithm:
  recalibrate: false
  realign: false
```
and that will skip these with minimal effect on downstream variant calling (http://bcb.io/2013/10/21/updated-comparison-of-variant-detection-methods-ensemble-freebayes-and-minimal-bam-preparation-pipelines/), or alternatively try to set the temporary directory to a non-shared filesystem with local disk.

Hope this helps.

**Comment by junchend** [comment]
Thanks so much, "recalibrate and realign" is the reason, I will find a local disk to store the tmp files

**Comment by lpantano** [comment]
Hi,

hope you could find the solution. Feel free to open any other issue.

thanks!
