### ISSUE TITLE
report-ready.Rmd minor bug

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1366]
Good morning!

Again, excellent pipeline!

in final/project/report/report-ready.Rmd
first table Basic_sample_metrics (built on metrics/metrics.tsv),
columns Mapped_reads_pct, Duplicated_pct are displayed incorrectly 
(1% instead of 99%) : in metrics.tsv they 
are in the format 0.99 (for 99%) so there is no need to divide them by 100.

Solution: comment two lines:

> # Adjust some of the text information for formatting purposes
>qc_table <- qc[, metrics]

>qc_table$Mapped_reads_pct = as.numeric(gsub("%", "", qc_table$Mapped_reads_pct))
>#qc_table$Mapped_reads_pct <- qc_table$Mapped_reads_pct / 100

>qc_table$Duplicates_pct = as.numeric(gsub("%", "", qc_table$Duplicates_pct))
>#qc_table$Duplicates_pct <- qc_table$Duplicates_pct / 100

Unfortunately I did not find where to fix this in the repo.

Best,
Sergey

**Comment by lpantano** [comment]
Thanks a lot, feel free to do a PR to https://github.com/lpantano/bcbio.coverage/blob/master/bcbreport/qc.Rmd <https://github.com/lpantano/bcbio.coverage/blob/master/bcbreport/qc.Rmd>

If not I will apply the changes.

cheers

**Comment by lpantano** [comment]
thanks again!
