### ISSUE TITLE
NA12878-hg38-validate yaml file

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1369]
Hi,

When I testing the bcbio pipeline with NA12878-hg38-validate.

$ wget -c https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/config/examples/NA12878-hg38-validate.yaml

I have an trouble with yaml configuration.

Please check this issue.

![2016-04-27 10 10 19](https://cloud.githubusercontent.com/assets/4966343/14838848/7f5cca50-0c60-11e6-9033-d300372a16fa.png)

**Comment by roryk** [comment]
Hi @hmkim,

Sorry about that, I fixed the trailing whitespace issue so this should be all set. Let me know if you are still running into problems.

**Comment by hmkim** [comment]
Thanks for your support!

**Comment by chapmanb** [comment]
Thanks Rory for the quick fix. I also pushed an improvement to the YAML checking to avoid failing on whitespace issues, so the latest development will be a bit more lenient. Thanks much for reporting this.
