### ISSUE TITLE
KeyError: "base" if genome loc files point to non-existent directories

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1370]
As the subject says, in one of my clusters the machine installing bcbio (which does not use it, it only exports the installation via NFS) and the paths are different on that machine versus the exported path.

I handle this after upgrades, but if I don't, and the `*.loc` files point to non existent genomes, I get greeted by that error (which is misleading) rather than a proper exception.

**Comment by chapmanb** [comment]
Luca -- thanks much for the heads up on the problem. I added in a more useful error message that should point you in the right direction for any future problems. Thanks again for the suggestion.
