### ISSUE TITLE
Planning the another workflow

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1371]
Hi, all

I wondering about the bcbio-nextgen's next plan.

I really hope to contribute the another workflow (like metagenome, de novo assembly, epigenome) in bcbio.

💃

**Comment by schelhorn** [comment]
I guess that genome assembly is a little out-of-scope, but I may be wrong. Bisulfite-seq and chip-seq could use some work, in my opinion, if you want to contribute.

**Comment by chapmanb** [comment]
Hyunmin;
Thanks for your enthusiasm and offers to help. We don't have any plans to expand to additional pipelines right now. This is generally driven by researcher need, and most of our effort currently is on testing and expanding existing variant calling, small RNA and RNA-seq pipelines. If you wanted to work on one, the current CHiP-seq pipeline could use additional love and testing. Thanks so much.

**Comment by hmkim** [comment]
Ok. I recognized it.

Thank you very much for your effort!
