### ISSUE TITLE
RNAseq pipeline: how to incorporate clinical metadata?

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1373]
Hi all,

I have some clinical metadata for my samples (BMI, blood sugar, age, etc) and would like to incorporate it into the RNAseq analysis if possible.

I can imagine I could add it to the config file. Right now, I have information about the sequencing run in there and the condition (healthy or disease).

Is this the best approach to incorporating this kind of information into an RNAseq run? Or is it better to use this metadata in the downstream analysis somehow?

Both my batch information and condition information are factor variables, but BMI could be a continuous variable. Does this matter to the analysis?

I'd appreciate any suggestions you might have (or pointers to resources that describe such an analysis)!

Best,
~Lina

**Comment by roryk** [comment]
Hi Lina,

You can add it under the metadata field in the data file, usually using the automated configuration analysis is helpful:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#automated-sample-configuration

`bcbio-nextgen` won't do the differential expression analysis, it will just set you up with a table of counts and sailfish output so you can do the differential expression. This repository: 

https://github.com/roryk/bcbio.rnaseq

Will do the differential expresson. You'd do:

```bash
bcbio-rnaseq summarize -f bmi+batch+condition path-to-the-project-summary-file.yaml
```

This will make a bunch of QC plots and run a DESeq2 differential expression using the Sailfish quantitated counts, doing paired analysis controlling for bmi and comparing only conditions from the same batch to each other. What we usually do is set up something like that and then open up the report in RStudio and explore the data, almost all experiments need some kind of manual intervention, but this at least gets you set up to start.

**Comment by lfaller** [comment]
Thanks, that makes sense! I wasn't sure if I had to rerun the whole RNAseq pipeline (which would take very long :-) )
