### ISSUE TITLE
Installation to tmp directory

### ISSUE THREAD

**Issue by rohandavidg** [chapmanb/bcbio-nextgen#1374]
Hi,

is there a way to avoid cloudbiolinux to write to home directory and write to a specified directory

I got this error when i tried to install bcbio
mkdir: cannot create directory `/home/rohan/tmp/cloudbiolinux/12e9f8b9-99ec-3859-82b3-6afaf15ef2ca': Disk quota exceeded

Fatal error: local() encountered an error (return code 1) while executing 'mkdir -p '/home/rohan/tmp/cloudbiolinux/12e9f8b9-99ec-3859-82b3-6afaf15ef2ca''

Aborting.

Thanks,
Rohan

**Comment by chapmanb** [comment]
Rohan;
Sorry about the problem. We shouldn't be using cloudbiolinux temporary directories for too much in the install at this point. If you post the full traceback happy to try and resolve it's usage here. To work around the problem and set to a different place you can do:
```
export TMPDIR=/your/new/tmpdir
```
Hope this helps.
