### ISSUE TITLE
ERCC in yaml

### ISSUE THREAD

**Issue by saboswell** [chapmanb/bcbio-nextgen#1375]
I am trying to run the RNAseq pipeline and have the -ercc option. I couldn't get this to work.  Can you let me know the right way to put this in the yaml file?

**Comment by roryk** [comment]
Hi @saboswell,

The ERCC option is for when you make the genome, it appends the ERCC spike ins to the genome and the GTF file. We don't do anything special with the ERCC inside of bcbio so it doesn't need a configuration parameter. Another way you can get the ERCC counts is to align to the ERCC spike ins with bwa outside of bcbio to get a rough idea of the counts. Hope that helps.

**Comment by lpantano** [comment]
Hi @saboswell, I am closing this but feel free to open if you still have issues.

thanks
