### ISSUE TITLE
salmon (Segmentation fault)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1376]
When I use the fast-RNAseq workflow, I got the error in below with salmon.

>...
> [2016-05-01 06:40:33.484] [jointLog] [warning] NOTE: Read Lib [( /dev/fd/63, /dev/fd/62 )] :
> 
> Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: /BiO/Human-RNAseq-fast-rnaseq/work/salmon/OHO/tx/tmpTfIOH0/quant/libFormatCounts.txt for details
> 
> /bin/bash: line 1: 12838 Segmentation fault      (core dumped) /BiO/BioTools/bcbio/data/galaxy/../anaconda/bin/salmon quant -l ISR -i /BiO/Human-RNAseq-fast-rnaseq/work/salmon/OHO/index/GRCh37 -p 6 -o /BiO/Human-RNAseq-fast-rnaseq/work/salmon/OHO/tx/tmpTfIOH0/quant -1 <(gzip -cd Human-RNAseq-2016-04-TBD160162/merged/OHO_R1.fastq.gz) -2 <(gzip -cd Human-RNAseq-2016-04-TBD160162/merged/OHO_R2.fastq.gz) --numBootstraps 30
> ' returned non-zero exit status 139

I look at about this error.  (Refer to this https://github.com/COMBINE-lab/salmon/issues/34)

and I downloaded this version of salmon. (https://github.com/COMBINE-lab/salmon/releases/download/v0.6.0/SalmonBeta-0.6.0_DebianSqueeze.tar.gz)

I finished the salmon step successfully with this version

> ...
> [2016-05-01 15:51:30.272] [jointLog] [info] wrote 29 bootstraps
> [2016-05-01 15:51:47.354] [jointLog] [info] wrote 30 bootstraps
> [2016-05-01 15:51:47.425] [jointLog] [info] Finished Bootstrapping
> [2016-05-01 15:51:47.428] [jointLog] [warning] NOTE: Read Lib [( /dev/fd/63, /dev/fd/62 )] :
> 
> > Greater than 5% of the alignments (but not, necessarily reads) disagreed with the provided library type; check the file: /BiO/Human-RNAseq-fast-rnaseq/work/salmon/OHO/tx/tmpTfIOH0/quant/libFormatCounts.txt for details

Please check the salmon tool in bcbio.

**Comment by chapmanb** [comment]
Hyunmin;
Thanks for the problem report and pointer to the Salmon issue. The pre-built Salmon binaries unfortunately only work on CentOS6+, but we adjusted the bioconda recipe to use a custom downloaded version of tcmalloc which will hopefully avoid the problem. Thank you again.
