### ISSUE TITLE
RNAseq pipeline: how to add more samples afterwards

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1379]
Hi all,

I am using bcbio-next gen to run the RNAseq pipeline.

I have a bunch of samples that I ran through bcbio-nextgen pipeline. However, I recently got another batch of samples that I want to incorporate into the initial analysis (to ultimately determine DE genes).

I originally aligned all the samples using tophat which took forever :-) so I don't want to just rerun the whole thing from scratch.

If I just run the new samples from scratch, will the end result be comparable so that I can compare it using DESeq2? What's the best way to incorporate these new samples into the existing project?

Thanks a bunch!
~Lina

**Comment by roryk** [comment]
Hi Lina-- you can totally run the new samples separately, but you'd have to combine the reports at the end manually by combining the counts and the metadata about the samples together before running DESeq2. If you are good with doing that then you should be all set.

**Comment by roryk** [comment]
There are some options to speed things up; you could switch to the STAR aligner which is much faster but requires around 40GB of RAM. Another option if you only care about getting the count results fast is to run the fast RNA-seq pipeline in bcbio-nextgen. This will skip almost all QC of the samples though, so I don't recommend doing it if you think the samples are going to need some QC.

**Comment by lfaller** [comment]
Great! I can definitely combine two count matrices manually :-)

I will check out the STAR aligner option and the fast RNA-seq pipeline. My gut instinct would say to try the tophat route first so that all samples were processed the same way, but maybe STAR is so fast that I can rerun all the samples using it...

**Comment by roryk** [comment]
Hi Lina,

You got it— you could rerun all of the samples with STAR or the new subset with Tophat, but not mix the two.

Best,

Rory
