### ISSUE TITLE
Manta description not compatible with SVTools vcftobedpe 

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#1385]
Forgive me for not doing a pull request. I can not find the actual script for svtools vcftobedpe. Maybe its not even in this repository since it is bcbio-tools?

Its a minor issue, except to me because Im trying to convert the manta vcf into a bedpe so I can attempt to merge it in some fashion with the other SV callers. 

manta.vcf.gz has a description which breaks on line 68 of bcbio-tools/bin/vcftobedpe. Specifically in the def add_header of the Reader object.

The offending header line is:
```##FORMAT=<ID=SR,Number=.,Type=Integer,Description="Split reads for the ref and alt alleles in the order listed, for reads where P(allele|read)>0.999">```

First off ```a = line[line.find('<')+1:line.find('>')]``` will truncate the 0.999"

Then ```r = re.compile(r'(?:[^,\"]|\"[^\"]*\")+')``` will chew this up as such:
```>>> r.findall(a)
['ID=SR', 'Number=.', 'Type=Integer', 'Description=', 'Split reads for the ref and alt alleles in the order listed', ' for reads where P(allele|read)']```
Which results in an IndexError. The regex pattern really needs that truncated ". Id recommend changing line 66 to ```a = line[line.find('<')+1:line.rfind('>')]```

Crazy simple, surprisingly. Maybe change all of them that way to be safe?

**Comment by bwubb** [comment]
Ugh. One further issue. This one in the def vcfToBedpe proper, around line 467. Manta BND annotation seems to neither have 'SECONDARY' nor 'EVENT=' in the variant INFO. Im not sure why since EVENT are described in the vcf header; SECONDARY is not.

**Comment by chapmanb** [comment]
Brad;
Thanks for the useful feedback. Can you report this to the svtools team (https://github.com/hall-lab/svtools)? That code isn't part of bcbio so they'd have a better understanding of how well your fixes fit. We also updated with a new version of svtools which contains a unified interface (so you now run `svtools vcftobedpe`). It would be worth upgrading bcbio to get this and testing if the new version is any better before reporting. If you still have issues I know it would also help them to have a test case to reproduce the problems. Thanks again.

**Comment by brainstorm** [comment]
@bwubb, indeed, a few months ago I found that issue and reported to the upstream repo:

https://github.com/hall-lab/svtools/pull/6

According to the original author, it should be solved in newer versions and AFAIK there's a bioconda package you'll be able to use soon:

https://github.com/bioconda/bioconda-recipes/pull/1479
