### ISSUE TITLE
bcbio stats doesn't show up properly for tumor-normal pair analysis

### ISSUE THREAD

**Issue by tanglingfung** [chapmanb/bcbio-nextgen#1387]
only % off target and % dup is shown

other metrics are probably messed up with tumor-normal pair setting

**Comment by lpantano** [comment]
Hi,

sorry about this. Can you explain a little better? Are you talking about the multiqc report, the table you see on the top? And I guess you are missing number of variants or what metrics for normal? or for tumor? 

I know that for normal, you won't have number of variants when is tumor-normal analysis, something that I am thinking about how to solve, but need to change bcbio code for that right now. Any other metrics that are wrong or missing?

**Comment by tanglingfung** [comment]
yes, I was referring to the table on the top. average coverage, % in dbsnp are missing for all samples. 

Total variations, ts/tv, homozygous variations, and heterozygous variations are missing for germline sample, which can be extracted from the germline-vcf that's now generated. 

variants specific metrics may be good to be put in another table, where interesting metrics for germline may be different from that of somatic variants. But the current table is nice.

**Comment by lpantano** [comment]
average coverage only will appear if you get the `coverage` option in the YAML file. The % in dbsnp should be there if is human/mouse I think. At least for human is working, so I am not sure why you don't get it. I need to work in the variations for the normal samples, hopefully this week I can look at that.

**Comment by lpantano** [comment]
Hi,

I worked on that, and this should be good now. There would be a specific section for variants metrics in multiqc with the last bcbio development and updating tools.  (69bb98ac8abb3ab68ab320410ef584df696124d3)

I continue working on that, so hopefully it will improve with time.

thanks for reporting this.
