### ISSUE TITLE
Simple install?

### ISSUE THREAD

**Issue by dbolser-ebi** [chapmanb/bcbio-nextgen#1391]
All I want to do is run plink_to_vcf.py... What install instructions should I use?

**Comment by dbolser-ebi** [comment]
Tried this...

    virtualenv venv
    source ./venv/bin/activate
    pip install argparse
    wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
    python bcbio_nextgen_install.py ./

which seems to be working for now.

**Comment by dbolser-ebi** [comment]
Well, that ran OK, but I don't see plink_to_vcf.py installed anywhere... how do I run it?

Many thanks,
Dan.

**Comment by chapmanb** [comment]
Dan -- plink_to_vcf.py is a standalone script so you don't need to install bcbio_nextgen or follow any of the install instructions for that. You'll need to manually install the required tools but otherwise just download the script and call it with Python. Sorry for any confusion.

**Comment by dbolser-ebi** [comment]
Ah, thanks. I was having difficulty installing bx-python, so thought that installing bcbio-nextgen properly would meet that dependency.

**Comment by chapmanb** [comment]
Dan -- that makes sense although all of bcbio is a bit too much for that. You can use a conda install and bioconda to install bx-python cleanly (https://bioconda.github.io/):
```
conda install -c bioconda bx-python
```
That's what bcbio does under the hood but you can pick and choose what you need instead of installing everything. Hope this helps.

**Comment by dbolser-ebi** [comment]
Hmm... I didn't seem to have bx-python available under the bcbio venv.
Thanks for the tip though.


Dan.

**Comment by chapmanb** [comment]
Dan;
The bcbio install script creates it's own isolated python installation, using conda, so bx-python and other dependencies will be within that. It should be under `/path/to/bcbio/anaconda/bin/python`.

**Comment by dbolser-ebi** [comment]
Ah, thanks.

**Comment by lpantano** [comment]
Hi @dbolser-ebi 

I assume Brad's comment fixes the problem.

Come back if you find more issues.

cheers
