### ISSUE TITLE
Creating configuration yaml files in an automated way.

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1393]
Hi Brad,

I have about ~200 patients( 2 bam files each tumor/normal) to get mutations called and lucky, I decided my configuration file which will take care of the processes. However, for all of these 200 patients I have to enter bam id, sm tag.

I know it can be done with scripting languages but is there a known/easier way. For ex: yaml format manipulation?? Could you illuminate me with your experince about this subject?

Thank you very much,

Tunc.

**Comment by chapmanb** [comment]
Tunc;
bcbio has a template system where you supply with a YAML containing most of the parameters and a CSV file with changing information like files and descriptions:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#automated-sample-configuration

Hope this provides what you need.
