### ISSUE TITLE
Amplicon data with mark_duplicates: false. Does not switch off PCR duplicate removal in GATK-HC

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1394]
I think this is a case of me not interpreting the docs correctly. I was performing variant calling using GATK-HC. I set `mark_duplicates: false` but this does not switch off GATK-HC from removing PCR duplicates downs stream (resulted in ~80% of my reads being removed). In order to switch off this I used the command `-drf DuplicateRead`. Is there any way of configuring this in BCBIO?

**Comment by chapmanb** [comment]
Kevin;
Good catch, thanks for identifying this. I agree that it would be better to skip this filter for non-duplicate marked or amplicon data and added in default to do this automatically based on those parameters. If you update to the latest development it'll remove the `DuplicateRead` filter for these cases. Thanks again.

**Comment by kevjp** [comment]
Thanks Brad, was scratching my head wondering why obvious calls were being missed. Thanks for fixing this. I should be able to re-run the analysis with the same configuration.
