### ISSUE TITLE
Install doesn't find STAR indices, causes (slow) generation of them

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1397]
```
[localhost] local: mkdir -p '/home/einar/tmp/cloudbiolinux/0360b202-91e1-3159-9130-d79db8aaf3e3'
[localhost] local: wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz'
--2016-05-18 14:10:19--  https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.115.26
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.115.26|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-05-18 14:10:19 ERROR 404: Not Found.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz''
```

Therefore this causes the generation of the STAR indices, which can be extremely slow. I've also seen this with `hg19`.

**Comment by chapmanb** [comment]
Luca;
STAR produces very large indices, so it is not practical for us to pre-build and distribute them like we do with other aligners. Building locally is the expected behavior. For build speeds, STAR requires a lot of memory so making more available to the install process (I think 48Gb is the recommended amount but @roryk is the expert) will hopefully speed it up. Hope this helps.

**Comment by lbeltrame** [comment]
Fair enough. I wonder though, if STAR needs to run single core for this:

```[localhost] local: export PATH=/opt/bcbio-tools/bin:$PATH && STAR --genomeDir /usr/local/bcbio/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 14
```

It's been running like this since yesterday (32G machine with 8 cores) and I have no idea how long will it take...

**Comment by chapmanb** [comment]
Luca;
Sorry I should have mentioned that in my message. There is a `--cores` argument to `bcbio_nextgen.py upgrade` that will translate to the indexing. If you set `--cores 8` it should improve the index time. Thanks for working through this.
