### ISSUE TITLE
BUG with docker installation and config file

### ISSUE THREAD

**Issue by sib-bcf** [chapmanb/bcbio-nextgen#1398]
Hello, 
I've found a problem when installing bcbio-nextgen within docker.

In bcbio/pipeline/config_utils.load_system_config, the variable config_file is set to point to the merged file in the work directory.
The problem is that the same variable is then used to get the configuration directory for galaxy loc files in bcbio/pipeline/run_info.setup_directories. But, now the variable contains the work directory, and not the install one, therefore the loc files cannot be read, and I get the error:
ValueError: Could not find reference genome file hg38 samtools

Here is the "problematic" code.
In bcbio/pipeline/config_utils.load_system_config:
  
_if docker_config:
        assert work_dir is not None, "Need working directory to merge docker config"
        config_file = os.path.join(work_dir, "%s-merged%s" % os.path.splitext(os.path.basename(config_file)))
        config = _merge_system_configs(config, docker_config, config_file)_

In  bcbio/pipeline/run_info.setup_directories:

_def setup_directories(work_dir, fc_dir, config, config_file):
    fastq_dir, galaxy_dir, config_dir = _get_full_paths(flowcell.get_fastq_dir(fc_dir)
                                                        if fc_dir else None,
                                                        config, config_file)_

**Comment by chapmanb** [comment]
Paolo;
Sorry about the issues. Could you provide a bit more detail about how you are installing and running bcbio inside Docker? We have a pre-built docker image containing bcbio:

https://hub.docker.com/r/bcbio/bcbio/

and a separate interface to run this, which manages the inside/outside Docker parts and mounts in the reference data:

https://github.com/chapmanb/bcbio-nextgen-vm

Are you running with these, or doing something differently? Understanding your process will help us understand how best to avoid the issue you're running into. Thanks much.

**Comment by sib-bcf** [comment]
Dear Brad,
here is my procedure. 
1) Build an image from the docker file https://github.com/chapmanb/bcbio-nextgen/blob/master/Dockerfile#L5
`docker build -t sib-pc6:5000/bcbio:v2016.10.05.test ./`
NB: I changed the installation directory form /usr/local/share/bcbio-nextgen to /bcbio-data
Here is my complete dockerfile:
`FROM stackbrew/ubuntu:14.04
MAINTAINER Brad Chapman "https://github.com/chapmanb"

# v0.9.7 -- https://github.com/chapmanb/bcbio-nextgen/commit/52cda3e

# Setup a base system 
RUN apt-get update && \
    apt-get install -y build-essential unzip wget git openjdk-7-jdk openjdk-7-jre && \
    apt-get install -y libglu1-mesa && \
    apt-get install -y curl pigz bsdmainutils && \
# Support inclusion in Arvados pipelines
    apt-get install -y --no-install-recommends libcurl4-gnutls-dev mbuffer python2.7-dev python-virtualenv && \

# Fake a fuse install; openjdk pulls this in 
# https://github.com/dotcloud/docker/issues/514
# https://gist.github.com/henrik-muehe/6155333
    mkdir -p /tmp/fuse-hack && cd /tmp/fuse-hack && \
    apt-get install libfuse2 && \
    apt-get download fuse && \
    dpkg-deb -x fuse_* . && \
    dpkg-deb -e fuse_* && \
    rm fuse_*.deb && \
    echo -en '#!/bin/bash\nexit 0\n' > DEBIAN/postinst && \
    dpkg-deb -b . /fuse.deb && \
    dpkg -i /fuse.deb && \
    rm -rf /tmp/fuse-hack && \

# bcbio-nextgen installation
    mkdir -p /tmp/bcbio-nextgen-install && cd /tmp/bcbio-nextgen-install && \
    wget --no-check-certificate \
      https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py && \
    python bcbio_nextgen_install.py /bcbio-data \
      --isolate --nodata -u development --tooldir=/usr/local && \
    git config --global url.https://github.com/.insteadOf git://github.com/ && \
    /bcbio-data/anaconda/bin/bcbio_nextgen.py upgrade --isolate --tooldir=/usr/local --tools && \
    /bcbio-data/anaconda/bin/bcbio_nextgen.py upgrade --isolate -u development --tools && \

# setup paths
    echo 'export PATH=/usr/local/bin:$PATH' >> /etc/profile.d/bcbio.sh && \

# add user run script
    wget --no-check-certificate -O createsetuser \
      https://raw.github.com/chapmanb/bcbio-nextgen-vm/master/scripts/createsetuser && \
    chmod a+x createsetuser && mv createsetuser /sbin && \

# clean filesystem
    cd /usr/local && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/tmp/* && \
    /bcbio-data/anaconda/bin/conda clean --yes --tarballs && \
    rm -rf /bcbio-data/anaconda/pkgs/qt* && \
    rm -rf /usr/local/.git && \
    rm -rf /.cpanm && \
    rm -rf /tmp/bcbio-nextgen-install && \

# Create directories and symlinks for data 
    mkdir -p /mnt/biodata && \
    mkdir -p /tmp/bcbio-nextgen && \
    mv /bcbio-data/galaxy/bcbio_system.yaml /bcbio-data/config && \
    rmdir /bcbio-data/galaxy && \
    ln -s /mnt/biodata/galaxy /bcbio-data/galaxy && \
    ln -s /mnt/biodata/gemini_data /bcbio-data/gemini_data && \
    ln -s /mnt/biodata/genomes /bcbio-data/genomes && \
    ln -s /mnt/biodata/liftOver /bcbio-data/liftOver && \
    chmod a+rwx /bcbio-data && \
    chmod a+rwx /bcbio-data/config && \
    chmod a+rwx /bcbio-data/config/*.yaml && \

# Ensure permissions are set for update in place by arbitrary users
    find /usr/local -perm /u+x -execdir chmod a+x {} \; && \
    find /usr/local -perm /u+w -execdir chmod a+w {} \;
`
2) Create a volume container for the reference genome (the /mnt/biodata directories):
`docker create -v /mnt/biodata/liftOver -v /mnt/biodata/genomes -v  /mnt/biodata/gemini_data -v /mnt/biodata/galaxy  --name reference.GRh38.2016.13.05  ubuntu`

The idea here is to have the tools in the image, and the genome reference in a data volume container, as from docker "good practice".

3) Run a container from the built image + reference data container to add the reference files 
`docker run -it --volumes-from reference.GRh38.2016.13.05 --name bcbio_install sib-pc6:5000/bcbio:v2016.10.05.test /bin/bash`

In the container, I've installed the reference genome:
`bcbio_nextgen.py upgrade --data --genomes hg38 --aligners bwa `

4) Run a container with the work directory in the volume /data:
`docker run -it --volumes-from reference.GRh38.2016.13.05 -v $PWD:/data --name bcbio_test sib-pc6:5000/bcbio:v2016.10.05.test /bin/bash`

Run a test (the Standard pipeline for aligning a single fastq file with bwa). 
`root@1c879736bc3d:/data# bcbio_nextgen.py test.yaml -t local -n 8`

Here is the yaml file
`details:
- algorithm:
    aligner: bwa
  analysis: Standard
  description: test-PD12354b
  files: [PD12354b.fastq]
  genome_build: hg38
fc_date: '2016-05-19'
fc_name: test
upload:
  dir: ../final`

The test fails:
`[2016-05-20T08:27Z] System YAML configuration: /data/bcbio_system-merged.yaml
[2016-05-20T08:27Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-05-20T08:27Z] Configuring 1 jobs to run, using 8 cores each with 16.1g of memory reserved for each job
[2016-05-20T08:27Z] Timing: organize samples
[2016-05-20T08:27Z] multiprocessing: organize_samples
[2016-05-20T08:27Z] Using input YAML configuration: /data/test.yaml
[2016-05-20T08:27Z] Checking sample YAML configuration: /data/test.yaml
[2016-05-20T08:27Z] Downloading hg38 samtools from AWS
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 47, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 218, in standardpipeline
    [x[0]["description"] for x in samples]]])
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 287, in organize_samples
    return run_info.organize(*args)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 65, in organize
    item = add_reference_resources(item, remote_retriever)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 162, in add_reference_resources
    data["reference"] = genome.get_refs(data["genome_build"], aligner, data["dirs"]["galaxy"], data)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 207, in get_refs
    galaxy_config, data)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 159, in _get_ref_from_galaxy_loc
    cur_ref = download_prepped_genome(genome_build, data, name, need_remap)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/genome.py", line 278, in download_prepped_genome
    raise ValueError("Could not find reference genome file %s %s" % (genome_build, name))
ValueError: Could not find reference genome file hg38 samtools`

I've checked the .loc files:
`root@1c879736bc3d:/bcbio-data/galaxy# grep -r "hg38" * 
tool-data/gatk_sorted_picard_index.loc:hg38	hg38	Human (hg38) full	/bcbio-data/genomes/Hsapiens/hg38/seq/hg38.fa
tool-data/sam_fa_indices.loc:index	hg38	/bcbio-data/genomes/Hsapiens/hg38/seq/hg38.fa
tool-data/bwa_index.loc:hg38	hg38	Human (hg38) full	/bcbio-data/genomes/Hsapiens/hg38/bwa/hg38.fa
tool-data/picard_index.loc:hg38	hg38	Human (hg38) full	/bcbio-data/genomes/Hsapiens/hg38/seq/hg38.fa`

I've added some print in the code to have a hint on the problem, and I've seen that **config_file** points to **/data**/bcbio_system-merged.yaml instead of **/bcbio-data**/config/bcbio_system.yaml. Therefore config_dir and galaxy_dir are set to **/data** and the .loc files are not found.
Here is the output with the print commands:
`root@1c879736bc3d:/data# bcbio_nextgen.py test.yaml -t local -n 8
config
{'galaxy_config': 'universe_wsgi.ini', 'algorithm': {}, 'resources': {'sailfish': {'cores': 16, 'memory': '1g'}, 'samtools': {'cores': 16, 'memory': '2G'}, 'star': {'cores': 16, 'memory': '2g'}, 'stringtie': {'cores': 16, 'memory': '1g'}, 'hisat2': {'cores': 16, 'memory': '2G'}, 'miraligner': {'jvm_opts': ['-Xms750m', '-Xmx4500m']}, 'picard': {'jvm_opts': ['-Xms750m', '-Xmx3500m']}, 'oncofuse': {'jvm_opts': ['-Xms750m', '-Xmx2000m']}, 'express': {'memory': '8g'}, 'seqcluster': {'memory': '8g'}, 'vardict': {'jvm_opts': ['-Xms750m', '-Xmx3000m']}, 'bwa': {'cores': 16, 'cmd': 'bwa'}, 'default': {'cores': 16, 'jvm_opts': ['-Xms750m', '-Xmx2000m'], 'memory': '2G'}, 'macs2': {'cores': 1, 'memory': '8g'}, 'dexseq': {'memory': '10g'}, 'gatk': {'jvm_opts': ['-Xms500m', '-Xmx3500m']}, 'snpeff': {'jvm_opts': ['-Xms750m', '-Xmx6g']}, 'snap': {'cores': 16, 'memory': '4G'}, 'cufflinks': {'cores': 16, 'memory': '3g'}, 'wham': {'memory': '3500m'}, 'qualimap': {'memory': '4g'}}, 'bcbio_system': '/data/bcbio_system-merged.yaml'}
config_file
/data/bcbio_system-merged.yaml
CONFIG_DIR
/data
CONFIG GET
universe_wsgi.ini
GALAXY DIR
/data
[2016-05-20T08:27Z] System YAML configuration: /data/bcbio_system-merged.yaml
[2016-05-20T08:27Z] Resource requests: bwa, sambamba, samtools; memory: 2.00, 2.00; cores: 16, 16, 16
[2016-05-20T08:27Z] Configuring 1 jobs to run, using 8 cores each with 16.1g of memory reserved for each job
[2016-05-20T08:27Z] Timing: organize samples
[2016-05-20T08:27Z] multiprocessing: organize_samples
[2016-05-20T08:27Z] Using input YAML configuration: /data/test.yaml
[2016-05-20T08:27Z] Checking sample YAML configuration: /data/test.yaml
[2016-05-20T08:27Z] Downloading hg38 samtools from AWS
Traceback (most recent call last):
`

**Comment by sib-bcf** [comment]
Brad,
Thanks for you help, and sorry for bothering you.

I've also a (maybe) related issue.
If the bcbio_system.yaml file is present only in the "docker" _config_ directory (it is moved there in the dockerfile) and not in the _galaxy_ directory, I get the error:

```
root@41775e50af93:/data# bcbio_nextgen.py test.yaml -t local -n 8
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    config, config_file = config_utils.load_system_config(config_file, workdir)
  File "/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 67, in load_system_config
    (config_file, os.path.join(base_dir, "galaxy")))
ValueError: Could not find input system configuration file bcbio_system.yaml, including inside standard directory /bcbio-data/galaxy
```

It seems to me that when config_utils.load_system_config() is called from pipeline/main.run_main, it should be called with the parameter allow_missing set to True, am I wrong?

**Comment by chapmanb** [comment]
Paolo;
Thanks for all the details. If you use the bcbio Dockerfile it assumes you're running with the bcbio_vm.py wrapper scripts (or a Common Workflow Language tool). bcbio_vm.py handles merging an external bcbio_system.yaml file (so you can edit cores/memory) with the internal bcbio_system.yaml (so you can have pointers to directories like GATK jar installations in the container). That's why it's getting confused with the system configurations when you run with your method.

I believe the fix is as easy as getting rid of the lines in the Docker file that move the configuration to the "internal" Docker location under `config`, instead of `galaxy`:
```
mv /bcbio-data/galaxy/bcbio_system.yaml /bcbio-data/config && \
    rmdir /bcbio-data/galaxy && \
    ln -s /mnt/biodata/galaxy /bcbio-data/galaxy && \
```
Then it'll be a standard bcbio installation and not try to do the merging steps which mess up the resolution in your case. Hope this fixes it for you.

**Comment by sib-bcf** [comment]
Thank you Brad, it works!

I didn't realize that the dockerfile was written to run together with the bcbio_vm.py wrapper. 

I'm thinking about still having the `bcbio_system.yaml` in a configuration directory like `config.system`, and a link to it from the `galaxy` directory. In this way, I can still do separate installation of the tools and the reference data. What do you advice?   

In any case, the exercise gave me some insight on the internal work of the scripts :)

**Comment by chapmanb** [comment]
Paolo;
Having a symlinked configuration would work without any problems as well, although just not moving to `config/bcbio_system.yaml` should allow you to separate tools and reference data. The `config` directory setup is really just to signal that we're inside a Docker container running by bcbio_vm and can merge externally specified memory and core usage information. Glad this got it working for you.
