### ISSUE TITLE
Optimising Bcbio running time.

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1400]
Hi Brad;

Sorry for the too general title name I couldn't name it well. I have couple questions related optimising bcbio running time.

1) Our HPC has two two queues for running processes ( short/long). The difference is in short you can only run a process with 2 hours then it will be killed. Since bcbio has a continue option, I thought that I can run it for 2 hour repetitions. I am trying to increase the number of the cores as many as I can get.
- Will I loose data ?
- Is this feasible ?
- For example, If a mutation calling process will not finish within this interval, will it start over ? or continue from where it was left of ?

2) bcbio vm has a module where I can get information about timigs of the individual steps? Can I get that information bcbio single machine one? Also, I would like to obtain information about mutation callers timings', But when I check it from the bcbio-log, I got confused. 

I tried ``` cat bcbio-log.txt | grep Timings ``` This game information related to whole variant calling process. So, where should I look ? (Alternatively, i tried to subtract time difference of the last and the first file of any caller.) 

3) We have many number of nodes in our server.( I apologise for my ignorance in terminology). For example there are two nodes with have 16 cores each and I need 16 cores for my process. Sometimes, I may not get 16 cores from a single machine so our queuing system has a mode where it gathers from the other nodes. So in this case say 8 from node1 and 8 from node2. Will bcbio run in this situation without ipython option ? Should I set up an ipython module for this ?

Thank you for all of your valuable information,

Have a nice week,

Best regards,

Tunc.

**Comment by roryk** [comment]
Hi Tunc,

The short queue plan won't work too well; bcbio-nextgen can restart where it left off, but only if it completes a step which is measured by whether or not the full file for that step was created. 

The `Timing` entries are at the level of the step, the machine specific timings aren't available. The logging output for status messages for tools have the machine in the name. I'm a little confused by the calling mutations and variant calling distinction you're making but I think they are the same thing. For the calling of the actual variants the timing will be labelled `variant calling`.

For a local run all the cores need to be on the same machine-- if they need to be spread across machines then using ipython gets that going. Each IPython engine requests cores on a single machine, so if you passed `-n 32` to the bcbio_nextgen.py script and your machines have 16 cores and you have the `cores` options in your `bcbio_system.yaml` file set to 16, then you'll get for steps that can use the 16 cores two engines each on 16 core machines taking up all the cores.

Hope that helps, Brad probably has some suggestions too.

**Comment by chapmanb** [comment]
Thanks Rory -- that's all right on. Tunc, for the variant timing you can't get separate runtimes for individual callers if you're running multiple at the same time. The runs for each tools happen concurrently so there is currently not an easy way to separate the time spent on each. If you need this information you need to run a single caller independently in a run. Hope this helps.

**Comment by mortunco** [comment]
Thank you for the valuable information.
