### ISSUE TITLE
installation in existing conda env

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1401]
Hi Brad,

We'd like to implement bcbio at our institution to automate some of our data processing. In our cluster environment, all packages and tools are installed using conda in a default env.

Since the automated install script tries to install another miniconda instance, this is no option for us. 
I've already created a conda env for bcbio, and followed the instructions in the manual for a "local/private bcbio installation". However, the last step is a bit unclear for me. The manual says to symlink all executables in `path-to-bcbio/anaconda/bin/` to the created conda env, but by following the steps in the manual, there is no such directory.

Could you clarify what's the purpose of this last step? I thought all dependencies were already installed in the conda env in a previous step?

Thanks
M

**Comment by matthdsm** [comment]
also, how do I install the requisite tools? since the bcbio_nextgen_install.py is used to install the aligners etc, I don't suppose this is an option? using the bcbio_nextgen.py script with the upgrade option also doensn't work.

Thanks
M

**Comment by roryk** [comment]
Hi @matthdsm,

Brad might have a better suggestion, but I'd recommend installing it completely separately, miniconda and all, and then just sticking a link to the bcbio_nextgen.py from that install into the systemwide conda that everyone is using.
