### ISSUE TITLE
small rna seq (multiqc error)

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1402]
> [2016-05-24T04:37Z] summarize variants
> [2016-05-24T04:37Z] Run multiqc
> [2016-05-24T04:37Z] [INFO   ]         multiqc : This is MultiQC v0.6
> [2016-05-24T04:37Z] [INFO   ]         multiqc : Searching 'trimmed'
> [2016-05-24T04:37Z] [WARNING]         multiqc : No analysis results found. Cleaning up..
> [2016-05-24T04:37Z] [INFO   ]         multiqc : MultiQC complete
> Traceback (most recent call last):
>   File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 226, in <module>
>     main(**kwargs)
>   File "/BiO/BioTools/bcbio/tools/bin/bcbio_nextgen.py", line 43, in main
>     run_main(**kwargs)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 43, in run_main
>     fc_dir, run_info_yaml)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 328, in smallrnaseqpipeline
>     samples = qcsummary.generate_parallel(samples, run_parallel)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 26, in generate_parallel
>     samples = run_parallel("multiqc_summary", [samples])
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
>     return run_multicore(fn, items, config, parallel=parallel)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
>     for data in joblib.Parallel(parallel["num_jobs"])(joblib.delayed(fn)(x) for x in items):
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 800, in __call__
>     while self.dispatch_one_batch(iterator):
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 658, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 566, in _dispatch
>     job = ImmediateComputeBatch(batch)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 180, in __init__
>     self.results = batch()
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
>     return apply(f, *args, **kwargs)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 140, in multiqc_summary
>     return multiqc.summary(*args)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/qc/multiqc.py", line 51, in summary
>     shutil.move(os.path.join(tx_out, "multiqc_report.html"), out_file)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/shutil.py", line 302, in move
>     copy2(src, real_dst)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/shutil.py", line 130, in copy2
>     copyfile(src, dst)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
>     with open(src, 'rb') as fsrc:
> IOError: [Errno 2] No such file or directory: '/BiO/BioProjects/Project/Project-merged/work/tx/tmpvM20wC/multiqc_report.html'

Can you check this error in small rna seq workflow?

**Comment by hmkim** [comment]
```
 42     # Back compatible -- to migrate to explicit specifications in input YAML
 43     folders += ["trimmed", "htseq-count/*summary"]
 44     if not utils.file_exists(out_file):
 45         with utils.chdir(work_dir):
 46             input_dir = " ".join([_check_multiqc_input(d) for d in folders])
 47             if input_dir.strip():
 48                 cmd = "{multiqc} -f {input_dir} -o {tx_out} {opts}"
 49                 with tx_tmpdir(data, work_dir) as tx_out:
 50                     do.run(cmd.format(**locals()), "Run multiqc")
 51                     shutil.move(os.path.join(tx_out, "multiqc_report.html"), out_file)
 52                     shutil.move(os.path.join(tx_out, "multiqc_data"), out_data)
 53     out = []
```
When I block the line of 51, 52, I finished job.

Why don't have the result of multiqc? Anyway, in case of this need the passing of this step.

**Comment by lpantano** [comment]
Hi,

sorry about that. Not sure why you don't have any results. Can you update to  development version, including tools? 

Multiqc should at least have the fastqc output. It there should  be a fastqc folder inside qc in the working directory. Do you have that?

**Comment by roryk** [comment]
This has happened to me as well, but restarting it fixed it. I'm not sure if the fix was due to updating the code to the development version or rerunning it, though.

**Comment by hmkim** [comment]
Yeah, I think too @roryk 
@lpantano I always keep to updating to development version including tools.

I restart the workflow but no fixed it.

With this config,
> details:
> - algorithm:
>     adapters:
>     - TGGAATTCTCGGGTGCCAAGG
>     aligner: star
>     species: mmu
>   analysis: smallRNA-seq
>   description: PK 1
>   files:
>   - /BiO/BioProjects/Project/T1.fastq.gz
>   genome_build: mm10
>   metadata:
>     type: PK
> - algorithm:
>     adapters:
>     - TGGAATTCTCGGGTGCCAAGG
>     aligner: star
>     species: mmu
>   analysis: smallRNA-seq
>   description: PI 1
>   files:
>   - /BiO/BioProjects/Project/T2.fastq.gz
>   genome_build: mm10
>   metadata:
>     type: PI
> ...
> fc_date: '2016-05-23'
> fc_name: TBD160209-merged
> upload:
>   dir: upload

In my work directory, there is no qc directory.
```
work $ ls
align  checkpoints_parallel  inputs  log  mirbase  mirdeep2  multiqc  project-summary.yaml  provenance  report  rna.ps  seqcluster  trimmed  trna  tx  upload
```

**Comment by lpantano** [comment]
Did you update before re-starting? we are doing a lot of work in the QC the last weeks and I want to make sure there wasn't a temporal bug.

If you get this error with the last development, can you send me the LOGs file please? maybe I can see something.

sorry about the issues.

**Comment by hmkim** [comment]
When I update with the last development, it has no problem.

Thanks,
