### ISSUE TITLE
Clustering in small rna report

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1404]
Below, this is code in small rnaseq workflow.

### Clustering
```{r mirna-clustering, eval=ismirbase}
counts = counts(obj)
dds = DESeqDataSetFromMatrix(counts[rowSums(counts>0)>3,], colData=design, design=~1)
vst = rlog(dds)

pheatmap(assay(vst), annotation_col = design, show_rownames = F, 
         clustering_distance_cols = "correlation",
         clustering_method = "ward.D")
```

When I running the report script with my data, I got the error in R.

> dds = DESeqDataSetFromMatrix(counts[rowSums(counts>0)>3,], colData=design, design=~1)
converting counts to integer mode
> vst = rlog(dds)
Error in estimateSizeFactorsForMatrix(counts(object), locfunc = locfunc,  : 
  every gene contains at least one zero, cannot compute log geometric means

![2016-05-26 13 41 54](https://cloud.githubusercontent.com/assets/4966343/15563860/a787330a-2347-11e6-9a5b-986862ae8875.png)

**Comment by lpantano** [comment]
Hi,

sorry about that. But it seems your data is not as expected. DESeq2 will need to have rows where at least all sample has some values, other wise can not normalize. It seems you have very few reads are annotated, and that is a warning for problems in the library preparation and I don't know how much we can trust those numbers.

I don't think the report will work with this data. What would you want to do with that? I only can think of using edgeR instead, maybe it has less restriction. But, as I said, I don't know how much you can trust this in the sense that don't know if those numbers reflect really the real expression.

But, you will need to code yourself because this isn't an expected miRNA data set.

hope this help.

**Comment by lpantano** [comment]
You can try to change this line in case that help:

`dds = DESeqDataSetFromMatrix(counts, colData=design, design=~1)`

**Comment by roryk** [comment]
You can calculate your own version of the geometric means that will get around this error and set the size factors manually:
```
geoMeans = apply(counts, 1, function(row) if (all(row == 0)) 0 else
                 exp(mean(log(row[row != 0]))))
dds = estimateSizeFactors(dds, geoMeans=geoMeans)
```

**Comment by hmkim** [comment]
@lpantano Thanks for your comment. I'll try to analyze with edgeR.
@roryk Thanks for your reply.  I'll try it.

**Comment by hmkim** [comment]
```
> head(assay(vst))
                    B-332      B-340     B-344     B-362      B-371        B-375     B-376
hsa-let-7a-2-3p  2.341578  1.3727496  1.420016  1.893527  1.5568376 -0.001161153  0.815964
hsa-let-7a-3p   10.791047 10.3270608 10.842259 11.098459 11.2003986 10.935129696 10.721029
hsa-let-7a-5p   18.926544 17.9083707 18.530504 18.076433 19.6061448 18.777105616 17.943720
hsa-let-7b-3p   11.089317 10.1167183 11.483489 11.167033 11.5732016 10.766074796 10.496683
hsa-let-7b-5p   16.251453 15.2663444 16.313983 15.966429 17.0895321 16.502040499 15.324242
hsa-let-7c-3p    6.634920  0.3977725  1.178295  3.463485  0.6571737  0.457471697  1.229257
                      B-379     B-407      B-408      B-442      B-444     B-449     B-513
hsa-let-7a-2-3p -0.00500646  2.211619  0.6834753  0.5450910  0.1147926  1.894183  1.597481
hsa-let-7a-3p   10.90810460 10.728484 10.5837025 10.7590746 11.1143354 10.300482 10.798222
hsa-let-7a-5p   19.17100836 18.079088 18.4104564 18.4143518 18.8651266 19.065348 18.188016
hsa-let-7b-3p   11.11222578 10.523866 10.6820384 10.3241710 10.5683958 10.897570 10.492906
hsa-let-7b-5p   16.66470932 15.898820 15.9697339 15.7217689 16.1664212 16.136493 15.982578
hsa-let-7c-3p    0.45221174  2.019025  1.7308893  0.9342329  0.6145399  4.977081  2.142039
                     B-570     B-585       B-612      B-613      B-614     B-633     B-644
hsa-let-7a-2-3p  1.0748688  1.234150 -0.05885191 -0.1310145 -0.1310858  2.100481  2.193966
hsa-let-7a-3p   11.2482008 10.978136 10.67891571 10.9779511 10.8166571 11.508798 10.564941
hsa-let-7a-5p   18.6875037 18.063877 18.42041066 18.6451934 18.5005942 18.552671 18.156141
hsa-let-7b-3p   11.3122771 10.462373 10.35812006 10.9530461 10.2835952 10.446914  9.996429
hsa-let-7b-5p   16.5160570 15.193941 16.20156437 16.4666535 15.9177237 15.962268 15.449748
hsa-let-7c-3p    0.3985822  2.506486  0.37809520  0.2770982  0.2769972  1.936219  4.343858
                      B-662     B-667    BS-667     BT-278       BT-287     BT-301      BT-309
hsa-let-7a-2-3p -0.04398344  1.185983  2.151094  0.1627322  0.001236821 -0.1271673 -0.06360384
hsa-let-7a-3p   10.95741838 10.763450 10.621095 11.4081627 11.442557212 11.0642787  9.97719262
hsa-let-7a-5p   19.03946923 18.851025 18.452473 19.3232366 19.346139725 18.6002639 19.34781203
hsa-let-7b-3p   11.30908772 10.525738 10.198294 11.6657409 11.376736244 11.1507371 10.99785521
hsa-let-7b-5p   16.55239899 16.292041 15.880261 17.0987179 16.967461790 16.3982084 16.45860994
hsa-let-7c-3p    0.39865342  3.327487  2.607207  2.0616566  2.189548578  1.5535574  1.45322384
                    BT-312     C-359     C-362     C-368     C-369
hsa-let-7a-2-3p -0.2212989  2.832719  3.061427  2.383292  2.040646
hsa-let-7a-3p   10.5701870 10.730067 10.738789 10.795776 10.651851
hsa-let-7a-5p   18.2680715 18.527916 18.578039 18.945795 18.523040
hsa-let-7b-3p   10.0617485 10.025657 10.541703 10.357888 10.314145
hsa-let-7b-5p   15.7649021 15.829922 16.446595 16.292001 15.796748
hsa-let-7c-3p    0.1469735  4.009235  4.371326  4.543349  3.528750

> pheatmap(assay(vst), annotation_col = design, show_rownames = F,
+ clustering_distance_cols = "correlation",
+ clustering_method = "ward.D")
Error in cut.default(a, breaks = 100) : 'x' must be numeric
```

Can you check this error?

> Error in cut.default(a, breaks = 100) : 'x' must be numeric

**Comment by lpantano** [comment]
Hi,

can you pase the design matrix? 

if only contains one column with the same values or the row names are not the same than the column names from the matrix, normally throws this error.

thanks for helping debugging this.

**Comment by hmkim** [comment]
> head(design)
       type batch phenotype
B-332  MIBC  None        NA
B-340  MIBC  None        NA
B-344 NMIBC  None        NA
B-362  MIBC  None        NA
B-371 NMIBC  None        NA
B-375 NMIBC  None        NA

**Comment by lpantano** [comment]
Hi @hmkim,

yes, normally you have different names for each columns. I would do `design[,"type",drop=FALSE]. You would need to do this for all the cases pheatmap is in the code.

cheers

**Comment by hmkim** [comment]
Yeah! I recognized it.

Thanks @lpantano
