### ISSUE TITLE
bcbio parallel doesn't get correct hostname

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1406]
Hi,

when trying to run a parallel analysis using iPython on our torque cluster, I get the following message
```
Cannot resolve a local IP address that isn't 127.0.0. Your machines might not have a local IP address assigned or are not able to resolve it.
```

run command is 
```
bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml -t ipython -n 8 -s torque -q default 
```

output for `python -c 'import socket; print socket.gethostbyname(socket.gethostname())'  ` is `127.0.0.1`, which seems to be correct.
However, I noticed the check in `bcbio-nextgen/bcbio/log/__init__.py` uses this
```
if parallel_type == "ipython":
        ips = [ip for ip in socket.gethostbyname_ex(socket.gethostname())[2]
               if not ip.startswith("127.0.0")]
        if not ips:
            sys.stderr.write("Cannot resolve a local IP address that isn't 127.0.0. "
                             "Your machines might not have a local IP address "
                             "assigned or are not able to resolve it.\n")
            sys.exit(1)
```

which returns no output on our system.
Is this a bug of am I missing something? I suppose by editing the command to resemble to one in the manual would fix this, but I'd like to hear from you before I go muddling about.

Thanks!
M

**Comment by chapmanb** [comment]
Matt;
For the parallel runs to work, bcbio/IPython needs to be able to find a local address that is not 127.0.0.1. That only lets a machine talk to itself. We need to get the internal networking IPs that let machines talk to each other within your network so the engines can contact the controller. There is more detail in the documentation here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#troubleshooting

Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad,

I went through the manual, and edited all required files, but to no avail. I'm still getting the same error message. It's possible to ssh between our submission and compute nodes using the hostname, so I don't really think there's an issue there.

Any more ideas?

Thanks!
M

**Comment by chapmanb** [comment]
Matt;
Sorry you're still stuck on this. Could you provide more details on the contents of `/etc/hosts` after editing it? Can you ssh to the same machine using the hostname (as opposed to localhost)? bcbio/IPython should be resolving IPs in the standard way that most other applications do, so I'm not sure why it's having trouble finding it's own host name. Happy to help more but we'll probably need more details about your system to provide more clues as all the general tips we know are in the documentation.
