### ISSUE TITLE
Duplicate removal should use the globally configured temporary directory

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1409]
It looks like it writes inside on the `work` directory instead for temporary files.

**Comment by chapmanb** [comment]
Luca -- thanks for the report. Which command line is running (from `log/bcbio-nextgen-commands.log`) when you're seeing temporary files in the work directory? There are a few different methods to de-duplicate depending on the input files and on a quick read of the code they appear to use the temporary directory. If I could focus on the place you're seeing issues happy to try and debug further. Thanks much.

**Comment by lbeltrame** [comment]
I've found another occurrence of this during sv calling, when split and discordant reads are handled. Example command (notice that all temporary dirs are in `/storage/rozo`, while my path is configured elsewhere for temporary directories):

```
/storage/rozo/bcbio/anaconda/bin/samtools sort -n -@ 7 -m 682M -O sam -T /storage/rozo/projects/OV-223/ov223-final/work/tx/tmpJwI0MO/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-namesort /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup.bam | /storage/rozo/bcbio/anaconda/bin/samblaster --addMateTags -M --splitterFile >(/storage/rozo/bcbio/anaconda/bin/samtools sort -@ 7 -m 682M -T /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/tx/tmp1iw6xJ/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-dedup-sorttmp-spl -o /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/tx/tmps56WvI/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-sr.bam /dev/stdin) --discordantFile >(/storage/rozo/bcbio/anaconda/bin/samtools sort -@ 7 -m 682M -T /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/tx/tmp1iw6xJ/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-dedup-sorttmp-disc -o /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/tx/tmplrnQEc/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-disc.bam /dev/stdin) | /storage/rozo/bcbio/anaconda/bin/samtools view -b -S -u - | /storage/rozo/bcbio/anaconda/bin/sambamba sort  -t 7 -m 682M --tmpdir /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/tx/tmp1iw6xJ/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-dedup-sorttmp-full -o /storage/rozo/projects/OV-223/ov223-final/work/bamclean/LC0044_R-OV-MNOD/tx/tmp1iw6xJ/LC0044-R-OV-MN-ready-reorder-fixrgs-gatkfilter-dedup-dedup.bam /dev/stdin
```

**Comment by chapmanb** [comment]
Luca;
Sorry about the issues. I can't replicate this with our test cases -- they appear to do the right thing with respect to the temporary directory. Could you provide more detail about your input YAML and how you define the temporary directories? Perhaps this is some sort of issue wtih the specification we can resolve. Thanks much.

**Comment by lbeltrame** [comment]
Does `tmp` need to be defined *inside* the `resources` section in the `bcbio_system.yaml` file?

**Comment by chapmanb** [comment]
Luca -- that's exactly right:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#temporary-directory

**Comment by lbeltrame** [comment]
Well, as embarrassing as it may seem, my indentation was off and the `tmp` field was on the wrong level. Adjusted and now works. Thanks and sorry for the noise!
