### ISSUE TITLE
Error with supply sufficent memory to run GATK indel realigner

### ISSUE THREAD

**Issue by kevjp** [chapmanb/bcbio-nextgen#1411]
Hi

I am running into an issue with providing sufficient memory to run the indel realignment step:

``` bash
 java -Xms681m -Xmx1g -XX:+UseSerialGC -Djava.io.tmpdir=/home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/tx/tmp78ZE5G -jar /usr/local/share/bcbio/toolplus/gatk/3.5-0-g36282e4/GenomeAnalysisTK.jar -T IndelRealigner -I /home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/bamprep/Pool3_indel_sort_x1000Total_GATK_HC/X/Pool3_indel_sort_x1000Total-reorder-fixrgs-gatkfilter-X_93113273_108631036-prep-prealign.bam -R /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -targetIntervals /home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/bamprep/Pool3_indel_sort_x1000Total_GATK_HC/X/Pool3_indel_sort_x1000Total-reorder-fixrgs-gatkfilter-X_93113273_108631036-prep-prealign-realign.intervals -L X:93113274-108631036 --knownAlleles /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation/Mills_and_1000G_gold_standard.indels.vcf.gz -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /home/kevin/Documents/NGS_Pipeline/INDELanalysis/AmpliconIndel20x-100x160527/validation/work/bamprep/Pool3_indel_sort_x1000Total_GATK_HC/X/tx/tmpM_qqKV/Pool3_indel_sort_x1000Total-reorder-fixrgs-gatkfilter-X_93113273_108631036-prep.bam
```

The error I am getting is:

```
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A USER ERROR has occurred (version 3.5-0-g36282e4): 
##### ERROR
##### ERROR This means that one or more arguments or inputs in your command are incorrect.
##### ERROR The error message below tells you what is the problem.
##### ERROR
##### ERROR If the problem is an invalid argument, please check the online documentation guide
##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
##### ERROR
##### ERROR Visit our website and forum for extensive documentation and answers to 
##### ERROR commonly asked questions http://www.broadinstitute.org/gatk
##### ERROR
##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
##### ERROR
##### ERROR MESSAGE: An error occurred because you did not provide enough memory to run this program. You can use the -Xmx argument (before the -jar argument) to adjust the maximum heap size provided to Java. Note that this is a JVM argument, not a GATK argument.
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
```

I noticed that from previous versions of the pipeline you had this step running with more memory allocated:

``` java -Xms454m -Xmx3181m -XX:```

**Comment by chapmanb** [comment]
Kevin;
Sorry about the issue. The memory option here is taken from your bcbio_system.yaml file. By default it should be set to 3500m, which scaled down for system memory is likely what you saw before:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/bcbio_system.yaml#L40

Did you adjust this or make other changes on the update/install? Hope this helps

**Comment by kevjp** [comment]
Hi Brad
I have a file called bcbio_system.yaml.bak2016-05-29-22-48-36 which has the correct settings i.e.
```
gatk:
    jvm_opts: ["-Xms500m", "-Xmx3500m"] 
```
 
This file is located at /usr/local/share/bcbio/galaxy.
There is also another file in the same folder called bcbio_system.yaml which points to where the GenomeAnalysisTK.jar files is stored. The way I installed GATK was I  simply downloaded and unzipped the latest version and then i made the jar available to bcbio-nextgen with:

```
 bcbio_nextgen.py upgrade --tools --toolplus gatk=/path/to/gatk/GenomeAnalysisTK.jar
```

Thanks for responding so quickly.

Kevin

**Comment by chapmanb** [comment]
Kevin;
Apologies for the problem, this was a bug in how we were adding in the jar directory information. It was incorrectly removing existing specifications, so removed the jvm_opts memory specification. I pushed a fix to avoid this on future upgrades, but the quick fix for your case is to edit your bcbio_system.yaml file to add the `jvm_opts` specification from above back into the `gatk` section. Thanks for helping track this down and sorry again about the problem.

**Comment by kevjp** [comment]
Brad 
I also noticed that there is no reference to haplotype caller in either of my config files 
ie.

```
gatk-haplotype:
    jvm_opts: ["-Xms500m", "-Xmx3500m"]
```
so perhaps I need to upgrade to your latest development version.  What do you suggest?

Thanks

Kevin

**Comment by chapmanb** [comment]
Kevin;
You don't strictly need that unless you want to specify different memory for HaplotypeCaller and other GATK programs. This option used to be more useful since HaplotypeCaller used a lot of memory, but recent versions are more efficient so we removed it from the defaults. If you don't specify it, bcbio will pick up and use the memory from the general `gatk` option. Hope this helps.

**Comment by kevjp** [comment]
Great I updated my bcbio_system.yaml so it now reads as:

```
gatk:
    dir: /usr/local/share/bcbio/toolplus/gatk/3.5-0-g36282e4
    jvm_opts:
    - -Xms500m
    - -Xmx3500m
```

So hopefully it will be ok now. Thanks for pushing the fix.

Kevin
