### ISSUE TITLE
Pipeline fails in prep_align_input stages when directories contain spaces

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1413]
This was not intentional, but at a time, someone created a result folder for the sequencer which included spaces. When running a new analysis, it bombed right in `prep_align_inputs`:

```
exceptions from call to method: prep_align_inputs
[Engine Exception]CalledProcessError: Command 'set -o pipefail; gunzip -c /storage/miseq_data/sequencing_storage/OV.225 1_2 DNA/fastq/21506_blood_S3_L001_R1_001.fastq.gz | /opt/bcbio/galaxy/../anaconda/bin/pbgzip -n 8  -c /dev/stdin > /scratch/bcbiotx/a71b7929-3f32-4091-9671-d5c0fb30ba9e/tmp63qHDL/21506_blood_S3_L001_R1_001.fastq.gz
gzip: /storage/miseq_data/sequencing_storage/OV.225.gz: No such file or directory
```

I already told the relevant people not to use spaces in the directories. ;) But I guess these commands should be shell-escaped to prevent this?

**Comment by lpantano** [comment]
Hi @lbeltrame 

I remember we did something to avoid this while ago. 

Please, let us know if you still find further issues with this.

cheers
