### ISSUE TITLE
sambamba error

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1415]
Hi Brad and others,

Recently for one particular sample bcbio fails with an error for sambamba. It complains about a file missing in a particular location but when I go to that specified directory I find the file existing there. Can you pelase help me to figure out what is causing this error?

Attached is the bcbio.stderr file.

Thanks,

Diya
[bcbio.stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/293934/bcbio.stderr.txt)

**Comment by lpantano** [comment]
Hi Diya,

sorry about that. I tried to look for an error in that file, but actually the last line says bcbio finished good. Can you find the line where sambamba is failing?

thanks

**Comment by DiyaVaka** [comment]
[bcbio.stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/294161/bcbio.stderr.txt)

Can you see the error in this file?

**Comment by lpantano** [comment]
Hi,

I see it. What version of bcbio are you running? Normally is related to headers in the BED file. We try to clean it, but maybe it is some other thing we didn't think about it. 

Do you have any header in the BED file?

**Comment by DiyaVaka** [comment]
here is the header of the bed file

track name=target_region description="Target Regions"

**Comment by lpantano** [comment]
There is some code trying to remove that, so I don't know exactly why is nor working. Maybe is the bcbio version.

One solution is to remove that from the BED file and restart. 

If you are using the last bcbio stable version, bcbio should do it alone, and I would need to try to reproduce first.

Any chance you can modify the file and re-start?

**Comment by DiyaVaka** [comment]
I did restart the job after cleaning the bed file by having only three columns chr#, start and stop. Looks like its working. Thank you for responding quickly and giving a solution.

**Comment by DiyaVaka** [comment]
Hi Ipantano,

After we upgraded our bcbio stable to development version, I am getting error message with sambamba, This time its not complaining about the bed file. but it says its not able to map.

Can you look at the err file and suggest how to fix it?
[bcbio_err.txt](https://github.com/chapmanb/bcbio-nextgen/files/391151/bcbio_err.txt)

**Comment by lpantano** [comment]
Hi,

sorry about that. 
Can you run this command alone to see if we can get a better idea of the error?

`/mnt/speed/qc/sequencing/bcbio/anaconda/bin/sambamba depth region -F "not unmapped" -t 1 -C 1000 -T 1 -T 5 -T 10 -T 20 -T 40 -T 50 -T 60 -T 70 -T 80 -T 100 -L /mnt/speed/qc/sequencing/ihg-pipeline/Sample_P3-T-04066233T/bedprep/cov-SeqCap_EZ_Exome_v3_primary.bed /mnt/speed/qc/sequencing/ihg-pipeline/Sample_P3-T-04066233T/align/P3-T-04066233T/P3-T-04066233T-sort.bam | sed 's/# chrom/chrom/' > P3-T-04066233T_coverage.bed`

**Comment by DiyaVaka** [comment]
It did run normally. Not sure why is it not going through bcbio setup

**Comment by lpantano** [comment]
Maybe you can try to give more memory to sambamba?

Did you look into your log files for the jobs? 

I just push a fix to allow control the memory for sambamba, so you can add this tool into your bcbio_system.yaml or you can modify samtools, and increase the memory. 

I have no other idea for now, but will continue trying to reproduce this.

**Comment by DiyaVaka** [comment]
Hi Ipantano,

I tried doing both adding sambamba to system.yaml and also increasing the memory of the samtools still no luck.

Thanks,

Diya

**Comment by lpantano** [comment]
sorry we still have problems.

What about run it in single core? just bcbio-nextgen.py config_file.yaml, maybe we get the error related to bcbio.

**Comment by DiyaVaka** [comment]
Just to double check is it bcbio-nextgen.py system.yaml instead of config_file.yaml?

**Comment by lpantano** [comment]
oh, I meant just run bcbio in since core: 

bcbio_nextgen.py /mnt/speed/qc/sequencing/ihg-pipeline/Sample_P3-T-04066233T/sample.yaml

**Comment by DiyaVaka** [comment]
It died again with the same error.

**Comment by lpantano** [comment]
sorry I am totally lost here. sorry.
When you ran it alone that command how much memory you used for this? like you put some limit or it could use all memory you have in the node.
In the log I see the limit is 10G, then I don't know how much memory you set up in the previous test. Any mismatch between what bcbio command could use and what sambamba used when it ran as a separated command without error?

**Comment by DiyaVaka** [comment]
Rerunning it as bcbio_nextgen.py /mnt/speed/qc/sequencing/ihg-pipeline/Sample_P3-T-04066233T/sample.yaml worked. Not sure why it did not work the first time and passed the second time.  It was given exactly the same way both the times.

**Comment by chapmanb** [comment]
Lorena and Diya;
I think you may have been running into this non-deterministic sambamba issue:

https://github.com/lomereiter/sambamba/issues/223#issuecomment-237816534

I think we're currently stuck on this without a better way to reproduce. The two practical suggestions currently are to re-run or avoid using realignment (the new default as of 0.9.9) to work around the problem. Hope this explains what you're seeing.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue and the original issue form sambamba is closed.

Come back if you find other issues  or want to continue with this one.

cheers
