### ISSUE TITLE
small RNA-seq: a problem with TAIR10 genome setup

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1416]
Dear colleagues,

I set up A.thaliana for small rna analysis:
bcbio_nextgen.py upgrade --genomes TAIR10 --datatarget smallrna 
and I saw no mirbase in the bcbio/genomes/Athaliana/TAIR10

When I run the analysis it could not find mirbase (obviously).

I tried to install A.thaliana as a custom genome, but it did not allow me,
because A.thaliana is in the list.

Please help!
SN

**Comment by lpantano** [comment]
Hi,

Can you send the error? because it should skip creating folders if they exists. If you send me the command you used for the custom genome creation and the error, I can further debug.

Meanwhile, I will modify the script to allow addition of smallrna data. 

I will like to add the annotation to the genome by default, can you point me to the files you were using as srna_gtf? I can add the miRBase related files.

thanks

**Comment by naumenko-sa** [comment]
Hi,
I use reference and annotation from
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000001735.3_TAIR10/
and microRNA from
ftp://mirbase.org/pub/mirbase/CURRENT/genomes/ath.gff3
(I've converted gff3 to gtf)

The command
```
bcbio_setup_genome.py -f $APATH/GCF_000001735.3_TAIR10_genomic.fna \
  --gff3 -g $APATH/GCF_000001735.3_TAIR10_genomic.gff -n athaliana -b TAIR10 --mirbase ath -i star\ 
 --srna_gtf $APATH/ath.gtf -c 5
```
gives an error
```
Traceback (most recent call last):
  File "/home/naumenko/work/tools/bin/bcbio_setup_genome.py", line 237, in <module>
    args.gtf = gff3_to_gtf(args.gtf)
  File "/home/naumenko/work/tools/bin/bcbio_setup_genome.py", line 54, in gff3_to_gtf
    _output_ncbi_gff3(gff3_file, out_file, dialect)
  File "/home/naumenko/work/tools/bin/bcbio_setup_genome.py", line 74, in _output_ncbi_gff3
    db = gffutils.create_db(gff3_file, ":memory:", id_spec=id_spec)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 1273, in create_db
    c.create()
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 488, in create
    self._populate_from_lines(self.iterator)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 571, in _populate_from_lines
    fixed, final_strategy = self._do_merge(f, self.merge_strategy)
  File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/gffutils/create.py", line 218, in _do_merge
    raise ValueError("Duplicate ID {0.id}".format(f))
ValueError: Duplicate ID APS2
```
I'm not sure what it complains about.

**Comment by naumenko-sa** [comment]
Also if I am not using micro-RNA gtf in the bcbio_setup_genome.py --srna_gtf parameter, and instead would feed it with the genome annotation (in the docs it is written that it is possible), would it download miRNA annotation from MIRbase using mirname?

**Comment by lpantano** [comment]
Hi,

it wont actually work like that. But i will work in the custom genome script to allow better addition of the srna data.

Meanwhile, can you update your data? It should download the new annotation and update the resources file.

cheers

**Comment by naumenko-sa** [comment]
It seems that it is not working
```
 bcbio_nextgen.py upgrade -u development --data --genomes TAIR10 --datatarget smallrna
```
File seq/TAIR10-resources.yaml is updated,
but there is no srnaseq folder in the bcbio/genomes/Athbaliana/TAIR10

**Comment by lpantano** [comment]
sorry, I forgot to push another file. Can you try again, and make sure to remove any temporal folder bcbio download for the installation. 

I hope this time works.

**Comment by naumenko-sa** [comment]
Thanks a lot, now the srnaseq folder is populated.
