### ISSUE TITLE
bedtools/pybedtools version problem

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1419]
Hi!

When testing the [cineca-fix](https://github.com/roryk/ipython-cluster-helper/tree/cineca-fix) branch of ipython cluster helper I get the following error, after installing a brand new stable version of bcbio:

<pre>
[2016-06-06T13:09Z] node019: bedtools groupby coverage: Y : LUAD_7763_01A_TP-sort.bam
[2016-06-06T13:09Z] node014: Unexpected error
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 187, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 184, in postprocess_alignment
    callable.block_regions(bam_file_ready, ref_file, data)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/bam/callable.py", line 338, in block_regions
    if len(ref_regions.subtract(nblock_regions, nonamecheck=True)) > 0:
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 773, in decorated
    result = method(self, *args, **kwargs)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 203, in not_implemented_func
    raise NotImplementedError(help_str)
NotImplementedError: "subtractBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.

</pre>

There is only one bedtools in the path, the one installed by bcbio, so I was wondering what might be the source of error.

<pre>
[node002 log ]$ type -all bedtools
bedtools is /pico/home/userexternal/esebesty/work/bcbio/tool/bin/bedtools
</pre>

Any ideas?

**Comment by chapmanb** [comment]
Endre;
That's unexpected, it seems like something is wrong with the bedtools installation. It's not likely a version issue as subtract has been around for a while. Does bedtools work?
```
/pico/home/userexternal/esebesty/work/bcbio/tool/bin/bedtools --version
/pico/home/userexternal/esebesty/work/bcbio/tool/bin/bedtools subtract -h
```
Sorry I'm not sure why you would see this but digging into the bedtools installation on your system is probably the best way to try and identify what is wrong. Hope this helps some.

**Comment by razZ0r** [comment]
bedtools seems to be ok:

<pre>
[node013 ~ ]$ /pico/home/userexternal/esebesty/work/bcbio/tool/bin/bedtools --version
bedtools v2.24.0
[node013 ~ ]$ /pico/home/userexternal/esebesty/work/bcbio/tool/bin/bedtools subtract -h

Tool:    bedtools subtract (aka subtractBed)
Version: v2.24.0
Summary: Removes the portion(s) of an interval that is overlapped
	 by another feature(s).

Usage:   bedtools subtract [OPTIONS] -a <bed/gff/vcf> -b <bed/gff/vcf>

</pre>

Maybe a pybedtools error?

**Comment by lpantano** [comment]
Hi @razZ0r,

Can you try this python code with bcbio python:
```
import pybedtools
a = pybedtools.example_bedtool('a.bed')
b = pybedtools.example_bedtool('b.bed')
c = a.subtract(b)
```

This works with my current installation of bcbio. Jut trying to isolate the problem.

thanks

**Comment by razZ0r** [comment]
Not working!

<pre>
[node013 bin ]$ ./python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pybedtools
>>> a = pybedtools.example_bedtool('a.bed')
>>> b = pybedtools.example_bedtool('b.bed')
>>> c = a.subtract(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 773, in decorated
    result = method(self, *args, **kwargs)
  File "/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/lib/python2.7/site-packages/pybedtools/bedtool.py", line 203, in not_implemented_func
    raise NotImplementedError(help_str)
NotImplementedError: "subtractBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.
>>>
</pre>

**Comment by lpantano** [comment]
ok, any chance you can try to update pybedtools, in case something happened?

use conda binary from bcbio installation:

`conda remove pybedtools`
`conda install pybedtools -c bioconda`

and try again the code?

**Comment by razZ0r** [comment]
Done, and still getting the same error message.

**Comment by lpantano** [comment]
Hi,

sorry about that. I don't know if you removed other package along pybedtools. 
I am thinking to update everything to default:

```
conda install pybedtools gemini metasv bcbio-nextgen -c bioconda
conda install -f bedtools -c bioconda
bcbio_nextgen.py upgrade -u stable --tools
```

if you are using development just change `stable` to development.

if that doesn't fix it, I think I cannot think of anything else. It happens in some other nodes? in the login node?

I am trying to reproduce, but everything is working.

**Comment by chapmanb** [comment]
Endre -- maybe this is too obvious, but is `/pico/home/userexternal/esebesty/work/bcbio/tool/bin` in your PATH when running these commands/tests?

**Comment by razZ0r** [comment]
Hmm, updated everything and now its working. Setting PATH was the first step when testing, so it shouldn't have been a problem. Anyway, the latest bcbio seems to work properly with pbspro, and I'm running a test sample pair on 32 CPUs/2 nodes right now.
