### ISSUE TITLE
Using bcbio's ensemble approach

### ISSUE THREAD

**Issue by mortunco** [chapmanb/bcbio-nextgen#1431]
Hi Brad,

I would like to ask if it is possible to use bcbio's ensemble approach with given vcf files as input without calling them with bcbio.

Best,

Tunc.

**Comment by chapmanb** [comment]
Tunc;
It is a standalone tool you can use outside of bcbio:

https://github.com/chapmanb/bcbio.variation.recall#ensemble

bcbio handles a lot of the VCF cleanup and other work to format things correctly, but as long as the inputs are well formed that hopefully will work for you.
