### ISSUE TITLE
[Cancer] The offending line was: "OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:"

### ISSUE THREAD

**Issue by hmkim** [chapmanb/bcbio-nextgen#1432]
> [2016-06-12T09:50Z] INFO  18:50:22,615 MicroScheduler -   -> 0 reads (0.00% of total) failing MappingQualityUnavailableFilter
> [2016-06-12T09:50Z] INFO  18:50:22,615 MicroScheduler -   -> 0 reads (0.00% of total) failing NotPrimaryAlignmentFilter
> [2016-06-12T09:50Z] INFO  18:50:22,615 MicroScheduler -   -> 3315 reads (0.14% of total) failing UnmappedReadFilter
> [2016-06-12T09:50Z] INFO  18:50:22,951 ProgressMeter -       16:130180          24472.0    60.0 s           40.9 m        0.4%     3.8 h       3.8 h
> [2016-06-12T09:50Z] ERROR 18:50:23,967 MuTect2 - Null qss at 220908
> [2016-06-12T09:50Z] INFO  18:50:24,173 ProgressMeter -     20:42080398          93371.0    60.0 s           10.7 m        0.3%     5.9 h       5.9 h
> [2016-06-12T09:50Z] INFO  18:50:24,534 GATKRunReport - Uploaded run statistics report to AWS S3
> [2016-06-12T09:50Z] tabix index syn6-Y_58896687_59373566.vcf.gz
> [2016-06-12T09:50Z] [E::get_intv] failed to parse TBX_VCF, was wrong -p [type] used?
> [2016-06-12T09:50Z] The offending line was: "OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:"
> [2016-06-12T09:50Z] /bin/bash: line 1: 74187 Segmentation fault      (core dumped) /BiO/BioTools/bcbio/data/anaconda/bin/tabix -f -p vcf /BiO/BioProjects/SomaticCaller-Benchmark/Analysis/set6/work/mutect2/Y/tx/tmpM3vaZh/syn6-Y_58896687_59373566.vcf.gz
> [2016-06-12T09:50Z] Uncaught exception occurred
> Traceback (most recent call last):
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
>     _do_run(cmd, checks, log_stdout)
>   File "/BiO/BioTools/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; /BiO/BioTools/bcbio/data/anaconda/bin/tabix -f -p vcf /BiO/BioProjects/SomaticCaller-Benchmark/Analysis/set6/work/mutect2/Y/tx/tmpM3vaZh/syn6-Y_58896687_59373566.vcf.gz
> [E::get_intv] failed to parse TBX_VCF, was wrong -p [type] used?
> The offending line was: "OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:"
> /bin/bash: line 1: 74187 Segmentation fault      (core dumped) /BiO/BioTools/bcbio/data/anaconda/bin/tabix -f -p vcf /BiO/BioProjects/SomaticCaller-Benchmark/Analysis/set6/work/mutect2/Y/tx/tmpM3vaZh/syn6-Y_58896687_59373566.vcf.gz
> ' returned non-zero exit status 139
> [2016-06-12T09:50Z] ERROR 18:50:24,961 MuTect2 - Null qss at 70868
> [2016-06-12T09:50Z] ERROR 18:50:24,962 MuTect2 - Null qss at 70870
> [2016-06-12T09:50Z] ERROR 18:50:27,514 MuTect2 - Null qss at 239253
> [2016-06-12T09:50Z] GATK: HaplotypeCaller
> [2016-06-12T09:50Z] OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
> [2016-06-12T09:50Z]    74192
> [2016-06-12T09:50Z] Try using the -Djava.io.tmpdir= option to select an alternate temp location.
> [2016-06-12T09:50Z]
> [2016-06-12T09:50Z] ERROR 18:50:29,362 MuTect2 - Null qss at 114492995
> [2016-06-12T09:50Z] ERROR 18:50:29,761 MuTect2 - Null qss at 114493151
> [2016-06-12T09:50Z] ERROR 18:50:30,171 MuTect2 - Null qss at 247760

Hi, All

When I analyzing the cancer data (Dream set), I got the error in above.

How can I handle the shared memory size in bcbio ?

**Comment by chapmanb** [comment]
Sorry about the issue. I'm not sure what happened here, bcbio already sets `java.io.tmpdir` to a the transactional work directory so this should have plenty of space unless your filesystem filled up during the run. So I don't know anything to do other than re-run this. It looks like the error unfortunately got spewed into the output file so if you remove the problem file:
```
rm -f /BiO/BioProjects/SomaticCaller-Benchmark/Analysis/set6/work/mutect2/Y/syn6-Y_58896687_59373566.vcf.gz
```
and re-start the analysis hopefully it will finish cleanly.

**Comment by hmkim** [comment]
I don't know why vcf file have this line.

> OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
>    17217
> Try using the -Djava.io.tmpdir= option to select an alternate temp location.
> 

```
brandon@tiger:/BiO/BioProjects/SomaticCaller-Benchmark/Analysis/set6/work/mutect2/9$ zcat syn6-9_81726081_100761107.vcf.gz | head
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   17217
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

##fileformat=VCFv4.2
##FILTER=<ID=alt_allele_in_normal,Description="Evidence seen in the normal sample">
##FILTER=<ID=clustered_events,Description="Clustered events observed in the tumor">
##FILTER=<ID=germline_risk,Description="Evidence indicates this site is germline, not somatic">
##FILTER=<ID=homologous_mapping_event,Description="More than three events were observed in the tumor">
##FILTER=<ID=multi_event_alt_allele_in_normal,Description="Multiple events observed in tumor and normal">
```

I'll try to remove all vcf file related to error and re-analysis.

Thanks.

**Comment by chapmanb** [comment]
Hyunmin -- thanks for cleaning up and sorry again about the issue. I'm not sure why Java outputs this message to stdout so it gets mixed up with the output -- it really should be in stderr. We're working right now to swap over to Java 8 which I hope handles this problem better. Hope things work correctly after cleaning up the problem files and re-running. Please re-open if you find any persistent issues we can fix.
