### ISSUE TITLE
Tracking: sambamba 0.6.1 segfaults in variant2 coverage step

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1433]
This is to track a (seemingly) random segfault issue in sambamba that occurs during depth/coverage counting in QC with large samples (or long BED files). The linked issue upstream is https://github.com/lomereiter/sambamba/issues/223, I will update once I know more.

**Comment by schelhorn** [comment]
Seems to be fixed upstream in `sambamba 0.6.3`; waiting for bioconda release to confirm.

**Comment by chapmanb** [comment]
Thanks for testing this, and to @lomereiter for the new release. I bumped the bioconda version to 0.6.3 so you should be able to update tools in bcbio and get the latest for testing. Hope this fixes the problem.

**Comment by lomereiter** [comment]
Sven-Eric and Brad,
the issue seems to have disappeared with upgrading to more recent LLVM used for compilation. Please bump the bioconda version to 0.6.5, and I mildly hope to never hear of random segfaults again.

**Comment by schelhorn** [comment]
Thanks a bunch: @chapmanb, feel free to close the issue once the version requirements have been bumped.

**Comment by chapmanb** [comment]
Artem -- brilliant, thank you so much for tracking this down. It looks like you beat me to the update in bioconda so updating bcbio will pull down the latest version. Much appreciated.
