### ISSUE TITLE
Minor bug fix for simple_sv_annotation.py

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1434]
AZ kindly contributed the simple_sv_annotation script, which is hosted by bioconda and used in bcbio. I have a minor bugfix for this module; however, it seems to be vanished from the AZ github repository at the moment. The bug fix is very simple; in line `218` of that file, it says:

```python
        exons.append(int(ann_a[8].split('/')[0]))
```

Sometimes, the extracted values can be `''` (an empty string), in which case the cast to integer fails. The fix is to catch the error and pass on it:

```python
        try:
            exons.append(int(ann_a[8].split('/')[0]))
        except ValueError:
            pass
```
@miika, perhaps you could comment on the script being lost from your repo, and could fix the bug in the bioconda version? Thanks a bunch.

**Comment by mjafin** [comment]
<joke> Now that we got you hooked, we pulled it and will be monetising on it! </joke>
More seriously, let me see what's happened. 

On a positive note, SnpEff 4.3 will finally support properly annotating gene fusions resulting from inv/dup/del so most of the hackery we have in place will be redundant soon I hope. Just helping Pablo Cingolani with the remaining issues.

**Comment by mjafin** [comment]
It's back now at https://github.com/AstraZeneca-NGS/simple_sv_annotation, can you check? Happy to accept pull requests.

**Comment by mjafin** [comment]
All done now

**Comment by chapmanb** [comment]
Sven-Eric and Miika -- thanks much for this. I'll update the conda package with the new version.

**Comment by schelhorn** [comment]
Hello @chapmanb, could it be that the conda package you updated did not include the bug fix? The AZ repository does contain the fix, but I was just [looking at the source of 2016.06.15](https://anaconda.org/bioconda/simple_sv_annotation/files), and the problematic line seems to be unchanged there.

**Comment by chapmanb** [comment]
Sven-Eric -- apologies, that's my mistake. I messed up building the previous package and just rebuilt it so if you update you should get the latest which will include your fix. Sorry about the mistake.

**Comment by schelhorn** [comment]
Great, thanks for the update.
