### ISSUE TITLE
oncofuse: called up with wrong location

### ISSUE THREAD

**Issue by csardas** [chapmanb/bcbio-nextgen#1445]
I tried to call up oncofuse while running star algner by enable fusion_mode: True  in yaml
The process ended up with an "Uncaught exception occurred"
seems location of Oncofuse.jar was replaced by anaconda/bin/oncofuse
where can I fix this mistake?

[2016-06-28T04:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; java -Xms750m -Xmx2000m -jar /tools/bcbio/galaxy/../anaconda/bin/oncofuse /home/csardas/RNAseq_test/test_bcbio_run5_star_fusion/align/525N/525NChimeric.out.junction.hg19 rnastar-2-4 AVG /home/csardas/RNAseq_test/test_bcbio_run5_star_fusion/align/525N/tx/tmpAVE66p/oncofuse_out.txt
Error: Invalid or corrupt jarfile /tools/bcbio/galaxy/../anaconda/bin/oncofuse
' returned non-zero exit status 1

**Comment by roryk** [comment]
Hi @csardas,

This should be fixed in the development version of `bcbio-nextgen`. If you update with:

```
bcbio_nextgen.py upgrade -u development
```

You should pull in the version that has the fix. Sorry about that.

**Comment by csardas** [comment]
thanks for response
i have some questions about fusion-mode

I tried fusion-mode with tophat2, the pipeline will call up tophat-fuse,
but ended up with  KeyError: 'rg' in novoalign.py

is this bug fixed in development version?
and is it possible to combine tophat and oncofuse?
(I know tophat is not recommended...)

...........................................................................
/tools/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/novoalign.py in get_rg_info(names={'lane': '525N_tophat2_fusion_debug'})
     15 from bcbio.utils import (memoize_outfile, file_exists)
     16
     17 # ## BAM realignment
     18
     19 def get_rg_info(names):
---> 20     out = r"@RG\tID:{rg}\tPL:{pl}\tPU:{pu}\tSM:{sample}".format(**names)
        out.format = undefined
        names = {'lane': '525N_tophat2_fusion_debug'}
     21     if names.get("lb"):
     22         out += r"\tLB:{lb}".format(**names)
     23     return out
     24

KeyError: 'rg'
