### ISSUE TITLE
Significant inefficiency in prioritize module, simple fix

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1446]
In `variation.prioritize`, there is a significant (in terms of time lost) inefficiency in the `_prep_priority_filter` method. The method checks if its output is already existing; however, that output file is always deleted by the last line (`bgzip_and_index`) in the same function. The fix is to check not for the `tsv` file (which gets deleted) but for the `tsv.gz` file with the same base name. Please fix.

**Comment by schelhorn** [comment]
Perhaps it would also make sense to look for similar cases where `bgzip_and_index` is used (which is all over the place). The side effect of deleting the input file may not always be intended.

**Comment by chapmanb** [comment]
Sven-Eric;
Apologies about the file checking mistake and thanks for the heads up. I pushed a fix for this to skip regenerating the CSV on re-runs if the bgzipped output exists. We generally try to do this in other cases but missing it here. If you find any other instances happy to fix them. Thanks again.

**Comment by schelhorn** [comment]
Thanks, Brad.
