### ISSUE TITLE
Java heap space issue in bcbio-prioritize, please add configurable java memory option

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1453]
`bcbio-prioritize` doesn't seem to be too happy when large priority BED files is supplied (such as all human transcripts, 60k regions). Appearently, 16 GB RAM aren't sufficient for thus prioritizing genome-wide `cnvkit` calls on a WGS sample, which is a little surprising; I am now trying to use 32 GB which seems to work. However, currently, the [bcbio implementation](https://github.com/chapmanb/bcbio-nextgen/blob/8a2640d4e6916729f76b1d7bb59d4342026fb2ff/bcbio/structural/prioritize.py#L52) takes its memory options from the global `jvm_opts`. Could we please get a local resource setting just for `bcbio-prioritize`, so that the memory settings of the other java tools aren't scaled up as well?

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the problems, Using all genes doesn't provide a ton of advantage of over selecting directly on snpEff annotations so I hadn't considered that use case. It's a pretty rough and ready implementation so likely would need some work to not be so terrible at memory usage.

Practically, you can set memory with `bcbio_prioritize` right now:
```
resources:
   bcbio_prioritize:
     jvm_opts: []
```
which is the line above where you liked above. Sorry about the underscore/dash confusion on that but hope that gets your analysis finished.

**Comment by schelhorn** [comment]
Excellent, thank you; sorry for not realizing the resource configuration myself, it was rather obvious after all. We are using a custom gene definition that also considers regulatory regions, that's why the BED file is so long.
