### ISSUE TITLE
Modify JVM's memory of gatk in yaml

### ISSUE THREAD

**Issue by xiang-hong** [chapmanb/bcbio-nextgen#1460]
I wrote this in the resource section of YAML file:

resource:
　　gatk:
　　　　jvm_opts:["-Xms750","-Xmx2000m"]

but I still got error about memory:

> ##### ERROR MESSAGE: An error occurred because you did not provide enough memory to run this program. You can use the -Xmx argument (before the -jar argument) to adjust the maximum heap size provided to Java. Note that this is a JVM argument, not a GATK argument.
##### ERROR

and I found it out in the bcbio-nextgen-commands.log:

`Java -Xms681m -Xmx1g........ -jar GenomeAnalysisTK.jar`

How can I solve this problem?

**Comment by chapmanb** [comment]
Sorry about the problem, this looks like a typo in your specification. It should be `resources`, not `resource`:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources

If that was a typo in your problem report (instead of the YAML) it could also be a section where bcbio scales down memory usage. In some cases we run multiple things in parallel so need to share the total memory. You could try increasing total available GATK memory further to see if that helps. If you're still stuck, knowing the command that it fails on would help us provide more specific advice.

Hope this helps.

**Comment by xiang-hong** [comment]
I added jvm_opts["-Xms750","-Xmx2000m"] in bcbio_system.yaml,
but bcbio-nextgen-commands.log shows that bcbio set argument as -Xms681 -Xmx1g to launch GATK.

**Comment by chapmanb** [comment]
Could you provide the specific command line that fails so we can see what GATK is running? This will allow us to give more specific advice.

If you change the specification to:
```
resources:
  gatk:
     jvm_opts: ["-Xms750", "-Xmx4000m"]
```
does that help?

**Comment by xiang-hong** [comment]
It's work , and this is my config yaml:

```
upload:
　dir: ../final
resources:
　gatk:
　　jvm_opts: ["-Xms750m" , "-Xmx4g"]
details:
- algorithm:
　　aligner: star
　　quality_format: Standard
　　strandedness: unstranded
　　trim_reads: False
　　variantcaller: gatk
  analysis: RNA-seq
  description: testrun14
  files:
  - ../525N_S99_L999_R1_001.clean.fastq.gz
  - ../525N_S99_L999_R2_001.clean.fastq.gz
  genome_build: GRCh37
```

and I checked the bcbio-nextgen-commands.log show that:

[2016-07-11T02:50Z] java -Xms681m -Xmx3g -XX:+UseSerialGC -Djava.io.tmpdir=/pete
rhouse/s1001733/testgatk/work/tx/tmp3GK8uZ -jar /peterhouse/tools/bcbio/toolplus
/gatk/3.6-0-g89b7209/GenomeAnalysisTK.jar -T SplitNCigarReads -R /peterhouse/too
ls/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /peterhouse/s1001733/testgatk/
work/align/525N_testrun14/525N_testrun14_star/525N_testrun14-dedup.bam -o /peter
house/s1001733/testgatk/work/align/525N_testrun14/525N_testrun14_star/tx/tmpWFol
kG/525N_testrun14-dedup.splitN.bam -rf ReassignOneMappingQuality -RMQF 255 -RMQT
 60 -rf UnmappedRead -U ALLOW_N_CIGAR_READS --read_filter BadCigar --read_filter
 NotPrimaryAlignment

why isn't -Xms750m   -Xmx4g ?

**Comment by xiang-hong** [comment]
sorry,I think I misunderstood your mean about control memory.
The problem has solved.

Thanks for your help.

**Comment by chapmanb** [comment]
Great -- glad that helped. Thanks again for the discussion and testing.
