### ISSUE TITLE
BWA mapping in HLA typing using OptiType

### ISSUE THREAD

**Issue by aditiq** [chapmanb/bcbio-nextgen#1463]
Hi,

I wanted to understand better the 1st step of HLA typing using Optitype in bcbio i.e. aligning to hg38 to extract fastq reads in HLA regions.

Are you using bwa-mem to align to the reference fasta file provided by Optitype ? Also what parameters of bwa do you use with RNAseq reads?

Thanks!

**Comment by chapmanb** [comment]
Thanks for the questions:

- We align with bwa-mem to the hg38 distribution containing HLA as alternative alles from 1000 genomes (ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/). bwa extracts reads aligning to HLA regions into a separate fastq file. We then align this much smaller set of reads to the OptiType reference according to their recommended workflow.
- We don't currently use bwa for RNA-seq or have a supported approach for HLA typing with RNA-seq reads. The implementation works for DNA-seq variant calling experiments.

Hope this helps, please let us know if you have other questions.

**Comment by lpantano** [comment]
Hi @aditiq 

I am closing this since it seems Brad answered your question, please feel free to open an issue if you find again the problem.

thanks!
