### ISSUE TITLE
Feature request: option for not uploading alignment files to final storag

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1466]
When processing larger amounts of WGS data, it would be convenient if we could selectively disable uploading any alignment and disambiguation files to the `final` location (POSIX or S3). I believe that is currently not enabled in bcbio and would require an additional flag in the configuration YAML and allow `bcbio.upload._maybe_add_alignment` to skip uploading of any alignment files to the final storage. Would it be possible to implement this?

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the suggestion. The latest development version has a `tools_off: [upload_alignment]` which will skip upload of these for a sample if set. Hope this helps and please let us know if you run into any problems.

**Comment by schelhorn** [comment]
Thanks!
