### ISSUE TITLE
memory outage issue 

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1470]
Hi Team,

Recently we ran 30 samples through bcbio pipeline. Of these 2 fail with memory issue. I am running these on 100GB node even
[bcbio.stderr.txt](https://github.com/chapmanb/bcbio-nextgen/files/362151/bcbio.stderr.txt)

 though it does not require that much. More over these are SNP(20 sites) samples. Not sure if its indeed a memory issue. Can you guys help.

Thanks,

**Comment by chapmanb** [comment]
Diya;
It looks like GATK itself needs more memory allocated to complete processing on your input files. It is current using ~3g which it looks like may be scaled from a higher setting. If you adjust `jvm_opts` for `gatk` to have a higher maximum memory usage (`-Xmx10g`) hopefully that will let your analysis finish cleanly:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources

Hope this helps
