### ISSUE TITLE
hg19-resources.yaml dbsnp version

### ISSUE THREAD

**Issue by duxan** [chapmanb/bcbio-nextgen#1471]
Hi, after data upgrade (bcbio_nextgen.py upgrade --data) pipeline is still looking for dbsnp_138.vcf.gz while it seems that recently v147 is introduced (https://github.com/chapmanb/cloudbiolinux/commit/0010429e56cef9af18837266b516989393bd2bc5)

**Comment by chapmanb** [comment]
Dušan -- thank you for the report and apologies about the oversight. I bumped the references in the bcbio configuration files so if you do `bcbio_nextgen.py upgrade --data` again it should look for the newer files. Hope this gets everything working for you.

**Comment by duxan** [comment]
It works after upgrade now - thank you Brad.
