### ISSUE TITLE
New gene list feature for svprioritize seems to break coverage QC

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1475]
As the title says; the new SV prioritization using `svprioritize` runs fine with a custom gene list (gene symbols, one per row as the AZ list), but then coverage estimation fails in `variation.coverage.priority_coverage()` when calling `cleaned_bed = clean_file(bed_file, data, prefix="cov-", simple=True)`, since of course the file is no BED file any more: `ValueError: Contigs in BED file FILEPATH.bed not in reference genome:  ['FGFR1OP2', 'AGK', 'HIST1H4E', ...`.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for the report and sorry about the oversight. I pushed a fix that will skip these priority coverage estimations for now. I know we need to do some work to look overall all the coverage steps so can revisit looking up coordinates via gene names in the transcript BED files if this ends up being useful. Thanks again.
