### ISSUE TITLE
tests/run_tests.sh fails (nosetests directory missing)

### ISSUE THREAD

**Issue by gberriz** [chapmanb/bcbio-nextgen#1477]
The error message is this:

    tests/run_tests.sh: line 27: /tmp/bcbio-nextgen/scripts/nosetests: No such file or directory

(FWIW, I list the full interaction below, but I think the issue is pretty straightforward.)

Where can I get the missing `nosetests` directory?

NB: I am only secondarily interested in running the tests.  My primary interest is to read the source code for the tests.  (Running the tests is only to ensure that they are in sync with the code I have.)

Thanks!

G

    # -----------------------------------------------------------------------------

    % cd /tmp

    % git clone https://github.com/chapmanb/bcbio-nextgen.git
    Cloning into 'bcbio-nextgen'...
    remote: Counting objects: 31201, done.
    remote: Compressing objects: 100% (46/46), done.
    remote: Total 31201 (delta 13), reused 0 (delta 0), pack-reused 31153
    Receiving objects: 100% (31201/31201), 24.28 MiB | 9.53 MiB/s, done.
    Resolving deltas: 100% (22206/22206), done.
    Checking connectivity... done.

    % cd bcbio-nextgen/

    % (PATH=$PWD/scripts:$PATH; tests/run_tests.sh)
    tests/run_tests.sh: line 27: /tmp/bcbio-nextgen/scripts/nosetests: No such file or directory

    % find . -name nosetests
    # (no output)

**Comment by roryk** [comment]
Hi Gabriel,

`nosetests` is a program to run the tests, which you can install via pip:

```
bcbio_pip install nosetests
```

The source code for the tests is in `tests/test_automated_analysis.py`. Hope that helps get you going.

**Comment by gberriz** [comment]
I'm aware of the nosetests module, in fact, I have it installed; since nosetests will not be installed under $BCBIO_DIR (like the script expects), I assumed that it had to be something else.  That's ok, I'll put a symlink in there.  Thanks.

**Comment by chapmanb** [comment]
Gabriel;
This looks like the test script can't find the bcbio installation which should include nosetests. Do you have bcbio installed and available in your PATH?

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

If you do that, things should hopefully run cleanly. Hope this helps.

**Comment by gberriz** [comment]
Brad, thanks for the clarification.  I've been working off the clone of the bcbio-nextgen GitHub repo, rather than a full-blown installation.

**Comment by chapmanb** [comment]
Gabriel -- thanks for following up. You can run the unit tests with a bcbio installation lacking genome data (using the `--nodata` option) since they use a self-contained local test set, but you do need to have the tools installed via the installation method. Hope doing that will get things running cleanly for you. Please feel free to reopen this if you run into other problems.
