### ISSUE TITLE
ChIP-Seq pipeline: allow bypassing alignment

### ISSUE THREAD

**Issue by LMannarino** [chapmanb/bcbio-nextgen#1481]
(cc @lbeltrame )

I need to re-run the pipeline without file realignment, since they were previously generated.   Setting the parameter aligner to false does not allow to bypass realignment and raises this error:

````
      1 from bcbio.ngsalign.bowtie2 import filter_multimappers
      2 import bcbio.pipeline.datadict as dd
      3 
      4 def clean_chipseq_alignment(data):
      5     aligner = dd.get_aligner(data)
----> 6     assert aligner == "bowtie2", "ChIP-seq only supported for bowtie2."
      7     if aligner == "bowtie2":
      8         data["raw_bam"] = dd.get_work_bam(data)
      9         unique_bam = filter_multimappers(dd.get_work_bam(data), data)
     10         data["work_bam"] = unique_bam

AssertionError: ChIP-seq only supported for bowtie2.
```
The ChiP-seq pipeline should support skipping the alignment step as the other pipelines.
I last update the pipeline Tuesday 19 July 2016.

**Comment by lpantano** [comment]
Hi

sorry about this.

I pushed a fix for that, and it should be able to run with BAM files as input. The only thing is that the bam file should be ready to be used for peak calling, that cleaning function is only compatible with bowtie2.

I will add a warning for that.

thanks

**Comment by lbeltrame** [comment]
For context, these BAM files were made by the pipeline, and we just wanted to change the MACS2 parameters. Hence why this option may come in handy.

**Comment by lpantano** [comment]
sure, it is a good idea. Just want to add the message for other situations where the bam file doesn’t come from previous bcbio.

thanks for the suggestion

**Comment by LMannarino** [comment]
Just updated, unfortunately it does not work. It raises this error:

````

     7     if aligner:
      8         assert aligner == "bowtie2", "ChIP-seq only supported for bowtie2."
      9         unique_bam = filter_multimappers(dd.get_work_bam(data), data)
     10         data["work_bam"] = unique_bam
     11     else:
---> 12         logger.info("When BAM file is given, bcbio skips multimappers removal.")
     13         logger.info("If BAM is not cleaned for peak calling, can result in downstream errors.")
     14     return [[data]]
     15 
     16 

NameError: global name 'logger' is not defined
```

**Comment by lpantano** [comment]
sorry, forgot to push that one commit.

hopefully now it works?

**Comment by LMannarino** [comment]
yes, thank you very much!
