### ISSUE TITLE
Document how to use a "bundled" (via conda) java for GATK 3.6

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1485]
When trying to get 0.9.9 installed on a new cluster (Ubuntu 14.04 based), the installation failed if I specified `toolplus gatk=` if the path pointed to a JAR of the GATK 3.6 (Unsupported version etc).
The notes in the changelog are a bit sparse: how would one proceed to ensure everything is in order to use another Java version provided by bcbio or equivalent?

**Comment by lbeltrame** [comment]
Actually it should work if it's in your PATH, but a new installation won't have it (because it's not there yet).

**Comment by chapmanb** [comment]
Luca;
There is a new way to register GATK 3.6 Java 8 dependent packages, documented here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

This uses bioconda so no longer needs our custom changes in bcbio. Hopefully that works for getting things going.

**Comment by lbeltrame** [comment]
Brilliant, thanks!
