### ISSUE TITLE
Genome installation via ggd uses system Java leading to issues with Picard 2.x

### ISSUE THREAD

**Issue by cbrueffer** [chapmanb/bcbio-nextgen#1486]
Hi,

adding a new genome via bcbio_nextgen.py upgrade --genomes hg38-noalt tries installation with ggd first, which seems to use the system Java (1.7 in my case), instead of the one in the local conda installation (Java 1.8). This leads to an exception when calling Picard, which requires Java 1.8 since Picard 2.x.

This is with up to date tools and bcbio-nextgen 0.9.9.

The full log of the above command is here: https://gist.github.com/cbrueffer/c15b188a52926f053ea19e12d376ad72

**Comment by chapmanb** [comment]
Christian;
Thanks for the heads up on the problem. I swapped over the bioconda package to use the anaconda installed java by default, so if you update bcbio tools (`bcbio_nextgen.py upgrade --tools`) and re-run it should do the right thing (provided you don't also have to have JAVA_HOME set).

As an aside not related to this, we're not actively developing hg38-noalt as we think you can do everything you need with hg38 and want to try to work around a single distribution in build 38. If you need noalt for some reason it would be helpful to know how we can migrate to the standard full hg38.

**Comment by cbrueffer** [comment]
Thanks a lot Brad!

Regarding hg38-noalt, this is what the samples I work with (>4000) are already aligned against. While there are discussions of re-aligning them to hg38 proper, using hg38-noalt allows me to experiment with stuff further down the line (especially variant calling) without needing to re-align anything.
