### ISSUE TITLE
SV analysis failed, run_metasv.py not found

### ISSUE THREAD

**Issue by ycl6** [chapmanb/bcbio-nextgen#1489]
I am running SV analysis (`svcaller: [lumpy, manta, delly, metasv]`), and it wasn't until the last step I realise metasv is not installed in the requested path. How can I solve this?

```
$ bcbio_nextgen.py --version
0.9.9
```

Error:
```
/xxx/bcbio/bcbio-nextgen/anaconda/bin/python: can't open file '/xxx/bcbio/bcbio-nextgen/anaconda/bin/run_metasv.py': [Errno 2] No such file or directory
Uncaught exception occurred
```

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. I've been trying to reproduce this on a clean install of bcbio but haven't been able to do so. `metasv` is included in the packages installed by bcbio and should be present. As a workaround you should be able to do:
```
bcbio_conda install -c bioconda metasv
```
to ensure metasv gets installed. Hope this resolves the problem for you.

**Comment by ycl6** [comment]
Thanks, I re-install bcbio-nextgen, and it's now installed.
