### ISSUE TITLE
sailfish output to limma

### ISSUE THREAD

**Issue by zahrahaider** [chapmanb/bcbio-nextgen#1490]
Hi,

So I have run bcbio-nextgen pipeline for RNA-seq analysis and now I am interested in differential isoform quantification. Should I use the output file: combined.isoform.sf.tpm directly as input to the limma package? 

Thanks in advance!

**Comment by roryk** [comment]
Hi @zahrahaider,

We recommend using the bootstrap estimates for transcript expression from Sailfish that are in the final/sample/sailfish directories as input to Sleuth. We have a standalone repository to set that up for you here, if you pass along the `--sleuth` option and a formula you want to fit. This won't actually run Sleuth, but it will set everything up for you.

```
https://github.com/roryk/bcbio.rnaseq
```

You can also install it as a conda package:

```
conda install -c bioconda bcbio-rnaseq
```

**Comment by zahrahaider** [comment]
Thanks alot for the response.

**Comment by roryk** [comment]
Great!
