### ISSUE TITLE
raise ValueError("Default tool directory not yet saved in config defaults. " ValueError: Default tool directory not yet saved in config defaults. Specify the '--tooldir=/path/to/tools' to upgrade tools. After a successful upgrade, the '--tools' parameter will work for future upgrades.

### ISSUE THREAD

**Issue by ScarecrowFu** [chapmanb/bcbio-nextgen#1499]
HI ,I am alan .

I run "bcbio_nextgen.py upgrade --tools"

 got this problems:

raise ValueError("Default tool directory not yet saved in config defaults. "
ValueError: Default tool directory not yet saved in config defaults. Specify the '--tooldir=/path/to/tools' to upgrade tools. After a successful upgrade, the '--tools' parameter will work for future upgrades.

**Comment by chapmanb** [comment]
Sorry about the issue and happy to try to help to correct your installation. Can you provide more details about how you installed bcbio? You should use the automated installer:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

which will create a tool directory and set the configuration properly to be able to run in place upgrades of tools like you're trying to do. If you installed this way and things got broken somehow, you can follow the instructions in the error message and do:
```
bcbio_nextgen.py upgrade --tools --tooldir=/where/you/want/tools/installed
```
Hope this helps.
