### ISSUE TITLE
RNA-seq variant calling: precision might be improved

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1502]
Hi bcbio developers!

I have validated RNA-seq variant calling in BCBIO with SRR307898 dataset (GM12878 cell line).
The precision is 90%. 

In bcbio-nextgen/bcbio/rnaseq/variation.py I see 3 steps
```
def rnaseq_gatk_variant_calling(data):
    data = dd.set_deduped_bam(data, dedup_bam(dd.get_work_bam(data), data))
    data = gatk_splitreads(data)
    data = gatk_rnaseq_calling(data)
    return data
```
While GATK best practices suggest one more important step: filtering (step 7).
[https://software.broadinstitute.org/gatk/guide/article?id=3891](https://software.broadinstitute.org/gatk/guide/article?id=3891).

In my experience it really improves precision at least to 95%.

Could you include this step into variation.py?

Also it would be nice to filter out RNA-editing sites by default.
It should not be complex:
```
bedtools subtract -header -a input.vcf -b rnaedit.bed >output.vcf
```

Many thanks,
SN

**Comment by roryk** [comment]
Hi Sergey,

Awesome, thanks so much for testing.  We provide editing sites from RADAR but don't have them run automatically: 

`genomes/Hsapiens/GRCh37/editing/RADAR-GRCh37.bed`

if you intersect with those, does that give you the same bump in precision? I know there is also the DARNED database but I haven't been following the literature much to know whats the best resource to use. If RADAR works, and the BED file we provide looks good, we can totally add it to the postprocessing of the RNA-seq variants. Otherwise it would be great to know where you grabbed your BED file from.

**Comment by naumenko-sa** [comment]
Hi Roryk, 
I filtered out RNAediting sites with bed file before measuring precision.
SN

**Comment by roryk** [comment]
Hi Sergey,

Yup-- but is the editing sites BED file you used from RADAR or another place?

**Comment by naumenko-sa** [comment]
Yes, it was from RADAR.

**Comment by roryk** [comment]
Thanks, this is super helpful. I've been messing around with Brent's vcfanno (https://github.com/brentp/vcfanno) for doing this. I was thinking instead of splitting the VCF up into possible-edits and not, we can instead tag each variant that is a possible deaminase event and overlaps the RADAR edit sites as a possible edit event in the INFO field. Would that work?

**Comment by roryk** [comment]
Thanks Sergey, added support for this in the development version. It uses `vcfanno` to add a `possible_edit` entry to the INFO field for events that are a) SNPs and b) overlap RADAR.

**Comment by naumenko-sa** [comment]
Thanks Roryk, the annotation approach is perfect. Anyone then could filter out these sites, or keep them.SN

**Comment by naumenko-sa** [comment]
Hi Roryk, in my initial post I started with GATK filtration step. Could you please implement this also?
```
java -jar GenomeAnalysisTK.jar -T VariantFiltration -R hg_19.fasta -V input.vcf -window 35 -cluster 3 -filterName FS -filter "FS > 30.0" -filterName QD -filter "QD < 2.0" -o output.vcf 
```
This would boost the precision.

**Comment by roryk** [comment]
Hi Sergey,

Sure-- where did you pick those filters from and what do they do?

**Comment by naumenko-sa** [comment]
It is from GATK best practices for RNA-seq,
[https://software.broadinstitute.org/gatk/guide/article?id=3891](https://software.broadinstitute.org/gatk/guide/article?id=3891)

```
To filter the resulting callset, you will need to apply hard filters, as we do not yet have the RNAseq training/truth resources that would be needed to run variant recalibration (VQSR).

We recommend that you filter clusters of at least 3 SNPs that are within a window of 35 bases between them by adding -window 35 -cluster 3 to your command. This filter recommendation is specific for RNA-seq data.

As in DNA-seq, we recommend filtering based on Fisher Strand values (FS > 30.0) and Qual By Depth values (QD < 2.0).

java -jar GenomeAnalysisTK.jar -T VariantFiltration -R hg_19.fasta -V input.vcf -window 35 -cluster 3 -filterName FS -filter "FS > 30.0" -filterName QD -filter "QD < 2.0" -o output.vcf 

Please note that we selected these hard filtering values in attempting to optimize both high sensitivity and specificity together. By applying the hard filters, some real sites will get filtered. This is a tradeoff that each analyst should consider based on his/her own project. If you care more about sensitivity and are willing to tolerate more false positives calls, you can choose not to filter at all (or to use less restrictive thresholds).

An example of filtered (SNPs cluster filter) and unfiltered false variant calls: 
```
In my testing this filter really improves precision.

**Comment by roryk** [comment]
Thanks Sergey, I added these filters-- we were counting on folks running their own filters on variants downstream, but I think people run the RNA-seq variant calling so seldomly that it makes sense to err on the side of leaving out some calls rather than including everything.

**Comment by naumenko-sa** [comment]
Thanks Roryk, this is what I need. I have tested the updated version with 
```
details:
- algorithm:
    aligner: star
    effects: snpeff
    variantcaller: gatk
  analysis: RNA-seq
  description: SRR307898
  files:
  - /hpf/largeprojects/ccmbio/naumenko/RIVAL/pipeline_results/bcbio/input/SRR307898_1.fq.gz
  - /hpf/largeprojects/ccmbio/naumenko/RIVAL/pipeline_results/bcbio/input/SRR307898_2.fq.gz
  genome_build: GRCh37
upload:
  dir: ../final
```
In final/project/combined.vcf I see that SnpCluster filter is working.
But regarding RNAediting annotation I have not found anything. Maybe I forgot to turn it on?
```
bedtools intersect -header -a combined.vcf -b rnaedit.v2.bed > combined.rnaedit.vcf
cat combined.rnaedit.vcf | grep -vc '^#'
24764
cat combined.vcf | grep -c possible_edit 
0
```
Combined.vcf does contain some variants in RNA editing sites and does not contain possible_edit annotation.
Please check this!
Thanks, 
Sergey

**Comment by roryk** [comment]
Hi Sergey,

Sorry about that-- could you look through your log file and see what it says about vcfanno? It will just skip running vcfanno if it can't find the configuration files, and it would be helpful to know which it is missing.

**Comment by naumenko-sa** [comment]
Hi Roryk!
```
cat bcbio-nextgen-commands.log | grep vcfanno
<empty>
```
SN

**Comment by roryk** [comment]
Thanks, what about the debug log file? It should be spitting out some messages about why it is not running vcfanno.

**Comment by naumenko-sa** [comment]
Yes, you are right:
```
The vcfanno configuration /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/GRCh37-rnaedit.conf was not found for GRCh37, skipping.

```

**Comment by roryk** [comment]
Great-- if you do a data update with `bcbio_nextgen.py upgrade --data`  it should pull in the vcfanno directory to here: `/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/`. Let me know if that doesn't work.

**Comment by naumenko-sa** [comment]
I have updated successfully, but I have got an error:
```
subprocess.CalledProcessError: Command 'set -o pipefail; /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/galaxy/../anaconda/bin/vcfanno -lua /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/GRCh37-rnaedit.lua -base-path /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/GRCh37-rnaedit.conf /hpf/largeprojects/ccmbio/naumenko/RIVAL/pipeline_results/bcbio/work/align/SRR307898/SRR307898_star/SRR307898-dedup.splitN.gvcf > /hpf/largeprojects/ccmbio/naumenko/RIVAL/pipeline_results/bcbio/work/align/SRR307898/SRR307898_star/tx/tmpXDMZ4S/SRR307898-dedup.splitNrnaedit-annotated.vcf.gz

=============================================
vcfanno version 0.0.11-beta [built with devel +5ec87ba Thu Apr 28 15:36:34 2016 +0000]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:108: [Flatten] unable to open file: /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno//hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/../editing/RADAR-GRCh37.bed.gz in /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno
' returned non-zero exit status 1
```
Kind of path error somewhere. How to fix it?
SN

**Comment by naumenko-sa** [comment]
Hi Roryk,
could you please check if the filter gatk_filter_rnaseq(data, vrn_file, out_file):
from 
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/variation.py
is actually running? The commands.log file does not contain VariantFiltration command.
SN

**Comment by roryk** [comment]
Hi Sergey,

Thanks, I fixed the code to run this properly and ran it on the dataset you are running and it appears to be working okay. The vcfanno edit annotation does not work 100% properly at the moment, the feature we are using to call if a possible edit is a SNP is in the unreleased version of vcfanno: https://github.com/brentp/vcfanno/releases/download/v0.1.0-dev/vcfanno   so right now it will just call if it overlaps an edit site, not if it could be one.

**Comment by naumenko-sa** [comment]
Thanks, Roryk!
Unfortunately the last step is not working for me. The pipeline tries to run the command
```
/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/galaxy/../anaconda/bin/vcfanno -lua /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/GRCh37-rnaedit.lua -base-path /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/GRCh37-rnaedit.conf variation/combined.vcf | bgzip -c > variation/tx/tmpYNxXPd/combinedrnaedit-annotated.vcf.gz
```
This is throws an error
```
vcfanno.go:108: [Flatten] unable to open file: /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno//hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno/../editing/RADAR-GRCh37.bed.gz in /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/vcfanno
```
SN

**Comment by naumenko-sa** [comment]
Hi Rory!

I found that the problem is not in the code, but in the database:
bcbio/genomes/Hsapiens/GRCh37/editing
the file RADAR-GRCh37.bed

should be processed:
* remove first line 
* bedtools sort
* bgzip
* tabix

After that vcfanno runs, but with errors:
```
api.go:72: lua-error @ 12:122959771: <string>:2: attempt to index a non-table object(nil)
stack traceback:
	<string>:2: in function 'is_snp'
	<string>:6: in main chunk
	(tailcall): ?
	[G]: ?
```
in the result it annotates only a few indels (why indels?) with:
```
possible_rnaedit=err:<nil>
```

Not a problem for me  - I still can remove RNAediting events with bedtools, but this problematic
step does not allow the pipeline to finish correctly (empty final folder).

SN

**Comment by roryk** [comment]
Hi Sergey,

Sorry about that. If you do a data update, you should get a new version of the RADAR data that is sorted, zipped and indexed, I should have mentioned that. The err:nil error you are seeing is because the new functionality relies on an unreleased version of vcfanno (https://github.com/brentp/vcfanno). I'll bug brent to push a release so we can get that up to date.

**Comment by naumenko-sa** [comment]
Thanks Rory!
Could you please check the update procedure? I've just updated successfully and I see no changes in the Hsapiens/GRCh37/editing directory.

**Comment by roryk** [comment]
Hi Sergey,

Hm-- did you do a `bcbio_nextgen.py upgrade -u development --data`?

**Comment by roryk** [comment]
It looks like I forgot to bump the version. If you nuke the temporary directory that gets pulled in during the update (its tmp-cbl or something like that), relative to your current-working directory, you should pull down the new RADAR recipe from cloudbiolinux.

**Comment by naumenko-sa** [comment]
Unfortunately the update does not work. I see the correct RADAR.yaml in the temporary folder during the installation but the editing folder does not change. I tried also to remove the editing folder and RADAR string from versions.csv - did not help.
The upgrade command is 
```
bcbio_nextgen.py upgrade  -u development --data
```
Not on the list?

```
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'rtg', 'star'], 'genomes': [{'annotations': ['GA4GH_problem_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'transcripts', 'mirbase'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}, {'validation': ['platinum-genome-NA12878', 'giab-NA12878-remap', 'giab-NA12878-crossmap', 'dream-syn4-crossmap', 'dream-syn3-crossmap'], 'name': 'Human (hg38) full', 'dbkey': 'hg38', 'annotations': ['coverage', 'prioritize', 'dbsnp', 'hapmap_snps', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', '1000g_indels', 'clinvar', 'qsignature', 'transcripts']}, {'name': 'Mouse (mm10)', 'dbkey': 'mm10', 'annotations': ['problem_regions', 'dbsnp', 'transcripts', 'mirbase']}, {'name': 'Arabidopsis thaliana (TAIR10)', 'dbkey': 'TAIR10', 'annotations': ['mirbase']}], 'install_uniref': False}'): Human (GRCh37), Human (hg38) full, Mouse (mm10), Arabidopsis thaliana (TAIR10)
```

**Comment by roryk** [comment]
Hi Sergey,

Thanks for debugging, sorry about that. The cloudbiolinux issue was twofold: 1) RADAR was turned off and 2) the ggd recipe had some formatting issues. It looked like it was working for me because it didn't throw an error because it was turned off and I already had the tabixed files in that directory from testing. It should be all good now.

**Comment by naumenko-sa** [comment]
Thanks Rory, now it updates! Running GGD recipe: RADAR-GRCh37

**Comment by roryk** [comment]
Great! Thanks, sorry for how long it took.

**Comment by roryk** [comment]
vcfanno just got a new version, I'll update the bioconda recipe and after that this all should be working cleanly.

**Comment by naumenko-sa** [comment]
Great! I will calculate RNA-seq variant calling precision then and we hopefully will have a nice estimate!

**Comment by roryk** [comment]
Thanks a lot Sergey, happy to incorporate any other changes that seem like they will help. We haven't done too much RNA-seq variant calling work so your input is super helpful.

**Comment by naumenko-sa** [comment]
Hi Rory! Could please help me with this issue? I am completely stuck with it. https://github.com/chapmanb/bcbio-nextgen/issues/1546
SN

**Comment by naumenko-sa** [comment]
Hi Rory! 

Sorry, I will bother you again with RNA-seq pipeline.
I'm running validation of RNA-seq variant calling with SRR307898 which is RNA-seq of NA12878
on the latest update of bcbio.

In the final/project/combinedrnaedit-annotated.vcf.gz 
I have 178,994 variants, and 
only 24 of them have possible_rnaedit annotation. They all are deletions and the annotation looks like 'possible_rnaedit=err:<nil>'. Sounds like a bug, eh?

When checking against the RADAR database I see much more.
```
bedtools intersect -a combinedrnaedit-annotated.vcf.gz -b ~/work/tools/bcbio/genomes/Hsapiens/GRCh37/editing/RADAR-GRCh37.bed.gz | wc -l
24764
```
For now I can filter with bedtools, but if you could fix the code to do RNAedit annotation properly, it would be of great help.

Thanks,
Sergey

**Comment by roryk** [comment]
Hi Sergey,

Huh-- let me see if I can reproduce with SRR307898 and get back to you.

**Comment by roryk** [comment]
Thanks Sergey, I tracked this down to vcfanno not supporting the way we were specifying the BED file. I fixed the RADAR BED files and it should work now, will test on your test dataset.

**Comment by naumenko-sa** [comment]
Thanks Rory for you work, now rna-seq pipeline annotates rna_editing events well!

Could you please check this 2PASS STAR issue if you have time: https://github.com/chapmanb/bcbio-nextgen/issues/1629
