### ISSUE TITLE
bcbio-variation-recall square error

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1503]
Hi! 

I am running a freebayes joint variant call and have encountered an error on the bcbio-variation-recall square command. The full command was:

bcbio-variation-recall square -Xms250m -Xmx4g -XX:+UseSerialGC -c 6 -r 9:46566299-141213\
431 --caller freebayes /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_fb_joint/work/joint/freebayes-joint/elite\
268/9/elite268-9_46566298_141213431.vcf.gz /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /scratch/PI/euan/\
projects/elite/bcbio/projects/project_n268_fb_joint/work/joint/freebayes-joint/elite268/9/elite268-9_46566298_141213431.vcf-\
inputs.txt

A couple bcbio-variation-recall square commands worked before this one encountered an issue, but I have no clue really what this function does and why it might be randomly failing.

The output generated in the bcbio-nextgen.log file:

Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'bcbio-variation-recall square -Xms250m -Xmx4g -XX:+UseSerialGC -c 6 -r 9:1-46565846 --caller freebayes/scratch/PI/euan/projects/elite/bcbio/projects/project_n268_fb_joint/work/joint/freebayes-joint/elite268/9/elite268-\9_0_46565846.vcf.gz /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_fb_joint/work/joint/freebayes-joint/elite268/9/elite268-9_0_46565846.vcf-inputs.txt

**AND**

Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setu\
p_logging
    yield config
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 432, in square_batch_region
    return ipython.zip_args(apply(joint.square_batch_region, *args))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 123, in square_batch_region
    _square_batch_bcbio_variation(data, region, bam_files, vrn_files, out_file, "square")
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 173, in _square_batch_bcbio_variation
    do.run(cmd, "%s in region: %s" % (cmd, bamprep.region_to_gatk(region)))
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'bcbio-variation-recall square -Xms250m -Xmx4g -XX:+UseSerialGC -c 6 -r 9:1-46565846 --caller freebayes /scratch/PI/euan/projects/elite/bcbio/projects/project_n268_fb_joint/work/joint/freebayes-joint/elite268/9/elite268-9_0_46565846.vcf.gz /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa /scratch/PI/euan/projects/elite/bcbio/pr\
ojects/project_n268_fb_joint/work/joint/freebayes-joint/elite268/9/elite268-9_0_46565846.vcf-inputs.txt

Any thoughts? :)

Thank you very much for all your help!
Luke

**Comment by chapmanb** [comment]
Luke;
Sorry about the issues and for the detailed report. Unfortunately I don't see see any informative errors in what you pasted. The messages say that the bcbio-variation-recall command, which is what runs the joint calling of the initial calls, failed but don't give a clue as to why.

Practically, the FreeBayes joint calling implementation is pretty disk intensive and can cause issues. How many samples are you running with joint calling? If it's a smaller number, than using batch calling (calling everything together) is probably a better option. If it's a larger number, is using gatk-haplotype joint calling an option? That will scale much better than our current FreeBayes implementation.

If you're stuck at FreeBayes joint calling we can diagnose more with more of the traceback that you could post at https://gist.github.com/ and link to here. Hope this helps.

**Comment by lsturm1** [comment]
I am joint calling 268 samples. I would definitely switch to gatk-haplotype joint calling instead if it scales better! Thanks for that advice! Yeah I am sorry I couldn't provide a better debug log, but that is pretty much all it said... Hopefully it will be fine after I switch to gatk.

Thanks!

**Comment by lsturm1** [comment]
Hi Brad,

Here is the gist: https://gist.github.com/lsturm1/a2a1ab80b464ee141fc552a6205e356b

I didn't put the whole bcbio-nextgen-debug.log because it gets very big quick with joint calling. 
It seems as though this is the main error: vcffixup: could not open stdin
This error does not crash the whole job though.

Would love your thoughts. Thanks for the help!

**Comment by chapmanb** [comment]
Luke;
Thanks for the details, this helps a lot. I believe we're running into a bug with the current FreeBayes (https://github.com/ekg/freebayes/issues/310) here, causing FreeBayes to segfault. I pushed a workaround for this to bcbio-variation-recall, so if you do:
```
bcbio_nextgen.py upgrade --tools
```
and then re-run your analysis in place it should hopefully work cleanly. Hope this fixes it for you.
