### ISSUE TITLE
Fusion genes by RNA-seq

### ISSUE THREAD

**Issue by zahrahaider** [chapmanb/bcbio-nextgen#1506]
Hi again!

I would like to know if bcbio-nextgene pipeline for RNA-seq analysis includes fusion gene discovery or detection of inter-chromosomal translocations? 
If not, do you have any recommendations how I could use the output from the RNA-seq pipeline for fusion gene detection?

Thanks alot!

**Comment by roryk** [comment]
Hi Zahra,

Hope everything is well. We do have some support for calling fusions with Oncofuse, you can turn it on with `fusion_mode=True` in the YAML file. I personally have almost no experience calling fusion events. @mjafin and @schelhorn have a lot of experience and I think they've had good success using the fusioncatcher pipeline that @ndaniel wrote: https://github.com/ndaniel/fusioncatcher  I would love to include it in bcbio during fusion calls but I've been holding out for a conda package to handle the dependencies, the installation is pretty heavy weight.

**Comment by zahrahaider** [comment]
Hi!

Thank you for such a super quick response! 

Best Regards

**Comment by lpantano** [comment]
Hi,

I am closing this, since it seems resolve.

Thanks!
