### ISSUE TITLE
building custom pipelines

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1507]
Hello

I'm looking for some direction on customizing pipelines. Specifically what's doable via config vs code. I wasn't sure given all the work on cwl. I'm fine with either but wanted to double check on recommendations.

A few examples:

1. annotation. I already have vcfs and want to run vep. Problem is I want to run a number of vep plugins for loftee and clinvar functionality. I was unclear how to parametrize a call to vep.

2. joint calling from bams/vcfs. I have vcfs (or gvcfs) and just want the squared off call set.

3. pedigree calling. For example RTG with a ped file. Or GATK with a ped file for standard batch calling with post processing step for optimized phasing (readbackphasing, phasebytransmission and ld/haplotypecaller). 

4. exome cnv calling. conifer, xhmm, penncnv-exomseq

**Comment by chapmanb** [comment]
Daryl;
Thanks for the thoughts. We're hoping the CWL mechanism will allow people to build their own custom pipelines and then mix/match with bcbio components. This is still a bit of a work in progress and although bcbio can run with CWL (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) it would still be for early adopters if you want to play with it.

To answer your questions specifically, 1 and 2 are probably best done outside of bcbio. bcbio doesn't provide a lot of value over running VEP or running GenotypeGVCFs so it's probably not worth the overhead of trying to force these cases into a run. 

For 3, we don't currently do that although it would be nice to include the functionality in bcbio. This is something that could fit quite well within the framework but would need to be coded and tested.

For 4, we have exome CNV calling implemented with `svcaller: [cnvkit]`: http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#structural-variant-calling and http://cnvkit.readthedocs.io This should work as is with a standard run.

Hope this helps.

**Comment by dwaggott** [comment]
Thanks for the update!
