### ISSUE TITLE
STAR aligner using only one thread

### ISSUE THREAD

**Issue by KanduriC** [chapmanb/bcbio-nextgen#1510]
Hi,

I was trying to run a RNA-seq pipeline with STAR as aligner. Irrespective of the instructions to use 16 cores for star aligner (specified through sample configuration file), I find that star is being instructed to use only 1 thread through command line. I am running the job on a cluster where each node contains 16 cores and at least 56G free memory. My sample configuration file and bcbio-nextgen-commands.log are shown below. Could you help me figure out the problem? Thanks.

```
more ../rnaseq-seqc.yaml
# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    files: [input/SRR950080_1.fastq.gz, input/SRR950080_2.fastq.gz]
    description: rna_seq_example_run
    resources:
      star:
        cores: 16
        memory: 3G
        options: [--runThreadN, 16]
    genome_build: GRCh37
    algorithm:
      quality_format: Standard
      aligner: star
      strandedness: unstranded
upload:
  dir: ../final
```
**bcbio-nextgen-commands.log**
```
more bcbio-nextgen-commands.log 
[2016-08-10T15:55Z] /cluster/home/skanduri/bcbio/galaxy/../anaconda/bin/STAR --g
enomeDir /cluster/home/skanduri/bcbio/genomes/Hsapiens/GRCh37/star/ --readFilesI
n /work/jobs/15294111.d/seqc-test/input/SRR950080_1.fastq.gz /work/jobs/15294111
.d/seqc-test/input/SRR950080_2.fastq.gz **--runThreadN 1** --outFileNamePrefix /work
/jobs/15294111.d/seqc-test/align/rna_seq_example_run/rna_seq_example_run --outRe
adsUnmapped Fastx --outFilterMultimapNmax 10 --outStd SAM  --outSAMunmapped With
in --outSAMattributes NH HI NM MD AS  --sjdbGTFfile /cluster/home/skanduri/bcbio
/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.gtf  --sjdbOverhang 100  --readF
ilesCommand zcat  --outSAMattrRGline ID:rna_seq_example_run PL:illumina PU:rna_s
eq_example_run SM:rna_seq_example_run  --outSAMstrandField intronMotif  --quantM
ode TranscriptomeSAM  | /cluster/home/skanduri/bcbio/galaxy/../anaconda/bin/samt
ools sort -@ 1 -m 1G  -T /work/jobs/15294111.d/seqc-test/align/rna_seq_example_r
un/rna_seq_example_run_star/tx/tmpvvZ5vP/rna_seq_example_run-sorttmp -o /work/jo
bs/15294111.d/seqc-test/align/rna_seq_example_run/rna_seq_example_run_star/tx/tm
pvvZ5vP/rna_seq_example_run.bam /dev/stdin
```
**bcbio-nextgen-debug.log**
```
more bcbio-nextgen-debug.log
[2016-08-10T15:55Z] System YAML configuration: /cluster/home/skanduri/bcbio/gala
xy/bcbio_system.yaml
[2016-08-10T15:55Z] Resource requests: picard; memory: 3.50; cores: 1
[2016-08-10T15:55Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of 
memory reserved for each job
[2016-08-10T15:55Z] run local -- checkpoint passed: trimming
[2016-08-10T15:55Z] Timing: organize samples
[2016-08-10T15:55Z] multiprocessing: organize_samples
[2016-08-10T15:55Z] Using input YAML configuration: /work/jobs/15294111.d/seqc-t
est/rnaseq-seqc.yaml
[2016-08-10T15:55Z] Checking sample YAML configuration: /work/jobs/15294111.d/se
qc-test/rnaseq-seqc.yaml
[2016-08-10T15:55Z] Testing minimum versions of installed programs
[2016-08-10T15:55Z] multiprocessing: prepare_sample
[2016-08-10T15:55Z] Preparing rna_seq_example_run
[2016-08-10T15:55Z] Resource requests: picard, star; memory: 3.50, 3.00; cores: 
1, 16
[2016-08-10T15:55Z] Configuring 1 jobs to run, using 16 cores each with 56.1g of
 memory reserved for each job
[2016-08-10T15:55Z] run local -- checkpoint passed: alignment
[2016-08-10T15:55Z] Timing: alignment
[2016-08-10T15:55Z] multiprocessing: disambiguate_split
[2016-08-10T15:55Z] multiprocessing: process_alignment
[2016-08-10T15:55Z] Aligning lane rna_seq_example_run with star aligner
[2016-08-10T15:55Z] Running STAR aligner on /work/jobs/15294111.d/seqc-test/inpu
t/SRR950080_1.fastq.gz and /cluster/home/skanduri/bcbio/genomes/Hsapiens/GRCh37/
star/

```

**Comment by roryk** [comment]
Hi Chakravarthi,

It looks like the alignment has already finished, this line:

`run local -- checkpoint passed: alignment`

is skipping spinning up the complete resources because it thinks the alignment is finished already. The checkpoint files are in the `work/checkpoints` directory. If you nuke the alignment one, it will spin up the full resources. The checkpoint file shouldn't be written unless the entire alignment step finished properly, by any chance did this complete once already and more samples got added or the alignment directory was deleted?

**Comment by KanduriC** [comment]
Thanks a lot for the quick reply.

Yes, because of a [previous issue post-alignment](https://github.com/chapmanb/bcbio-nextgen/issues/1501), I removed the alignment directories, but ignored a directory `checkpoints-parallel` that contains alignment.done and trimming.done. Is this causing the problem, was that the reason `--runThreadN 1` was being passed to STAR?

**Comment by roryk** [comment]
Yup, you got it, that's exactly right. You can nuke the --runThread under options in your YAML file too.

**Comment by KanduriC** [comment]
thanks once again. I will come back if the problem persists. 
I've another question. I've installed bcbio on say `oldpath/dir-1`, but later moved the whole directories to `newpath/dir-2`. But when I run the job, bcbio seem to use the executables from the old location. How can I fix this?  Is this path information stored somewhere? Thanks.

**Comment by roryk** [comment]
Sorry about that, I don't have a great answer for that one, it definitely isn't designed to be relocated like that so it might have that information baked in a bunch of places. It is probably a lot less hassle to just reinstall into the directory you want it to go in.

**Comment by KanduriC** [comment]
The problem is that I have to install it on a cluster that doesn't have internet (intended to handle sensitive data), so I was wondering whether I can handle it this way.

**Comment by roryk** [comment]
Gotcha, one way you could do it would be to install it somewhere that does have access to the internet, and then mount that installation over NFS, if that is a possibility. That way the sensitive compute never sees the outside internet but you can still update the tools and what not. It's going to be super tough to keep up to date without the ability to update stuff.
