### ISSUE TITLE
ensemble calling issue

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1515]
Hi!

I found an issue with the ensemble calls. It turns out multiple rows may exist for the same variant but with calling differences. See below. 

In the first row (entry), all callers find the variant in all samples, whereas in second row reports results for platypus only and the variant is not detected in the last sample.  

Not sure what's going on here. And when I come to think about it, might it make more sense to include what callers detected a variant in the sample genotype fields?

```
chr12   2791132 .   A   G   82783.80    PASS    AC=8;AF=0.666667;AN=12;CALLERS=freebayes,gatk-haplotype,platypus,samtools;DECOMPOSED;LEN=1;NS=6;TYPE=snp    GT:AO:DP:GQ:PL:QA:QR:RO 1|1:1024,0:1024:99:34308,3083,0,34308,3083,34308:38141,0:0:0    0|1:593,1:1066:99:16784,0,12676,18171,14430,32628:22223,38:17655:471    1|1:696,0:698:99:23217,2063,0,23220,2095,23252:25851,0:38:1 0|1:355,0:729:99:9766,0,10310,10885,11379,22263:13290,0:13895:372   0|1:310,2:642:99:8399,0,9200,9327,10071,19454:11477,76:12368:329    0|1:5,295:596:99:8120,8856,17916,0,8919,8187:190,11007:11081:296
chr12   2791132 .   A   G   2947    PASS    AC=7;AF=0.583333;AN=12;CALLERS=platypus;DECOMPOSED;LEN=1;NS=6;TYPE=snp  GT:GOF:GQ:NR:NV:PL  1|1:1:99:1016:1016:2994,2994,0  0|1:1:99:1050:583:2997,0,3000   1|1:1:99:694:692:2994,2004,0    0|1:2:99:725:353:2997,0,3000    0|1:1:99:636:308:2997,0,3000    0|0:1:99:594:5:0,2997,3000
```

**Comment by chapmanb** [comment]
Pär;
Sorry about the issue. Do the initial Platypus calls have two variant calls at this position? I'm trying to figure out if the ensemble method propagates an issue in the original calls or creates a new incompatible call as part of the merging process. If the later, then it would be helpful to have a minimal VCFs of the inputs in this region and we can try to debug further.

In general, the ensemble method is not smart, especially for multisample VCFs, so it's not going to be especially robust to any input issues. Trying to have a smarter ensemble method is something we'd like to do.

**Comment by lpantano** [comment]
Hi @parlar 

I am closing this, please feel free to open an issue if you find again the problem.

thanks!
