### ISSUE TITLE
Updating tools 

### ISSUE THREAD

**Issue by lsturm1** [chapmanb/bcbio-nextgen#1517]
Thank you so much for pushing the fix for the segfault! When trying to update using bcbio-nextgen.py upgrade --tools, I got this fatal error: 

Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio/anaconda/bin/conda", line 6, in <module>

  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/install.py", line 1068, in link
    _link(src, dst, lt)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda/install.py", line 216, in _link
    shutil.copy2(src, dst)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/share/PI/euan/apps/bcbio/anaconda/pkgs/conda-env-2.5.2-py27_0/lib/python2.7/site-packages/conda_env/__init__.py`and`/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/conda_env/**init**.py` are the same file

Fatal error: local() encountered an error (return code 1) while executing '/share/PI/euan/apps/bcbio/anaconda/bin/conda install -y -c bioconda -c r -c conda-forge age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools=1.3.0 bedtools=2.24.0 bio-vcf biobambam bowtie bowtie2 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt delly express fastqc freebayes=1.0.2.29 gatk gatk-framework gemini geneimpacts glpk=4.57 grabix gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kraken lofreq lumpy-sv macs2 manta mbuffer metasv mirdeep2 moreutils multiqc multiqc-bcbio novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff spades star stringtie subread svtools svtyper tdrmapper theta2 tophat ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java variant-effect-predictor variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham awscli p7zip s3gof3r perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.
---

Is this a problem with conda or our setup?

Thank you,
Luke

**Comment by chapmanb** [comment]
Luke;
Sorry about the problem. I'm not sure what is going on here, I can't replicate the conda issue or find any bugs with the same problem. Does conda work at all, if you do:
```
/share/PI/euan/apps/bcbio/anaconda/bin/conda list | grep conda-env
```
If so, maybe try `bcbio_conda uninstall conda-env && bcbio_conda install conda-env` to try and fix the conda-env installation.

If conda doesn't work at all I'm not sure how best to recover from getting in this state other than trying to force a re-install with `bcbio_pip uninstall conda && bcbio_pip install conda`. 

Hope one of these helps resolve the problem.

**Comment by lpantano** [comment]
Hi Luke,

I will close this, but if you still have issues, feel free to open it.

thanks!
