### ISSUE TITLE
 error while loading shared libraries: libmaus2.so.2

### ISSUE THREAD

**Issue by ScarecrowFu** [chapmanb/bcbio-nextgen#1523]
i was running the example **Cancer tumor normal**

got this ,looking for help:

[2016-08-20T03:05Z] Ensure integrity of input merge BAM files
[2016-08-20T03:05Z] Merge bam files to syn3-normal-sort.bam
[2016-08-20T03:05Z] bamsormadup: error while loading shared libraries: libmaus2.so.2: cannot open shared object file: No such file or directory
[2016-08-20T03:05Z] bamcat: error while loading shared libraries: libmaus2.so.2: cannot open shared object file: No such file or directory
[2016-08-20T03:05Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/opt/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; bamcat level=0 tmpfile=/home/alan/cancer-dream-syn3/work/align/syn3-normal/tx/tmpCE7klJ/syn3-normal-sort.bam-bammerge `cat /home/alan/cancer-dream-syn3/work/align/syn3-normal/tx/tmpCE7klJ/syn3-normal-sort.list` | bamsormadup threads=8 indexfilename=/home/alan/cancer-dream-syn3/work/align/syn3-normal/tx/tmpCE7klJ/syn3-normal-sort.bam.bai tmpfile=/home/alan/cancer-dream-syn3/work/align/syn3-normal/tx/tmpCE7klJ/syn3-normal-sort.bam-bamsormaduptmp > /home/alan/cancer-dream-syn3/work/align/syn3-normal/tx/tmpCE7klJ/syn3-normal-sort.bam
bamsormadup: error while loading shared libraries: libmaus2.so.2: cannot open shared object file: No such file or directory
bamcat: error while loading shared libraries: libmaus2.so.2: cannot open shared object file: No such file or directory
' returned non-zero exit status 127

**Comment by chapmanb** [comment]
Alan;
Sorry about this issues. Is it possible you have another biobambam installation on your machine that takes precedence over the one installed with bcbio? What does:
```
which bamsormadup
readlink -f `which bamsormadup`
ldd $(readlink -f `which bamsormadup`)
```
report? The installation within bcbio should take care of referencing the necessary shared libraries correctly within bioconda, so this might help diagnose what happened with the installation.

**Comment by ScarecrowFu** [comment]
hi,chapmanb  ,thanks the help

i ran 

`which bamsormadup
readlink -f `which bamsormadup`
ldd $(readlink -f `which bamsormadup`)`

got this:

(root) [alan@GZJZ tests]$ which bamsormadup
/opt/local/share/bcbio/anaconda/bin/bamsormadup
(root) [alan@GZJZ tests]$ readlink -f `which bamsormadup`
/opt/local/share/bcbio/anaconda/bin/bamsormadup
(root) [alan@GZJZ tests]$ ldd $(readlink -f `which bamsormadup`)
	linux-vdso.so.1 =>  (0x00007ffeb679f000)
	**libmaus2.so.2 => not found
	libalign.so => not found**
	**libmaus2_simd_align_128.so.2 => not found
	libmaus2_simd_align_256.so.2 => not found**
	libsnappy.so.1 => /opt/local/share/bcbio/anaconda/bin/../lib/libsnappy.so.1 (0x00007f915b680000)
	libstdc++.so.6 => /opt/local/share/bcbio/anaconda/bin/../lib/libstdc++.so.6 (0x00007f915b2c4000)
	libgnutls.so.28 => not found
	libp11-kit.so.0 => /usr/lib64/libp11-kit.so.0 (0x0000003d8a600000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003d8a200000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003d8aa00000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003d8b200000)
	libtasn1.so.6 => not found
	libhogweed.so.2 => not found
	libgmp.so.10 => /opt/local/share/bcbio/anaconda/bin/../lib/libgmp.so.10 (0x00007f915b04e000)
	libz.so.1 => /opt/local/share/bcbio/anaconda/bin/../lib/libz.so.1 (0x00007f915ae38000)
	libnettle.so.4 => not found
	libm.so.6 => /lib64/libm.so.6 (0x0000003faf000000)
	libgomp.so.1 => /opt/local/share/bcbio/anaconda/bin/../lib/libgomp.so.1 (0x00007f915ac14000)
	libgcc_s.so.1 => /opt/local/share/bcbio/anaconda/bin/../lib/libgcc_s.so.1 (0x00007f915a9fd000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003d89e00000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003d89a00000)
	libfreebl3.so => /lib64/libfreebl3.so (0x0000003d90e00000)
(root) [alan@GZJZ tests]$

**Comment by ScarecrowFu** [comment]
hi,chapmanb,I had fix this error

I ran  ` sudo find / -name libmaus2.so.2 `

got this:
/opt/local/share/bcbio/anaconda/pkgs/biobambam-2.0.44-0/share/biobambam-2.0.44-0/lib/libmaus2.so.2
/opt/local/share/bcbio/anaconda/share/biobambam-2.0.44-0/lib/libmaus2.so.2
/opt/local/share/bcbio/anaconda/lib/libmaus2.so.2
/exports/home/alan/libmaus2-master/src/.libs/libmaus2.so.2
/exports/opt/share/bcbio/anaconda/pkgs/biobambam-2.0.44-0/share/biobambam-2.0.44-0/lib/libmaus2.so.2
/exports/opt/share/bcbio/anaconda/share/biobambam-2.0.44-0/lib/libmaus2.so.2
/exports/opt/share/bcbio/anaconda/lib/libmaus2.so.2


I found libmaus2.so.2, libalign.so, libmaus2_simd_align_128.so.2,libmaus2_simd_align_256.so.2 
in /opt/local/share/bcbio/anaconda/pkgs/biobambam-2.0.44-0/share/biobambam-2.0.44-0/lib/

so i copy them into /opt/local/share/bcbio/anaconda/lib/

`cp /opt/local/share/bcbio/anaconda/pkgs/biobambam-2.0.44-0/share/biobambam-2.0.44-0/lib/* /opt/local/share/bcbio/anaconda/lib/`

that fix the problem.
