### ISSUE TITLE
illumina ftp not available on install

### ISSUE THREAD

**Issue by mattdmem** [chapmanb/bcbio-nextgen#1527]
-2016-08-23 18:30:29--  ftp://platgene_ro:*password*@ussd-ftp.illumina.com/2016-1.0/hg19/small_variants/NA12878/NA12878.vcf.gz
  (try: 6) => ‘validation/platinum-genome-NA12878/truth_small_variants.vcf.gz’
Connecting to ussd-ftp.illumina.com (ussd-ftp.illumina.com)|66.192.10.36|:21... connected.
Logging in as platgene_ro ...
Error in server response, closing control connection.
Retrying.

**Comment by chapmanb** [comment]
Matthew;
Sorry about the install issues. This download appears to be working for me now so this might have been an intermittent issue. Could you retry the installation/upgrade with the same parameters? It should pick up where it left off and hopefully finish successfully.

**Comment by mattdmem** [comment]
Thanks brad, it's no problem.

I checked this morning and it is still failing - could be an issue with our internal network.

**Comment by mattdmem** [comment]
Is there a way to ignore these files in the meantime?

**Comment by chapmanb** [comment]
Matthew;
Do you have issues downloading these files via other methods on your network? I'm trying to figure out if we can add options to wget or tweak somehow to correctly resolve this so you can get the files. We don't have a configurable way to ignore downloads but you could fix manually by editing `tmpbcbio_install/cloudbiolinux/config/biodata.yaml` to remove references to `platinum-genome-NA12878`. Hope this helps.

**Comment by mattdmem** [comment]
Thanks brad - it's a firewall issue on our end I think - I tried editing the yaml but the problem is it gets downloaded fresh every time you run the install.  I'm talking with our IT.

**Comment by chapmanb** [comment]
Matthew -- thanks for checking locally. Happy to put in fixes if you come up with any ideas.

Regarding the workaround, if you run `bcbio_nextgen_install.py` it will remove the directory since there are stages prior to the data installation. But you have enough installed that you can use the automated upgrader which will not remove it:
```
/path/to/tools/bin/bcbio_nextgen.py upgrade --data
```
which could hopefully cleanly finish the installation. Then in the future you can do upgrades of tools and code:
```
bcbio_nextgen.py upgrade -u development --tools
```
without needing this. Hope this is a reasonable workaround.

**Comment by mattdmem** [comment]
Thanks brad.  I get this:
Upgrading bcbio
Data not installed, no genomes provided with `--genomes` flag
Upgrade completed successfully.

I'm going to keep on at our IT to see what they can do.

**Comment by chapmanb** [comment]
Matthew -- sorry if it never finished successfully on the previous run you won't have a configuration with the genomes you need. You might need to copy over the `--genomes --aligners --tooldir` inputs from your install command until you get a successful run. Hope this helps.

**Comment by mattdmem** [comment]
I'll try this.  Looks like we are blacklisted on illumina's FTP and it doesn't look like they can rectify anytime soon.  You may consider making this 3rd party repositories somehow optional on install?

**Comment by mattdmem** [comment]
This workaround still tries to download the illumina truth set and then fails!

**Comment by chapmanb** [comment]
Matt -- so sorry about all these issues. I'm not sure why the Illumina FTP site isn't working from your location but I don't want to block you anymore so I prepared cached versions of these files in S3 and updated the recipes to point at the new location. If you remove the temporary bcbio download directory (`rm -rf tmpbcbio-install`) and re-run it should grab the updated versions and hopefully get you past this. Hope this gets a clean install for you to work from. Thanks so much for all the patience with this.

**Comment by mattdmem** [comment]
Thanks Brad - this is amazing - it is installed now!!  Really appreciate your help with this.

 I will still keep hounding illumina tech support - but even they said that it was "difficult" to action these requests.
