### ISSUE TITLE
multiple times input files GATK HC

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1534]
Hi Brad,
I am running in the following issue. It seems to me that the normal bam name is paste two time in the GATK routine.

I have add the error message and the yaml for the run.

Thanks!
Alessandro

- algorithm:
    aligner: bwa
    background: /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/m7/PON/m7-PON_nodd.vcf
    coverage: /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/m7/bed/m7_FLIPI_plus9_Strand_A_82068-Regions_GRCh37.bed
    coverage_interval: amplicon
    ensemble:
      numpass: 2
    mark_duplicates: false
    platform: illumina
    quality_format: standard
    realign: gatk
    recalibrate: gatk
    remove_lcr: true
    tools_off:
    - gemini
    tools_on:
    - multiqc
    variant_regions: /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/m7/bed/m7_FLIPI_plus9_Strand_A_82068-Regions_GRCh37.bed
    variantcaller:
    - gatk-haplotype
    - mutect
    - vardict
    - freebayes
    - mutect2
  analysis: variant2
  description: OCI-Ly8_S14
  files:
  - /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/fastq/OCI-Ly8_S14_L001_R1_001.fastq.gz
  - /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/fastq/OCI-Ly8_S14_L001_R2_001.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: OCI-Ly8
    phenotype: tumor
- algorithm:
    aligner: bwa
    background: /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/m7/PON/m7-PON_nodd.vcf
    coverage: /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/m7/bed/m7_FLIPI_plus9_Strand_A_82068-Regions_GRCh37.bed
    coverage_interval: amplicon
    ensemble:
      numpass: 2
    mark_duplicates: false
    platform: illumina
    quality_format: standard
    realign: gatk
    recalibrate: gatk
    remove_lcr: true
    tools_off:
    - gemini
    tools_on:
    - multiqc
    variant_regions: /cbio/cslab/home/pastore/nobackup/install/bcbio-vm/data/project/m7/bed/m7_FLIPI_plus9_Strand_A_82068-Regions_GRCh37.bed
    variantcaller:
    - gatk-haplotype
    - mutect
    - vardict
    - freebayes
    - mutect2
  analysis: variant2
  description: PONs
  files:
  - /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/fastq/PON_R1_001.fastq.gz
  - /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/fastq/PON_R2_001.fastq.gz
  genome_build: GRCh37
  metadata:
    batch:
    - '1317'
    - '1494'
    - '1588'
    - '1607'
    - '1611'
    - '1687'
    - '2147'
    - '2176'
    - '2444'
    - '2765'
    - '3058'
    - '3116'
    - DB
    - Namalwa
    - OCI-Ly1
    - OCI-Ly1
    - OCI-Ly8
    - SU-DHL-5
    - WSU-FSCCL
    phenotype: normal

INFO  22:47:47,432 HelpFormatter - Program Args: -T VariantAnnotator -R /cbio/cslab/nobackup/pastore/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --variant /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/m7-FL_low_nodedup/work/freebayes/1/OCI-Ly1-1_27056130_150727636.vcf.gz --out /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/m7-FL_low_nodedup/work/freebayes/1/tx/tmpMntqT3/OCI-Ly1-1_27056130_150727636-gatkann.vcf.gz -L /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/m7-FL_low_nodedup/work/freebayes/1/OCI-Ly1-1_27056130_150727636.vcf.gz --dbsnp /cbio/cslab/nobackup/pastore/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-147.vcf.gz -I /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/m7-FL_low_nodedup/work/bamprep/OCI-Ly1_S13/1/OCI-Ly1_S13-sort-1_27056130_150727636-prep.bam -I /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/m7-FL_low_nodedup/work/bamprep/PONs/1/PONs-sort-1_27056130_150727636-prep.bam -I /cbio/cslab/nobackup/pastore/install/bcbio-vm/data/project/m7/m7low_input/m7-FL_low_nodedup/work/bamprep/PONs/1/PONs-sort-1_27056130_150727636-prep.bam -A BaseQualityRankSumTest -A FisherStrand -A GCContent -A HaplotypeScore -A HomopolymerRun -A MappingQualityRankSumTest -A MappingQualityZero -A QualByDepth -A ReadPosRankSumTest -A RMSMappingQuality --allow_potentially_misencoded_quality_scores -U ALL --read_filter BadCigar --read_filter NotPrimaryAlignment 
INFO  22:47:47,447 HelpFormatter - Executing as pastore@gpu-2-8.local on Linux 2.6.32-573.18.1.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_92-b15. 
INFO  22:47:47,448 HelpFormatter - Date/Time: 2016/08/23 22:47:47 
INFO  22:47:47,449 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  22:47:47,449 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  22:47:47,470 GenomeAnalysisEngine - Strictness is SILENT

**Comment by apastore** [comment]
thanks!

**Comment by chapmanb** [comment]
Alessandro;
Apologies about the issue, it looks like your normal metadata batch specified `OCI-Ly1`, resulting in double inclusion of this and the error you're seeing. I pushed a fix to remove duplicates from batches that should resolve it, or you can edit your YAML to avoid the duplication. It might be worth double checking your batches that this is a duplication and not a substitution for another sample that is missing it's normal mate. Hope this helps.

**Comment by apastore** [comment]
Brad, you are right I was missing a 0 in a batch name.
Thanks!
