### ISSUE TITLE
Copy cnvkit *.cnr files to result directory

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1538]
As it stands, only `cns` files are copied, however cnr files can be useful for plotting: https://cnvkit.readthedocs.io/en/latest/plots.html. 

Since presenting results from SV callers to a biologist is (in my extremely limited experience) extremely difficult, this would allow using a few more tools to ease the problem.

Downside: files can be large.

**Comment by chapmanb** [comment]
Luca -- these files should be passed into the output directory. Here is what I see in the test run for cnvkit outputs:
```
upload/Test1/Test1-cnvkit.bed
upload/Test1/Test1-cnvkit-call.cns
upload/Test1/Test1-cnvkit.cnr
upload/Test1/Test1-cnvkit.cns
upload/Test1/Test1-cnvkit-gainloss.txt
upload/Test1/Test1-cnvkit-segmetrics.txt
upload/Test1/Test1-cnvkit.vcf
```
Are you running a much older version of bcbio that might not include copying these? Hope this helps.

**Comment by lbeltrame** [comment]
This is what I get:

```
 ls *cn*
LC0044-cnvkit.bed  LC0044-cnvkit.cns  LC0044-cnvkit-gainloss.txt  LC0044-cnvkit-segmetrics.txt  LC0044-cnvkit.vcf
```

The `*.cnr` files are however available in the `raw` directory of the CNVkit results.

**Comment by chapmanb** [comment]
Luca -- sorry about the issue. Could you try upgrading to the latest development version to see if that correctly passes along the cnr files? We've been doing a lot of work on CNVkit since the last release so that might be the issue. Apologies about the problems, we'll work to have a new release soon if that fixes the problem.

**Comment by lbeltrame** [comment]
Unfortunately I can't test the development version easily at this point as the machine it runs on (and the associated data files) must run the latest *stable* version at all times (policies...).

**Comment by chapmanb** [comment]
Luca -- we'll try to have a new release soon so you can test this and hopefully fix the problem. Apologies for not being able to replicate, I'm not sure why you see this behavior even in the latest stable release. Thanks for testing and helping debug.

**Comment by lbeltrame** [comment]
I finally managed to check with the latest development version, and the problem is indeed fixed. The `cnr` files are all present (and concidentally, the `gainloss` files now output information, unlike before).
