### ISSUE TITLE
Quantified RNA-Seq on custom gtf

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1539]
Hi rorky,
I have a question, is possible to pass to bcbio a custom gtf file for quantification/counts or I have to generate a new genome for every new transcriptom / territory I want Bcbio to count on?

Thanks!

Alessandro

**Comment by roryk** [comment]
Hi @apastore,

Unfortunately, to run the full RNA-seq pipeline you need to make a new genome with the updated annotation if you want to update the GTF file. If you're just looking to quantitate and do nothing else, the fast RNA-seq pipeline lets you pass in a custom annotation file to use by setting `transcriptome_fasta` to point to the FASTA file of transcripts in the `algorithm` section.

**Comment by apastore** [comment]
Thanks for the tip! I will try the fast-rna. There is an example for the transcriptom fasta file?

Thanks!

**Comment by roryk** [comment]
Ensembl has cDNA files:

```
ftp://ftp.ensembl.org/pub/release-85/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
```

Don't use the ab inito files though.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
