### ISSUE TITLE
Scalpel error "sdbm: cannot insert after SPLTMAX attempts."

### ISSUE THREAD

**Issue by razZ0r** [chapmanb/bcbio-nextgen#1543]
I'm getting the following error when running Scalpel. It seems that the MLDBM perl module used by Scalpel doesn't like something. Any idea what might be the reason?

<pre>
[2016-09-01T17:48Z] node004: -- Print parameters to /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1622/work/mutect/3/LUSC_1622-3_0_128673605-somaticIndels-scalpel-work/main/paramet
ers.txt
[2016-09-01T17:48Z] node004: -- Detect mutations on normal
[2016-09-01T17:48Z] node004: -- Print parameters to /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1622/work/mutect/3/LUSC_1622-3_0_128673605-somaticIndels-scalpel-work/main/normal/
parameters.txt
[2016-09-01T17:48Z] node004: Loading targets from BED file...56112 targets (filtered 0 overlapping).
[2016-09-01T17:48Z] node004: Assembly Exons
[2016-09-01T17:48Z] node004: start assembly of 1205154 regions.
[2016-09-01T17:48Z] node004: stepSize: 1205154
[2016-09-02T02:45Z] node004: ** 0 started, pid: 4698
[2016-09-02T02:45Z] node004: 1. [0..1205153]
[2016-09-02T19:17Z] node004: ** 0 just got out of the pool [PID: 4698 | exit code: 0 | exit signal: 0 | core dump: 0]
[2016-09-02T19:17Z] node004: Merge DBs...
[2016-09-02T19:17Z] node004: sdbm: cannot insert after SPLTMAX attempts.
[2016-09-02T19:17Z] node004: sdbm store returned -1, errno 25, key "a77da048f51f7423d813f4093d768d35" at /pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/share/scalpel-0.5.1-3/MLDBM/Sync/SD
BM_File.pm line 80.
[2016-09-02T19:17Z] node004: Command failure: findVariants (/pico/work/ELIX_prj6/esebesty/bcbio/data/anaconda/share/scalpel-0.5.1-3/FindVariants.pl --bam /pico/scratch/userexternal/esebesty/
bcbio_run/uuid_batch1622/work/bamprep/LUSC_1622_11A_NT/3/LUSC_1622_11A_NT-sort-3_0_128673605-prep.bam --bed /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1622/work/mutect/3/LUSC_16
22-3_0_128673605-somaticIndels-regions-nolcr-nolcr.bed --ref /pico/work/ELIX_prj6/esebesty/bcbio/data/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --kmer 25 --mincov 5 --covthr 3 --lowcov 1 --covra
tio 0.01 --radius 100 --window 400 --maxregcov 10000 --step 100 --mapscore 1 --mismatches 3 --pathlimit 10000 --dir /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1622/work/mutect/3
/LUSC_1622-3_0_128673605-somaticIndels-scalpel-work/main/normal --sample ALL --numprocs 0 --coords null --format vcf --cov2file --intarget)...
[2016-09-02T19:17Z] node004: child exited with value 25
</pre>

**Comment by chapmanb** [comment]
Endre;
Sorry about the issue. Is this a persistent problem if you re-run the analysis or run with `-n 1`? I haven't seen this issue but from searching it looks like it might be a disk write problem. If it fails consistently, it would be useful to know about the type of the filesystem and if anything might be unusual about it. Hope this helps some with debugging.

**Comment by razZ0r** [comment]
Hi,

I just checked, and scalpel seems to fail every time at the same region in the same sample `LUSC_1622_11A_NT-sort-3_0_128673605-prep.bam`. I restarted the pipeline 3 times, and this happens on different nodes.  

The filesystem is GPFS and I had no issue with it up to now.

I'll check if it fails with `-n 1` but I suspect yes.

**Comment by chapmanb** [comment]
Endre;
Sorry about the continued issues. I'm not familiar enough with Perl here to have a good fix for you. If you can reproduce consistently outside of bcbio it might be worth asking @gnarzisi if he has any tips for debugging the problem. Are you able to put together a minimal test case using the commands from `log/bcbio-nextgen-commands.log` that fails reproducibly?

**Comment by gnarzisi** [comment]
Hi Endre, 

yes, if the error is reproducible, a minimal test case would be useful here. Just extract the portion of the BAM file that generates the problem.

I have seen the SPLTMAX error before (very few instances) but it never seem to be reproducible. What's special about the region?

**Comment by razZ0r** [comment]
Hi,

A bit late, but I'll try to put together a minimal case. I have a 9GB bam file, that always fails, but it takes something like 20 hours for scalpel to process it. I'll try to narrow down the problem. BTW I have another sample producing the same error, now a 7.5GB bam. 

Can it be simply a problem of reaching some limitation of the MLDBM perl module?

**Comment by chapmanb** [comment]
Endre;
Thanks for digging into this. I wish I could help more but have no real knowledge or experience with MLDBM so don't know what to suggest. Hopefully with a test case Giuseppe or someone with more Perl saavy can help diagnose the underlying issue.

**Comment by razZ0r** [comment]
I downsampled the bam file in question to 50% and the scalpel step (`FindVariants.pl`) that previously failed with the MLDBM error, now runs ok. The original bam contained 62 million reads, now it contains 32 million. I can try to run it with 75% downsampling or something similar, but I suspect that the high coverage is causing problems.

Unfortunately, I can't share the bam file, as it is TCGA data.

**Comment by razZ0r** [comment]
And scalpel fails with the 75% downsampled (46 million reads) bam file. 

<pre>
[node3 scalpel ]$ bash ./run_scalpel.sh
-- Print parameters to /lustre/home/esebesty/work/tmp/scalpel/normal2/parameters.txt
Loading targets from BED file...56112 targets (filtered 0 overlapping).
Indexing BAM file...
Assembly Exons
start assembly of 1205154 regions.
stepSize: 1205154
** 0 started, pid: 29117
1. [0..1205153]
** 0 just got out of the pool [PID: 29117 | exit code: 0 | exit signal: 0 | core dump: 0]
Merge DBs...
sdbm: cannot insert after SPLTMAX attempts.
sdbm store returned -1, errno 25, key "a77da048f51f7423d813f4093d768d35" at /lustre/data/t-tcga/esebesty/bcbio-20160922/data/anaconda/share/scalpel-0.5.1-3/MLDBM/Sync/SDBM_File.pm line 80.
</pre>


Is it possible to break down the bam files into smaller chunks with bcbio when scalpel is processing them?

**Comment by gnarzisi** [comment]
Your guess about coverage is probably correct. Due to the high coverage there are too many alternative path/variants to analyze, more than the what MLDBM can handle. However you do not need to break down the bam file, just need to parallelize by chromosome or even further.

Finally, if your dealing with cancer data data, I would recommend using Lancet (https://github.com/nygenome/lancet)

**Comment by razZ0r** [comment]
Problem is, that I started processing my samples with bcbio, and that's where I'm using Scalpel. If I drop Scalpel now and/or change to a different caller, that would be a mess, as I'm also using the [Ensemble variant calling feature](http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#ensemble-variant-calling).

BTW  this is already only a part of chr3, split by bcbio. So I think the best solution now would be to just split these high coverage regions into even smaller regions and simply rerun the pipeline before cleaning up the bcbio work/tmp files.

**Comment by gnarzisi** [comment]
Sounds like a good plan. Hope that will work fine.

**Comment by razZ0r** [comment]
Any suggestions from @chapmanb on how to split these bam chunks into even smaller regions automatically? There doesn't seem to be an option to control this in bcbio.

**Comment by chapmanb** [comment]
Endre and Giuseppe -- thanks for the work on diagnosing this. If the issue is excessive depth it seems like we'll have to downsample BAMs prior to feeding to Scalpel rather than restricting region size, which we could do with VariantBam:

https://github.com/walaj/VariantBam#example-use-8

or we could try to remove high depth regions from the indel calls that scalpel does to avoid this. Is this a whole genome run? If so, do you have a `*-highdepth.bed` file in the align directory for this sample and have regions identified in the areas you're seeing failures. If so, this would be an easier fix but I wanted to be sure it might be helpful before putting it in place. Thanks again for all the debugging help.

**Comment by gnarzisi** [comment]
Downsampling the regions with excessive depth should work great. Thank you Brad.

**Comment by razZ0r** [comment]
Yes, I do have a `LUSC_1622_11A_NT-sort-highdepth.bed` file, and it overlaps with the chr3:0-128673605 region causing the problem.

The same scalpel error happened with another sample last week, where I also have a `*-highdepth.bed` file overlapping the region where scalpel fails.

**Comment by chapmanb** [comment]
Endre;
Thanks for following up, I pushed a fix to remove high depth regions from scalpel assessment which will hopefully avoid this. Please let me know if you still run into issues running with the latest development and we can re-open and explore if so. Fingers crossed this will get your analysis done.

**Comment by razZ0r** [comment]
I tried rerunning my pipeline and now I get the following error, on exactly the same region where scalpel failed previously with the MLDBM error.

<pre>
[2016-10-01T04:46Z] node029: Sort BED file : LUAD_1680_10A_NB
[2016-10-01T04:46Z] node029: ***** ERROR: too many digits/characters for integer conversion in string �[{-�W^X�@z^T���ҍ�U��:^X7,^V�!���^Kt;�b(�^P��t^]����^R#�_��^C�^K�#��w�^~lߏ��"��Cݚ^^H�^A/
�^K. Exiting...
[2016-10-01T04:46Z] node029: Uncaught exception occurred
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cat /pico/home/userexternal/esebesty/scratch/tmp/bcbiotx/62eaf2b9-7f28-461c-8667-f1dff96f1928/tmpog_bbG/LUAD_1680-8_32674703_132228185-somaticIn
dels-regions-nolcr-glimit-all.bed | sort -V -k1,1 -k2,2n | bedtools merge -i - -c 4 -o distinct > /pico/home/userexternal/esebesty/scratch/tmp/bcbiotx/1c13910b-9dca-4837-971f-3df03bbc58ba/tmpaUl68s/LUAD_1680-8_32674703_132228185-somaticIndels-regions-nolcr-glimit-all-sort.bed
***** ERROR: too many digits/characters for integer conversion in string �[{-�W^X�@z^T���ҍ�U��:^X7,^V�!���^Kt;�b(�^P��t^]����^R#�_��^C�^K�#��w�^~lߏ��"��Cݚ^^H�^A/�^K. Exiting...
' returned non-zero exit status 1
[2016-10-01T04:46Z] node029: Unexpected error
Traceback (most recent call last):
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 326, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 313, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 149, in mutect_caller
    region=region, out_file=out_file_indels)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py", line 154, in _run_scalpel_paired
    opts = " ".join(_scalpel_options_from_config(items, config, out_file, region, tmp_path))
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py", line 53, in _scalpel_options_from_config
    opts += _scalpel_bed_file_opts(items, config, out_file, region, tmp_path)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py", line 39, in _scalpel_bed_file_opts
    target_bed = shared.remove_highdepth_regions(target_bed, items)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/pipeline/shared.py", line 217, in remove_highdepth_regions
    to_remove = bedutils.sort_merge(all_file, items[0])
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/bedutils.py", line 83, in sort_merge
    do.run(cmd.format(**locals()), "Sort BED file", data)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cat /pico/home/userexternal/esebesty/scratch/tmp/bcbiotx/62eaf2b9-7f28-461c-8667-f1dff96f1928/tmpog_bbG/LUAD_1680-8_32674703_132228185-somaticIndels-regions-nolcr-glimit-all.bed | sort -V -k1,1 -k2,2n | bedtools merge -i - -c 4 -o distinct > /pico/home/userexternal/esebesty/scratch/tmp/bcbiotx/1c13910b-9dca-4837-971f-3df03bbc58ba/tmpaUl68s/LUAD_1680-8_32674703_132228185-somaticIndels-regions-nolcr-glimit-all-sort.bed
</pre>

**Comment by tkoomar** [comment]
I have recently begun to experience the same `***** ERROR: too many digits/characters for integer conversion in string` followed by what appears to be binary, as Endre reports above. It occurs prior to freebayes snv calling  as well as manta cnv calling -- though other callers do not appear to be affected, at this point. 

Below is the error, though it actually occurs three times -- once each for three `-regions-nolcr-glimit-all.bed` files.  Gist of full debug log: https://gist.github.com/tkoomar/32bf733d6035092ebf2f535655b50e3d

```
[2016-10-03T15:59Z] Sort BED file : sample50
[2016-10-03T15:59Z] ***** ERROR: too many digits/characters for integer conversion in string �[{-�W�@z���ҍ�U��:7,�!���t;�b(���t����#�_����#��w�^~lߏ��"��CݚH�/�. Exiting...
[2016-10-03T15:59Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/Dedicated/jmichaelson-wdata/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cat /Dedicated/jmichaelson-sdata/SLI_WGS/batch10/fq/sample_50/freebayes/1/tx/tmpTTl6JC/test-1_0_16360711-regions-nolcr-glimit-all.bed | sort -V -k1,1 -k2,2n | bedtools merge -i - -c 4 -o distinct > /Dedicated/jmichaelson-sdata/SLI_WGS/batch10/fq/sample_50/freebayes/1/tx/tmpTTl6JC/tx/tmpf9mppD/test-1_0_16360711-regions-nolcr-glimit-all-sort.bed
***** ERROR: too many digits/characters for integer conversion in string �[{-�W�@z���ҍ�U��:7,�!���t;�b(���t����#�_����#��w�^~lߏ��"��CݚH�/�. Exiting...
' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Endre and @tkoomar -- thanks for the report and apologies about the new issue. The code for preparing highdepth regions wasn't correctly handling bgzipped file inputs and we recently changed some of the pre-installed data inputs to be bgzipped for easier access from vcfanno for variant annotation. I pushed a fix that I hope will resolve this for you both if you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
Thanks again for the report and hope this gets things working for you.

**Comment by razZ0r** [comment]
Hi, the scalpel findVariants command fails at exactly the same genomic region on the same sample with the same error as previously.

As the `./data/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py` file is updated, I was wondering what might be the problem. Does bcbio generates a new bam file, or it tries to pick up where it failed last time, without taking into account that it should skip high coverage regions now? If this is happening, I guess I need to clean up the `/pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1680/work/mutect/8/LUAD_1680-8_32674703_132228185-somaticIndels-scalpel-work/` directory. Am I right?

**Comment by chapmanb** [comment]
Endre;
Sorry this is still causing issues after the update. bcbio should generate a new BED file for the analysis with high depth regions excluded. You should be able to see in `log/bcbio-nextgen-commands.log` if it's using a different BED file which would indicate bcbio is applying the new code and trying to remove the high depth regions causing problems. If you have concerns you could remove everything related to this failing sample:
```
 rm /pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1680/work/mutect/8/LUAD_1680-8_32674703_132228185*
```
and that should ensure it uses the new BED files. Fingers crossed that will fix it.

**Comment by razZ0r** [comment]
Hi,

bcbio generates exactly the same files, and fails with the same error. I tried restarting it several times, even removed the full `/pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1680/work/mutect/8` directory, but no progress. findVariants fails just the same on the same region and the bam file is still 7.5 GB.

**Comment by razZ0r** [comment]
for the record: I downsampled the problematic large bam file in `/pico/scratch/userexternal/esebesty/bcbio_run/uuid_batch1680/work/mutect/8/` manually (50% ~8Gb -> ~4Gb) and restarted bcbio. It finished without additonal errors.

**Comment by chapmanb** [comment]
Endre;
Sorry that my fix didn't handle this but I'm glad you got your analysis finished. From the bcbio side I guess the best way to leave this now is that we can't run scalpel on really high depth BAMs. Hopefully this won't be a major limitation for anyone's analyses. Thanks again.

**Comment by ravenhall** [comment]
[SDBM](https://github.com/davidar/sdbm/blob/master/sdbm.c) is a hashed database library.
SPLTMAX can be set as an environment variable to control how many times SDBM will attempt to split an overfull page file. If the env var isn't set, it will only attempt once.
Try: `export SPLTMAX=1000` to allow 1,000 attempts.
