### ISSUE TITLE
Summarize total samples, batches, and their numbers in project-summary.yaml

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1547]
Very useful for internal project presentations. ;)

**Comment by chapmanb** [comment]
Luca -- the sample information should be present in the file along with the metadata batch information. Is that sufficient for your downstream analysis? We think of this file more as a starting point for custom downstream reporting than a ready to go presented analysis. Would post-processing what is in the summary file work for you?

**Comment by lbeltrame** [comment]
Likely, I was just being lazy... No problem if it stays that way.
