### ISSUE TITLE
Alternative gatk dir in resources configuration?

### ISSUE THREAD

**Issue by hliang** [chapmanb/bcbio-nextgen#1553]
In an older version of bcbio, it accepted new GATK path in YAML file (resources:gatk:dir). But this aproach does not work in the current version. bcbio is using an fixed path "/path/to/bcbio/anaconda/opt/gatk-3.6/". Or did I miss some other settings?

**Comment by chapmanb** [comment]
Sorry about the issues, the process to register the GATK jar did change to use `gatk-register` from `bioconda` so we can cleanly support GATK 3.6 and Java 8. The new approach for registering your downloaded jar is documented here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2

Hope this helps.

**Comment by hliang** [comment]
Thanks for the quick reply.

`gatk-register` seems to copy jar file into a fixed path. Running `gatk-register /path/to/nightlybuild/GenomeAnalysisTK.jar --noversioncheck` will copy the nightly jar file into `/path/to/bcbio/anaconda/opt/gatk-3.6/`. The destination seems to be always `/path/to/bcbio/anaconda/opt/gatk-3.6/`, no matter what version the jar file is.
In this process, `gatk`, which is a link pointing to `/path/to/bcbio/anaconda/opt/gatk-3.6/gatk.sh` is not touched. That means when `gatk` is called when running bcbio, it always runs `/path/to/bcbio/anaconda/opt/gatk-3.6/gatk.sh`.

What I expected (and used to work in release 0.9.9) was: different versions can be put in different paths, like
`/path/to/bcbio/anaconda/opt/gatk-3.6/` and `/path/to/bcbio/anaconda/opt/gatk-nightly-xyz/`, so different bcbio runs can pick different versions by specifying resources:gatk:dir in the yaml file.

**Comment by hliang** [comment]
The problem was (kind of) fixed in the latest version. When bcbio tries to run gatk, it first tests `/path/to/bcbio/bin/gatk` (which points to `/path/to/bcbio/anaconda/opt/gatk-3.6/gatk.sh`). If that works, it will use that path. If that `gatk` command fails, it will then try looking into `resources:gatk:dir:` specified in yaml config file.

So the reason why it didn't work for my runs was: I had a valid gatk jar in `/path/to/bcbio/anaconda/opt/gatk-3.6/` (previously done by `gatk-register` command). Once I remove the jar from that path, bcbio honors the one configured in yaml.

**Comment by chapmanb** [comment]
Thanks so much for following up with the answer to your own question. That's exactly right, it uses the gatk-register jar if that is present and otherwise will fall back to using the older method. So if you need to support multiple simultaneous versions of GATK in a single installation you would have to resort to using the old approach. Hope this gets your analyses working and thanks again.
