### ISSUE TITLE
pbspro --resources options not carried over to pbspro_controller

### ISSUE THREAD

**Issue by lorenzofarina** [chapmanb/bcbio-nextgen#1559]
pbspro --resources options aren't carried over to the pbspro_controller script.

${bcbio} ${yaml} -t ipython -s pbspro -q ${queue} -n ${cpu} \
        --timeout ${timeout} --retries ${retries} \
        --resources 'account=ELIX_prj6;walltime=100:00:00'

In the pbspro_controller script the lines referring to account and walltime are missing, the other inputs seem to be there as expected.

I installed the latest stable version on September 9

**Comment by razZ0r** [comment]
Hi, any update on this? We made it work with:

<pre>
git clone https://github.com/roryk/ipython-cluster-helper
git checkout -b working_pbs c668dd8
/pico/home/userexternal/esebesty/work/bcbio/data/anaconda/bin/python setup.py install
</pre>

So installed the last working version of the library that I know of.

**Comment by chapmanb** [comment]
Thanks for following up, I know @roryk has been looking at this but we're a bit hampered by not having a PBSPro machine to test on so it always relies on a bit of back and forth.

What version of ipython-cluster-helper were you using previously that did not work? Was it 0.5.3 or a previous version? It looks like your fix gives you version 0.5.2 and you'll need at least that version to have a working PBSPro since a bunch of fixes when in for that release. I'm trying to determine if there was a regression from 0.5.2 to 0.5.3 in your hands. Thanks much.

**Comment by lorenzofarina** [comment]
Hi,
the version of ipython-cluster-helper I was using was 0.5.1, and it was the one downloaded in with bcbio

**Comment by chapmanb** [comment]
Thanks for following up. Apologies, it sounded like you needed an upgrade since a lot of fixes for PBSPro were in the 0.5.2 version. If you only want to update ipython-cluster-helper you can do:
```
bcbio_conda install -c bioconda ipython-cluster-helper
```
Hope this gets things running smoothly for you.

**Comment by razZ0r** [comment]
So the latest stable version of bcbio still comes with ipython-cluster-helper 0.5.1 and you have to update it manually to have the pbspro support?

<pre>
[node1 bcbio-20160922 ]$ find . -name "*ipython-cluster-helper*" -print
./data/anaconda/conda-meta/ipython-cluster-helper-0.5.1-py27_0.json
./data/anaconda/pkgs/ipython-cluster-helper-0.5.1-py27_0.tar.bz2
./data/anaconda/pkgs/ipython-cluster-helper-0.5.1-py27_0
</pre>

 I thought 0.5.2 or 0.5.3 was already in bcbio. Anyway, we can update manually, thanks.

**Comment by chapmanb** [comment]
Endre -- bcbio should ship with the latest ipython-cluster-helper (0.5.3) and we don't have any restriction on the version. If you were updating conda doesn't always upgrade all packages so it's possible you got a bcbio upgrade without bumping the ipython-cluster-helper version. Sorry about the problems, hope the manual update fixes it for you.
