### ISSUE TITLE
joint_group_size breaks

### ISSUE THREAD

**Issue by hliang** [chapmanb/bcbio-nextgen#1564]
I had 160 WGS samples, and set `joint_group_size` to 60. bcbio combineGVCFs 54 merged gvcf files, 3 samples in each. Then it GenotypeGVCFs all 54 gvcf files together.
The behavior of merging 3 samples doesn't make sense to me. I thought it would generate 3 merged gvcf files, 60 samples in each.

**Comment by chapmanb** [comment]
Thanks for the questions. `joint_group_size` refers to the maximum number of samples feeding into GenotypeGVCFs so in this case it's doing small grouping to get < 60 samples as input to that process.
If you want to do more merging prior to genotyping you could set `joint_group_size: 3` which should behave the way you want. Out of curiosity, why do you want such fine grained control over the merging process? Are you running into issues during genotyping?

**Comment by hliang** [comment]
So I misunderstood `joint_group_size`. I thought it was the ~~"number of samples in each small group"~~, turns out it should be "(max) number of groups". Is that right?

Indeed, I had issue during genotyping and just submit another issue #1565 for that, in order not to hijack this thread.

**Comment by chapmanb** [comment]
That's exactly right. Thanks for the other problem report and I'll follow up in #1565
