### ISSUE TITLE
Wrong quality scores for GATK

### ISSUE THREAD

**Issue by eyalbenda** [chapmanb/bcbio-nextgen#1566]
Hi,

I'm getting an error when doing variant calling on a very high coverage illumina dataset:

> ##### ERROR MESSAGE: SAM/BAM/CRAM file htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter@5ed88e31 appears to be using the wrong encoding for quality scores: we encountered an extremely high quality score of 62. Please see https://www.broadinstitute.org/gatk/guide/article?id=6470 for more details and options related to this error.

I read that I should add a flag " --fix_misencoded_quality_scores" to GATK run. My problem is that I can't 
seem to find a way to add that option. I tried to add:

>    resources:
        gatk-haplotype:
          options: [--fix_misencoded_quality_scores]

To the config.yaml but it didn't do the trick. Is there a way to customize additional flags for specific tools? 

Thanks,

Eyal

**Comment by eyalbenda** [comment]
Just an update. I tried running again with "illumina" quality scores and got an error that the supplied quality scores are wrong. I changed a line in gatk.py to be:

>  if _joint_calling(items) or any("gvcf" in dd.get_tools_on(d) for d in items):
>                 params += ["--emitRefConfidence", "GVCF", "--variant_index_type", "LINEAR",
>                            "--variant_index_parameter", "128000","--fix_misencoded_quality_scores"]
> 
Not saying it's pretty but I'm trying it again, it might work?

**Comment by eyalbenda** [comment]
It didn't work, with an error that there is a mixture of valid and invalid quality values...

**Comment by chapmanb** [comment]
Eyal;
Thanks for the detailed report. It sounds like there is something problematic about your BAM file. How as it generated? If you have the original fastqs and know the quality encoding you could try aligning with bcbio instead of using the pre-aligned BAM. Alternatively you could use `bam_clean` to try and fix the input BAM:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

It sounds like something like:
```
aligner: false
bam_clean: picard
quality_format: illumina
```
might help rescue the BAM. Hope this helps.

**Comment by eyalbenda** [comment]
Thanks for the help.
I'm actually realigning the whole thing from fastq, and specifying quality_format: illumina gives an error early that the wrong quality format was specified. Also, as I wrote, having GATK fix the scores doesn't work either since apparently only some are incompatible and some aren't.
These are extremely high coverage sequencing of specific c. elegans strains, way beyond what you would get for human (because of the smaller genome). Could this cause higher qualities than expected and result in this error?

**Comment by chapmanb** [comment]
Eyal;
High depth won't affect the quality scores, those are individually encoded for each read. I'm not sure how you got a mix of different quality scores but it sounds like you'll have to resolve these to a single encoding prior feeding into bcbio. Most tools won't correctly handle a mix of encodings. 

You'd probably have to write something custom to split your fastq file into the different encodings and the wikipedia FASTQ page has a nice description of expected quality scores for each encoding:

https://en.wikipedia.org/wiki/FASTQ_format#Encoding

Hope this helps.

**Comment by eyalbenda** [comment]
Ok, thanks I understand now. Will try to figure this out.
