### ISSUE TITLE
how to force bam to stream directly to bwa?

### ISSUE THREAD

**Issue by brentp** [chapmanb/bcbio-nextgen#1567]
I see there is a function to do this, but I keep getting bamtofastq hitting the disk.
I tried save_diskpace: true, but that didn't work.

**Comment by chapmanb** [comment]
Brent;
We had code to support his previously but it's not currently active. Right now everything goes through a bgzipped fastq intermediate so we can parallelize with grabix extracted chunks of the fastq. We had a lot of issues with larger inputs and no splitting streaming directly into alignment. They would hang or run into hard to diagnose memory issues. We settled on the fastq intermediate as a more consistently working approach. We could try to revisit if it would help solve issues you're running into.

**Comment by brentp** [comment]
I'll close for now. The only reason I wanted it was to have samblaster output, but hopefully that won't be necessary soon.

**Comment by lpantano** [comment]
Hi @brentp 

I am closing this because it seems that won't change anytime soon, please feel free to open an issue if you find again the problem.

thanks!
