### ISSUE TITLE
upgrade can't find anaconda

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#1570]
The anaconda directory seems fine, any ideas?

```
$ bcbio_nextgen.py upgrade -u development
Upgrading bcbio
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 56, in upgrade_bcbio
    anaconda_dir = _update_conda_devel()
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 228, in _update_conda_devel
    assert conda_bin, "Could not find anaconda distribution for upgrading bcbio"
AssertionError: Could not find anaconda distribution for upgrading bcbio
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issues, my guess is that the install is using a different python than you expect so it's not finding conda in the install directory. I checked in a fix to have a better more useful error message in the future but for debugging now you might want to edit `/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py` right before the assertion to add:
```
print(os.path.realpath(sys.executable))
```
to determine what python it's using and why there isn't a conda executable at the same place as it. Hope this helps with debugging.

**Comment by dwaggott** [comment]
Ah thanks, I think the my paths got muddled again. Still this is expected no? 

```
$ bcbio_nextgen.py upgrade -u stable
Upgrading bcbio
/share/PI/euan/apps/bcbio/anaconda/bin/python2.7
Traceback (most recent call last):
  File "/share/PI/euan/apps/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 63, in upgrade_bcbio
    _update_conda_packages()
  File "/share/PI/euan/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 214, in _update_conda_packages
    assert conda_bin, "Could not find anaconda distribution for upgrading bcbio"
AssertionError: Could not find anaconda distribution for upgrading bcbio
```

**Comment by dwaggott** [comment]
Wait, another user tried to upgrade and created some conda files. This might be related to a permissions conflict.

**Comment by chapmanb** [comment]
Daryl;
That does look right to me, but for some reason bcbio is not finding `/share/PI/euan/apps/bcbio/anaconda/bin/conda`. If it's not a permission or missing file issue then happy to try and dig into what is happening with more information. Hope this helps.

**Comment by dwaggott** [comment]
Right, it seems to have vanished. Maybe a failed partial upgrade? All I see is:

 /share/PI/euan/apps/bcbio/anaconda/bin/conda-env

**Comment by chapmanb** [comment]
Daryl;
I'm not sure how that happened since I haven't seen upgrades end up in this state. Practically your best bet would be to remove the broken anaconda directory and run a new install:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

pointing bcbio at your existing data directory to avoid needing to re-download/re-prepare that. Hope this gets your installation running.

**Comment by dwaggott** [comment]
All clear. It was a permissions conflict on a conda install temp file that
made things go pear shaped. Thanks!
