### ISSUE TITLE
vep annotation fields + hgvs

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1571]
Hi Brad, 

just a quick question. Is there a reason you omitted some VEP annotation options during that step?
Wouldn't it be possible to just use the "--everything" option to maximize the annotations VEP performs?

also, has there been any further thoughts on fixing the hgvs notations when using VEP? Since the reference fasta is already included in bcbio, I don't think it should be much of a problem to add this? Or are there any other reasons behind this? Any way we can help?

thanks
M

**Comment by chapmanb** [comment]
Thanks for digging into the VEP implementation. We didn't include all of the annotations as I know some of them can be quite slow and VEP already struggles a bit in terms of speed. We were also trying to synchronize VEP with GEMINI's parsing of attributes, although GEMINI can now more flexibly support additional fields.

We could add hgvs notation with fastas, although if I remember right that was one of the slower operations based on word of mouth. If you're able to add and benchmark additions to VEP to be sure they don't result in big slowdowns we'd be happy to add them in. Let us know what we can do to support this.

**Comment by matthdsm** [comment]
Hi Brad,

thanks for the time. I feel like the HGVS should be enabled, regardless of slowdown. VEP provides the most relevant annotations for diagnostics use, but without the HGVS notation it's very hard to report the variant (some clinicians are VERY stubborn when it comes to adopting newer things). Since snpEff provides a good HGVS notation, I think VEP should have the same ability.
Maybe it's possible to add a warning or disclaimer in de manual for a possible slowdown? Anyways `clinical_reporting` is optional, so if it's documented, people using the option know what they're getting into.

How do you propose we set up a development instance? Is there a possibility for unit tests in the bcbio framework? Or do we just benchmark VEP on it's own?

thanks
M

**Comment by pfpjs** [comment]
I second the request for HGVS notation with VEP.

Also, from my experience, VEP isn't slow at all when comparing to the rest of the pipeline: for annotating a WES sample, it takes just a few minutes (32 core machine, with VEP using 17 cores as configured automatically by bcbio_nextgen):

```
[2016-08-21T05:31Z] Calculating variation effects for Uni29500, gatk-haplotype
[2016-08-21T05:31Z] Ensembl variant effect predictor : Uni29500
[2016-08-21T05:33Z] tabix index Uni29500-vepeffects.vcf.gz
[2016-08-21T05:33Z] Annotate VCF file: Uni29500, gatk-haplotype
[2016-08-21T05:33Z] Filtering for Uni29500, gatk-haplotype
[2016-08-21T05:33Z] Hard filtering /path/to/Uni29500-vepeffects.vcf.gz with TYPE="snp" && (MQ < 30.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0 || QD < 2.0 || FS > 60.0) : Uni29500
[2016-08-21T05:33Z] tabix index Uni29500-vepeffects-filterSNP.vcf.gz
[2016-08-21T05:33Z] Hard filtering /path/to/Uni29500-vepeffects-filterSNP.vcf.gz with TYPE="indel" && (ReadPosRankSum < -20.0 || QD < 2.0 || FS > 200.0) : Uni29500
[2016-08-21T05:33Z] tabix index Uni29500-vepeffects-filterSNP-filterINDEL.vcf.gz
[2016-08-21T05:33Z] Remove stray NON_REF gVCF information from VCF output : Uni29500
[2016-08-21T05:34Z] tabix index Uni29500-vepeffects-filterSNP-filterINDEL-gatkclean.vcf.gz
[2016-08-21T05:34Z] Prioritization for Uni29500, gatk-haplotype
[2016-08-21T05:34Z] Germline extraction for Uni29500, gatk-haplotype
[2016-08-21T05:34Z] Finalizing variant calls: Uni29501, gatk-haplotype
[2016-08-21T05:34Z] Calculating variation effects for Uni29501, gatk-haplotype
```

**Comment by matthdsm** [comment]
Alternatively, would it be possible to modify the annotation with snpEff to include snpSift with dbNSFP? I realize this has already been discussed before, but it would be a huge improvement and bring the snpEff annotations on par with VEP.

M

**Comment by chapmanb** [comment]
Thanks for all the thoughts. I pushed a fix with HGVS support for VEP when `clinical_reporting: true` is set in the configuration. The one concern I had was about VEP trying to index FASTA files and potentially needing access to the install directories, but this didn't seem to be the case with small test runs so it might only need the standard indices we already have in place.

It would be great if you could take this for a test run and report any issues. I'll be especially interested in your experience with larger WGS runs which is where we often see VEP being slower.

We could also explore SnpSift/dbNSFP if we want to expand the snpEff side as well, so happy to try and tackle that if it would be useful beyond this.

Thanks again for all the suggestions and discussion.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for the fix, I'll make sure to test this and report back as soon as we start another run!

M

**Comment by pfpjs** [comment]
Thank you Brad!

I'm currently running a WES sample and will report back in a couple of hours.

**Comment by pfpjs** [comment]
Sorry for taking longer than expected reporting back. 

The run completed successfully but VEP annotations (including HGVS) are missing from the VCF CSQ field, but are present in the header:

```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Consequence|Codons|Amino_acids|Gene|SYMBOL|Feature|EXON|PolyPhen|SIFT|Protein_position|BIOTYPE|CANONICAL|CCDS|RadialSVM_score|RadialSVM_pred|LR_score|LR_pred|MutationTaster_score|MutationTaster_pred|FATHMM_score|FATHMM_pred|PROVEAN_score|PROVEAN_pred|MetaSVM_score|MetaSVM_pred|CADD_raw|CADD_phred|Reliability_index|LoF|LoF_filter|LoF_flags|HGVS">
(...)
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Uni24979
1	2337032	rs1129171	C	T	635.77	PASS	AC=1;AF=0.5;AN=2;BaseQRankSum=-2.183;ClippingRankSum=0;DB;DP=36;ExcessHet=3.0103;FS=12.08;MLEAC=1;MLEAF=0.5;MQ=60;MQ0=0;MQRankSum=0;QD=17.66;ReadPosRankSum=2.283;SOR=0.031;CSQ=3_prime_UTR_variant|||ENSG00000157911|PEX10|ENST00000288774|6/6|||-/346|protein_coding|YES|CCDS41.1|||||||||||||||||||	GT:AD:DP:GQ:PL	0/1:15,21:36:99:664,0,469
(...)
```
Digging through the log, VEP runs successfully and is called with (it seems to me) the correct arguments:

```
[2016-09-27T15:51Z] unset PERL5LIB && export PATH=/path/to/bcbio/anaconda/bin:$PATH && /path/to/bcbio/anaconda/bin/variant_effect_predictor.pl --vcf -o stdout -i /path/to/work/gatk-haplotype/Uni24979.vcf.gz --fork 17 --species homo_sapiens --no_stats --cache --offline --dir /path/to/bcbio/genomes/Hsapiens/GRCh37/vep --symbol --numbers --biotype --total_length --canonical --gene_phenotype --ccds --fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,RadialSVM_score,RadialSVM_pred,LR_score,LR_pred,MutationTaster_score,MutationTaster_pred,FATHMM_score,FATHMM_pred,PROVEAN_score,PROVEAN_pred,MetaSVM_score,MetaSVM_pred,CADD_raw,CADD_phred,Reliability_index,LoF,LoF_filter,LoF_flags,HGVS --sift b --polyphen b --plugin dbNSFP,/path/to/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFP.txt.gz,RadialSVM_score,RadialSVM_pred,LR_score,LR_pred,MutationTaster_score,MutationTaster_pred,FATHMM_score,FATHMM_pred,PROVEAN_score,PROVEAN_pred,MetaSVM_score,MetaSVM_pred,CADD_raw,CADD_phred,Reliability_index --plugin LoF,human_ancestor_fa:/path/to/bcbio/genomes/Hsapiens/GRCh37/variation/human_ancestor.fa.gz --pick --hgvs --shift_hgvs 1 --fasta /path/to/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa | sed '/^#/! s/;;/;/g' | bgzip -c > /path/to/work/gatk-haplotype/tx/tmpAGy0st/Uni24979-vepeffects.vcf.gz
```
My config YAML file is as follows:

```
details:
- algorithm:
    align_split_size: false
    aligner: bwa
    clinical_reporting: true
    coverage: /path/to/coverage-kit.bed
    coverage_interval: regional
    effects: vep
    mark_duplicates: true
    platform: illumina
    realign: gatk
    recalibrate: gatk
    remove_lcr: false
    tools_on:
    - qualimap_full
    - multiqc
    variant_regions: /path/to/genes-of-interest.bed
    variantcaller: gatk-haplotype
  analysis: variant2
  description: Uni24979
  files:
  - ../24979_1.fastq.gz
  - ../24979_2.fastq.gz
  genome_build: GRCh37
```

I updated `bcbio_nextgen` as of 3 days ago, and I used the following command to do so:

```
bcbio_nextgen.py upgrade -u development \
    --tools  --tooldir bcbio-tools/ \
    --data --datatarget variation \
    --datatarget gemini \
    --datatarget cadd \
    --datatarget vep \
    --datatarget dbnsfp \
    --datatarget rnaseq \
    --datatarget smallrna \
    --genomes GRCh37 \
    --genomes hg19 \
    --genomes hg38 \
    --genomes hg38-noalt
```

**Comment by chapmanb** [comment]
Paulo -- thanks for testing and sorry about the issues. Apologies, I missed that VEP outputs protein and DNA (.p and .c) HGVS and need naming specifically for that. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
remove the previously annotated files (`rm -f */*vepeffects*`) and re-run it should hopefully do the right thing now. Please let us know if you run into any other issues.

**Comment by pfpjs** [comment]
Thank you Brad - I've just fired up another analysis with 12 samples, which will run over the weekend, and I'll post again as soon as I get my hands on the resulting VCFs.

Thank you again!

**Comment by pfpjs** [comment]
Hi,

HGVSc and HGVSp are working correctly now:

```
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Consequence|Codons|Amino_acids|Gene|SYMBOL|Feature|EXON|PolyPhen|SIFT|Protein_position|BIOTYPE|CANONICAL|CCDS|RadialSVM_score|RadialSVM_pred|LR_score|LR_pred|MutationTaster_score|MutationTaster_pred|FATHMM_score|FATHMM_pred|PROVEAN_score|PROVEAN_pred|MetaSVM_score|MetaSVM_pred|CADD_raw|CADD_phred|Reliability_index|LoF|LoF_filter|LoF_flags|HGVSc|HGVSp">
(...)
1	63881552	rs4630153	C	T	780.77	PASS	AC=1;AF=0.5;AN=2;BaseQRankSum=-1.419;ClippingRankSum=0;DB;DP=75;ExcessHet=3.0103;FS=0.908;MLEAC=1;MLEAF=0.5;MQ=60;MQ0=0;MQRankSum=0;QD=10.7;ReadPosRankSum=1.173;SOR=0.906;CSQ=missense_variant|tCt/tTt|S/F|ENSG00000088035|ALG6|ENST00000371108|11/15|benign(0)|tolerated(0.32)|304/507|protein_coding|YES|CCDS30735.1|||||||||||||||||||ENST00000371108.4:c.911C>T|ENSP00000360149.4:p.Ser304Phe	GT:AD:DP:GQ:PL	0/1:38,35:73:99:809,0,986
```

However, some VEP annotations are still missing, namely:

RadialSVM_score|RadialSVM_pred|LR_score|LR_pred|MutationTaster_score|MutationTaster_pred|FATHMM_score|FATHMM_pred|PROVEAN_score|PROVEAN_pred|MetaSVM_score|MetaSVM_pred|CADD_raw|CADD_phred|Reliability_index|LoF|LoF_filter|LoF_flags

Did anyone come across this before? I believe these come from dbNSFP, which is installed correctly. I'll test running VEP directly on a small VCF, trying different command line arguments (the VEP command bcbio runs is displayed above - https://github.com/chapmanb/bcbio-nextgen/issues/1571#issuecomment-250435581 ) but I need to spend my time on more pressing issues at the moment. If I manage to fix this I'll post to let everyone know.

Thanks again for implementing HGVS notation with VEP!

**Comment by matthdsm** [comment]
Hi Paulo,

Thanks for confirming this works! (Haven't had a chance to test). We also noticed the missing dbNSFP annotations when using vep. I hope you'll be able to fix it!

M

**Comment by matthdsm** [comment]
Hi @chapmanb , @pfpjs 

I did some tests with vep and got the following error:
```
[E::get_intv] failed to parse TBX_GENERIC, was wrong -p [type] used?
The offending line was: "#chr   pos(1-based)    ref     alt     aaref   aaalt   rs_dbSNP144     hg19_chr        hg19_pos(1-based)       hg18_chr        hg18_pos(1-based)       genename        cds_strand      refcodon        codonpos        codon_degeneracy        Ancestral_allele        AltaiNeandertal Denisova     Ensembl_geneid   Ensembl_transcriptid    Ensembl_proteinid       aapos   SIFT_score      SIFT_converted_rankscore        SIFT_pred       LRT_score       LRT_converted_rankscore LRT_pred        LRT_Omega       MutationTaster_score    MutationTaster_converted_rankscore      MutationTaster_pred     MutationTaster_model MutationTaster_AAE       Uniprot_id_MutationAssessor     Uniprot_variant_MutationAssessor        MutationAssessor_score  MutationAssessor_rankscore      MutationAssessor_pred   FATHMM_score    FATHMM_converted_rankscore      FATHMM_pred     PROVEAN_score   PROVEAN_converted_rankscore     PROVEAN_pred    fathmm-MKL_coding_score       fathmm-MKL_coding_rankscore     fathmm-MKL_coding_pred  fathmm-MKL_coding_group MetaSVM_score   MetaSVM_rankscore       MetaSVM_pred    MetaLR_score    MetaLR_rankscore        MetaLR_pred     Reliability_index       integrated_fitCons_score        integrated_fitCons_rankscore    integrated_confidence_value   GM12878_fitCons_score   GM12878_fitCons_rankscore       GM12878_confidence_value        H1-hESC_fitCons_score   H1-hESC_fitCons_rankscore       H1-hESC_confidence_value        HUVEC_fitCons_score     HUVEC_fitCons_rankscore HUVEC_confidence_value  GERP++_NR       GERP++_RS       GERP++_RS_rankscore     phyloP7way_vertebrate phyloP7way_vertebrate_rankscore phyloP20way_mammalian   phyloP20way_mammalian_rankscore phastCons7way_vertebrate        phastCons7way_vertebrate_rankscore      phastCons20way_mammalian        phastCons20way_mammalian_rankscore      SiPhy_29way_pi  SiPhy_29way_logOdds     SiPhy_29way_logOdds_rankscore1000Gp3_AC       1000Gp3_AF      1000Gp3_AFR_AC  1000Gp3_AFR_AF  1000Gp3_EUR_AC  1000Gp3_EUR_AF  1000Gp3_AMR_AC  1000Gp3_AMR_AF  1000Gp3_EAS_AC  1000Gp3_EAS_AF  1000Gp3_SAS_AC  1000Gp3_SAS_AF  TWINSUK_AC      TWINSUK_AF      ALSPAC_AC       ALSPAC_AF       ESP6500_AA_AC   ESP6500_AA_AF   ESP6500_EA_AC   ESP6500_EA_AFExAC_AC  ExAC_AF ExAC_Adj_AC     ExAC_Adj_AF     ExAC_AFR_AC     ExAC_AFR_AF     ExAC_AMR_AC     ExAC_AMR_AF     ExAC_EAS_AC     ExAC_EAS_AF     ExAC_FIN_AC     ExAC_FIN_AF     ExAC_NFE_AC     ExAC_NFE_AF     ExAC_SAS_AC     ExAC_SAS_AF     clinvar_rs      clinvar_clnsig  clinvar_trait   Interpro_domain GTEx_V6_gene GTEx_V6_tissue"
[=======================>                       ]   [ 54% ][E::get_intv] failed to parse TBX_GENERIC, was wrong -p [type] used?
The offending line was: "#chr   pos(1-based)    ref     alt     aaref   aaalt   rs_dbSNP144     hg19_chr        hg19_pos(1-based)       hg18_chr        hg18_pos(1-based)       genename        cds_strand      refcodon        codonpos        codon_degeneracy        Ancestral_allele        AltaiNeandertal Denisova     Ensembl_geneid   Ensembl_transcriptid    Ensembl_proteinid       aapos   SIFT_score      SIFT_converted_rankscore        SIFT_pred       LRT_score       LRT_converted_rankscore LRT_pred        LRT_Omega       MutationTaster_score    MutationTaster_converted_rankscore      MutationTaster_pred     MutationTaster_model MutationTaster_AAE       Uniprot_id_MutationAssessor     Uniprot_variant_MutationAssessor        MutationAssessor_score  MutationAssessor_rankscore      MutationAssessor_pred   FATHMM_score    FATHMM_converted_rankscore      FATHMM_pred     PROVEAN_score   PROVEAN_converted_rankscore     PROVEAN_pred    fathmm-MKL_coding_score       fathmm-MKL_coding_rankscore     fathmm-MKL_coding_pred  fathmm-MKL_coding_group MetaSVM_score   MetaSVM_rankscore       MetaSVM_pred    MetaLR_score    MetaLR_rankscore        MetaLR_pred     Reliability_index       integrated_fitCons_score        integrated_fitCons_rankscore    integrated_confidence_value   GM12878_fitCons_score   GM12878_fitCons_rankscore       GM12878_confidence_value        H1-hESC_fitCons_score   H1-hESC_fitCons_rankscore       H1-hESC_confidence_value        HUVEC_fitCons_score     HUVEC_fitCons_rankscore HUVEC_confidence_value  GERP++_NR       GERP++_RS       GERP++_RS_rankscore     phyloP7way_vertebrate phyloP7way_vertebrate_rankscore phyloP20way_mammalian   phyloP20way_mammalian_rankscore phastCons7way_vertebrate        phastCons7way_vertebrate_rankscore      phastCons20way_mammalian        phastCons20way_mammalian_rankscore      SiPhy_29way_pi  SiPhy_29way_logOdds     SiPhy_29way_logOdds_rankscore1000Gp3_AC       1000Gp3_AF      1000Gp3_AFR_AC  1000Gp3_AFR_AF  1000Gp3_EUR_AC  1000Gp3_EUR_AF  1000Gp3_AMR_AC  1000Gp3_AMR_AF  1000Gp3_EAS_AC  1000Gp3_EAS_AF  1000Gp3_SAS_AC  1000Gp3_SAS_AF  TWINSUK_AC      TWINSUK_AF      ALSPAC_AC       ALSPAC_AF       ESP6500_AA_AC   ESP6500_AA_AF   ESP6500_EA_AC   ESP6500_EA_AFExAC_AC  ExAC_AF ExAC_Adj_AC     ExAC_Adj_AF     ExAC_AFR_AC     ExAC_AFR_AF     ExAC_AMR_AC     ExAC_AMR_AF     ExAC_EAS_AC     ExAC_EAS_AF     ExAC_FIN_AC     ExAC_FIN_AF     ExAC_NFE_AC     ExAC_NFE_AF     ExAC_SAS_AC     ExAC_SAS_AF     clinvar_rs      clinvar_clnsig  clinvar_trait   Interpro_domain GTEx_V6_gene GTEx_V6_tissue"

```
Which leads me to believe the dbNSFP issue is caused by how dbNSFP was parsed initially during the installation step. I tested the script with a version of dbNSFP2.9 we use for Galaxy and the error message was gone.

We encountered this error before and according to the ensembl helpdesk, dbNSFP should be processed as follows:

```
unzip dbNSFPv3.0a.zip
head -n1 dbNSFP3.0a_variant.chr1 > dbNSFPv3.0a.txt
cat dbNSFP3.0a_variant.chr* | grep -v ^# >> dbNSFPv3.0a.txt
bgzip dbNSFPv3.0a.txt > tabix -s 1 -b 2 -e 2 dbNSFPv3.0a.txt.gz
```

The docs inside the perl module for dbNSFP say we have to do this:
```
wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFPv3.0b2a.zip
unzip dbNSFPv3.0b2a.zip
cat dbNSFP*chr* | bgzip -c > dbNSFP.gz
tabix -s 1 -b 2 -e 2 dbNSFP.gz
```

I'm not sure how dbNSFP gets processed on the bcbio side, but I think that might be the issue.

**Comment by chapmanb** [comment]
Thanks for following up on checking with dbNSFP and VEP. Apologies, I don't use this functionality much so need to spin up a test case with all the downloads so I can help. Practically, this is how we prepare dbNSFP which is meant to follow this preparation scheme:

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/GRCh37/dbnsfp.yaml

Thanks again for looking at this and helping with fixes.

**Comment by matthdsm** [comment]
I'd also like to propose some more changes and additions to VEP. If possible, I'd like to add some plugins to get splice site predictions, and I'd like to add some more fields to dbNSFP

Here I go:

### VEP Plugins
#### dbNSFP
- fields currently in use:

 ```
 "RadialSVM_score", "RadialSVM_pred", "LR_score", "LR_pred", "MutationTaster_score", "MutationTaster_pred", "FATHMM_score", "FATHMM_pred", "PROVEAN_score", "PROVEAN_pred", "MetaSVM_score", "MetaSVM_pred","CADD_raw", "CADD_phred", "Reliability_index"
 ```
- fields needed (still subject to change):

```
"LRT_score","LRT_pred","MutationTaster_score","MutationTaster_pred","FATHMM_score","FATHMM_pred","PROVEAN_score","PROVEAN_pred","MetaSVM_score","MetaSVM_pred","MetaLR_score","MetaLR_pred","Reliability_index","CADD_raw","CADD_phred","clinvar_rs","clinvar_clnsig","clinvar_trait"
```

#### LoF
- no modifications needed

#### dbSscSNV
- plugin url: `https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/86/dbscSNV.pm`
- available from dbNSFP: `wget ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbscSNV.zip`
- process as follows:
```
unzip dbscSNV.zip && \
head -n1 dbscSNV.chr1 > /dev/null && \
cat dbscSNV.chr* | grep -v ^chr | cat h - | bgzip -c > dbscSNV.txt.gz && \
tabix -s 1 -b 2 -e 2 -c c dbscSNV.txt.gz && \
rm dbscSNV.chr*
```
- usage: `--plugin dbscSNV,/path/to/dbscSNV.txt.gz`

#### GeneSplicer
- plugin url: `https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/86/GeneSplicer.pm`
- available from John Hopkins: `wget ftp://ccb.jhu.edu/pub/software/genesplicer/GeneSplicer.tar.gz`
- unpack to directory
- usage: `--plugin GeneSplicer,/path/to/genesplicer/bin,/path/to/genesplicer/human,[context=100],[cache_size=50],[tmpdir=/tmp]`

#### MaxEntScan
- plugin url: `https://raw.githubusercontent.com/Ensembl/VEP_plugins/release/86/MaxEntScan.pm`
- available from MIT: `wget -O MaxEntScan.tar.gz http://genes.mit.edu/burgelab/maxent/download/fordownload.tar.gz`
- unpack to directory
- usage: `--plugin MaxEntScan,/path/to/maxentscan/dir`


Do you suppose it would be viable to integrate this? I suppose we'd need to write some bioconda recipes for the external software (GeneSplicer & MaxEntscan) to be able to add those in easily. To use dbscSNV we could leverage cloudbiolinux the same way you do for dbNSFP.

Any thoughts? I'm currently still testing the plugins with VEP, but I'm convinced these would be useful additions

**Comment by chapmanb** [comment]
This all sounds like good functionality to add, thank you for the suggestions. My main concern is complexity of maintenance as we're introducing a lot of moving parts into VEP runs. If you're willing to take this on, we'd be happy to integrate it and help with setting things up. Thanks much for looking at these.

**Comment by matthdsm** [comment]
As you know, I've already modified the conda recipe for VEP to use the latest version, and to include the needed plugins. I've also already created a conda recipe for GeneSplicer, and the one for MaxEntScan is in the works. The only dependency left is the download of dbSCNV, which presents the same issue as dbNSFP, although it's a fair bit smaller. I thinks it's doable, provided we can get VEP to annotate everything correctly (still working on the missing annotations @pfpjs reported)

**Comment by matthdsm** [comment]
and once all of that checks out, we'll need to figure out a way to get all those annotations into gemini. If I'm understanding the source code correctly, Gemini only supports a a fixed set of annotations, which I think is too bad. Gemini seems a really great platform, but loses a lot of it's usefulness in our case if we don't have the complete set of annotations VEP will be able to provide. As you're also involved in the development of Gemini, do you suppose that is something that will be made possible in the future? Or am I just completely misunderstanding the inner workings?

**Comment by brentp** [comment]
I'll try to get into the next gemini release to support any VEP annotations.

**Comment by matthdsm** [comment]
That would be awesome! Thank you for you work!

**Comment by ohofmann** [comment]
@brentp -- shouldn't this already be resolved by Gemini "2.0"? I.e., as long as it's in the VCF it would get picked up? We (well, Rory) are in the process of migrating things over.

**Comment by brentp** [comment]
@ohofmann 
In this case, no, because there is special parsing for VEP and SnpEff stuff since those are all smashed into a single INFO field.
I recently made updates the `geneimpacts` module to ease this, but haven't had time to complete the integration yet. Once that's done, it will also be in `vcf2db.py` since that also uses geneimpacts.

**Comment by ohofmann** [comment]
Got it. Looking forward to this, then!

**Comment by brentp** [comment]
I just pushed changes to geneimpacts and vcf2db that add extra VEP fields to the database.

**Comment by matthdsm** [comment]
Allright! Awesome, I'm testing this immediatly!

**Comment by matthdsm** [comment]
Hi @brentp 

When I'm trying to create a new db, I'm getting the following error

```
[pbsqueue] matdsmet:results $ python ../vcf2db/vcf2db.py D1106193-vep-dbnsfp-maxentscan-genesplicer-dbscSNV.vcf.gz ../D1106193.ped D1106193-vep-vcf2db.db                                                                                                                                                           [8:42:21]
skipping 'AC' because it has Number=A
skipping 'AF' because it has Number=A
skipping 'MLEAC' because it has Number=A
skipping 'MLEAF' because it has Number=A
/home/galaxy/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '1'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
/home/galaxy/bcbio/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value ''. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
Traceback (most recent call last):
  File "../vcf2db/vcf2db.py", line 806, in <module>
    VCFDB(a.VCF, a.db, a.ped, black_list=a.info_exclude, expand=a.expand, blobber=main_blobber)
  File "../vcf2db/vcf2db.py", line 214, in __init__
    self.load()
  File "../vcf2db/vcf2db.py", line 278, in load
    i = self._load(self.cache, create=True, start=1)
  File "../vcf2db/vcf2db.py", line 271, in _load
    self.insert(variants, expanded, keys, i, create=create)
  File "../vcf2db/vcf2db.py", line 300, in insert
    v in variants)
  File "../vcf2db/vcf2db.py", line 763, in gene_info
    for k in impact.unused():
AttributeError: 'VEP' object has no attribute 'unused'

```
I suppose there's still a bug in the most recent changes? Thanks for trying to add in this functionality so quickly!

M

**Comment by matthdsm** [comment]
Seems to work nicely 👍 Would it be possible to update the requisite conda recipes? We'd like to take this into production

M

**Comment by brentp** [comment]
Thanks for testing. I'll plan to update this week. After I put it through the paces a bit more.

**Comment by matthdsm** [comment]
thanks!  Could you update this issue when you do?

**Comment by matthdsm** [comment]
Hi Brad,

In the mean time we've made some progress regarding VEP and dbNSFP. I'm sorry to say we've found a huge flaw in the use of dbNSFP. BCBIO uses by default dbNSFPv3.2c, and does so for every genome build. However, v3.2 in it's default form is incompatible with GRCh37/hg19. The coordinates used in the file, and used by tabix to get the annotation, are hg38 based. Therefore, if you annotate something based on GRCh37 with dbNSFPv3.2, you'll get faulty annotaties.

There are 2 possible fixes for this, but both mean there will have to be a separate version of dbNSFP per build.

- When using VEP and dbNSFP on GRCh37, the annotations should be sourced from dbNSFPv2.9.1. This is the latest version, based on GRCH37, and works out of the box with the VEP plugin.

- Alternatively, dbNSFPv3.2 could be changed to enable usage with GRCh37. v3.2 contains columns with the coordinates for hg19 and hg18. If we replace the `chr` and `pos(1-based)` columns with the `hg19_chr` and  `hg19_pos(1-based)` and reindex the file with tabix as usual, it should be compatible with hg19.

I'd appreciate your feedback on this as this has some serious implications on the results produced by the pipeline.

Thanks!
M

**Comment by chapmanb** [comment]
Thanks much for the dbNSFP work, you're right on that it is the likely issue. I pushed a fix to index this by the hg19 chromosome and coordinates instead, moved to the academic version, and adjusted to use Google Drive links as those are much faster for downloads:

https://github.com/chapmanb/cloudbiolinux/commit/52fbd82079398ea04bcdc94b5b11b0a242df2274

Could you give the latest version a try, and hopefully it will now do the right thing for you. Thanks again for the diagnosis and help debugging this.
