### ISSUE TITLE
HG38 and Gemini

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1573]
Hello again,

I was wondering if there are plans to overhaul the approach to gemini to support Hg38? According to [this thread](https://github.com/arq5x/gemini/issues/781) it's possible to use gemini with Hg38 using vcfanno and vcf2db. Do you think it is viable to replace the`gemini load` step with annotation by vcfanno and db loading with vcf2db? I suppose, this way it's possible to keep supporting hg19  and also build in some extra hg38 support.

M

**Comment by brentp** [comment]
Hi Matt, I'm not clear on what you are asking. As I stated in the other thread, you can load with vcf2db and that will be the way forward. To my knowledge the loader is stable and integrates with gemini well. We just haven't aggregated the annotations yet, but users can do that on their own and send to vcfanno.

**Comment by brentp** [comment]
oh, I just noticed this issue is in bcbio-nextgen. I just got a notice and assumed it was in gemini. Once we have everything in place, I will work to get it integrated into bcbio-nextgen.

We have a grad student working on aggregating annotations and developing the infrastructure for that now.

**Comment by ohofmann** [comment]
@roryk is working on this within bcbio. Some more testing to do, and I want to run a couple of GiaB runs and ICGC samples (exome, WGS) to get a sense of performance and edge cases. Should be integrated soon (tm).

**Comment by roryk** [comment]
It's on my TODO list but totally happy to have Brent work on it since he knows way more than me. Right now my progress was "the gem.conf in vcfanno seems to work ok on my test variant file".

**Comment by ohofmann** [comment]
@brentp Are you going to focus on somatic use cases at all? If not that's something we might be able to field...

**Comment by brentp** [comment]
no. we don't have any plans on somatic stuff. I am happy to help anywhere, as needed.

@roryk, I'll make a few updates to the gem.conf this week as we've found a few things that need tweaking.

**Comment by brentp** [comment]
I have just updated the gem.conf and custom.lua within the vcfanno repo.

**Comment by matthdsm** [comment]
Hi Brad,
I'd like to follow up on this question. Can Bcbio already create db's for analysis run on hg38? Or is that something that's still in the works? As it stands now, we let bcbio skip the gemini step and we then manually load the annotated vcf with vcf2db (which works great, parses the complete CSQ tag from vep). It would be great to have vcf2db integrated as an alternative to Gemini on hg38.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
I know Rory is working on this but don't know how close we are to having it in place. The major issue is likely having the external data sources organized and a vcfanno configuration file in place. Brent, is this already organized for hg19/hg38 or still a work in progress?

**Comment by brentp** [comment]
I will be happy to write the vcfanno config, but I don't have any of the annotation files currently. Can we enumerate them here as a start and then I can work on the conf file?

**Comment by matthdsm** [comment]
I feel like it should be a priority to be able to create db's on hg38. Perhaps it's possible to implement something intermediary? e.g. keep the gemini setup for GRCh37 and add vcf2db (without any extra annotations) for hg38. As it is now, vep and snpeff annotations are supported beautifully in vcf2db and it would be great to have those in a queryable platform.

**Comment by brentp** [comment]
I agree, @matthdsm that would be a sensible start and easy to build on. 
I can get clinvar: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/archive/2016
in there and ESP: http://evs.gs.washington.edu/evs_bulk_data/ESP6500SI-V2-SSA137.GRCh38-liftover.snps_indels.vcf.tar.gz

Is there a lifted ExAC anywhere?

**Comment by matthdsm** [comment]
Hi Brent, 

I'm not sure if vcfanno should handle population annotation, since vep already can do a lot of them. It would be a waste of time to duplicate the functionality (at least in the context of bcbio). I we ( or myself) keep the vep recipe up to date with the latest version, we can have recent annotations (and hg38 compatibility), without having to do much extra work. I feel the vcfanno effort should focus on integrating datasets that aren't handled by vep by default. (no example comes to mind, but perhaps something like CADD of HGMD would be valuable)

**Comment by schelhorn** [comment]
Hello all, thanks for bringing this up again; this thread touches many of the same points as one of my older issues https://github.com/chapmanb/bcbio-nextgen/issues/817 and I'm glad that we seem to converge on a solution here. 

What I see as a possible challenge are the different parallelapproaches that bcbio is or will be implementing: built-in prioritization with `vep` or `snpeff`, annotation in GEMINI, and the new `vcfanno` approach by the same authors. Wouldn't it be more maintainable and explicit to just support one way of doing it, preferably one that is well-maintained and that scales well? That may require some refactoring but will probably pay off in the long term. 

In general I like the `vcfanno` approach, since it seems to be very flexible to extend (just drop a new VCF or BED file in a folder, use everything in that folder to annotate), but going with GEMINI is nice as well due to the nice filtering capabilities. So I'm undecided myself.

**Comment by matthdsm** [comment]
Hi @schelhorn 

+1 on the going for a single approach, I believe most of the functionality of gemini already is duplicated in the vcfanno/vcf2db combo ( @brentp will surely have something more to say on that). As far as I know, any filtering done with gemini, can also be done on a vcf2db db, since they should be fully compatible.
I suppose, provided it's possible to procure the requisite reference sets, we should be able to eliminate the gemini dependency entirely, or at least for the loading step.

**Comment by schelhorn** [comment]
Excellent, @matthdsm.

**Comment by brentp** [comment]
yes, a vcf2db database should be compatible with current gemini (other than gene_summary tables). if not, it's likely a bug. Let me know if you need anything to move forward with this.

**Comment by chapmanb** [comment]
Thanks everyone for all the suggestions and help with this. I put together the initial framework to annotate with vcfanno and create databases with vcf2db. Currently, this allows us to create bare GEMINI databases (no extra annotations) for all non-hg19/GRCh37 organisms, including hg38. For now, I've stuck with the original approach for hg19/GRCh37 but the code should be easy to switch over as soon as it gets some additional testing.

As a next step, I'd like to include as many annotations as we have for hg38 and start building up hg19 equivalent functionality. I'll work on getting these installed in bcbio with ggd recipes, then we can build up a configuration. Currently we have dbsnp and clinvar:

https://github.com/chapmanb/cloudbiolinux/tree/master/ggd-recipes/hg38

Beyond that we can add ESP (from Brent's comments above) and ExAC (https://twitter.com/chrisamiller/status/817056726075719680). Are there other resources we should start with?

**Comment by schelhorn** [comment]
Great! Is there any way users could add custom VCFs and BEDs at analysis time in the mid term, or is that out of scope?

**Comment by matthdsm** [comment]
Hi all!
Great to hear there's been some serious progress 👍. I just got back from some time off and will start testing!

**Comment by matthdsm** [comment]
👍 on @schelhorn's suggestion. That would be a huge plus for us too.
I quickly went through to code and have a question. How will duplicate annotations be handled? Currently, vcfanno annotates with the ExAc vcf, but VEP can do this natively, of through dbNSFP. At some point, either one of these annotation sources will be updated, which could yield conflicting results. I see the same issue with dbsnp. Could we make this configurable? Perhaps something like this:
```
variant_db:  #either gemini or vcf2db, depending on reference
  annotations: [exac, dbsnp, all]
  custom_annotation_source: /path/to/custom/vcf
  custom annotation_config: /path/to/config.conf
```

This way, the user can decide where the annotations come from.

**Comment by matthdsm** [comment]
or I we want to support multiple custom annotations

```
variant_db:  #either gemini or vcf2db, depending on reference
  annotations: [exac, dbsnp, all]
  custom_annotation: [/path/to/custom/vcf,/path/to/config.conf]
  custom annotation: [/path/to/custom/bed,/path/to/config2.conf]

```

**Comment by matthdsm** [comment]
Also, it would be nice if we could decide wether or not to use the `expand` option. Using `expand` results in a slightly bigger db, but makes it possible to query the entire db with sqlite commands.

M

**Comment by chapmanb** [comment]
Sven-Eric and Matthias;
Thanks for all the thoughts and suggestions.

Having a way to plug in a custom annotation configuration instead of the default makes a lot of sense and I'll look at implementing that after the initial workflow is tested. Matthias, this should address your other concerns since you can tweak this to use whatever annotations you want in GEMINI. The nice thing about the vcfanno/vcf2db workflow is that it's completely abstracted. Here's our current hg38 configuration for vcfanno, which you could build off of to include/exclude other annotations as desired:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/vcfanno/hg38-gemini.conf

Regarding `--expand`, I could make this the default if there are not many downsides. @brentp -- what are the tradeoffs of having this in place? Is having it on by default reasonable? Also, would you be open to having an equivalent of the `--passonly` argument in vcf2db?

**Comment by brentp** [comment]
The downsides to `--expand` are increases in database size and load time. I think if n-samples is < 100 or so, then keeping it on is fine. However, it will fail with > 1000 or so samples because of limitations in the number of columns that sqlite allows.

I am hesitant to add `--passonly`, but not completely opposed. The same thing could be accomplished with grep or all records could be loaded and then filtered with sql for FILTER = 'PASS'. Can you expand more on why it's needed?

**Comment by chapmanb** [comment]
Brent -- thanks for the details on extend. Matthias, were you thinking to have everything expanded or only some fields? I might make this an option after all as vcf2db already looks like the bottleneck here and I don't want to make it even slower.

For `--passonly`, we found that most users were confused having all of the variants in the database. They'd forget to set FILTER and then ended up working with filtered variants. Having them in a database disconnects a bit from the VCF format, so it was most useful to load only passing ones and avoid this confusion. We could do it upstream during prep/decomposition if you'd rather not put it into vcf2db itself.

**Comment by matthdsm** [comment]
Hi Brad, Brent

Brad, if possible, I'd like to expand all fields. We're working on a lightweight GUI for gemini db's and eliminating Gemini itself from the dependencies saves us about 75% of the total size of the docker image, hence our preference to use SQL queries.

As for the vcfanno configuration, currently there isn't an option (as far as I know) to edit this post install.
Do you suppose it would be possible to eliminate the vcfanno config as a default, and add the current one as an example? The config can then be defined in the analysis yaml. That way, users can write their own config, based of the available examples and add/remove datasets as they please. If no config is present, the step is skipped or the default is used.

I realize this essentially removes some annotations that were default under GRCh37, but it increases the available options for the users, which for me personally takes preference, as long as it's documented.

**Comment by a113n** [comment]
I have created a customized branch of vcf2db and geneimpacts that allows me to include GRCh38 gene
annotations as well as supporting more fields in dbNSFP. [https://github.com/a113n/vcf2db/tree/gene_table?files=1](url)
[https://github.com/a113n/geneimpacts](url)

Hope that's useful for someone else who need GRCh38 support in vcf2db!

**Comment by chapmanb** [comment]
bcbio now supports generic creation of GEMINI databases for any organism using vcfanno/vcf2db, thank you all for the help getting this far. For hg38, we annotate with dbSNP, Clinvar, ExAC and ESP in addition to the fields in the INFO column.

Matthias, after the next release I'll work on making this more general so you can specify expansion and have a custom vcfanno configuration file. We'll use the one by default and then users can specify their own if they have specific needs that aren't covered.

@a113n -- thanks for sharing that. Would you be able to submit the geneimpacts and vcf2db changes upstream so Brent can include them? If so, we can update these packages and have the extra VEP fields included by default in bcbio creation.

I'll leave this issue open until we've satisfied the ability to have custom loading, but happy to have gotten this far. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for all the work! Does the vcf2db implementation support the `--expand`option? This is something that's quite important to us, since we have an interface that depends on SQL queries.

**Comment by chapmanb** [comment]
Matthias -- not yet, the plan is to work on `--expand` and custom annotations after the next release.

**Comment by a113n** [comment]
Hi Brad,

No problem! Looks like github is down now, I will issue a PR when github is
back online.

Allen

**Comment by matthdsm** [comment]
Hi all, 

Could I get a status update on the efforts for custom vcfanno configs? Has there been any work towards this at all?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
I haven't started on this yet but it was one of the final things I was hoping to finish prior to the next release so will hopefully work on it soon. Thanks for following up on it.

**Comment by matthdsm** [comment]
Ok, great to hear. As I said, I can provide a config for dbNSFP, which we've used without issue for about 50+ samples, so I think it's pretty well tested.

A possible solution for custom vcfanno configs could be by running vcfanno multiple times, or by simply concatenating all configs and then running vcfanno.

M

**Comment by chapmanb** [comment]
Matthias and all;
The latest development version now has the ability to use arbitrary vcfanno input configuration files, either supplementing or replacing the existing default gemini configuration. You enable this with the `vcfanno` key/value:
```
config:
  algorithm:
     vcfanno: [/your/vcfanno.conf]
```
More details and examples are in the documentation:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#variant-annotation

This happily wraps up all the points to support hg38 and generalized vcfanno in bcbio. Thanks for all the feedback and suggestions and please let us know if you run into any problems at all.

**Comment by matthdsm** [comment]
Hi Brad,

Great to hear! I'm updating right away.

M

**Comment by schelhorn** [comment]
Great, thanks everyone. Is there an bcbio example/test case already that contains a maximum number of annotations so people can see what is there?

**Comment by vladsaveliev** [comment]
Sven-Eric, I think this file contains quite a lot and looks like a good example: https://github.com/chapmanb/bcbio-nextgen/blob/master/config/vcfanno/hg38-gemini.conf

**Comment by matthdsm** [comment]
I've got a config file for everything JPOPGEN (dbNSFP & dbscSNV).
Can be found [here](https://gist.github.com/matthdsm/f68bbc0a6b7856a0f86bf33990a049e4).
I should add a disclaimer though. There are still some issues with the field names and the db import in vcf2db. More details @ quinlan-lab/vcf2db#27

M

**Comment by chapmanb** [comment]
Matthias;
Thanks much for putting this together. We can definitely work to incorporate once it's working cleanly for you.

Regarding parameters, we can also look at cleaning this up with the new approach. Right now we have:

- `effects`: This is only for effects prediction (snpEff, VEP) and does not change vcfanno and other annotations. Users may need effects and not vcfanno (or vice versa).
- `vcfanno`: Defines what annotations are used for vcfanno loading.
- `tools_off: [gemini]` Turns off vcfanno and GEMINI database creation
- `tools_on: [gemini_allvariants, db2vcf_expand]` Tunes behavior of GEMINI database loading

The current docs are here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#variant-annotation

The current gap I see is that you can't currently have vcfanno without subsequent GEMINI database creation using vcf2db. We may want to decouple these and make vcfanno the default annotation approach and then creation of a GEMINI database an optional step. What does everyone think?

**Comment by matthdsm** [comment]
Hi Brad, 
Thanks for commenting. Personally, I'd go with the decoupling approach, as this was the reason why vcfanno/vcf2db were created in the first place.
Perhaps something like this is doable:
- `effects: [snpEff,VEP,vcfanno]` Let the users decide which source for annotation they'd like to use, with the disclaimer that `snpEff` and `VEP` are mutually exclusive.
- `vcfanno: [gemini, custom.conf]`Defines what annotations are used for vcfanno loading, but only used when `vcfanno`is specified in the `effects` list. Maybe `dbNSFP`/`dbscSNV` can be added to the preconfigured annotations, either immediately (annotations work perfect) or when the issues with `vcf2db` are resolved.
- `tools_off: [gemini]` Only turns off db creation, be it `gemini`of `vcf2db`.
- ` tools_on: [gemini_allvariants, vcf2db_expand]` Tunes behavior of GEMINI database loading.

Cheers,
M

**Comment by chapmanb** [comment]
Matthias and all;
Thanks for the configuration discussion. I've been thinking about this and decided to use two parameters for vcfanno and GEMINI configuration:

- `tools_off: [gemini]` turns off default GEMINI database creation and also default vcfanno runs.
- `vcfanno: [gemini]` or `vcfanno: [/your/custom/ann.yaml]` turns on vcfanno independent of GEMINI usage.

`effects` behavior stays the same, since vcfanno is not really an effects prediction and is a completely different step in the process.

This makes it configurable with the minimum amount of tuning and special cases. Hope this makes sense and provides all the functionality everyone needs. Thanks again for all the help and discussion working on this.

**Comment by matthdsm** [comment]
Hi Brad, 
Thanks for all the work! Looking good to me 👍
