### ISSUE TITLE
covearge file for whole genome sequencing

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1577]
Hi Brad,

In exome samples we use the respective capture bed file to calculate coverage and variants. Now we are analyzing whole genome stuff and there is no exome capture step what are we suppose to give in the coverage and variants fields of the sample.yaml file?

Thanks,

**Comment by chapmanb** [comment]
Diya;
If it's not a capture experiment you don't need to include `coverage` and `variant_regions` in your YAML files. When you leave these out bcbio will do whole genome sequencing analysis and calculate regions to analyze based on coverage. Hope this helps.

**Comment by DiyaVaka** [comment]
thank you Brad. So for exome projects according to the bed file positions it calculates the coverage and variants, where as for whole genome projects it calculates coverage and variants on the entire genome?

**Comment by chapmanb** [comment]
Diya -- that's exactly right. It tackles the entire genome unless you restrict to specific regions.
