### ISSUE TITLE
"Checking sample YAML configuration" takes too long

### ISSUE THREAD

**Issue by hliang** [chapmanb/bcbio-nextgen#1579]
The "organize samples - Checking sample YAML configuration" step takes too long when a lot of samples are included. Each sample takes around 15 sec. One thousand samples would take >4 hours... I think I tracked this issue down to `gtf_to_bed` - this function generates the same bed file over and over again at the same path. I suggests a quick fix which skips making the file if it already exists.

`bcbio/rnaseq/gtf.py`:
```
            out_file = os.path.join(alt_out_dir, os.path.basename(out_file))
```

to 

```
            out_file = os.path.join(alt_out_dir, os.path.basename(out_file))
            if file_exists(out_file):
                return out_file
```

**Comment by chapmanb** [comment]
Apologies about the issue and thank you for identifying the problem. I pushed a fix that will hopefully resolve this if you update to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
Hope this gets things running for you.
