### ISSUE TITLE
resource unavailable and failed to open BAM errors

### ISSUE THREAD

**Issue by MengNiu** [chapmanb/bcbio-nextgen#1580]
Hi,

I repeatedly got this error after resubmitting the job. Please help. Thanks.

> [2016-09-27T20:36Z] ica1: Uncaught exception occurred
> Traceback (most recent call last):
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
>     _do_run(cmd, checks, log_stdout)
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 72, in _do_run
>     cmd, shell_arg, executable_arg = _normalize_cmd_args(cmd)
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 63, in _normalize_cmd_args
>     return "set -o pipefail; " + cmd, True, find_bash()
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 44, in find_bash
>     for test_bash in [find_cmd("bash"), "/bin/bash", "/usr/bin/bash", "/usr/local/bin/bash"]:
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 51, in find_cmd
>     return subprocess.check_output(["which", cmd]).strip()
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
>     process = Popen(stdout=PIPE, *popenargs, **kwargs)
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 1231, in _execute_child
>     self.pid = os.fork()
> OSError: [Errno 11] Resource temporarily unavailable
> [2016-09-27T20:36Z] ica1: Uncaught exception occurred
> Traceback (most recent call last):
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
>     _do_run(cmd, checks, log_stdout)
>   File "/home/mmn/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; /home/mmn/local/share/bcbio/galaxy/../anaconda/bin/sambamba view -F 'mapping_quality > 0' -L /home/mmn/p.fang/p.fang_agilent_16/work/align/p1tumor/p1tumor-sort-callable-split/p1tumor-sort-9-callable-coverageregions.bed -f bam -l 1 /home/mmn/p.fang/p.fang_agilent_16/work/align/p1tumor/p1tumor-sort.bam | /home/mmn/local/share/bcbio/galaxy/../anaconda/bin/bedtools genomecov -split -ibam stdin -bga -g /home/mmn/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa.fai > /home/mmn/p.fang/p.fang_agilent_16/work/align/p1tumor/p1tumor-sort-callable-split/tx/tmp4Ho5_U/p1tumor-sort-9-callable-genomecov.bed
> core.thread.ThreadError@/tmp/ldc/runtime/druntime/src/core/thread.d(3071): Error creating thread
> ----------------
> Failed to open BAM file stdin
> ' returned non-zero exit status 1
>

**Comment by chapmanb** [comment]
Meng;
This appears as if at least one of your worker nodes has run out of system resources. This is typically due to ulimit settings for open file handles:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#open-file-handles

bcbio tries to adjust file handles to avoid this, but if it doesn't have permissions or there are other tasks on `ica1` dominating resource usage the system can run out. The fix is to try and investigate what is happening on your machines and retry the pipeline. It will pick up where it left off once you have enough resources. Hope this helps.
