### ISSUE TITLE
FILTER 'REJECT' is not defined in the header 

### ISSUE THREAD

**Issue by JoKw** [chapmanb/bcbio-nextgen#1586]
Hi, I ran freebayes, scalpel, varscan and vardict for ensemble calling, but I ended up getting the error below. Is there any solution without rerunning the whole calling procedure from the beginning. Thanks

CalledProcessError: Command 'set -o pipefail; /usr/local/share/bcbio/anaconda/bin/bcftools concat --allow-overlaps -O z --file-list /test/work/scalpel/test-files.list -o /test/work/scalpel/tx/tmp8Vbs4E/NBvMB.vcf.gz
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header
[W::vcf_parse] FILTER 'REJECT' is not defined in the header

**Comment by chapmanb** [comment]
Apologies about the problem and thanks for the report. Would you be able to paste the entire error message, including information up and downstream of this? Right now I can't tell why the concat command fails. We have warning messages from bcftools but those shouldn't trigger a failure. There are probably some useful error messages upstream indicating why the GATK attempt at CatVariants failed and we fell back to bcftools concat that might be diagnostic. Thanks much for the help debugging.

**Comment by JoKw** [comment]
Hi Brad, I have sent the log files to your fastmail.

**Comment by chapmanb** [comment]
Johnny;
Thanks for the additional details, this helps a lot. `scalpel` is not supported as a standalone caller in bcbio, which is what triggers this error. It can only be used as a supplemental caller to add indels to SNP only callers (`mutect` currently). If you want to include it you could do with:
```
variantcaller: [freebayes, vardict, varscan, mutect]
indelcaller: scalpel
```
and that should work correctly. Alternatives you can remove `scalpel` from `variantcaller` and run with the other 3 callers.

Either way, you can edit your configuration and restart in place and it will pick up where it left off. Hope this helps.
