### ISSUE TITLE
With prefix "chr" and without prefix "chr" in the input bam files question

### ISSUE THREAD

**Issue by eudoraleer** [chapmanb/bcbio-nextgen#1587]
Why would there be a difference in the output file if I were **to use GRCh38 to assemble bam files having "chr" as prefix for chromosome numbers** vs **to use GRCh38 to assemble bam files having no "chr" as prefix for chromosome numbers**?

Thanks!

**Comment by chapmanb** [comment]
In bcbio, GRCh38/hg38 uses `chr` as the prefix for all chromosomes. Input files like BED regions need to use this convention. If you're trying to use pre-aligned BAMs they also need to be aligned to the same reference as bcbio uses. bcbio can realign from input BAMs and will automatically convert to fastq, so this is a good way around that.

In case this matters for your use: bcbio doesn't do assembly, the variant calling methods are alignment based.

Hope this helps.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers

**Comment by eudoraleer** [comment]
Thank you so much!
