### ISSUE TITLE
Resource: SV reference

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1592]
Feel free to close this issue if not relevant; this paper may help to validate SV events within bcbio: http://www.nature.com/articles/ncomms12989

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the pointer to this paper. That's an incredible amount of work into calling and consolidating structural variant calls. They provide the SV calls at a population level so we couldn't use them directly for validation but this would be a useful population to sanity check calls, especially in somatic SV calling. I could imagine using this similar to ExAC to prioritize variants not in high frequency in this population, as high frequency ones are likely to be background or gene representation issues. Thanks for starting this discussion.

**Comment by schelhorn** [comment]
True; I'll copy it over to my "normal" SV issue. 

Here's another set of SV calls from the NA reference, with a lot more (true?) indels, for the next indel benchmark: http://www.pacb.com/blog/identifying-structural-variants-na12878-low-fold-coverage-sequencing-pacbio-sequel-system/

**Comment by schelhorn** [comment]
I'm closing this and am keeping the reference in #963.
