### ISSUE TITLE
Validation report bug: only FreeBayes results are reported

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1596]
Hi bcbio-developers!

Thanks for the great pipeline.

When I'm running WES validation as described here
https://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#exome-with-validation-against-reference-materials
I see validation results in work/validate/NA12878-1
for ensemble, freebayes, gatk-haplotype, and samtools.
however work/validate/grading-summary-NA12878-1.csv contains only freebayes results,
and final/project and final/sample contains freebayes only as well.

All the variant calls in vcf and gemini.db files are present, it seems to be the validation report bug.

Could you please fix this?
Thanks,
SN

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issue, this was a problem with combining the validations in the output report and we put in a fix a couple of days ago:

https://github.com/chapmanb/bcbio-nextgen/commit/0a656c30f76b65be5af9acb168e2adea5322ca32

So upgrading the latest development (`bcbio_nextgen.py upgrade -u development`) and re-running in place (no need to delete anything) should fix the summary reports. You might want to wait a few hours to update as we're waiting to build a new package for goleft coverage calculation, but after that is in place there aren't any outstanding issues we know of in development. Hope this helps.

**Comment by naumenko-sa** [comment]
Thanks Brad.
