### ISSUE TITLE
Improvement for the validation report: please include tp_baseline in the statistics.

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1598]
Hi bcbio-developers!

Bcbio uses RTG Tools to calculate TP/FP/FN statistics.

rtg vcfeval according to RTG manual (p.34)
https://github.com/RealTimeGenomics/rtg-tools/blob/master/installer/resources/tools/RTGOperationsManual.pdf
produces 
```
• tp.vcf – contains those variants from the **calls** VCF which agree with variants in the baseline VCF
• tp-baseline.vcf – contains those variants from the **baseline** VCF which agree with variants in the
calls VCF. Thus, the variants in tp.vcf and tp-baseline.vcf are equivalent. This file can be used to
successively refine a highly sensitive baseline variant set to produce a consensus from several call sets.
• fp.vcf – contains variants from the **calls** VCF which do not agree with baseline variants.
• fn.vcf – contains variants from the **baseline** VCF which were not correctly called.
```
Could you please report all four numbers? TP, TP-Baseline, FP, and FN?

TP and TP-Baseline might be slightly different because the same variant might be reported
as 2 SNPs or 1 indel.
Then  TP+FN sums might have slightly different values for different callers,
because TP is based on **calls** and FN on **baseline**.
Some people are confused, because in theory TP+FN should be constant.
TP-baseline + FN is constant indeed.

At the same time, people also need TP, for example to sum up TP+FP from **calls**.

Thanks,
SN

**Comment by naumenko-sa** [comment]
It seems that bcbio uses TP-baseline for TP.

**Comment by chapmanb** [comment]
Sergey -- thanks for the suggestions and glad bcbio is doing the right thing for you. It can get a bit confusing with complex MNPs as those can match and be split in different ways but we try to provide the most consistent representation. Thanks again.
