### ISSUE TITLE
Expression quantitation: salmon vs sailfish

### ISSUE THREAD

**Issue by tomsing1** [chapmanb/bcbio-nextgen#1600]
I am curious: it seems that depending on which RNA-seq pipeline is used, either [sailfish](http://www.cs.cmu.edu/~ckingsf/software/sailfish/) or [salmon](https://combine-lab.github.io/salmon/) are used for quantitation. For example, the [fast_rnaseq](https://github.com/chapmanb/bcbio-nextgen/blob/9b019912e6d3a8ce580f1f63bbb4f15c51a1a574/bcbio/pipeline/rnaseq.py#L12) pipeline uses salmon, but the [quantitate](https://github.com/chapmanb/bcbio-nextgen/blob/9b019912e6d3a8ce580f1f63bbb4f15c51a1a574/bcbio/pipeline/rnaseq.py#L83) and [quantitate_expression_parallel](https://github.com/chapmanb/bcbio-nextgen/blob/9b019912e6d3a8ce580f1f63bbb4f15c51a1a574/bcbio/pipeline/rnaseq.py#L89) functions use sailfish. 

What is the rationale of not using salmon for both steps? Wouldn't it be nice to be able to compare output from fast (alignment-free) and slow (alignment) pipelines from the same tool (e.g. salmon)?

**Comment by roryk** [comment]
Hi Tom,

Thanks, good spot. Using Salmon for both makes good sense, especially since Salmon has a bunch of nice new options for correcting biases, we just haven't switched over yet.

**Comment by schelhorn** [comment]
+1 for broad use of Salmon. Any chance we can get gene fusion calling and disambiguation with it as well?

**Comment by tomsing1** [comment]
Awesome to hear that you are open to switching to Salmon. Any idea when you might have time to revisit this? I am planning an analysis and was wondering if it was worth waiting for.
