### ISSUE TITLE
Ensemble or joint calling for rare variants in a large cohort of families?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1601]
Dear bcbio developers and users!

Could you please share your experience when studying cohorts 
(rare germline variants)?

Is it better to run ensemble calling sample by sample, or joint calling?
Joint calling is caller specific, so you cannot run ensemble+joint, 
just 4 different joint runs, right?

Generally it is accepted that joint genotyping (multisample) is better, 
but it cannot be validated in my case.

Ensemble calling does a great job in terms of sensitivity, gatk best practices
say that some singletones may be lost with joint genotyping.

Would you expect any difference in sensitivity/specificity, or it is just a way to organize data,
one large gemini result database is better than 1000 small databases?

What do you think?
Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for starting this discussion. You're right that multisample calling and ensemble are not very compatible right now. My general suggestion would be to run either HaplotypeCaller or FreeBayes on the multisample batches and use those calls. Ensemble is more useful right now for trickier calling like somatic detection of low frequency variants and does less for population based calling where the callers are doing a good job. As you said, it also makes interpretation much easier as you have a single squared off VCF to assess call rates across variants for the full population. Hope this helps.

**Comment by naumenko-sa** [comment]
Thanks Brad;

Finally I'm running per-family (up to 3-4 samples) ensemble, because
- joint genotyping allows to rescue low coverage variants when evidence exists in the other sample,
at the same time it is less confident for singletons (rare mutations), when there is no evidence in other samples. We are interested in singletons in the project.
- it is easy to validate ensemble calls even for families (platinum exomes have families), but it is not so easy to validate joint genotyping: we don't have 100 platinum exomes, the only way is to mix platinum exomes and sequenced samples;
- it is hard to convince people, that mixing reads from different families makes sense. It is better to get high quality variants and then study allele frequencies in the population.

Sergey
