### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by tombair** [chapmanb/bcbio-nextgen#1602]
I have not encountered this before:

python bcbio_nextgen_install.py /Shared/Bioinformatics/data/bcbio --tooldir /Shared/Bioinformatics/data/bcbio --genomes GRCh37 -u stable
Checking required dependencies
Installing isolated base python installation
PREFIX=/Shared/Bioinformatics/data/bcbio/anaconda
installing: _cache-0.0-py27_x0 ...
bzip2: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
tar: Child returned status 127
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 245, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    anaconda = install_anaconda_python(args)
  File "bcbio_nextgen_install.py", line 98, in install_anaconda_python
    (os.path.basename(url), anaconda_dir), shell=True)
  File "/opt/python/2.7.10/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash Miniconda-latest-Linux-x86_64.sh -b -p /Shared/Bioinformatics/data/bcbio/anaconda' returned non-zero exit status 1

**Comment by tombair** [comment]
Looks like this is env dependent as I am able to install on a similar machine. I will close

**Comment by chapmanb** [comment]
Tom -- thanks for the report and following up. It looks like your system bzip2 is broken -- it's the one complaining about a missing libbz2.so.1.0. bcbio needs this to bootstrap the initial installation, so if you can fix that it should proceed cleanly after that. Hope this helps.
