### ISSUE TITLE
ERROR: WGS svhit samblaster

### ISSUE THREAD

**Issue by dmb107** [chapmanb/bcbio-nextgen#1604]
Hi, I've seen related posts about this issue, but did not find a resolution. I am running structural variation calling on a germline WGS. The pipeline finishes CNVkit, but fails at structural variation during the samblaster first step. I have tried troubleshooting by performing the initial samtools sort command, and it does produce a read id sorted bam file. Thank you for your help.

[2016-10-21T14:40Z] [bam_sort_core] merging from 461 files...
[2016-10-21T14:40Z] samblaster: Loaded 86 header sequence entries.
[2016-10-21T14:40Z] samblaster: Can't find first and/or second of pair in sam block of length 1 for id: ST-E00273:125:HJKGYCCXX:2:1101:1113:33656
[2016-10-21T14:40Z] samblaster: Are you sure the input is sorted by read ids?
[2016-10-21T14:40Z]
[2016-10-21T14:40Z] [bam_merge_core2] failed to write to output file.
[2016-10-21T14:40Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/nethome/dmb107/lab/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/nethome/dmb107/lab/apps/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /nethome/dmb107/lab/apps/bcbio/anaconda/bin/samtools sort -n -@ 1 -m 1G -O sam -T /scratch/projects//dmb107/CNV//work/tx/tmpQDRdCr/20_sorted-dedup-namesort /scratch/projects//dmb107/CNV//work/prealign/20/20_sorted-dedup.bam | /nethome/dmb107/lab/apps/bcbio/anaconda/bin/samblaster --addMateTags -M --splitterFile >(/nethome/dmb107/lab/apps/bcbio/anaconda/bin/samtools sort -@ 1 -m 1G -T /scratch/projects//dmb107/CNV//work/prealign/20/tx/tmpscugVF/20_sorted-dedup-dedup-sorttmp-spl -o /scratch/projects//dmb107/CNV//work/prealign//tx/tmpMOdZx7/20_sorted-dedup-sr.bam /dev/stdin) --discordantFile >(/nethome/dmb107/lab/apps/bcbio/anaconda/bin/samtools sort -@ 1 -m 1G -T /scratch/projects//dmb107/CNV//work/prealign/20/tx/tmpscugVF/20_sorted-dedup-dedup-sorttmp-disc -o /scratch/projects//dmb107/CNV//work/prealign//tx/tmpvCoz8_/20_sorted-dedup-disc.bam /dev/stdin) | /nethome/dmb107/lab/apps/bcbio/anaconda/bin/samtools view -b -S -u - | /nethome/dmb107/lab/apps/bcbio/anaconda/bin/sambamba sort  -t 1 -m 1G --tmpdir /scratch/projects//dmb107/CNV//work/prealign//tx/tmpscugVF/20_sorted-dedup-dedup-sorttmp-full -o /scratch/projects//dmb107/CNV//work/prealign/20/tx/tmpscugVF/201601143472_sorted-dedup-dedup.bam /dev/stdin

**Comment by chapmanb** [comment]
Sorry about the issue. We have seen intermittent problems with feeding pre-aligned BAM files into the pipeline for SV calling with Lumpy. This conversion step can trigger memory problems during sorting on larger input BAMs resulting in failures like you're seeing here. A couple of practical suggestions to avoid this:

- You could try running on larger machine with additional resources. From the command line it looks like this is on a smaller node/machine.
- Use `manta` for pre-aligned BAMs instead of `lumpy`. Manta does not require this pre-processing step.
- Add in alignment to your pipeline, which will produce split and discordant reads needed for lumpy by partitioning up the original input BAM.

Hope one of these approaches works for you.

**Comment by dmb107** [comment]
Thank you for the feedback! I am actually running it on a LSF cluster, but I will try specifying additional memory. If not, I will try the other suggestions.

**Comment by NeillGibson** [comment]
@dmb107  Did you manage to solve this? I have the same issue?

**Comment by chapmanb** [comment]
Neill, following up on this in #1660
