### ISSUE TITLE
Mutect1 and mutect2 in the ensemble method

### ISSUE THREAD

**Issue by JoKw** [chapmanb/bcbio-nextgen#1606]
I specified mutect and mutect2 in the ensemble caller but no variant was found by mutect2 in the ensemble vcf. Are the results of mutect2 merged into those of mutect in the current implementation? Thanks

**Comment by chapmanb** [comment]
We don't do any merging like this and you should be able to use both callers simultaneously. Do you see calls in the MuTect2 output that are not present in the output? Happy to help diagnose with more information and details.

**Comment by lpantano** [comment]
Hi @JoKw 


I am closing this because the question was answered, please feel free to open an issue if you find again the problem.

thanks!
