### ISSUE TITLE
CNVkit inconsistency in BAF values

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#1607]
Hi Brad,

Wanted to let you know that the BAF columns in the file *cnvkit-call.cns and *cnvkit.cns do not have the same values. I also highlighted the issue to the CNVkit folks (Etal), but just thought to let you know in case the discrepency is due to some processing done by the bcbio pipeline. Thanks!

**Comment by etal** [comment]
Looking into it here: https://github.com/etal/cnvkit/issues/148

**Comment by chapmanb** [comment]
Thanks for reporting this. It sounds like Eric is on it so we'll close this issue and track in #148. Let me know if there's anything we can do from the bcbio side to help.
