### ISSUE TITLE
gb2genome.py produces a fasta file with all N's

### ISSUE THREAD

**Issue by lfaller** [chapmanb/bcbio-nextgen#1608]
Hi all,

I would like to use `gb2genome.py` to generate a set of new reference files for E. coli MG1655.

I downloaded the genbank file from here: https://www.ncbi.nlm.nih.gov/nuccore/U00096.3?report=gbwithparts&log$=seqview

I selected "full" Genbank format and "show GIs".

Unfortunately, when I run `gb2genome.py`, I get a fasta file full of N's. The gtf file looks fine at first glance.

I called the command as follows:

```
~/bin/gb2genome.py --gbk ecoli_mg1655.gb --prefix ecoli_mg1655

U00096.3        Skipped 417 entries having types: rep_origin, source, misc_feature, mobile_element, repeat_region.
#Time elapsed: 0:00:01.247412
```

Thanks for any advice you might have!
~Lina

**Comment by chapmanb** [comment]
Lina;
It looks like that GenBank file doesn't have any sequence information in it. It's only a collection of features. If you'd need the fasta file sequence as well you need to find a GenBank input that also has the sequence. Hope this helps get it running for you.

**Comment by lfaller** [comment]
Ah, makes sense! I don't know how to get the Genbank file with the fasta sequence in it, but there is a link to "FASTA" on the top of the page that shows the whole chromosome, it seems. 

So I will try to run the script to generate the GTF file and then download the separate fasta file.

Thanks!

**Comment by lpantano** [comment]
Hi,

normally the genbank that they showed is the small version. There should be an option to get the full genbank file, that would make easier to have a consistent annotation, but I guess that downloading the FASTA should make the trick.

I think you should go to the link Send, and then choose File, And then full genbank. That is how I normally do.

let us know if any of the option worked.

thanks

**Comment by lfaller** [comment]
Hi Lorena, 

Yes, the "full" genbank version is what I tried first, but it didn't give me the fasta sequence. But I don't mind the extra manual step involved in downloading the fasta sequence separately :-)

Thanks!

**Comment by druvus** [comment]
The "full" genbank downloaded in the web interface doesn't contain sequences for gene features. You need to click "Show sequence" and then "Update View" if you want to download it through the home page. 

If you instead go to the assembly or genome page you will see a link to the ftp. The ftp version contains all sequences. You could download it [here](ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.gbff.gz).

**Comment by lfaller** [comment]
Great, thanks for the link, this is very helpful!

**Comment by lpantano** [comment]
HI,

i will close this for now. Thanks for the help @druvus. sorry about the inconvenience.
