### ISSUE TITLE
variant2 mapping metrics

### ISSUE THREAD

**Issue by lindakohn** [chapmanb/bcbio-nextgen#1614]
Hi,

Question about  'offtarget' in metrics.tsv generated with variant2 pipeline. Is it enough that part of the read is off target for it to be counted or does the entire read have to be off target?

Linda

**Comment by chapmanb** [comment]
Linda;
Off-target (and other coverage statistics) are calculated relative to bases covered, not with respect to reads. So if a read half overlaps on-target and off-target the off-target section will be counted. Hope this helps.

**Comment by lindakohn** [comment]
Yes, thank you!
