### ISSUE TITLE
somatic calling sensitivity?

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#1615]
Hi, 

Is there any way to increase sensitivity for somatic calling? For example, as I understand varscan imposes  by default a 20% VAF limit for variants. Would be nice if this setting for varscan and similar settings in other tools could be tweaked depending on the objective of your work. 

Kind regards,

Pär

**Comment by chapmanb** [comment]
Pär;
Absolutely, you can change min_allele_fraction to resolve lower frequency variants:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#cancer-variant-calling

This will set the selected frequency for VarScan, VarDict, FreeBayes and other somatic callers that support it. Hope this helps.
