### ISSUE TITLE
Whole genome sequence error

### ISSUE THREAD

**Issue by vinogradovs** [chapmanb/bcbio-nextgen#1623]
Hi, 
I have got an error while try to run bcbio with "coverage_interval: genome"  option

[2016-11-02T17:39Z] multiprocessing: variantcall_sample
[2016-11-02T17:39Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 98, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; cat /home/adminlocal/wgs/work/vardict/1/tx/tmp0Rgnp4/AURA_small-1_77803636_93665912-unmerged-regions-glimit-all.bed | sort -V -k1,1 -k2,2n | bedtools merge -i - -c 4 -o distinct > /home/adminlocal/wgs/work/vardict/1/tx/tmp0Rgnp4/tx/tmp7uD7Nm/AURA_small-1_77803636_93665912-unmerged-regions-glimit-all-sort.bed
Error: Unable to determine type for file -
' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue. Can you try updating to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
and re-running? There are some fixes for bgzipped BED input files that are not in the 0.9.9 release which I believe explain the issue here. Hope this fixes it for you.

**Comment by vinogradovs** [comment]
Thanks Brad, 
This fix works.
