### ISSUE TITLE
No CADD scores in gemini for variant calling

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1624]
Hi bcbio developers!

I see that by default CADD is off in variant calling pipeline.
It loads vcf to gemini with --skip-cadd.

It seems that 
```bcbio_nextgen.py upgrade --data --datatarget cadd ```
does not install CADD.
Could you check this please?

Thanks,
Sergey

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issues. I've been trying to replicate this but it seems to be adding cadd okay for me so am not sure what is happening. To try and synchronize, I'm running:
```
$ gemini --version
gemini 0.19.1
```
It it possible you didn't previous add gemini as a datatarget, so need to do:
```
 bcbio_nextgen.py upgrade --data --datatarget cadd --datatarget gemini
```
When you run that, do you see gemini updates happening? You should see a lot of lines of:
```
* downloading https://s3.amazonaws.com/gemini-annotations/geno2mp.variants.tidy.vcf.gz.tbi to /usr/local/share/bcbio_nextgen/gemini_data
```
Sorry to not be able to identify a problem but hope this helps with debugging.

**Comment by naumenko-sa** [comment]
Thanks Brad!
Now I have CADD scores. Sorry for you time spent on that. I was sure that I had all the databases from GEMINI. Actually I had all but whole_genome_SNVs.tsv.compressed.gz
Sergey
