### ISSUE TITLE
Error running FreeBayes 

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1626]
Hello,

I'm getting the error below when running a pipeline (using bcbio-vm). I've updated the code to the most recent version 1-2 days ago. Couldn't find what is causing this.
Any direction?

Thank you,
Y.

[2016-11-03T20:00Z] awk: write failure (Broken pipe)
[2016-11-03T20:00Z] awk: close failed on file /dev/stdout (Broken pipe)
[2016-11-03T20:00Z] /bin/bash: line 1:   281 Done                    /usr/local/bin/freebayes -f /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa --ploidy 2 --targets /mnt/work/freebayes/chr1/blood_sample_batch-chr1_47059480_62745369-raw-regions.bed --min-repeat-entropy 1 -b /mnt/work/bamprep/blood_sample/chr1/1_2016-11-03_germline_pipeline-sort-chr1_47059480_62745369-prep.bam
[2016-11-03T20:00Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/bin/freebayes -f /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa --ploidy 2 --targets /mnt/work/freebayes/chr1/blood_sample_batch-chr1_47059480_62745369-raw-regions.bed --min-repeat-entropy 1 -b /mnt/work/bamprep/blood_sample/chr1/1_2016-11-03_germline_pipeline-sort-chr1_47059480_62745369-prep.bam | /usr/local/bin/vcffilter -f 'QUAL > 5' -s | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' | bcftools view -a - 2> /dev/null | /usr/local/share/bcbio-nextgen/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa -q - 2> /dev/null | vcfuniqalleles | bgzip -c > /mnt/work/freebayes/chr1/tx/tmpE2Wnlm/blood_sample_batch-chr1_47059480_62745369-raw.vcf.gz
awk: write failure (Broken pipe)
awk: close failed on file /dev/stdout (Broken pipe)
/bin/bash: line 1:   281 Done                    /usr/local/bin/freebayes -f /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa --ploidy 2 --targets /mnt/work/freebayes/chr1/blood_sample_batch-chr1_47059480_62745369-raw-regions.bed --min-repeat-entropy 1 -b /mnt/work/bamprep/blood_sample/chr1/1_2016-11-03_germline_pipeline-sort-chr1_47059480_62745369-prep.bam
       282                       | /usr/local/bin/vcffilter -f 'QUAL > 5' -s
       283 Exit 2                  | awk -F'	' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}'
       284 Aborted                 (core dumped) | bcftools view -a - 2> /dev/null
       285                       | /usr/local/share/bcbio-nextgen/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)'
       286                       | vcfallelicprimitives -t DECOMPOSED --keep-geno
       287                       | vcffixup -
       288                       | vcfstreamsort
       289                       | vt normalize -n -r /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa -q - 2> /dev/null
       290                       | vcfuniqalleles
       291                       | bgzip -c > /mnt/work/freebayes/chr1/tx/tmpE2Wnlm/blood_sample_batch-chr1_47059480_62745369-raw.vcf.gz
' returned non-zero exit status 134
[2016-11-03T20:00Z] Genotyping with FreeBayes
[2016-11-03T20:00Z] INFO  20:00:51,041 VariantAnnotator - Processed 5728 loci.
[2016-11-03T20:00Z]

**Comment by chapmanb** [comment]
Sorry about the issue, I don't see an obvious error in the traceback so you might need to dig into this a bit on the commandline. I'd suggest trying to run the failing command outside of bcbio:
```
/usr/local/bin/freebayes -f /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa --ploidy 2 --targets /mnt/work/freebayes/chr1/blood_sample_batch-chr1_47059480_62745369-raw-regions.bed --min-repeat-entropy 1 -b /mnt/work/bamprep/blood_sample/chr1/1_2016-11-03_germline_pipeline-sort-chr1_47059480_62745369-prep.bam | /usr/local/bin/vcffilter -f 'QUAL > 5' -s | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' | bcftools view -a - 2> /dev/null | /usr/local/share/bcbio-nextgen/anaconda/bin/py -x 'bcbio.variation.freebayes.remove_missingalt(x)' | vcfallelicprimitives -t DECOMPOSED --keep-geno | vcffixup - | vcfstreamsort | vt normalize -n -r /mnt/work/inputs/data/genomes/hg19/seq/hg19.fa -q - 2> /dev/null | vcfuniqalleles
```
If you can reproduce there, try removing commands from the pipe until you have the smallest command that will fail and hopefully that'll provide a more useful message and we might be able to identify what is going on. Sorry about all the manual debugging but hope that helps.

**Comment by deber1980** [comment]
Thanks Brad. 

I actually tried running it outside bcbio (inside new docker container) and when I do it like that it seems to be working fine.
When I try rerunning bcbio (bcbio-vm) if fails with similar error, which is really strange.
This happens after I replaced the bcbio docker image from an older version (0.9.6 I think) to the most recent code in master (1.0.0).

I now see there is additional error before, but it still doesn't explain what's causing it.

[2016-11-07T07:57Z] Genotyping with FreeBayes
[2016-11-07T07:57Z] Traceback (most recent call last):
[2016-11-07T07:57Z]   File "<string>", line 1, in <module>
[2016-11-07T07:57Z]     bcbio.variation.freebayes.remove_missingalt(x)
[2016-11-07T07:57Z]   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/freebayes.py", line 246, in remove_missingalt
[2016-11-07T07:57Z]     if parts[4] == ".":
[2016-11-07T07:57Z] IndexError: list index out of range
[2016-11-07T07:57Z] awk: write failure (Broken pipe)
[2016-11-07T07:57Z] awk: close failed on file /dev/stdout (Broken pipe)

**Comment by chapmanb** [comment]
Thanks for the follow up. I'm a bit confused about the setup you're using but would suggest updating to the latest development and re-running. If you can do outside of Docker/bcbio-vm, that should make debugging easier. The new error you posted indicates something is wrong with the FreeBayes output when it gets to the python cleanup script (it has a shortened line) so if you can break apart the pipe that might help identify where and how the VCF gets corrupted. Thanks for the work debugging this.

**Comment by deber1980** [comment]
OK, sorry for that. I found the problem. Thanks for the help
