### ISSUE TITLE
A BAM/CRAM ERROR 

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1632]
Hi Brad,
I am running tumor-germline somatic variant calling pipeline. The bcbio-nextgen is 1.0.0 development version and all the --data have been updated into the newest in November 3rd including dbnsfp database. I am using the following yaml file,

details:
   - analysis: variant2 
     genome_build: GRCh37 
     algorithm: 
       aligner: bwa 
       align_split_size: 5000000 
       mark_duplicates: true
       indelcaller: false
       nomap_split_targets: 100
       platform: illumina
       quality_format: standard
       realign: true 
       recalibrate: true
       remove_lcr: true
       variantcaller: [mutect2, freebayes, vardict, varscan]
       ensemble: 
         numpass: 2

Could you help me with the debugging?
Thanks.

[2016-11-05T02:52Z] ***.edu: Unexpected error
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 193, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 209, in postprocess_alignment
    data = _recal_no_markduplicates(data)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 215, in _recal_no_markduplicates
    data = recalibrate.prep_recal(data)[0][0]
  File "/path/to/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 44, in prep_recal
    platform, dbsnp_file, intervals, data)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 89, in _gatk_base_recalibrator
    broad_runner.run_gatk(params, tmp_dir)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 311, in run_gatk
    log_error=log_error)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/path/to/bcbio/anaconda/bin:$PATH && /path/to/bcbio/anaconda/bin/gatk -Xms500m -Xmx25480m -XX:+UseSerialGC -Djava.io.tmpdir=/path/to/12th_s/work/tx/tmpaUNcQq -T BaseRecalibrator -o /path/to/12th_s/work/align/1126T/tx/tmpqL63Ut/1126T-sort.grp -I /path/to/12th_s/work/align/1126T/1126T-sort.bam -R /path/to/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --downsample_to_fraction 0.313230956739 --downsampling_type ALL_READS --knownSites /path/to/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-147.vcf.gz -L /path/to/12th_s/work/bedprep/1126T-sort-callable_sample-callableblocks.bed --interval_set_rule INTERSECTION -nct 16 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
INFO  21:16:54,580 ProgressMeter -    10:102763801   4.1652958E7    82.3 m     118.0 s       57.5%     2.4 h      60.8 m 
INFO  21:17:24,584 ProgressMeter -    10:113924337   4.1952962E7    82.8 m     118.0 s       57.9%     2.4 h      60.3 m 
INFO  21:17:56,363 ProgressMeter -    10:121212132   4.2252968E7    83.3 m     118.0 s       58.1%     2.4 h      60.1 m 
INFO  21:18:24,998 ReadShardBalancer$1 - Loading BAM index data 
INFO  21:18:26,138 ReadShardBalancer$1 - Done loading BAM index data 
INFO  21:18:26,387 ProgressMeter -    10:134270207   4.245297E7    83.8 m     118.0 s       58.5%     2.4 h      59.4 m 
INFO  21:18:56,595 ProgressMeter -      11:1283168   4.2724879E7    84.3 m     118.0 s       58.6%     2.4 h      59.6 m 
INFO  21:19:27,115 ProgressMeter -      11:5602599   4.3024882E7    84.8 m     118.0 s       58.7%     2.4 h      59.6 m 
INFO  21:19:57,118 ProgressMeter -     11:10797004   4.3224888E7    85.3 m     118.0 s       58.9%     2.4 h      59.6 m 
INFO  21:20:30,258 ProgressMeter -     11:20649623   4.3524894E7    85.9 m     118.0 s       59.2%     2.4 h      59.2 m 
INFO  21:21:00,262 ProgressMeter -     11:34670672   4.3724897E7    86.4 m     118.0 s       59.7%     2.4 h      58.4 m 
INFO  21:21:30,621 ProgressMeter -     11:47772553   4.4024904E7    86.9 m     118.0 s       60.1%     2.4 h      57.7 m 
INFO  21:22:00,626 ProgressMeter -     11:59260027   4.4324908E7    87.4 m     118.0 s       60.5%     2.4 h      57.1 m 
INFO  21:22:33,202 ProgressMeter -     11:63979134   4.4624911E7    87.9 m     118.0 s       60.6%     2.4 h      57.1 m 
INFO  21:23:03,487 ProgressMeter -     11:67012937   4.5024916E7    88.4 m     117.0 s       60.7%     2.4 h      57.2 m 
INFO  21:23:33,578 ProgressMeter -     11:71944030   4.532492E7    88.9 m     117.0 s       60.9%     2.4 h      57.2 m 
INFO  21:24:05,943 ProgressMeter -     11:78780766   4.5524925E7    89.5 m     117.0 s       61.1%     2.4 h      57.0 m 
INFO  21:24:38,423 ProgressMeter -     11:93464822   4.5724927E7    90.0 m     118.0 s       61.6%     2.4 h      56.2 m 
INFO  21:25:08,923 ProgressMeter -    11:108063061   4.602493E7    90.5 m     118.0 s       62.0%     2.4 h      55.4 m 
INFO  21:25:41,049 ProgressMeter -    11:115760132   4.6324936E7    91.1 m     117.0 s       62.3%     2.4 h      55.2 m 
INFO  21:26:12,877 ProgressMeter -    11:121414874   4.6624943E7    91.6 m     117.0 s       62.5%     2.4 h      55.0 m 
INFO  21:26:36,618 ReadShardBalancer$1 - Loading BAM index data 
INFO  21:26:37,869 ReadShardBalancer$1 - Done loading BAM index data 
INFO  21:26:43,193 ProgressMeter -    11:130773140   4.6824945E7    92.1 m     118.0 s       62.8%     2.4 h      54.6 m 
INFO  21:27:13,196 ProgressMeter -      12:4737198   4.708522E7    92.6 m     118.0 s       63.1%     2.4 h      54.3 m 
INFO  21:27:43,200 ProgressMeter -      12:9144877   4.7385225E7    93.1 m     117.0 s       63.2%     2.5 h      54.2 m 
INFO  21:28:13,516 ProgressMeter -     12:18891897   4.7685234E7    93.6 m     117.0 s       63.5%     2.5 h      53.8 m 
INFO  21:28:44,402 ProgressMeter -     12:28544401   4.7885237E7    94.1 m     117.0 s       63.8%     2.5 h      53.3 m 
INFO  21:29:14,721 ProgressMeter -     12:40922106   4.8085239E7    94.6 m     118.0 s       64.2%     2.5 h      52.7 m 
INFO  21:29:44,826 ProgressMeter -     12:50821723   4.8485247E7    95.1 m     117.0 s       64.5%     2.5 h      52.3 m 
INFO  21:30:17,469 ProgressMeter -     12:54765488   4.8785253E7    95.7 m     117.0 s       64.7%     2.5 h      52.3 m 
INFO  21:30:47,633 ProgressMeter -     12:57892432   4.9085261E7    96.2 m     117.0 s       64.8%     2.5 h      52.3 m 
INFO  21:31:17,828 ProgressMeter -     12:70760914   4.9385265E7    96.7 m     117.0 s       65.2%     2.5 h      51.6 m 
INFO  21:31:47,850 ProgressMeter -     12:81688980   4.9585268E7    97.2 m     117.0 s       65.5%     2.5 h      51.1 m 
INFO  21:32:17,855 ProgressMeter -    12:100646366   4.9885277E7    97.7 m     117.0 s       66.1%     2.5 h      50.0 m 
INFO  21:32:48,459 ProgressMeter -    12:106901574   5.0185282E7    98.2 m     117.0 s       66.3%     2.5 h      49.8 m 
INFO  21:33:20,059 ProgressMeter -    12:114395710   5.0485288E7    98.7 m     117.0 s       66.6%     2.5 h      49.5 m 
INFO  21:33:52,052 ProgressMeter -    12:121766326   5.0785296E7    99.3 m     117.0 s       66.8%     2.5 h      49.3 m 
INFO  21:34:24,784 ProgressMeter -    12:133225675   5.10853E7    99.8 m     117.0 s       67.2%     2.5 h      48.7 m 
INFO  21:34:25,566 ReadShardBalancer$1 - Loading BAM index data 
INFO  21:34:26,559 ReadShardBalancer$1 - Done loading BAM index data 
INFO  21:34:57,435 ProgressMeter -     13:26154110   5.1302494E7   100.3 m     117.0 s       68.1%     2.5 h      47.1 m 
INFO  21:35:27,443 ProgressMeter -     13:35756614   5.16025E7   100.8 m     117.0 s       68.4%     2.5 h      46.6 m 
INFO  21:35:57,561 ProgressMeter -     13:46725011   5.1802506E7   101.3 m     117.0 s       68.7%     2.5 h      46.1 m 
INFO  21:36:27,572 ProgressMeter -     13:60566363   5.2002508E7   101.8 m     117.0 s       69.2%     2.5 h      45.4 m 
INFO  21:36:57,582 ProgressMeter -     13:93922401   5.2202511E7   102.3 m     117.0 s       70.2%     2.4 h      43.3 m 
INFO  21:37:27,793 ProgressMeter -    13:103387886   5.2402514E7   102.8 m     117.0 s       70.6%     2.4 h      42.9 m 
INFO  21:37:44,727 ReadShardBalancer$1 - Loading BAM index data 
INFO  21:37:45,741 ReadShardBalancer$1 - Done loading BAM index data 
INFO  21:37:57,813 ProgressMeter -    13:115091817   5.2702517E7   103.3 m     117.0 s       70.9%     2.4 h      42.4 m 
INFO  21:38:27,956 ProgressMeter -     14:24034984   5.3049218E7   103.9 m     117.0 s       71.7%     2.4 h      41.0 m 
INFO  21:38:58,403 ProgressMeter -     14:33290904   5.3249221E7   104.4 m     117.0 s       72.0%     2.4 h      40.6 m 
INFO  21:39:30,671 ProgressMeter -     14:50088440   5.3449226E7   104.9 m     117.0 s       72.5%     2.4 h      39.7 m 
INFO  21:40:00,687 ProgressMeter -     14:60622009   5.3749229E7   105.4 m     117.0 s       72.9%     2.4 h      39.2 m 
INFO  21:40:30,691 ProgressMeter -     14:69795338   5.4049233E7   105.9 m     117.0 s       73.2%     2.4 h      38.8 m 
INFO  21:41:02,270 ProgressMeter -     14:75325228   5.4349238E7   106.4 m     117.0 s       73.4%     2.4 h      38.6 m 
INFO  21:41:32,273 ProgressMeter -     14:89039432   5.454924E7   106.9 m     117.0 s       73.8%     2.4 h      38.0 m 
INFO  21:42:02,483 ProgressMeter -     14:95598000   5.4749242E7   107.4 m     117.0 s       74.0%     2.4 h      37.7 m 
INFO  21:42:36,699 ProgressMeter -    14:105615774   5.5149252E7   108.0 m     117.0 s       74.3%     2.4 h      37.3 m 
INFO  21:42:37,191 ReadShardBalancer$1 - Loading BAM index data 
INFO  21:42:37,873 ReadShardBalancer$1 - Done loading BAM index data 
INFO  21:43:06,729 ProgressMeter -     15:25322377   5.5314904E7   108.5 m     117.0 s       75.2%     2.4 h      35.8 m 
INFO  21:43:37,374 ProgressMeter -     15:38786815   5.5614907E7   109.0 m     117.0 s       75.6%     2.4 h      35.1 m 
INFO  21:44:07,379 ProgressMeter -     15:42985034   5.591492E7   109.5 m     117.0 s       75.8%     2.4 h      35.0 m 
INFO  21:44:37,639 ProgressMeter -     15:48786354   5.6214928E7   110.0 m     117.0 s       76.0%     2.4 h      34.8 m 
INFO  21:45:08,108 ProgressMeter -     15:58044460   5.6514932E7   110.5 m     117.0 s       76.3%     2.4 h      34.4 m 
INFO  21:45:38,174 ProgressMeter -     15:66193445   5.6814935E7   111.0 m     117.0 s       76.5%     2.4 h      34.1 m 
INFO  21:46:08,217 ProgressMeter -     15:74364261   5.7114939E7   111.5 m     117.0 s       76.8%     2.4 h      33.7 m 
INFO  21:46:38,879 ProgressMeter -     15:80672525   5.7414946E7   112.0 m     117.0 s       77.0%     2.4 h      33.5 m 
INFO  21:47:14,348 ProgressMeter -     15:90758294   5.7614948E7   112.6 m     117.0 s       77.3%     2.4 h      33.0 m 
INFO  21:47:29,041 ReadShardBalancer$1 - Loading BAM index data 
INFO  21:47:29,880 ReadShardBalancer$1 - Done loading BAM index data 
INFO  21:47:44,487 ProgressMeter -    15:102517835   5.7914954E7   113.1 m     117.0 s       77.7%     2.4 h      32.5 m 
INFO  21:48:14,823 ProgressMeter -      16:2505495   5.8277864E7   113.6 m     116.0 s       77.8%     2.4 h      32.5 m 
INFO  21:48:46,398 ProgressMeter -      16:4940809   5.8477867E7   114.2 m     117.0 s       77.9%     2.4 h      32.5 m 
INFO  21:49:18,450 ProgressMeter -     16:17432072   5.8777874E7   114.7 m     117.0 s       78.3%     2.4 h      31.9 m 
INFO  21:49:48,979 ProgressMeter -     16:22192803   5.907788E7   115.2 m     116.0 s       78.4%     2.4 h      31.7 m 
INFO  21:50:20,959 ProgressMeter -     16:30734340   5.9377884E7   115.7 m     116.0 s       78.7%     2.5 h      31.3 m 
INFO  21:50:50,963 ProgressMeter -     16:48596053   5.9677888E7   116.2 m     116.0 s       79.3%     2.4 h      30.4 m 
INFO  21:51:23,006 ProgressMeter -     16:57089106   5.9977891E7   116.8 m     116.0 s       79.5%     2.4 h      30.0 m 
INFO  21:51:53,130 ProgressMeter -     16:67768911   6.0177893E7   117.3 m     116.0 s       79.9%     2.4 h      29.5 m 
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1

**Comment by pengxiao78** [comment]
Can anybody answer my question? Urgent to solve the problem. Thanks!

**Comment by chapmanb** [comment]
Sorry about the delay and the issue. I'm not sure what is going on exactly, GATK is reporting that it thinks the BAM file is truncated, which you could check with:
```
picard ValidateSamFile I=/path/to/12th_s/work/align/1126T/1126T-sort.bam
```
If the file looks okay, we ran into a similar issue that was due to a problematic dbSNP file:

https://github.com/chapmanb/bcbio-nextgen/issues/1546#issuecomment-248328884

I still don't understand what happened (or why it gives this error) but you could check dbSNP and removing and re-downloading with bcbio if it's problematic.

Finally, if you don't need realignment and recalibration you can set:
```
realign: false
recalibrate: false
```
in your configuration to skip these steps in case there is an issue there. Hope one of these ideas helps.

**Comment by pengxiao78** [comment]
Hi Brad,

When I run picard ValidateSamFile I=/path/to/12th_s/work/align/1126T/1126T-sort.bam,
I did find the following errors. Any suggestion?

Thanks,

Peng

Linux 2.6.32-642.6.2.el6.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_92-b15; Picard version: 2.5.0(2c370988aefe41f579920c8a6a678a201c5261c1_1466708365)
ERROR: Record 3709, Read name D00195:196:C9VUYANXX:1:1207:21262:59387, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 3709, Read name D00195:196:C9VUYANXX:1:1207:21262:59387, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 7180, Read name D00195:196:C9VUYANXX:2:2211:21295:62001, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 7180, Read name D00195:196:C9VUYANXX:2:2211:21295:62001, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 8607, Read name D00195:196:C9VUYANXX:7:1304:19203:36496, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 8607, Read name D00195:196:C9VUYANXX:7:1304:19203:36496, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 9168, Read name D00195:196:C9VUYANXX:2:1101:2004:90403, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 9168, Read name D00195:196:C9VUYANXX:2:1101:2004:90403, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 9421, Read name D00195:196:C9VUYANXX:6:1108:7516:70688, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 9421, Read name D00195:196:C9VUYANXX:6:1108:7516:70688, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 11017, Read name D00195:196:C9VUYANXX:8:2104:20312:51148, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 11017, Read name D00195:196:C9VUYANXX:8:2104:20312:51148, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 14530, Read name D00195:196:C9VUYANXX:2:1206:13809:51611, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 14530, Read name D00195:196:C9VUYANXX:2:1206:13809:51611, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 15224, Read name D00195:196:C9VUYANXX:4:1116:1639:68487, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 15224, Read name D00195:196:C9VUYANXX:4:1116:1639:68487, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 17226, Read name D00195:196:C9VUYANXX:2:2307:17035:13804, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 17226, Read name D00195:196:C9VUYANXX:2:2307:17035:13804, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 18988, Read name D00195:196:C9VUYANXX:7:1208:3257:46404, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 18988, Read name D00195:196:C9VUYANXX:7:1208:3257:46404, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 26139, Read name D00195:196:C9VUYANXX:7:1301:5115:3251, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 26139, Read name D00195:196:C9VUYANXX:7:1301:5115:3251, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 27360, Read name D00195:196:C9VUYANXX:4:2304:10154:86989, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 27360, Read name D00195:196:C9VUYANXX:4:2304:10154:86989, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 29302, Read name D00195:196:C9VUYANXX:3:2312:21296:67962, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 29302, Read name D00195:196:C9VUYANXX:3:2312:21296:67962, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 37297, Read name D00195:196:C9VUYANXX:2:1101:4929:70349, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 37297, Read name D00195:196:C9VUYANXX:2:1101:4929:70349, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 39568, Read name D00195:196:C9VUYANXX:1:1214:13318:47958, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 39568, Read name D00195:196:C9VUYANXX:1:1214:13318:47958, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 41105, Read name D00195:196:C9VUYANXX:8:1216:8068:73244, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 41105, Read name D00195:196:C9VUYANXX:8:1216:8068:73244, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 45339, Read name D00195:196:C9VUYANXX:8:2105:11850:68440, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 45339, Read name D00195:196:C9VUYANXX:8:2105:11850:68440, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 51300, Read name D00195:196:C9VUYANXX:1:1110:21260:100517, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 51300, Read name D00195:196:C9VUYANXX:1:1110:21260:100517, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 54649, Read name D00195:196:C9VUYANXX:1:2112:21284:43679, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 54649, Read name D00195:196:C9VUYANXX:1:2112:21284:43679, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 54679, Read name D00195:196:C9VUYANXX:7:2302:16845:94116, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 54679, Read name D00195:196:C9VUYANXX:7:2302:16845:94116, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55654, Read name D00195:196:C9VUYANXX:1:2115:13039:79747, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55654, Read name D00195:196:C9VUYANXX:1:2115:13039:79747, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55661, Read name D00195:196:C9VUYANXX:7:2315:5226:22337, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55661, Read name D00195:196:C9VUYANXX:7:2315:5226:22337, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55683, Read name D00195:196:C9VUYANXX:3:1207:1795:49121, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55683, Read name D00195:196:C9VUYANXX:3:1207:1795:49121, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55685, Read name D00195:196:C9VUYANXX:3:2113:3035:9209, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55685, Read name D00195:196:C9VUYANXX:3:2113:3035:9209, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55696, Read name D00195:196:C9VUYANXX:7:2304:16822:62096, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55696, Read name D00195:196:C9VUYANXX:7:2304:16822:62096, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55697, Read name D00195:196:C9VUYANXX:1:2308:3192:42862, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55697, Read name D00195:196:C9VUYANXX:1:2308:3192:42862, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55699, Read name D00195:196:C9VUYANXX:3:2211:18204:27633, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55699, Read name D00195:196:C9VUYANXX:3:2211:18204:27633, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55713, Read name D00195:196:C9VUYANXX:5:2212:2256:57699, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55713, Read name D00195:196:C9VUYANXX:5:2212:2256:57699, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55722, Read name D00195:196:C9VUYANXX:1:1210:17366:100768, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55722, Read name D00195:196:C9VUYANXX:1:1210:17366:100768, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55728, Read name D00195:196:C9VUYANXX:1:2109:19416:47232, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55728, Read name D00195:196:C9VUYANXX:1:2109:19416:47232, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55731, Read name D00195:196:C9VUYANXX:7:2315:6778:97238, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55731, Read name D00195:196:C9VUYANXX:7:2315:6778:97238, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55764, Read name D00195:196:C9VUYANXX:1:1109:3084:47925, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55764, Read name D00195:196:C9VUYANXX:1:1109:3084:47925, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55832, Read name D00195:196:C9VUYANXX:3:2106:17573:77823, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55832, Read name D00195:196:C9VUYANXX:3:2106:17573:77823, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55861, Read name D00195:196:C9VUYANXX:3:2104:5889:48475, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55861, Read name D00195:196:C9VUYANXX:3:2104:5889:48475, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55866, Read name D00195:196:C9VUYANXX:5:2102:19378:20316, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55866, Read name D00195:196:C9VUYANXX:5:2102:19378:20316, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55920, Read name D00195:196:C9VUYANXX:4:2113:14572:69285, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55920, Read name D00195:196:C9VUYANXX:4:2113:14572:69285, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55940, Read name D00195:196:C9VUYANXX:4:1209:7003:20298, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55940, Read name D00195:196:C9VUYANXX:4:1209:7003:20298, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 55987, Read name D00195:196:C9VUYANXX:2:2202:18275:6927, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 55987, Read name D00195:196:C9VUYANXX:2:2202:18275:6927, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56050, Read name D00195:196:C9VUYANXX:7:1212:14544:25212, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56050, Read name D00195:196:C9VUYANXX:7:1212:14544:25212, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56096, Read name D00195:196:C9VUYANXX:4:1110:2439:13403, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56096, Read name D00195:196:C9VUYANXX:4:1110:2439:13403, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56123, Read name D00195:196:C9VUYANXX:3:1106:17322:84913, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56123, Read name D00195:196:C9VUYANXX:3:1106:17322:84913, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56125, Read name D00195:196:C9VUYANXX:1:1115:5163:6796, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56125, Read name D00195:196:C9VUYANXX:1:1115:5163:6796, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56130, Read name D00195:196:C9VUYANXX:4:1307:4420:99391, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56130, Read name D00195:196:C9VUYANXX:4:1307:4420:99391, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56192, Read name D00195:196:C9VUYANXX:8:2110:4894:24611, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56192, Read name D00195:196:C9VUYANXX:8:2110:4894:24611, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56222, Read name D00195:196:C9VUYANXX:6:2113:10674:60906, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56222, Read name D00195:196:C9VUYANXX:6:2113:10674:60906, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56278, Read name D00195:196:C9VUYANXX:4:1303:17694:38818, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56278, Read name D00195:196:C9VUYANXX:4:1303:17694:38818, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56285, Read name D00195:196:C9VUYANXX:3:1306:14564:78703, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56285, Read name D00195:196:C9VUYANXX:3:1306:14564:78703, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56393, Read name D00195:196:C9VUYANXX:5:2214:17487:12566, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56393, Read name D00195:196:C9VUYANXX:5:2214:17487:12566, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56437, Read name D00195:196:C9VUYANXX:1:2208:13137:54602, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56437, Read name D00195:196:C9VUYANXX:1:2208:13137:54602, Mate CIGAR string does not match CIGAR string of mate
ERROR: Record 56490, Read name D00195:196:C9VUYANXX:5:1301:5797:13143, Mate CIGAR String (MC Attribute) present for a read whose mate is unmapped
ERROR: Record 56490, Read name D00195:196:C9VUYANXX:5:1301:5797:13143, Mate CIGAR string does not match CIGAR string of mate
Maximum output of [100] errors reached.

**Comment by chapmanb** [comment]
Peng;
Those errors/warnings aren't relevant to the problem you have (GATK is complaining about a truncated file). picard is pretty picky and the MC issue doesn't cause problems with other software (although is resolved with recent versions of samblaster and biobambam). You might need to use samtools instead to check the BAM file:
```
samtools quickcheck /path/to/12th_s/work/align/1126T/1126T-sort.bam
````
If that looks good I'd proceed to the other suggestions for debugging. Hope this helps.

**Comment by naumenko-sa** [comment]
Hi Peng,
are you running ipython parallel version or single node multicore?
Sergey

**Comment by pengxiao78** [comment]
Hi Brad,
I just further updated the dbSNP. The running is going and does not show any error until now.
Thank you!

**Comment by lpantano** [comment]
Hi @pengxiao78 

I will close this guessing you got it working. Let us know if you find more issues.

Thanks!
