### ISSUE TITLE
bcbio_nextgen upgrade also not working

### ISSUE THREAD

**Issue by csmatyi** [chapmanb/bcbio-nextgen#1635]
Hello,

I'm also having trouble with bcbio_nextgen upgrade also not working. My command is:

nohup bin/bcbio_nextgen.py upgrade -u stable --tools --data --datatarget gemini --datatarget cadd --datatarget vep --datatarget dbnsfp --datatarget battenberg &>err.bcbio_nextgen4 &

The error file is in this secret gist:

https://gist.github.com/csmatyi/ffeaa401bac5dbe5db1adcc56e6224af

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. I believe this was a problem with the dbNSFP download recipe, and just pushed a fix which should resolve it. If you remove your cached cloudbiolinux:
```
rm -rf tmpbcbio-install
```
and re-run the upgrade command it'll hopefully pick up where it left off and work cleanly. Thanks again for the report.
