### ISSUE TITLE
AssertionError due to missing scalpel output file

### ISSUE THREAD

**Issue by lorenzofarina** [chapmanb/bcbio-nextgen#1637]
Hi,

I get the following error in the bcbio-nextgen.log:

<pre>
[2016-11-09T20:36Z] node040: Unexpected error
Traceback (most recent call last):
  File "/pico/work/ELIX_prj6/lfarina0/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/pico/work/ELIX_prj6/lfarina0/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 326, in variantcall_sample
    return ipython.zip_args(apply(genotype.variantcall_sample, *args))
  File "/pico/work/ELIX_prj6/lfarina0/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 313, in variantcall_sample
    call_file = caller_fn(align_bams, items, sam_ref, assoc_files, region, call_file)
  File "/pico/work/ELIX_prj6/lfarina0/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/mutect.py", line 149, in mutect_caller
    region=region, out_file=out_file_indels)
  File "/pico/work/ELIX_prj6/lfarina0/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/scalpel.py", line 177, in _run_scalpel_paired
    scalpel_tmp_file_common = bgzip_and_index(os.path.join(tmp_path, "main/common.indel.vcf"), config)
  File "/pico/work/ELIX_prj6/lfarina0/bcbio/data/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 466, in bgzip_and_index
    assert os.path.exists(in_file), "Input file %s not found" % in_file
AssertionError: Input file /pico/scratch/userexternal/lfarina0/bcbio_run/uuid_batch3415/work/mutect/7/LUSC_3415-7_31317795_62753570-somaticIndels-scalpel-work/main/common.indel.vcf not found
</pre>

The file is in fact missing but no scalpel error is reported in the bcbio-nextgen.log or bcbio-nextgen-debug.log files.

I'm using bcbio-nextgen version 1.0.0a0 (scalpel version 0.5.1).
@gnarzisi

Thanks

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the report. I'm not sure under what conditions scalpel will not produce the `common.indel.vcf` file, the code is written under the assumption that it gets produced when `somatic.indel.vcf` is present. We use it to filter out likely germline calls from the somatic output. If it is not produced under some valid cases, we could add logic to avoid using it for filtering but I also don't want to do that and potentially skip an error.

Are you able to reproduce this outside of bcbio? The best approach would be to look for the scalpel command producing `LUSC_3415-7_31317795_62753570-somaticIndels-scalpel-work` in `log/bcbio-nextgen-commands.log` and adjust to run outside of bcbio to see if you can replicate. This would help us identify if this is an error in Scalpel or some edge case that bcbio should handle. Thanks much.

**Comment by razZ0r** [comment]
Hi,

I had several cases similar to this one. Either the `common.indel.vcf` or the `somatic.indel.vcf` file is missing, and bcbio dies later when looking for them.

If I run the `scalpel-discovery` command on the same files separately, everything is OK, no files are missing.

**Comment by chapmanb** [comment]
Endre;
Thanks for following up on this. Do you see the failures consistently with bcbio if you remove a partially finished directory and rerun? I'm concerned with being unable to replicate outside of bcbio that this might be some kind of temporary resource/filesystem issue we'll have to try to identify. If a re-run works, a workaround here would be to look for the files and re-try if they're missing. Thanks again for the help debugging.

**Comment by razZ0r** [comment]
Yes, it seems that sometimes just rerunning bcbio solves the problem. However, I have a sample where I restarted bcbio 3 times, and it always ends up with this error. I'll test it one last time with removing the partially finished directories and report back.

**Comment by razZ0r** [comment]
I reran that particular sample the 4th time after removing every file for the problematic region in the mutect directory and it did complete properly. So this might not be a scalpel error but some filesystem error. I have no idea what, as the storage system seems stable otherwise, I only have missing files during scalpel runs.

**Comment by chapmanb** [comment]
Endre;
Thanks for following up. Unless you want to go on a deep exploration of Perl and Scalpel, the best practical advice here is to clean up and re-run for rare failed cases. It's a non-satisfying approach but it's very tough to approach non-reproducible issues in a systematic way. If you end up finding anything we can do to help improve the problem happy to re-open this and work more on it. Thanks again for all the work debugging this.
