### ISSUE TITLE
r-base 3.3.1 and age-metas update error 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1644]
Hi Brad, I have tried to update my bcbio with bcbio_nextgen.py upgrade -u development --tools --data and But I receive.

I guess the problem is with age-metas dependencies.

Thanks!

UnsatisfiableError: The following specifications were found to be in conflict:
  - age-metasv
  - r-openssl -> r-base 3.3.1*
Use "conda info <package>" to see the dependencies for each package.

Fatal error: local() encountered an error (return code 1) while executing '/cbio/cslab/nobackup/pastore/bcbio/anaconda/bin/conda install -y -c bioconda -c r -c conda-forge age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools=1.3.0 bedtools=2.24.0 bio-vcf biobambam bowtie bowtie2 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly express fastqc fgbio freebayes=1.0.2.29 gatk gatk-framework gemini geneimpacts glpk=4.57 goleft grabix gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta mbuffer metasv mirdeep2 moreutils multiqc multiqc-bcbio novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig vardict vardict-java variant-effect-predictor=83 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli p7zip s3gof3r perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.

**Comment by chapmanb** [comment]
Thanks for reporting the issue. Apologies, I can't seem to replicate this on three different installations and am not sure what is going on. age-metasv has no dependencies so shouldn't be conflicting with anything r, and I'm not positive where the r-openssl dependency comes from. If you try to uninstall these:
```
bcbio_conda uninstall age-metasv r-openssl
```
and then re-run, does that help resolve it? Sorry to not be able to reproduce but hope this helps.

**Comment by apastore** [comment]
Hi Brad,
I have also to remove r-tibble
`bcbio_conda uninstall age-metasv r-openssl r-tibble`

Thanks
