### ISSUE TITLE
Work on RNA-Seq fusion calling

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1649]
Hi there, together with @tetianakh we are currently evaluating transcriptome-alignment-based fusion callers for inclusion into bcbio; the current STAR workflow is too memory hungry (since we quantitate with Sailfish anyway), and also not very specific. The goal is to offer an alternative to the STAR+Oncofuse setup. We are considering EricScript or FusionCatcher, possibly with Oncofuse, Pegasus or Chimera annotations. Does anyone have an opinion on this, perhaps @roryk or @mjafin?

**Comment by mjafin** [comment]
Hi @schelhorn, I like FusionCatcher a lot and @ndaniel can probably give us good advice if needed. It's completely standalone and pulls its own reference genomes and annotations so I'm not sure it would fit well within bcbio though. 

Manta supports fusions but, moving forward with hg38, it would need Hisat2 to support split reads. 

@roryk said he'd try out "... Rob’s branch of Salmon that has fusion gene calling implemented" but that "it is sensitive but isn’t the strongest out there in terms of specificity"

**Comment by ndaniel** [comment]
Just some comments:

- FusionCatcher is standalone mostly because the gene annotations leave a lot to desire and still need even today to be manually modified in order to allow some fusions genes to be found (for example one example, one needs to add manually IGH@ and IGK@  annotations in order to allow IGH fusions to be found; as far as I know only CICERO and FusionCatcher are able to find IGH fusions),
- it is very easy to find fusion genes but the challenging part is in specificity.

**Comment by tetianakh** [comment]
I've checked some benchmarking studies (the most relevant are https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4748267/ and http://nar.oxfordjournals.org/content/44/5/e47.short)
In short:
1. Gene fusion detection tools are generally standalone. 
2. The trickiest part is reducing the number of false-positives. Each tool has its own algorithms to identify valid fusions. 
3. Some align to genome, and some to transcriptome. Some also contain additional local alignment steps.
4. Performance of a tool (both in terms of resources and in terms of sensitivity/specificity) depends _a lot _on the dataset, length and quality of reads.

Here's my [shortlist of tools](https://docs.google.com/spreadsheets/d/1luqK0PQQkf06XVa48k5uYyF5EvXJWP1Zg8VkslxGvxs/edit?usp=sharing), with some characteristics. I was looking for something specific, fast, and not resource hungry, and it looks like EricScript is the most reasonable choice.
The "best" tools in terms of sensitivity and specificity are Jaffa and FusionCatcher, however, they're quite resource hungry.
Other tools were not updated for over 3 years.

As most other fusion callers, EricScript has its own reference data, calls its own aligners, and has its own filters and result evaluation. In fact, it wrap the whole fusion calling pipeline. However, I believe it makes sense to have it in bcbio from the user experience point of view. Bcbio is a popular framework, and running gene fusion analysis using the same familiar bcbio interface may be preferable to users as compared to installation & deployment of a standalone tool.

**Comment by ndaniel** [comment]
If I have to suggest a fusion finder, which is not FusionCatcher, then I would suggest strongly [STAR-fusion](https://github.com/STAR-Fusion/STAR-Fusion). From my own tests, [STAR-fusion](https://github.com/STAR-Fusion/STAR-Fusion), which can be used also by analyzing the output produced by [STAR aligner](https://github.com/alexdobin/STAR), runs much faster and gives better results than EricScript. Plus, [STAR-fusion](https://github.com/STAR-Fusion/STAR-Fusion) comes with its own tools for filtering the fusions, visualizing them, etc. See: [FusionFilter](https://github.com/FusionFilter/FusionFilter)

Another, very fast and light fusion finder I am looking to, is [Pizzl]y(https://mobile.twitter.com/torstenseemann/status/778607477260750848).

**Comment by schelhorn** [comment]
I am closing this issue since thanks to @roryk and others, `pizzly` is now integrated in _bcbio-dev_. I am happy to exchange experiences regarding the new caller, and will drive functional annotation of these fusions upstream at `pizzly`.
