### ISSUE TITLE
using vep 86 in bcbio

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1653]
Hi Brad,
Is there a reason the latest version of VEP wasn't included into the latest release? I understand if it isn't possible to include all the modifications I've requested earlier, but I think as for the vep release, newer = better no?

Thanks again!
M

**Comment by chapmanb** [comment]
We hadn't yet worked on any of the additional VEP modules you added, so haven't worked on bumping the database and tool version yet. I was hoping to get dbNSFP working and then see about the possibility of adding in the new modules. There is potentially some value in just increasing versions, but also downsides. It requires testing to ensure the new version is actually better, and also imposes the cost of re-building the data indexes for everyone. Definitely happy to support you if you have the ability to test the new version and include the additional modules, sorry we haven't had the opportunity to do so yet.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for the quick response. What steps need to be taken for the newest release to be included? I saw that someone else had taken on the dbNSFP issue, as I haven't had much time anymore to further solve any issues. I do think this problem is resolved now?

As for the testing of the latest version, currently our pipeline is set up to just use bcbio for mapping, variant calling and QC. After this is finished, we use VEP v86 and all plugins mentioned earlier to annotate the resulting VCF, after which we use vcf2db to create a gemini compatible db (support for hg38). This method has yielded some great results, both for GRCh37 and hg38, with several clinical cases solved using the resulting db. So we know it actually works.

We'd be delighted if we could plug this method into bcbio, because of the underlying parallelization, which should speed up our analysis significantly. The recipe for vep 86 is in bioconda and works fine.
It also includes the files needed for the plugins to run.

I would like to propose the following steps to be taken
- [ ] Bump vep to v86
- [ ] Add ggd recipe for dbNSFP (hg38)
- [ ] Add ggd recipe for dbSCNV (GRCh37 and hg38)
- [ ] (if possible) Add mechanism that allows users to set the required dbNSFP fields manually (e.g. in the bcbio_system.yaml)
- [ ] (if possible) Add mechanism that allows users to activate/deactivate vep plugins.

I'd be happy to help develop/set this up. There is also still some work that needs to be done on the bioconda recipes for GeneSplicer and MaxEntScan, but perhaps I could ask some help on that front from the bioconda community.

I'd love to hear your thoughts on this. We're so close to being able to use bcbio as our go to pipeline for almost every routine analysis.

Thanks!
M

**Comment by matthdsm** [comment]
some preliminary work in chapmanb/cloudbiolinux#233

**Comment by chapmanb** [comment]
Thanks much for all this work. I left comments with small suggestions/questions in the two PRs and am happy to merge these in to get it working for you. Thanks again for making this all happen.

**Comment by matthdsm** [comment]
Thanks!
I will need some help with added extra plugins to the VEP routine. Are you willing to provide me with some pointers on how I should add those?

M

**Comment by naumenko-sa** [comment]
Hi Matthias and Brad!
Is it possible to add an option turning --pick in VEP off? This one forces VEP to report one effect per variant. It is ok by default, because without --pick the database size and running time will increase. But sometimes it is desired to report all effects.
Thanks,
Sergey

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issues and confusion with `--pick`. This is off by default and turned on when setting `clinical_reporting: true`:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/effects.py#L140

so if you don't set that it should report multiple variants. Hope this helps.

**Comment by naumenko-sa** [comment]
Thanks Brad; 
Yes, I do use clinical_reporting. Unfortunately I need HGVS notation and no --pick at the same time. Maybe it is possible to split clinical_reporting and vep_pick: true/false sometime in the future?
Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for the feedback. I pushed fixes to bcbio which decouple HGVS and pick in the latest development version. Now HGVS is on by default and you can specify using canonical transcripts only (`--pick` in VEP) with `effects_transcripts: canonical`. I dropped `clinical_reporting` although it's behavior is left in to be back compatible with older configurations. Hope this provides what you need for using VEP. Thanks again for the feedback.

**Comment by naumenko-sa** [comment]
Thanks Brad!
