### ISSUE TITLE
Update bcbio_prepare_samples.py missing force_single in _get_samples_to_process function call. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1656]
Hi @lpantano.  

Could you please update line 140 in bcbio_prepare_samples.py to also supply the needed `force_single` argument for `_get_samples_to_process` in the same file. 

I now get the following error when trying to concatenate my input fastq files
```
bcbio_prepare_samples.py --out ./input_fastq/concat/ --csv ./my_fastq_samples.csv
Traceback (most recent call last):
  File "/tools/bcbio-1.0.0/bin/bcbio_prepare_samples.py", line 140, in <module>
    samples = _get_samples_to_process(args.csv, out_dir, config)
TypeError: _get_samples_to_process() takes exactly 4 arguments (3 given)
```

(I am running bcbio v1.0.0a0 development version so that I can run the freebayes v.1.1)

I thinks this line was by accident missed in this commit:
https://github.com/chapmanb/bcbio-nextgen/commit/dcb9b79d8f8b949a477f9114f7a5153092defb2c

https://github.com/chapmanb/bcbio-nextgen/blob/dcb9b79d8f8b949a477f9114f7a5153092defb2c/scripts/bcbio_prepare_samples.py#L140

https://github.com/chapmanb/bcbio-nextgen/blob/dcb9b79d8f8b949a477f9114f7a5153092defb2c/scripts/bcbio_prepare_samples.py#L40

Thank you!

**Comment by lpantano** [comment]
Hi @NeillGibson 

sorry about that. I pushed the fix here: https://github.com/chapmanb/bcbio-nextgen/commit/fb4a04b63638ba25af80557acab7e3ca1e6edfbd

thanks

**Comment by NeillGibson** [comment]
Thank you Lorena.
