### ISSUE TITLE
CNVkit WGS issues

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1657]
Hello @chapmanb,

I have an issue following your commit https://github.com/chapmanb/bcbio-nextgen/commit/354847fbdf9d1fdda2ce15109906d41c1f5b2eb4 and relating to the CNVkit issue https://github.com/etal/cnvkit/issues/162; when I run CNVkit on tumor-only WGS samples with `coverage_interval = 'genome'`, I do not receive allelic CNV calls but an exception:

```python
/bcbio/lib/anaconda/lib/python2.7/site-packages/pandas/core/indexing.pyc in _convert_to_indexer(self=<pandas.core.indexing._IXIndexer object>, obj=['chromosome', 'start', 'end', 'cn', 'cn1', 'cn2'], axis=1, is_setter=False)
   1209                          missing) = labels.get_indexer_non_unique(objarr)
   1210                         check = indexer
   1211 
   1212                 mask = check == -1
   1213                 if mask.any():
-> 1214                     raise KeyError('%s not in index' % objarr[mask])
   1215 
   1216                 return _values_from_object(indexer)
   1217 
   1218         else:

KeyError: "['cn1' 'cn2'] not in index"
```

due to malformed allelic CNV call files that miss the `cn1`, `cn2` header (so no allelic CNV calls).

This happens during prioritization:

```python
/bcbio/lib/anaconda/lib/python2.7/site-packages/bcbio/structural/prioritize.pyc in _cnvkit_prioritize(sample='SAMPLE', genes=['5S_rRNA', '7SK', 'A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1', 'A2ML1-AS2', 'A2MP1', 'A3GALT2', 'A4GALT', 'A4GNT', 'AAAS', 'AACS', 'AACSP1', 'AADAC', 'AADACL2', 'AADACL3', ...], allele_file='/WORKINGDIR/.../SAMPLE-sort-call.cns', metrics_file='WORKINGDIR/.../SAMPLE-sort-segmetrics.txt')
    154     print 'DEBUG'
    155     print allele_file
    156     adf = pd.read_table(allele_file)
    157     if len(genes) > 0:
    158         adf = adf[adf["gene"].str.contains("|".join(genes))]
--> 159     adf = adf[["chromosome", "start", "end", "cn", "cn1", "cn2"]]
    160     df = pd.merge(mdf, adf, on=["chromosome", "start", "end"])
    161     df = df[df["cn"] != 2]
    162     if len(df) > 0:
    163         def passes(row):`
```

We really need whole-genome allelic CNV calls by CNVkit; could this please be enabled in bcbio?

Edit: I am also using an `svprioritize` list of all exons padded by 10kbp and subsequently merged by overlapping regions; may thus be an influencing factor?

**Comment by schelhorn** [comment]
Also, there seem to be specific recommendations for CNVkit WGS analyses including multiprocessing options to use multiple CPU cores (http://cnvkit.readthedocs.io/en/stable/nonhybrid.html); if I have looked at the code correctly, this is currently not being used in bcbio.

**Comment by etal** [comment]
To get allelic copy number calls I recommend using the `call -v` command to (re)calculate the cn1 and cn2 columns, rather than using the cn1 and cn2 values from `segment -v` (which was buggy and will be gone in the next release, see etal/cnvkit#148 and chapmanb/bcbio-nextgen#1607). Segmenting by SNP b-allele frequencies will still work.

CNVkit's multiprocessing is fairly coarse-grained, and if you have at least as many samples to analyze as CPUs available, you'll see roughly the same CPU utilization by running the individual CNVkit commands in concurrent processes, as bcbio does. In the most recent CNVkit release the `coverage` and `segment` steps can also be parallelized within each sample, which is an improvement on one-sample-per-core but risks blowing out the available RAM on WGS samples if you're aggressive with it.

**Comment by chapmanb** [comment]
Sven-Eric and Eric;
Thanks much for the report and suggestions. It sounds like I was overly aggressive in removing `-v` from the `call` command based only on memory issues during segmentation. Apologies, I added this back in to the latest development so if you update and re-run after removing the previous call files with:
```
rm -f structural/*/cnvkit/raw/*-call*
```
hopefully it will provide the correct inputs for prioritization.

Regarding parallelization, the splitting within bcbio is meant to replicate what happens in the CNVkit recommendations and in some cases we're more aggressive in parallelizing by splitting up coverage calculations into hunks. Definitely happy to revisit segmentation if that is a bottleneck and we can parallelize more there without triggering more memory issues.

Thanks again for all the feedback and please feel free to re-open if this doesn't resolve the issues.

**Comment by schelhorn** [comment]
Thanks, Brad, that should solve the issue and of course the parallelization strategy is fine.

>  I recommend using the call -v command to (re)calculate the cn1 and cn2 columns, rather than using the cn1 and cn2 values from segment -v (which was buggy and will be gone in the next release (...)

The `segment -v` option is still being used in bcbio's `structural.cnvkit._cnvkit_segment_base` for non-WGS samples; is it safe to remove it there if we use `call -v` later on? Also, bcbio disables bootstrapping for WGS samples when computing `segmetrics` (in `structural.cnvkit._add_segmetrics_to_output`). I could not find a recommendation for disabling boostrapping in the [CNVkit WGS docs](http://cnvkit.readthedocs.io/en/stable/nonhybrid.html); could someone please elaborate on that decision? 

Thanks again to everyone.

**Comment by chapmanb** [comment]
Thanks so much for testing this all out on WGS runs.

I'm happy to do whatever Eric recommends for `segment -v` with targeted runs. I'd tested previously with both `segment -v` and `call -v` so not sure how they do independently. It's only that WGS runs don't work memory-wise with `segment -v`.

I believe I don't have the extra bootstrapping step for WGS samples due to a recommendation from Eric, but if that's not going to be a concern for time/memory we could also adjust that.

So the short answer is: whatever Eric recommends we can do.

**Comment by etal** [comment]
Running `segment -v` will detect additional segments with copy-number-neutral loss of heterozygosity, but `call -v` will only calculate `baf`, `cn1` and `cn2` columns for segments already identified by `segment`.

If even a coarse bootstrapping for 90% confidence intervals (e.g. `segmetrics --ci -a 0.1 -b 50`) is too slow, then you can try filtering by SEM instead (`segmetrics --sem`). Ideally the results should be similar, but I think the bootstrap is more reliable where it's feasible. This assumes the next step is to filter segments via `call --filter ci` or `call --filter sem`.

The next CNVkit release will address some of these issues, hopefully making WGS analysis easier.

**Comment by chapmanb** [comment]
Eric -- thanks so much for the suggestion. I'll leave the segmentation as is to allow it to help with detection for panels, and keep cn1, cn2 estimation for all sample types.

For bootstrapping, I added in Eric's suggestion for a compromise between runtimes and number of bootstraps. Sven-Eric, let us know if this causes major run time issues and we can revisit.

Thanks again for all the work and testing on this.
