### ISSUE TITLE
Exception in variation.effects.run_vep() - missing VEP plugins not being dealt with correctly?

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1669]
I get the following exception in `variation.effects.run_vep()`, which seems to be new: 

```python
  File "/bcbio/lib/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 158, in run_vep
    prediction_args + dbnsfp_args + loftee_args + clinical_args
TypeError: can only concatenate list (not "NoneType") to list
```

I am working on human data and I believe I don't have `dbnsfp` or `loftee` installed. May this be the reason for the 'None's? There's a bunch of code previous to the line generating the error that may assume that these plugins are installed.

**Comment by schelhorn** [comment]
I changed the relevant section in effects.py to:

```python
                if is_human:
                    dbnsfp_args, dbnsfp_fields = _get_dbnsfp(data)
                    loftee_args, loftee_fields = _get_loftee(data)
                    if not dbnsfp_args:
                        dbnsfp_args = ['']
                    if not dbnsfp_fields:
                        dbnsfp_fields = ['']
                    if not loftee_args:
                        loftee_args = ['']
                    if not loftee_fields:
                        loftee_fields = ['']

```

Perhaps that could be done more elegantly in the getter functions, but in any way it resolves the issue. Please fix in main.

**Comment by schelhorn** [comment]
On second thought, that results in an empty field for the VEP `--fields [list]` argument (after `CCDS`):

```bash
--fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE,CANONICAL,CCDS,,LoF,LoF_filter,LoF_flags,HGVSc,HGVSp
```

Perhaps @matthdsm could have a look.

**Comment by matthdsm** [comment]
Hi @schelhorn,

I've actually just begun familiarizing myself with the inner workings of bcbio, up until recently I've counted on the expertise of almighty Brad Chapman, so I doubt I'll be much help.
None the less, I'll have a look and see what I can come up with. Might be a good learning excercise.
M

**Comment by chapmanb** [comment]
Sven-Eric and Matthias;
Sorry about the issue, this is my mistake of not catching this case during the PR review. I pushed a fix to resolve the issue and always ensure we have annotation fields if you have dbNSFP present. Apologies about that, if you update to development it should now do the right thing. Thanks so much for reporting.
