### ISSUE TITLE
directory structure problem downloading data with ggd-run.sh, can't do a fresh install

### ISSUE THREAD

**Issue by stephenturner** [chapmanb/bcbio-nextgen#1670]
Running into the same error with fresh installations on two different systems (one CentOS, other Ubuntu). Installation with `--nodata` works fine, but fails when trying to get data with:

```sh
bcbio_nextgen.py upgrade --cores 12 --data --genomes GRCh37 --aligners bwa --aligners star
```

End of the error string is:

```
  File "/home/sdt5z/bcbio/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['bash', '/nv/vol46/uvabx/bcbio/local/share/bcbio/genomes/Hsapiens/GRCh37/txtmp/ggd-run.sh']' returned non-zero exit status 1
```

When I try running that script by itself:

```
$ bash ggd-run.sh
--2016-12-02 10:04:45--  ftp://gsapubftp-anonymous:*password*@ftp.broadinstitute.org/bundle/2.8/b37/hapmap_3.3.b37.vcf.gz
           => `-'
Resolving ftp.broadinstitute.org... 69.173.80.251
Connecting to ftp.broadinstitute.org|69.173.80.251|:21... connected.
Logging in as gsapubftp-anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /bundle/2.8/b37 ...
No such directory `bundle/2.8/b37'.


gzip: stdin: unexpected end of file
```

Looks like `ftp.broadinstitute.org/bundle/2.8/b37/` doesn't exist - that is, there's no `2.8/`, it's just ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/b37. 

When I edit this script to remove the broken path:

```sh
# baseurl=ftp://gsapubftp-anonymous:none@ftp.broadinstitute.org/bundle/2.8/b37/hapmap_3.3.b37.vcf.gz
baseurl=ftp://gsapubftp-anonymous:none@ftp.broadinstitute.org/bundle/b37/hapmap_3.3.b37.vcf.gz
```

and re-run it, the data downloads successfully. But, I still can't run the `bcbio_nextgen.py upgrade ...` command successfully, because it apparently overwrites the file I just edited. 

Thanks for the help!

**Comment by stephenturner** [comment]
if chapmanb/cloudbiolinux#235 fixes this, there are other .yaml files in chapmanb/cloudbiolinux that'll need updating. hopefully this works.

**Comment by stephenturner** [comment]
Glad to see chapmanb/cloudbiolinux#235 was the issue. Once this is merged, would simply running the update script again do the trick? Or will I need to remove some tmp directories? (1st time trying bcbio, thanks).

**Comment by chapmanb** [comment]
Stephen;
Thanks again for the report and the fix. It looks like the GATK FTP directory structure changed, causing these recipes to break. I updated all of the remaining recipes and to fix you'd need to do:
```
rm -rf tmpbcbio-install
bcbio_nextgen.py upgrade --cores 12 --data --genomes GRCh37 --aligners bwa --aligners star
```
that will remove the cached cloudbiolinux and get an update from GitHub with the fixed recipes. Hope this gets installation working smoothly for you. Let us know if you have any other problems at all.
