### ISSUE TITLE
bcbio-nextgen fails installing into singularity container

### ISSUE THREAD

**Issue by jlec** [chapmanb/bcbio-nextgen#1672]
[Singularity](http://singularity.lbl.gov/) is a daemon less container technology which targets HPC system. Being able to install bcbio-nextgen into these containers would be really helpfull.

Using the [installation instructions](https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html) to install it fails with 
```
Errors were encountered while processing:
 libpam-systemd:amd64
 policykit-1
 colord
 policykit-1-gnome
E: Sub-process /usr/bin/dpkg returned an error code (1)

Fatal error: local() encountered an error (return code 100) while executing 'apt-get -y --force-yes install fastx-toolkit last-align maq plink tabix openjdk-7-jdk openjdk-7-jre gsl-bin libatlas-base-dev libblas-dev libbz2-dev libc6-dev libcurl4-openssl-dev libeigen3-dev libgsl0-dev libgsl0ldbl liblapack-dev liblzma-dev libncurses5-dev libnetcdf-dev libpcre3-dev libpng12-dev libreadline-dev libssl-dev libxml2 libxml2-dev libxslt1-dev libxslt1.1 libzip-dev mime-support'

Aborting.
```

I used the following singularity bootstrapping script
```
BootStrap: debootstrap
OSVersion: trusty
MirrorURL: http://uk.archive.ubuntu.com/ubuntu/

%runscript
    echo "Arguments received: $*"
    exec /bin/bash "$@"

%post
    apt-get -y --force-yes install nano curl wget git unzip tar gzip bzip2 xz-utils python
    wget -O /tmp/bcbio_nextgen_install.py https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
    python /tmp/bcbio_nextgen_install.py --tooldir=/usr/local -u stable --distribution ubuntu --nodata /usr/local/share/bcbio
```

The full build log can be found [here](https://gist.github.com/jlec/9a1b947c08e7c1b549f95c1fdc8da4fc).

**Comment by schelhorn** [comment]
What are the permissions of the `dpkg` binary?

**Comment by chapmanb** [comment]
Justin;
Thanks for trying out bcbio installs on Singularity and sorry about the issues. In general we recommend not running the installer as root, although I understand inside a container is a special case. If running as root you should add the `--isolate` flag to the install command:
```
python /tmp/bcbio_nextgen_install.py --isolate --tooldir=/usr/local -u stable --distribution ubuntu --nodata /usr/local/share/bcbio
```
and it will avoid trying to update and install system packages within the installer. I've made this the default so it'll do the right thing with the next release. Hope this gets the install finished cleanly for you and let us know if you run into any other issues.

**Comment by jlec** [comment]
@chapmanb Singularity bootstrap only works as root. If I use ```--isolate```, do I have all the dependencies installed? Is there a list of deps required?

**Comment by chapmanb** [comment]
Justin -- based on the apt-get you posted above you should be fine with `--isolate`. We've been working a lot on reducing dependencies so the extra additions CloudBioLinux makes without isolate aren't necessary. All of the required dependencies are documented here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

Hope this helps.

**Comment by jlec** [comment]
I managed to do the exact same installation as the _Dockerfile_ does in a singularity container. Will send a PR for the bootstrap later. The trick was to `ln -sf /bin/true /sbin/start`.

**Comment by chapmanb** [comment]
Thanks for reporting back and glad things got resolved within Singularity. Looking forward to hearing how it works out.
