### ISSUE TITLE
Assertio Error

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#1676]
Hi bcbio Team,

Recently we are experiencing issues for few samples within a flowcell while they are going through bcbio pipeline. The error I see on these samples is

    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 104, in prep_align_inputs
    return alignprep.create_inputs(*args)
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 53, in create_inputs
    splits = _find_read_splits(data["files"][0], data["config"]["algorithm"]["align_split_size"])
  File "/mnt/speed/qc/sequencing/bcbio/anaconda/lib/python2.7/site-packages/bcbio/ngsalign/alignprep.py", line 220, in _find_read_splits
    assert num_lines % 4 == 0, "Expected lines to be multiple of 4"
AssertionError: Expected lines to be multiple of 4

I checked the fastq files and they are multiples of 4. Not sure as why this happens only for few of them.

Thanks,

Diya

**Comment by chapmanb** [comment]
Diya;
Thanks for the report and sorry about the issues. This message is indicating that some of the files in `align_prep` were not correctly prepared. bcbio bgzips the input files then indexes them with grabix producing `.gbi` indexes for random access to the file. It sanity checks these indexes and is where it's finding files that don't have lines of 4. This could indicate something happened during bgzipping, or the grabix index failed. If the original files are definitely good, you could try removing the problem files from `align_prep` and regenerating to see if the problem persists. Sorry to not have any better ideas than retrying but hope this helps with debugging.

**Comment by gabeng** [comment]
Hi Diya,
were you able to solve the issue? I am running into the same problem both with bcbio 1.0.1 and the current development version. Executing the bcbio commands manually creates `.gbi` files without error. The `.gbi` files contain 5 lines, though, thus bcbio stops with error.
Any hints? Are there any checks that I can perform on the fastq.gz files? They seem ok. The initial files are not pbgzipped.

**Comment by DiyaVaka** [comment]
Hi,

I have recreated my fastq files and it solved the issue.

**Comment by gabeng** [comment]
Hi,
thanks for the info. Unfortunately, the fastq files come from a third party and there is no way for me to re-create them. However, addin the option `align_split_size: false` allowed me to avoid the error message. Since I am using single multi-core machines this is fine for me.

**Comment by chapmanb** [comment]
Ben and Diya;
Thanks for the discussion on this. Ben, were there new bgzipped fastq files created in the `align_prep` directory? If so, those could be a source of the underlying issue if something happened during that creation process. If you could identify what is wrong we could try to catch it. If bcbio skipped re-bgzipping them and thinks the initial files are bgzipped, it could be something is an issue with the original file. You might want to check the output BAM files to ensure they have all the reads you'd expect but otherwise I'm glad things are moving forward cleanly.
