### ISSUE TITLE
Variant normalization before feeding GEMINI

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1680]
Hey bcbio developers and users!

I found that bcbio reports multiallelic variants alleles like 
```
6	137325901	.	TAA	TA,T	8113.29	PASS	AC=1,5;AF=0.166667,0.833333;AN=6;CALLERS=freebayes,gatk-haplotype,platypus;CSQ=splice_region_variant&intron_variant|||ENSG00000016402|IL20RA|ENST00000316649||||-/553|protein_coding|YES|CCDS5181.1||||ENST00000316649.5:c.725-6_725-5delTTinsT|;DECOMPOSED;LEN=1,2;NS=3;TYPE=del,del	GT:AO:DP:GQ:PL:QA:QR:RO	2|2:109,3:165:99:2778,328,0,2707,257,2698:3087,89:0:0	2|1:14,94:148:49:2475,2108,2278,176,0,105:478,2892:259:7	2|2:105,1:138:99:3123,316,0,3110,303,3107:3471,18:0:0
```
in the GEMINI database as 
```
TAA>TA
```
This a rare allele not found in 1000G, exac, etc.

However when I tried to decompose with vt as described on the GEMINI website with a script
(https://github.com/naumenko-sa/bioscripts/blob/master/gemini.decompose.sh)
I got 
```
TA > T
TAA> T
```
which are high frequency variants.

Am I right that bcbio is not using VT for decomposition. Maybe it is worth trying to switch to VT instead of vcftools?

Thanks,
Sergey

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issues, bcbio does decompose variants with vt prior to preparing the GEMINI database:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/population.py#L28
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/multiallelic.py

and you should see `*-decompose*.vcf.gz` files in the `gemini` directory. This only done as part of GEMINI database preparation, not in the standard output files, since decomposed variants can also cause issues with downstream tools that expect multiallelic variants on a single line.

I'm not sure why you're not seeing this in your GEMINI database builds. Are these created with bcbio? Do you see the `decompose` files in the `gemini` directory? Definitely happy to debug further so we can figure out the issue.

**Comment by naumenko-sa** [comment]
Thanks Brad for the immediate response!
Sorry, I was wrong about the absence of vt in bcbio.

Yes, I have *decompose* files in the gemini directory.

The variant called is (as in the output file, not decomposed): 
cat 166-ensemble.vcf | grep 137325901
```
6	137325901	.	TAA	TA,T	
```
This variant as loaded into GEMINI database by bcbio:
`gemini query -q "select ref,alt,gts from variants where start=137325900" 166-ensemble.db`
```
TAA	TA	./.,./TA,./. #rare variant
TAA	T	T|T,T|.,T|T
```
The same variant loaded into GEMINI.db by my script:
`gemini query -q "select ref,alt,gts from variants where start=137325900" 166-ensemble.decomposed.db`
```
TA	T	./.,./T,./.   #frequent fariant
TAA	T	T|T,T|.,T|T
```
Variant in the vcf decomposed by bcbio:
`gunzip -c 166-ensemble-decompose-vepeffects.vcf.gz | grep 137325901`
```
6	137325901	.	TAA	TA	#rare variant
6	137325901	.	TAA	T	
```
Variant in the vcf decomposed by my script
`gunzip -c 166-ensemble.decomposed.vcf.gz | grep 137325901`
```
6	137325901	.	TA	T	#frequent variant
6	137325901	.	TAA	T	
```
The only difference between bcbio.log file and my script I see is 
the usage of vt normalize (suggested by gemini manual), and vt uniq (added by me):
```
cat $1 | sed s/"##FORMAT=<ID=AD,Number=."/"##FORMAT=<ID=AD,Number=R"/ > $bname.modified.vcf
vt decompose -s $bname.modified.vcf | vt normalize -r ~/work/tools/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa - | vt uniq - > $bname.decomposed.vcf
```
So the correct suggestion would be to use variant normalization  with vt, sorry for not figuring this out from the beginning.

Sergey

**Comment by chapmanb** [comment]
Thanks much for the detailed diagnosis. I added in `vt normalize` after decomposition to hopefully correctly clean up these type of complex variants, so hopefully bcbio will now do the right thing preparing these if you update to the latest development version. Please let us know if you run into any other issues at all.
