### ISSUE TITLE
adding module to bcbio/upload

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1686]
Hi Brad,

how hard do suppose it would be to add an extra upload function? I'd like to have a built in capability to upload the results to an iRods repository. They have a [python API client](https://github.com/irods/python-irodsclient), which should be usable.

Do you suppose this is doable? Perhaps, while we're at it, we could also add the posibility to fetch input data from irods.

Thanks
M

**Comment by schelhorn** [comment]
I'd be interested in this as well since we're using iRODS for some of our clinical data to track provenance and implement auditability. Getting this in bcbio would be nice for the future but has somewhat lower priority for us right now.

**Comment by matthdsm** [comment]
Hi Brad,
I've been looking a bit into integrating iRods and I have some questions.
What is your stand on dependencies? I don't think it's going to be possible to integrate the cli installer into bcbio or conda. Are you opposed to requiring the user to have the cli and configuration for iRods pre installed? In most (or all) cases, this will already be ok, since an iRods repo isn't usable without this installed. This would also silmplify the matter for integration, since authentication etc would be preconfigured and handled by the cli. Downloading and uploading should then only be a matter doing some subprocess calls to the cli interface.
@schelhorn, your thoughts? I think you have some more iRods experience than I have, seeing as you already have a working instance.

M

**Comment by chapmanb** [comment]
Matthias;
Having iRods installed as a separate dependency is the right way to go. This is a pretty specialized need so we don't have to ship it with bcbio right now, and will require a correctly setup environment to use it. Thanks again for looking into this.

**Comment by matthdsm** [comment]
finished upload module in #1746
