### ISSUE TITLE
bcbio installation - hg38

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1688]
Hi Brad, 

I'm (still) trying to install a clean dev version of bcbio, but when I upgrade with 
`bcbio_nextgen.py upgrade -u development --datatarget vep --datatarget dbnsfp`, neither vep or dbnsfp gets installed. Could there be some config file we forgot to edit to make this work for hg38?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issue, we'd forgotten to add dbNSFP to the available annotations for hg38. I pushed a fix that should resolve this if you remove any cached downloads (`rm -rf tmpbcbio-install`) and re-try.

For VEP, I'm not sure why it wouldn't install for hg38. Everything looks to be in place for it. Do you have any messages or other information? Does bcbio make any of the directories for the VEP databases?

Thanks for the help debugging this.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for fixing, I'm going to wait to pull the changes to avoid some overhead from dbNSFP untill my other pull request is merged (that is, if you're planning on merging off course). I seems vep was installed, but not correctly, because of the issue with bioperl, should be fixed once we can upgrade to the new version of vep.

M
