### ISSUE TITLE
GATK 3.7

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1691]
Hi Brad,

Has there been any work done to integrate GATK 3.7? Or do you suppose it'll work out of the box?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
3.7 appears to work without any problems on my initial tests. We'll also run a full validation but I don't expect issues since we've been testing with recent nightly builds because of bugs in the 3.6 release. If you hit any problems, please let us know.

**Comment by matthdsm** [comment]
Okay, thanks!

M
