### ISSUE TITLE
Can't upgrade with hg38: snpeff_v4_2_GRCh38.86.zip not found 

### ISSUE THREAD

**Issue by duxan** [chapmanb/bcbio-nextgen#1693]
Hi,

When I run upgrade with `bcbio_nextgen.py upgrade -u stable --genomes hg38 --aligners bwa --isolate` it gets to the point of downloading snpeff database when i get 404. link is below:

```
http://downloads.sourceforge.net/project/snpeff/databases/v4_2/snpEff_v4_2_GRCh38.86.zip
```

Is this a temporary network error or could be something else.

Thanks!

**Comment by chapmanb** [comment]
Dušan -- thanks for the report. When upgrading you also need to update the tools (add `--tools` to the command line) so you get the most recent snpEff release (4.3g) with support for this database. I'd also recommend upgrading to the latest development version as it has some fixes from the last stable release. We plan to have a new release soon:
```
bcbio_nextgen.py upgrade -u development --tools --genomes hg38 --aligners bwa 
```
Hope this fixes things for you.
