### ISSUE TITLE
manta file checks after bcbio restart

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1697]
Just a quick question - I have noticed that when restarting a bcbio analysis that got stuck in QC, bcbio always spawns a lot of local (because the checkpoint has been passed before) `manta` worker processes that stop again very quickly, I guess because the see that their files have already been produced. Still, doing that via `manta` takes a lot of time on a WGS set, so I was wondering whether bcbio itself could check if the `manta` output files are already there before starting manta again. This is on WGS data with a `svprioritize` and a `sv_regions`-file, if that makes a difference.

**Comment by schelhorn** [comment]
Okay, I checked again and bcbio seems to redo the whole `manta` analysis each time. I believe that may be due to @tetianakh's changes that introduced transactional directories in the manta logic. In `bcbio/structural/manta.py`, in the `run` method, the `_run_workflow()` call is not pointed towards a temporary directory which by definition is empty. On reruns, it's the job of the  `_run_workflow` method to check whether the files it writes are already in the shared directory; even if they are, `_run_workflow` cannot know about it because it only knows about the transactional directory. As a result, `manta` will now redo the whole analysis each time. It would be better if the existence of output files is checked earlier, in in the `run` method before the transactional directories are made (which aren't required anyway if the files are already there).

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks so much for catching this issue and for the analysis. I pushed fixes to check for output files prior to creation of transactional directories, so bcbio will now correctly skip manta on re-runs. Please let us know if you run into any other issues at all and thanks again.

**Comment by schelhorn** [comment]
Thanks for the quick fix; appreciated as always.
