### ISSUE TITLE
dbscsnv option missing from datatarget

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1698]
Hi Brad, 

it seems I missed something while trying to add the dbscsnv option to the installer/upgrade.
I'm getting `bcbio_nextgen.py upgrade: error: argument --datatarget: invalid choice: 'dbscsnv' (choose from 'variation', 'rnaseq', 'smallrna', 'gemini', 'cadd', 'vep', 'dbnsfp', 'battenberg', 'kraken')`

Could you check where I went wrong?
Thanks
M

**Comment by matthdsm** [comment]
Nevermind, fixed it in #1699

can you go over this and check if I didn't miss anything?


Thanks!
M

**Comment by chapmanb** [comment]
Thanks for the fix, I'll follow up in #1699
