### ISSUE TITLE
Cannot install bcbio-nextgene follow Quick-Start

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1702]
Hello:
I need your help 

I got some issue on installation bcbio-nextgen. 
I follow the instruction of Quick Start installation. My command as follows: python bcbio_nextgen_install.py ./bcbio --tooldir=./tools   --genomes GRCh37 --aligners bwa --aligners bowtie2

The log as follows:

root@ubuntu:/media/miaokui/bcbio# python bcbio_nextgen_install.py ./bcbio --tooldir=./tools   --genomes GRCh37 --aligners bwa --aligners bowtie2
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2016-12-18 16:30:13--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.100.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.100.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

100%[===================================================================================================================================================================>] 20          --.-K/s   in 0s      

2016-12-18 16:30:14 (2.34 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Fetching package metadata: ........
Solving package specifications: .........

Package plan for installation in environment /media/miaokui/bcbio/bcbio/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.0          |                1         281 KB
    libiconv-1.14              |                4         2.0 MB
    libsodium-0.4.5            |                0         529 KB
    mkl-11.3.3                 |                0       122.1 MB
    ncurses-5.9                |               10         1.1 MB
    sqlite-3.13.0              |                0         4.9 MB
    xz-5.2.2                   |                0         853 KB
    bcftools-1.3.1             |                1         1.7 MB
    curl-7.49.1                |                2         545 KB
    libpng-1.6.26              |                0         297 KB
    libtiff-4.0.6              |                7         507 KB
    libxml2-2.9.4              |                3         4.9 MB
    python-2.7.12              |                1        15.5 MB
    zeromq-4.1.5               |                0         5.0 MB
    argh-0.26.2                |           py27_0          51 KB
    backports.shutil_get_terminal_size-1.0.0|           py27_0           5 KB
    backports_abc-0.5          |           py27_0           6 KB
    boto-2.43.0                |           py27_0         1.3 MB
    certifi-2016.9.26          |           py27_0         217 KB
    click-6.6                  |           py27_0          97 KB
    configparser-3.5.0         |           py27_0          31 KB
    cython-0.25.2              |           py27_0         6.3 MB
    decorator-4.0.10           |           py27_1          14 KB
    enum34-1.1.6               |           py27_1          54 KB
    et_xmlfile-1.0.1           |           py27_0          15 KB
    fadapa-0.3.1               |           py27_0           7 KB
    freetype-2.6.3             |                1         2.8 MB
    functools32-3.2.3.2        |           py27_1          16 KB
    futures-3.0.5              |           py27_0          19 KB
    htslib-1.3.1               |                1         950 KB
    idna-2.1                   |           py27_0         111 KB
    ipaddress-1.0.17           |           py27_0          29 KB
    ipython_genutils-0.1.0     |           py27_0          33 KB
    jdcal-1.3                  |           py27_0           8 KB
    joblib-0.10.3              |           py27_0         172 KB
    libxslt-1.1.29             |                2         1.6 MB
    logbook-0.12.2             |           py27_0         220 KB
    markupsafe-0.23            |           py27_2          31 KB
    mistune-0.7.3              |           py27_0          22 KB
    msgpack-python-0.4.8       |           py27_0         243 KB
    numpy-1.11.2               |           py27_0         6.2 MB
    path.py-8.2.1              |           py27_0          45 KB
    progressbar-2.3            |           py27_0          13 KB
    psutil-5.0.0               |           py27_0         237 KB
    ptyprocess-0.5.1           |           py27_0          19 KB
    pyasn1-0.1.9               |           py27_0          56 KB
    pycparser-2.17             |           py27_0         153 KB
    pyparsing-2.1.10           |           py27_0          91 KB
    pytz-2016.10               |           py27_0         161 KB
    pyvcf-0.6.8                |           py27_0          56 KB
    pyzmq-16.0.2               |           py27_0         880 KB
    ruamel_yaml-0.11.14        |           py27_0         352 KB
    samtools-1.3.1             |                5         874 KB
    sh-1.11                    |           py27_0          37 KB
    simplegeneric-0.8.1        |           py27_1           7 KB
    simplejson-3.10.0          |           py27_0         126 KB
    sip-4.18                   |           py27_0         263 KB
    six-1.10.0                 |           py27_1          18 KB
    sqlalchemy-1.1.4           |           py27_0         1.4 MB
    ssl_match_hostname-3.5.0.1 |           py27_0           6 KB
    tabulate-0.7.7             |           py27_0          31 KB
    toolz-0.8.2                |           py27_0          84 KB
    wcwidth-0.1.7              |           py27_0          22 KB
    argcomplete-1.0.0          |           py27_1          32 KB
    azure-nspkg-1.0.0          |           py27_0           2 KB
    biopython-1.68             |      np111py27_0         2.2 MB
    cffi-1.9.1                 |           py27_0         325 KB
    conda-4.2.13               |           py27_0         374 KB
    cycler-0.10.0              |           py27_0          13 KB
    entrypoints-0.2.2          |           py27_0           6 KB
    fontconfig-2.12.1          |                1         938 KB
    jinja2-2.8                 |           py27_1         282 KB
    jsonschema-2.5.1           |           py27_0          70 KB
    lxml-3.7.0                 |           py27_0         3.3 MB
    netifaces-0.10.4           |           py27_1          28 KB
    nose-1.3.7                 |           py27_2         204 KB
    openpyxl-2.4.0             |           py27_0         265 KB
    pathlib2-2.1.0             |           py27_0          26 KB
    pexpect-4.2.1              |           py27_0          65 KB
    pillow-3.4.2               |           py27_0         926 KB
    pyfaidx-0.4.7.1            |           py27_0          39 KB
    pygments-2.1.3             |           py27_1         1.2 MB
    pysam-0.9.1.4              |           py27_0         5.1 MB
    python-dateutil-2.6.0      |           py27_0         232 KB
    requests-toolbelt-0.7.0    |           py27_0          52 KB
    scipy-0.18.1               |      np111py27_0        30.9 MB
    singledispatch-3.4.0.3     |           py27_0          12 KB
    traitlets-4.3.1            |           py27_0         121 KB
    yamllint-1.5.0             |           py27_0          41 KB
    arrow-0.10.0               |           py27_0          53 KB
    azure-common-1.1.4         |           py27_0           4 KB
    azure-mgmt-nspkg-1.0.0     |           py27_0           2 KB
    bioblend-0.8.0             |           py27_0         132 KB
    cryptography-1.6           |           py27_0         837 KB
    gffutils-0.8.7.1           |           py27_1         1.2 MB
    jupyter_core-4.2.1         |           py27_0          56 KB
    pandas-0.19.1              |      np111py27_0        16.7 MB
    patsy-0.4.1                |           py27_0         291 KB
    pickleshare-0.7.4          |           py27_0           8 KB
    prompt_toolkit-1.0.9       |           py27_0         313 KB
    qt-4.8.6                   |                3        36.3 MB
    reportlab-3.3.0            |           py27_0         2.2 MB
    tornado-4.4.2              |           py27_0         569 KB
    azure-mgmt-common-0.20.0   |           py27_0           8 KB
    azure-servicebus-0.20.1    |           py27_0          43 KB
    azure-storage-0.20.3       |           py27_0          85 KB
    ipython-5.1.0              |           py27_1         980 KB
    jupyter_client-4.4.0       |           py27_0         101 KB
    nbformat-4.2.0             |           py27_0         125 KB
    paramiko-2.0.2             |           py27_0         215 KB
    pybedtools-0.7.8           |           py27_1        12.9 MB
    pyopenssl-16.2.0           |           py27_0          68 KB
    pyqt-4.11.4                |           py27_4         3.3 MB
    statsmodels-0.6.1          |      np111py27_1         5.0 MB
    terminado-0.6              |           py27_0          18 KB
    azure-mgmt-compute-0.20.1  |           py27_0          79 KB
    azure-mgmt-network-0.20.1  |           py27_0          91 KB
    azure-mgmt-resource-0.20.1 |           py27_0          42 KB
    azure-mgmt-storage-0.20.0  |           py27_0          24 KB
    azure-servicemanagement-legacy-0.20.1|           py27_0          97 KB
    fabric-1.13.1              |           py27_0         116 KB
    ipykernel-4.5.2            |           py27_0         130 KB
    matplotlib-1.5.3           |      np111py27_3         6.6 MB
    nbconvert-4.2.0            |           py27_0         310 KB
    azure-mgmt-0.20.1          |           py27_0           3 KB
    ipyparallel-5.2.0          |           py27_1         278 KB
    notebook-4.3.0             |           py27_0         5.3 MB
    seaborn-0.7.1              |           py27_0         276 KB
    seqcluster-1.2.4a          |           py27_0         165 KB
    azure-1.0.3                |           py27_0           2 KB
    cyvcf2-0.5.5               |           py27_0         2.3 MB
    ipython-cluster-helper-0.5.1|           py27_0          29 KB
    widgetsnbextension-1.2.6   |           py27_3         1.1 MB
    ipywidgets-5.2.2           |           py27_2          61 KB
    bcbio-nextgen-1.0.0        |           py27_0         751 KB
    ------------------------------------------------------------
                                           Total:       331.3 MB

The following NEW packages will be INSTALLED:

    argcomplete:                        1.0.0-py27_1      
    argh:                               0.26.2-py27_0     
    arrow:                              0.10.0-py27_0     
    azure:                              1.0.3-py27_0      
    azure-common:                       1.1.4-py27_0      
    azure-mgmt:                         0.20.1-py27_0     
    azure-mgmt-common:                  0.20.0-py27_0     
    azure-mgmt-compute:                 0.20.1-py27_0     
    azure-mgmt-network:                 0.20.1-py27_0     
    azure-mgmt-nspkg:                   1.0.0-py27_0      
    azure-mgmt-resource:                0.20.1-py27_0     
    azure-mgmt-storage:                 0.20.0-py27_0     
    azure-nspkg:                        1.0.0-py27_0      
    azure-servicebus:                   0.20.1-py27_0     
    azure-servicemanagement-legacy:     0.20.1-py27_0     
    azure-storage:                      0.20.3-py27_0     
    backports.shutil_get_terminal_size: 1.0.0-py27_0      
    backports_abc:                      0.5-py27_0        
    bcbio-nextgen:                      1.0.0-py27_0      
    bcftools:                           1.3.1-1           
    bioblend:                           0.8.0-py27_0      
    biopython:                          1.68-np111py27_0  
    boto:                               2.43.0-py27_0     
    certifi:                            2016.9.26-py27_0  
    cffi:                               1.9.1-py27_0      
    click:                              6.6-py27_0        
    configparser:                       3.5.0-py27_0      
    cryptography:                       1.6-py27_0        
    curl:                               7.49.1-2          
    cycler:                             0.10.0-py27_0     
    cython:                             0.25.2-py27_0     
    cyvcf2:                             0.5.5-py27_0      
    decorator:                          4.0.10-py27_1     
    entrypoints:                        0.2.2-py27_0      
    enum34:                             1.1.6-py27_1      
    et_xmlfile:                         1.0.1-py27_0      
    fabric:                             1.13.1-py27_0     
    fadapa:                             0.3.1-py27_0      
    fontconfig:                         2.12.1-1          
    freetype:                           2.6.3-1           
    functools32:                        3.2.3.2-py27_1    
    futures:                            3.0.5-py27_0      
    gffutils:                           0.8.7.1-py27_1    
    htslib:                             1.3.1-1           
    icu:                                56.1-4            
    idna:                               2.1-py27_0        
    ipaddress:                          1.0.17-py27_0     
    ipykernel:                          4.5.2-py27_0      
    ipyparallel:                        5.2.0-py27_1      
    ipython:                            5.1.0-py27_1      
    ipython-cluster-helper:             0.5.1-py27_0      
    ipython_genutils:                   0.1.0-py27_0      
    ipywidgets:                         5.2.2-py27_2      
    jdcal:                              1.3-py27_0        
    jinja2:                             2.8-py27_1        
    joblib:                             0.10.3-py27_0     
    jpeg:                               9b-0              
    jsonschema:                         2.5.1-py27_0      
    jupyter_client:                     4.4.0-py27_0      
    jupyter_core:                       4.2.1-py27_0      
    libffi:                             3.2.1-2           
    libgcc:                             5.2.0-0           
    libgfortran:                        3.0.0-1           
    libiconv:                           1.14-4            
    libpng:                             1.6.26-0          
    libsodium:                          0.4.5-0           
    libtiff:                            4.0.6-7           
    libxml2:                            2.9.4-3           
    libxslt:                            1.1.29-2          
    logbook:                            0.12.2-py27_0     
    lxml:                               3.7.0-py27_0      
    markupsafe:                         0.23-py27_2       
    matplotlib:                         1.5.3-np111py27_3 
    mistune:                            0.7.3-py27_0      
    mkl:                                11.3.3-0          
    msgpack-python:                     0.4.8-py27_0      
    nbconvert:                          4.2.0-py27_0      
    nbformat:                           4.2.0-py27_0      
    ncurses:                            5.9-10            
    netifaces:                          0.10.4-py27_1     
    nose:                               1.3.7-py27_2      
    notebook:                           4.3.0-py27_0      
    numpy:                              1.11.2-py27_0     
    openpyxl:                           2.4.0-py27_0      
    pandas:                             0.19.1-np111py27_0
    paramiko:                           2.0.2-py27_0      
    path.py:                            8.2.1-py27_0      
    pathlib2:                           2.1.0-py27_0      
    patsy:                              0.4.1-py27_0      
    pexpect:                            4.2.1-py27_0      
    pickleshare:                        0.7.4-py27_0      
    pillow:                             3.4.2-py27_0      
    progressbar:                        2.3-py27_0        
    prompt_toolkit:                     1.0.9-py27_0      
    psutil:                             5.0.0-py27_0      
    ptyprocess:                         0.5.1-py27_0      
    pyasn1:                             0.1.9-py27_0      
    pybedtools:                         0.7.8-py27_1      
    pycparser:                          2.17-py27_0       
    pyfaidx:                            0.4.7.1-py27_0    
    pygments:                           2.1.3-py27_1      
    pyopenssl:                          16.2.0-py27_0     
    pyparsing:                          2.1.10-py27_0     
    pyqt:                               4.11.4-py27_4     
    pysam:                              0.9.1.4-py27_0    
    python-dateutil:                    2.6.0-py27_0      
    pytz:                               2016.10-py27_0    
    pyvcf:                              0.6.8-py27_0      
    pyzmq:                              16.0.2-py27_0     
    qt:                                 4.8.6-3           
    reportlab:                          3.3.0-py27_0      
    requests-toolbelt:                  0.7.0-py27_0      
    ruamel_yaml:                        0.11.14-py27_0    
    samtools:                           1.3.1-5           
    scipy:                              0.18.1-np111py27_0
    seaborn:                            0.7.1-py27_0      
    seqcluster:                         1.2.4a-py27_0     
    sh:                                 1.11-py27_0       
    simplegeneric:                      0.8.1-py27_1      
    simplejson:                         3.10.0-py27_0     
    singledispatch:                     3.4.0.3-py27_0    
    sip:                                4.18-py27_0       
    six:                                1.10.0-py27_1     
    sqlalchemy:                         1.1.4-py27_0      
    ssl_match_hostname:                 3.5.0.1-py27_0    
    statsmodels:                        0.6.1-np111py27_1 
    tabulate:                           0.7.7-py27_0      
    terminado:                          0.6-py27_0        
    toolz:                              0.8.2-py27_0      
    tornado:                            4.4.2-py27_0      
    traitlets:                          4.3.1-py27_0      
    wcwidth:                            0.1.7-py27_0      
    widgetsnbextension:                 1.2.6-py27_3      
    xz:                                 5.2.2-0           
    yamllint:                           1.5.0-py27_0      
    zeromq:                             4.1.5-0           

The following packages will be UPDATED:

    conda:                              4.0.5-py27_0 --> 4.2.13-py27_0     
    conda-env:                          2.4.5-py27_0 --> 2.6.0-0           
    python:                             2.7.11-0     --> 2.7.12-1          
    sqlite:                             3.9.2-0      --> 3.13.0-0          

Installing data and third party dependencies
Upgrading bcbio
Upgrading third party tools to latest versions
--2016-12-18 17:28:04--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2016-12-18 17:28:07--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘STDOUT’

    [              <=>                                                                                                            ] 3,062,218   1020KB/s              [               <=>                                                                                                         ] 3,069,068   1021KB/s                [                    <=>                                                                                               ] 5,158,936   1.39MB/s   in 3.5s    

2016-12-18 17:28:12 (1.39 MB/s) - written to stdout [5158936]

mv: cannot stat ‘master’: No such file or directory
Traceback (most recent call last):
  File "/media/miaokui/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0', 'bcbio_nextgen.py')
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 211, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 79, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 449, in upgrade_thirdparty_tools
    cbl_deploy = __import__("cloudbio.deploy", fromlist=["deploy"])
  File "/media/miaokui/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 10, in <module>
    from cloudbio.biodata.genomes import install_data, install_data_s3, install_data_rsync
  File "/media/miaokui/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 32, in <module>
    from cloudbio.biodata import dbsnp, galaxy, ggd, rnaseq
  File "/media/miaokui/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 23, in <module>
    from fabric.contrib.files import cd
ImportError: cannot import name cd
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 246, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/media/miaokui/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=./tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

It looks like the command  '['/media/miaokui/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=./tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']'  does not run successfully, so I try following: /media/miaokui/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py upgrade --tooldir=./tools --genomes GRCh37 --aligners bwa --aligners bowtie2 --data 

Then the error is Upgrading bcbio
Upgrading third party tools to latest versions
Traceback (most recent call last):
  File "/media/miaokui/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen==1.0.0', 'bcbio_nextgen.py')
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1484, in run_script
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio_nextgen-1.0.0-py2.7.egg-info/scripts/bcbio_nextgen.py", line 211, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 79, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/media/miaokui/bcbio/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 449, in upgrade_thirdparty_tools
    cbl_deploy = __import__("cloudbio.deploy", fromlist=["deploy"])
  File "/media/miaokui/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 10, in <module>
    from cloudbio.biodata.genomes import install_data, install_data_s3, install_data_rsync
  File "/media/miaokui/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 32, in <module>
    from cloudbio.biodata import dbsnp, galaxy, ggd, rnaseq
  File "/media/miaokui/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/dbsnp.py", line 23, in <module>
    from fabric.contrib.files import cd
ImportError: cannot import name cd

There are no cd object in fabric.contrib.files. I wondering why. 
I really apreciate someone who can help me. 
My system is ubuntu 14.04

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. This was due to some older code in the install referring to a previous location of the fabric `cd` function. I cleaned up the old code and pushed a fix, so if you:
```
rm -rf tmpbcbio-install
/media/miaokui/bcbio/bcbio/anaconda/bin/bcbio_nextgen.py upgrade --tooldir=./tools --genomes GRCh37 --aligners bwa --aligners bowtie2 --data
```
It should hopefully run correctly for you now. Thanks again and please let us know if you run into any other issues at all.

**Comment by MIAOKUI** [comment]
Thank you for your answer, I'll try it out. 

Thanks 
Emmanuel Miao kui
