### ISSUE TITLE
`plugin_fields` variable in vep annotations doesn't seem to get used anywhere

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1705]
I came across that as I read the code to emulate what bcbio did with VEP in some post-pipeline scripts. I noticed that such a list is continuously added to, but not used. Perhaps it's meant to be passed to the `fields` parameter along with the standard fields?

**Comment by chapmanb** [comment]
Luca -- thank you for the code review. You're exactly right, this was a typo and I pushed a fix to actually use the specifications for VEP output. Thanks again for catching this.
