### ISSUE TITLE
CRAN + bioconductor dependencies list / install script

### ISSUE THREAD

**Issue by stephenturner** [chapmanb/bcbio-nextgen#1706]
Small feature request: might be nice to output a list of required CRAN/bioconductor packages needed to compile the Rmd reports written out by the smallrna-seq pipeline. Better yet, a script to run the appropriate installation command, whether that's `install.packages` for CRAN, `biocLite` for bioc, or `devtools::install_github()`. Just grepping for `library` in some of the Rmd scripts shows:

```r
library(CHBUtils)
library(DESeq2)
library(DT)
library(RColorBrewer)
library(devtools)
library(dplyr)
library(edgeR)
library(genefilter)
library(ggplot2)
library(gridExtra)
library(gtools)
library(isomiRs)
library(knitr)
library(pheatmap)
library(reshape)
library(reshape2)
library(rmarkdown)
library(scales)
library(tidyr)
library(vsn)
```

I'm sure there are others elsewhere when an Rmd script is written to be optionally compiled by the user.

**Comment by roryk** [comment]
Hi Stephen,

Thanks-- there is a script here:

https://github.com/roryk/bcbio.rnaseq/blob/master/resources/scripts/install_libraries.R

The bcbio.rnaseq that gets installed via bioconda is a little out of date. I had trouble getting all the dependencies to build in bioconda a while ago, but I will revisit it now that bioconda got more stable.

**Comment by lpantano** [comment]
Hi @stephenturner 

I am closing this, please feel free to open an issue if you find again the problem.

thanks!
