### ISSUE TITLE
Upload MultiQC list_files.txt into final

### ISSUE THREAD

**Issue by vladsaveliev** [chapmanb/bcbio-nextgen#1708]
Would be useful to allow to easily regenerate the MultiQC report after losing the work directory. For instance, to add extra stuff into the report later.

- Upload `work/list_files.txt` into `final/<datestamp>/multiqc`
- Modify all paths in list_files.txt to link to qc in `final` instead of `work`

I plan to handle it, so creating the issue more for myself.

**Comment by lpantano** [comment]
this sounds super great! let me know if there is something I can do to help!
