### ISSUE TITLE
effects_transcripts option is unexpected

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1713]
Hello!

I have started using 
```effects_transcripts: all```
 in the config file and got an error:
```
ValueError: Unexpected configuration keyword in 'algorithm' section: ['effects_transcripts']
```

Could you please check this? I'm on the latest update.

Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
Sorry about the issue, this should work cleanly on the latest development version:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/run_info.py#L425

 Is it possible you're on the last release. An update with `bcbio_nextgen.py upgrade -u development` should enable this. Hope that fixes it for you.

**Comment by naumenko-sa** [comment]
Thanks Brad,

I'm usually on latest development, but today I have somehow lost this status solving this issue
https://github.com/chapmanb/bcbio-nextgen/issues/1712

Now it works.

Sergey
