### ISSUE TITLE
Where is the code for lsf scheduler 

### ISSUE THREAD

**Issue by MIAOKUI** [chapmanb/bcbio-nextgen#1717]
Hi, 

I found bcbio can be adapted on lsf scheduler on https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html. But the source code, I only find torgue, sge, slurm, on /provenance/system.py. I wonder where is the lsf scheduler definition? The codes part :

 `sched_info_dict = {
                            "slurm": _slurm_info,
                            "torque": _torque_info,
                            "sge": _sge_info
`
There is no lsf scheduler, I wondering where they are?   The source code is downloaded from github recently. 

Thank you for your help, I really like to learn the source codes. 

Emmanuel

**Comment by chapmanb** [comment]
Emmanuel;
The majority of the code for scheduler batch job preparation is in the ipython-cluster-helper project (https://github.com/roryk/ipython-cluster-helper). The main classes are here:

https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L142

and the utility functions for LSF code are here:

https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/lsf.py

Hope this helps.

**Comment by MIAOKUI** [comment]
Great thanks, Chapmanb !
I really like bcbio project, I'll take time to learn the codes :)

**Comment by lpantano** [comment]
Hi @MIAOKUI 

I will close this guessing you got what you needed. Let us know if you find more issues.

Thanks!
