### ISSUE TITLE
py.test tests/unit unable to import ConfigParser with Python 3.4.5 

### ISSUE THREAD

**Issue by anchizhang** [chapmanb/bcbio-nextgen#1720]
(.venv) [azhang@node15 bcbio-nextgen]$ pip install ConfigParser
Requirement already satisfied: ConfigParser in ./.venv/lib/python3.4/site-packages
(.venv) [azhang@node15 bcbio-nextgen]$ pip freeze | grep -i configparser
configparser==3.5.0
(.venv) [azhang@node15 bcbio-nextgen]$ py.test tests/unit
============================= test session starts ==============================
platform linux -- Python 3.4.5, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /home/azhang/bcbio-nextgen, inifile:
collected 0 items / 3 errors

==================================== ERRORS ====================================
________________ ERROR collecting tests/unit/test_alignprep.py _________________
ImportError while importing test module '/home/azhang/bcbio-nextgen/tests/unit/test_alignprep.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/test_alignprep.py:1: in <module>
    from bcbio.ngsalign import alignprep
bcbio/ngsalign/alignprep.py:12: in <module>
    from bcbio import bam, utils
bcbio/bam/__init__.py:13: in <module>
    from bcbio import utils
bcbio/utils.py:12: in <module>
    import ConfigParser
E   ImportError: No module named 'ConfigParser'
_________ ERROR collecting tests/unit/distributed/test_transaction.py __________
ImportError while importing test module '/home/azhang/bcbio-nextgen/tests/unit/distributed/test_transaction.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/distributed/test_transaction.py:4: in <module>
    from bcbio.distributed import transaction
bcbio/distributed/transaction.py:15: in <module>
    from bcbio import utils
bcbio/utils.py:12: in <module>
    import ConfigParser
E   ImportError: No module named 'ConfigParser'
______________ ERROR collecting tests/unit/ngsalign/test_star.py _______________
ImportError while importing test module '/home/azhang/bcbio-nextgen/tests/unit/ngsalign/test_star.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/ngsalign/test_star.py:7: in <module>
    from bcbio.ngsalign.star import _get_star_dirnames
bcbio/ngsalign/star.py:9: in <module>
    from bcbio.distributed.transaction import file_transaction, tx_tmpdir
bcbio/distributed/transaction.py:15: in <module>
    from bcbio import utils
bcbio/utils.py:12: in <module>
    import ConfigParser
E   ImportError: No module named 'ConfigParser'
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 3 error in 0.91 seconds ============================

**Comment by chapmanb** [comment]
Thank you for the report and sorry about the test suite issues. bcbio is not compatible with Python 3. This is something we'd like to work on but hasn't yet been a priority over pipeline development and parallelization improvements.

bcbio pre-installs `py.test` and has a small wrapper that makes it easy to use, and that is the best bet for running the tests. Apologies, the documentation was out of date on this and I updated to reflect the suggested approach:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#test-suite

Hope that will gets tests working for you.
