### ISSUE TITLE
Possible "GATK RUNTIME ERROR" w/ Freebayes crashes job

### ISSUE THREAD

**Issue by pjr314** [chapmanb/bcbio-nextgen#1726]
I woke up to a monster of a crash, not sure even where to start with the output, I'm including everything from where it starts to go wonky.  Also here is my config file.

details:
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS2A
  files:
  - /efs/merged/MS2A_R1.fastq.gz
  - /efs/merged/MS2A_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS2B
  files:
  - /efs/merged/MS2B_R1.fastq.gz
  - /efs/merged/MS2B_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS2C
  files:
  - /efs/merged/MS2C_R1.fastq.gz
  - /efs/merged/MS2C_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS4D
  files:
  - /efs/merged/MS4D_R1.fastq.gz
  - /efs/merged/MS4D_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS4F
  files:
  - /efs/merged/MS4F_R1.fastq.gz
  - /efs/merged/MS4F_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS8DC
  files:
  - /efs/merged/MS8DC_R1.fastq.gz
  - /efs/merged/MS8DC_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    ensemble:
      numpass: 3
    mark_duplicates: true
    mixup_check:
    - qsignature_full
    phasing: false
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    variantcaller:
    - samtools
    - platypus
    - gatk-haplotype
    - freebayes
  analysis: variant2
  description: MS8M
  files:
  - /efs/merged/MS8M_R1.fastq.gz
  - /efs/merged/MS8M_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: WGS_MS_Project
    description: null
    phenotype: null
fc_date: '2016-12-01'
fc_name: MS_Project_WGS-merged
upload:
  dir: ../final

[nohup.out.txt](https://github.com/chapmanb/bcbio-nextgen/files/690488/nohup.out.txt)

**Comment by chapmanb** [comment]
Thanks for the report, it looks like you're running into this known bug in GATK 3.6:

http://gatkforums.broadinstitute.org/gatk/discussion/7756/hashmap-iterator-problem-with-gatk-3-6-on-na12878-validations

This bug is fixed in the GATK 3.7 release, so If you update GATK with `gatk-register` (http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#gatk-and-mutect-mutect2) it should hopefully finish cleanly. Hope this helps.
