### ISSUE TITLE
goleft usage

### ISSUE THREAD

**Issue by brentp** [chapmanb/bcbio-nextgen#1731]
hi Brad,
I was looking at making some changes in `goleft depth` so I was checking your usage to see how it would affect bcbio. It looks like you are needlessly using windows.

For whole-genome, it will be much faster to call goleft without `--bed` and if you must use --bed, then use a much larger window size (at least 1e6),

Currently, goleft depth is much slower for exomes when `--bed` is specified (vs running without a --bed argument). So that's what I'm intending to fix--especially if you use that argument with the capture regions when bcbio runs exomes. If not, I'm tempted to remove it because most of the non-capture regions will be empty and the user can always do an bedtools intersect -v post-hoc. Please let me know your thoughts.

**Comment by chapmanb** [comment]
Brent;
Thanks for looking at this. For whole genome I'm using a BED file of each chromosome from all non-alts (to avoid HLAs and other messy alts on hg38). For targeted, I'm using a BED file of capture regions. We could run bedtools post-run if it's faster to do an exome without and BED file regions.

For windows, I was looking at supporting pre-calculated depth for CNVkit and other callers but you're right, 5000 is too big for those and I guess slowing down goleft so is not very useful.

Happy to adjust to whatever is fastest and easiest for implementation. I wanted to have a new release of bcbio soon and could re-work this right afterwards if that works for your timeline.

**Comment by brentp** [comment]
so, bcbio uses --window (-w) and --bed for whole-genome? What is the purpose of --bed in that case? It slows it down execution and gives (should give) identical output.

for exome:
do you use the output in .depth.bed? if not, then we can just not use --bed and goleft will report all callable regions regardless of capture region in .callable.bed

**Comment by chapmanb** [comment]
Brent -- the idea of `--bed` for whole genome is to avoid calculating callable regions on alts on hg38. The HLA naming with asterisks screws up downstream programs so we avoid including them for variant/SV analysis.

We're not using `.depth.bed` right now. I was aiming to as a plan to avoid downstream coverage calculations but the file sizes are so big to provide any kind of generic output that I haven't switched over.

So it sounds like my best approach is to avoid using `--bed` and then subset afterwards with contigs we want for WGS and variant regions for exome/capture. Is that right?

**Comment by brentp** [comment]
Is the naming something that goleft can address or does it error in samtools? Or do you just need to exclude those regions for other tools? I'll see if I can find an hg38+alts bam on our cluster.

I can make .depth.bed output bgzipped files. Those should compress pretty well. You can also decide not to use --stats to reduce file size, if that is unused (though I think that cnvkit could use that).

> best approach is to avoid using --bed and then subset afterwards with contigs we want for WGS and 
> variant regions for exome/capture. Is that right?

Because the code works so fast, and I want to keep (or make) it simple, yes. The limitation is that if you choose a 300 base --window so you get e.g. '6:1200-1500' and your capture region is 6:1200-1250' then the mean coverage value will be based on 300 bases instead of on 50. I've come up with a number of ways to resolve that, but they all end up being so complex that I have scrapped it.

One addition would be to have an additional column indicating the number of covered bases.
I'm still thinking on the best way to resolve this, and I might find a solution that works OK, but it would be good to get your input on exactly what's needed downstream.

**Comment by chapmanb** [comment]
Brent -- sorry, samtools and coverage calculations handle it fine, it's some downstream tools that fail on it so I exclude them from callable regions and then don't work on them. So I think goleft is fine, just telling you the rationale behind having a BED file. Here's the hg38 build from 1000 genomes we use:

ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/

I might punt on `.depth.bed` for right now and just work on making coverage calculations fast until we can revisit with CNVkit and Seq2C CNV calling in might. bgzip would help but it's still a huge file because we end up needing pretty precise resolution. @etal would be the best person to provide details about what a CNVkit ready coverage file could look like, and I could work from that.

**Comment by chapmanb** [comment]
Brent -- thanks again for the suggestions on goleft depth usage. I pushed an improved version of bcbio integration that avoids setting `--windowsize` and `--bed` and lets goleft use whatever it thinks best for parallelizing. When we have a good plan for CNVkit integration we can work to re-include depth based calculations here to try to avoid an extra step but hopefully this update makes it easier to add the changes you have planned for `goleft depth`. Thanks again.
