### ISSUE TITLE
Duplicate variants are sometimes created by freebayes pipe, remove with vcfuniq and createmulti?

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1733]
Hi,

Duplicate variants are sometimes created by freebayes output piped into vcfallelicprimitives and vt normalize. 

```
Chr_01       	51900	.      	G      	A      	703.53 	PASS   	AC=3;AF=0.214286;AN=14;DECOMPOSED;LEN=1;NS=7;TYPE=snp  
Chr_01       	51900	.      	G      	A      	1106.57	PASS   	AC=3;AF=0.214286;AN=14;DECOMPOSED;LEN=1;NS=7;TYPE=snp  
							
Chr_01       	52142       	.      	GAT    	G      	148.23 	PASS   	AC=1;AF=0.0714286;AN=14;DECOMPOSED;LEN=2;NS=7;OLD_VARIANT=Chr_01:52146:TAT/T;TYPE=del
Chr_01       	52142       	.      	G      	GATATAT	148.23 	PASS   	AC=4;AF=0.285714;AN=14;DECOMPOSED;LEN=6;NS=7;OLD_VARIANT=Chr_01:52149:A/ATATATA;TYPE=ins     
							
Chr_01 	8253       	.      	C      	T      	3704.88	PASS   	AC=1;AF=0.0714286;AN=14;DECOMPOSED;LEN=1;NS=7;TYPE=snp 
Chr_01 	8253       	.      	C      	T      	4782.19	PASS   	AB=0.76087;ABP=193.345;AC=2;AF=0.142857;AN=14;AO=257;CIGAR=1X;DP=561;DPB=561;DPRA=2.00775;EPP=156.999;EPPR=4.41033;GTI=3;LEN=1;MEANALT=1;MQM=32.821;MQMR=47.0164;NS=7;NUMALT=1;ODDS=2.10787;PAIRED=0.996109;PAIREDR=0.947368;PAO=0;PQA=0;PQR=0;PRO=0;QA=9255;QR=11131;RO=304;RPL=165;RPP=48.0367;RPPR=19.4678;RPR=92;RUN=1;SAF=214;SAP=250.077;SAR=43;SRF=171;SRP=13.3248;SRR=133;TYPE=snp;technology.illumina=1 
							
Chr_01 	5376	.      	T      	A,G    	3451.33	PASS   	AC=1,2;AF=0.0714286,0.142857;AN=14;DECOMPOSED;LEN=1,1;NS=7;TYPE=snp,snp
Chr_01 	5376	.      	T      	G      	703.53 	PASS   	AC=3;AF=0.214286;AN=14;DECOMPOSED;LEN=1;NS=7;TYPE=snp  
```

This seems to be linked to duplicated regions  (coverage 80x were 20x expected) and regions were INDELs are located. 

The exact duplicate variants can be removed with vcfuniq. 

The duplicate variants that have different alternative alleles can be collapsed with createmulti (also from vcflib). This did collapse way more variants then I expected; ca 1.5 M on 40M total to 0.5M new multi-allelic variants and 1M existing multi-allelic variants. 

Do you also see these duplicate variants in your output?

And would you consider adding vcfuniq and createmulti to the freebayes variant calling pipe? 
vcfuniq seems to be a small change without side effect. 

I am not sure myself about the side effects / full impact of createmulti. 

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thanks for the suggestion. I haven't spotted this previously, so appreciate the heads up. I'd be for including `vt uniq` (https://github.com/atks/vt) into the pipeline and doing validations following that. I can take that on after the next release to not delay that any longer. I'm not as sure about collapsing with createmulti, as that is likely to start creating issues with incorrect INFO/FORMAT fields. That's already a problematic issue with our use of vcfallelicprimatives and I worry this would make it worse. Thanks again for starting this discussion.

**Comment by NeillGibson** [comment]
Yes I also wasn't sure about createmulti. `vt uniq` sounds good.

**Comment by chapmanb** [comment]
Neill -- thank you again for the debugging and suggestion. Validation runs for adding `vt uniq` look great and it removes some false positives in a NA12878 comparison (http://imgur.com/a/dF1XZ). I checked in this fix and hopefully it'll resolve the issues you saw in your samples. Much appreciated.
