### ISSUE TITLE
activate vcf2db on hg38

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1735]
Hi Brad, 

I've tried several times to update my bcbio development instance and do a run on hg38, but I don't seems to be able to create db's. Am I missing some option somewhere? I can see vcfanno working in the logs, but no vcf2db.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
We almost have everything in place for GEMINI hg38 support through vcfanno/vcf2db, and I think by tomorrow it'll be ready to run without any potential sticking points.

That said, it should run both vcfanno and vcf2db right now. There is no logic in the code to run vcfanno and skip vcf2db; they happen back to back:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/population.py#L49

What commands do you see for `vcfanno` in `log/bcbio-nextgen-commands.log`. Do you have any kind of error message or other debugging info to look at what is going on?

**Comment by matthdsm** [comment]
Apologies, I stand corrected.
Neither vcf2db nor vcfanno is run. 
I updated the code as usual with `bcbio_nextgen.py upgrade -u development` but I still feel like something is missing. Could there be some config file that doensn't autmatically update? 
The `vcfanno`dir under `bcbio/genomes/Hsapiens/hg38/` is also still empty in my case.

Thanks for the help
M

**Comment by chapmanb** [comment]
Matthias;
You'll need to update the data as well to pull in the vcfanno configuration and files for hg38:
```
bcbio_nextgen.py upgrade --data
```
Hope this gets it running for you.

**Comment by matthdsm** [comment]
yep, fixed it for me, stupid oversight!

Thanks for the help!
M
