### ISSUE TITLE
Deprecate Galaxy integration

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1737]
Hi Brad,

This isn't a priority, but I think the built in Galaxy integration can be deprecated. The Galaxy dev's have already abandoned the integrated LIMS effort for further development (I asked a while ago), and after several tries, I haven't gotten it to work properly (or at all).

This deprecation could clean out some unused functions in the codebase, and perhaps fix something that's bothered me for some time. After installing bcbio, there's a `config` and a `galaxy` directory in the install dir. However, the main configuration file is found under `galaxy`instead of `config`, which seems counterintuitive to me.

I don't know what your stand is on this matter, but if possible I'd like to see all configuration files moved to `config` for the sake of clarity and to just drop the whole `galaxy` directory

Hoping to hear your thoughts on this.
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the discussion. We still support older LIMS integrations with Galaxy using bcbio so have no plans to remove the code, but don't recommend using it for future development.

This is a separate issue from the location of the `bcbio_system.yaml` file. We could migrate this to be in `config` by default if it makes maintenance much clearer. I agree it makes more sense, but also requires making the change and being back compatible with old installations so we haven't prioritized it. If you find it a serious issue for understanding bcbio we could put it on the list of things to work on. Thanks again..

**Comment by matthdsm** [comment]
Hi Brad,

I understand the need for backward compatibility. I don't really mind the current location of the config, I just thought I'd bring it up for the sake of clarity. I'll close the issue and this idea can be put on the back burner. 

Thanks for chiming in. 
M
