### ISSUE TITLE
Getting Lumpy pipeline to work robust from BAM files

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1738]
Hi Brad, 

Running the lumpy pipe line from BAM files still does not work for us. 
I am running bcbio version 1.0a ( this commit to be specific: fb4a04b )

BCBio currently creates a complex pipe to extract the discordant and split read BAM files that LUMPY needs.
https://github.com/chapmanb/bcbio-nextgen/blob/edc5930469d6f50036fbf6fbf8e72bd3fb145c1b/bcbio/structural/shared.py#L215

Running Lumpy from FASTQ works, but is very inefficiently because we want regularly rerun SV calling over increasing cohorts. Staring from FASTQ gives the extra overhead of rerunning BWA and duplicating all our BAM data. 

Running Manta from BAM files works, but Manta has a much lower sensitivity on our known SV's than Lumpy. 

I see 3 possible ways of getting Lumpy to work robust starting from BAM files:
1. finding and fixing (upstream) all the bugs in this pipe / the tools in this pipe
2. replacing this pipe with a more simple serial set of steps
3. falling back to a more simple set of serial steps on crash of the complex pipe

Lumpy recommend this set of serial steps to create the discordant and split read bam files.
https://github.com/arq5x/lumpy-sv

```
# Align the data
bwa mem human_g1k_v37.fasta sample.1.fq sample.2.fq \
    | samtools view -S -b - \
    > sample.bam 

# Extract the discordant paired-end alignments.
samtools view -b -F 1294 sample.bam > sample.discordants.unsorted.bam 

# Extract the split-read alignments
samtools view -h sample.bam \
    | scripts/extractSplitReads_BwaMem -i stdin \
    | samtools view -Sb - \
    > sample.splitters.unsorted.bam 

# Sort both alignments
samtools sort sample.discordants.unsorted.bam sample.discordants
samtools sort sample.splitters.unsorted.bam sample.splitters
```

To find and fix all the bugs in the pipe we could use the BAM files that we created with BCBio for a set of public fastq files from a consortium. 

Once we identified the BAM or BAM slices that cause the problems we could send you those or the ENA links to the fastq files for further debugging / having upstream tools fix the issues. 

What are your thoughts on this?

Thank you.

**Comment by chapmanb** [comment]
Neill;
Sorry you're still having problems with this even with the most recent samblaster update (0.1.24). Are these larger BAM files that might be running out of memory, or some other issue? The pipe we're running is the equivalent of what the lumpy documentation recommends, but we try to keep things off disk to avoid IO and file intermediates.

A reproducible example would certainly help try to diagnose what is happening and come up with some workaround. As an alternative, would being able to pass in the `split` and `discordant` reads directly help, or are these BAM files prepared by a method other than bcbio so you don't have them? Thanks much for the help debugging.

**Comment by NeillGibson** [comment]
Hi Brad, 

Yes I am using the most recent samblaster: `samblaster: Version 0.1.24`

The bam files are not very big. ca 3GB, as the reference genome of the species that I tested with is only a few 100 megabase.

Our current plan is to only archive 1 BAM file per sample, so we rather recreate the split and discordant bam files every time we run Lumpy. Archiving the split and discordant BAM files would mean more complex data management.  Therefore I would like to give debugging the pipe first another shot. 

The bam files are produced by BCBio version 0.9.9 or 1.0.0. 

Running the pipe in bcbio local mode and even outside of bcbio on a large memory machine also crashed. 

Are there any more updates coming up to the lumpy pipeline? And is a release a new bcbio release close? Then I could pick a version a bcbio to test with and try to send you a reproducible case based on the data from ENA.

**Comment by chapmanb** [comment]
Neill;
Thanks again for all of this. The latest development version of bcbio now uses the extract_sv_reads (https://github.com/hall-lab/extract_sv_reads) tool from Dave Larson to pull split and discordant reads. This is much more straightforward and less resource intensive than the previous approach since we don't need to namesort the input file. It worked cleanly on my test sets and I hope will avoid the issues you were seeing. If you still run into any problems happy to diagnose further, but hope this helps fix any problems with your BAM based lumpy runs.

**Comment by NeillGibson** [comment]
Thank you Brad!
