### ISSUE TITLE
RNASeq example troubleshooting: tophat won't complete

### ISSUE THREAD

**Issue by dbrami** [chapmanb/bcbio-nextgen#1739]
Hi,
I've been trying to run the RNAseq example but I have been unsuccessful so far.
I believe the pipeline is crapping out at the Tophat stage.
Kindly take a look at my error log ([run2.err.txt](https://github.com/chapmanb/bcbio-nextgen/files/700532/run2.err.txt)) and let me know what you think is going on.
It is worth noting that I am running the dev version of the BCBio package (needed to update to get exome pipeline to run).
I tried running the test scripts and unfortunately these were unsuccessful.
Here's what happens when I try to run the tests:
```
[sbsuser@localhost bin]$ ./py.test -v -s -m rnaseq
============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /mnt/bcbio/anaconda/bin/python
cachedir: .cache
rootdir: /mnt/bcbio/anaconda/bin, inifile: 
plugins: cov-2.4.0, marks-0.4, mock-1.1
collected 0 items 

======================================================================= no tests ran in 0.11 seconds ========================================================================

```

**Comment by roryk** [comment]
Hi Daniel,

Sorry for the troubles. For the first error, I think that sometimes happens when you've run out of diskspace. Could you check to see if that is the case?

For running the tests, you'll need to run the code from the main repository. So if you do:

```
git clone git@github.com:chapmanb/bcbio-nextgen.git
cd bcbio-nextgen
py.test -v -s -m rnaseq
```

it should find the tests and run them.

**Comment by dbrami** [comment]
Hi Rory,
Thank you very much for getting back to me promptly.
I checked the available disk space and I have plenty - terabytes of free disk space. So I'm glad that's not the issue.

```[sbsuser@localhost src]$ git clone https://github.com/chapmanb/bcbio-nextgen.git
Cloning into 'bcbio-nextgen'...
remote: Counting objects: 34550, done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 34550 (delta 62), reused 0 (delta 0), pack-reused 34437
Receiving objects: 100% (34550/34550), 26.42 MiB | 515.00 KiB/s, done.
Resolving deltas: 100% (24881/24881), done.
[sbsuser@localhost src]$ cd bcbio-nextgen/
[sbsuser@localhost bcbio-nextgen]$ py.test -v -s -m rnaseq
-bash: py.test: command not found
[sbsuser@localhost bcbio-nextgen]$ echo $PATH
/mnt/bcbio/tools/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/sbsuser/.local/bin:/home/sbsuser/bin```

The git command you suggested did not work for me so I had to replace it that component.
Then py.test is a located in anaconda/bin which is not added to the path as part of the bcbio installation.
I then ran the test from "src/bcbio-nextgen" (location from above) using the following command:
```/mnt/bcbio/anaconda/bin/py.test -v -s -m rnaseq```.
Unforturnately, the tests didnt seem to go too well:
```[sbsuser@localhost bcbio-nextgen]$ /mnt/bcbio/anaconda/bin/py.test -v -s -m rnaseq
============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.13, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /mnt/bcbio/anaconda/bin/python
cachedir: .cache
rootdir: /mnt/bcbio/src/bcbio-nextgen, inifile: 
plugins: cov-2.4.0, marks-0.4, mock-1.1
collected 61 items / 3 errors 

================================================================================== ERRORS ===================================================================================
_____________________________________________________________ ERROR collecting scripts/utils/test_resources.py ______________________________________________________________
ImportError while importing test module '/mnt/bcbio/src/bcbio-nextgen/scripts/utils/test_resources.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
scripts/utils/test_resources.py:7: in <module>
    from bcbio.install import _get_data_dir
bcbio/install.py:24: in <module>
    from bcbio import broad, utils
bcbio/broad/__init__.py:19: in <module>
    from bcbio.provenance import do, programs
bcbio/provenance/programs.py:14: in <module>
    from bcbio.pipeline import config_utils, version
E   ImportError: cannot import name version
____________________________________________________________ ERROR collecting tests/integration/test_pipeline.py ____________________________________________________________
ImportError while importing test module '/mnt/bcbio/src/bcbio-nextgen/tests/integration/test_pipeline.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/integration/test_pipeline.py:12: in <module>
    from bcbio.provenance import programs
bcbio/provenance/programs.py:14: in <module>
    from bcbio.pipeline import config_utils, version
E   ImportError: cannot import name version
_____________________________________________________________ ERROR collecting tests/unit/ngsalign/test_star.py _____________________________________________________________
ImportError while importing test module '/mnt/bcbio/src/bcbio-nextgen/tests/unit/ngsalign/test_star.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/unit/ngsalign/test_star.py:7: in <module>
    from bcbio.ngsalign.star import _get_star_dirnames
bcbio/ngsalign/star.py:15: in <module>
    from bcbio.ngsalign import postalign
bcbio/ngsalign/postalign.py:14: in <module>
    from bcbio import bam, broad, utils
bcbio/broad/__init__.py:16: in <module>
    from bcbio.broad import picardrun
E   ImportError: cannot import name picardrun
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 54 tests deselected ============================================================================
================================================================== 54 deselected, 3 error in 0.81 seconds ===================================================================```

Is the problem simply due to not having the correct elements in the system path?

**Comment by roryk** [comment]
Hi Daniel,

Yup you're right, to get the tests to work, you'll have to have the anaconda/bin directory in your path. Then they should work.

Hm-- could you have run out of disk space in a temporary directory? I see bcbio is loaded in /mnt-- is that the place with lots of disk space? If you look in the log/bcbio-nextgen-commands.log file you'll see some of the commands that are run are going to a temporary file, is that going to the place where you have all the space?

**Comment by dbrami** [comment]
Hola Rory,
I have the suspicion that I don't really need to have the anaconda/bin in the path and the errors I'm getting (described above) are for other reasons.
I did make certain that I have plenty of disk space and no disk quota on my temp file directories.

- The first thing I think I see going awry is the following common error:
```
    from bcbio.pipeline import config_utils, version
E   ImportError: cannot import name version
```
When looking at the source code, there is no version.py file in the bcbio/pipeline directory
That being said, I'm at loss why the same sort of error is happening with the picardrun module:
```
    from bcbio.broad import picardrun
E   ImportError: cannot import name picardrun
```
as the required file exists in the correct location.

Any ideas?

**Comment by chapmanb** [comment]
Daniel;
Sorry about the test running issues. Could you try using the shell script in the test directory to run the rnaseq tests:
```
./run_tests.sh  rnaseq
```
That tries to correctly setup your paths and use the correct python for running. Hopefully that'll run cleanly and ensure you have everything installed and setup as expected.

**Comment by dbrami** [comment]
Hi guys,
I'm pleasantly surprised that I was right - including the correct version.py file in the pipeline directory allowed for the tests to launch BUT they crashed a little later on.
Here's what I did for a fix (please see what you can do to have a versions.py file in the right place in the master src repository)
```
cp ./anaconda/lib/python2.7/site-packages/bcbio/pipeline/version.py /mnt/bcbio/src/bcbio-nextgen/bcbio/pipeline/
```

I then successfully launched the tests using following command from /mnt/bcbio/src/bcbio-nextgen/tests:
```
[sbsuser@localhost tests]$ nohup ./run_tests.sh rnaseq 1>rnaseq_test_out.txt 2>rnaseq_test_err.txt &
```

Here are my output logs:
[rnaseq_test_err.txt](https://github.com/chapmanb/bcbio-nextgen/files/705495/rnaseq_test_err.txt)
[rnaseq_test_out.txt](https://github.com/chapmanb/bcbio-nextgen/files/705494/rnaseq_test_out.txt)

Please see what you can deduce from these but it now seems like no shocker that my rnaseq validation tests are not completing

**Comment by chapmanb** [comment]
Daniel;
Thanks for the additional testing and outputs, this was a big help for tracking down the issue. There was a new release of bowtie2 (2.3.0) and this appears to be causing the issue; apologies, I had 2.2.8 on my machine and wasn't seeing the issue until updating. There is now a fix in the install to ensure we stick with 2.2.8 until the issues with the newer version get resolved. If you run:
```
bcbio_nextgen.py upgrade --tools
```
it should install the correct version and the tests should hopefully pass cleanly for you.

For the `version.py` issue, that file gets created during installation so there is no reason it needs to be present in the source directory. Having it there shouldn't hurt anything but it also doesn't need to be a required step.

Thanks again for all the help debugging and hope the new version gets things running cleanly for you.

**Comment by dbrami** [comment]
Hi Brian,
Looks like we have a rabbit hole :(
```
#pwd: /mnt/bcbio/
nohup ./tools/bin/bcbio_nextgen.py upgrade --tools 1>std4.out 2>std4.err &
```
Here are the logs for the upgrade that failed:
[std4.out.txt](https://github.com/chapmanb/bcbio-nextgen/files/706392/std4.out.txt)
[std4.err.txt](https://github.com/chapmanb/bcbio-nextgen/files/706393/std4.err.txt)
I'm also attaching the failed fresh install logs:
```
# original command:
wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
# modified for installation under /mnt/bcbio
nohup python ./bcbio_nextgen_install.py /mnt/bcbio --tooldir=/mnt/bcbio/tools \
  --genomes GRCh37 --aligners bwa --aligners bowtie2 1>std.out 2>std.err &
```
here are the renamed output logs
[fresh_install_std.out.txt](https://github.com/chapmanb/bcbio-nextgen/files/706394/fresh_install_std.out.txt)
[fresh_install_std.err.txt](https://github.com/chapmanb/bcbio-nextgen/files/706395/fresh_install_std.err.txt)

Thank you again very much to you and your team and getting this whole solution streamlined and turn-key

**Comment by chapmanb** [comment]
Daniel;
Sorry about the additional issue. It looks like there was a change in the output for the `conda info` output we were parsing, and I pushed a fix to the install to handle this. If you remove the temporarily cached cloudbiolinux (`rm -rf tmpbcbio-install`) and re-run the update command it should hopefully work cleanly this time and get you the right version. Thanks again for the patience debugging this.

**Comment by dbrami** [comment]
Hi Brad,
It finally ran end to end after a fresh install.
Thank you with all the help in getting this run as expected.
Well done.
Daniel

**Comment by dbrami** [comment]
Hi again,
Although the pipeline seemed to have completed, there are still aligner errors in the log.
I'm including them for you to look at them at your leisure and decide wether or not it is significant.
Cheers.
Daniel
[bcbio-nextgen.log.zip](https://github.com/chapmanb/bcbio-nextgen/files/730606/bcbio-nextgen.log.zip)

**Comment by chapmanb** [comment]
Daniel -- thanks much for reporting back, glad to hear everything worked with your analysis. The errors in your log are from previous failed runs since bcbio concatenates to the log files rather than risking over-writing previous logging information. It looks like your last run proceeded without any issues. Thanks again.

**Comment by lpantano** [comment]
Hi @dbrami 

I will close this guessing you got it working. Let us know if you find more issues.

Thanks!
