### ISSUE TITLE
libjli.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1743]
Hi,
When I was running cancer variant calling pipeline, I found the following error for java in the recalibaration. Could you help me to debug it?
Thanks!

[2017-01-12T15:06Z] ica3: 13574T: Assigned coverage as 'regional' with 6.5% genome coverage and 0.0% offtarget coverage
[2017-01-12T15:06Z] ica3: Recalibrating 13574T with GATK
[2017-01-12T15:06Z] ica4: Uncaught exception occurred
Traceback (most recent call last):
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/path/to/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/path/to/bcbio/anaconda/bin:$PATH && /path/to/bcbio/anaconda/bin/gatk -Xms500m -Xmx43680m -XX:+UseSerialGC -Djava.io.tmpdir=/path/to/work/tx/tmpIqDU4R -T BaseRecalibrator -o /path/to/work/align/1049N/tx/tmpNtH5mc/1049N-sort.grp -I /path/to/work/align/1049N/1049N-sort.bam -R /path/to/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --knownSites /path/to/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-147.vcf.gz -L /path/to/work/bedprep/1049N-sort-callable_sample-callableblocks.bed --interval_set_rule INTERSECTION -nct 16 -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
/path/to/bcbio/anaconda/bin/java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
' returned non-zero exit status 127

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. It looks like something is problematic with the java version that bcbio installs but it's not clear what happened. `libjli.so` should be installed with java and linked from the executable. Could you run the following two commands and see what they report:
```
$ bcbio_conda list | grep jdk
java-jdk                  8.0.92                        1    bioconda
$ ldd /usr/local/share/bcbio_nextgen/anaconda/bin/java
        linux-vdso.so.1 =>  (0x00007ffc9cbd4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbd9890e000)
        libjli.so => /usr/local/share/bcbio_nextgen/anaconda/bin/../lib/libjli.so (0x00007fbd986f8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbd984f4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd9812f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbd98b2c000)
```
If you're missing `libjli.so` for some reason, perhaps uninstalling and re-installing java would help:
```
bcbio_conda uninstall java-jdk
bcbio_conda install -c bioconda java-jdk
```
Thanks for working to debug this.

**Comment by pengxiao78** [comment]
Hi Brad,
The libjli.so was missing. I uninstalled and re-installed the java in bcbio-nextgen by following your instruction. Now the pipeline is running well. 
Thank you for your help!

**Comment by chapmanb** [comment]
Glad that fixed the issue, thanks for letting us know the solution. Hope everything else runs cleanly.
