### ISSUE TITLE
vardict: dbSNP annotation turned on despite "effects: false"

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1750]
Since we have a separate pipeline for annotation, we generally turn off annotation in bcbio with "effects: false". When using freebayes, no annotation is performed. Now I am using vardict for the first time and dbSNP annotation is performed.
How can I turn this off in bcbio 1.0.0?

**Comment by chapmanb** [comment]
Ben;
We don't currently have a mechanism to avoid doing the post-calling dbSNP annotation of VarDict right now. `effects: false` only impacts effects based predictions (snpEff, VEP). FreeBayes doesn't do this separately since it assigns dbSNP IDs during the calling process. Is there a reason you need to turn it off? It should be a quick process and we generally try to limit on/off options if we can. Happy to consider it if it's causing problems with your analysis.

**Comment by gabeng** [comment]
Brad,
after looking into the log files more dilligently, I can see that you are right: the overhead is small. Thanks for clarifying that freebayes also does this (opaquely). 
I would generally recommend to cleanly separate the steps of variant calling and annotation. For us it just inflates files with data that we later have to remove anyhow. But this is no reason to add more options. Thanks for your comment.

**Comment by gabeng** [comment]
I must correct myself. I had previously configured both freebayes and vardict to run and therefore it was a little difficult to determine from the logs which step took longest. It seems that for very small data sets (single gene panels) there is some huge overhead in `bcftools annotate`. It cannot be the size of the vcf files, they are tiny. I will try to replace the dbSNP file with a one-line VCF in the next run. `bcftools annotate` is also orders of magnitute slower in these instances than vardict itself. Is there a specific reason why `bcftools annotate` is called here?

**Comment by gabeng** [comment]
My short test showed: with a small dbSNP vcf file I am down to seconds per sample from more than 10min wall clock time.

**Comment by mjafin** [comment]
I wonder if the dbSNP file you're using is bgzipped and indexed?

**Comment by gabeng** [comment]
It is both bgzipped and indexed. Otherwise `bcftools` would complain.

**Comment by chapmanb** [comment]
Ben -- how are you timing the `bcftools annotate` command? Separately from bcbio or through timestamps? It should be pretty quick and take only a fraction of the time the VarDict variant calling takes. Only looking at timestamps can be confusing since the annotation occurs right after VarDict so if you have concurrent VarDict commands running it may be waiting on another to finish rather than waiting for the annotation. If you run the short test outside of bcbio is it still taking 10 minutes?

**Comment by gabeng** [comment]
Just did a short test outside bcbio (but using the tools from bcbio):
```
time bcftools annotate -c ID -a /home/ubuntu/local/share/bcbio/genomes/Hsapiens/hg19/variation/dbsnp-147.vcf.gz XXX-S1_L001_R1_001-vardict.vcf.gz -O z -o XXX-S1_L001_R1_001-vardict.vcf_annotated.gz

real    22m27.799s
user    5m16.620s
sys     0m1.164s
```
The vcf file was generated using bcbio and contains only 7 variants. The command above ran on an EC2 m4.2xlarge with a gp2 EBS volume (on a single core, of course). It seems that IOPS is the limit. 
In the bcbio workflow the command is executed several times per sample on previously split vcf files. Once I cut down the dbsnp-147.vcf.gz to a few lines, the entre variant calling process completes within seconds. It appears that this does not scale well with the size of the annotation file.

**Comment by chapmanb** [comment]
Ben -- thanks so much for debugging this further. Apologies, I hadn't benchmarked how slow the bcftools annotate lookup was with these larger files. I swapped out that approach with one based on vcfanno for the lookup and bcftools for the ID annotation, and this is much faster. It runs in ~1 second on my tests, so shouldn't impact your pipeline runs much even if you're not using the annotations downstream. Thank you again for working on this and please let us know if you run into any other problems.

**Comment by gabeng** [comment]
Brad, it is fun to watch how quickly bcbio improves. Great work! Thanks for the fix.

**Comment by audyavar** [comment]
I am having the same issue. I turned the variant annotation off by "effects: false", but my pipeline is still running it and stopping at the variant effects and gives me error message "ValueError: Unexpected variant effects configuration: [False]". What am I doing wrong here? I don't want to waste time in variant annotation as I am using a different package for doing it.

**Comment by chapmanb** [comment]
Sorry about the issue. Would it be possible to share your configuration? I'm not able to reproduce this unless I specify effects as a list:
```
effects:[false]
```
rather than `effects: false`. Is it possible it accidentally got specified that way in the configuration? Thanks for the help debugging.
