### ISSUE TITLE
STAR junction file error

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1755]
Hello @roryk and @chapmanb, I am seeing a weird new error with RNA-Seq workflow on GRCh37+mm10 (disambiguated), STAR and oncofuse and was I hoping one of you could help me.

I get:
```python
File "/bcbio/lib/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 122
, in generate_transcript_counts
    oncofuse_file = oncofuse.run(data)
  File "/bcbio/lib/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/oncofuse.py", line 31,
 in run
    input_file = _fix_star_junction_output(input_file)
  File "/bcbio/lib/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/oncofuse.py", line 118
, in _fix_star_junction_output
    with open(chimeric_out_junction_file, "r") as in_handle:
IOError: [Errno 2] No such file or directory: '/WORKDIR/align/SAMPLE/GRCh37/6_sampleChimeric.out.junction'
```

Indeed, the junction file is called differently in the working directory: `Chimeric.out.junction.hg19` (note that I aligned to GRCh37), which results from the code line `out_file = chimeric_out_junction_file + ".hg19` in ` rnaseq.oncofuse._fix_star_junction_output()`. Strangely, the same workflow went through two weeks ago; where there any changes to the RNA-Seq workflow or junction disambiguation which may have caused this?

**Comment by schelhorn** [comment]
Also, the junction file is empty.

**Comment by schelhorn** [comment]
Okay, only 10% of my samples in the current run are affected by this error, the rest went through just fine. I'll check if a realignment of the problematic samples solves the issues.

**Comment by schelhorn** [comment]
Problem was resolved by deleting and regenerating all alignment files pertaining to the affected samples. Issue doesn't seem to be immediately reproducible. Closing for now.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for reporting and following up. If you find the issue is reproducible going forward we can definitely investigate.
