### ISSUE TITLE
VarDict update request

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1768]
I noted (working on another issue) that even the bcbio dev branch still links to an older version of vardict (vardict,2016.02.19). Modifications were made in March which would be very helpful (the `-A` option in `var2vcf_valid.pl`.
Currently, if there are two valid het calls at one position, one of the calls is filtered out. I still have to verify on my data, but you may want to consider this option for the standard workflow.

**Comment by chapmanb** [comment]
Ben -- thanks again for this. I updated bcbio so it'll now install the latest vardict perl and supplemental scripts. Definitely let us know if you think tweaking any parameters help with sensitivity/specificity in your evaluations and we can explore more.

**Comment by gabeng** [comment]
Brad, thanks for catching this so quickly. I will check if the parameter tweaking will lead to the desired result on my limited data set. I will let you know so that you can check against your gold standard data.
