### ISSUE TITLE
Germline vcf files

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1774]
Hi Brad,
I just finished the somatic pipeline for tumor-normal pairs using the most recent bcbio development version but found that the germline vcf files are not available for each variant caller, which are very important for our research. Is there anyway to retrieve them in the work folder. 
Thanks.

**Comment by chapmanb** [comment]
Germline calling in somatic samples has been re-written to do separate calling on the normal sample of the tumor/normal pair, so should be much more accurate than the previous implementation which tried to extract these from the somatic calls. It also now allows selection of multiple germline callers and the documentation on enabling it is here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#somatic-with-germline-variants

Hope this helps provide what you need for re-enabling these in your workflows.

**Comment by pengxiao78** [comment]
Since the running has been finished, is it possible to add the germline variant request back to the yaml file to retrieve the germline part without hadicapping or running the completed somatic results? Please give me a detailed instruction for this retrieval. Thanks!

**Comment by chapmanb** [comment]
Absolutely. Edit the YAML file to have the new germline configuration, keeping the somatic callers you had previous under somatic. Then `rm checkpoints_parallel/*.done` to re-enable parallelization on the project and re-run from the same directory. It should do germline calling on the samples and make those available alongside the previous run somatic samples. Hope this helps.
