### ISSUE TITLE
add datatarget flag for vcfanno

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1778]
Hi Brad

I feel like there should be a separate flag for the vcfanno and gemini files. Currently, if someone wants to use the vcfanno/vcf2db functionality, you need to add `--datatarget gemini` which downloads loads of gemini annotations based on GRCh37, which are useless on hg38. Hence the need for a separate download flag/or a check for which builds reference data is needed.

Thanks
M

**Comment by chapmanb** [comment]
Matthias -- good catch, thank you. I pushed a fix to the latest development version to only install the GEMINI data for build 37 if hg19/GRCh37 is in the specified genomes so it should avoid the extra downloads if you're only using hg38. Thanks again.
