### ISSUE TITLE
Gemini is not working after the latest update

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1781]
Hello!

I have been working with GEMINI from bcbio installation a lot, and everything was fine.
After the latest update (yesterday), I see in
/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py,
function load_clinvar:
```
diseases = [x.decode('utf8', 'ignore').encode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
```
while in the gemini github the enconding is different:
https://github.com/arq5x/gemini/blob/master/gemini/gemini_load_chunk.py
```
 #diseases = [x.decode('utf8', 'ignore').encode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
diseases = [x.encode('ascii', 'ignore').decode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
```

When running 
```
gemini load --passonly --skip-gerp-bp -v $vcf -t VEP --cores 16 --tempdir . $bname.db
```
with bcbio's new version, it throws an error:
```
File "/home/naumenko/work/tools/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 72, in load_clinvar
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 8: ordinal not in range(128)
    diseases = [x.decode('utf8', 'ignore').encode('ascii', 'ignore') for x in info.get('CLNDBN').split("|") if not x in (".", "not_specified", "not_provided")]
```

In the meanwhile I have fixed the code according to GEMINI github, and it works.

Could you please fix the problem for other users?

Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey -- thanks for the heads up on the issue. @brentp, would it be possible to roll a new 0.19.2 point release? I could also just update the bioconda package from the latest GitHub development, whatever works better for you.

**Comment by brentp** [comment]
@chapmanb probably best to just do a bioconda package from github as Aaron is still controlling the release stuff and we're both swamped this week. 
Sergey, thanks for figuring that out and glad we've already addressed it in github repo.

**Comment by chapmanb** [comment]
Thanks again for the report on this. To fix entirely I had to update both the gemini and cyvcf2 bioconda packages to the latest development versions and it now seems to work cleanly. If you run:
```
bcbio_nextgen.py upgrade --tools
```
you should get the latest versions that now work correctly. Please let us know if you run into any other problems at all.

**Comment by naumenko-sa** [comment]
Thanks Brad, it works.
