### ISSUE TITLE
Tools and Detailed description for Low complexity region filtering process for SNP pipeline?

### ISSUE THREAD

**Issue by hyong2000** [chapmanb/bcbio-nextgen#1785]
Could you provide the list of tools and the description for removing Low complexity region (LCR) of mutation calling pipeline? I was looking for some description on the document, but I couldn't find it. Thanks!

**Comment by chapmanb** [comment]
Taehyong -- thanks for the questions. We have a post with full details about the optional low complexity region removal and how it influences indel validations:

http://bcb.io/2014/05/12/wgs-trio-variant-evaluation/

This includes links to Heng Li's paper and BED files used in bcbio. Hope this helps.
