### ISSUE TITLE
Alignment parameters

### ISSUE THREAD

**Issue by lindakohn** [chapmanb/bcbio-nextgen#1787]
Hi,

I'm curious to know what arguments are specified and how they are set for alignment with bwa mem in the cancer variant calling pipeline and STAR in the RNA-seq pipeline?

Thanks
Linda

**Comment by schelhorn** [comment]
It's in the code ;)

**Comment by chapmanb** [comment]
Linda;
Sven-Eric is right, although I can expand a bit. In general the best way to examine these is to look at the generated command lines in `log/bcbio-nextgen-commands.log` and if you want to dig further look at the aligner implementations:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/bwa.py
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/star.py

If you have specific questions about anything happy to help answer those. Hope this helps.

**Comment by lpantano** [comment]
Hi @lindakohn 

I will close this guessing you got all the information. Let us know if you find more issues.

Thanks!
