### ISSUE TITLE
goleft indexcov returns error: expected 2 sex chr, found: 1

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1793]
This seems to be new in the current development version. This config ran through with the same data without errors about a week ago. I did not indicate gender in my sample config.

```
/home/ubuntu/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py in _do_run(cmd='set -o pipefail; goleft indexcov --directory /bi...3_L001_R1_001/L-_S73_L001_R1_001-ready.bam', checks=None, log_stdout=False, env=None)
     97                 error_msg = " ".join(cmd) if not isinstance(cmd, basestring) else cmd
     98                 error_msg += "\n"
     99                 error_msg += "".join(debug_stdout)
    100                 s.communicate()
    101                 s.stdout.close()
--> 102                 raise subprocess.CalledProcessError(exitcode, error_msg)
        exitcode = 1
        error_msg = 'set -o pipefail; goleft indexcov --directory /bi...3 indexcov: expected 2 sex chromosomes, found: 1\n'
    103             else:
    104                 break
    105     s.communicate()
    106     s.stdout.close()

CalledProcessError: Command 'set -o pipefail; goleft indexcov --directory /bioinf-data/10123-eval-testrun-5/work/bcbiotx/tmp4Ox37z/L-_S73_L001_R1_001 --sex chrX,chrY -- /bioinf-data/10123-eval-testrun-5/work/prealign/L-_S73_L001_R1_001/L-_S73_L001_R1_001-ready.bam
2017/01/27 16:44:02 indexcov: running on 1 indexes
2017/01/27 16:44:03 indexcov: expected 2 sex chromosomes, found: 1
' returned non-zero exit status 1

```

**Comment by chapmanb** [comment]
Ben;
Sorry about the issues, the goleft indexcov code is new in development. We're working on using it to get global coverage plots into MultiQC output. Is it possible you have an older version of goleft, you should have 0.1.12 if you run:
```
goleft
```
without any parameters. The way you specified sex chromosomes to indexcov changed in a very recent version. If you're out of date, a `bcbio_conda install -c bioconda goleft` should get the latest version. Hope this helps fix the problem.

**Comment by deber1980** [comment]
I'm getting the same error even though goleft version is indeed 0.1.12

**Comment by chapmanb** [comment]
Thanks for confirming the issue and checking on the version. As a temporary workaround, I turned off the gender specification to `goleft indexcov` to avoid the problem.

@brentp, do you know what we're doing wrong with the `--sex chrX,chrY` specification to `goleft indexcov`. Happy to adjust to do the right thing from bcbio.

**Comment by brentp** [comment]
maybe try: `--sex "chrX,chrY"` ?
If that doesn't work, I'll have a look.
what does the output show?

**Comment by chapmanb** [comment]
@deber1980 or @gabeng -- would it be possible to try the quoted command on one of the goleft indexcov commands that is failing for you? I haven't yet been able to reproduce this so appreciate you helping with debugging.

**Comment by brentp** [comment]
yes, and if you can recreate, please let me know. indexcov is stabilizing, but might have issues I haven't seen. For example if your bams have no reads on chrX and chrY.

This error: `2017/01/27 16:44:03 indexcov: expected 2 sex chromosomes, found: 1`
indicates that something is wrong there. 

This shouldn't cause goleft to abort, so if you can share the bam index and the bam header (no reads needed) then I can debug and fix.

**Comment by deber1980** [comment]
This is the output for running it.
These are very small panels so it makes sense that the bam won't have reads on some of the chromosomes.
I'll check the anonymize and see if I can send it.
Thanks

> root@31af9b775830:/# goleft indexcov --directory /mnt/work/bcbiotx/tmp08H0wt/my_sample  -- /mnt/work/align/my_sample/my_sample-sort.bam 
2017/01/31 07:50:51 indexcov: running on 1 indexes
2017/01/31 07:50:52 indexcov: found chromosome "chrX", wanted "X" please use exact chromosome names for --sex.
2017/01/31 07:50:52 indexcov: found chromosome "chrY", wanted "Y" please use exact chromosome names for --sex.
2017/01/31 07:50:52 indexcov: expected 2 sex chromosomes, found: 0
root@31af9b775830:/# goleft indexcov --directory /mnt/work/bcbiotx/tmp08H0wt/my_sample --sex "chrX,chrY"  -- /mnt/work/align/my_sample/my_sample-sort.bam 
2017/01/31 07:50:58 indexcov: running on 1 indexes
2017/01/31 07:50:59 indexcov: expected 2 sex chromosomes, found: 1

**Comment by deber1980** [comment]
[sample_name_0001.bam.zip](https://github.com/chapmanb/bcbio-nextgen/files/741386/sample_name_0001.bam.zip)

**Comment by brentp** [comment]
can you include the .bai in the zip file?

**Comment by deber1980** [comment]
[Archive.zip](https://github.com/chapmanb/bcbio-nextgen/files/742863/Archive.zip)

**Comment by brentp** [comment]
thanks for the test-case I'll make this work better in next release.

@chapmanb indexcov is really only useful for WGS, if you can detect targetted projects and not run indexcov for those it would probably avoid some confusion

**Comment by chapmanb** [comment]
Brent -- thank so much for looking at the underlying issue. I pushed a fix to skip running indexcov except for whole genome samples so this will hopefully practically fix the problem for anyone having this issue. Thanks again for the reports and help debugging.
