### ISSUE TITLE
metasv (spades) parallelization ?

### ISSUE THREAD

**Issue by PatrickJReed** [chapmanb/bcbio-nextgen#1794]
Are there config changes that can be made so metasv utilizes more available resources?  Currently, it seems to only be using 1-2 cores and a small fraction of memory on a single sample.

Cheers,

**Comment by chapmanb** [comment]
Patrick;
Within bcbio we're passing the `--num_threads` option to MetaSV so it should hopefully be able to use as many cores as available on a single machine in your cluster. Are you seeing `--num_threads` in `log/bcbio-nextgen-commands.log` set to the expected number? If so and metasv is still under utilitizing resources it might be worth asking on the metasv issue tracker if there are approaches we could take to better parallelize.

Practically we haven't done a lot of work recently on metasv and have been focusing on a prioritization based approach and hopefully some future methods to recall with multiple callers. This thread has more context and discussion:

https://github.com/chapmanb/bcbio-nextgen/issues/1729#issuecomment-271988200

Hope this helps.

**Comment by PatrickJReed** [comment]
I just checked the log file, looks like metasv was only called with 1 thread.

[2017-01-20T16:43Z] /usr/local/share/bcbio/anaconda/bin/python /usr/local/share/bcbio/anaconda/bin/run_metasv.py --sample 3_SZ_Fibro --reference /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --bam /efs/SZ_WGS_Meta-merged/work/align/3_SZ_Fibro/3_SZ_Fibro-sort.bam --outdir /efs/SZ_WGS_Meta-merged/work/structural/3_SZ_Fibro/metasv --cnvkit_vcf /efs/SZ_WGS_Meta-merged/work/structural/3_SZ_Fibro/cnvkit/raw/3_SZ_Fibro-sort-call-effects.vcf --manta_vcf /efs/SZ_WGS_Meta-merged/work/structural/3_SZ_Fibro/manta/somaticSV-3_SZ_Fibro-effects.vcf.gz --wham_vcf /efs/SZ_WGS_Meta-merged/work/structural/3_SZ_Fibro/wham/3_SZ_Fibro-wham-3_SZ_Fibro-effects.vcf.gz --workdir /efs/SZ_WGS_Meta-merged/work/structural/3_SZ_Fibro/metasv/raw --num_threads 1 --spades /usr/local/bin/spades.py --age /usr/local/bin/age_align --assembly_max_tools=1 --assembly_pad=500 --boost_sc --isize_mean 240.661027407 --isize_sd 92.1300424798

**Comment by chapmanb** [comment]
Patrick;
Thanks for helping dig more into this. How are you calling and parallelizing bcbio? Are other steps in the pipeline using multiple cores during your run? If you're able to provide more details we can hopefully figure out why bcbio only thinks it has one core to use at this point in the analysis.

**Comment by PatrickJReed** [comment]
Hi Brad,

I have bcbio development version installed on a m4.4xlarge amazon instance running ubuntu 14.04.  bcbio and reference files are installed locally, sequence data and working directory are on a mounted efs.

Everything up to this point has done a great job of optimizing the available 16/64.  

here is the gist of my config file:
details:
- algorithm:
    adapters:
    - truseq
    - illumina
    align_split_size: 5000000
    aligner: bwa
    effects: vep
    mark_duplicates: true
    realign: false
    recalibrate: false
    remove_lcr: true
    save_diskspace: true
    tools_on:
    - bwa-mem
    svcaller:
    - manta
    - cnvkit
    - metasv
    - wham
    svvalidate:
      DEL: /home/ubuntu/giab-svclassify-deletions-2015-05-22.bed
      INS: /home/ubuntu/giab-svclassify-insertions-2015-05-22.bed
  analysis: variant2
  description: 1_NT_Blood
  files:
  - /efs/merged/1_NT_Blood_R1.fastq.gz
  - /efs/merged/1_NT_Blood_R2.fastq.gz
  genome_build: GRCh37
  metadata:
    batch: T1B
    description: null
    phenotype: normal

and my system config file:
galaxy_config: universe_wsgi.ini
resources:
  default:
    cores: 16
    jvm_opts:
    - -Xms750m
    - -Xmx3500m
    memory: 3G
  dexseq:
    memory: 10g
  express:
    memory: 8g
  gatk:
    dir: /usr/local/share/bcbio/toolplus/gatk/3.6-0-g89b7209
    jvm_opts:
    - -Xms500m
    - -Xmx3500m
  macs2:
    memory: 8g
  qualimap:
    memory: 4g
  seqcluster:
    memory: 8g
  snpeff:
    jvm_opts:
    - -Xms750m
    - -Xmx4g

I attached part of the debug log where metasv starts.  let me know what other info may help.
cheers
[log_out.txt](https://github.com/chapmanb/bcbio-nextgen/files/739588/log_out.txt)

**Comment by chapmanb** [comment]
Patrick;
Thanks much for following up with all these details. I believe the issue is that you're re-running in a previously finished directory so bcbio is not parallelizing jobs. You can either update to the latest development version, which no longer does this for local multicore jobs:
```
bcbio_nextgen.py upgrade -u development
```
or remove the checkpoint file 
```
rm checkpoints_parallel/multicore2.done
```
and then re-run. Hopefully this will result in proper parallelization for MetaSV. If you're still running into issues please re-open and we can investigate more.

**Comment by PatrickJReed** [comment]
Thanks. This brings up a question I've been meaning to ask, what is the best way to add additional analysis to one that has completed?  In this case, I wanted to try metasv and had already ran other sv callers?

**Comment by chapmanb** [comment]
Patrick;
You can edit the configuration with additional callers and run in the same directory, so the way you're doing it works. We use the `checkpoints_parallel` steps to try and define what already finished and avoid doing extra steps like spinning up clusters on parallel grid systems. As I mentioned we also restricted cores on local runs when this was present but no longer do this in the latest development.

So the short answer is: you're doing it right but either need to remove checkpoints_parallel or use the latest development. Hope this helps.
