### ISSUE TITLE
Difficulties installing sacCer3 (yeast) RNA-Seq resources

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#1796]
Hi there - 

  I'm trying to analyze some yeast RNA-Seq data. I tried updgrading my bcbio install like so:

```
bcbio_nextgen.py upgrade --datatarget rnaseq --genomes sacCer
```

  During the install process, I get lots of error messages like:

```
[localhost] local: wget --continue --no-check-certificate -O sacCer3-seq.tar.xz 'https://s3.amazonaws.com/biodata/genomes/sacCer3-seq.tar.xz'
--2017-01-27 17:07:40--  https://s3.amazonaws.com/biodata/genomes/sacCer3-seq.tar.xz
Resolving s3.amazonaws.com... 54.231.40.114
Connecting to s3.amazonaws.com|54.231.40.114|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-27 17:07:40 ERROR 404: Not Found.
```

The genome and transcriptome indexes all eventually build correctly (I think), but the RNA-Seq references described in [sacCer3=resources.yaml](https://github.com/chapmanb/bcbio-nextgen/blob/d08d661f15275e84974b0d064301c9efaa81ed1f/config/genomes/sacCer3-resources.yaml) don't seem to exist in my install directory:

```
$ bcbio/genomes/Scerevisiae/sacCer3/> ls -1
bowtie2
bwa
rtg
seq
seq_prep
snap
snpeff
star
vep
```

Any thoughts on what might be happening? Alternately, is there another spot I can grab the transcript reference files from? Thanks!

**Comment by rdocking** [comment]
Note - I've worked around this issue for now by downloading the yeast genes in GTF format and setting up a custom genome:

```
> bcbio_setup_genome.py --cores 8 --fasta genomes/Scerevisiae/sacCer3/seq/sacCer3.fa \
 --gtf sacCer3_sgd_genes.gtf --name Scerevisiae \
 --build sacCer3_override --indexes star
```

**Comment by roryk** [comment]
Hi @rdocking,

Thanks-- you nailed it, we don't have the transcriptome set up for yeast out of the box and your workaround is what we'd do to make it.

**Comment by rdocking** [comment]
Hi @roryk - thanks for your response. Please feel free to close this issue if you'd like - it looks like my yeast RNA-Seq runs are going well.
