### ISSUE TITLE
bcbio_vm data dir location

### ISSUE THREAD

**Issue by deber1980** [chapmanb/bcbio-nextgen#1797]
Hello,

I'm using bcbio_vm - starting a new instance (machine), deploying bcbio_vm with docker image on it and run the analysis.
The Docker image doesn't contain the data files (which is great to reduce the size of the image), however, each time I run an analysis there is a part where all the data is being downloaded to the host machine, under the "work" directory. 

What would be the best way to:
(1) Download the relevant data just once to the host machine and specify the location
(2) Pass the location of the data dir when calling bcbio_vm
?

I am familiar with what is described here https://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html but I don't really understand how to do this for bcbio_vm

Thanks,
Y.

**Comment by chapmanb** [comment]
For bcbio-vm, there is a separate download command for data, similar to the bcbio approach:
```
bcbio_vm.py --datadir=~/install/bcbio-vm/data install --data --tools \
  --genomes GRCh37 --aligners bwa
```
That's documented in the bcbio-vm README with more details:

https://github.com/chapmanb/bcbio-nextgen-vm#installation

If you're running on AWS, we've also been doing a lot of work on an automated approach for single machine analyses that uses bcbio without the Docker components:

https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible

There are still some rough cases for Docker around re-running analyses so using a standard bcbio installation can have some advantages in terms of updates and running. Hope this helps.

**Comment by deber1980** [comment]
Thanks Brad. I'll check it out

**Comment by lpantano** [comment]
Hi @deber1980 

I will close this guessing you got it working. Let us know if you find more issues.

Thanks!
