### ISSUE TITLE
Description of qc and alignment pipelines for publication

### ISSUE THREAD

**Issue by eyalbenda** [chapmanb/bcbio-nextgen#1800]
Hi,

I'm preparing a manuscript in which I used bcbio. I'm trying to get for the methods all the pipeline steps (from version 0.9.9) of the qc and alignment. Is it described anywhere? Is it part of bcbio output?

Thanks,

Eyal

**Comment by chapmanb** [comment]
Eyal;
Congrats on getting to the manuscript writing stage, we're always happy to hear when bcbio helped in a project. The bcbio run and final directory have a log of all commands run in the file `bcbio-nextgen-commands.log` which will give you all the details on command lines and flags and programs. Hopefully that provides what you need, please let us know if you have any specific questions and happy to improve the documentation about them.

**Comment by lpantano** [comment]
Hi @eyalbenda 

I am closing this because it seems solved, please feel free to open an issue if you find again the problem.

thanks!
