### ISSUE TITLE
Docs: add why which step is taken

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1801]
Hi Brad, 

We're trying to put together some documentation on bcbio for our clinical validation and accreditation.
Would it be possible to expand to the documentation with:
- A list of (general) steps taken
- The reasoning behind each step

I'd be happy to share to docs we put together afterward, but I'm going to need some more info.
For example, the goleft calculates a bed file with depths/variant regions. This takes quite some compute time, but for the life of me, I don't know where those results are used. I'm sure a lot of users would benefit from a somewhat more verbose explanation of each step.

Could you help me out?
Thanks
M

**Comment by ohofmann** [comment]
We are going through the accreditation process as well and probably need a similar level of detail. Happy to help with this. The list of tools and databases associated with the template/config might serve as a starting point, along with the general phases (what bcbio reports under `Timing:` in the logs). Can put this together in a Google Doc and take it from there.

@matthdsm -- is this for germline, somatic? Panels, exomes, WGS?

**Comment by matthdsm** [comment]
Hi Oliver,

Currently we're going for exomes, but if the evaluations from the medical staff are ok, we will include panels and WGS, both germline and somatic. A thorough explanation of the exome pipeline is now the most important to us, since we're having our accreditation in the latter half of the year.

Thank you for your input!
M

**Comment by chapmanb** [comment]
Matthias and Oliver;
Thanks much for the discussion. We're definitely happy to have better docs for steps of the process. I hope that most of the standard steps like alignment, variant calling and QC are relatively well documented and understood. For callable regions I added details about the usage and linked to the previous blog post describing how this feeds into parallelization of the process:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/internals.html#parallel

It would be great to link to the type of documentation you need for produce for accreditation. If there are other areas that could use additional detail please let us know. Thanks again.
