### ISSUE TITLE
bcbio merging multiple files per sample 

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#1802]
Hi Brad,

Previously, I used the way in the following link to merge multiple files per sample. 
http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#multiple-files-per-sample

Our fastq files have the same file names in different folders (duplicates in different dates). Previously, when I provide the samplename with directory following the file name such as
samplename                        description        batch       phenotype
/A/1T_L1_R1_001.fastq.gz      1T                       1            tumor
/B/1T_L1_R1_001.fastq.gz      1T                       1            tumor

The bcbio_prepare_samples.py will automatically recognize them and merge them into 1T_R1.fastq.gz. 

However, when I ran the same command in the recently updated 1.0.1 stable bcbio version 
bcbio_prepare_samples.py --out merged --csv file.csv

The bcbio just showed the following errors
/A/1T_L1_R1_001.fastq.gz and /B/1T_L1_R1_001.fastq.gz have the same stem, so we don't know how to assign it to the sample data in the CSV. To get around this you can rename one of the files. If they are meant to be the same sample run in two lanes, combine them first with the bcbio_prepare_samples.py script.(http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#multiple-files-per-sample)

Could you please give the previous merging function back? Otherwise, I will do further effort to change the file name before merging.

Thank you!

**Comment by lpantano** [comment]
Hi @pengxiao78,

sorry about that. It seems we updated the function that recognized paired samples but this function is used when running bcbio_prepare_samples.py. I would try to work around this and come back to you.

thanks

**Comment by lpantano** [comment]
Hi,

can you update and check? please, read the commit, it has limitation. I couldn't figure out another way to fix it right now. I have no idea how this worked in the past. 

Cheers

**Comment by pengxiao78** [comment]
Hi Brad,

I did merge several hundred pairs with bcbio_prepare_samples.py  for the same file names in different folders since 2015 when I started to use bcbio,  even I was okay in last week before I update the bcbio into 1.0.1. I never need to change any file names. Could you help me to figure out the problem? 

Thanks!

I can give you masked example of part of my previous csv file (with same file names in different folder names) that has been successfully merged into

100T_R1.fastq.gz
100T_R2.fastq.gz
100N_R1.fastq.gz
100N_R1.fastq.gz


samplename,description,batch,phenotype,sex
/path/to/input/33-34/D55-265/100T_S34_L006_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L006_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L008_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L008_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L002_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L007_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L007_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L003_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L004_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L001_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L001_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L005_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L002_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L004_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L005_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-265/100T_S34_L003_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L006_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L006_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L008_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L008_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L002_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L007_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L007_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L003_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L004_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L001_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L001_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L005_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L002_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L004_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L005_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D55-963/100T_S34_L003_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/33-34/D54-311/100N_S5_L008_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L004_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L003_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L006_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L005_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L007_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L002_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L001_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L006_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L008_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L005_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L003_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L002_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L004_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L001_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-311/100N_S5_L007_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L008_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L004_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L003_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L006_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L005_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L007_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L002_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L001_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L006_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L008_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L005_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L003_R1_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L002_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L004_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L001_R2_001.fastq.gz,100N,100,normal,female
/path/to/input/33-34/D54-151/100N_S5_L007_R2_001.fastq.gz,100N,100,normal,female

**Comment by lpantano** [comment]
Hi @pengxiao78 

the last development code in bcbio should work.
Can you update to development, and try again, and then let me know what happens?

thanks

**Comment by pengxiao78** [comment]
You mean the latest development version? Thanks.

**Comment by lpantano** [comment]
yes!

**Comment by pengxiao78** [comment]
Yes, it works now! Thank you!

**Comment by pengxiao78** [comment]
Hi Brad,
This problem comes back again. I don't know if it is warning or error. Before run the merge, I found the following statement

100T_S56_L003_R2_001.fastq.gz stem is multiple times in your file list, so we don't know how to assign it to the sample data in the CSV. We are gonna use full path to make a difference, that means paired files should be in the same folder. If this is a problem, you should rename the files you want to merge. Sorry, no possible magic here.

When I typed bcbio_nextgen.py -v
It showed 1.0.2a0

As the previous mentioned, the problem of the same names in different folder problem has been solved. Since I updated the bcbio again recently, the function disappeared again?  I just repeated our data structure as follows again. Within each batch, the file names are unique and different also paired. But between the two batches the files names are the same. Previously, once I provided the full path, the software could automatically merge all the R1 files into single R1 file and all the R2 files into single R2 file as follows. 

Merged files

100T_R1.fastq.gz
100T_R2.fastq.gz

from the following CSV
samplename,description,batch,phenotype,sex
/path/to/input/batch1/100T_S34_L001_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch1/100T_S34_L001_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch1/100T_S34_L002_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch1/100T_S34_L002_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch2/100T_S34_L001_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch2/100T_S34_L001_R2_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch2/100T_S34_L002_R1_001.fastq.gz,100T,100,tumor,female
/path/to/input/batch2/100T_S34_L002_R2_001.fastq.gz,100T,100,tumor,female

Could you update bcbio_prepare_samples.py with the original function to recognize and merge the same name files in different folders? Otherwise, we need to generate a script to change the original file names every time when we receive the data.

Thanks!

**Comment by lpantano** [comment]
Hi @pengxiao78 

Are you getting the final files though?

That is a warning just to tell you the limitations.

You can check the size of the final files and see if they match the sum of the individuals for instance.

I will re-write the message to make clear is a warning.

Let me know if you final files have not the expected size. You can look (and post here) the content of logs/*commands.log file. That one will tell you if all files were used for merging.

Cheers

**Comment by pengxiao78** [comment]
Yes, that was just warning but the commands and file sizes are correct. Thanks!
