### ISSUE TITLE
How to skip QC file creation when re-doing variant calling? 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1807]
Hi Brad, 

We want to accumulate the QC files of the increasing cohorts of samples that we sequence. 

We re-variant call all samples when our cohorts expands (we get new samples) to get a square genotype table over all samples. 

This leads to fastqc and samtools stats being run for samples for which we already have fastq and samtools stats files. 

Is there a way to skip fastq, samtools and bcftools stats/QC file creation?

For example by specifying the QC steps to skip in the input fastq/bam bcbio sample table? We also would like to skip bcftools stats always because for large VCF files  (100M+ variants * few 100 samples) that takes way to much time. 

Another option would be to check a directory for if the sample QC files already exist. 
But specifying which QC steps to run / skip in the input sample table is more robust (does not depend on actual storage used for the accumulation of the QC files). 

Thank you. 

Neill

**Comment by chapmanb** [comment]
Neill;
Thanks for the discussion on this. I'll follow up with more details in #1808 since these are linked and I hope we have a dirty copy solution that will work relatively well.

**Comment by NeillGibson** [comment]
Yes sure. I wasn't sure if this was handled best as 1 or 2 separate issues.
