### ISSUE TITLE
Bogus memory request on runs on a clulster

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1811]
```
[2017-02-09T15:14Z] mn-00: Resource requests: bwa, sambamba, samtools; memory: 1.00, 1.00, 1.00; cores: 8, 8, 8
[2017-02-09T15:14Z] mn-00: Configuring 3 jobs to run, using 1 cores each with -0.0990234375g of memory reserved for each job
```

This is a VM cluster of 27 nodes with 32G RAM and 8 virtual CPUs each.

In SLURM they're configured as (example):

```
NodeName=mn-0[0-9] CPUs=8 State=UNKNOWN RealMemory=32000
```

It doesn't matter what I set on `bcbio_system.yaml`, I still get that bogus memory request.

**Comment by chapmanb** [comment]
Luca;
Thanks for the report, it sounds like bcbio is not properly detecting the memory and machines on your cluster. If you run:
```
sinfo -h -p queuename --format '%c %m %D'
```
what does it report? Looking at `provenance/system-ipython-queuename.yaml` should also provide some insight into what bcbio sees for expected memory/cpu usage on the cluster. It would be great if we could detect this automatically but if something is off about the configuration and can't be changed you can also defined core/memory usage automatically to skip the check:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#determining-available-cores-and-memory-per-machine

Hope this helps.

**Comment by lbeltrame** [comment]
```sinfo -h -p analysis --format '%c %m %D'
8 32000 28```
```
and
```
cat provenance/system-ipython-analysis.yaml 
- cores: 8
  memory: 0.0009765625
  name: slurm_machine
```

**Comment by chapmanb** [comment]
Luca;
Thanks for the additional details. I'm confused as to what is going on here, it looks like sinfo is reporting the right thing but I can'f figure out from reading the code why it ends up with that bogus memory specification in the output. Would you be able to manually add some debugging lines to the function that calculates it:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/provenance/system.py#L61

on your install and see if you can identify the point where the `mem` specification gets problematic? Thanks for the help debugging this.

**Comment by lbeltrame** [comment]
One question, which perhaps may shed light on the problem: is the `system-ipython-analysis.yaml` file regenerated on each run, or once present it stays there?

**Comment by chapmanb** [comment]
It is not regenerated each run. bcbio will use it if present and only query slurm if missing. If you changed the configuration at some point you could remove this to try re-creating it. Hope that explains it.

**Comment by lbeltrame** [comment]
Ok, then this report is invalid. The reason is that I did not specify `RealMemory` at first in `slurm.conf` and therefore it  couldn't find any nodes with the right RAM (but it triggered another bug, which I will open later). I then made the change, but the file stayed, therefore causing these bogus errors.
