### ISSUE TITLE
Make BCBIO work with environment modules

### ISSUE THREAD

**Issue by pforai** [chapmanb/bcbio-nextgen#1812]
Dear Authors!
We have quite some of our users who want to give BCBIO a try. We've found that the software is kinda expected to run within a "blank" Linux environment with a defined state and no software pre-installed. 

It seems to me that it doesn't integrate well with common concepts on shared HPC user environments like the environment modules package. We provide all the software that are  ship with BCBIO anyway through modules that the user can load upon request. We automate software installation through tools like https://github.com/hpcugent/easybuild and as such building software is not that of a pain. We can easily bump versions and recompile the whole stack from scratch.

Is there a way to just get part of BCBIO that is the "workflow" engine without it building the tools itself that I might have missed? Also running containers is not something we want to force upon every user. 

Thanks for your suggestions!

best,
P

**Comment by chapmanb** [comment]
Petar;
Thanks for trying to make bcbio fit within your environment. There is no hard requirement that you use the software installed with bcbio and instead manually setup everything it needs. However bcbio does install a lot of software. If you want to do it this way you can install bcbio itself and the data without tools by leaving out the `--tooldir` option when running the installer:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated

Practically, my preferred approach would be to include bcbio with all the tools as a separate module that adds the bcbio PATH into the users environment when loaded. This ensures you have everything needed for bcbio and lets users load/unload bcbio + tools as needed without conflicting with other tool installations. Hope this helps.

**Comment by lpantano** [comment]
Hi @pforai 

I will close this guessing it worked at the end. Let us know if you find more issues.
