### ISSUE TITLE
Non-human references: pig and macaque

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1813]
We have internally added bcbio references (i.e., .fa, .gff, and snpEff) for domestic pig (S. scrofa domesticus) und macaque (M. fascicularis), two organisms commonly used as tox models. Would it be of interest to you, @chapmanb, to host these for common use in bcbio?

**Comment by mjafin** [comment]
I've been using mfa5 for years this way too. The crazy number of scaffolds and contigs meant quite a few changes in bcbio were required way back when. I wasn't sure if anyone else was interested in having mfa5 available through bcbio directly but @pcingola has the genome preparation scripts at https://github.com/pcingola/SnpEff/tree/1912515470a7643d2c08be267943420d57980f76/scripts_build/data/Macaca_fascicularis (using chr** notation for the main chromosomes).

**Comment by chapmanb** [comment]
Sven-Eric and Miika;
Definitely, we're always happy to host/automate more genomes if they'll be useful to the community. If you have files (or scripts available for preparing them) we can add ggd download recipes and make them part of the downloaded genomes. Thanks much for this.

**Comment by schelhorn** [comment]
So to close this: I could contribute `mfa5` and `Sscrofa10.2` in the pre-processed bcbio format with or without indexes - shall I upload them to some S3 bucket of yours, Brad?

**Comment by mjafin** [comment]
Sven-Eric, have you found any annotation for either? There is a dbsnp file for mfa but it was very sparse when I last looked

**Comment by schelhorn** [comment]
Nope, not much variation data around. I'm mostly interested in expression for tox, though.

**Comment by chapmanb** [comment]
Sven-Eric;
I'm not sure if I understand the magic to make a S3 bucket accessible for upload to you but I could grab these and put in the biodata bucket if you have them hosted on AWS somewhere now. Thanks for putting these together.

**Comment by lpantano** [comment]
Hi all

I'll close this assuming you handle this separately.

Thanks!
