### ISSUE TITLE
dbNSFPv3.3a manual download

### ISSUE THREAD

**Issue by rjsicko** [chapmanb/bcbio-nextgen#1815]
I did not have enough room on my main drive to download and unpack dbNSFPv3.3a. I copied `ggd-run.sh` to a mounted drive and ran it there. I now have `dbNSFP.txt.gz` & `dbNSFP.txt.gz.tbi` in a variation folder on the mounted drive which I can move back to `/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation`

Is there any bcbio config files I have to update to point to this new file?  I currently have  `dbNSFP_v3.0b2c.gz` in `/usr/local/share/bcbio/genomes/Hsapiens/GRCh37/variation` 

thank you!

**Comment by chapmanb** [comment]
For manual install you'd need to put three prepared files in `GRCh37/variation`:
```
      - variation/dbNSFP.txt.gz
      - variation/dbNSFP.txt.gz.tbi
      - variation/dbNSFP.readme.txt
```
and edit `GRCh37/versions.csv` to have:
```
dbnsfp,3.3a
```
so bcbio doesn't try to re-install it. Hope this gets it working for you.

**Comment by rjsicko** [comment]
thank you! this worked
