### ISSUE TITLE
Copy over some more MACS files (optionally compressing them) for CHiP-seq analysis

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1817]
cc @LMannarino 

Currently bcbio only saves the XLS file made by MACS. However the other files made during the analysis may be very useful (for visualization, or downstream work), such as `pileup`, `narrowPeak`, `bdg` and `summit` files.

As the pileups are very large, perhaps those could be compressed prior to being copied (they're text, so they could be compressed with high efficiency).

**Comment by lpantano** [comment]
Hi,

I add the whole folder to the sample folder inside the upload directory.

Thanks for the suggestion.

PS: I would work tomorrow in compressing the files before moving.

**Comment by lpantano** [comment]
thanks for the suggestion!
