### ISSUE TITLE
biobambam 2.0.58 installed with bcbio 1.0.1

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1822]
I am using the last release bcbio 1.0.1. Strangely, I have issues with the produced `.bam´ files downstream with htsjdk as described here: https://github.com/gt1/biobambam2/issues/35

It seems that the workaround with `samtools view` was removed in 1.0.1, but the fixed biobambam 2.0.62 is not installed/used in my bcbio 1.0.1. I must admit I have no clue where to look for dependencies. Any help is much appreciated.

**Comment by chapmanb** [comment]
Ben -- when upgrading to a stable release you need to add the `--tools` flag as well. In general you want to upgrade with:
```
bcbio_nextgen.py -u stable --tools --data
```
to get everything synchronized. `--tools` will update the third party dependencies. We leave them separate in case you have specialized upgrade paths. Hope that fixes it for you.

**Comment by gabeng** [comment]
Brad, thanks for the explanation!
