### ISSUE TITLE
Filtering LCR's

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1823]
Hi Brad,

I was going through the config options (again) and noticed the `remove_lcr` option. I was wondering if this options is supported for hg38, since the paper to which it references is completely GRCh37 based. Have these regions been recalculated for hg38?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the question. They are supported on hg38. Here is the download/provenance ggd-recipe:

https://github.com/chapmanb/cloudbiolinux/blob/master/ggd-recipes/hg38/coverage.yaml

In general, the resources files are a good place to check if a genome supports different data types:

https://github.com/chapmanb/bcbio-nextgen/blob/master/config/genomes/hg38-resources.yaml#L16

Hope this helps.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for clearing this up!

M
