### ISSUE TITLE
Filter blacklist region and LCR from macs bed peaks

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1828]
Hi @lpantano,

This is just a suggestion, but for me would be really useful to filter the macs2 bed file (and eventually the bam) in the Chip-seq / ATAC pipeline for Encode Blacklist and LCR using the bed in the genome folder problem_regions.

I am doing this every time, and there is good consensus in doing this.

Thanks,

Alessandro

**Comment by lpantano** [comment]
I follow up here: https://github.com/chapmanb/bcbio-nextgen/issues/1831
