### ISSUE TITLE
Minor inconvenience in CSV->YAML parsing when multiple batch identifiers are assigned to a sample

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1830]
I got a minor bug (or inconvenience) in `bcbio.pipeline.main.variant2pipeline`: when a user specifies multiple batch memberships of a sample via the  `';'` notation in the sample description CSV, and decides to end this list of batch names with an `';'` again (which is off the spec, I know), then this is interpreted as an additional batch name of `''` (empty string). Consequently, this batch identifier is assigned in the YAML to all samples (assuming you always closed the CSV line with  `';'`). That leads to some interesting bugs downstream which are hard to interpret, such as `ValueError: VarDict does not support pooled non-tumor/normal calling`. Would it make sense to help the user a little here to write her CSV by the specs?

**Comment by mjafin** [comment]
Would it make sense to throw an error in templating if an empty field is encountered?

**Comment by schelhorn** [comment]
Yes, that is what I was thinking.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for reporting this problem case. I pushed a fix that will remove empty values from lists which will hopefully avoid this. We don't have any cases right now where we need to specify empty strings in lists, so this removes the problem without needing extra errors being raised. Hope this works and let us know if you run into any other edge cases.

**Comment by schelhorn** [comment]
Thanks!
