### ISSUE TITLE
Annotation - snpSift

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1832]
Hi Brad,

I was wondering if you'd be interested in integrating SnpSift into bcbio for dbNSFP annotations?
Would be nice to provide the option for snpEff users. 
We're looking to start using snpEff ourselves, and as you know, dbNSFP annotations mean a great deal to us.

I previously pushed vcfanno for dbNSFP annotations, and while this is a viable option, it limits the gemini functionality later on, when passed through vcf2db.

We've also noticed the latest version of snpEff supports splice site annations. I've already updated snpEff to the latest version in bioconda and will be issuing a PR in cloudbiolinux with the updated version tag. Would you be interested in implementing this function?

Thanks.
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the heads up on the new functionality in 4.3i. I can pull it in and test to be sure everything works correctly with downstream prioritization and GEMINI database creation.

For snpSift, what do you see as the advantages over vcfanno? We've generally been moving to vcfanno as a single way to do post-variant annotations to make things simpler to maintain and understand.

Thanks much.

**Comment by matthdsm** [comment]
Hi Brad

The advantage of snpsift over vcfanno is the way it adds annotations. For example, VEP puts everything in a CSQ tag, snpeff and snpsift put them in a ANN tag. Those tags are parsed by the geneimpacts module by @brentp when using vcf2db. This puts all variant transcripts + annotations in the variant_impacts  table. Everything outside those tags (eg other INFO fields) are left out. 

Perhaps @brentp could expand on this? The way I see it, for the moment we're stuck with combining VEP\snpEff with vcfanno. 

Of course, I'd love to hear everyone's thoughts on this. Perhaps there's something in the works I don't know of. 

Have a nice weekend
M

**Comment by brentp** [comment]
@matthdsm so the root problem is that stuff isn't getting propagated to the variant_impacts table?

I assume this is related to this comment: https://github.com/quinlan-lab/vcf2db/issues/27#issuecomment-281920563 ?

perhaps vcf2db could have a --transcript-level flag that indicates which fields should be propagated to the variant impacts table? e.g.:
```
--transcript-level m_cap_pred --transcript-level m_cap_rankscore 
```

so those would be propagated to variant_impacts table.

would that address the limitation you're hitting?

**Comment by matthdsm** [comment]
Hi Brent, 

That would be awesome! It would fix the only remaining issue we're having with vcf2db and enable all users here to use dbNSFP to its full extent. 

M

**Comment by brentp** [comment]
I just pushed a change that allows the user to specify which fields should be sent to variant_impacts in vcf2db. It is via: `--impacts-field` which may be specified multiple times. Please give it a try and let me know any problems.

**Comment by matthdsm** [comment]
Hi Brent,
I issued a small PR to fix a typo and I'll adress so further request in a new issue.
Thanks for everything!
M
