### ISSUE TITLE
RFC: Evaluate the MuSE somatic caller

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1833]
As the subject says, [it was published in Genome Biology last year](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1029-6) and at least from the paper it looks interesting for samples that are highly heterogeneous. 

The code is FOSS and available under the GPL v2 (https://github.com/danielfan/MuSE) so that's another plus. 

That said, I haven't actually *tried* it yet. I'd like to test it with my own data and see whether this is a good fit for the pipeline.

**Comment by chapmanb** [comment]
Luca;
Thanks for looking into MuSE. It does look like a nice caller and worth exploring. My main concern is that it doesn't appear to be actively maintained, which is often a sign that install and use may be challenging. Looking forward to hearing how it looks with your data after testing.

**Comment by lbeltrame** [comment]
Some random bits while I have been running it (I'll likely write a longer post when things are over):

- No installation whatsoever, uses a Makefile like samtools et al (sadly)
- Non-verbose output: actually, the output is totally silent (no debug, nothing)
- Suitable for exome or WGS, nothing else
- Two step process: first `MuSE call` (which takes the BAMs and generates an intermediate file) and `MuSE sump` that creates the final VCF file
- `MuSE call` is single-threaded apparently, will likely need to run using split region BAMs for maximum performance
- `MuSE sump` is relatively fast, requires dbSNP and a switch to tell if it's exome or WGS
- As described in the paper, uses `PASS` or `TierXX` where X is a number from 1 to 5 to classify variants
- The VCF is rather bare: we have `GT`, `DP`, `AD`, `BQ` and `SS`.  `INFO` only contains `SOMATIC` (this word) and nothing else
- Like VarScan, it replaces the sample names with `TUMOR` and `NORMAL`, so these would have to get renamed. 
- At least in the sample I tested, only calls SNPs. In this run it yielded 342 SNPs. 

More stuff later when I annotate and filter the results...

**Comment by lbeltrame** [comment]
Some more data from this single sample I analyzed:

- Numerically generates ~half the calls of MuTect 2
- 340 variants, of which 20 pass the filters we usually use (variant DP > 60; VAF >= 5%) and aren't Tier 5
- All of them fall into Tiers from 1 to 4 (no PASS) - notice that Tiers aren't failures, so this might cause problems with prioritization and filtering (up to Tier 4 is OK for WES according to the authors; Tier5 is fine for WGS). 
- Some calls are also found in MuTect 2, with roughly the same calls for depth and fraction. 

Current status: uncertain. This would need probably a validation against the benchmarks used by bcbio, but it would be a lot of work to enable MuSE support just for benchmarking.

**Comment by lbeltrame** [comment]
At the moment I think it's not worthwhile to pursue this, so closing.
