### ISSUE TITLE
cnvkit -> pandas dependency issue

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1836]
Hello Brad,

I had to do a manual `pandas` update from `0.18.1` to `0.19.2` due to an error `AttributeError: 'Series' object has no attribute 'is_monotonic_increasing'` originating from `cnvlib.genome.subtract.py`. That attribute is new in `0.19.1` and `cnvkit` seems to require it. I am using the  `cnvkit` from conda that bcbio installed (also, there was no newer version available through conda). Could there by any dependency issues either in `cnvkit` or bcbio? Mentioning @etal here as well.

**Comment by chapmanb** [comment]
Sven-Eric -- sorry about the issue. I'll bump the minimum pandas version requirement for cnvkit to be sure it installs an up to date version is `is_monotonic_increasing` included. I'll follow up here when the updated package is in bioconda.

**Comment by chapmanb** [comment]
Eric - I've been working on this conda package and realized it's a bit challenging to move to 0.19.x right now. bioconda builds against numpy 1.10 and there are only conda packages for pandas built against numpy 1.11 and 1.12, so trying to increase the pandas version causes conflicts and will lead to needing to rebuild other packages with updated numpy. Is there a larger dependency on having 0.19.2 or could we adjust CNVkit to avoid needing this 0.19.1+ only function?

**Comment by etal** [comment]
OK, I think I can work around it. The purpose of that line is to safely handle nested intervals (which happen sometimes in users' target BED files and more often in gene annotations), in particular to decide whether it's safe to take a fast path to compute interval intersections. I'll add a check for that attribute and if it's missing, always take the slow path.

Is there an ETA on when it's safe to bump the minimum pandas version from 0.18.1 back to 0.19.1+, or some way I can watch for it? The pandas API moves faster than numpy and I would prefer to minimize the range of expected behaviors.

I'm working up to properly triaging chapmanb/bcbio-nextgen#1799, and once that looks OK I'll roll another point release of CNVkit including both that and the pandas shim.

**Comment by chapmanb** [comment]
Eric -- thanks for the quick fix, I'll update the cnvkit conda package with that as a temporary workaround. I'm not sure what it entails to build numpy so raised an issue to discuss bioconda/bioconda-recipes#3961 and will try to get that in place for forward usage. Thanks again.

**Comment by chapmanb** [comment]
I've updated the bioconda package with Eric's fix to support older pandas version so that should be good to go now. We'll work next on updating numpy in bioconda so that we can also use newer versions of pandas as the longer term fix. Thanks again for all the help with this.
