### ISSUE TITLE
Genome fail to update 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1838]
Hi Brad, I have a question I have notice that my genome folder is not complete for some species. I have update with bcbio_nextgen.py upgrade -u development --tools --data --genomes GRCh37 --genomes mm10 --genomes hg19 --genomes mm9 , but still I could not find the complete mm10-resources.yaml.

Do you have any idea what is going on before I just delete and reinstall all the genomes?

Thanks! 

: ~$ cat bcbio/genomes/Mmusculus/mm10/versions.csv 
sranseq,20151008
srnaseq,20161121
problem_regions,20151028
dbsnp,20130912
transcripts,2014-07-14
: ~$ ls bcbio/genomes/Mmusculus/mm10
Agilent_Covered_mm10.bed  bowtie2  bwa  rtg  seq  snpeff  star  vep  versions.csv

**Comment by chapmanb** [comment]
Sorry about the issue. Do you have any error messages from the install? That would be the best place to start debugging. It could be a temporary download issue or some other more persistent problem we could fix but it's hard to guess without more logging information from the upgrade process. Thanks for the help debugging.

**Comment by apastore** [comment]
No, it finish clean. I had notice this a couple of week ago and regular tried to update the genome mm10 and mm9 but they are still incomplete.

**Comment by apastore** [comment]
DBG [config.py]: Using config file /cbio/cslab/home/pastore/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/r-libs.yaml
Creating manifest of installed packages in /cbio/cslab/nobackup/pastore/bcbio/manifest
Third party tools upgrade complete.
Upgrading bcbio-nextgen data files
--2017-02-28 18:34:45--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2017-02-28 18:34:46--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5162374 (4.9M) [application/x-gzip]
Saving to: “STDOUT”

100%[================================================================================================================================================================>] 5,162,374   14.2M/s   in 0.3s    

2017-02-28 18:34:46 (14.2 MB/s) - written to stdout [5162374/5162374]

mv: cannot stat `master': No such file or directory
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7ff157b2c638>
INFO: <cloudbio.flavor.Flavor instance at 0x7ff157b2c638>
INFO: This is a ngs_pipeline_minimal flavor
INFO: This is a ngs_pipeline_minimal flavor
INFO: Distribution __auto__
INFO: Distribution __auto__
INFO: Get local environment
INFO: Get local environment
INFO: CentOS setup
INFO: CentOS setup
WARN [distribution.py(216)]: NixPkgs are currently not supported for centos
WARN [distribution.py(216)]: NixPkgs are currently not supported for centos
DBG [distribution.py]: NixPkgs: Ignored
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'rtg', 'star'], 'genomes': [{'annotations': ['dbnsfp', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase', 'battenberg'], 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA24385', 'giab-NA24631'], 'name': 'Human (hg19)', 'dbkey': 'hg19'}, {'annotations': ['dbnsfp', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase', 'battenberg'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}, {'name': 'Mouse (mm9)', 'dbkey': 'mm9', 'annotations': []}, {'name': 'Mouse (mm10)', 'dbkey': 'mm10', 'annotations': ['problem_regions', 'dbsnp', 'transcripts', 'mirbase']}], 'install_uniref': False}'): Human (hg19), Human (GRCh37), Mouse (mm9), Mouse (mm10)
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'bowtie2', 'rtg', 'star'], 'genomes': [{'annotations': ['dbnsfp', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase', 'battenberg'], 'validation': ['giab-NA12878', 'platinum-genome-NA12878', 'giab-NA24385', 'giab-NA24631'], 'name': 'Human (hg19)', 'dbkey': 'hg19'}, {'annotations': ['dbnsfp', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase', 'battenberg'], 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4'], 'name': 'Human (GRCh37)', 'dbkey': 'GRCh37'}, {'name': 'Mouse (mm9)', 'dbkey': 'mm9', 'annotations': []}, {'name': 'Mouse (mm10)', 'dbkey': 'mm10', 'annotations': ['problem_regions', 'dbsnp', 'transcripts', 'mirbase']}], 'install_uniref': False}'): Human (hg19), Human (GRCh37), Mouse (mm9), Mouse (mm10)

......

Gemini data files updated
bcbio-nextgen data upgrade complete.
Isolated tool installation not automatically added to environmental variables
 Add:
  /cbio/cslab/nobackup/pastore/bcbio/bin to PATH
Upgrade completed successfully.

**Comment by chapmanb** [comment]
Thanks for following up. Glad it's finishing cleanly. It looks like you have the right number of annotation files for mm10 -- it doesn't have nearly has many external resources as human. Could you describe what problem you have with `mm10/seq/mm10-resources.yaml`? It is completely missing or truncated? I'm just trying to understand the error you're seeing so we can diagnose. Thanks much.

**Comment by apastore** [comment]
Hi Brad, sorry for the misunderstend. Bcbio finish clean, but the genome mm10 is not Update and the Problem region and rna gtf are still missing

**Comment by chapmanb** [comment]
Thanks, I see. I'm not sure what happened to your install that those files are missing, but versions.csv indicates they're present to bcbio doesn't try to re-download them. You can edit `mm10/versions.csv` to remove the `problem_regions` and `transcript` lines and re-run and it should hopefully re-download them. Hope this helps.

**Comment by apastore** [comment]
Thanks ! This is was I was looking for!
I did not know that the version.csv was the checkpoint!
Perfect
