### ISSUE TITLE
Feature: remove gvcf blocks before db creation

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1839]
Hi Brad,

We configure bcbio to output gvcf files instead of regular vcf's, but this causes the gemini db's to expand significantly. Would it be possible to remove the gvcf blocks from the vcf before creating the db? gvcf entries are also pretty useless to have in a gemini db, and slow down queries.

This can easily be done using `gvcftools` function `extract_variants`. I'd implement this myself, but I don't really know where I'd best add this pipe.

Your thoughts?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the suggestion. Are you using `tools_on: [gvcf]` to force gVCF output? If so, what you do think about using the joint calling approach instead of this flag, which is more meant for debugging and gVCF work:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#population-calling

For HaplotypeCaller this produces both the sample gVCF and joint called VCF for GEMINI automatically. We'd also like to expand FreeBayes support to do this as well, if you're using that as a caller.

The tricky thing about doing outside of joint calling is that there are many different flavors of gVCF and we'd have to maintain tools to specifically remove reference blocks.

Thanks for the ideas and discussion.

**Comment by matthdsm** [comment]
Hi Brad,
We are indeed using `tools_on: [gvcf]`. I thought this was the best approach, since we're dealing with single samples and not with batches or cohorts.
I'll give it a shot anyways, and keep you posted on the progress!

Thanks for the suggestion!
M

**Comment by matthdsm** [comment]
Hi Brad,
I tested the suggestion above and ran into the following error:
```
Traceback (most recent call last):
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml) 
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 185, in variant2pipeline
    samples = population.prep_db_parallel(samples, run_parallel)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 313, in prep_db_parallel
    output = parallel_fn("prep_gemini_db", to_process)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)  
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch() 
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
    return apply(f, *args, **kwargs)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 268, in prep_gemini_db
    return population.prep_gemini_db(*args)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 39, in prep_gemini_db
    gemini_db = create_gemini_db(gemini_vcf, data, gemini_db, ped_file)
  File "/home/galaxy/bcbio-dev/anaconda/lib/python2.7/site-packages/bcbio/variation/population.py", line 67, in create_gemini_db
    cmd = [vcf2db, ann_file, ped_file, tx_gemini_db] + vcf2db_args
NameError: global name 'ann_file' is not defined
``` 

I'm on the latest dev version, using the following config:
```
#bcbio-nextgen v1.0.2a
---
fc_name: bcbio-dev_run
upload:
  dir: ../final
globals:
  analysis_regions: RefSeq_allexons_20bp.sorted.merged.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: GiB
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      variant_regions: analysis_regions
      effects: snpeff
      effects_transcripts: all
      vcfanno:
        - gemini
        - ../annotations/eog.conf
        - ../jpopgen.conf
    files: [../input/GiB_R1.fastq.gz,..//input/GiB_R2.fastq.gz]
```

If I understand the explanation you gave me yesterday, this approach creates 2 different vcf files. Could it be there's some confusion which vcf should be handled by vcf2db?

Thanks 
M

**Comment by chapmanb** [comment]
Matthias;
Sorry about the problem, this was my mistake during the work of generalizing the vcf2db/vcfanno parts. I pushed a fix and things should now work cleanly if you update to the latest development version. Please let us know if you run into any other problems.

**Comment by matthdsm** [comment]
Great, thanks! I'll go ahead and try this right away.
M

**Comment by matthdsm** [comment]
Hi Brad, 
Thanks for the fix works beautifully now. I've encountered another issue regarding snpEff, but I'll open a new issue for that.

Thanks again!
M

**Comment by matthdsm** [comment]
Hi Brad,

I'd like to reopen this issue. We ran some validation tests using Hap.py and noticed that using the jointcaller approach yielded much worse results than when using the regular variant calling approach. Do you have any idea why and how to fix it?
There are some more tests running at the moment, but the preliminary results don't look too good.

cheers
M

**Comment by chapmanb** [comment]
Matthias -- are you able to share some of the problematic results so we can dig more? Thanks much.

**Comment by matthdsm** [comment]
Hi Brad, 
I'll post the graph's and resulting vcf's as soon as all the tests have finished.

M

**Comment by matthdsm** [comment]
Hi Brad, 
to start, here's the [vcf](https://github.com/chapmanb/bcbio-nextgen/files/841482/GiB-joint-gatk-haplotype-joint-decompose-effects-annotated-gemini.vcf.gz)
 with the problematic calls. The configuration we used is already mentioned above.

I'm re-running the same analysis, but with the built in validation activated. I'll post the results as soon as I have them.

M

**Comment by matthdsm** [comment]
Hi Brad,

The built-in validation finished yesterday. I've sent you an e-mail (@fastmail) with a download link. This links to an archive containing the complete "final" dir of our run.

Hope you can make something out of it.
Cheers

M

**Comment by chapmanb** [comment]
Matthias;
Thanks for sending along the files and validation reports. Can you provide a bit more detail about what specifically concerns you about the outputs? I don't know a lot about your input dataset and capture regions. Guessing that it's an internal NA12878 and exome like set of regions, the results don't look too far off what we're getting now with standard calling in terms of FNR and FDR for SNPs and indels. Here's a recent set of validations:

http://imgur.com/a/xXyXi

What aspects of it made you conclude it was doing much worse? That would help with understanding how best to improve your calls. Thanks.

**Comment by matthdsm** [comment]
Hi Brad,

Sorry for panicking, turns out the fault was entirely ours. We've been comparing the outputs to the wrong files 😇 - I hope we didn't waste too much of your time.

Sorry again and thanks for everything.
M
