### ISSUE TITLE
goleft indexcov crashes on not present expects X and Y chromosomes, possible also breaks MultiQC report

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1843]
Hi Brad,

go left index cov seem to expect chromosomes named X and Y.  

I am running a recent bcbio development version (ca a week old). 

When running alignment and variant calling against a reference without a X and Y chromosome I get this error:
```
[2017-03-06T16:37Z] gridnode7: Uncaught exception occurred
Traceback (most recent call last):
  File "/data/Tools/bcbio/1.0.1/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/Tools/bcbio/1.0.1/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; goleft indexcov --directory /run/Projects/Project123/work/bcbiotx/tmpggPq77/VSDA_400_06  -- /run/Projects/Project123/work/align/Project123_06/Project123_06-sort.bam
2017/03/06 17:37:12 X,Y
2017/03/06 17:37:12 indexcov: running on 1 indexes
2017/03/06 17:37:13 indexcov: expected 2 sex chromosomes, found: 0
' returned non-zero exit status 1
```

Downstream from this error I also have a probably related error creating the multiqc report.
```

[ERROR  ]         multiqc : Oops! The 'goleft_indexcov' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module goleft_indexcov raised an exception: Traceback (most recent call last):
  File "/data/Tools/bcbio/1.0.1/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/data/Tools/bcbio/1.0.1/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/goleft_indexcov/goleft_indexcov.py", line 21, in __init__
    roc_plot = self.roc_plot()
  File "/data/Tools/bcbio/1.0.1/anaconda/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/goleft_indexcov/goleft_indexcov.py", line 74, in roc_plot
    chrom, cov = parts[:2]
ValueError: need more than 1 value to unpack
==============================================
```

This multiqc error seems to be caused by truncated indexcov files. When opened in a text editor all the index cov files seem to end halfway in a record before the records of the last chromosome. 

Could bcbio or go left be modified to handle references without X and Y chromosomes?

Thank you.

**Comment by chapmanb** [comment]
Neill;
Sorry about the issue. I just pushed a fix for this to MultiQC this morning and will get the bioconda package updated and follow up here. The sex chromosome problem is unrelated and bcbio should catch and skip it (which it sounds like it does in your case). There is a better fix into goleft indexcov and I'll also pull that in once there is a new release.

So the short story is that with a MultiQC conda release we should have this issue fixed. I'll report back here once that's in place. Thanks much.

**Comment by NeillGibson** [comment]
Hi Brad. Thank you for fixing this / having this fixed.

**Comment by chapmanb** [comment]
Thanks Neill, let us know if you run into any other problems. Once we update goleft to the next version we'll hopefully avoid the noisy error message about X,Y chromosomes as well. Thanks again.
