### ISSUE TITLE
cnvkit issue with shared-normal somatic analysis

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1858]
I am running in a shared-normal tumor-normal batch setting and have issues with cnvkit outputs files not being correctly generated (and thus no cnvkit vcfs being made). I could track back the issue to the structural.cnvkit module, in the _run_cnvkit_shared function. The function returns a `ckouts` list that is filled in line 163 based on the base name of a input bam file. The same `ckouts` is returned at the end of the function. However, the bam file base name does not take into account paired samples, which are generated in line 166ff with corresponding cnvkit files that are written to disk (in the concatenated sample name-batch name fashion, and not in the single-sample bam base name fashion). 

So the function is specifying single-sample files in line 160ff that are never generated in the batched setting. Thankfully, the right batched files are generated, but never reported in the return value of the function.

Does what I said make any sense to you, Brad, or am I totally off the rails here?

**Comment by chapmanb** [comment]
Sven-Eric;
Thank you for the heads up and apologies about the issue. This was a bug resulting from the updates that fixed binning size issues for share normal batching. I pushed a fix which correctly finds the newly
named files and will pass them on to downstream processing and upload to the final directory. Please let us know if you run into any other problems with this.

**Comment by schelhorn** [comment]
Thanks!

**Comment by schelhorn** [comment]
(Currently I see that now the correct files are being generated in `structural`, but they are not copied over to the `upload` folder. Instead, the single-sample results (non-batched) are copied over to `upload`. I will remove both folders and restart bcbio to see if that is a persistent issue).

**Comment by chapmanb** [comment]
Sven-Eric -- is this a re-run of an older project? If so, that's the expected behavior. It's meant to be back compatible with non-shared normal cases (which were fine previously) so re-running those analysis doesn't require re-computing the CNVkit parts. On new analyses it'll use the batched name approach. Although it shouldn't generate both sets now so I'm not sure if I'm understanding your setup correctly.

**Comment by schelhorn** [comment]
Hi Brad, I have deleted the `structural` folder and re-ran the analysis; the correct (batched) names are now being generated in `structural`, but incorrectly renamed to "unbatched" names in the `upload` folder. The content of the files in `structural` and `upload` is identical (verified by exact file sizes), just the file names differ. So I believe the code doing the copy of cnvkit results to `upload` doesn't consider batches correctly for cnvkit (it does it correctly for paired vardict results, though).

To be more specific, in my `upload` folder there is one results directory for each sample (not batch), and one "combined" directory containing the paired (and correctly batch-named) vardict results. For my paired  (tumor-normal, with shared normals) cnvkit results, the `upload` files are always located in the sample folder associated with the "tumor" phenotype, and the result files within that folder are again named by the "tumor" phenotype sample name. The sample folders of the "normal" phenotypes do not contain any cnvkit result files. 

I am fine with the cnvkit result files being in the folder of the `tumor` sample, also it would be slighlty mor elegant to put them in the same folder as the batched vardict results. In any event, the cnvkit result files should be named according to batch name and not by sample name, since they represent the results of a paired analysis. That would share the behavior of the paired vardict analysis and allows one to differentiate paired from unpaired cnvkit analysis results (and also would allow for tumor-normal analysis with shared tumors, if that is possible at all).

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for all the details. I'm agreed that having the batch names in the outputs makes more sense, and also allows for complex batching setups with SVs like tumor-only and shared tumor-normals together. I pushed a fix which avoids collapsing these in some places in SV and QC where we didn't consider multiple batches, and also renames the outputs to have the batch results. Putting the outputs in the shared/project directory for tumor/normal would be a bit more disruption so I left in the sample directory for the tumor as before. I'm a bit torn on what makes the most sense as both can be confusing in different ways; I know the population and sample VCFs for shared germline calling have tripped up some people.

Thanks again for the details and helping identify the issue. Please let us know if you run into any problems with the updates.

**Comment by schelhorn** [comment]
You're awesome, Brad. Thank you.
