### ISSUE TITLE
VEP dbNSFP plugin is not working with dbNSFP3.0a

### ISSUE THREAD

**Issue by tgambin** [chapmanb/bcbio-nextgen#1869]
I found that there are no dbNSFP annotations included in the final VCF. This is because in file bcbio-nextgen/bcbio/variation/effects.py in _get_dbnsfp function, there are four columns that does not exists in new version of dbNSFP, i.e.: 'RadialSVM_score', 'RadialSVM_pred', 'LR_score', 'LR_pred' . 
Also, do you have any plans to ugrade dbNSFP to v3.4?
Best,
Tomek

**Comment by chapmanb** [comment]
Tomek;
We're currently supporting dbNSFP 3.3 with bcbio, which should have the columns that you're missing. You can update with:
```
bcbio_nextgen.py upgrade --data
```
to re-sync with the latest supported version. It's unfortunately quite tricky to support multiple versions simultaneously so we try to keep data and code in sync.

Is there new data in the dbNSFP 3.4 that you'd like to use? We're not opposed to upgrading but it's a pretty large download so we avoid trying to change it too much to avoid everyone using it need to re-download. Thanks much.

**Comment by tgambin** [comment]
Thank you  for your quick response!

I am sorry, it looks I already have dbnsfp3.3a (I installed bcbio just few days ago).

However, the problem still exists and there are no dbNSFP annotations in the final VCF.
I think the issue is in _get_dbnsfp function from bcbio-nextgen/bcbio/variation/effects.py:

    annotations = ['RadialSVM_score', 'RadialSVM_pred', 'LR_score', 'LR_pred', 'MutationTaster_score',
                   'MutationTaster_pred', 'FATHMM_score', 'FATHMM_pred', 'PROVEAN_score', 'PROVEAN_pred',
                   'MetaSVM_score', 'MetaSVM_pred', 'CADD_raw', 'CADD_phred', 'Reliability_index']

First four columns (RadialSVM_sore, RadialSVM_pred, LR_score, LR_pred) do not exist in dbnsfp3.3. 
https://drive.google.com/file/d/0B60wROKy6OqcTm1KVm5sVW9Rd28/view
It looks that they were included in dbNSFP  versions from 2.3 till 2.8.

When I removed this four columns from the code dbNSFP annotations are generated by variant_effect_predictor script.

Regarding dbNSFP verson, 3.3 is just fine - I was just concerned about having clinvar annotation up to date.

**Comment by chapmanb** [comment]
Tomek;
Thanks much for following and up and identifying the underlying issue. The latest development version removes these missing fields so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
it should now hopefully work cleanly. Please let us know if you run into any other problems.

**Comment by tgambin** [comment]
Thank you Brad! Everything works right now.
