### ISSUE TITLE
PBSPro controller job runs out of memory

### ISSUE THREAD

**Issue by vandalum** [chapmanb/bcbio-nextgen#1872]
Dear bcbio,

When starting a run of  approximately 50 pannel samples on a cluster using PBSpro:
bcbio_nextgen.py ../config/batch_config.yaml -t ipython -n 16 -s pbspro -q default --timeout 600 -r account=cluster-account -r walltime=01:59:00
We ran into the following problem: The bcbio-controller job fails because it runs out of memory.  Which in turn caused the rest of our jobs to fail due to a missing controller. 

The controller batch job was launched without a memory allocation statement by bcbio. This causes the job to launch with the default memory allocation setting configured by the cluster we run bcbio on.  The default memory requested for a job is 256mb in our case, which causes our low memory issue. 

The que default is outside of our control so we applied to following change to fix this issue 
The batchjob is defined in the ipython-cluster-helper pkg, here we altered the draft batchjob in cluster_helper/cluster.py to include a memory allocation statement. (we changed line 739 to: #PBS -l select=1:ncpus={cores}:mem=1gb)

This solved our issue, but I wanted to share our solution. (I thought it was a bit to minimal for a pull request)

**Comment by roryk** [comment]
Thank you! I pushed your change to ipython-cluster-helper, 1GB seems like a good default to me.
