### ISSUE TITLE
Failed to download genome 

### ISSUE THREAD

**Issue by changhw01** [chapmanb/bcbio-nextgen#1881]
Hello,

I am trying to install bcbio in a Google Compute Engine VM. When downloading the genome, it seems failed and the system starts to run STAR with single thread, which is super slow. Is there anything I can do to fix it?

INFO: Genome preparation method ggd failed, trying next
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: GRCh37 seq
INFO: Downloading genome from s3: GRCh37 seq
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/home/hwchang/tmp/cloudbiolinux/cc024535-a1f0-32ba-b64b-d20851a71c42'
[localhost] local: wget --continue --no-check-certificate -O GRCh37-seq.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-seq.tar.xz'
--2017-03-29 17:12:51--  https://s3.amazonaws.com/biodata/genomes/GRCh37-seq.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.17.11
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.17.11|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 713995116 (681M) [binary/octet-stream]
Saving to: ‘GRCh37-seq.tar.xz’

100%[===================================================================================================================================================================================================>] 713,995,116 56.4MB/s   in 17s    

2017-03-29 17:13:09 (39.0 MB/s) - ‘GRCh37-seq.tar.xz’ saved [713995116/713995116]

[localhost] local: mv GRCh37-seq.tar.xz /usr/local/share/bcbio/genomes/Hsapiens/GRCh37
[localhost] local: rm -rf /home/hwchang/tmp/cloudbiolinux/cc024535-a1f0-32ba-b64b-d20851a71c42
[localhost] local: xz -dc GRCh37-seq.tar.xz | tar -xvpf -
seq/
seq/GRCh37.fa
seq/GRCh37.dict
seq/GRCh37.fa.fai
[localhost] local: rm -f GRCh37-seq.tar.xz
INFO: Genome preparation method ggd failed, trying next
INFO: Genome preparation method ggd failed, trying next
INFO: Downloading genome from s3: GRCh37 star
INFO: Downloading genome from s3: GRCh37 star
[localhost] local: pwd
[localhost] local: echo $HOME
[localhost] local: mkdir -p '/home/hwchang/tmp/cloudbiolinux/1516c3ab-87f9-3a58-89d9-5ec24ce90ec6'
[localhost] local: wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz'
--2017-03-29 17:14:05--  https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.81.107
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.81.107|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-29 17:14:05 ERROR 404: Not Found.

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O GRCh37-star.tar.xz 'https://s3.amazonaws.com/biodata/genomes/GRCh37-star.tar.xz''

INFO: Genome preparation method s3 failed, trying next
INFO: Genome preparation method s3 failed, trying next
INFO: Preparing genome GRCh37 with index star
INFO: Preparing genome GRCh37 with index star
[localhost] local: mkdir /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/star
[localhost] local: export PATH=/usr/local/bin:$PATH && STAR --genomeDir /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/star --genomeFastaFiles /usr/local/share/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa --runThreadN 1 --limitGenomeGenerateRAM 30000000000 --genomeChrBinNbits 14 --runMode genomeGenerate --genomeSAindexNbases 14
Mar 29 17:14:07 ..... started STAR run
Mar 29 17:14:07 ... starting to generate Genome files
Mar 29 17:15:15 ... starting to sort Suffix Array. This may take a long time...
Mar 29 17:15:33 ... sorting Suffix Array chunks and saving them to disk...

**Comment by roryk** [comment]
Hi Huang-Wei,

The STAR indices are pretty big so we have to generate them locally instead of download them. The main installer script doesn't have a way to pass a number of cores, but if you install first with no data via the --nodata flag, and then do an upgrade to the data, you can pass a cores argument to the upgrade command which will build the index with multiple cores as a workaround for now.

**Comment by changhw01** [comment]
Okay, sounds reasonable to me. Then should we remove the download steps from the script? Or I misunderstood what the messages mean? Thanks!

**Comment by roryk** [comment]
Hi Huang-Wei,

The download messages are innocuous, it tries to download the STAR indexes but since it can't find them, it builds them; it will do the same for other things that it tries to download as well.

**Comment by chapmanb** [comment]
Huang-Wei and Rory -- glad this all got resolved so quickly. To make this easier in the future I also added a `--cores` option to `bcbio_nextgen_install.py` and added documentation. Hope the install finished cleanly after following Rory's approach and thanks for letting us know about the problem.
