### ISSUE TITLE
Align SOLiD RNA sequencing

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#1892]
Just a question, does anybody know if I can use BCBIO on SOLiD RNA seq? and If yes with aligner and which parameter should I set? I have seen that start does not support SOLiD and when I set tophat2 i get the following error:

Command 'set -o pipefail; unset JAVA_HOME && /bcbio/galaxy/../anaconda/bin/bowtie2 -s 100000 -u 250000 -q -x /bcbio/genomes/Hsapiens/hg19/bowtie2/hg19 --sensitive -X 2000 -1 /sradownload/merged/MB147_R1.fastq.gz -2 /merged/MB147_R2.fastq.gz -p 16 | bamsormadup inputformat=sam threads=16 tmpfile=/GSE68559/work/bcbiotx/tmp9wq1tD/MB147-sort-sorttmp-markdup SO=coordinate indexfilename=/GSE68559/work/bcbiotx/tmp9wq1tD/MB147-sort.bam.bai > /GSE68559/work/bcbiotx/tmp9wq1tD/MB147-sort.bam
Error: Read SRR2009389.1 1_28_3544_F3 length=50 has more quality values than read characters.
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT) 

Thanks a lot!

**Comment by schelhorn** [comment]
Solid is not supported by any of the bcbio aligners, as far as I know. Bowtie aligns in color space as well, but I don't know if that is supported in bcbio. Perhaps it's best to convert first: https://davetang.org/muse/2012/07/04/from-sra-to-fastq-for-solid-data/

**Comment by apastore** [comment]
Thanks ! Yes, this is an option I was considering any idea if the converted fastq a valid fastq is ? or still there are problem with the quality scores?

**Comment by chapmanb** [comment]
Sven-Eric is exactly right, converting to fastq first is the best approach. I personally don't have any recent experience with SOLiD data so can't predict how well it will work, but unfortunately there is no support for colorspace in bcbio. Hope converting works for you.

**Comment by apastore** [comment]
Thanks!

(For some reason the solid2fastq.pl is not generating any fastq)
