### ISSUE TITLE
How to use --alleles in yaml configure of gatk?

### ISSUE THREAD

**Issue by semal** [chapmanb/bcbio-nextgen#1897]
I want to get specific SNPs genotype by using gatk UnifiedGenotyper with '--alleles' option. I use options: ["--genotyping_mode", "GENOTYPE_GIVEN_ALLELES", "--alleles", "../input/snps.vcf"] in gatk resources configure. But it seems not working.

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the lack of support for this. I added support to also allow custom setting of options using resources with UnifiedGenotyper:
```
resources:
   gatk:
    options: [...]
```
If you update to the latest development version (`bcbio_nextgen.py upgrade -u development`).

This previously did work with HaplotyperCaller (using `gatk-haplotype`). Out of curiousity, why do you prefer using UnifiedGenotyper over HaplotypeCaller?

Hope this helps and thanks again for the report.
