### ISSUE TITLE
ImportError: libhts.so.1: on upgraded bcbio version

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#1905]
Hi, 

I get the following error when trying to run an analysis from an upgraded bcbio development installation. 
```
from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
```

I am guessing my pysam library is out of date.

I tried to use bcbio_conda to update pysam. But that gives a timeout error. 
```
bcbio_conda install -c bioconda pysam
Fetching package metadata .....

CondaHTTPError: HTTP None None for url <https://conda.binstar.org/bcbio/linux-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)
```

Thank you.

**Comment by chapmanb** [comment]
Neill;
Sorry about the issues, I thought we'd hopefully shaken out all of these incompatibilities by requiring the recent pysam in all of the newest builds. As a manual workaround, the `bcbio_conda` invocation you supplied should work. It looks like you might be referencing some old channels in your `~/.condarc` file (binstar.org is the old name of anaconda.org). Maybe clearing out `binstar.org` references from there will resolve the issue and get the manual update working. Hope this fixes it for you.

**Comment by NeillGibson** [comment]
After removing the `binstar `entry from  `~/.condarc` I could update pysam to latest version.  That also fixed the import error allowing me start an analysis.  Thank you.
