### ISSUE TITLE
Speed up the germline variant pipeline for ensemble calling might be easy

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1907]
Hello, bcbio developers!

Thanks for the excellent work!

In germline variant calling pipeline when I use ensembl calling,
it creates gemini database for each caller, i.e. 5 databases:
- ensemble.db
- gatk.db
- samtools.db
- platypus.db
- freebayes.db

And it takes a while for families.

Is it possible to turn off generation of last 4 gemini databases?

Sergey

**Comment by chapmanb** [comment]
Sergey;
We don't have a way to fine tune which variants have gemini databases built for them, and that sounds like something that's probably a little more fine-grained then we want to incorporate. A couple of options are:

- Swap over to use the new vcfanno/gemini pipeline for GRCh37/hg19 (if that's the build you're working against). You can do with `vcfanno: [gemini]` (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#variant-annotation). It's a faster build and creation process.
- Turn off automated GEMINI builds all together (`tools_off: [gemini]`) and build the databases you want after the initial run.

Hope one of these will work for you.

**Comment by naumenko-sa** [comment]
Ok, I'll try the new loader.
Thanks!
SN
