### ISSUE TITLE
battenberg hg38

### ISSUE THREAD

**Issue by mcieslik-mctp** [chapmanb/bcbio-nextgen#1910]
I was reading through the battenberg module `bcbio-nextgen/bcbio/structural/battenberg.py` and found that specific GRCh37 genomic positions are hardcoded in lines 94-100. Does this mean that the battenberg.py does not work on hg38?

Thanks!

**Comment by chapmanb** [comment]
Unfortunately battenberg is hg19/GRCh37 only. It uses a number of imputation files specific to build 37. Battenberg has also recently been un-open sourced:

https://github.com/cancerit/cgpBattenberg/releases

so we're not likely to explore trying to add this soon. We are continuing to work on purity, clonality and heterogeneity analysis that will support hg38 and the work plan is in #1876. Sorry to not have this ready currently but hope this helps.
