### ISSUE TITLE
Update to Ensembl VEP

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1911]
Hi Brad,

Ensembl deprecated the `variant_effect_predictor.pl`script with the latest release in favor of a new and improved `ensembl_vep` script. How would you feel about adopting the latest and greatest version? There are some slight modifications in the CLI, but nothing major. I'll look into updating the code to reflect the new arguments.

I've already created a conda recipe for the latest release( at the time), but the script still seems under heavy development (e.g. a new release each week).

Would you support this update?  I also would like to push for some modifications to the annotation approach. Personally, I'd like to remove dbNSFP and dbscSNV from vep and move those to vcfanno.

Let me know what you think.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Thanks much for this, it would be great to transition to the new VEP scripts. I also agree this would be a good time to consider moving things like dbNSFP to vcfanno. My main concern is breaking user's downstream scripts that use the VEP annotations.

Do you have a quick overview of what changes with this adjustment so we could document this as part of the improvement? It would also help other users comment here on if this will negatively or positively change their workflows. Thanks for the help continuing to move this forward.

**Comment by matthdsm** [comment]
Hi Brad,
I don't think there will be much issues downstream, except for some field names in the VCF that are changed.

The biggest changes will be:
- All fields from dbNSFP and dbscSNV will be moved OUT of the CSQ tag and into separate fields. The field names itself will not be changed, and since the config file is easily modified, advanced users can add /remove fields as they please.
- When creating a gemini db, only the fields within the CSQ tag are incorporated into the `variants_impacts` table. This means that all dbNSFP fields will be absent in that table. They will still be available in the `variants` table.
- For the changes in VEP, I'll have to refer to the docs, found [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#new)

I plan to keep the conda recipe up to date and will be moving forward to v89 coming May. Perhaps you could hold off a new bcbio release until then? 

I'll open a PR for this, so you can track the modifications and give your opinion.

Cheers 
M

**Comment by matthdsm** [comment]
PR with modifications can be found here: #1916 

M

**Comment by matthdsm** [comment]
Hi Brad,

I don't know if you (or anyone else) has had the time to test the new vep implementation, but I'm experiencing a small issue, and I can't seem to find it.

When running vep, the bcbio-debug log reports the following:
```
[2017-05-16T20:48Z] multiprocessing: postprocess_variants
[2017-05-16T20:48Z] Finalizing variant calls: GiaB, gatk-haplotype
[2017-05-16T20:48Z] Calculating variation effects for GiaB, gatk-haplotype
[2017-05-16T20:48Z] Ensembl variant effect predictor : GiaB
[2017-05-16T20:50Z]
[2017-05-16T20:50Z] gzip: stdout: Broken pipe
```
The commands log shows this:
```
[2017-05-16T20:48Z] unset PERL5LIB && export PATH=/home/galaxy/bcbio-dev/anaconda/bin:$PATH && /home/galaxy/bcbio-dev/anaconda/bin/vep --vcf -o stdout -i /home/projects/bcbio_annotation/test_runs/bcbio_dev/work/joint/gatk-haplotype-joint/GiaB-joint/GiaB-joint-joint.vcf.gz --fork 8 --species homo_sapiens --no_stats --cache --merged --offline --dir /home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/vep --symbol --numbers --biotype --total_length --canonical --gene_phenotype --ccds --uniprot --domains --regulatory --protein --tsl --appris --af --max_af --af_1kg --af_esp --af_exac --pubmed --variant_class --plugin LoF,human_ancestor_fa:false --plugin MaxEntScan,/home/galaxy/bcbio-dev/anaconda/share/maxentscan-0_2004.04.21-0 --plugin GeneSplicer,/home/galaxy/bcbio-dev/anaconda/share/genesplicer-1.0-1/genesplicer,/home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/variation/genesplicer --sift b --polyphen b --hgvs --shift_hgvs 1 --fasta /home/galaxy/bcbio-dev/genomes/Hsapiens/hg38/seq/hg38.fa | sed '/^#/! s/;;/;/g' | bgzip -c > /tmp/bcbio/tmpK2ymfZ/GiaB-joint-joint-vepeffects.vcf.gz
```

I've tried to run to command manually in the bcbio env, and everything seems to run fine. However, when running from within the pipeline, I'm getting the `gzip` error. `vep` seems to be running fine, but takes forever (8h+) and then crashes.

Do you have any idea what could be the issue? Are there any more steps I could take to debug this?

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for the heads up. I hadn't run the new VEP on a large file but did now to do some testing and also see the same behavior you did. Removing the HGVS arguments fixes the problem and `vep` will now finish in ~1hr on whole genome files when running with 8 cores. The `gzip: stdout` appears to not be a problem, I'd guess that somewhere in the `vep` script they check the head of a gzipped file which gives these sorts of messages (something like `zcat file.gz | head -10`).

I currently commented out the HGVS generation so `vep` will work. It would be worth inquiring with the Ensembl team about expected runtimes for including HGVS and see if there are any suggestions to improve the speed. I know it would be nice to have if we can get it running in a reasonable time. Thanks much.

**Comment by matthdsm** [comment]
Hi Brad,

I think the HGVS issue can easily be fixed with some small modifications. In it's current form, vep uses the plain fasta file.  

if we modify the cache installer command in `prep_vep_cache` to include the ensembl provided compressed fasta file, I think this issue should be resolved. It is weird though that I'm able to run the entire command without any hiccups via the command line.

I'll do some more testing and keep you posted.

Cheers
M

**Comment by matthdsm** [comment]
Hi Brad,

it seems there's still a small issue with the conda recipe for vep. The Bio:DB:HTS module needed to use gzipped files isn't found by the executable. I've asked @willmclaren for some help in ensembl/ensembl-vep#50. In the meantime, perhaps you could have a quick glance at the recipe? There might be something I'm missing there.

Thanks
M

**Comment by matthdsm** [comment]
Hi Brad,

According to [this](ensembl/ensembl-vep#53) the hgvs issues can be fixed by solving some issues with the bioconda recipe, mainly by fixing the bio-db-hts package, so vep can find and use it. This should improve perfomance. Furhter increases can be had by using a compressed fasta as reference.

I'm doing some test builds locally, but so far no improvements. Since you did the magic for the previous versions of vep, would you be willing to check out the recipe?

Thanks
M

**Comment by matthdsm** [comment]
Another update, 
I updated the vep recipe to the latest subversion and did some more checks.
Apparently, the issues we're having are caused by htslib. conda vep + htslib 1.3 works fine.
With htslib 1.4.1 I'm getting [this](bioconda/bioconda-recipes#4783).

Cheers
M
