### ISSUE TITLE
Hosting dbNSFP file

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1912]
Hi Brad,

To increase the speed of the installation, do you suppose it would be possible for you to host a preprocessed dbNSFP file + index on AWS? I realize this comes at an increased cost for you, but it would greatly improve the installation time and user friendliness, since this is a step that often has issues during installation.

Cheers 
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for checking about this. dbNSFP is a pain to install, but download costs can get expensive so we generally try not to host large files ourselves. As an alternative, if you're about to host pre-built databases in your AWS S3 I'd be happy to point the downloads at those. Hope this works for you.

**Comment by matthdsm** [comment]
Hi Brad, 

thanks for the reply. I'm sorry to say we don't have any publicly available storage at the moment, so us hosting this file isn't an option at the moment.

Thanks anyway.
M
