### ISSUE TITLE
Invalid character '%' in 'FREQ' FORMAT field 

### ISSUE THREAD

**Issue by JoKw** [chapmanb/bcbio-nextgen#1914]
Hi,

When I used the ensemble method, I encountered the following error:

`CalledProcessError: Command 'set -o pipefail; bcftools reheader -h /home/test/sample/work/varscan/samplecall-annotated-header.txt /home/test/sample/work/varscan/samplecall.vcf.gz | bcftools view  | bgzip -c > /home/test/sample/work/bcbiotx/tmpB22Zux/samplecall-annotated.vcf.gz`
`[W::vcf_parse] contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)`
`[E::vcf_parse_format] Invalid character '%' in 'FREQ' FORMAT field at 1:11181327`
`Write failed, wrote -1 instead of 14820 bytes.`
`' returned non-zero exit status 255`

I had a look at the Varscan VCF file and it seems that the error was caused by the use of "%" in the FREQ field in the VCF file 

Any fix for that? Thanks

**Comment by chapmanb** [comment]
Sorry about the issue, it looks like there is something problematic with the varscan output file that bcftools does not like. Would you be able to share the output of:
```
tabix /home/test/sample/work/varscan/samplecall.vcf.gz 1:11181327-11181327
```
and we can determine how best to work around it? Thanks much for the help debugging.

**Comment by JoKw** [comment]
1       11166713        .       T       C       0       PASS
 ADP=168;HET=1;HOM=0;NC=0;WT=0
GT:GQ:SDP:DP:RD:AD:FREQ:PVAL:RBQ:ABQ:RDF:RDR:ADF:ADR
 0/1:154:168:168:122:46:27.38%:3.9712E-16:55:54:88:34:34:12

**Comment by chapmanb** [comment]
Thanks so much for following up with the problem samples. This helped me identify the underlying issue: we have code to fix FREQ but it was only being used on tumor/normal samples, not tumor-only. I pushed a fix to the latest development version (`bcbio_nextgen.py upgrade -u development`) which should resolve the problem. You can re-run your current project but should remove the `varscan` directory and `checkpoints_parallel` directories to let bcbio re-run the VarScan variant calls with the post-calling fix. Hope this gets everything working cleanly for you.
