### ISSUE TITLE
Installation problems HELP

### ISSUE THREAD

**Issue by YangZituo** [chapmanb/bcbio-nextgen#1921]
Hello,

I am trying to install bcbio on Temasek Life science HPC in Singapore and got the below error,

The following packages will be DOWNGRADED due to dependency conflicts:

    fontconfig:                        2.12.1-4                   conda-forge --> 2.11.1-6          conda-forge
    freetype:                          2.7-1                      conda-forge --> 2.6.3-1           conda-forge
    icu:                               58.1-1                     conda-forge --> 56.1-4            conda-forge
    libxml2:                           2.9.4-4                    conda-forge --> 2.9.4-3           conda-forge
    matplotlib:                        2.0.1-np112py27_0          conda-forge --> 2.0.0-np112py27_1 conda-forge
    pillow:                            4.1.0-py27_0               conda-forge --> 4.0.0-py27_1      conda-forge
    pyqt:                              5.6.0-py27_2               conda-forge --> 4.11.4-py27_2     conda-forge
    qt:                                5.6.2-2                    conda-forge --> 4.8.7-3           conda-forge

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /data/GenhuaLab/zituo/bcbio/anaconda  (writable)
    default environment : /data/GenhuaLab/zituo/bcbio/anaconda
       envs directories : /data/GenhuaLab/zituo/bcbio/anaconda/envs
          package cache : /data/GenhuaLab/zituo/bcbio/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /gpfsdata/GenhuaLab/zituo/bcbio/anaconda/bin/conda install --quiet -y -c bioconda -c conda-forge -c r age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variant-effect-predictor=87 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli nodejs p7zip s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics=0.18.0 bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges=2.4.7 bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi`

    Traceback (most recent call last):
      File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/data/GenhuaLab/zituo/bcbio/anaconda/pkgs/genesplicer-1.0-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

Fatal error: local() encountered an error (return code 1) while executing '/gpfsdata/GenhuaLab/zituo/bcbio/anaconda/bin/conda install --quiet -y -c bioconda -c conda-forge -c r age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variant-effect-predictor=87 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli nodejs p7zip s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics=0.18.0 bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges=2.4.7 bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.6/subprocess.py", line 502, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data/GenhuaLab/zituo/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/data/GenhuaLab/zituo/bcbio', '--data']' returned non-zero exit status 1

always go back there.
Anybody can help me? Thanks!! @chapmanb

**Comment by chapmanb** [comment]
Sorry about the install issue. This looks like your connection is timing out when downloading conda packages:
```
HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
```
We don't have a good fix other than rerunning the same install command. bcbio should pick up where it left off and retry downloads. Depending on your connection it could happen multiple times for all the packages but hopefully a few retrys will get them downloaded for you. Hope this helps.

**Comment by YangZituo** [comment]
Thanks for your reply.
But I find that 

"File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install    raise CondaRuntimeError('RuntimeError: %s' % e)"

this seems not about the connection and i have installed the python2.7. Does it necessary to install it with bc-bio?
Thanks a lot!

**Comment by YangZituo** [comment]
Traceback (most recent call last):
      File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/data/GenhuaLab/zituo/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/data/GenhuaLab/zituo/local/share/bcbio/anaconda/pkgs/star-2.5.3a-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

It says "Could not open u'/data/GenhuaLab/zituo/local/share/bcbio/anaconda/pkgs/star-2.5.3a-0.tar.bz2.part' for writing" 
Does it is related to some problems that could not open /........./ ??? 
Because I think the network is actually good.

Thanks @chapmanb

**Comment by chapmanb** [comment]
Thanks for the followup. When you restarted did you find that you get stuck at the same place consistently? I haven't seen this error before but the `Read timed out` indicates to me that the problem is due to network issues. This could also be an error on the amazon side, but either way a restart at the same place hopefully will fix it. If not, happy to try to debug more but it would be useful to understand where you are at with the retries.

Beyond that, everything else looks normal from the bcbio side. It installed a separate conda python environment and is using it for the tool installation. Hope this helps.

**Comment by YangZituo** [comment]
Thanks for your reply.
I always get stuck at the same place : 
"Traceback (most recent call last):
  File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
    exit_code = args.func(args, p)
  File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/data/GenhuaLab/zituo/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/data/GenhuaLab/zituo/bcbio/anaconda/pkgs/genesplicer-1.0-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.)."
Showing "could not open /genesplicer-1.0-1.tar.bz2.part' for writing /"

And, sorry I'm new in Linux. May you tell me how to restart the installation at the same place?

Thanks a lot! @chapmanb

**Comment by YangZituo** [comment]
Hi, I just reinstall many times.....then it complete. 
Anyway, Thanks for your kind suggestions!!

**Comment by chapmanb** [comment]
Thank you for following up, I'm glad it worked in the end and hope all works cleanly with bcbio.
