### ISSUE TITLE
Sambamba equivalent of bedcov?

### ISSUE THREAD

**Issue by abalter** [chapmanb/bcbio-nextgen#1923]
Is there an equivalent?

**Comment by lpantano** [comment]
Hi @abalter 

I don't know if sambamba base will do the job, not sure what are you asking. Is there any problem with bcbio?

**Comment by abalter** [comment]
I would like something like 

    sambamba depth -b <bed file of regions> [ list of bam files ] > out

That gives an output like:

    chr        start        stop        depth
    1            18293     19873     3478
    ...            ...           ...             ...
