### ISSUE TITLE
Quick readgroup question

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1927]
Quick question: assuming that I want to feed BAMs with one read group per BAM into bcbio, but I want the samples to be named (and associated with the metadata) by the basename of the BAM file rather than by the name of the read group, is there a way to enforce that? Ignoring the read group all together and just taking all reads from the BAM would work as well. BAMs will be re-mapped by bcbio and I am aiming for variant2 with `bwa`+`vardict`, if that makes a difference.

**Comment by chapmanb** [comment]
Sven-Eric;
Are you running into an issue during the templating step? I'm not sure if I totally understand but with a BAM bcbio will auto assign the description from the existing read group, but then also give you the chance to over-write that to whatever you want through the CSV metdata:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/workflow/template.py#L358

so it should use either the original description or the base BAM name, whatever you put in the first column of your metadata CSV file.

For the actual run, bcbio uses the read group specified in description, if realigning, and does not keep the original read group.

Does that answer your question? Let me know if not and happy to discuss more.

**Comment by schelhorn** [comment]
I see; so if a fill in the `description` field in the metadata CSV then the read group name will never be used within bcbio? That's exactly how I want it, thanks. Feel free to close.

**Comment by schelhorn** [comment]
Belay that, another question since I have your attention: if I use BAMs as inputs, and want to remap, will bcbio also split the mapping across multiple compute nodes (as it does with the bgzipped FASTQs by streaming batches of FASTQ records to multiple mapper processes)?

**Comment by chapmanb** [comment]
That's exactly right. The only time we use an existing read group is if you feel a pre-aligned BAM file and don't do alignment or have `bam_clean: fixrg` turned on. Glad this works for you.

**Comment by chapmanb** [comment]
Sven-Eric;
It will split mapping as normal. The first step is to convert BAMs into bgzipped fastqs then they get processed as normal. So for realigning BAM inputs should be no different than fastq. Hope this helps.

**Comment by schelhorn** [comment]
Excellent, thanks a bunch. So it always does the right thing whatever you throw at it. I should have known that, naturally ;)
