### ISSUE TITLE
Uncaught exception in indexcov

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#1930]
Hi,
I'm doing somatic/germline VC with match T/N samples, and while bcbio finishes everything fine, there are still some errors in the bcbio-nextgen.log file that I'm not sure about:

> indexcov: 1 principal components, not plotting
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/brentp/goleft/indexcov.plotSex(0xc4239b40c0, 0xc4200e73c0, 0x2, 0x2, 0xc4202b1690, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
>         /home/brentp/go/src/github.com/brentp/goleft/indexcov/plot.go:315 +0xc22
> github.com/brentp/goleft/indexcov.writeIndex(0xc4239b40c0, 0xc420270038, 0x1, 0x1, 0xc4200e73c0, 0x2, 0x2, 0xc4202b1690, 0x1, 0x1, ...)
>         /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:704 +0x1977
> github.com/brentp/goleft/indexcov.Main()
>         /home/brentp/go/src/github.com/brentp/goleft/indexcov/indexcov.go:358 +0x711
> main.main()
>         /home/brentp/go/src/github.com/brentp/goleft/cmd/goleft/goleft.go:66 +0x191
> ' returned non-zero exit status 2

This is my config file:
https://gist.github.com/leiendeckerlu/298c1605a7be435e1b7e6f6a1a2dd4a3

And this is the except from the bcbio log:
https://gist.github.com/leiendeckerlu/b5117d13e200ada14812f829ac0df470

Do I have to worry about these? Thanks a lot!

**Comment by chapmanb** [comment]
Glad you got everything to run though. goleft indexcov is a QC step and some components like the PCA don't always work depending on the amount of data in your samples. bcbio should correctly catch these errors and keep working, so they're nothing to worry about. Hope this helps.
