### ISSUE TITLE
QC: sambamba view -c single-threaded

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#1935]
Brad, I know you had your reasons removing multithreading from sambamba view
https://github.com/chapmanb/bcbio-nextgen/commit/8e2e9a0219e2d6b077a546c57b735f271b4083cc

In my experience this adds quite a bit of overhead to the process. Are there any plans to bring this back to multi-threading or to switch to a different tool?

**Comment by ohofmann** [comment]
I need to start testing the latest sambamba version to see if it resolves the problem. Thanks for the nudge.

**Comment by chapmanb** [comment]
Ben and Oliver;
samtools 1.4 supports multithreading in the `view` and `index` commands and an alternative approach is to swap over to use of samtools over sambamba for these cases. I'm not sure where we stand with sambamba on the latest releases -- it's been a difficult problem to debug as we only have intermittent failures on some machines. I could look into swapping over and for this section will need to revisit the QC work @vladsaveliev added.

**Comment by NeillGibson** [comment]
FYI: I understand from the Sambama Issue #283 that performance for simple reading and writing is now almost the same between samtools1.4 and latest sambamba.  On our systems samtools is also more reliable than sambamba.

**Comment by gabeng** [comment]
Hi Brad and Oliver,

just wanted to check back with you: what are your plans regarding implementing a change - swapping to samtools vs testing sambamba? In our application the single threaded `sambamba view -c -t 1` is slowing us down quite a bit.

**Comment by ohofmann** [comment]
I'd prefer a swap to samtools if possible.

**Comment by chapmanb** [comment]
Ben -- thanks, this is definitely something we're planning to do soon. Sorry to not have tackled it yet with other ongoing work, but hopefully we'll continue to move over sambamba commands to multi-threaded samtools. We'll plan to prioritize the counting functionality first. Thanks for pinging about this.

**Comment by chapmanb** [comment]
Ben, Neill and Oliver;
Thank you again for all the feedback and thoughts on this. The latest development version of bcbio now avoids use of multicore sambamba, replacing it with equivalent samtools commands for most things and mosdepth for depth calculations. I hope this will be faster and more reliable than the previous version. We're planning to have a release soon with all these improvements so please let us know if you run into any problems. Thank you again.
