### ISSUE TITLE
GATK memory issue

### ISSUE THREAD

**Issue by pfujita** [chapmanb/bcbio-nextgen#1936]
Hi @chapmanb and team,

We're having a memory issue which may be related to [1654](https://github.com/chapmanb/bcbio-nextgen/issues/1654). We had samples fail the bamprep stage with a call similar to the following:

> 

> subprocess.CalledProcessError: Command 'set -o pipefail; java -Xms454m -Xmx9g -XX:+UseSerialGC -Djava.io.tmpdir=/coldstorage/fastq/D00108/170512_D00108_0715_BHG2MCBCXY/051217_EX33/GML388_51695910_bcbio/tx/tmpJ7bYiF -jar /mnt/speed/qc/sequencing/bcbio/toolplus/gatk/2015.1.1-3.4.46-0-ga8e1d99/GenomeAnalysisTK.jar -T PrintReads -L 12:1-15637187 -R /mnt/speed/qc/sequencing/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /coldstorage/fastq/D00108/170512_D00108_0715_BHG2MCBCXY/051217_EX33/GML388_51695910_bcbio/align/GML388_51695910/GML388_51695910-sort.bam -BQSR /coldstorage/fastq/D00108/170512_D00108_0715_BHG2MCBCXY/051217_EX33/GML388_51695910_bcbio/align/GML388_51695910/GML388_51695910-sort.grp -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment -o /coldstorage/fastq/D00108/170512_D00108_0715_BHG2MCBCXY/051217_EX33/GML388_51695910_bcbio/bamprep/GML388_51695910/12/tx/tmpm5pKF0/GML388_51695910-sort-12_0_15637187-prep.bam
> ...
> Exception in thread "ProgressMeterDaemon" java.lang.OutOfMemoryError: Java heap space
>         at java.util.Arrays.copyOfRange(Arrays.java:3664)
>         at java.lang.String.<init>(String.java:201)
>         at java.lang.StringBuilder.toString(StringBuilder.java:407)
>         at java.lang.Throwable.printStackTrace(Throwable.java:658)
>         at java.lang.Throwable.printStackTrace(Throwable.java:721)
>         at org.apache.log4j.spi.LocationInfo.<init>(LocationInfo.java:113)
>         at org.apache.log4j.spi.LoggingEvent.getLocationInformation(LoggingEvent.java:247)
>         at org.apache.log4j.helpers.PatternParser$ClassNamePatternConverter.getFullyQualifiedName(PatternParser.java:538)
>         at org.apache.log4j.helpers.PatternParser$NamedPatternConverter.convert(PatternParser.java:511)
>         at org.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:65)
>         at org.apache.log4j.PatternLayout.format(PatternLayout.java:502)
>         at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:302)
>         at org.apache.log4j.WriterAppender.append(WriterAppender.java:160)
>         at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
>         at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
>         at org.apache.log4j.Category.callAppenders(Category.java:206)
>         at org.apache.log4j.Category.forcedLog(Category.java:391)
>         at org.apache.log4j.Category.info(Category.java:666)
>         at org.broadinstitute.gatk.utils.progressmeter.ProgressMeter.printProgress(ProgressMeter.java:390)
>         at org.broadinstitute.gatk.utils.progressmeter.ProgressMeterDaemon.run(ProgressMeterDaemon.java:102)
> ##### ERROR ------------------------------------------------------------------------------------------
> ##### ERROR A USER ERROR has occurred (version 2015.1.1-3.4.46-0-ga8e1d99):
> ##### ERROR
> ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
> ##### ERROR The error message below tells you what is the problem.
> ##### ERROR
> ##### ERROR If the problem is an invalid argument, please check the online documentation guide
> ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
> ##### ERROR
> ##### ERROR Visit our website for extensive documentation and answers to
> ##### ERROR commonly asked questions http://gatkdocs.appistry.com/
> ##### ERROR
> ##### ERROR MESSAGE: There was a failure because you did not provide enough memory to run this program.  See the -Xmx JVM argument to adjust the maximum heap size provided to Java
> ##### ERROR ------------------------------------------------------------------------------------------
> ' returned non-zero exit status 1

Note this setting in particular: -Xmx9g

But if I look in our system.yaml file (attached:[bcbio_system.yaml.txt](https://github.com/chapmanb/bcbio-nextgen/files/1005970/bcbio_system.yaml.txt)), we're not passing 9g as a memory allocation anywhere (or I'm misunderstanding how this works). Do you know where it's getting this number from if not from the system.yaml as I'm guessing we need to up this limit to get these samples to run?

**Comment by chapmanb** [comment]
Pauline;
Sorry about the issue and thanks for the report. bcbio retrieves the memory from the gatk section in your configuration:
```
gatk:
    dir: /mnt/speed/qc/sequencing/bcbio/toolplus/gatk/2015.1.1-3.4.46-0-ga8e1d99
    jvm_opts:
    - -Xms500m
    - -Xmx10g
```
It's scaling down the memory slighly to help manage the overhead of running multiple commands in parallel on the machine. If you increase `-Xmx` here it will increase the memory available to PrintReads.

Sorry you ran into this, some of the recalibration steps can be unexpectedly memory hungry. Hope increasing memory helps work through the problem.

**Comment by pfujita** [comment]
Hi @chapmanb,

Thanks again for your prompt help (still blown away how responsive you guys manage to be!). We'll try this and see how it goes.
