### ISSUE TITLE
freebayes variant2 pipeline lost dbsnp id

### ISSUE THREAD

**Issue by semal** [chapmanb/bcbio-nextgen#1943]
freebayes variant2 pipeline lost dbsnp id, I check the *-files.list, maybe the files list in the file is not right.

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issues. Could you provide a bit more details to help with debugging?

- What genome are you variant calling against?
- What version of bcbio do you have? The latest should include dbsnp 150.
- Do you have GATK installed? The FreeBayes calling uses the non-free parts of GATK to provide post-calling annotation and dbSNP IDs? We could swap to only add dbSNP IDs and not other annotations if GATK is not available if this is the issue.

Thanks for the help digging into the problem.

**Comment by semal** [comment]
- I used build37.2 genome of NCBI
- 1.0.2 of bcbio, 149 dbSNP
- GATK is installed, I checked the command used in log, it works.

By the way, There are [position]-gatkann.vcf.gz which has dbSNP IDs and [position].vcf.gz files in freebayes output folder. But files list in *-files.list are [position].vcf.gz files.

**Comment by chapmanb** [comment]
Thank you for the additional details, this was really helpful to track down the problem. You're exactly right: we weren't passing the annotated files to the final concatenation step, leaving them behind. I pushed a fix to resolve this, and also fall back to vcfanno dbSNP annotation if GATK is not present. To fix an existing run you'll have to update bcbio to the latest development version, remove the freebayes directory and re-run in place. Thank you again for letting us know about the problem.
