### ISSUE TITLE
using gzipped reference fasta

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1945]
Hi Brad,

just a quick question. Is there a reason we're still using an uncompressed fasta reference? Are there still many tools left that can't handle compressed fasta?

Thanks
M

**Comment by chapmanb** [comment]
Matthias -- there is no reason other than needing to go through and ensure it works correctly with all of the tools that get passed the reference. It would be a lot of work to do so we haven't prioritized it yet. Thanks for starting this discussion.

**Comment by matthdsm** [comment]
Perhaps it might be worthwhile to check this out. A lot of tools have better performance with gzipped fasta + index vs plain fasta.

I'll see if i can find the time in the future to test this.
M

**Comment by matthdsm** [comment]
Proven to be not feasible, due to incompatibilities.
ref #1948 

M

**Comment by matthdsm** [comment]
Hi Brad,

Small update,
BWA seems to able to handle bgzipped references cleanly, even though this isn't mentioned in the manual. I think's it's safe to migrate bwa to the compressed reference once everything is in place.

Cheers
M

PS, I'll keep updating this thread as I find more compatible tools.

**Comment by ohofmann** [comment]
Thanks for doing this, Matthias, this is awesome.

**Comment by chapmanb** [comment]
Matthias -- thanks for digging into these. We shouldn't need the fasta reference for standard bwa usage (just the pre-built index) but happy to start swapping over logic to use compressed references when available for other tools that need it in the pipeline. If we're primarily using it then we can stop shipping uncompressed references and use thse directly. Thanks again.
