### ISSUE TITLE
/bin/bash: gtf_to_fasta: command not found

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#1949]
Hi there,
I'm currently doing some test runs of bcbio via IPython on our cluster and encountered the following error during execution of the RNAseq pipeline

bcbio-nextgen.log : https://gist.github.com/leiendeckerlu/1ff9a26488320a880449dc4c4ca792d0

bcbio-nextgen-commands.log: https://gist.github.com/leiendeckerlu/15a7e3979e1e74c62e572e2f5573dc59

Do you think it is a problem regarding the PATH that is not properly handed off to the subjobs bcbio starts?

Thanks a lot!

**Comment by roryk** [comment]
Hi @leiendeckerlu,

It looks like for gtf_to_fasta we're just assuming it is in your path, which is incorrect. If you add  /bioinformatics/bcbio/anaconda/bin/ to your PATH and rerun, it should pick it up without having to do anything extra. I'll fix this issue inside of bcbio as well.

**Comment by roryk** [comment]
Thanks! I fixed this so it shouldn't be a problem anymore in the next release.
