### ISSUE TITLE
Conda LcokError

### ISSUE THREAD

**Issue by swimtwin** [chapmanb/bcbio-nextgen#1956]
I'm very new to linux and installs such as this, sorry if this is a silly question, I do feel like I'm missing something obvious. I keep getting a conda lock error. I've tried installing multiple times, updating conda, and using conda clean lock and keep getting this error, shown below. I am following the install instructions outlined

The following packages will be DOWNGRADED due to dependency conflicts:

    fontconfig:                        2.12.1-4                   conda-forge --> 2.11.1-6          conda-forge
    freetype:                          2.7-1                      conda-forge --> 2.6.3-1           conda-forge
    icu:                               58.1-1                     conda-forge --> 56.1-4            conda-forge
    libxml2:                           2.9.4-4                    conda-forge --> 2.9.4-3           conda-forge
    matplotlib:                        2.0.2-np112py27_0          conda-forge --> 2.0.0-np112py27_1 conda-forge
    pillow:                            4.1.1-py27_0               conda-forge --> 4.0.0-py27_1      conda-forge
    pyqt:                              5.6.0-py27_2               conda-forge --> 4.11.4-py27_2     conda-forge
    qt:                                5.6.2-2                    conda-forge --> 4.8.7-3           conda-forge

Exceeded max retries, giving up

LockError: Lock error: Already locked: Lock error: 
LOCKERROR: It looks like conda is already doing something.
The lock [u'/usr/local/share/bcbio/anaconda/pkgs/nose-1.3.7-py27_2.pid6568.conda_lock'] was found. Wait for it to finish before continuing.
If you are sure that conda is not running, remove it and try again.
You can also use: $ conda clean --lock

Fatal error: local() encountered an error (return code 1) while executing '/usr/local/share/bcbio/anaconda/bin/conda install --quiet -y -c bioconda -c conda-forge -c r age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter ensembl-vep=88.* express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variant-effect-predictor=87 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli nodejs p7zip s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics=0.18.0 bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges=2.4.7 bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

Here is the current version of conda I have from conda info:

Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/jcutts/miniconda2  (writable)
    default environment : /home/jcutts/miniconda2
       envs directories : /home/jcutts/miniconda2/envs
                          /home/jcutts/.conda/envs
          package cache : /home/jcutts/miniconda2/pkgs
                          /home/jcutts/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jcutts/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Linux/4.8.0-36-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

Please let me know what I can do to solve this issue. Thank you.

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the detailed report. It sounds like your install may have died during a previous operation and needs to be cleaned up. bcbio installs its own anaconda python and it appears as if you're running `conda clean` on a different separate conda. If you do:
```
/usr/local/share/bcbio/anaconda/bin/conda clean --lock
```
and then re-run the install/upgrade command it should hopefully have resolved that problem and continue cleanly. Please feel free to re-open if you run into any other issues.

**Comment by swimtwin** [comment]
Wow, thanks for the quick response. I did what you said and the lock was removed:

/usr/local/share/bcbio/anaconda/bin/conda clean --lock
removing: /usr/local/share/bcbio/anaconda/pkgs/nose-1.3.7-py27_2.pid6568.conda_lock


But when installing I run into the exact same problem at the same place. One thing I forgot to mention, I had to use sudo to run:

python bcbio_nextgen_install.py /usr/local//share/bcbio --tooldir=/usr/local

When I don't use sudo, it won't write files because it says permission denied, shown below. Maybe using sudo is influencing this error that I keep running into?

python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --aligners bowtie2
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2017-05-26 07:25:20--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.24.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.24.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
requirements-conda.txt: Permission denied

Cannot write to ‘requirements-conda.txt’ (Success).
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 71, in install_conda_pkgs
    subprocess.check_call(["wget", "--no-check-certificate", REMOTES["requirements"]])
  File "/home/jcutts/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--no-check-certificate', 'https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt']' returned non-zero exit status 3

**Comment by chapmanb** [comment]
Thanks for following up with the additional details. You don't want to run the installer as sudo, so this could be contributing to the problem. That would be especially true if you've run both with and without sudo -- you might be ending up with some strange permission errors. I am confused how the lock gets removed yet you keep ending up stuck there -- are there any other errors you're seeing?

For the non-sudo user issue, that code is trying to download a file into `tmpbcbio-install` in your current working directory. Is it possible that directory has some permissions issue from a previous run? You could do `rm -rf tmpbcbio-install` (maybe needing sudo there) and then re-running to avoid that. Hope this fixes it for you.

**Comment by swimtwin** [comment]
sudo rm -rf tmpbcbio-install removed the files and I was able to run:

python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local \
> --aligners bowtie2
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2017-05-26 08:38:03--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.24.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.24.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

requirements-conda. 100%[===================>]      20  --.-KB/s    in 0s      

2017-05-26 08:38:03 (1.65 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /usr/local/share/bcbio/anaconda:
#
nomkl                     1.0                           0  
Fetching package metadata ...........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /usr/local/share/bcbio/anaconda:
#
bcbio-nextgen             1.0.3                    py27_0    bioconda
Installing data and third party dependencies
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 42, in main
    args.tooldir)
  File "bcbio_nextgen_install.py", line 125, in write_system_config
    shutil.copy(out_file, bak_file)
  File "/home/jcutts/miniconda2/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/home/jcutts/miniconda2/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/share/bcbio/galaxy/bcbio_system.yaml.bak20173826_0838'

but got this permission denied error

**Comment by chapmanb** [comment]
It sounds like you need to set correct permissions on your install directory so your standard user has the ability to install there. bcbio doesn't do any permission manipulation and requires you to take care of this prior to installation. It does this to avoid needing elevated permission levels for installation.

From your install location, it sounds like doing:
```
sudo chown -R $USER /usr/local/share/bcbio
```
will set this up to give your standard user permissions. Hope this helps.
