### ISSUE TITLE
Enable trimming also for variant2 analysis

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1958]
Rationale for this change: a too long read set up on a NextSeq 500 ended up getting a signiifcant (> 6%) percentage of adapters. I'm not sure how well BWA-MEM would handle those, and it would be nice to get them trimmed prior to analysis.

Unfortunately trimming with adapters is not supported in the variant2 analysis. Does it make sense to have such an option, or is it by design?

**Comment by mjafin** [comment]
We use the trimming facility in bcl2fastq for that, would that be an option for you?

**Comment by chapmanb** [comment]
Luca;
Thanks for the suggestion. cutadapt read trimming is not available in the variant calling pipeline if you update to the latest development version:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#read-trimming

Please let us know if you run into any problems using it. Thanks much.
