### ISSUE TITLE
IPython cluster may listen on the wrong IP address

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#1960]
Note: this may be a bug in ipython-cluster-helper instead.

Some of my nodes have 2 network cards:

- Internal network: 192.168.0.0/24 for the cluster itself
- 192.168.5.0/24 which is a separate network for the distributed FS they are using

The two networks are not routed across each other (that was by design). However, the controller ends up listening on the wrong IP (192.168.5.xxx) and for this reason the cluster never finishes initializing correctly (because the other nodes can't connect to it).

**Comment by lbeltrame** [comment]
The reason lies in https://github.com/roryk/ipython-cluster-helper/blob/8a6a8a04bc50aea5d46cd1151992068b49c51669/cluster_helper/cluster.py#L89 which inconditionally gets the last IP among those available.

**Comment by chapmanb** [comment]
Luca;
Sorry about the issues. It is tricky to find the right interface in these sort of complicated network setups. Our workaround to the issue is just prior to the code you linked, the idea of having priority interfaces:

https://github.com/roryk/ipython-cluster-helper/blob/8a6a8a04bc50aea5d46cd1151992068b49c51669/cluster_helper/cluster.py#L72

What does ifconfig look like on one of these nodes? Could we use this to prioritize the correct interface? Thanks for helping dig into the issue.

**Comment by lbeltrame** [comment]
```
ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:e0:81:c6:76:8d brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.247/24 brd 255.255.255.0 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2e0:81ff:fec6:768d/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 00:e0:81:c6:76:8c brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:e0:81:c6:7d:e2 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.249/24 brd 192.168.5.255 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::2e0:81ff:fec6:7de2/64 scope link 
       valid_lft forever preferred_lft forever
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:e0:81:c6:7d:e3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::2e0:81ff:fec6:7de3/64 scope link 
       valid_lft forever preferred_lft forever
```
(Ignore the ipv6 addresses, they are unused).

**Comment by lbeltrame** [comment]
The right one is on `eth0`, and the wrong one on `eth2`.

**Comment by chapmanb** [comment]
Luca -- thanks for the details. I pushed a solution I hope will fix this to pypi, so you can test with:
```
bcbio_pip install --upgrade ipython-cluster-helper
```
to get 0.5.5. This sorts the interfaces, preferring earlier ones (eth0) and hopefully selecting the right thing for your case. I'll also work on getting the bioconda package for this updated to include the fix. Thanks again for the report.
