### ISSUE TITLE
bcbio/variation/validate.py error

### ISSUE THREAD

**Issue by vandalum** [chapmanb/bcbio-nextgen#1963]
I ran into the following error using different installations and files:
 
 File "/software/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/validate.py", line 294, in _pick_best_quality_score
    if rec.info.get("VQSLOD") is not None:
  File "pysam/libcbcf.pyx", line 2642, in pysam.libcbcf.VariantRecordInfo.get (pysam/libcbcf.c:40036)
ValueError: Invalid header

I ran into this error using both the stable and development branch. The easiest way to reproduce it is using the test scripts run_tests.sh. It occurs when processing tests/data/automated/run_info-variantcall.yaml. See the attached log snipet for details.  

[log_snipet.txt](https://github.com/chapmanb/bcbio-nextgen/files/1037798/log_snipet.txt)

**Comment by chapmanb** [comment]
Guus;
Thanks much for the report and apologies about the issue. The latest release of pysam looks to be stricter about testing retrieval of INFO field values from a VCF when they're not present in the header. I pushed a fix to avoid the problem, so if you update to the latest development it should work cleanly again. Thank you again for reporting this and let us know if you run into any other issues.

**Comment by lbeltrame** [comment]
>  if you update to the latest development it should work cleanly again

While CNVkit was updated, it didn't bring in the needed commit. I ended up patching it manually.

**Comment by chapmanb** [comment]
Luca -- thanks for following up. Apologies, I pushed the fix to CNVkit as well but have not yet updated the bioconda package. I'm working on that and once it's in place both places should work cleanly. If you're stuck before that happens an alternative approach is to temporarily downgrade pysam:
```
bcbio_conda install -c conda-forge -c bioconda pysam=0.11.1
```
Sorry again about the issue and hope this helps.

**Comment by leiendeckerlu** [comment]
This error also occurs during runs with the exome_with_validation and cancer_tumor_normal sample test runs. Downgrade of pysam as described above solved the issue.

Thanks!

**Comment by chapmanb** [comment]
This should be fixed in the latest version of CNVkit from bioconda so an alternative fix is to do:
```
bcbio_conda install -c conda-forge -c bioconda cnvkit
```
Either will work to clean up a problem pysam/cnvkit install. Thanks much for following up.
