### ISSUE TITLE
Splitting BAMs into callable and non-callable blocks seems to skip alignments on callable and non-callable region boundaries

### ISSUE THREAD

**Issue by pfpjs** [chapmanb/bcbio-nextgen#1966]
Hi Brad,

Recently, I've had to rerun a few WES samples which were ran in a previous dev version of bcbio (roughly v0.9.8). Specifically, I had to take an IGV screenshot of a variant on the last exon of a gene (PCDH19, ChrX).

After rerunning the WES sample with bcbio, current dev version (updated sometime last week), I loaded up the BAM in IGV and, to my surprise, no reads were present in the coding region, and the previously identified variant was not present in the resulting VCF either.

Digging up in the intermediate BAM files I believe the issue here is that this particular region was "chosen" by bcbio as a breakpoint for parallel analysis blocks. For some reason, no reads from the "right-side" boundary of the callable block are present in the final merged output files.

The following screenshot can illustrate what I am saying much better than my explanation, where I highlighted the problematic region:
![pcdh19-missingex6](https://cloud.githubusercontent.com/assets/17730990/26628439/0c57c48a-45f6-11e7-9b62-e26537bd25a8.png)

The first track shown is the final BAM, the second track is the BAM generated by `bwa` (in the `work/align` dir), the third and fourth tracks are parallel analysis BAMs, and the fifth track is the non-callable region. You can see the alignment is shown in the output from `bwa` but it is not there anymore in any of the other intermediate BAMs, including the final generated BAM.

I ran this sample (and all others) with `realign: gatk` and `recalibrate: gatk`, I haven't tried turning them off to check if this issue is still present, however, I think even with these (now somewhat deprecated) options on it should work well, i.e., not skip any alignments.

Thanks for looking into this!

Cheers,
-- Paulo

**Comment by chapmanb** [comment]
Paulo;
Thanks for the report and apologies about the issues. Although I generally think you shouldn't need realignment for most analyses, we definitely shouldn't be breaking things by doing it. From the information you've provided it looks like bcbio is somehow confused about the callable/non-callable regions but I'm not sure why. Would you be able to share some additional information as a gist (https://gist.github.com/) so we can try to dig into what is going on?

- The calculated callable regions in `align/sample/sample-coverage.callable.bed`
- The `variant_region` file, if you're using one
- The analysis and no_analysis block files

You can subset to just this region on chrX. I'm just trying to get a sense of why it's making this decision to know how to explore more. Thanks again for the report and help debugging.

**Comment by pfpjs** [comment]
Brad,

Sure thing, I have uploaded the files you requested at a gist, subsetted to only ChrX:
https://gist.github.com/pfpjs/074cbe6fc6051d874ec928924df62538

If you need anything else let me know. Thank you for your help!

**Comment by chapmanb** [comment]
Paulo;
Thanks for the information. I dug into it and it looks from the IGV screenshot like the problem is this no-analysis block in your region of interest:
```
X       62858109        62863839
```
bcbio excludes this because it's not included in the `variant_regions` file you supplied. Here are the two regions you tell it to analyze in that BED file that flank this excluded region:
```
X       62857887        62858109        NM_015185_cds_0_0_chrX_62857908_r       0       -
X       62863839        62863948        NM_001173479_cds_1_0_chrX_62863860_r    0       -
```
As a result bcbio feels free to pick the region to split the analysis at, leading to the result you're seeing. If you'd like this included the best way is to adjust `variant_regions` to avoid excluding this section. In previous versions of bcbio we were a bit looser with `variant_regions` but this resulted in off-target calls so we've gotten stricter in excluding non-desired regions. Hope this helps get things working as expected for you.

**Comment by pfpjs** [comment]
Brad,
Thank you for your help. However, the problem region is not that one, but (roughly) the following one:

```
X	99550575	99552939
```

Here's a more zoomed in IGV screenshot, with the same tracks as the image above plus the `coverage.callable.bed` track:
![pcdh19-missingex6-zoomin](https://cloud.githubusercontent.com/assets/17730990/26732415/7579522a-47af-11e7-8127-c38370973cba.png)

You can see the highlighted region is in an analysis block, is callable, and included in `variant_regions`. I believe the issue here is that bcbio split processing into analysis and non-analysis blocks inside a callable region.

**Comment by chapmanb** [comment]
Paulo;
Thanks for following up with the additional details. It looks like bcbio is doing the right thing with assigning analysis and no-analysis regions -- it correctly breaks at the end of that variant regions file and assigns the no-analysis bit beyond it. However I see the issue that the reads seem to get lost in the `-ready.bam` file and in the sub region BAM file that spans the region.

I've been trying to reproduce this with minimal test cases but haven't been able to do so yet. Without that I've been reading the code trying to spot the bug or issue, and it would help a bit to be able to isolate it to either the realignment or recalibration step.

Is it possible to re-run the bamprep part of this analysis with `realign: true` and `recalibrate: true` set individually in two runs? If you could identify which of the steps causes issues (or both) for your sample I could hopefully be able to narrow it down some. I'll continue to read and try to spot the issue but happy for any help you could give to help debug and narrow this. Thanks so much for the patience and helping figure out the problem.

**Comment by pfpjs** [comment]
Brad,

Thank you for continuing looking into this. I too am continuing to look into this, as the skipped exon happened to have a pathogenic variant - so this can be a pretty big issue.

So far, I've tried rerunning (with both `realign: gatk` and `recalibrate: gatk`):

- With the latest Oracle JDK 1.8 (in case it was a OpenJDK issue with GATK - I hardcoded the Java dir in both the `gatk` and `gatk-framework` script) - no change
- With GATK 3.6 in case it was a bug in 3.7 - no change
- With both `realign: false` and `recalibrate: false` - the reads (and variant) are correctly shown (as expected since the BAM was not split)

As you suggested, I'm currently rerunning the pipeline with one sample with `realign: gatk` and the other with `recalibrate: gatk` (the same sample actually - which is the same as the shown above in IGV).

I'm thinking the issue here might be with GATK's PrintReads not outputting any reads towards the end of the analysis block, or something happening during the recalibration and/or realignment step which is so close to the boundary.

In any case, shouldn't bcbio avoid splitting analysis blocks inside callable regions and look instead to a nearby `LOW` or `NO_COVERAGE` regions?

**Comment by pfpjs** [comment]
So the test run has finished, and it seems to be a problem with the realignment step:

![pcdh19-recal-realn](https://user-images.githubusercontent.com/17730990/26842151-ba3e2df4-4ae3-11e7-8e0d-76fda03d0f59.png)

The first track is the bwa output, the second is with `realign: gatk` and `recalibrate: false` and the third is with `realign: false` and `recalibrate: gatk`.

**Comment by chapmanb** [comment]
Paulo;
Thanks much for following up and isolating the issue to the realignment steps. bcbio should be fine breaking in a callable region and this should not generally effect PrintReads (in preparing the inputs) or IndelRealigner. I've done some testing with minimal cases just now and can't make it lose reads like this. In terms of bcbio it breaks either in low/no coverage regions or when it falls off of `variant_regions` blocks. The later is the case here so it's justified breaking there and you'd need to expand your region in your BED file if you want to capture the higher coverage regions surrounding the exon you target.

On to debugging, my suggestion would be to pull out the commands in `log/bcbio-nextgen-commands.log` that create the original input file and the realigned file in this region, which should be named something like:
```
bamprep/Uni30315/X/Uni30315-X_62863839_99551893-prealign.bam
bamprep/Uni30315/X/Uni30315-X_62863839_99551893-prep.bam
```
The later file should still be present on the filesystem, the former would be deleted (to clean up space). If you could manually regenerate the first and see if the problem exists there that would isolate if it's something happening at the first or second step. Also it would be useful to know what is in the `*-realign.intervals` file located in this directory. Is there anything unusual about that file?

Thanks for the help debugging and helping further isolate the problem.

**Comment by pfpjs** [comment]
Hi Brad,

Apologies for taking some time to continue debugging this issue, but I think I found the culprit.

So I've regenerated the `Uni30315-realn-X_62863839_99551893-prealign.bam` intermediate file (the realignment-only test run), opened it up in IGV and, amazingly, the reads were there! This was not making any sense, so I also regenerated the intermediate files of the recalibration-only test run (PrintReads with BQSR). I then noticed the GATK-generated `.bai` index files, and, without thinking much, removed them, and reindexed them with `samtools index -@ 1 <bam>`. I then opened up both BAMs on IGV, and lo and behold, both BAMs were missing reads in the problem region. I deleted the indexes again, regenerated them, using `sambamba index` this time, reloaded the files in IGV and the reads were there again!

So it seems to be a faulty BAM index. I have been able to reproduce the issue consistently with the following commands (using the same BAM):

- `samtools index -@ 1 <bam>` - reads are missing (as above)
- `samtools index -@ 2 <bam>` - reads are missing
- `sambamba index <bam>` - reads are present
- `samtools index <bam>` - reads are present
- `sambamba index -t 1 <bam>` - reads are present

I have tested this with the same results on two different servers, one with samtools 1.4.1 and the other with samtools 1.4, and I think it explains what we're seeing.

Are you able to reproduce the issue with the commands above?

**Comment by pfpjs** [comment]
A small update: With the latest samtools 1.4.1-dev and htslib 1.4.1-dev (cloned just now from github) I still see the same problem. I didn't test samtools 1.3.1 but it should work well, as this probably has to do with the multithreading support introduced in 1.4.

**Comment by chapmanb** [comment]
Paulo;
Yikes, thanks for catching this. I can't reproduce this here but I'm quite worried if standard multithreaded index leaves sections unreadable. Are you able to share the BAM file that causes this for you? If so, I can confirm I can reproduce, and we should then raise an issue with the samtools team. Within bcbio we can move back to sambamba indexing inside bcbio until the issue is resolved. Thanks again for tracking down the problem.

**Comment by pfpjs** [comment]
I've created a reproducible test which indexes the same BAM with `samtools` and `sambamba`, single and multi-threaded:

![bamindex-test](https://user-images.githubusercontent.com/17730990/26973071-7c377d64-4d0c-11e7-8a80-e6a28c88be63.png)

Any idea where I can share the BAM? It's ~55Mb, plus a small shell script. I tried Gist but it doesn't like binary files.

**Comment by chapmanb** [comment]
Paulo -- thanks so much. Do you have Dropbox or Google Drive? If you can share with me I'll replicate, upload to S3 and handle making a reproducible test case. You could also e-mail it to me directly if you don't have way to share it. My e-mail is in my GitHub profile. Thanks again.

**Comment by pfpjs** [comment]
Whoops, of course, Google Drive!

Here you go:
https://drive.google.com/open?id=0ByFgFvT1pt9wYzk0WEJKSFpVU1U

There you'll find the BAM, plus a shell script to create copies of the BAM and index them separately using `samtools` and `sambamba`, both single and multi-threaded, which you can then open up in IGV and hopefully get an image similar to the one above.

I've run this script, reproducibly, on an Ubuntu 14.04 server, an Ubuntu 16.04 server and on my MBP laptop (OSX 10.12.5, with `samtools` 1.4.1 installed from bioconda), all with the same results.

**Comment by chapmanb** [comment]
Paulo -- thanks for this. I can reproduce and put together a use case that demonstrates it from the commandline. I've raised an issue with samtools to hopefully get it fixed there. In the short term I swapped back to using sambamba indexing (the older approach). Thank you so much for tracking this down and helping identify the underlying issue. I hope updating and regenerating bai files will now give you correct results.

**Comment by pfpjs** [comment]
Many thanks Brad! I've updated and am now continuing the previous runs. Unfortunately, because of the faulty BAM indexes, I've decided to continue the runs from the bwa output - the `-ready.bam` files are in fact missing the reads, possibly because of intermediate tools which used the bad indexes.

In the future I'll switch off `realign` and `recalibrate`.
