### ISSUE TITLE
Cannot find citation

### ISSUE THREAD

**Issue by elenimijalis** [chapmanb/bcbio-nextgen#1967]
I used BCBio in a tool I have written up for publication. Is there a citation available I can use (perhaps specifically for BCBio-GFF)?

**Comment by chapmanb** [comment]
Eleni;
Congratulations on the paper submission. We're incredibly happy bcbio helped in your research. We don't have a formal citation for bcbio and generally just ask that you reference the website and version of code used. Hope this works for you.
