### ISSUE TITLE
Re-Deriving Ensemble Mutations w/ different numpass parameter

### ISSUE THREAD

**Issue by RiNiculous93** [chapmanb/bcbio-nextgen#1977]
Hey, 

I've used ensemble mutation calling to call mutations which appear in 2/5 individual callers. I'm now wanting to go back and re-call those which appear in 3/5, 4/5, 5/5, and 1/5. Is there a way of doing this without doing the whole mutation-calling step again, but using the individual called VCF files as input? What would the yaml for this look like? I've attached the basic format of the one I'm using.

details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    recalibrate: gatk
    realign: gatk
    effects: vep
    platform: illumina
    variantcaller: [mutect, mutect2, freebayes, vardict, varscan]
    ensemble:
      numpass: 2
  analysis: variant2
  description: p145-normal
  files:
    - p145_N_1.fastq.gz
    - p145_N_2.fastq.gz
  genome_build: hg38-noalt
  metadata:
    batch: p145
    phenotype: normal
- algorithm:
    aligner: bwa
    mark_duplicates: true
    recalibrate: gatk
    realign: gatk
    effects: vep
    platform: illumina
    variantcaller: [mutect, mutect2, freebayes, vardict, varscan]
    ensemble:
      numpass: 2
  analysis: variant2
  description: p145-tumor
  files:
    - p145_T_1.fastq.gz
    - p145_T_2.fastq.gz
  genome_build: hg38-noalt
  metadata:
    batch: p145
    phenotype: tumor
fc_date: 'Jun-17'
fc_name: p145_T-N_Calling
upload:
  dir: ./

Best wishes, 

Nick

**Comment by chapmanb** [comment]
Nick;
Thanks for the question. We don't have a clean way to re-run the ensemble calling from within bcbio, unless you've saved the work directory. If you have the work directory, then you can manually remove the `ensemble` directory, adjust the YAML settings, and then re-run producing a new ensemble callset.

Alternatively, you could run with with the minimum numpass you want (1 in this case) and then do custom post-filtering for higher sets using the `CALLERS` attribute in the `INFO` field. That's probably the easiest way to avoid a lot of manual re-running and editing.

Hope this helps.

**Comment by RiNiculous93** [comment]
Hey, 

Thanks a lot, I'll give it a go.
