### ISSUE TITLE
debugging of VEP upgrade

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1978]
Hello!

Could you please help me to debug VEP upgrade?

I'm upgrading with
```
bcbio_nextgen.py upgrade -u development --tools --datatarget vep --genomes GRCh37
```
It downloads cloudbiolinux, and in
cloudbiolinux/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
there are two VEPs:
- ensembl-vep=89.*
- variant-effect-predictor=87

It installs both to bcbio/anaconda/bin:
vep -> ../share/ensembl-vep-89.1-1/vep
vep_convert_cache -> ../share/ensembl-vep-89.1-1/vep_convert_cache
vep_convert_cache.pl -> ../share/variant-effect-predictor-87-0/vep_convert_cache.pl
vep_install -> ../share/ensembl-vep-89.1-1/vep_install
vep_install.pl -> ../share/variant-effect-predictor-87-0/vep_install.pl

Maybe the old version should be removed?

Then it comes to VEP data.
It downloads ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh37.tar.gz

and gets stuck with
```
wget -c ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh37.tar.gz
--2017-06-14 14:03:01--  ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh37.tar.gz
           => “homo_sapiens_merged_vep_89_GRCh37.tar.gz”
Resolving ftp.ensembl.org... 193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/release-89/variation/VEP ... done.
==> SIZE homo_sapiens_merged_vep_89_GRCh37.tar.gz ... 6399176382
==> PASV ... done.    ==> REST 6399176382 ...
```
The same problem when running wget from CLI.

Any ideas why?
The other files from /pub/release-89/variation/VEP work well.

Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for testing these. We purposely install both the old and new VEP right now since the development version uses the new VEP and the last release uses the old. We'll plan to no longer install both on the next release.

For your problem, are you seeing an error message? It looks like it might be working on reformatting/bgzipping the cache which takes a long time and doesn't produce any messages. Is it possible it's still working and not yet finished?

**Comment by naumenko-sa** [comment]
Thanks Brad!

I see no error messages. Finally it wrote 
```
2017-06-14 15:59:07 (497 KB/s) - “homo_sapiens_merged_vep_89_GRCh37.tar.gz” saved [6399176382]
```
And switched to the another download:
```
--2017-06-14 16:57:42--  ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh38.tar.gz
           => “homo_sapiens_merged_vep_89_GRCh38.tar.gz”
```
bcbio/genomes/Hsapiens/GRCh37/vep/homo_sapiens_merged does not contain 89_GRCh37 folder,
and the file homo_sapiens_merged_vep_89_GRCh37.tar.gz is gone.
So no decompressing occurred.

I will try to reproduce it one more time - maybe just some random network issues,
but for now it looks like the command 
```
wget -c  ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh37.tar.gz
```
does not return a value (from CLI as well), and the installer, after waiting for timeout,
switches to another file.

88_GRCh37 behaved well.

BTW why the installer tries to download VEP for GRCh38? I thought that --genomes GRCh37 should force it to download GRCh37 only?

Sergey

**Comment by chapmanb** [comment]
Sergey;
Glad it worked even if it's slower than we'd like. It sounds like its doing the right thing but just not reporting progress as it works. If you're doing an upgrade bcbio will upgrade genomes for everything installed, not just for the `--genomes` specified on the command line. The general idea is that the upgrade gives you correct data files across all your installed genomes. If you just want to upgrade, you don't need to include `--genomes` as it stores details about everything previous installed. Hope this helps explain everything.

**Comment by naumenko-sa** [comment]
Hi Brad!

Unfortunately, it is not working.
```
bcbio_nextgen.py upgrade -u skip --data --datatarget vep --genomes GRCh37
```
(I have recently upgraded with -u development --tools).

It downloads ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh37.tar.gz to 
bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/txtmp

and then switches to GRCh38. No unpacking happens, 
bcbio/genomes/Hsapiens/GRCh37/vep/homo_sapiens_merged is empty.

Not a network issue - I tried 3 times.

```
--2017-06-15 14:27:21--  ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh37.tar.gz
           => “homo_sapiens_merged_vep_89_GRCh37.tar.gz”
Resolving ftp.ensembl.org... 193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/release-89/variation/VEP ... done.
==> SIZE homo_sapiens_merged_vep_89_GRCh37.tar.gz ... 6399176382
==> PASV ... done.    ==> RETR homo_sapiens_merged_vep_89_GRCh37.tar.gz ... done.
Length: 6399176382 (6.0G) (unauthoritative)


2017-06-15 14:56:24 (3.50 MB/s) - “homo_sapiens_merged_vep_89_GRCh37.tar.gz” saved [6399176382]

--2017-06-15 14:56:34--  ftp://ftp.ensembl.org/pub/release-89/variation/VEP/homo_sapiens_merged_vep_89_GRCh38.tar.gz
           => “homo_sapiens_merged_vep_89_GRCh38.tar.gz”
Resolving ftp.ensembl.org... 193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:21... connected.
```

Any ideas how to trace the error?

Thanks,
Sergey

**Comment by naumenko-sa** [comment]
Then it continued with mouse genome, 
bcbio/genomes/Hsapiens/hg38/vep/homo_sapiens_merged is empty as GRCh37
```
2017-06-15 17:57:02 (886 KB/s) - “homo_sapiens_merged_vep_89_GRCh38.tar.gz” saved [7124356527]

--2017-06-15 17:57:19--  ftp://ftp.ensembl.org/pub/release-89/variation/VEP/mus_musculus_vep_89_GRCm38.tar.gz
           => “mus_musculus_vep_89_GRCm38.tar.gz”
Resolving ftp.ensembl.org... 193.62.193.8
Connecting to ftp.ensembl.org|193.62.193.8|:21... connected.
```

**Comment by naumenko-sa** [comment]
So in bcbio.variation.effects.prep_vep_cache
```
subprocess.check_call...
```
works for wget - there are messages in the output, but 
```
do.run...
```
does not, because there is no message "Prepare VEP directory ..." in the output.

**Comment by chapmanb** [comment]
Sergey;
Thanks for digging more into this. I'll need to spend some time debugging to try and replicate/fix. I had an update work recently but not sure what is going wrong here. As an immediate idea, do you have the latest development code? There were some fixes for this that went in a couple of days ago. @matthdsm -- do you have any other thoughts on what might be going on here? Thanks much.

**Comment by naumenko-sa** [comment]
I've tried to upgrade with -u development, did not work either. I give up at this point, will try to re-install bcbio from scratch.

**Comment by naumenko-sa** [comment]
Clean install has helped.

**Comment by chapmanb** [comment]
Thanks for following up and glad to hear that a clean installation worked. If you can isolate the underlying problem happy to try and fix it to avoid other folks getting tripped up on the same issues. Thanks as always for the work debugging.

**Comment by naumenko-sa** [comment]
My pleasure, as the pipeline solves (almost) all my problems. I've deleted old files, so I could not reproduce this case. The only thing I can suggest, is to introduce a sort of cleaning procedure for bcbio. After a year of usage and permanent upgrade, I had so many copies of different versions of VEP caches. It takes spaces, and maybe VEP directory becomes very heavy even on our super resilient file system. It might slow things down, and even lead to timeouts. It is a theory, not a proved causality though. But I'd be happy to have something like bcbio_nextgen.py upgrade --cleanup, which would delete old VEP/dbNSFp caches.

**Comment by matthdsm** [comment]
Hi Brad, Sergey,

I've no idea what's wrong with VEP or the caches. We're still struggling too to get VEP to work as it should. I'm still trying to work out what the issue is, but the program just keeps failing altogeher when we run the pipeline.

Anyway, I second the idea of implementing a `cleanup` option. Over time, it is possible there's a huge accumulation of unused reference data.

Cheers
M

**Comment by chapmanb** [comment]
Matthias and Sergey;
Thanks for the suggestions. Older data files shouldn't influence runs so I don't see that contributing beyond using extra disk space. Sorry to not have a better clue what was going on. In general I prefer to avoid automating deletion, especially recursive directory removes, since it's too easy to mess up and make a mistake on. If either of you want to work on this happy to incorporate it. Thanks again for following up and all the suggestions and glad things are working now.
