### ISSUE TITLE
Missleading error message: java not found on PATH. Java 1.7 required for MuTect and GATK < 3.6.

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#1979]
The following error message is (incorrectly) shown if Mutect is not installed but requested as variant caller. 
Indeed, Java is correctly installed and properly working with Mutect2, so a more descriptive error message that specifically mentions looking at a proper Mutect installation might be useful.

> Unexpected error
> Traceback (most recent call last):
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
>     yield config
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 480, in organize_samples
>     return ipython.zip_args(apply(run_info.organize, *args))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 81, in organize
>     out = _add_provenance(out, dirs, config, add_provenance)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 94, in _add_provenance
>     versioncheck.testall(items)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/versioncheck.py", line 85, in testall
>     "\n".join(msgs))
> OSError: Program problems found. You can upgrade dependencies with:
> bcbio_nextgen.py upgrade -u skip --tooldir=/usr/local
> java not found on PATH. Java 1.7 required for MuTect and GATK < 3.6.

**Comment by chapmanb** [comment]
Sorry about the problem. MuTect requires an externally installed Java 1.7 which it appears is not available on your PATH. MuTect2 and other callers use Java 1.8, which we install along with bcbio. There is an initial sanity check for this, which is the error you're seeing here. If you make Java 1.7 available then it should get past this and will give an error message like:
```
ValueError: Could not find jar muTect
```
when you try to actually run MuTect later. So there are likely two issues in your case and we catch the first initially. Hope this helps with getting things running.
