### ISSUE TITLE
ValueError: could not convert string to float: NA12878

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#1980]
Running the structural variant calling test pipeline, I get the following error message:

> WARNING 2017-06-15 11:05:40,367 metasv.sv_interval   Skipping Record(CHROM=Y, POS=9999257, REF=N, ALT=[< DEL >]) due to large size
> WARNING 2017-06-15 11:05:40,370 metasv.sv_interval   Skipping Record(CHROM=Y, POS=17700015, REF=N, ALT=[< DEL >]) due to large size
> INFO 2017-06-15 11:05:40,386 metasv.sv_interval   Loading SV intervals from /bcbio_testruns/structural_variant_calling/NA12878-sv-eval/work/structural/NA12878/wham/NA12878-wham-NA12878-effects.vcf.gz
> Traceback (most recent call last):
>   File "/bcbio/local/share/bcbio/anaconda/bin/run_metasv.py", line 148, in <module>
>     sys.exit(run_metasv(args))
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/metasv/main.py", line 151, in run_metasv
>     svs_to_report=args.svs_to_report, maxsvlen=args.maxsvlen)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/metasv/vcf_utils.py", line 74, in load_intervals
>     for vcf_record in vcf_reader:
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 572, in next
>     info = self._parse_info(row[7])
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 394, in _parse_info
>     val = self._map(float, vals)
>   File "/bcbio/local/share/bcbio/anaconda/lib/python2.7/site-packages/vcf/parser.py", line 360, in _map
>     for x in iterable]
> ValueError: could not convert string to float: NA12878
> ' returned non-zero exit status 1

Is here the sample name making problems? I at least didn't change it after downloading the files as described here: http://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#structural-variant-calling-whole-genome-na12878-50x

**Comment by chapmanb** [comment]
Thanks much for the report and sorry about the problem. This was a bug in the WHAM generated VCF headers and we hadn't updated the conda package to include the fix. I finalized this (after a lot of fighting with the build machinery on bioconda) and if you update (`bcbio_nextgen.py upgrade --tools`) it will grab the latest WHAM which avoids this problem. You'll need to remove the generated WHAM files, then a re-run should produce versions that work cleanly. Thanks again for letting us know about the issue.
