### ISSUE TITLE
ERROR: No cache found for homo_sapiens_merged, version 87

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#1981]
During VEP annotation, I get the following error (bcbio-nextgen.log):

https://gist.github.com/leiendeckerlu/ad795a26dcfc914e3ddfed2ab1c329cc

Maybe related to this https://github.com/chapmanb/bcbio-nextgen/issues/1978 ?

I'm especially wondering why it worked for mutect2 and vardict but failed for varscan?

As always, thanks a lot!

**Comment by chapmanb** [comment]
Sorry about the issues with running VEP. I'd recommend updating to the latest development version (`bcbio_nextgen.py upgrade -u development`) if you want to use vep, as it switches to use the newer recommended script from Ensembl. I believe you're running into an issue where you're using the older script (version 87) but only have databases for the newer (version 89). I'm not sure how this could work for some samples and not others -- is it possible the working callers/samples have no variants so VEP doesn't actually get called?

Sorry about the confusion as we're transitioning to the newer VEP infrasucture. Hope this helps.

**Comment by naumenko-sa** [comment]
Hi!
Same error for me on grch37 and hg38: a fresh install of the stable version (1.0.3) installs VEP89 cache only, but the script wants VEP87, so upgrade to the development version should help.
Sergey
