### ISSUE TITLE
Novartis' PISCES

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#1983]
So it seems [Matt](https://github.com/mdshw5) from Novartis has a Python 3 package called [PISCES](http://www.openwetware.org/images/6/6b/2017-02-16_BIG-meeting.pdf) that implements a `salmon`-based RNA-Seq quantitation and QC workflow; they have a couple of nice additional options like flexible PDX references and visualizations and most importantly it seems to be able to do QC without having to generate full alignments. 

@roryk, could you have a look? I know you have built much of that yourself in bcbio and that's super valuable - I was just wondering if it could make sense to make use of external innovation and maintenance. The upcoming CWL conversion will require touching much of the RNA-Seq code anyway, I could imagine. 

@mdshw5, would you like to chime in as well concerning availability?

**Comment by roryk** [comment]
Hi Sven-Eric,

Thanks for the heads up, PISCES looks great and dropping doing whole genome alignments for QC would be helpful. At the very least maybe we can snag the ideas for doing that from Matt's work. You can spit out mappings as a SAM file from Salmon, I just haven't tried running them through QC tools to see if they give reasonable looking results.

**Comment by schelhorn** [comment]
Great; doing QC on the `salmon` outputs would be super useful indeed. Let's see if `pisces` becomes available in source.

**Comment by mdshw5** [comment]
Hey there. Sorry for the delay. I'm writing up a description of PISCES, and expect to have a manuscript and code available before Genome Informatics in November. The package is hosted in a private Bitbucket repo right now, but if there's some interest in doing an early release I can see about the process for moving the project to open source more quickly.

**Comment by schelhorn** [comment]
That sounds great, @mdshw5. @roryk, would it make sense for you time/interest-wise to look at the sources before November?

**Comment by schelhorn** [comment]
I'm closing this since bcbio (or rather, @roryk) seems to be more likely to go with `kallisto`+ pseudo-BAMs instead.

**Comment by mdshw5** [comment]
Hey there. I’ll be presenting a poster this week at Genome Informatics. PISCES development has been slow (it’s just me and I have to manage to do some actual data analysis and project support too :)) but I’d be interested in discussing our methods. The project code is moving through our open source review and will be available after the conference. I’ll say that after using a quasialignment based QC I’ve fallen back on doing a downsampled alignment for most QC measures. This is just for pragmatic reasons since speed is comparable and I’m not sure how best to estimate information about genomic mapping metrics with these methods.

**Comment by roryk** [comment]
Awesome, will your poster be online anywhere? Excited to see what good ideas you have. Thanks for sharing that information about the quasialignments and QC that's the reason why we've kept STAR alignment, just for those metrics. Downsampling is a really good idea-- we do that already for some of the metrics, but not prior to STAR alignment. How far are you downsampling?
