### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '../rnaseq/ref-transcripts.gtf'

### ISSUE THREAD

**Issue by mchimenti** [chapmanb/bcbio-nextgen#1984]
Trying to run RNA-Seq on mouse mm9 samples.  Getting this error (below, last few hundred lines for brevity) when the workflow kicks off.  

Running with this config on each sample.  mm9 is installed: 
details:
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
  analysis: RNA-seq
  description: '18871'
  files:
  - /Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/18871.fastq.gz
  genome_build: mm9

Any insight would be appreciated.  Thanks.  

Last ~100 lines of traceback: 
****************

/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py in get_qc_tools(data={'analysis': 'RNA-seq', 'config': {'algorithm': {'adapters': ['truseq', 'polya'], 'align_split_size': None, 'aligner': 'star', 'archive': [], 'coverage_interval': None, 'mark_duplicates': True, 'nomap_split_size': 250, 'nomap_split_targets': 200, 'num_cores': 1, 'qc': [], ...}, 'bcbio_system': '/Shared/Bioinformatics/data/bcbio/galaxy/bcbio_system.yaml', 'galaxy_config': 'universe_wsgi.ini', 'log_dir': '/Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/work/log', 'resources': {'default': {'cores': 16, 'jvm_opts': ['-Xms750m', '-Xmx3500m'], 'memory': '3G'}, 'dexseq': {'memory': '10g'}, 'express': {'memory': '8g'}, 'gatk': {'dir': '/Shared/Bioinformatics/data/bcbio/toolplus/gatk/3.6-0-g89b7209', 'jvm_opts': ['-Xms4g', '-Xmx8g']}, 'macs2': {'memory': '8g'}, 'mutect': {'dir': '/Shared/Bioinformatics/data/bcbio/toolplus/mutect/1.1.7'}, 'qualimap': {'memory': '4g'}, 'seqcluster': {'memory': '8g'}, 'snpeff': {'jvm_opts': ['-Xms1g', '-Xmx4g']}}}, 'description': '18871', 'dirs': {'config': '/Shared/Bioinformatics/data/bcbio/galaxy', 'fastq': None, 'flowcell': None, 'galaxy': '/Shared/Bioinformatics/data/bcbio/galaxy', 'work': '/Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/work'}, 'files': ['/Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/18871.fastq.gz'], 'genome_build': 'mm9', 'genome_resources': {'rnaseq': {'transcriptome_index': {'tophat': '../rnaseq/tophat/mm9_transcriptome.ver'}, 'transcripts': '../rnaseq/ref-transcripts.gtf', 'transcripts_mask': '../rnaseq/ref-transcripts-mask.gtf'}, 'variation': {'cosmic': None, 'dbsnp': None}, 'version': 7}, 'lane': '1', 'metadata': {'batch': None, 'phenotype': ''}, 'name': ['', '18871'], ...})
     83     if any([tool in dd.get_tools_on(data)
     84             for tool in ["qualimap", "qualimap_full"]]):
     85         to_run.append("qualimap")
     86     if analysis.startswith("rna-seq"):
     87         if "qualimap" not in dd.get_tools_off(data):
---> 88             if gtf.is_qualimap_compatible(dd.get_gtf_file(data)):
        data = {'analysis': 'RNA-seq', 'config': {'algorithm': {'adapters': ['truseq', 'polya'], 'align_split_size': None, 'aligner': 'star', 'archive': [], 'coverage_interval': None, 'mark_duplicates': True, 'nomap_split_size': 250, 'nomap_split_targets': 200, 'num_cores': 1, 'qc': [], ...}, 'bcbio_system': '/Shared/Bioinformatics/data/bcbio/galaxy/bcbio_system.yaml', 'galaxy_config': 'universe_wsgi.ini', 'log_dir': '/Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/work/log', 'resources': {'default': {'cores': 16, 'jvm_opts': ['-Xms750m', '-Xmx3500m'], 'memory': '3G'}, 'dexseq': {'memory': '10g'}, 'express': {'memory': '8g'}, 'gatk': {'dir': '/Shared/Bioinformatics/data/bcbio/toolplus/gatk/3.6-0-g89b7209', 'jvm_opts': ['-Xms4g', '-Xmx8g']}, 'macs2': {'memory': '8g'}, 'mutect': {'dir': '/Shared/Bioinformatics/data/bcbio/toolplus/mutect/1.1.7'}, 'qualimap': {'memory': '4g'}, 'seqcluster': {'memory': '8g'}, 'snpeff': {'jvm_opts': ['-Xms1g', '-Xmx4g']}}}, 'description': '18871', 'dirs': {'config': '/Shared/Bioinformatics/data/bcbio/galaxy', 'fastq': None, 'flowcell': None, 'galaxy': '/Shared/Bioinformatics/data/bcbio/galaxy', 'work': '/Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/work'}, 'files': ['/Shared/Bioinformatics/data/mchiment/hartylab/rnaseq_project_june2017/merged/18871.fastq.gz'], 'genome_build': 'mm9', 'genome_resources': {'rnaseq': {'transcriptome_index': {'tophat': '../rnaseq/tophat/mm9_transcriptome.ver'}, 'transcripts': '../rnaseq/ref-transcripts.gtf', 'transcripts_mask': '../rnaseq/ref-transcripts-mask.gtf'}, 'variation': {'cosmic': None, 'dbsnp': None}, 'version': 7}, 'lane': '1', 'metadata': {'batch': None, 'phenotype': ''}, 'name': ['', '18871'], ...}
     89                 to_run.append("qualimap_rnaseq")
     90             else:
     91                 logger.debug("GTF not compatible with Qualimap, skipping.")
     92     if analysis.startswith("smallrna-seq"):

...........................................................................
/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py in is_qualimap_compatible(gtf='../rnaseq/ref-transcripts.gtf')
    303     Qualimap needs a very specific GTF format or it fails, so skip it if
    304     the GTF is not in that format
    305     """
    306     if not gtf:
    307         return False
--> 308     db = get_gtf_db(gtf)
        db = undefined
        gtf = '../rnaseq/ref-transcripts.gtf'
    309     def qualimap_compatible(feature):
    310         gene_id = feature.attributes.get('gene_id', [None])[0]
    311         transcript_id = feature.attributes.get('transcript_id', [None])[0]
    312         exon_number = feature.attributes.get('exon_number', [None])[0]

...........................................................................
/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py in get_gtf_db(gtf='../rnaseq/ref-transcripts.gtf', in_memory=False)
     40     db_file = gtf + ".db"
     41     if file_exists(db_file):
     42         return gffutils.FeatureDB(db_file)
     43     db_file = ":memory:" if in_memory else db_file
     44     if in_memory or not file_exists(db_file):
---> 45         infer_extent = guess_infer_extent(gtf)
        infer_extent = undefined
        gtf = '../rnaseq/ref-transcripts.gtf'
     46         db = gffutils.create_db(gtf, dbfn=db_file,
     47                                 infer_gene_extent=infer_extent)
     48     if in_memory:
     49         return db

...........................................................................
/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py in guess_infer_extent(gtf_file='../rnaseq/ref-transcripts.gtf')
     16     """
     17     _, ext = os.path.splitext(gtf_file)
     18     tmp_out = tempfile.NamedTemporaryFile(suffix=".gtf", delete=False).name
     19     with open(tmp_out, "w") as out_handle:
     20         count = 0
---> 21         in_handle = open(gtf_file) if ext != ".gz" else gzip.open(gtf_file)
        in_handle = undefined
        gtf_file = '../rnaseq/ref-transcripts.gtf'
        ext = '.gtf'
     22         for line in in_handle:
     23             if count > 1000:
     24                 break
     25             out_handle.write(line)

IOError: [Errno 2] No such file or directory: '../rnaseq/ref-transcripts.gtf'

**Comment by roryk** [comment]
Hi Michael,

Is the RNA-seq data for mm9 installed? It looks like that might not have been installed. It should be under /Shared/Bioinformatics/data/bcbio/genomes/Mmusculus/mm9/rnaseq I think based on the traceback. 

mm10 has been out for a while and is better to use, you might want to consider switching over to that as well.

**Comment by mchimenti** [comment]
Thanks roryk.  Yes, that was it.  Now however, I am getting this.  Some problem with the SQLite database? 

...........................................................................
/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py in gtf_to_bed(gtf='/Shared/Bioinformatics/data/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf', alt_out_dir='/Shared/Bioinformatics/data/mchiment/hartylab/rn...ject_june2017/merged/work/inputs/data/annotations')
     64         else:
     65             out_file = os.path.join(alt_out_dir, os.path.basename(out_file))
     66     if file_exists(out_file):
     67         return out_file
     68     with open(out_file, "w") as out_handle:
---> 69         db = get_gtf_db(gtf)
        db = undefined
        gtf = '/Shared/Bioinformatics/data/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf'
     70         for feature in db.features_of_type('transcript', order_by=("seqid", "start", "end")):
     71             chrom = feature.chrom
     72             start = feature.start - 1
     73             end = feature.end

...........................................................................
/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/gtf.py in get_gtf_db(gtf='/Shared/Bioinformatics/data/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf', in_memory=False)
     37     """
     38     create a gffutils DB
     39     """
     40     db_file = gtf + ".db"
     41     if file_exists(db_file):
---> 42         return gffutils.FeatureDB(db_file)
        db_file = '/Shared/Bioinformatics/data/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf.db'
     43     db_file = ":memory:" if in_memory else db_file
     44     if in_memory or not file_exists(db_file):
     45         infer_extent = guess_infer_extent(gtf)
     46         db = gffutils.create_db(gtf, dbfn=db_file,

...........................................................................
/Shared/Bioinformatics/data/bcbio/anaconda/lib/python2.7/site-packages/gffutils/interface.py in __init__(self=<gffutils.interface.FeatureDB object>, dbfn='/Shared/Bioinformatics/data/bcbio/genomes/Mmusculus/mm10/rnaseq/ref-transcripts.gtf.db', default_encoding='utf-8', keep_order=False, pragmas={'journal_mode': 'MEMORY', 'main.cache_size': 10000, 'main.page_size': 4096, 'synchronous': 'NORMAL'}, sort_attribute_values=False, text_factory=<type 'cell'>)
    125         # TODO: this is a good place to check for previous versions, and offer
    126         # to upgrade...
    127         c.execute(
    128             '''
    129             SELECT version, dialect FROM meta
--> 130             ''')
    131         version, dialect = c.fetchone()
    132         self.version = version
    133         self.dialect = helpers._unjsonify(dialect)
    134
OperationalError: database is locked

**Comment by roryk** [comment]
Hi Michael,

This can happen because sqlite3 doesn't play well over NFS setups. https://github.com/chapmanb/bcbio-nextgen/issues/1123#issuecomment-160821592 has a workaround that has worked in the past-- do you think you could get your sysadmin to mount that filesystem with the nolock option on?

**Comment by mchimenti** [comment]
Will work on it with him thanks.  Will open new issue if needed at later time.
