### ISSUE TITLE
Pysam and Htslib errors after Bcbio fresh install

### ISSUE THREAD

**Issue by amizeranschi** [chapmanb/bcbio-nextgen#1987]
Hello,

I've been using Bcbio fine on the same system, previously, however I started getting errors (see below) after upgrading to enable support for MuTect. I tried doing a fresh install, however I end up getting the same error:

> bcbio_nextgen.py 
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio/tools/bin/bcbio_nextgen.py", line 33, in <module>
>     from bcbio import install, utils, workflow
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 25, in <module>
>     from bcbio import broad, utils
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 16, in <module>
>     from bcbio.broad import picardrun
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/broad/picardrun.py", line 6, in <module>
>     import pysam
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
>     from pysam.libchtslib import *
>   File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib (pysam/libchtslib.c:12515)
> ImportError: /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/pysam/libcbcftools.so: undefined symbol: hts_log

This is the output of ldd on that library:

> ldd /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/pysam/libcbcftools.so
> 	linux-vdso.so.1 =>  (0x00007ffff7ffd000)
> 	libz.so.1 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/libz.so.1 (0x00007ffff7b09000)
> 	libhts.so.2 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/libhts.so.2 (0x00007ffff7839000)
> 	libchtslib.so => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/pysam/libchtslib.so (0x00007ffff7612000)
> 	libpython2.7.so.1.0 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/libpython2.7.so.1.0 (0x00007ffff7216000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffff6feb000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007ffff6c2a000)
> 	liblzma.so.5 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/./liblzma.so.5 (0x00007ffff6a04000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00007ffff6702000)
> 	libcurl.so.4 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/./libcurl.so.4 (0x00007ffff649c000)
> 	libcrypto.so.1.0.0 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/./libcrypto.so.1.0.0 (0x00007ffff6065000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffff5e60000)
> 	libutil.so.1 => /lib64/libutil.so.1 (0x00007ffff5c5d000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00007ffff5a54000)
> 	libssl.so.1.0.0 => /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/././libssl.so.1.0.0 (0x00007ffff57dd000)

Each Bcbio executable throws the same error, so I'm unable to run an upgrade command, for example. How can I get Bcbio working again?

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the report. We recently updated samtools, bcftools, htslib and pysam and it looks like things got out of sync on your install. You should be able to do:
```
bcbio_conda install -c conda-forge -c bioconda htslib pysam
```
to get the latest version of both. Updating to htslib 1.5 should resolve the issue. I'll re-update the install package to explicitly define this dependency to avoid the problem going forward. Please let us know if you run into any other issues.

**Comment by amizeranschi** [comment]
Thank you very much for the answer. Manually updating those packages fixed things for me.
