### ISSUE TITLE
A bug in the platypus wrapper for grch38?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#1988]
Hello!

In WES multisample calling on grch38, when it comes to 

```
bcftools view -O z  work/platypus/vexomes-vepeffects-filter.vcf.gz -s IV3 > [tmp_folder] IV3-vepeffects-filter.vcf.gz
```
it throws an error:
```
Error: subset called for sample that does not exist in header: "IV3". Use "--force-samples" to ignore this error.
```
Indeed the sample names in vexomes-vepeffects-filter.vcf.gz are IV24-sort, IV3-sort,
instead of IV24, IV3.
The sample names are correct for the other callers: gatk-haplotype,samtools,freebayes.

Could you please check this?

Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks much for the report. I tried to replicate this on a simple test case but Platypus appears to do the right thing for me: it pulls the sample names from the BAM read groups and applies them correctly. A couple of thoughts/ideas for debugging:

- Are you running alignment with bcbio so it sets the read groups correctly?
- Is it possible you have some older version of platypus on your PATH? The bcbio shipped version (0.8.1) appears to do the right thing.

Any other information you can supply to help replicate would be really helpful. Thanks again for the report and help debugging.

**Comment by naumenko-sa** [comment]
Hi Brad!
Thanks for helping with that issue.

1. Yes, I'm running bcbio starting from fastq files, so the alignment step has been done with bcbio.
And freebayes uses the same bam file to produce correct sample names in the vcf.
2. No, I'm using platypus from bcbio and I don't have another one in the PATH.

I hope it is platypus 0.8.1-1:
```
ls -l `which -a platypus`
/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/bin/platypus -> ../anaconda/bin/platypus

ls -l /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/bin/platypus
/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/bin/platypus -> ../share/platypus-variant-0.8.1-1/platypus
```
but in the beginning of the vcf file platypus writes:
```
gunzip -c platypus.vexomes-chr4_0_36067222.vcf.gz | head -n3
##fileformat=VCFv4.0
##fileDate=2017-06-26
##source=Platypus_Version_0.7.9.5
```

Any ideas?

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks for following up. I read through the Platypus code and it looks like it will fall back to using the filename if parsing the BAM file fails:

https://github.com/andyrimmer/Platypus/blob/master/src/cython/platypusutils.pyx#L142

so that explains what you're seeing but I'm not sure why the parsing of the BAM file fails. If you could manually run one of the `platypus callVariants` command lines from `log/bcbio-nextgen-commands.log` and edit to increase verbosity (`--logFileName test.log --verbosity=3`) then you should hopefully be able to see a log message about why it failed which should give us some clue to debug more. Hope this helps some with identifying the underlying issue.

**Comment by naumenko-sa** [comment]
Thanks so much, Brad, what a brilliant debug!

The platypus error was:
```
2017-06-27 16:37:48,350 - DEBUG - Error in BAM header sample parsing. Error was 
unknown field code 'AH' in record 'SQ'

2017-06-27 16:37:48,350 - DEBUG - Adding sample name IV3-sort
```

It is hg38. In the bam header there are records like
```
@SQ	SN:chr1_KI270762v1_alt	LN:354444	AH:*
@SQ	SN:chr1_KI270766v1_alt	LN:256271	AH:*
@SQ	SN:chr1_KI270760v1_alt	LN:109528	AH:*
@SQ	SN:chr1_KI270765v1_alt	LN:185285	AH:*
```

So the error comes when using platypus with hg38.

Will remove_extracontigs or hg38_noalt help?

Sergey

**Comment by chapmanb** [comment]
Sergey;
Thanks so much for the details from the debug log. I sent a PR upstream to Platypus to fix the issue and will work on rebuilding a new bioconda package with the fix after that gets merged. AH values are valid SAM and the parser in Platypus only preceeds them so hopefully adding this all in gets it fixed correctly. Thanks again.

**Comment by chapmanb** [comment]
Sergey;
I haven't heard from the Platypus team but pushed a new release to my branch with this fix and updated the bioconda package. If you update your tools (`bcbio_nextgen.py upgrade --tools`) or just Platypus (`bcbio_conda install -c conda-forge -c bioconda platypus-variant`) it should give you the fixed version. Removing the platypus directory of the old calls and re-running will hopefully give you output with the correct sample names. Thanks again for the help debugging this.

**Comment by naumenko-sa** [comment]
Thanks, it works - passed the platypus step.
SN
