### ISSUE TITLE
"Invalid character '%' in 'FREQ' FORMAT field" in Varscan germline variant calls

### ISSUE THREAD

**Issue by amizeranschi** [chapmanb/bcbio-nextgen#1989]
Hello, I'm getting an error during an ensemble pipeline for germline variant calling. It seems that the output of varscan is incorrectly being read by Bcbio, near the end of the whole process, when the batch variant calls are computed. 

I am using the latest version of Bcbio, freshly installed yesterday. Is there anything I can do to fix this, besides disabling varscan altogether?

> [2017-06-27T18:43Z] multiprocessing: combine_calls
> [2017-06-27T18:43Z] Ensemble consensus calls for P10w-comp: gatk-haplotype,freebayes,platypus,samtools,varscan
> [2017-06-27T18:43Z] Ensemble intersection calling: P10w-comp
> [2017-06-27T18:43Z] 2017-06-27 20:43:19 urga1.cerit-sc.cz INFO [bcbio.run.itx] - [W::bcf_hdr_check_sanity] GL should be declared as Number=G
> [2017-06-27T18:43Z] 2017-06-27 20:43:19 urga1.cerit-sc.cz INFO [bcbio.run.itx] - [E::vcf_parse_format] Invalid character '%' in 'FREQ' FORMAT field at chrI:25
> [2017-06-27T18:43Z] 2017-06-27 20:43:19 urga1.cerit-sc.cz INFO [bcbio.run.itx] - Error: VCF parse error
> [2017-06-27T18:43Z] 2017-06-27 20:43:19 urga1.cerit-sc.cz ERROR [bcbio.run.itx] -
> [2017-06-27T18:43Z] java.lang.Exception: Shell command failed: bcftools view -f 'PASS,.' /scratch/amizeranschi/job_54934.wagap-pro.cerit-sc.cz/allDNA-P10w-down-germline/work/gemini/P10w-comp-varscan.vcf.gz -O z -o /scratch/amizeranschi/job_54934.wagap-pro.cerit-sc.cz/allDNA-P10w-down-germline/work/bcbiotx/tmpTLY3JN/P10w-comp-ensemble-work/txtmp4312770904236230970/P10w-comp-varscan-nofilter.vcf.gz
> [2017-06-27T18:43Z]                      Error: VCF parse error
> [2017-06-27T18:43Z]                      [E::vcf_parse_format] Invalid character '%' in 'FREQ' FORMAT field at chrI:25
> [2017-06-27T18:43Z]                                bcbio.run.itx/check-run           itx.clj:  168
> [2017-06-27T18:43Z] bcbio.variation.ensemble.intersect/maybe-nofiltered/fn     intersect.clj:   69
> [2017-06-27T18:43Z]    bcbio.variation.ensemble.intersect/maybe-nofiltered     intersect.clj:   69
> [2017-06-27T18:43Z]    bcbio.variation.ensemble.intersect/ensemble-vcfs/fn     intersect.clj:   82
> [2017-06-27T18:43Z]                                    clojure.core/map/fn          core.clj: 2622
> [2017-06-27T18:43Z]                              clojure.lang.LazySeq.sval      LazySeq.java:   40
> [2017-06-27T18:43Z]                               clojure.lang.LazySeq.seq      LazySeq.java:   49
> [2017-06-27T18:43Z]                                    clojure.lang.RT.seq           RT.java:  507
> [2017-06-27T18:43Z]                                       clojure.core/seq          core.clj:  137
> [2017-06-27T18:43Z]                                 clojure.core/filter/fn          core.clj: 2679
> [2017-06-27T18:43Z]                              clojure.lang.LazySeq.sval      LazySeq.java:   40
> [2017-06-27T18:43Z]                               clojure.lang.LazySeq.seq      LazySeq.java:   49
> [2017-06-27T18:43Z]                   clojure.lang.ChunkedCons.chunkedNext  ChunkedCons.java:   59
> [2017-06-27T18:43Z]                          clojure.lang.ChunkedCons.next  ChunkedCons.java:   43
> [2017-06-27T18:43Z]                                   clojure.lang.RT.next           RT.java:  674
> [2017-06-27T18:43Z]                                      clojure.core/next          core.clj:   64
> [2017-06-27T18:43Z]                                      clojure.core/some          core.clj: 2570
> [2017-06-27T18:43Z]                                   clojure.core/comp/fn          core.clj: 2439
> [2017-06-27T18:43Z]      bcbio.variation.ensemble.prep/unique-work-file/fn          prep.clj:   18
> [2017-06-27T18:43Z]         bcbio.variation.ensemble.prep/unique-work-file          prep.clj:   16
> [2017-06-27T18:43Z]        bcbio.variation.ensemble.vcfsample/sort-samples     vcfsample.clj:   36
> [2017-06-27T18:43Z]    bcbio.variation.ensemble.vcfsample/maybe-sort-names     vcfsample.clj:   53
> [2017-06-27T18:43Z] bcbio.variation.ensemble.vcfsample/consistent-order/fn     vcfsample.clj:   62
> [2017-06-27T18:43Z]                                    clojure.core/map/fn          core.clj: 2622
> [2017-06-27T18:43Z]                              clojure.lang.LazySeq.sval      LazySeq.java:   40
> [2017-06-27T18:43Z]                               clojure.lang.LazySeq.seq      LazySeq.java:   49
> [2017-06-27T18:43Z]                                 clojure.lang.Cons.next         Cons.java:   39
> [2017-06-27T18:43Z]                                   clojure.lang.RT.next           RT.java:  674
> [2017-06-27T18:43Z]                                      clojure.core/next          core.clj:   64
> [2017-06-27T18:43Z]                                    clojure.string/join        string.clj:  186
> [2017-06-27T18:43Z]      bcbio.variation.ensemble.intersect/intersect-vcfs     intersect.clj:   19
> [2017-06-27T18:43Z]       bcbio.variation.ensemble.intersect/ensemble-vcfs     intersect.clj:   85
> [2017-06-27T18:43Z]               bcbio.variation.ensemble.intersect/-main     intersect.clj:  140
> [2017-06-27T18:43Z]                            clojure.lang.RestFn.applyTo       RestFn.java:  137
> [2017-06-27T18:43Z]                                     clojure.core/apply          core.clj:  630
> [2017-06-27T18:43Z]                   bcbio.variation.recall.main/-main/fn          main.clj:   34
> [2017-06-27T18:43Z]                      bcbio.variation.recall.main/-main          main.clj:   33
> [2017-06-27T18:43Z]                            clojure.lang.RestFn.applyTo       RestFn.java:  137
> [2017-06-27T18:43Z]                       bcbio.variation.recall.main.main                  :

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. We do try to fix this VarScan bug in the code -- VarScan reports `FREQ` like `53%` but the header references it as a float so parsers that check will fail. However, we haven't used it much for germline, primarily somatic calling, so must have missed something. Reading the code, it looks like it might not correctly fix this for a multi-sample variant run. Is that what you're running here? Thanks much for the help debugging.

**Comment by amizeranschi** [comment]
Thank you for looking into this. Yes, I am running a multi-sample variant run, doing batch calling with 5 variant callers: haplotypecaller, freebayes, platypus, samtools and varscan.

**Comment by chapmanb** [comment]
Thank you for following up and confirming the underlying issue. I pushed a fix which will correctly clean up the FREQ fields for all samples in a multi-sample run and should resolve the problem. You'll have to re-run the VarScan calls but can re-use all other callers so if you update to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
then remove the VarScan calls (`rm -rf varscan`) and re-run it should hopefully work cleanly now. Please let us know if you run into any other issues.

**Comment by amizeranschi** [comment]
I've rerun the pipeline and it finished successfully this time. However, I still notice errors during the Varscan output fixing phase, which do not fully crash the pipeline this time around:

> [2017-07-01T12:13Z] 88734 bases in pileup file
> [2017-07-01T12:13Z] 23 variant positions (21 SNP, 2 indel)
> [2017-07-01T12:13Z] 8 were failed by the strand-filter
> [2017-07-01T12:13Z] 15 variant positions reported (13 SNP, 2 indel)
> [2017-07-01T12:13Z] Traceback (most recent call last):
> [2017-07-01T12:13Z]   File "<string>", line 1, in <module>
> [2017-07-01T12:13Z]     bcbio.variation.varscan.fix_varscan_output(x)
> [2017-07-01T12:13Z]   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/varscan.py", line 211, in fix_varscan_output
> [2017-07-01T12:13Z]     ndat[Ifreq] = str(float(ndat[Ifreq].rstrip("%")) / 100)
> [2017-07-01T12:13Z] IndexError: list index out of range
> [2017-07-01T12:13Z] bgzip P10w-comp-chrXII_980075_1068809.vcf
> [2017-07-01T12:13Z] tabix index P10w-comp-chrXII_980075_1068809.vcf.gz
> [2017-07-01T12:13Z] GATK: VariantAnnotator

This error does not seem to appear every time the output of Varscan is being fixed. I'm wondering whether these errors could lead to some of Varscan's results to not be reported in the final set of (ensemble) variants. Looking at the results in IGV, there seem to be some large discrepancies between Varscan's output and that of other tools in certain genomic regions (where Varscan effectively finds nothing), while in other regions Varscan's output seems to match that of other tools, to a degree. Could it be that the regions with the discrepancies are those for which the bcbio.variation.varscan.fix_varscan_output() method failed to run properly?

I hope I explained the problem well enough. Please let me know if I can offer more useful information. See also the following screenshot, comparing Varscan's results (top track) with that of the ensemble VCF file (bottom track) for a chromosome IV in the yeast S. Cerevisiae:

![screenshot](https://user-images.githubusercontent.com/11562164/27768485-14539a00-5f15-11e7-9c01-3cdce157ea76.png)

**Comment by chapmanb** [comment]
Thanks so much for the detailed report and apologies about the problem. Failing here is definitely the issue you're seeing with missing calls and is not the correct behavior. I pushed a fix to hopefully avoid these cases, which I believe are due to how VarScan handles no-calls. Unfortunately you'll have to update and re-run VarScan again but hopefully it'll now work correctly and avoid errors in these regions. Thanks for all the help debugging and please let us know if you spot any other problems.
