### ISSUE TITLE
OSError when running CNVkit

### ISSUE THREAD

**Issue by amizeranschi** [chapmanb/bcbio-nextgen#1990]
Hello, 

I have been testing CNVKit on a set of BAM files that were previously created with Bcbio and then downsampled. Germline and somatic variant calling are running fine on these BAM files. However, I am getting an error with CNVkit:

> 
> [2017-06-27T19:22Z] Configuring 1 jobs to run, using 64 cores each with 192.1g of memory reserved for each job
> [2017-06-27T19:22Z] CNVkit fix
> [2017-06-27T19:22Z] Processing target: P10-20N-down-2-P10w-comp-2_5
> [2017-06-27T19:22Z] Keeping 45267 of 45267 bins
> [2017-06-27T19:22Z] /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/skgenome/gary.py:208: FutureWarning: 'as_indexer' keyword was specified but is ignored (match now returns a boolean indexer by default), and will be removed in a future version.
> [2017-06-27T19:22Z]   as_indexer=True, na=False)
> [2017-06-27T19:22Z] Correcting for GC bias...
> [2017-06-27T19:22Z] Correcting for density bias...
> [2017-06-27T19:22Z] Processing antitarget: P10-20N-down-2-P10w-comp-2_5
> [2017-06-27T19:22Z] Wrote /scratch/amizeranschi/job_58848.wagap-pro.cerit-sc.cz/allDNA-P10w-down-somatic/work/bcbiotx/tmpeE3IJp/P10-20N-down-2-P10w-comp-2_5.cnr with 45267 regions
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
>     main(**kwargs)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
>     run_main(**kwargs)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
>     fc_dir, run_info_yaml)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 177, in variant2pipeline
>     samples = structural.run(samples, run_parallel, "standard")
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 172, in run
>     for xs in to_process.values()))
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
>     return run_multicore(fn, items, config, parallel=parallel)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
>     for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
>     while self.dispatch_one_batch(iterator):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
>     job = ImmediateComputeBatch(batch)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
>     self.results = batch()
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
>     return apply(f, *args, **kwargs)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 278, in detect_sv
>     return structural.detect_sv(*args)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 191, in detect_sv
>     for svdata in caller_fn(items):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 33, in run
>     return _cnvkit_by_type(items, background)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 45, in _cnvkit_by_type
>     return _run_cnvkit_cancer(items, background)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 90, in _run_cnvkit_cancer
>     ckouts = _run_cnvkit_shared([tumor_ready], [normal_ready] if normal_ready else [])
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 196, in _run_cnvkit_shared
>     inputs[0]["config"], parallel)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
>     for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
>     while self.dispatch_one_batch(iterator):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
>     job = ImmediateComputeBatch(batch)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
>     self.results = batch()
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
>     return apply(f, *args, **kwargs)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 63, in wrapper
>     out = f(*args, **kwargs)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 266, in _cnvkit_fix
>     return [_cnvkit_fix_base(cnns, background_cnn, items)]
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/cnvkit.py", line 277, in _cnvkit_fix_base
>     do.run(_prep_cmd(cmd, tx_out_file), "CNVkit fix")
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 75, in file_transaction
>     _move_tmp_files(safe, orig)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/transaction.py", line 86, in _move_tmp_files
>     utils.safe_makedir(os.path.dirname(orig))
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 183, in safe_makedir
>     os.makedirs(dname)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 150, in makedirs
>     makedirs(head, mode)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/os.py", line 157, in makedirs
>     mkdir(name, mode)
> OSError: [Errno 13] Permission denied: '/scratch/amizeranschi/job_58848wagap-procerit-sccz'

It seems like Bcbio is attempting to create a directory in the wrong path (/scratch/amizeranschi/job_58848wagap-procerit-sccz). The correct path for the Scratc directory where the job was running was "/scratch/amizeranschi/job_58848.wagap-pro.cerit-sc.cz". My guess is that one of the scripts was having a hard time dealing with paths that contain a dot within them. 

Is there a way I can circumvent this? I am running jobs on PBSPro, so I do not have any control over the naming convention for the jobs' Scratch directory...

**Comment by chapmanb** [comment]
Sorry about the issue, I believe this is the same problem that's fixed in the latest development version so like your qualimap/icu issue the best approach is to upgrade to that version which will have this fix:

https://github.com/chapmanb/bcbio-nextgen/commit/9f45462a2fbd6263482c5f12cb49969b85017848#diff-9e05b18dca9a5f29b9b5650ac2f39b32

We're hoping to have a new release soon including all these fixes. Please feel free to re-open if upgrading does not resolve the issue. Thanks again for all the reports.
