### ISSUE TITLE
vep splicesite annotations

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#1993]
Hi Brad, 

We've been testing VEP quite thorougly and have come to the following conclusions.
 - performance is up to speed, without extra splicesite annotations we're getting a runtime of about 6 min on 12 cores for a WES sample
- when using all splice-site annotations ( e.g. MaxEntScan, GeneSplicer and SpliceRegion) we face freqent failures, because of dying Perl forks.
- Since an [update of the MaxEntscan plugin](Ensembl/ensembl-vep#58) (available in the latest revision of the conda recipe), we're seeing increased performance (10 min/ 12 cores/ WES sample) when run without GeneSplicer.

It seems that for full annotations, GeneSplicer is the limiting factor. @willmclaren is going to take a look at the plugin to see if there are any performance gains to be made. In the mean time, I would propose disabling GeneSplicer under the `vep_splicesite_annotations`option, untill the perfomance issues have been resolved.

I don't know if you've tested the complete annotation package yourself, but I'd be interested in hearing your thoughts.

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for all the work on this, I've been following the other threads and appreciate all the testing and pushing these through. I dropped GeneSplicer for now and we can revisit if we find a way to make it stable and relatively fast. With the fixes for MaxEntScan do you think having this be the default makes sense, or does it still slow things down enough to keep it as an option? We've been primarily using snpEff so I appreciate all your experience and work making this stable and useful. Thanks again.

**Comment by matthdsm** [comment]
Hi Brad,

I think it's okay to have this on by default, as it only adds a couple of minutes to the runtime. Of course, I might be the wrong person to ask, since we need to have this option always on.

On the topic of snpEff, I saw there's a spliceAnalysis option in the latest version. Have you been able to test that one by any chance? The documentation is a bit sparse and we haven't had the time to try it out for ourselves.

Thanks!
M

**Comment by chapmanb** [comment]
Matthias;
Thanks -- I'll leave it as an option for now and do some whole genome testing with it and then think about including it as the default. Everything is good now, we only try to avoid extra options if we can help it. I haven't explore the splicing updates in snpEff yet. Thanks for the heads up on it, I'll definitely let you know if we look into it.

**Comment by matthdsm** [comment]
Sound good to me!
Cheers
M
