### ISSUE TITLE
Qualimap error in RNA-seq: "ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by amizeranschi** [chapmanb/bcbio-nextgen#1994]
Hello,

After a recent Bcbio upgrade, the RNA-seq pipeline is failing at the Qualimap stage. This pipeline was running perfectly up until recently, but now there seems to be an unmet dependency:

> [2017-06-28T05:45Z] Writing HTML report...
> [2017-06-28T05:45Z] HTML report created successfully
> [2017-06-28T05:45Z] 
> [2017-06-28T05:45Z] Fix Name Qualimap for B42-0000-L-06-R-1
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
>     main(**kwargs)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
>     run_main(**kwargs)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
>     fc_dir, run_info_yaml)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 267, in rnaseqpipeline
>     samples = qcsummary.generate_parallel(samples, run_parallel)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 35, in generate_parallel
>     qced = run_parallel("pipeline_summary", to_analyze)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
>     return run_multicore(fn, items, config, parallel=parallel)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
>     for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
>     while self.dispatch_one_batch(iterator):
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
>     job = ImmediateComputeBatch(batch)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
>     self.results = batch()
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 51, in wrapper
>     return apply(f, *args, **kwargs)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 182, in pipeline_summary
>     return qcsummary.pipeline_summary(*args)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 66, in pipeline_summary
>     data["summary"] = _run_qc_tools(work_bam, data)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 137, in _run_qc_tools
>     out = qc_fn(bam_file, data, cur_qc_dir)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 317, in run_rnaseq
>     metrics = _parse_rnaseq_qualimap_metrics(report_file)
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/qualimap.py", line 280, in _parse_rnaseq_qualimap_metrics
>     import lxml.html
>   File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/lxml/html/__init__.py", line 54, in <module>
>     from .. import etree
> ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
> WARNING: update already refers to: #'clojure.core/update in namespace: incanter.core, being replaced by: #'incanter.core/update
> Exception in thread "main" java.io.FileNotFoundException: */project-summary.yaml (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at clojure.java.io$fn__9189.invoke(io.clj:229)
> 	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
> 	at clojure.java.io$fn__9201.invoke(io.clj:258)
> 	at clojure.java.io$fn__9102$G__9095__9109.invoke(io.clj:69)
> 	at clojure.java.io$fn__9163.invoke(io.clj:165)
> 	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
> 	at clojure.java.io$reader.doInvoke(io.clj:102)
> 	at clojure.lang.RestFn.invoke(RestFn.java:410)
> 	at clojure.lang.AFn.applyToHelper(AFn.java:154)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
> 	at clojure.core$apply.invoke(core.clj:632)
> 	at clojure.core$slurp.doInvoke(core.clj:6653)
> 	at clojure.lang.RestFn.invoke(RestFn.java:410)
> 	at bcbio.rnaseq.config$load_yaml.invoke(config.clj:13)
> 	at bcbio.qcsummary.core$load_summary.invoke(core.clj:49)
> 	at bcbio.qcsummary.core$load_tidy_summary.invoke(core.clj:65)
> 	at bcbio.qcsummary.core$write_tidy_summary.invoke(core.clj:78)
> 	at bcbio.qcsummary.core$summarize.invoke(core.clj:127)
> 	at bcbio.qcsummary.core$summarize_cli.doInvoke(core.clj:157)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.core$apply.invoke(core.clj:630)
> 	at bcbio.rnaseq.core$_main.doInvoke(core.clj:93)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at bcbio.rnaseq.core.main(Unknown Source)

I tried installing ICU versio 58.1 manually, but this failed due to conflicting dependencies:

> bcbio_conda install -c conda-forge icu=58.1
> Fetching package metadata ....
> 
> .......
> Solving package specifications: .
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - icu 58.1*
>   - salmon -> boost 1.61* -> icu 56.*
> Use "conda info <package>" to see the dependencies for each package.

I also tried updating salmon manually, but it seems that I already have the latest version:

> bcbio_conda install -c conda-forge salmon
> Fetching package metadata ...........
> Solving package specifications: .
> 
> All requested packages already installed.
> packages in environment at /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda:
> 
> salmon                    0.8.2                         0    bioconda

**Comment by chapmanb** [comment]
Sorry about the issue, the icu dependency has been a real problem and we removed the lxml usage in the latest development version to avoid this problem. If you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run it'll use an alternative method for parsing the qualimap output that avoids this issue. Hope this gets it working for you.
