### ISSUE TITLE
AttributeError: 'module' object has no attribute 'iam'

### ISSUE THREAD

**Issue by egorrevkov** [chapmanb/bcbio-nextgen#1997]
Hello,

While trying to install bcbio on AWS I have encountered a problem: I have been following instructions on the AWS setup from the [bcbio-nextgen documentation](http://bcbio-nextgen.readthedocs.io/en/latest/contents/cloud.html) and got stuck at the 

`bcbio_vm.py aws iam --region=ap-southeast-1` 

(the region is changed to mine). After I run it, I get

```
 Traceback (most recent call last):
  File "/home/er/install/bcbio-vm/anaconda/bin/bcbio_vm.py", line 4, in <module>
    __import__('pkg_resources').run_script('bcbio-nextgen-vm==0.1.0a0', 'bcbio_vm.py')
  File "/home/er/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/er/install/bcbio-vm/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/home/er/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbio_nextgen_vm-0.1.0a0-py2.7.egg-info/scripts/bcbio_vm.py", line 327, in <module>
    args.func(args)
  File "/home/er/install/bcbio-vm/anaconda/lib/python2.7/site-packages/bcbiovm/aws/iam.py", line 35, in bootstrap
    conn = boto.iam.connect_to_region(args.region)
AttributeError: 'module' object has no attribute 'iam'
```

Everything prior to it worked correctly.
Reinstalling did not help, still stuck at the same place. Could anyone please help with what I am doing wrong?

Thanks in advance

**Comment by egorrevkov** [comment]
Maybe this will help: got kind of the same mistake when trying to install bcbio on AWS cloud with [this manual](https://github.com/chapmanb/bcbio-nextgen/tree/master/scripts/ansible): after running
 `bcbio_vm.py aws ansible ap-southeast-1b --keypair`
I got similar error
> AttributeError: 'module' object has no attribute 'ec2'

which was also referring to boto. 

So after looking through the last commits on [bcbio-nextgen-vm](https://github.com/chapmanb/bcbio-nextgen-vm) I noticed that the last one at the time (on June 24)  was about  [moving boto imports](https://github.com/chapmanb/bcbio-nextgen-vm/commit/110d291fea2083b416af67130e066b4be6738ab9). I reverted boto-related scripts to their earlier state (the commit before that) and then the command worked properly.

One other solution is to update **ansible**, but it seems that bcbio-vm relies on ansible **callback** plugin, which is deprecated in ansible>=2.0.0; so while it helps with the boto module problem, it still does not allow to proceed further.

P.S. I am sorry if I am posting this in the wrong issue section, maybe that problem belongs to the bcbio-nextgen-vm repository.

**Comment by chapmanb** [comment]
Egor;
Apologies, I forgot to follow up on this earlier. Thank you for the report and the fix. I pushed a fix that resolves it and updated the bioconda packages so if you do:
```
bcbio_vm.py upgrade --wrapper
```
it should hopefully work cleanly. Thank you again and hope everything else works smoothly for you.

**Comment by egorrevkov** [comment]
Hi Brad,

Great, thank you!

2017-07-10 9:06 GMT+08:00 Brad Chapman <notifications@github.com>:
