### ISSUE TITLE
No optitype output from tumor/normal calling

### ISSUE THREAD

**Issue by aadamk** [chapmanb/bcbio-nextgen#1998]
I ran tumor variant calling using an ensemble caller with vep annotation + hla calling for normal.  I successfully obtained an annotated ensemble vcf, but the expected .csv containing optitype output was not generated.  My aim was to get the hla genotype for normal tissue.  No issues are reported in the log files, but there is no record of optitype having run (though there are references to hla typing in the log file - e.g. 'Timing: HLA typing' & 'Multiprocessing: call_hla'). I have a snapshot of the sample.yaml file I created.  Is there an error in my preparation?

details:
- algorithm:
    aligner: false
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: false
    recalibrate: false
    realign: false
    remove_lcr: false
    platform: illumina
    quality_format: standard
    variantcaller: [vardict, mutect2]
    indelcaller: mutect2
    hlacaller: optitype
    bam_clean: fixrg
    ensemble:
      numpass: 2
  analysis: variant2
  description: 98-PBL_control
  files: /project/hanslab/lyn_Mel_Case/SN0119031/98-PBL_control.bam
  genome_build: GRCh37
  metadata:
    batch: mel_case22
    phenotype: normal
- algorithm:
    aligner: false
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: false
    recalibrate: false
    realign: false
    remove_lcr: false
    platform: illumina
    bam_clean: fixrg
    quality_format: standard
    variantcaller: [vardict, mutect2]
    indelcaller: mutect2
    ensemble:
      numpass: 2
    effects: vep
    tools_off: [gemini]
  analysis: variant2
  description: D14-617_C4
  files: /project/hanslab/lyn_Mel_Case/SN0119031/D14-617_C4.bam
  genome_build: GRCh37
  metadata:
    batch: mel_case22
    phenotype: tumor
fc_date: '7.5.2017'
fc_name: mel_case22
upload:
  dir: ../final

**Comment by schelhorn** [comment]
I believe you would have to align to `hg38` - at least that is what people are mostly using to include the ALTs.

**Comment by chapmanb** [comment]
Sven-Eric is exactly right, unfortunately HLA typing with OptiType only works with hg38. We use hg38 HLA alt alleles to extract HLA reads prior to feeding into OptiType. Apologies about the confusion, I added a check so bcbio will provide a useful error message instead of silently failing to call HLAs. Hopefully swapping to hg38 works for your analysis.

**Comment by aadamk** [comment]
Thanks all. Installed hg38 and simplified my sample.yaml file (to exclude tumor as I only want optitype calls on the normal sample; I also commented out variant calling lines including the somatic callers as well as the 'analysis: variant2' section).  However, my log file shows an exit status of 1.  Below are my sample.yaml configuration and snippet of the log file, which repeats 'Reorder SAM' even though I have bam_clean set to 'picard' and quality_format to 'illumina' (though these BAMs were generated from using GATK best practice QC). Any suggestions or notable errors?

sample.yaml:
details:
- algorithm:
    aligner: false
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: false
    recalibrate: false
    realign: false
    remove_lcr: false
    platform: illumina
    quality_format: illumina
    #variantcaller: [vardict, mutect2]
    #indelcaller: mutect2
    hlacaller: optitype
    bam_clean: picard
    #ensemble:
      #numpass: 2
    #variant_regions: ../input/NGv3.bed
    # svcaller: [cnvkit, lumpy, delly]
    # coverage_interval: amplicon
  #analysis: variant2
  description: 98-PBL_control
  files: /project/hanslab/lyn_Mel_Case/SN0119031/98-PBL_control.bam
  #files:
    #- ../input/synthetic_challenge_set3_normal_NGv3_1.fq.gz
    #- ../input/synthetic_challenge_set3_normal_NGv3_2.fq.gz
  genome_build: hg38
  metadata:
    batch: mel_normal_hla
    phenotype: normal
fc_date: '7.6.2017'
fc_name: mel_normal_hla
upload:
  dir: ../final

log file:
[2017-07-07T16:36Z] INFO        2017-07-07 12:36:02     ReorderSam        SN=%s LN=%d%nchrUn_JTFH01001972v1_decoy2142
[2017-07-07T16:36Z] INFO        2017-07-07 12:36:02     ReorderSam        SN=%s LN=%d%nchrUn_JTFH01001973v1_decoy2136
[2017-07-07T16:36Z] INFO        2017-07-07 12:36:02     ReorderSam        SN=%s LN=%d%nchrUn_JTFH01001974v1_decoy2130
[2017-07-07T16:36Z] INFO        2017-07-07 12:36:02     ReorderSam        SN=%s LN=%d%nchrUn_JTFH01001975v1_decoy2128
[2017-07-07T16:36Z] INFO        2017-07-07 12:36:02     ReorderSam        SN=%s LN=%d%nchrUn_JTFH01001976v1_decoy2126

**Comment by chapmanb** [comment]
Thanks for following up. bcbio will convert BAMs to fastq and realign automatically for you, so a configuration like this (based on what you posted previously) will align to hg38 and HLA call only:
```
details:
- algorithm:
    aligner: bwa
    hlacaller: optitype
  analysis: variant2
  description: 98-PBL_control
  files: /project/hanslab/lyn_Mel_Case/SN0119031/98-PBL_control.bam
  genome_build: hg38
fc_date: '7.6.2017'
fc_name: mel_normal_hla
upload:
  dir: ../final
```
Hope this gets it running for you.

**Comment by aadamk** [comment]
Thanks, this worked!
