### ISSUE TITLE
Prioritise is slow/stuck

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#2001]
Hi Brad,

My bcbio run has been unable to proceed past a certain T-N paired sample at the prioritisation step, up to the generation of the manta tsv files. I checked the commands and can't find anything wrong (other than the files being 0kb but I don't think this is the reason). The last commands run according to the log are:
[2017-07-10T05:48Z] export PATH=/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin:$PATH &&  zcat /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170630_Set3/bcbio/set3/work/structural/1775_020317_T/prioritize/1775_020317_T-manta-simple-prep.vcf.gz | vawk -v SNAME=1775_020317_T -v CALLER=manta '{if (($7 == "PASS" || $7 == ".") && (S$1775_020317_T$GT != "0/0")) print CALLER,SNAME,$1,$2,I$END,I$SVTYPE=="BND" ? I$SVTYPE":"$3":"I$MATEID : I$SVTYPE,I$LOF,I$SIMPLE_ANN,S$1775_020317_T$SR,S$1775_020317_T$PE,S$1775_020317_T$PR}' > /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170630_Set3/bcbio/set3/work/bcbiotx/tmpartYvl/1775_020317_T-manta-prioritize.tsv
[2017-07-10T05:48Z] export PATH=/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin:$PATH &&  zcat /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170630_Set3/bcbio/set3/work/structural/1775_020317_N/prioritize/1775_020317_N-manta-simple-prep.vcf.gz | vawk -v SNAME=1775_020317_N -v CALLER=manta '{if (($7 == "PASS" || $7 == ".") && (S$1775_020317_N$GT != "0/0")) print CALLER,SNAME,$1,$2,I$END,I$SVTYPE=="BND" ? I$SVTYPE":"$3":"I$MATEID : I$SVTYPE,I$LOF,I$SIMPLE_ANN,S$1775_020317_N$SR,S$1775_020317_N$PE,S$1775_020317_N$PR}' > /mnt/projects/ngbhs/cirqseq/20170224_plasma/20170630_Set3/bcbio/set3/work/bcbiotx/tmpFpH7Ss/1775_020317_N-manta-prioritize.tsv

I believe it's just very slow? Is there a way to improve the speed of prioritisation? Thank you!

Edit: Found the problematic sample in bcbiotx. It's taking more than 1 day to generate the prep-wgts.vcf.gz file.
-rw-r--r-- 1 dlho gib    168184 Jul 10 13:48 1713_060117_T-lumpy-simple-prep-wgts-header.txt
-rw-r--r-- 1 dlho gib 256901120 Jul 11 13:01 1713_060117_T-lumpy-simple-prep-wgts.vcf.gz

**Comment by chapmanb** [comment]
Thanks for the detailed report and sorry about the issue. Genotyping of Lumpy calls helps a lot with avoiding false positives, so bcbio tries to do this on breakend calls in prioritized regions (as an alternative to doing it earlier on all regions). Apologies for it being so slow -- that file seems pretty large for prioritized regions (2Gb?) which either indicates there are a ton of calls and some kind of issue or you have a lot of priority regions. What would you prefer if bcbio did here? Having an option to skip genotyping for Lumpy? Happy to hear any suggestions about how best to handle this. Thanks again for the report.

**Comment by phu5ion** [comment]
Hi Brad,

Yes I think it will be best to skip genotyping. Is there a way to specify that at this stage of the run, for e.g edit the config file for that particular sample and rerun? Happy to hear any suggestions from you or others too!

**Comment by chapmanb** [comment]
Thanks for the feedback. The latest development version (`bcbio_nextgen.py upgrade -u development`) adds support for a `tools_off: [lumpy-genotype]` option which will skip genotyping on Lumpy samples. You can add this to the algorithm section of your config for any samples causing issues:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#tweaking-defaults

Hope this lets your analysis finish cleanly and thanks again for the discussion.

**Comment by phu5ion** [comment]
Hi Brad,

When I used the command bcbio_nextgen.py upgrade -u development, there seems to be a problem:
UnsatisfiableError: The following specifications were found to be in conflict:
  - bioconductor-ensembldb -> bioconductor-genomicranges >=1.23.21 -> bioconductor-iranges >=2.7.8
  - bioconductor-iranges 2.4.7*
Use "conda info <package>" to see the dependencies for each package.


Fatal error: local() encountered an error (return code 1) while executing '/mnt/projects/dlho/tancrc/bcbio_pipeline/anaconda/bin/conda install --quiet -y -c bioconda -c conda-forge -c r age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter ensembl-vep=89.* express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gatk4 gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variant-effect-predictor=87 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli nodejs p7zip s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics=0.18.0 bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges=2.4.7 bioconductor-limma bioconductor-rtracklayer r r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi'

Aborting.

**Comment by chapmanb** [comment]
Sorry about the problem. We had a git rebase problem with cloudbiolinux but have things all fixed and resolved these problems. If you remove `tmpbcbio-install` and re-run this should fix both this and #2002. Please let us know if you hit anything else at all and thanks for the patience.
