### ISSUE TITLE
libbz2.so.1.0 error after/while hg38 upgrade attempt

### ISSUE THREAD

**Issue by firatuyulur** [chapmanb/bcbio-nextgen#2003]
Hi,

I was trying to patch hg38 to my genomes using 
`bcbio_nextgen.py upgrade -u stable --genomes hg38`
 After many successful steps, it raised an error as 
`tabix: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory` 
and it stopped. Since then, command with bcbio_nextgen.py gives the error

 `ImportError: libbz2.so.1.0: cannot open shared object file: No such file or directory` . 

Before this upgrade, I ran 2-3 rnaseqs 2 days ago without any error. I am also attaching the file where you can see the full upgrade lines.

Thanks already
Fırat

[bcbioError_hg38_upgrade.pdf](https://github.com/chapmanb/bcbio-nextgen/files/1147685/bcbioError_hg38_upgrade.pdf)

**Comment by chapmanb** [comment]
Firat;
Sorry about the issue, could you try re-runnning the update after removing the temporary install directory:
```
rm -rf tmpbcbio-install
 bcbio_nextgen.py upgrade -u stable --genomes hg38
```
We have a new update in place that was missing yesterday that should fix this. If you want to fix manually you can do:
```
bcbio_conda install -c conda-forge bzip2
```
Thanks for the report and hope this fixes it for you. Please reopen if you run into any other issues.

**Comment by firatuyulur** [comment]
This has fixed the issue. thanks!
