### ISSUE TITLE
Install error on fresh EC2

### ISSUE THREAD

**Issue by PatrickJReed** [chapmanb/bcbio-nextgen#2004]
Im getting a error I haven't come across before.
Any Ideas?

sudo python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa
Checking required dependencies
Installing isolated base python installation
Installing bcbio-nextgen
--2017-07-14 20:32:10--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: ‘requirements-conda.txt’

requirements-conda.txt                    100%[=====================================================================================>]      20  --.-KB/s    in 0s

2017-07-14 20:32:10 (6.73 MB/s) - ‘requirements-conda.txt’ saved [20/20]

Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /usr/local/share/bcbio/anaconda:

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.22-py27_0 conda-forge --> 4.3.22-py27_0
    conda-env: 2.6.0-0       conda-forge --> 2.6.0-0

Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /usr/local/share/bcbio/anaconda:

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.22-py27_0 --> 4.3.22-py27_0 conda-forge
    conda-env: 2.6.0-0       --> 2.6.0-0       conda-forge

Installing data and third party dependencies
Upgrading bcbio
Upgrading third party tools to latest versions
--2017-07-14 20:32:33--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2017-07-14 20:32:33--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.255.121, 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5163635 (4.9M) [application/x-gzip]
Saving to: ‘STDOUT’

     0K ........ ........ ........ ........ ........ ........ 60% 48.1M 0s
  3072K ........ ........ ........ ......                    100% 91.4M=0.08s

2017-07-14 20:32:33 (59.0 MB/s) - written to stdout [5163635/5163635]

mv: cannot stat 'master': No such file or directory
Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7f61ab2df3b0>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=xenial
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
INFO: Meta-package information from /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
- Packages: minimal,libraries,perl,python,java,r,ruby,bio_nextgen
- Libraries: r-libs
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/custom.yaml
INFO: Reading /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/custom.yaml
DBG [shared.py]: Packages to install:
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../config/chef_recipes.yaml
INFO: Reading /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../config/chef_recipes.yaml
DBG [shared.py]: Packages to install:
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../config/puppet_classes.yaml
INFO: Reading /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../config/puppet_classes.yaml
DBG [shared.py]: Packages to install:
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
INFO: Meta-package information from /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
- Packages: minimal,libraries,perl,python,java,r,ruby,bio_nextgen
- Libraries: r-libs
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/packages-homebrew.yaml
INFO: Reading /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/packages-homebrew.yaml
DBG [shared.py]: Packages to install:
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
INFO: Meta-package information from /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/main.yaml
- Packages: minimal,libraries,perl,python,java,r,ruby,bio_nextgen
- Libraries: r-libs
DBG [config.py]: Using config file /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
INFO: Reading /home/ubuntu/tmpbcbio-install/cloudbiolinux/cloudbio/../contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml
DBG [shared.py]: Packages to install: age-metasv,bamtools,bamutil,bcbio-prioritize,bcbio-rnaseq,bcbio-variation,bcbio-variation-recall,bcbreport,bcftools,bedtools=2.26.0,bio-vcf,biobambam,bowtie,bowtie2=2.2.8,bwa,bwakit,cage,cancerit-allelecount,cnvkit,cpat,cramtools,crossmap,cufflinks,cutadapt,cyvcf2,delly,dkfz-bias-filter,ensembl-vep=89.*,express,extract-sv-reads,fastqc,fgbio,freebayes=1.1.0,gatk,gatk-framework,gatk4,gemini,geneimpacts,genesplicer,glpk=4.57,goleft,grabix,gridss,gsort,gvcf-regions,hap.py,hisat2,hmmlearn,htseq,htslib,impute2,kallisto,kraken,lofreq,lumpy-sv,macs2,manta,maxentscan,mbuffer,metasv,mirdeep2=2.0.0.7,moreutils,multiqc,multiqc-bcbio,ngs-disambiguate,novoalign,oncofuse,optitype,pandoc,parallel,pbgzip,perl-sanger-cgp-battenberg,phylowgs,picard,pindel,platypus-variant,pyloh,pytabix,pythonpy,qsignature,qualimap,rapmap,razers3,rtg-tools,sailfish,salmon,sambamba,samblaster,samtools,scalpel,sentieon,seq2c,seqbuster,seqtk,sickle-trim,simple_sv_annotation,snap-aligner=1.0dev.97,snpeff=4.3i,spades,star,stringtie,subread,svtools,svtyper,tdrmapper,theta2,tophat,tophat-recondition,ucsc-bedgraphtobigwig,ucsc-bedtobigbed,ucsc-bigbedinfo,ucsc-bigbedsummary,ucsc-bigbedtobed,ucsc-bigwiginfo,ucsc-bigwigsummary,ucsc-bigwigtobedgraph,ucsc-bigwigtowig,ucsc-fatotwobit,ucsc-gtftogenepred,ucsc-liftover,ucsc-wigtobigwig,umis,vardict,vardict-java,variant-effect-predictor=87,variantbam,varscan,vawk,vcf2db,vcfanno,vcflib,viennarna,vt,wham,anaconda-client,awscli,bzip2,ncurses,nodejs,p7zip,readline,s3gof3r,xz,perl-app-cpanminus,perl-archive-extract,perl-archive-zip,perl-bio-db-sam,perl-cgi,perl-dbi,perl-encode-locale,perl-file-fetch,perl-file-sharedir,perl-file-sharedir-install,perl-ipc-system-simple,perl-lwp-protocol-https,perl-lwp-simple,perl-statistics-descriptive,perl-time-hires,perl-vcftools-vcf,bioconductor-annotate,bioconductor-biocgenerics,bioconductor-biocinstaller,bioconductor-biocstyle,bioconductor-biostrings,bioconductor-biovizbase,bioconductor-bubbletree,bioconductor-cn.mops,bioconductor-degreport,bioconductor-deseq2,bioconductor-dexseq,bioconductor-dnacopy,bioconductor-genomicranges,bioconductor-iranges,bioconductor-limma,bioconductor-rtracklayer,r-cghflasso,r-chbutils,r-devtools,r-dplyr,r-dt,r-ggdendro,r-ggplot2,r-gplots,r-gsalib,r-knitr,r-pheatmap,r-plyr,r-pscbs,r-reshape,r-rmarkdown,r-rsqlite,r-sleuth,r-snow,r-stringi,r-wasabi,r=3.3.2
[localhost] local: /usr/local/share/bcbio/anaconda/bin/conda info --json
[localhost] local: /usr/local/share/bcbio/anaconda/bin/conda list --json r-tximport
[localhost] local: /usr/local/share/bcbio/anaconda/bin/conda install --quiet -y -c conda-forge -c bioconda age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter ensembl-vep=89.* express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gatk4 gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variant-effect-predictor=87 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli bzip2 ncurses nodejs p7zip readline s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi r=3.3.2
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - ensembl-vep 89.* -> perl 5.22.0*
  - texlive-core
Use "conda info <package>" to see the dependencies for each package.

Fatal error: local() encountered an error (return code 1) while executing '/usr/local/share/bcbio/anaconda/bin/conda install --quiet -y -c conda-forge -c bioconda age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter ensembl-vep=89.* express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gatk4 gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype pandoc parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variant-effect-predictor=87 variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli bzip2 ncurses nodejs p7zip readline s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi r=3.3.2'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Patrick;
Thanks for the report and sorry about the issue. It looks like a recent change to bcftools adds tex as a dependency, which is causing version resolution issues. There are more details in the linked discussion but I'll work on resolving and update here when fixed.

**Comment by mshadbolt** [comment]
same exact error for me. Thanks for looking into it so quickly, will keep an eye out for a fix soon!

**Comment by PatrickJReed** [comment]
Awesome, thanks!

**Comment by chapmanb** [comment]
Thanks everyone for all the reports. I tried to work around the issue until it's fixed in conda by pinning bcftools to a previous build without this problem. If you remove your cached cloudbiolinux:
```
rm -rf tmpbcbio-install
```
and re-run it should hopefully pull bcftools 1.5-0 instead of 1.5-2 and avoid this dependency issue. Please let us know if you still run into any problems.
