### ISSUE TITLE
ensemble 

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#2006]
Hi Brad,

When we use ensemble in the yaml file the final vcf file generated by ensemble has read depth and other filters based on which caller? We are using gatk, gatk-haplotype, freebayes,

Thanks,

**Comment by chapmanb** [comment]
Diya;
There isn't a separate filtering step for the ensemble calls and all of the filters are done at the individual caller level. So each of UnifiedGenotyper, HaplotypeCaller and FreeBayes get run, filtered, then the ensemble calls are made from the post-filter calls from these. Hope this helps.

**Comment by DiyaVaka** [comment]
Hi Brad,

In that case when I open the vcf file (ensemble) it has AD in its headers. From which caller is this coming?

**Comment by chapmanb** [comment]
Diya;
The FORMAT/genotype outputs are a combination from the callers, so is an imperfect way to represent a heterogeneous set of inputs. We haven't yet tried to normalize these to any particular caller so post-processing this might take some custom scripting depending on your caller. I added more documentation on how it selects those here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#ensemble-variant-calling

Hope this helps.
