### ISSUE TITLE
GATK4 GenotypeGVCFs  needs gVCF files pre-combined with GenomicsDBImport 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2012]
Hi, 

I trying to run GATK4 in gVCF mode with 8 test samples in bcbio 1.0.5a0.  
The variant calling with GATK seems to work, I got 8 gVCF files. 

I got stuck at the the GenotypeGVCFs step. First the output argument has changed:
https://github.com/chapmanb/bcbio-nextgen/issues/2010

This is quickly changed in my local bcbio code but then I get stuck with a much bigger issue. 

GATK4 GenotypeGVCFs  requires that the gVCF files are pre-merged using GenomicsDBImport. See this issue at GATK forum:

https://gatkforums.broadinstitute.org/gatk/discussion/9933/how-to-use-multiple-g-vcf-files-in-gatk4-beta-1-genotypegvcfs

After fixing the output argument issue bcbio now crashes on multiple gVCF files being supplied to GATK4 GenotypeGVCFs  

```
***********************************************************************

A USER ERROR has occurred: Argument '[V, variant]' cannot be specified more than once.

***********************************************************************
Use -DGATK_STACKTRACE_ON_USER_EXCEPTIONto print the stack trace.
' returned non-zero exit status 1
[2017-07-20T08:37Z] node9: Unexpected error
Traceback (most recent call last):
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 450, in square_batch_region
    return ipython.zip_args(apply(joint.square_batch_region, *args))
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 126, in square_batch_region
    gatkjoint.run_region(data, region, vrn_files, out_file)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkjoint.py", line 18, in run_region
    return _run_genotype_gvcfs(data, region, vrn_files, dd.get_ref_file(data), out_file)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkjoint.py", line 52, in _run_genotype_gvcfs
    broad_runner.run_gatk(params, memscale=memscale)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 325, in run_gatk
    log_error=log_error)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/bcbio/latest/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/data/bcbio/latest/anaconda/bin:$PATH && gatk-launch --javaOptions '-Xms500m -Xmx28665m -XX:+UseSerialGC -Djava.io.tmpdir=/data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/bcbiotx/tmpKVSMhn' GenotypeGVCFs -R /data/bcbio/latest/genomes/my_species/my_species
/seq/my_species.fa -O /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/bcbiotx/tmpydMWLD/DA_834-Chr_01_8943622_9090387.vcf.gz -L Chr_01:8943623-9090387 --max_alternate_all
eles 4 --variant /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_05.vcf.gz --variant /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/
work/gatk-haplotype/DA_342_07.vcf.gz --variant /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_06.vcf.gz --variant /data/run/Projects/test_bcbi
o_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_01.vcf.gz --variant /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_04.vcf.gz --variant /dat
a/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_08.vcf.gz --variant /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_03.vcf.g
z --variant /data/run/Projects/test_bcbio_1.0.4_gatk/DA_834_bam_table/work/gatk-haplotype/DA_342_02.vcf.gz
```

I think the GenomicsDBImport step needs to be added to bcbio for the GATK4 gVCF workflow to work in bcbio.  This step currently seems not to be present in the bcbio code 
https://github.com/chapmanb/bcbio-nextgen/search?utf8=%E2%9C%93&q=GenomicsDBImport+&type=

Thank you.

**Comment by NeillGibson** [comment]
Using GenomicsDBImport seems straight forward enough from the example in the GATK issue:

> Here are example commands to use it:

```
gatk-launch GenomicsDBImport \
    -V data/gvcfs/mother.g.vcf \
    -V data/gvcfs/father.g.vcf \
    -V data/gvcfs/son.vcf \
    --genomicsDBWorkspace my_database \
    --intervals 20
```

> That generates a directory called my_database containing the combined gvcf data.
> 
> Then you run joint genotyping; note the gendb:// prefix to the database input directory path.

```
gatk-launch GenotypeGVCFs \
    -R data/ref/ref.fasta \
    -V gendb://my_database \
    -G StandardAnnotation -newQual \
    -O test_output.vcf 
```

> And that's all there is to it.
> 
> There are two caveats:
> 
> You can't add data to an existing database; you have to keep the original GVCFs around and >reimport them all together when you get new samples. For very large numbers of samples, there >are some batching options.
> 
> At the moment you can only run GenomicsDBImport on a single genomic interval (ie max one > contig). This will probably change because we'd like to enable running one more intervals in one  > go, but for now you need to run on each interval separately. We recommend scripting this of > course.

**Comment by chapmanb** [comment]
Neill;
Sorry about this, I should have mentioned in our discussion earlier that I haven't yet ported over the gVCF merging code yet. I appreciate all these pointers, this is super helpful for getting started. I'm at Codefest and BOSC the next few days so might not be able to tackle this until early next week if that would work okay. I'm also happy to accept PRs if you've already got it sorted for yourself. Sorry again not to have mentioned this earlier and thanks for testing it all out.

**Comment by NeillGibson** [comment]
Ok no worries, would be nice if this can be fixed somewhere in the coming weeks. Already having the gVCF files being produced is very useful for us to validate GATK4. 

For now I am running GenomicsDBImport and GenotypeGVCFs  outside of bcbio.  I can update this ticket with the steps that I needed to do to get a full multi-sample VCF file that I can run Picard Genotype concordance on. I am not sure I have enough knowledge about how workfows are build in bcbio to make an actual pull request. 

Have fun at Codefest and BOSC the next few days.

**Comment by chapmanb** [comment]
Neill;
Thanks again for testing and pushing on this. I started working on this last night and ended up getting it all finished so the latest development version should do the right thing by going through a GenomicsDB. Hopefully this'll help with testing and validation directly in bcbio. Please let us know if you run into any issues at all.

As of this, the things we knowingly don't support in GATK4 are VQSR and realignment so are getting more feature complete. Thank you again for helping push this forward.

**Comment by NeillGibson** [comment]
Hi Brad, 

Thank you for working on this. FYI GATK4  beta2 is out since yesterday which should fix some bugs, for example a nullpointer issue in GenotypeGVCFs. 

I am still trying to get GenotypeGVCFs to work manually with help of GATK support on my test data. 
Will also try GATK4 via bcbio later on. 

I am not planning on using BQSR, indel realignment or VQSR with GATK4.  So the feature GATK4 feature support in bcbio looks good to me.

**Comment by chapmanb** [comment]
Neill -- thanks for the heads up on the beta2 release. I updated that conda package so your next `--tools` update should pull it in. Thanks again for all this testing work.
