### ISSUE TITLE
Tumor-only somatic configuration

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#2015]
Hi Brad,
I have some tumor-only exome-seq data without matched normal data. But I still intend to call their somatic mutations. I read the online guidelines. It mentions that

For tumor-only samples, bcbio will try to remove likely germline variants present in the public databases like 1000 genomes and ExAC, and not in COSMIC. This runs as long as you have a local GEMINI installation and marks likely germline variants with a LowPriority filter. This post has more details on the approach and validation.

However, I cannot find any yaml template for the tumor-only pipeline. Are there any special requirements for the tumor-only batch file preparation? I will prepare the file merge file as follows,

samplename,description,batch,phenotype,sex
file1.fastq,sample1,batch1,tumor,female
file2.fastq,sample1,batch1,tumor,female
file1.fastq,sample2,batch2,tumor,female
file2.fastq,sample2,batch2,tumor,female

Is it okey if there is no normal sample in the batch?

Should I add any addition parameters into the yaml file that I used for tumor-normal yaml template as follows?

details:
   - analysis: variant2 
     genome_build: GRCh37 
     algorithm: 
       aligner: bwa 
       align_split_size: 5000000 
       mark_duplicates: true
       indelcaller: false
       nomap_split_targets: 100
       platform: illumina
       quality_format: standard
       realign: true 
       recalibrate: true
       remove_lcr: true
       variantcaller: [mutect, freebayes, vardict, varscan]
       ensemble: 
         numpass: 2

Thanks!

**Comment by chapmanb** [comment]
Thanks for the question, there isn't anything special needed for tumor-only germline prioritization other than having GEMINI available. We currently use GEMINI for extracting ExAC and other information, although plan to move to only needing vcfanno soon. So having tumor-only batches or samples (as of the latest development version) is fine.

Practically you don't want to list both fastq files in your template input. bcbio can infer them from supplying a base name to the two files:
```
samplename,description,batch,phenotype,sex
/path/to/sample1_file,sample1,batch1,tumor,female
/path/to/sample2_file,sample2,batch2,tumor,female
```
Hope this gets it working cleanly for you.
