### ISSUE TITLE
Rerun somatic Tumor with different min_allele_fraction Parameter 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2016]
Hi Brad,
I have a question: I have to rerun a tomor/normal paired variant calling project with a lower min_allele_fraction. I still have the work directory. Could you tell me what I should delete to rerun only the minimal possible part of the variant call pipeline?

Thanks for your help.

**Comment by chapmanb** [comment]
Thanks for the question. In general, removing the directories you want to regenerate is all you need to do. So I'd suggest removing any of the top level directories for anything listed in `variantcallers`. If you want to also regenerate gemini databases, remove `gemini` and if you need to redo a validation, remove `validate`. Hope this helps with the re-run.

**Comment by apastore** [comment]
Thanks ! 
Since is an presto large exome project, i was wondering at which level the allele fraction filter is apply and remove only those part of the variantcallers. 

Thanks a lot.

**Comment by chapmanb** [comment]
allellic fraction is a flag passed to the genotypers that support it: FreeBayes, VarDict, MuTect, VarScan. That means you need to clean the full variantcaller directories to let them recall.  Hope this helps.
