### ISSUE TITLE
GATK4 run_genomicsdb call to run_gatk should specify which optinal argument to use

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2021]
Hi, 

The run_genomicsdb method in bcbio should specify which optional argument(s) to use for running GATK. Currently the intended memscale parameter get's used as the tmp dir parameter. 

`java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -Dsnappy.disable=true -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir={direction: increase, magnitude: 9.0} -jar /data/run/Projects/test_bcbio_1.0.5a0_gatk4_beta2/bcbio_install/data_dir/anaconda/share/gatk4-4.0b2-0/gatk-package-4.beta.2-local.jar GenomicsDBImport etc ....`

This causes GenomicsDBImport step to fail. 

_run_genomicsdb_import:
https://github.com/chapmanb/bcbio-nextgen/blob/233c45834006ab955506a30981e943b07c6a665b/bcbio/variation/gatkjoint.py#L46

run_gatk:
https://github.com/chapmanb/bcbio-nextgen/blob/af80cd3166538c04b2b3a02ca4243dc4bef2cf56/bcbio/broad/__init__.py#L315

I am not sure if any of the other optional parameters, like tmp directory are needed and where to get that value from. 

Thank you.

**Comment by chapmanb** [comment]
Neill;
Sorry about the issue and thanks for the detailed report. This was my mistake in porting this over and should be fixed now in the latest development version. Please let me know if you run into any other issues at all.
