### ISSUE TITLE
Bug with strand-specific RNA-Seq quantification - gtf_to_fasta doesn't respect transcript orientation

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2025]
Hi there, I think I've uncovered a bug with the fast RNA-Seq pipeline (and perhaps the regular one). 

Somewhat briefly: when the `gtf_to_fasta` command generates a transcript fasta file from the genome reference and gtf file, it outputs all the fasta records in the genome positive strand orientation, rather than in the orientation of the transcript. This causes the strand-specific quantification estimates in sailfish/salmon to be incorrect. A potential fix would be to use the `gffread` utility already included with bcbio, which properly respects transcript orientation when generating the transcript fasta file.

The longer version: we were running the bcbio 'fast RNA-Seq' pipeline on some stranded RNA-Seq libraries. When I was inspecting salmon's output metrics file (`lib_format_counts.json`) I noticed some strange results:

```
> cat lib_format_counts.json
{
    "read_files": "( /dev/fd/63, /dev/fd/62 )",
    "expected_format": "ISR",
    "compatible_fragment_ratio": 0.5116883390587789,
    "num_compatible_fragments": 2427910,
    "num_assigned_fragments": 4744900,
    "num_consistent_mappings": 6369165,
    "num_inconsistent_mappings": 6964573,
    "MSF": 0,
    "OSF": 5797,
    "ISF": 5530376,
    "MSR": 0,
    "OSR": 6029,
    "ISR": 6369165,
    "SF": 667066,
    "SR": 730466,
    "MU": 0,
    "OU": 0,
    "IU": 0,
    "U": 0
}
```

These metrics are described in the [Sailfish documentation](http://sailfish.readthedocs.io/en/master/library_type.html). Essentially, what these results are saying is that:

- I've specified that I expect the read fragments to be in the 'ISR' format
- Only 51% of the fragments are in the expected orientation
- The fragments are split roughly 50/50 between the 'ISR' and 'ISF' orientations. This is a very implausible result.

I went back to some earlier transcript fasta files from a different project, and re-ran the quantifications (using the version of Salmon bundled with bcbio for the indexing and quantification), and observed more consistent results. 

I then checked the output of the `gtf_to_fasta` program against the tool I'd used previously for this task, `gffread` (which I had from the cufflinks package, and is also there in my bcbio install - presumably because I've installed an appropriate aligner). Looking at the results for transcripts on the _negative_ strand, I confirmed that while `gffread` appropriately reverse-complements the sequence (with respect to the genome), `gtf_to_fasta` does not. See below for a UCSC screenshot:

<img width="970" alt="reverse_orientation" src="https://user-images.githubusercontent.com/1554141/28739446-ed96a95c-73af-11e7-9da1-6dbc3a0f2a24.png">

We've done a bit of testing, and it seems like the quantification results are indeed affected by this (I'm not sure to what extent). Could someone please take a look and potentially correct this? Thanks!

**Comment by rdocking** [comment]
Here's what the results using a transcript fasta generated by `gffread`:

```
{
    "read_files": "( /dev/fd/63, /dev/fd/62 )",
    "expected_format": "ISR",
    "compatible_fragment_ratio": 0.8458915122335994,
    "num_compatible_fragments": 3937839,
    "num_assigned_fragments": 4655253,
    "num_consistent_mappings": 11735383,
    "num_inconsistent_mappings": 1449319,
    "MSF": 0,
    "OSF": 208,
    "ISF": 95266,
    "MSR": 0,
    "OSR": 11382,
    "ISR": 11735383,
    "SF": 91479,
    "SR": 1226047,
    "MU": 0,
    "OU": 0,
    "IU": 0,
    "U": 0
}

```

This shows the expected higher proportion of 'compatible' fragments.

**Comment by roryk** [comment]
Hi Rod,

Thanks for the awesome bug report and sorry for the problem. We almost never see stranded data here so we haven't noticed this behavior. When you ran gtf_to_fasta, were you using the gtf_to_fasta command line tool? Inside of bcbio we have a function called gtf_to_fasta, but it isn't the same thing as the command line tool. The bcbio function is here
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/gtf.py#L111 and you can see it just calls out to gffread.

For the run that looked poor, does the Sailfish/Salmon command line look correct? I'm confused about how we're running in this problem. Thanks so much!

**Comment by rdocking** [comment]
Thanks for your response Rory - that's interesting that it is indeed calling out to gffread. It may be the case that in our testing we were using the command-line gtf_to_fasta rather than the bcbio function. I'll confirm with my colleague and get back to you.

**Comment by roryk** [comment]
Thanks, let me know what you find, like I said we don't get much stranded data at all, so suggestions about how we can improve handling it, even if it ends up moving outside the scope of this issue, would be very much appreciated.

**Comment by roryk** [comment]
Guh, sorry to send you on a wild goose chase. It looks like we were actually calling out to gtf_to_fasta inside of the function we call to merge transcriptomes together and spit out a combined FASTA sequence. I nuked that faulty gtf_to_fasta function and pointed instead to the correct one which uses gffread.

**Comment by roryk** [comment]
This should fix the problem you were seeing now that we're properly using gffread across. the board. Thank you so much! Let me know if you run into anything else or have some other fixes/suggestions.

**Comment by rdocking** [comment]
Nice - thanks for tracking that down so quickly! I'll update and check things again - assume if I don't comment back here that things are fixed. Thanks again.
