### ISSUE TITLE
Unclear instructions on how to install bcbio_vm

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2027]
With a standard install of bcbio, it is not available:

```
bcbio_vm.py -h
bcbio_vm.py: command not found
```

It seems it's not also installable via conda:

```
bcbio_conda install -c bioconda  bcbio-nextgen-vm
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Dependencies missing in current linux-64 channels: 
  - bcbio-nextgen-vm -> arvados-cwl-runner -> arvados-python-client -> google-api-python-client -> httplib2
  - bcbio-nextgen-vm -> arvados-cwl-runner -> arvados-python-client -> google-api-python-client -> oauth2client
  - bcbio-nextgen-vm -> arvados-cwl-runner -> cwltool ==1.0.20160714182449 -> rdflib -> isodate
  - bcbio-nextgen-vm -> arvados-cwl-runner -> cwltool ==1.0.20160714182449 -> rdflib-jsonld
  - bcbio-nextgen-vm -> arvados-cwl-runner -> cwltool ==1.0.20160714182449 -> schema-salad ==1.14.20160708181155
  - bcbio-nextgen-vm -> elasticluster -> ansible
  - bcbio-nextgen-vm -> toil -> gcs-oauth2-boto-plugin ==1.9
  - bcbio-nextgen-vm -> dxpy -> xattr
```

The docs on CWL only mention isolated installations, while I wanted this in parallel to run some CWL workflows with Toil.

**Comment by chapmanb** [comment]
Luca;
Thanks for trying out bcbio_vm and the CWL generation process and apologies for the issues. bcbio-vm is meant to be a separate install -- it handles the CWL generation and workflow running parts, while bcbio_nextgen.py handles the actual execution of the biological code.

So you were installing separately correctly but unfortunately the docs were out of date leading to the dependency issue. If you do:
```
conda install -c conda-forge -c bioconda bcbio-nextgen-vm
```
(so add the conda-forge channel), it should install cleanly. Hope this helps for getting going and please let us know if you have any other questions.
