### ISSUE TITLE
A problem with miRDeep2 for small RNA-seq

### ISSUE THREAD

**Issue by AlessandroGorohovski** [chapmanb/bcbio-nextgen#2029]
Hi bcbio-nextgen team,
Many thanks for your project!

Sorry, for my question.
I try to run small RNA-seq and got following error messages:

<... truncated >
miRDeep2 started at 16:54:35
mkdir mirdeep_runs/run_res
#####################################
#                                   #
# miRDeep2.0.0.7                    #
#                                   #
# last change: 10/12/2014           #
#                                   #
#####################################
miRDeep2 started at 16:54:35
#Starting miRDeep2
Error:  RNAfold not found
Check if RNAfold is correctly installed and all Pathes were set correctly.
If you used the install.pl script make sure that you started a complete new shell window after installation.
If this did not help please restart youer workstation.

' returned non-zero exit status 127
[2017-08-02T13:54Z] mirdeep2 failed. Please report the error to https://github.com/lpantano/mirdeep2_core/issues.

<... truncated >

I'm understanding it is necessary to install RNAfold (eg. from your repository
or from https://www.tbi.univie.ac.at/RNA/index.html#binary_packages)

Sorry, 
How to do it right ?

Yeah, sure I used template YAML file :
$ cat template.yaml
upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star
      # change adapter according project
      adapters: ["TGGAATTCTCGGGTGC"]
      expression_caller: [trna, seqcluster, mirdeep2]
      species: hsa
    description: miRQCa
    genome_build: GRCh37

Many thanks in advance,
Alessandro

**Comment by AlessandroGorohovski** [comment]
Hello Brad,

Oh, Your magic worked,
I'm delighted you!

Many thanks,

But on my way the following problem arose with Java:
<truncated>
`CalledProcessError: Command 'set -o pipefail; JAVA_HOME=/home/morgensternlab/alessandro/.local/share/bcbio/anaconda/bin/.. &&  /data/morgensternlab/ales
sandro/.local/share/bcbio/galaxy/../anaconda/bin/miraligner -Xms750m -Xmx3500m -freq -sub 1 -trim 3 -add 3 -s hsa -i /data/morgensternlab/alessandro/Red
mine/bcbio-nextgen/small_RNA_analysis/mirqc_bcbio/work/trimmed/miRQC_A/SRR950876.clean.trimming.fastq -db /data/morgensternlab/alessandro/.local/share/b
cbio/genomes/Hsapiens/GRCh37/srnaseq  -o /data/morgensternlab/alessandro/Redmine/bcbio-nextgen/small_RNA_analysis/mirqc_bcbio/work/bcbiotx/tmpb_Xfg3/miR
QC_A
Exception in thread "main" java.lang.UnsupportedClassVersionError: miraligner/Main : Unsupported major.minor version 52.0`
<truncated>

I have Java:
`$ java -version`
```
java version "1.7.0_99"
OpenJDK Runtime Environment (rhel-2.6.5.0.el6_7-x86_64 u99-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

and JAVA_HOME is not set:
$ echo $JAVA_HOME

Yeah, I looked:
http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#troubleshooting
But probably something has changed and this documentation is outdated already
and I know that I need to dig deeper.

Maybe you know how to solve this problem correctly?

Thanks in advance,
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Sorry about the continued problems and thank you for the report. bcbio should be using Java 1.8, which it installs, for miraligner but is not for some reason. I re-worked the way this tries to specify java so if you update with:
```
bcbio_nextgen.py upgrade -u development
```
and re-run, hopefully it'll do the right thing and work cleanly. Thanks again for the report and hope this gets the pipeline finished cleanly for you.

**Comment by AlessandroGorohovski** [comment]
Hello Brad,
Here’s the good news!

Yes, I done ` upgrade -u development`, passed all the tests and received cherished results.
Dreams do come true :+1: 

Many thanks,
Alessandro

**Comment by lpantano** [comment]
Hi, sorry about this.

yes, we should use java 8. 

I quick fix is to remove that java 7 from your PATH, I’ll update the code to force to use java from our conda folder. 

Cheers

**Comment by AlessandroGorohovski** [comment]
Hi Lorena,
I hope you're fine.

I do not insist,
perhaps it would be correct to use a newer version miRDeep2.0.0.8
https://www.mdc-berlin.de/8551903/en/research/research_teams/systems_biology_of_gene_regulatory_elements/projects/miRDeep

Trust you,
Alessandro

**Comment by lpantano** [comment]
I am working in moving away of mirdeep2 in the next months, and I can look at the new version to check the main difference. The main problem is that I need to adapt the source code to be compatible with bcbio. I will have some time in the next weeks to work around this, so happy to look if changes are important for the de-novo discovery.

thanks for the head ups
