### ISSUE TITLE
cannot stat `master' when running bcbio_setup_genome.py

### ISSUE THREAD

**Issue by 0xaf1f** [chapmanb/bcbio-nextgen#2040]
```
$ bcbio_setup_genome.py \
>  --cores $SLURM_CPUS_PER_TASK \
>  --fasta human_g1k_v37_no_decoy2.fasta \
>  --name Hsapiens \
>  --build g1k_v37_no_decoy2
--2017-08-14 12:06:28--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving dtn04-e0... 10.1.200.240
Connecting to dtn04-e0|10.1.200.240|:3128... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2017-08-14 12:06:28--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Connecting to dtn04-e0|10.1.200.240|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 5164384 (4.9M) [application/x-gzip]
Saving to: “STDOUT”

100%[=============================================================================================================================>] 5,164,384   4.01M/s   in 1.2s    

2017-08-14 12:06:29 (4.01 MB/s) - written to stdout [5164384/5164384]

mv: cannot stat `master': No such file or directory
Creating directories using /fdb/bcbio-nextgen/current/genomes as the base.
...
```
And it goes on to do samtools and picard and has a successful exit code, but I guess the downloaded cloudbiolinux tarball wasn't used and I'm not sure if that's a problem. I'm running bcbio 1.0.2.

**Comment by chapmanb** [comment]
Thanks for the reports. That's an expected warning message -- the downloaded file can have a couple of different names so we cycle through and try them all, using the one we find for further processing. Are you encountering an error, or just worried about the message?

**Comment by 0xaf1f** [comment]
> Are you encountering an error, or just worried about the message?

The latter. If it's inconsequential, I'd suggest not letting it print to the screen because it looks like how a shell script behaves when return codes aren't being checked for errors before moving on. I wasn't sure whether one of the tasks had failed.

**Comment by chapmanb** [comment]
Thanks much for the feedback. I pushed a fix to the latest development to try the expected case first so it should remove this message and avoid confusion. Thanks again.
