### ISSUE TITLE
age-metasv PackageNotFoundError

### ISSUE THREAD

**Issue by magicsimo** [chapmanb/bcbio-nextgen#2041]
I tried to install bcbio_nextgen on 2 different macs and on a cluster. In each case, I always get the same error (described below), where the package age-metasv seems to be absent. However, I have already installed the package with the following commands: sudo pip install https://github.com/bioinform/metasv/archive/0.5.2.tar.gz

Any help would be really appreciated :)

-----------------
PackageNotFoundError: Packages missing in current channels:
            
  - age-metasv

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

Fatal error: local() encountered an error (return code 1) while executing '/Users/sgiac/Desktop/bcbio/anaconda/bin/conda install --quiet -y  -c conda-forge -c bioconda age-metasv bamtools bamutil bcbio-prioritize bcbio-rnaseq bcbio-variation bcbio-variation-recall bcbreport bcftools bedtools=2.26.0 bio-vcf biobambam bowtie bowtie2=2.2.8 bwa bwakit cage cancerit-allelecount cnvkit cpat cramtools crossmap cufflinks cutadapt cyvcf2 delly dkfz-bias-filter ensembl-vep=89.* express extract-sv-reads fastqc fgbio freebayes=1.1.0 gatk gatk-framework gatk4 gemini geneimpacts genesplicer glpk=4.57 goleft grabix gridss gsort gvcf-regions hap.py hisat2 hmmlearn htseq htslib impute2 kallisto kraken lofreq lumpy-sv macs2 manta maxentscan mbuffer metasv mirdeep2=2.0.0.7 moreutils multiqc multiqc-bcbio ngs-disambiguate novoalign oncofuse optitype parallel pbgzip perl-sanger-cgp-battenberg phylowgs picard pindel platypus-variant pyloh pytabix pythonpy qsignature qualimap rapmap razers3 rtg-tools sailfish salmon sambamba samblaster samtools scalpel sentieon seq2c seqbuster seqtk sickle-trim simple_sv_annotation singlecell-barcodes snap-aligner=1.0dev.97 snpeff=4.3i spades star stringtie subread svtools svtyper tdrmapper theta2 tophat tophat-recondition ucsc-bedgraphtobigwig ucsc-bedtobigbed ucsc-bigbedinfo ucsc-bigbedsummary ucsc-bigbedtobed ucsc-bigwiginfo ucsc-bigwigsummary ucsc-bigwigtobedgraph ucsc-bigwigtowig ucsc-fatotwobit ucsc-gtftogenepred ucsc-liftover ucsc-wigtobigwig umis vardict vardict-java variantbam varscan vawk vcf2db vcfanno vcflib viennarna vt wham anaconda-client awscli bzip2 ncurses nodejs nomkl p7zip readline s3gof3r xz perl-app-cpanminus perl-archive-extract perl-archive-zip perl-bio-db-sam perl-cgi perl-dbi perl-encode-locale perl-file-fetch perl-file-sharedir perl-file-sharedir-install perl-ipc-system-simple perl-lwp-protocol-https perl-lwp-simple perl-statistics-descriptive perl-time-hires perl-vcftools-vcf bioconductor-annotate bioconductor-biocgenerics bioconductor-biocinstaller bioconductor-biocstyle bioconductor-biostrings bioconductor-biovizbase bioconductor-bubbletree bioconductor-cn.mops bioconductor-degreport bioconductor-deseq2 bioconductor-dexseq bioconductor-dnacopy bioconductor-genomicranges bioconductor-iranges bioconductor-limma bioconductor-rtracklayer r-cghflasso r-chbutils r-devtools r-dplyr r-dt r-ggdendro r-ggplot2 r-gplots r-gsalib r-knitr r-pheatmap r-plyr r-pscbs r-reshape r-rmarkdown r-rsqlite r-sleuth r-snow r-stringi r-wasabi r=3.3.2'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 251, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/sgiac/Desktop/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/Users/sgiac/Desktop/bcbio/tools/', '--genomes', 'GRCh37', '--aligners', 'star', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thank you for trying out bcbio and sorry about the issue. We unfortunately don't currently support bcbio runs on OSX since not all of the tools we use are available there. We'd like to have it run on OSX but need some community support to go through and identify missing tools so we could provide either fixed conda builds of these or avoid installing them on OSX. It should install cleanly on clusters or local linux/unix systems. Hope this helps you focus your install efforts and please let us know if you run into any other issues.
