### ISSUE TITLE
Lumpy error (TypeError: %d format)

### ISSUE THREAD

**Issue by eyalbenda** [chapmanb/bcbio-nextgen#2044]
Hi,

I'm trying to run the structural variation pipeline with lumpy. I'm getting an error when lumpy is run. Running manually the call to lumpyexpress gets the error below. I've tried both the development and the stable versions, and getting the same error.

> Sourcing executables from /home/ebendavid/bcbio/anaconda/bin/lumpyexpress.config ...
> 
> Checking for required python modules (/home/ebendavid/bcbio/anaconda/bin/python)...
> 
>     create temporary directory
> Calculating insert distributions... 
> Library read groups: N203
> Library read length: 101
> /home/ebendavid/bcbio/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
>   warnings.warn("Mean of empty slice.", RuntimeWarning)
> /home/ebendavid/bcbio/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
>   ret = ret.dtype.type(ret / rcount)
> Traceback (most recent call last):
>   File "/home/ebendavid/bcbio/anaconda/share/lumpy-sv-0.2.13-0/scripts/pairend_distro.py", line 106, in <module>
>     (removed, upper_cutoff))
> TypeError: %d format: a number is required, not numpy.float64
>

**Comment by chapmanb** [comment]
Eyal;
Sorry about the issues, this error with lumpy is typically due to problems with the input data. It's trying to calculate details on paired end reads and not finding enough information to correctly calculate. You could try replacing `/home/ebendavid/bcbio/anaconda/share/lumpy-sv-0.2.13-0/scripts/pairend_distro.py` with the latest script:

https://github.com/arq5x/lumpy-sv/blob/master/scripts/pairend_distro.py

to see if it behaves better or provides additional details about what might be happening. If that helps at all we could update the lumpy conda package but it's worth checking if it's a sample quality issue first. Hope this helps.

**Comment by eyalbenda** [comment]
Hi,
Thanks for the help. The only thing I can think of re my data is that it is super high coverage (several 100x). could that be an issue for lumpy?

I'm trying the new pairend_distro file and will let you know. Thanks!

**Comment by eyalbenda** [comment]
Hi,

I used the new version of the script and it now progressed further, and got stuck on error: missing pair end parameters mean stdev

Thanks!

Eyal 

> [2017-08-26T19:57Z] Running LUMPY...
[2017-08-26T19:57Z] /home/ebendavid/bcbio/anaconda/bin/lumpy  \
[2017-08-26T19:57Z]     -t /home/ebendavid/bcbiotx/tmph7Ck8E/3-sort-svs.vcf \
[2017-08-26T19:57Z]     -msw 4 \
[2017-08-26T19:57Z]     -tt 0 \
[2017-08-26T19:57Z]      \
[2017-08-26T19:57Z]      -pe bam_file:/home/ebendavid/align/3/3-sort-disc.bam,histo_file:/
home/ebendavid/bcbiotx/tmph7Ck8E/3-sort-svs.vcf.sample1.lib1.x4.histo,mean:NA,stdev:NA,read_len
gth:101,min_non_overlap:101,discordant_z:5,back_distance:10,weight:1,id:3,min_mapping_threshold:20,read_group:3
3 \
[2017-08-26T19:57Z]      -sr bam_file:/home/ebendavid/align/3/3-sort-sr.bam,back_distance:
10,min_mapping_threshold:20,weight:1,id:3,min_clip:20 \
[2017-08-26T19:57Z]     > /home/ebendavid/bcbiotx/tmpM8jSm0/3-sort-svs.vcf
[2017-08-26T19:57Z] missing pair end parameters:mean stdev

**Comment by eyalbenda** [comment]
Well, reading through this error again I figure out I made my sample.csv file incorrectly, and so bcbio was treating it as single end (looking at the config file revealed that).

**Comment by chapmanb** [comment]
Thanks much for debugging and following up with the underlying issue. Glad it all got sorted out and hopefully the re-run works as expected.
