### ISSUE TITLE
Freebayes' wrapper puts samples in different order in multisampling calling and made(makes?) the wrong calls in older versions?

### ISSUE THREAD

**Issue by naumenko-sa** [chapmanb/bcbio-nextgen#2052]
Hello!

I found that freebayes puts samples in multisample vcf in a different order compared to gatk-haplotype, platypus, and samtools.
freebayes:
```
gunzip -c 1168R-freebayes-annotated-decomposed.vcf.gz | grep CHROM
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1168R_17-0296	1168R_17-0297	1168R_17-0295
```
gatk-haplotype and others:
```
gunzip -c 1168R-gatk-haplotype-annotated-decomposed.vcf.gz | grep CHROM
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1168R_17-0295	1168R_17-0296	1168R_17-0297
```
This is bcbio-nextgen,1.0.4, freebayes 1.1.0 and I see that the calls are assigned properly to samples, i.e.:
freebayes:
```
gunzip -c 1168R-freebayes-annotated-decomposed.vcf.gz | grep -v "^#" | head | awk '{print $1"\t"$2"\t"$(NF-2)"\t"$(NF-1)"\t"$NF}' | grep 15211
1	15211	1/1:1,19:19:21:94:319,37,0:424:29:1	1/1:1,16:16:17:85:230,28,0:315:23:1	0/1:5,8:8:13:0:49,0,39:127:120:5
```
gatk-haplotype:
```
gunzip -c 1168R-gatk-haplotype-annotated-decomposed.vcf.gz | grep -v "^#" | head | awk '{print $1"\t"$2"\t"$(NF-2)"\t"$(NF-1)"\t"$NF}' | grep 15211
1	15211	0/1:2,4:6:27:56,0,27	1/1:1,15:16:16:385,16,0	1/1:0,10:10:30:258,30,0

```
So 
genotype(1168R_17-0295) = 0/1
genotype(1168R_17-0296) = 1/1
genotype(1168R_17-0297) = 1/1

But!

It was not always the case. Look at the project processed with bcbio1.0.2a0-de960ca, freebayes 1.1.0, in February 2017.
```
freebayes:
gunzip -c 1106R-freebayes-annotated-decomposed.vcf.gz | grep CHROM
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	1106R_161158	1106R_161156	1106R_161157
gatk-haplotype:
gunzip -c 1106R-gatk-haplotype-annotated-decomposed.vcf.gz | grep CHROM
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT 1106R_161156	1106R_161157	1106R_161158
```
Variants:
```
freebayes:
gunzip -c 1106R-freebayes-annotated-decomposed.vcf.gz | grep -v "^#" |  awk '{print $1"\t"$2"\t"$(NF-2)"\t"$(NF-1)"\t"$NF}'  | grep 44560732
18	44560732	0/1:160:266:125,141:125:4284:141:4666:-340.026,0,-305.664	1/1:160:320:0,320:0:0:320:10510:-945.833,-96.3296,0	0/0:160:314:314,0:314:10958:0:0:0,-94.5234,-986.122
gatk-haplotype:
gunzip -c 1106R-gatk-haplotype-annotated-decomposed.vcf.gz | grep -v "^#" |  awk '{print $1"\t"$2"\t"$(NF-2)"\t"$(NF-1)"\t"$NF}'  | grep 44560732
18	44560732	0/1:120,140:260:99:3979,0,3253	1/1:0,312:312:99:10474,933,0	0/0:307,0:307:99:0,913,10477
```
So here freebayes reports
genotype(1106R_161158) = 0/1
genotype(1106R_161156) = 1/1
genotype(1106R_161157) = 0/0

While gatk-haplotype reports
genotype(1106R_161156) = 0/1
genotype(1106R_161157) = 1/1
genotype(1106R_161158) = 0/0

And all calls from freebayes are misleading, because other tools report the same calls as gatk-haplotype?
			
Could you please comment, whether this issue has been solved and when (1.0.3?). Were the ensemble calls incorrect too, when freebayes was on the first place in the list? 

Thanks!
Sergey

**Comment by chapmanb** [comment]
Sergey;
Apologies about this issue. FreeBayes did change sample ordering to be inconsistent with the introduction of the SeqLib wrapper, and we fixed this in the post-1.0.2 development cycle and released it in 1.0.3. It would have potentially caused issues with any calls using FreeBayes including ensemble outputs. Apologies about this and please let us know if you hit any problems with the latest production or development versions.
