### ISSUE TITLE
feature: goleft indexcov output in multiqc report

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2053]
Hi Brad,

Would it be possible to include the output of goleft indexcov in the multiqc report? This is already supported by multiqc natively and would be a nice addition to an already awesome report.

Thanks!
M

**Comment by chapmanb** [comment]
Matthias;
I'll have to dig into this more as it should work. I wrote the MultiQC goleft indexcov module to integrate with bcbio, so it did work at some point so I'm not sure what happened to make it stop functioning. To troubleshoot, does your project have goleft output in `coverage/sample/indexcov`? indexcov doesn't always work with smaller panels and exome data, which could explain it for a specific sample. Thanks for the help debugging.

**Comment by matthdsm** [comment]
Hi Brad, 

Thanks for the reply. The only output we have in`coverage/sample/indexcov` is the one from `sambamba`, so no `indexcov`.

I noticed there was some code related to `indexcov` and `MultiQC`, but I've never really seen any output from it. I'll try and play around with some more settings and files. Since we only have exome data, this could be the cause.

Thanks again
M

**Comment by chapmanb** [comment]
Matthias;
Sorry, that's my mistake. You'd expect to see the files in the QC directory `qc/sample/coverage/indexcov`. Practically indexcov works best on whole genome BAMs as the data in the index isn't defined enough to give a ton of information on exomes or panels, so may not produce any output. If you see indexcov output and it's not going into MultiQC definitely feel free to reopen and we can investigate more.
