### ISSUE TITLE
bcftools concat fails: 

### ISSUE THREAD

**Issue by amizeranschi** [chapmanb/bcbio-nextgen#2056]
Hello,

I am running a somatic variant calling pipeline and running into problems at the "concat_variant_files" stage:

> [2017-08-31T14:12Z] multiprocessing: variantcall_sample
> [2017-08-31T14:12Z] multiprocessing: concat_variant_files
> [2017-08-31T14:12Z] Prepare header file for merging
> [2017-08-31T14:12Z] Reheader initial VCF file in merge
> [2017-08-31T14:12Z] Prepare header file for merging
> [2017-08-31T14:12Z] Reheader initial VCF file in merge
> [2017-08-31T14:12Z] tabix index P10-S1S-som-chrI_0_162230-fixheader.vcf.gz
> [2017-08-31T14:12Z] Resource requests: ; memory: 1.00; cores: 1
> [2017-08-31T14:12Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
> [2017-08-31T14:12Z] tabix index P10-S3S-som-chrI_0_162230-fixheader.vcf.gz
> [2017-08-31T14:12Z] Resource requests: ; memory: 1.00; cores: 1
> [2017-08-31T14:12Z] Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
> [2017-08-31T14:12Z] bcftools concat variants
> [2017-08-31T14:12Z] bcftools concat variants
> [2017-08-31T14:12Z] [W::vcf_parse] FILTER 'REJECT' is not defined in the header
> [2017-08-31T14:12Z] [E::bcf_translate] Unchecked error (2), exiting
> [2017-08-31T14:12Z] Uncaught exception occurred
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; /storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/bin/bcftools concat --allow-overlaps -O z --file-list /storage/brno3-cerit/nfs4/home/amizeranschi/allDNA/allDNA-somatic-cnv-small/work/scalpel/P10-S1S-som-files.list -o /storage/brno3-cerit/nfs4/home/amizeranschi/allDNA/allDNA-somatic-cnv-small/work/bcbiotx/tmpjKSoFI/P10-S1S-som.vcf.gz
> [W::vcf_parse] FILTER 'REJECT' is not defined in the header
> [E::bcf_translate] Unchecked error (2), exiting
> ' returned non-zero exit status 1
> [2017-08-31T14:12Z] [W::vcf_parse] FILTER 'REJECT' is not defined in the header
> [2017-08-31T14:12Z] [E::bcf_translate] Unchecked error (2), exiting
> [2017-08-31T14:12Z] Uncaught exception occurred
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; /storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/bin/bcftools concat --allow-overlaps -O z --file-list /storage/brno3-cerit/nfs4/home/amizeranschi/allDNA/allDNA-somatic-cnv-small/work/scalpel/P10-S3S-som-files.list -o /storage/brno3-cerit/nfs4/home/amizeranschi/allDNA/allDNA-somatic-cnv-small/work/bcbiotx/tmpowjIFu/P10-S3S-som.vcf.gz
> [W::vcf_parse] FILTER 'REJECT' is not defined in the header
> [E::bcf_translate] Unchecked error (2), exiting
> ' returned non-zero exit status 1
> Traceback (most recent call last):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/tools/bin/bcbio_nextgen.py", line 234, in <module>
>     main(**kwargs)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/tools/bin/bcbio_nextgen.py", line 43, in main
>     run_main(**kwargs)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
>     fc_dir, run_info_yaml)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 142, in variant2pipeline
>     samples = genotype.parallel_variantcall_region(samples, run_parallel)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 193, in parallel_variantcall_region
>     "vrn_file", ["region", "sam_ref", "config"]))
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 35, in grouped_parallel_split_combine
>     parallel_fn(combine_name, combine_args)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
>     return run_multicore(fn, items, config, parallel=parallel)
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
>     for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 812, in __call__
>     self.retrieve()
>   File "/storage/brno3-cerit/home/amizeranschi/bcbio2/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 749, in retrieve
>     exception = exception_type(report)
> TypeError: __init__() takes at least 3 arguments (2 given)

I tried rerunning the pipeline after the first crash, and it always hangs at this stage. I am using a freshly installed copy of Bcbio (installed several days ago). 

This is the first time I see this error in Bcbio. How could I get this analysis to finish successfully?

**Comment by chapmanb** [comment]
Sorry about the issue, I'm not sure what happened here. bcbio tries to be sure it uses a non-empty VCF header for the first input (hence the `fixheader` VCF file) specifically to avoid this. 

It looks like this is a problem with scalpel -- do you need this for your analysis? This is a tool we haven't done a lot of work on recently so may have some edge cases like this. For indel calling in somatic samples I can recommend using VarDict, FreeBayes and MuTect2 (from GATK4, with `tools_on: [gatk4]`. Would those work for your needs?

**Comment by amizeranschi** [comment]
The surprising thing is, Scalpel used to work for me, on the same data, using a slightly older version of Bcbio (installed approx. 2-3 months ago). So my guess is that whatever "broke" Scalpel is related to a recent patch.

Interesting that you recommend MuTect2 from GATK4. I did not realize GATK4 was ready for production already. Thank you for mentioning it.

I retried the Bcbio run and it seems that leaving out Scalpel has allowed it to finish successfully.

**Comment by chapmanb** [comment]
I'm glad that swapping over to MuTect2 in GATK4 works for you and thanks for following up on this. I think recent versions of bcftools have gotten more strict in header parsing which likely explains the differences. You could also try the latest development version with scalpel since it replaces bcftools with equivalent GATK4 functionality. Please let us know if you run into any other problems.
