### ISSUE TITLE
verifybamid

### ISSUE THREAD

**Issue by DiyaVaka** [chapmanb/bcbio-nextgen#2058]
Hi Brad,

I see in the anoconda documentation the list of the packages has verifybamid, what is the way i could mention it in the sample.yaml

**Comment by chapmanb** [comment]
Diya;
This isn't integrated into bcbio right now. We added it to the tools as we were exploring it and found it generally useful for folks to have for custom usage outside of bcbio. Sorry to not have this integrated and ready to run but hope this helps.
