### ISSUE TITLE
Problems with updating for vcfanno resource files

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2066]
Hi guys,

  We're having a bit of an issue getting `vcfanno` to work correctly. I'm seeing an issue very similar to  #1974 , but it doesn't seem to be resolving itself upon running `bcbio_nextgen.py upgrade --data`.

  This manifests itself when `vcfanno` runs since the resource file it's expecting doesn't exist:

```
[2017-09-06T00:13Z] vcfanno.go:112: [Flatten] unable to open file: /projects/rdocking_prj/software/bcbio-nextgen/bcbio/gemini_data//projects/rdocking_prj/software/bcbio-nextgen/bcbio/gemini_data/clinvar_20170130.tidy.vcf.gz in /projects/rdocking_prj/software/bcbio-nextgen/bcbio/gemini_data
```

  In `bcbio/genomes/Hsapiens/hg19/config/vcfanno/gemini.conf`, I see:

```
[[annotation]]
file="clinvar_20170130.tidy.vcf.gz"
fields=["CLNSIG", "CLNDBN"]
names=["clinvar_pathogenic", "clinvar_disease_name"]
ops=["self", "self"]
```

  While in the `gemini_data` directory I see the older version:

```
/projects/rdocking_prj/software/bcbio-nextgen/bcbio/gemini_data/> ls -lh clinvar_20160203.tidy.vcf.gz*
-rw-r--r-- 1 rdocking karsanlab 5.8M Feb 19  2016 clinvar_20160203.tidy.vcf.gz
-rw-r--r-- 1 rdocking karsanlab 105K Feb 19  2016 clinvar_20160203.tidy.vcf.gz.tbi
```
  
  When I run `bcbio_nextgen.py upgrade --data` I see several errors like this:

```
INFO: Downloading genome from s3: sacCer3 twobit
[localhost] local: pwd
[localhost] local: wget --continue --no-check-certificate -O sacCer3-twobit.tar.xz 'https://s3.amazonaws.com/biodata/genomes/sacCer3-twobit.tar.xz'
--2017-09-07 14:44:00--  https://s3.amazonaws.com/biodata/genomes/sacCer3-twobit.tar.xz
Resolving s3.amazonaws.com... 52.216.86.69
Connecting to s3.amazonaws.com|52.216.86.69|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-07 14:44:01 ERROR 404: Not Found.


Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O sacCer3-twobit.tar.xz 'https://s3.amazonaws.com/biodata/genomes/sacCer3-twobit.tar.xz''

INFO: Genome preparation method s3 failed, trying next
```

... which make me suspect something has gone wrong with some of my config files. As well, at the end, I see:

```
Gemini data files updated
You have the latest version 2014-12-08 23:29:51+00:00.
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.
```

... which also seems suspicious. Any pointers on how I can fix this? Thanks again for all your help.

**Comment by chapmanb** [comment]
Rod;
Sorry about the issues. It seems like you might have an old version of gemini, either in your bcbio installation or somewhere else on your system. The gemini data downloads are linked with the gemini version so that's likely the reason you're not getting the updated files for vcfanno.

If you run `bcbio_nextgen.py upgrade --tools`, do you get a new version of gemini so that re-running the data downloads grabs those files? If not, is it possible there is another gemini version somewhere on your system it's picking up before the bcbio one?

The other download errors are expected for genomes like sacCer3 where we don't have pre-built indices and create them on the fly on your machine. Sorry for the noisey logs but those aren't issues.

Hope this helps figure out the issue.

**Comment by rdocking** [comment]
Hi Brad - thanks so much for your help! I think you've pointed me in the right direction. After a bit of poking around, I found that I'd somehow installed another version of `gemini` using `pip`, which was getting in the way of the `conda` version:

```
/projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda/bin/> ./conda list gemini
# packages in environment at /projects/rdocking_prj/software/bcbio-nextgen/bcbio/anaconda:
#
gemini                    0.20.0                    <pip>
gemini                    0.20.1                   py27_0    bioconda
```

After removing the pip-installed version, the `bcbio_nextgen.py upgrade --tools --data` command seems to have picked up the proper revised annotation files. 

Thinking back, this was almost certainly something I was fiddling with myself (installing different versions of gemini), so not any issue with bcbio.

Thanks again!
