### ISSUE TITLE
GATK gVCF varint calling runs into "Cannot force gVCF output and use VQSR" assertion

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2069]
Hi, 

I am evaluating GATK4 beta4 gVCF variant calling via bcbio. 

Creation of the gVCF files and merging the gVCF files via GenomicsDBImport and GenotypeGVCFs seems to work now. 

In the `gatk-haplotype-joint` directory I now have 1 VCF file that has circa the expected the number of vairants and genotypes for the my test samples. 

Filtering of this multi-sample VCF file seems to run into this assertion being false:
https://github.com/chapmanb/bcbio-nextgen/blob/05f085c7f39985e6433fe9f8df7d9c228efe37ff/bcbio/variation/gatkfilter.py#L21

```
 File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 79, in postprocess_variants
    data, orig_items)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/genotype.py", line 35, in variant_filtration
    return gatkfilter.run(call_file, ref_file, vrn_files, data)
  File "/workspace/my_user/tmp_bcbio_latest4/data_dir/anaconda/lib/python2.7/site-packages/bcbio/variation/gatkfilter.py", line 21, in run
    ("Cannot force gVCF output and use VQSR. Try using cutoff-based soft filtering with tools_off: [vqsr]")
AssertionError: Cannot force gVCF output and use VQSR. Try using cutoff-based soft filtering with tools_off: [vqsr]
```

I did not explicitly put VQSR filtering on or of. Is the tools on gVCF the issue? Or is this a bug in the the current bcbio code? Any way to make this analysis continue? Thank you.
```
# Template for whole genome Illumina variant calling with GATK4 beta4
---
details:
  - analysis: variant2
    genome_build: my_reference
    description:
    # to do multi-sample variant calling, assign samples the same metadata / batch
    metadata:
      batch: GATK4_beta4_test
    algorithm:
      aligner: false
      mark_duplicates: false
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      jointcaller: gatk-haplotype-joint
      ploidy:
          default: 2
      nomap_split_targets: 3000
      effects: false
      tools_on: [gatk4,gvcf]
      tools_off:
      - gemini
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
```

**Comment by chapmanb** [comment]
Neill;
Sorry about the issue. If you're doing jointcalling you don't need to specify the `tools_on: [gvcf]` component. That was initially added to force gVCF calling when folks weren't doing joint calling and the sanity check is there to avoid trying to run VQSR on a raw gVCF (which doesn't work).

Sorry I know this is confusing and I'm working to make them work together. If you update to the latest development version, it should work cleanly, or you can remove `gvcf` from `tools_on` in your configuration.

Thanks for testing this and let me know if you run into anything else at all.
