### ISSUE TITLE
mixup_check: false still runs qsignature

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2071]
As the subject says, I need to skip it because of issues within the data, however even setting it false (and a cursory look at the code seems to confirm it) will not matter, because it will be inconditionally run.

**Comment by roryk** [comment]
Hi Luca,

Sorry about that. Hmm--  I think it should skip it when it is set to false, there's a check here https://github.com/chapmanb/bcbio-nextgen/blob/5a03091d70f339f18789d03f4df3e5c2687d0724/bcbio/qc/qsignature.py#L38-L39  that should cover it. 

I ran it on one of the integration test datasets, with it ```mixup_check: qsignature``` it gets inside the function and then skips it in the tests since they aren't set up to run it:

```
test_automated_output/log/bcbio-nextgen.log:[2017-09-13T16:20Z] There is no qsignature for this species: hg19
```

and with ```mixup_check: false``` it bails out before running even that much. Are you seeing different behavior? Thanks!

**Comment by lbeltrame** [comment]
It is inconditionally run as part of the summary, if you use things like the `variant2` pipeline (bcbio/pipeline/qcsummary.py):

```python
if analysis.startswith(("standard", "variant", "variant2")):
    to_run += ["qsignature", "coverage", "variants", "picard"]
    if vcfutils.get_paired([data]):
```

**Comment by chapmanb** [comment]
Luca -- that's right but the actual QC code should skip doing any work if you don't have qsignature set:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/qc/qsignature.py#L20

What error are you running into? It might help to see the stack trace so we can understand what is happening and how to avoid the issue. Thanks for the help debugging.

**Comment by lbeltrame** [comment]
From what I understood in the code, it only checks if it's available in the path, rather than disabled. Or did I misunderstand how the function works?

The error I have is data-specific, and is due to a peculiar set of data I'm using to check RNA editing on (I bent the rules already a lot, so I know I'm in uncharted territory). qsignature crashes on it, so I needed to skip that part. The only way  I could get bcbio to skip  qsignature was to  remove it from `to_run`.

**Comment by chapmanb** [comment]
Luca;
This is the specific line where it should skip doing any work `mixup_check` is not set:

https://github.com/chapmanb/bcbio-nextgen/blob/dd31b8fc72125faf462c379713695e8bd79e135d/bcbio/qc/qsignature.py#L39

Sharing the stack trace might help us see where and how it gets run and causes the issue. From reading the code it should skip it but that is not the behavior you're seeing so happy to figure out how to get it fixed for your case with more details.

**Comment by lbeltrame** [comment]
As I got rid of the `work` directory to save space, I won't be able to reproduce this any time soon. I'll close it down for now and reopen if it manifests again. Sorry for the incomplete information.

**Comment by roryk** [comment]
Thanks Luca, hopefully this was a one off.
