### ISSUE TITLE
tmp dir on torque (ERR): mkfifo(/tmp/23457.inpipe1) failed.

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2074]
Hi Brad, I have got this error when the /tmp/ is not accessible on a computing node.
Do you think that writing in the job $TMPDIR would not be better?

Thanks!

CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /cbio/ski/abdelwao/nobackup/pastore/bcbio/galaxy/../anaconda/bin/bowtie2 -q -x /cbio/ski/abdelwao/nobackup/pastore/bcbio/genomes/Hsapiens/GRCh37/bowtie2/GRCh37 -X 2000 -1 /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/CLL/ATAC/sagar/input/Chr1814-PT43-1-AT-A-AGGCAGAA_AGGCAGAA_AC9528ANXX_L004_001.R1.fastq.gz -2 /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/CLL/ATAC/sagar/input/Chr1814-PT43-1-AT-A-AGGCAGAA_AGGCAGAA_AC9528ANXX_L004_001.R2.fastq.gz --rg-id PT43-1 --rg SM:PT43-1 --rg PL:illumina --rg PU:11_2017-09-13_sagar -p 16 | bamsormadup inputformat=sam threads=16 tmpfile=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/CLL/ATAC/sagar/bcbiotx/tmpLBje9s/PT43-1-sort-sorttmp-markdup SO=coordinate indexfilename=/cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/CLL/ATAC/sagar/bcbiotx/tmpLBje9s/PT43-1-sort.bam.bai > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/CLL/ATAC/sagar/bcbiotx/tmpLBje9s/PT43-1-sort.bam
(ERR): mkfifo(/tmp/23457.inpipe1) failed.

**Comment by chapmanb** [comment]
Sorry about the issue with this. bcbio isn't doing anything special here in terms of temporary file usage and is just using standard unix pipes to avoid too much disk IO. I'm not an expert on unix pipes but from a bit of Google research I don't see an obvious way to avoid creating these within the `/tmp` directory. Is it possible to discuss with your sysadmins to have `/tmp` available and accessible to users for use of piping?

Sorry to not have a way to adjust this but hope this helps.

**Comment by apastore** [comment]
Sure Brad!

This is a rare error on my system. I believe had something to do with high usage, or bandwidth that make tmp/ folder not available. 

On that run I had ~400 cores and one tmp error. 

Thanks for your help!
Alessandro

**Comment by chapmanb** [comment]
Alessandro;
Thanks for following up and glad it's not a persistent problem. Please feel free to reopen if you discover anything we can tweak in bcbio to help with this.
