### ISSUE TITLE
1000 genomes data is not added to vcf2db when doing hg38

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2075]
I'm not sure this is a VEP bug or something else, but in the latest runs I did with hg38 there's no `aaf_1kg` in the VEP annotations. 
EDIT: I see the data in the CSQ field. I need to investigate why vcf2db isn't picking it up (or vcfanno not annotating it).

**Comment by lbeltrame** [comment]
As far as I understand, this is because there is currently no equivalent data for hg38: what's there for hg19 comes from GEMINI. Am I correct?

**Comment by chapmanb** [comment]
Luca;
Thanks for starting this discussion. That's right, all of the hg19 resources are not necessarily available or prepared for hg38 yet. We haven't done 1000 genomes, although digging now it looks like they've prepared a liftover version:

http://www.internationalgenome.org/announcements/updated-GRCh38-liftover/

I know they also realigned to build 38 but don't see a set of native calls yet.

A lot of folks now use ExAC and gnomad for what 1000 genomes provided earlier, so we've focused so far on including those. Is 1000 genomes useful beyond what those resource supply?

**Comment by lbeltrame** [comment]
Probably not. I just noticed that because it was the first hg38 database that ended on my plate. `max_af_all`  is probably more useful for what I have in mind.
