### ISSUE TITLE
Feature request: add gene-level expression output for Salmon

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2077]
Hi there - I've got a (hopefully small-ish) feature request. When bcbio runs `salmon`, currently only isoform-level quantifications are output. It would be nice if gene-level quantifications were also part of the output - sometimes this allows for a simpler downstream analysis.

I took a quick look at the current call signature for `salmon` in the 'fast RNA-Seq' pipeline, which looks (roughly) like this:

```
salmon quant -l ISR \
	-i work/salmon/index/hg19 \
	-p 8 --gcBias -o data/salmon_default \
	-1 <(gzip -cd lib_1.fq.gz) \
	-2 <(gzip -cd lib_2.fq.gz) \
	--numBootstraps 30
```

To get the gene-level estimates, the `--geneMap` argument needs to be added like so:

```
salmon quant -l ISR \
	-i work/salmon/index/hg19 \
	-p 8 --gcBias -o data/salmon_default \
	-1 <(gzip -cd lib_1.fq.gz) \
	-2 <(gzip -cd lib_2.fq.gz) \
	--numBootstraps 30 \
        --geneMap bcbio-nextgen/bcbio/genomes/Hsapiens/hg19/rnaseq/ref-transcripts.gtf
```

In this case, the 'gene map' is the GTF file installed along with bcbio. In my (single, small) test, this only added ~30s to the runtime for Salmon.

Would be feasible to add this? If not, I can test trying to add this argument in the 'resources' section of my YAML config file.

Thanks!

**Comment by roryk** [comment]
Hi Rod,

Thanks for the suggestion! We've been handling the transcript->gene level conversion with tximport (http://bioconductor.org/packages/release/bioc/html/tximport.html) which uses the txgene.csv file that bcbio outputs to collapse the Salmon/Sailfish/kallisto/etc counts down into gene level counts. We have a package (https://github.com/hbc/bcbioRnaseq) that does all of this and sets up the initial QC analysis that we've been using and should be up on bioconductor soon. The plan is to do the initial import and QC with that package automatically in bcbio with the packages and spit out an R object folks can then use downstream to do their analysis. Would that work?

**Comment by rdocking** [comment]
Awesome - that seems to be a much more general solution than what I was suggesting. I wasn't aware of bcbioRnaseq - that looks like it'll handle a lot of what I was looking for. We've got some samples coming in that will be a great fit for this package - I'll try it out and let you know if we have issues.

I'll close this for now - thanks for your response!

**Comment by roryk** [comment]
Thanks-- let us know if you have problems getting bcbioRnaseq up and running, we're still working on it a bit but we've been using it for projects. It would be helpful to have someone external using it as well.

**Comment by rdocking** [comment]
Here's a quick trip report:

- I noted that the `tx2gene.csv` file was created for the regular RNA-Seq pipeline, but not the fast RNA-Seq pipeline (this is fine - I realized I wanted the QC reports from the regular pipeline anyways)
- I was able to install and load the `bcbioRnaseq` package without issue
- In RStudio (Version 1.1.338 on Mac OS X 10.11.6), I wasn't able to see the report templates using the recommended approach (File -> New File -> R Markdown... -> From Template)
- But, I found the report templates in the package directory, and a little bit of messing with the paths and options to match my experimental design, I was able to generate both the QC and DE reports.

Very impressive overall - thanks!

**Comment by roryk** [comment]
Thanks so much Rod, that is super helpful feedback. Is it cool if I copy that over to bcbioRnaseq and open up an issue there so folks can fix some of the problems/add to the documentation?

You're right about the fast-RNAseq pipeline. It's hard to create that tx2gene.csv file for the fast RNA-seq pipeline, because all we require is a FASTA file and we don't have any restrictions on its format so we have no way of figuring out which transcripts go with what. We use that when someone comes to us with some super fast deadline and we just need to churn out some data without all the bells and whistles.

**Comment by rdocking** [comment]
> Is it cool if I copy that over to bcbioRnaseq and open up an issue there so folks can fix some of the problems/add to the documentation?

Of course, please go ahead!
