### ISSUE TITLE
Bug with GATK4 in RNA-Seq

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2080]
Hi guys - I was giving a quick test to trying out GATK4 within the RNA-Seq pipeline, and came across this issue. It looks like GATK4 expects different options for specifying the output compared to GATK3. 

i.e., in [gatk.py](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/gatk.py):

```
if gatk_type == "gatk4":
                params += ["--output", tx_out_file]
            else:
                params += ["-o", tx_out_file]

```

While in [rnaseq/variation.py](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/variation.py):

```
with file_transaction(data, split_bam) as tx_split_bam:
        params = ["-T", "SplitNCigarReads",
                  "-R", ref_file,
                  "-I", deduped_bam,
                  "-o", tx_split_bam,
                  "-rf", "ReassignOneMappingQuality",
                  "-RMQF", "255",
                  "-RMQT", "60",
                  "-rf", "UnmappedRead",
                  "-U", "ALLOW_N_CIGAR_READS"] + quality_flag
```

I think this is causing the RNA-Seq pipeline to crash on variant-calling with GATK4. Does that sound correct?

**Comment by rdocking** [comment]
Hi Brad - thanks so much for taking a crack at this! I'll give it a try and report back if I run into any issues. 

I'm interested generally in calling variants from RNA-Seq data as part of my analysis pipelines - I've used the general bcbio alignment/variant calling pipeline (starting from STAR- and gsnap-aligned BAM files). As you might expect, there are definitely artefacts and gotchas that result from doing this, but I'm not sure whether those are best handled by maintaining separate RNA-seq variant calling workflows, or handling it on the post-processing side.

**Comment by roryk** [comment]
Thanks Rod, we have a proposal brewing to try to improve the RNA-seq variant calling in bcbio, if we end up getting funded for that work the calling should be a more full featured than it is now. Right now we call with default filters, try to mark the edits and then leave it at that. In the meantime, we would be happy to incorporate whatever improvements you think would be helpful. Thanks for testing this stuff out.
