### ISSUE TITLE
Error installing bcbio in antegros linux (arch)

### ISSUE THREAD

**Issue by eyalbenda** [chapmanb/bcbio-nextgen#2084]
I'm trying to install bcbio to my antegros linux build, and I get an error (see below).
Is it possible to make bcbio recognize arch linux? 

> 
> Exception: Attempt to automatically determine Linux distribution of target machine failed:
> antergos linux release 17.9 (iso-rolling)
> name="antergos linux"
> version="17.9-iso-rolling"
> id="antergos"
> id_like="arch"
> pretty_name="antergos linux"
> cpe_name="cpe:/o:antergosproject:antergos:17.9"

**Comment by chapmanb** [comment]
Eyal;
Thanks for the heads up. I pushed a fix to CloudBioLinux which should handle this if you remove the temporary download (`rm -rf tmpbcbio-install`) and rerun it should hopefully recognize it and install cleanly. Thanks again.
