### ISSUE TITLE
Dockerfile build error

### ISSUE THREAD

**Issue by sib-bcf** [chapmanb/bcbio-nextgen#2090]
Hello,
I'm trying to build a docker image from the Dockerfile that I've download directly from the repository. 

The bcbio installation stop with an error about some conda dependencies:

`
UnsatisfiableError: The following specifications were found to be in conflict:
  - libedit
  - perl-sanger-cgp-battenberg
  - r 3.3.2*
Use "conda info <package>" to see the dependencies for each package.`

Do you have any suggestion on how to fix this issue?

Thank you in advance for your help

**Comment by snashraf** [comment]
I have the same issue as well !! I was trying to install bcbio using below command.

python bcbio_nextgen_install.py /gpfs/home/nsyed/bcbio --tooldir=/gpfs/projects/bioinfo/najeeb/tools/  --genomes GRCh37 --aligners bwa --isolate

**Comment by chapmanb** [comment]
Thanks much for the heads up on the problem. It looks like there is an incompatibility between the latest conda versions and bioconda and conda-forge that we use for packaging, related to pinning to ncurses. I pushed a fix which should work around the problem. A Docker rebuild should work now and for a local install please remove your local cached cloudbiolinux with `rm -rf tmpbcbio-install` and then a re-run in place should work.

I've triggered a rebuild of the full docker that we distribute on Docker hub:

https://hub.docker.com/r/bcbio/bcbio/

and as an FYI we've been moving to an automated process tied with smaller method specific images:

https://github.com/bcbio/bcbio_docker

so one of those pre-built options might work for your needs. Thanks again for the report and please let us know if you run into any problems.
