### ISSUE TITLE
Detecting indels with Scalpel fails

### ISSUE THREAD

**Issue by HLAmolec** [chapmanb/bcbio-nextgen#2092]
Hello,

I trying to use Scalpel to detect somatic deletion/insertion on BWA-MEM aligned .bam files generated from Ion Torrent amplicon based Next-Gen assay.  I've made small region specific .bam files with samtools.  The test bam files contains an insertion.
I've tried running the following command;
scalpel-discovery --single --bam /data/scalpel/DL-12-10012_IonXpress_001_region_KIT_e11.bam --ref /data/scalpel/chr4.fa --bed 4:55593527-55593779
An empty vcf was generated.
I ran Pindel on the same files and it detected most of the indels. 
 Could someone please suggest how to use Scalpel to detect indels? I've heard it's a good tool but it doesn't seem to be working.

Thanks

**Comment by chapmanb** [comment]
Thanks for the questions, we do have scalpel support in bcbio although I personally haven't used it regularly, and also don't have practical experience with Ion data. It sounds like you might want to stick with the IonTorrent ready tools or Pindel. If you'd like to explore more, I believe lancet is the successor to scalpel (https://github.com/nygenome/lancet) so it might be worth providing a reproducible example for @gnarzisi so he can offer more specific advice. Sorry to not have a definite answer but hope this helps.
