### ISSUE TITLE
Bug in check for paired normal sample or background VCF

### ISSUE THREAD

**Issue by ameynert** [chapmanb/bcbio-nextgen#2095]
https://github.com/chapmanb/bcbio-nextgen/blob/a857c820e566cda0a24eff5291e8acb5bab7e2cc/bcbio/variation/vcfutils.py#L115

Fix:
```
if not (paired.normal_data or paired.normal_panel):
```

**Comment by chapmanb** [comment]
Alison -- thanks so much for catching this.
