### ISSUE TITLE
KeyError: 'NC_007605'

### ISSUE THREAD

**Issue by snashraf** [chapmanb/bcbio-nextgen#2097]
Hi Team ,

I am getting below error 

Traceback (most recent call last):
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 235, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 232, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/bam/callable.py", line 37, in sample_callable_bed
    callable_bed = coverage.calculate(bam_file, data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 88, in calculate
    callable_file = _mosdepth_to_callable(depth_file, params, data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 110, in _mosdepth_to_callable
    writer.writerow([cur_chrom, start_pos, contig_sizes[cur_chrom], cur_callable])
KeyError: 'NC_007605'
[2017-10-11T07:51Z] nsnode25: Unexpected error
Traceback (most recent call last):
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 235, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 232, in postprocess_alignment
    covinfo = callable.sample_callable_bed(bam_file_ready, ref_file, data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/bam/callable.py", line 37, in sample_callable_bed
    callable_bed = coverage.calculate(bam_file, data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 88, in calculate
    callable_file = _mosdepth_to_callable(depth_file, params, data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/variation/coverage.py", line 123, in _mosdepth_to_callable
    writer.writerow([cur_chrom, start_pos, contig_sizes[cur_chrom], cur_callable])
KeyError: 'hs37d5'

It seems this error is coming due to some of the contigs like NC_007605' and hs37d5 in BAM files. So Can you please suggest how to avoid this error as this is failing all my jobs to fail. 

Thanks 
Najeeb

**Comment by chapmanb** [comment]
Najeeb;
Sorry about the issue, it looks like you might be using a pre-aligned BAM with different contigs from the reference genome. The latest development version was reworked and should hopefully handle this correctly. If you do:
```
bcbio_nextgen.py upgrade -u development
```
and then re-run hopefully it will finish cleanly. If you still have issues please feel free to reopen and we can investigate further.

**Comment by snashraf** [comment]
Traceback (most recent call last):
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/gpfs/home/nsyed/bcbio/anaconda/bin:$PATH && /gpfs/home/nsyed/bcbio/anaconda/bin/gatk -Xms500m -Xmx14g -XX:+UseSerialGC -Djava.io.tmpdir=/gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/bcbiotx/tmp9YdYJQ -T PrintReads -R /gpfs/home/nsyed/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/prealign/0200135761/0200135761-dedup.bam -BQSR /gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/align/0200135761/0200135761-dedup-recal.grp -o /gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/bcbiotx/tmp9YdYJQ/0200135761-dedup-recal.bam -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
INFO  09:15:23,769 ProgressMeter -     2:186654404   4016119.0     6.5 m      97.0 s       14.1%    46.3 m      39.8 m
INFO  09:15:53,770 ProgressMeter -     2:222433498   4316123.0     7.0 m      97.0 s       15.2%    46.0 m      39.0 m
INFO  09:16:23,770 ProgressMeter -      3:10359822   4645488.0     7.5 m      96.0 s       16.2%    46.3 m      38.8 m
INFO  09:16:53,782 ProgressMeter -      3:47470510   4945491.0     8.0 m      97.0 s       17.4%    46.0 m      38.0 m
INFO  09:17:23,783 ProgressMeter -      3:73318810   5345496.0     8.5 m      95.0 s       18.2%    46.6 m      38.1 m
INFO  09:17:53,784 ProgressMeter -     3:128202905   5645499.0     9.0 m      95.0 s       20.0%    45.0 m      36.0 m
INFO  09:18:23,785 ProgressMeter -     3:179501781   5945504.0     9.5 m      95.0 s       21.7%    43.9 m      34.4 m
INFO  09:18:53,786 ProgressMeter -       4:8216420   6270067.0    10.0 m      95.0 s       22.5%    44.4 m      34.4 m
INFO  09:19:23,787 ProgressMeter -      4:68925185   6570071.0    10.5 m      95.0 s       24.5%    42.9 m      32.4 m
INFO  09:19:53,788 ProgressMeter -     4:116841883   6870075.0    11.0 m      96.0 s       26.0%    42.3 m      31.3 m
INFO  09:20:23,804 ProgressMeter -     4:186352170   7170079.0    11.5 m      96.0 s       28.3%    40.7 m      29.2 m
INFO  09:20:53,805 ProgressMeter -      5:52243340   7499139.0    12.0 m      96.0 s       30.1%    39.9 m      27.9 m
INFO  09:21:23,806 ProgressMeter -     5:111496816   7799142.0    12.5 m      96.0 s       32.0%    39.0 m      26.5 m
INFO  09:22:03,807 ProgressMeter -     5:151180449   8299148.0    13.2 m      95.0 s       33.3%    39.5 m      26.4 m
INFO  09:22:33,813 ProgressMeter -      6:13791137   8550616.0    13.7 m      95.0 s       34.7%    39.4 m      25.7 m
INFO  09:23:04,020 ProgressMeter -      6:33608489   8950624.0    14.2 m      95.0 s       35.3%    40.1 m      25.9 m
INFO  09:23:34,021 ProgressMeter -      6:71234398   9250629.0    14.7 m      95.0 s       36.6%    40.1 m      25.5 m
INFO  09:24:04,022 ProgressMeter -     6:131123023   9550632.0    15.2 m      95.0 s       38.5%    39.4 m      24.2 m
INFO  09:24:34,039 ProgressMeter -     6:171054941   9850636.0    15.7 m      95.0 s       39.8%    39.4 m      23.7 m
INFO  09:25:04,263 ProgressMeter -      7:42963105   1.021522E7    16.2 m      95.0 s       41.2%    39.3 m      23.1 m
INFO  09:25:34,264 ProgressMeter -      7:91722481   1.0515226E7    16.7 m      95.0 s       42.7%    39.0 m      22.3 m
INFO  09:26:04,280 ProgressMeter -     7:124404121   1.0815229E7    17.2 m      95.0 s       43.8%    39.2 m      22.0 m
INFO  09:26:34,281 ProgressMeter -     7:151873640   1.1115232E7    17.7 m      95.0 s       44.7%    39.6 m      21.9 m
INFO  09:27:04,282 ProgressMeter -      8:30643938   1.1447568E7    18.2 m      95.0 s       45.9%    39.6 m      21.4 m
INFO  09:27:34,284 ProgressMeter -      8:91522303   1.1747572E7    18.7 m      95.0 s       47.9%    39.0 m      20.3 m
INFO  09:28:04,790 ProgressMeter -     8:144732317   1.2047575E7    19.2 m      95.0 s       49.6%    38.7 m      19.5 m
INFO  09:28:34,790 ProgressMeter -      9:35706358   1.2438184E7    19.7 m      94.0 s       50.8%    38.8 m      19.1 m
INFO  09:29:04,793 ProgressMeter -     9:100070032   1.2738187E7    20.2 m      95.0 s       52.8%    38.2 m      18.0 m
INFO  09:29:34,794 ProgressMeter -     9:131858319   1.303819E7    20.7 m      95.0 s       53.9%    38.4 m      17.7 m
INFO  09:30:04,794 ProgressMeter -     10:12265584   1.334604E7    21.2 m      95.0 s       54.6%    38.8 m      17.6 m
INFO  09:30:35,393 ProgressMeter -     10:62548266   1.3646043E7    21.7 m      95.0 s       56.2%    38.6 m      16.9 m
INFO  09:31:05,394 ProgressMeter -    10:100016703   1.4046049E7    22.2 m      94.0 s       57.4%    38.7 m      16.5 m
INFO  09:31:35,395 ProgressMeter -    10:134819608   1.4346054E7    22.7 m      94.0 s       58.5%    38.8 m      16.1 m
INFO  09:32:15,396 ProgressMeter -     11:27520316   1.4716024E7    23.4 m      95.0 s       59.4%    39.3 m      16.0 m
INFO  09:32:45,548 ProgressMeter -     11:62398220   1.5116029E7    23.9 m      94.0 s       60.6%    39.4 m      15.5 m
INFO  09:33:15,549 ProgressMeter -     11:76892793   1.5416033E7    24.4 m      94.0 s       61.0%    39.9 m      15.6 m
INFO  09:33:45,550 ProgressMeter -    11:118940095   1.5716036E7    24.9 m      94.0 s       62.4%    39.9 m      15.0 m
INFO  09:34:15,551 ProgressMeter -      12:8376068   1.605113E7    25.4 m      94.0 s       63.2%    40.2 m      14.8 m
INFO  09:34:55,552 ProgressMeter -     12:52756025   1.6451134E7    26.0 m      94.0 s       64.6%    40.3 m      14.3 m
INFO  09:35:35,553 ProgressMeter -    12:102020625   1.6851142E7    26.7 m      95.0 s       66.2%    40.3 m      13.6 m
INFO  09:36:05,554 ProgressMeter -    12:132335766   1.7251147E7    27.2 m      94.0 s       67.2%    40.5 m      13.3 m
INFO  09:36:35,560 ProgressMeter -     13:60348496   1.7503505E7    27.7 m      94.0 s       69.2%    40.1 m      12.4 m
INFO  09:37:05,561 ProgressMeter -     14:22772419   1.7818182E7    28.2 m      94.0 s       71.7%    39.4 m      11.2 m
INFO  09:37:35,562 ProgressMeter -     14:64678738   1.8118186E7    28.7 m      95.0 s       73.0%    39.3 m      10.6 m
INFO  09:38:05,659 ProgressMeter -    14:101327376   1.851819E7    29.2 m      94.0 s       74.2%    39.4 m      10.2 m
INFO  09:38:35,660 ProgressMeter -     15:31267148   1.8787093E7    29.7 m      94.0 s       75.4%    39.4 m       9.7 m
INFO  09:39:05,661 ProgressMeter -     15:55475726   1.9087097E7    30.2 m      94.0 s       76.2%    39.6 m       9.4 m
INFO  09:39:35,662 ProgressMeter -     15:83004564   1.9387101E7    30.7 m      95.0 s       77.1%    39.8 m       9.1 m
INFO  09:40:05,689 ProgressMeter -      16:1996621   1.9783289E7    31.2 m      94.0 s       77.8%    40.1 m       8.9 m
INFO  09:40:35,690 ProgressMeter -     16:25590656   2.0083292E7    31.7 m      94.0 s       78.5%    40.4 m       8.7 m
INFO  09:41:05,701 ProgressMeter -     16:59286401   2.0383296E7    32.2 m      94.0 s       79.6%    40.5 m       8.3 m
INFO  09:41:35,702 ProgressMeter -     16:89254728   2.0683305E7    32.7 m      94.0 s       80.6%    40.6 m       7.9 m
INFO  09:42:05,724 ProgressMeter -     17:15508739   2.0980582E7    33.2 m      94.0 s       81.1%    40.9 m       7.7 m
INFO  09:42:35,724 ProgressMeter -     17:37420560   2.1280587E7    33.7 m      95.0 s       81.8%    41.2 m       7.5 m
INFO  09:43:06,015 ProgressMeter -     17:54939644   2.1680591E7    34.2 m      94.0 s       82.4%    41.5 m       7.3 m
INFO  09:43:36,016 ProgressMeter -     17:78179058   2.1980596E7    34.7 m      94.0 s       83.1%    41.7 m       7.0 m
INFO  09:44:06,017 ProgressMeter -     18:33077993   2.2323246E7    35.2 m      94.0 s       84.3%    41.8 m       6.6 m
INFO  09:44:36,027 ProgressMeter -      19:2808454   2.2559257E7    35.7 m      94.0 s       85.8%    41.6 m       5.9 m
INFO  09:45:06,645 ProgressMeter -     19:15198293   2.2959262E7    36.2 m      94.0 s       86.2%    42.0 m       5.8 m
INFO  09:45:36,646 ProgressMeter -     19:38943713   2.3259266E7    36.7 m      94.0 s       87.0%    42.2 m       5.5 m
INFO  09:46:06,654 ProgressMeter -     19:49953081   2.3559272E7    37.2 m      94.0 s       87.3%    42.6 m       5.4 m
INFO  09:46:36,655 ProgressMeter -      20:1161818   2.3917439E7    37.7 m      94.0 s       87.7%    43.0 m       5.3 m
INFO  09:47:06,656 ProgressMeter -     20:37383634   2.4217443E7    38.2 m      94.0 s       88.9%    43.0 m       4.8 m
INFO  09:47:36,669 ProgressMeter -     21:15149675   2.4549796E7    38.7 m      94.0 s       90.2%    42.9 m       4.2 m
INFO  09:48:06,670 ProgressMeter -     22:19137320   2.4849546E7    39.2 m      94.0 s       91.8%    42.7 m       3.5 m
INFO  09:48:36,671 ProgressMeter -     22:39084985   2.5149549E7    39.7 m      94.0 s       92.5%    42.9 m       3.2 m
INFO  09:49:06,672 ProgressMeter -      X:17750510   2.5516372E7    40.2 m      94.0 s       93.5%    43.0 m       2.8 m
INFO  09:49:36,673 ProgressMeter -      X:54836810   2.5816377E7    40.7 m      94.0 s       94.7%    43.0 m       2.3 m
INFO  09:50:06,674 ProgressMeter -     X:108623831   2.611638E7    41.2 m      94.0 s       96.4%    42.8 m      92.0 s
INFO  09:50:36,675 ProgressMeter -     X:153170716   2.6416384E7    41.7 m      94.0 s       97.8%    42.6 m      55.0 s
##### ERROR --
##### ERROR stack trace
org.broadinstitute.gatk.utils.exceptions.ReviewedGATKException: BUG: requested unknown contig=NC_007605 index=-1
	at org.broadinstitute.gatk.utils.MRUCachingSAMSequenceDictionary.updateCache(MRUCachingSAMSequenceDictionary.java:178)
	at org.broadinstitute.gatk.utils.MRUCachingSAMSequenceDictionary.getSequence(MRUCachingSAMSequenceDictionary.java:109)
	at org.broadinstitute.gatk.utils.GenomeLocParser.validateGenomeLoc(GenomeLocParser.java:306)
	at org.broadinstitute.gatk.utils.GenomeLocParser.createGenomeLoc(GenomeLocParser.java:261)
	at org.broadinstitute.gatk.utils.GenomeLocParser.createGenomeLoc(GenomeLocParser.java:471)
	at org.broadinstitute.gatk.engine.datasources.providers.ReadReferenceView.getReferenceContext(ReadReferenceView.java:98)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano$2.next(TraverseReadsNano.java:140)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano$2.next(TraverseReadsNano.java:128)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano.aggregateMapData(TraverseReadsNano.java:119)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano.traverse(TraverseReadsNano.java:101)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano.traverse(TraverseReadsNano.java:56)
	at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:107)
	at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:323)
	at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:123)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:256)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:158)
	at org.broadinstitute.gatk.engine.CommandLineGATK.main(CommandLineGATK.java:108)
##### ERROR ------------------------------------------------------------------------------------------
##### ERROR A GATK RUNTIME ERROR has occurred (version 3.8-0-ge9d806836):
##### ERROR
##### ERROR This might be a bug. Please check the documentation guide to see if this is a known problem.
##### ERROR If not, please post the error message, with stack trace, to the GATK forum.
##### ERROR Visit our website and forum for extensive documentation and answers to
##### ERROR commonly asked questions https://software.broadinstitute.org/gatk
##### ERROR
##### ERROR MESSAGE: BUG: requested unknown contig=NC_007605 index=-1
##### ERROR ------------------------------------------------------------------------------------------
' returned non-zero exit status 1
[2017-10-12T06:50Z] nsnode34: Unexpected error
Traceback (most recent call last):
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 235, in postprocess_alignment
    return ipython.zip_args(apply(sample.postprocess_alignment, *args))
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/pipeline/sample.py", line 246, in postprocess_alignment
    data = recalibrate.apply_recal(data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 47, in apply_recal
    data["work_bam"] = _gatk_apply_bqsr(data)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/variation/recalibrate.py", line 136, in _gatk_apply_bqsr
    parallel_gc=(cores > 1 and gatk_type == "gatk4"))
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 328, in run_gatk
    log_error=log_error)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/gpfs/home/nsyed/.local/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/gpfs/home/nsyed/bcbio/anaconda/bin:$PATH && /gpfs/home/nsyed/bcbio/anaconda/bin/gatk -Xms500m -Xmx14g -XX:+UseSerialGC -Djava.io.tmpdir=/gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/bcbiotx/tmp9YdYJQ -T PrintReads -R /gpfs/home/nsyed/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -I /gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/prealign/0200135761/0200135761-dedup.bam -BQSR /gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/align/0200135761/0200135761-dedup-recal.grp -o /gpfs/projects/bioinfo/najeeb/withDavide/inflammatory_breast_cancer/templateFinalPaired/work/bcbiotx/tmp9YdYJQ/0200135761-dedup-recal.bam -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment
INFO  09:15:23,769 ProgressMeter -     2:186654404   4016119.0     6.5 m      97.0 s       14.1%    46.3 m      39.8 m
INFO  09:15:53,770 ProgressMeter -     2:222433498   4316123.0     7.0 m      97.0 s       15.2%    46.0 m      39.0 m
INFO  09:16:23,770 ProgressMeter -      3:10359822   4645488.0     7.5 m      96.0 s       16.2%    46.3 m      38.8 m
INFO  09:16:53,782 ProgressMeter -      3:47470510   4945491.0     8.0 m      97.0 s       17.4%    46.0 m      38.0 m
INFO  09:17:23,783 ProgressMeter -      3:73318810   5345496.0     8.5 m      95.0 s       18.2%    46.6 m      38.1 m
INFO  09:17:53,784 ProgressMeter -     3:128202905   5645499.0     9.0 m      95.0 s       20.0%    45.0 m      36.0 m
INFO  09:18:23,785 ProgressMeter -     3:179501781   5945504.0     9.5 m      95.0 s       21.7%    43.9 m      34.4 m
INFO  09:18:53,786 ProgressMeter -       4:8216420   6270067.0    10.0 m      95.0 s       22.5%    44.4 m      34.4 m
INFO  09:19:23,787 ProgressMeter -      4:68925185   6570071.0    10.5 m      95.0 s       24.5%    42.9 m      32.4 m
INFO  09:19:53,788 ProgressMeter -     4:116841883   6870075.0    11.0 m      96.0 s       26.0%    42.3 m      31.3 m
INFO  09:20:23,804 ProgressMeter -     4:186352170   7170079.0    11.5 m      96.0 s       28.3%    40.7 m      29.2 m
INFO  09:20:53,805 ProgressMeter -      5:52243340   7499139.0    12.0 m      96.0 s       30.1%    39.9 m      27.9 m
INFO  09:21:23,806 ProgressMeter -     5:111496816   7799142.0    12.5 m      96.0 s       32.0%    39.0 m      26.5 m
INFO  09:22:03,807 ProgressMeter -     5:151180449   8299148.0    13.2 m      95.0 s       33.3%    39.5 m      26.4 m
INFO  09:22:33,813 ProgressMeter -      6:13791137   8550616.0    13.7 m      95.0 s       34.7%    39.4 m      25.7 m
INFO  09:23:04,020 ProgressMeter -      6:33608489   8950624.0    14.2 m      95.0 s       35.3%    40.1 m      25.9 m
INFO  09:23:34,021 ProgressMeter -      6:71234398   9250629.0    14.7 m      95.0 s       36.6%    40.1 m      25.5 m
INFO  09:24:04,022 ProgressMeter -     6:131123023   9550632.0    15.2 m      95.0 s       38.5%    39.4 m      24.2 m
INFO  09:24:34,039 ProgressMeter -     6:171054941   9850636.0    15.7 m      95.0 s       39.8%    39.4 m      23.7 m
INFO  09:25:04,263 ProgressMeter -      7:42963105   1.021522E7    16.2 m      95.0 s       41.2%    39.3 m      23.1 m
INFO  09:25:34,264 ProgressMeter -      7:91722481   1.0515226E7    16.7 m      95.0 s       42.7%    39.0 m      22.3 m
INFO  09:26:04,280 ProgressMeter -     7:124404121   1.0815229E7    17.2 m      95.0 s       43.8%    39.2 m      22.0 m
INFO  09:26:34,281 ProgressMeter -     7:151873640   1.1115232E7    17.7 m      95.0 s       44.7%    39.6 m      21.9 m
INFO  09:27:04,282 ProgressMeter -      8:30643938   1.1447568E7    18.2 m      95.0 s       45.9%    39.6 m      21.4 m
INFO  09:27:34,284 ProgressMeter -      8:91522303   1.1747572E7    18.7 m      95.0 s       47.9%    39.0 m      20.3 m
INFO  09:28:04,790 ProgressMeter -     8:144732317   1.2047575E7    19.2 m      95.0 s       49.6%    38.7 m      19.5 m
INFO  09:28:34,790 ProgressMeter -      9:35706358   1.2438184E7    19.7 m      94.0 s       50.8%    38.8 m      19.1 m
INFO  09:29:04,793 ProgressMeter -     9:100070032   1.2738187E7    20.2 m      95.0 s       52.8%    38.2 m      18.0 m
INFO  09:29:34,794 ProgressMeter -     9:131858319   1.303819E7    20.7 m      95.0 s       53.9%    38.4 m      17.7 m
INFO  09:30:04,794 ProgressMeter -     10:12265584   1.334604E7    21.2 m      95.0 s       54.6%    38.8 m      17.6 m
INFO  09:30:35,393 ProgressMeter -     10:62548266   1.3646043E7    21.7 m      95.0 s       56.2%    38.6 m      16.9 m
INFO  09:31:05,394 ProgressMeter -    10:100016703   1.4046049E7    22.2 m      94.0 s       57.4%    38.7 m      16.5 m
INFO  09:31:35,395 ProgressMeter -    10:134819608   1.4346054E7    22.7 m      94.0 s       58.5%    38.8 m      16.1 m
INFO  09:32:15,396 ProgressMeter -     11:27520316   1.4716024E7    23.4 m      95.0 s       59.4%    39.3 m      16.0 m
INFO  09:32:45,548 ProgressMeter -     11:62398220   1.5116029E7    23.9 m      94.0 s       60.6%    39.4 m      15.5 m
INFO  09:33:15,549 ProgressMeter -     11:76892793   1.5416033E7    24.4 m      94.0 s       61.0%    39.9 m      15.6 m
INFO  09:33:45,550 ProgressMeter -    11:118940095   1.5716036E7    24.9 m      94.0 s       62.4%    39.9 m      15.0 m
INFO  09:34:15,551 ProgressMeter -      12:8376068   1.605113E7    25.4 m      94.0 s       63.2%    40.2 m      14.8 m
INFO  09:34:55,552 ProgressMeter -     12:52756025   1.6451134E7    26.0 m      94.0 s       64.6%    40.3 m      14.3 m
INFO  09:35:35,553 ProgressMeter -    12:102020625   1.6851142E7    26.7 m      95.0 s       66.2%    40.3 m      13.6 m
INFO  09:36:05,554 ProgressMeter -    12:132335766   1.7251147E7    27.2 m      94.0 s       67.2%    40.5 m      13.3 m
INFO  09:36:35,560 ProgressMeter -     13:60348496   1.7503505E7    27.7 m      94.0 s       69.2%    40.1 m      12.4 m
INFO  09:37:05,561 ProgressMeter -     14:22772419   1.7818182E7    28.2 m      94.0 s       71.7%    39.4 m      11.2 m
INFO  09:37:35,562 ProgressMeter -     14:64678738   1.8118186E7    28.7 m      95.0 s       73.0%    39.3 m      10.6 m
INFO  09:38:05,659 ProgressMeter -    14:101327376   1.851819E7    29.2 m      94.0 s       74.2%    39.4 m      10.2 m
INFO  09:38:35,660 ProgressMeter -     15:31267148   1.8787093E7    29.7 m      94.0 s       75.4%    39.4 m       9.7 m
INFO  09:39:05,661 ProgressMeter -     15:55475726   1.9087097E7    30.2 m      94.0 s       76.2%    39.6 m       9.4 m
INFO  09:39:35,662 ProgressMeter -     15:83004564   1.9387101E7    30.7 m      95.0 s       77.1%    39.8 m       9.1 m
INFO  09:40:05,689 ProgressMeter -      16:1996621   1.9783289E7    31.2 m      94.0 s       77.8%    40.1 m       8.9 m
INFO  09:40:35,690 ProgressMeter -     16:25590656   2.0083292E7    31.7 m      94.0 s       78.5%    40.4 m       8.7 m
INFO  09:41:05,701 ProgressMeter -     16:59286401   2.0383296E7    32.2 m      94.0 s       79.6%    40.5 m       8.3 m
INFO  09:41:35,702 ProgressMeter -     16:89254728   2.0683305E7    32.7 m      94.0 s       80.6%    40.6 m       7.9 m
INFO  09:42:05,724 ProgressMeter -     17:15508739   2.0980582E7    33.2 m      94.0 s       81.1%    40.9 m       7.7 m
INFO  09:42:35,724 ProgressMeter -     17:37420560   2.1280587E7    33.7 m      95.0 s       81.8%    41.2 m       7.5 m
INFO  09:43:06,015 ProgressMeter -     17:54939644   2.1680591E7    34.2 m      94.0 s       82.4%    41.5 m       7.3 m
INFO  09:43:36,016 ProgressMeter -     17:78179058   2.1980596E7    34.7 m      94.0 s       83.1%    41.7 m       7.0 m
INFO  09:44:06,017 ProgressMeter -     18:33077993   2.2323246E7    35.2 m      94.0 s       84.3%    41.8 m       6.6 m
INFO  09:44:36,027 ProgressMeter -      19:2808454   2.2559257E7    35.7 m      94.0 s       85.8%    41.6 m       5.9 m
INFO  09:45:06,645 ProgressMeter -     19:15198293   2.2959262E7    36.2 m      94.0 s       86.2%    42.0 m       5.8 m
INFO  09:45:36,646 ProgressMeter -     19:38943713   2.3259266E7    36.7 m      94.0 s       87.0%    42.2 m       5.5 m
INFO  09:46:06,654 ProgressMeter -     19:49953081   2.3559272E7    37.2 m      94.0 s       87.3%    42.6 m       5.4 m
INFO  09:46:36,655 ProgressMeter -      20:1161818   2.3917439E7    37.7 m      94.0 s       87.7%    43.0 m       5.3 m
INFO  09:47:06,656 ProgressMeter -     20:37383634   2.4217443E7    38.2 m      94.0 s       88.9%    43.0 m       4.8 m
INFO  09:47:36,669 ProgressMeter -     21:15149675   2.4549796E7    38.7 m      94.0 s       90.2%    42.9 m       4.2 m
INFO  09:48:06,670 ProgressMeter -     22:19137320   2.4849546E7    39.2 m      94.0 s       91.8%    42.7 m       3.5 m
INFO  09:48:36,671 ProgressMeter -     22:39084985   2.5149549E7    39.7 m      94.0 s       92.5%    42.9 m       3.2 m
INFO  09:49:06,672 ProgressMeter -      X:17750510   2.5516372E7    40.2 m      94.0 s       93.5%    43.0 m       2.8 m
INFO  09:49:36,673 ProgressMeter -      X:54836810   2.5816377E7    40.7 m      94.0 s       94.7%    43.0 m       2.3 m
INFO  09:50:06,674 ProgressMeter -     X:108623831   2.611638E7    41.2 m      94.0 s       96.4%    42.8 m      92.0 s
INFO  09:50:36,675 ProgressMeter -     X:153170716   2.6416384E7    41.7 m      94.0 s       97.8%    42.6 m      55.0 s
##### ERROR --
##### ERROR stack trace
org.broadinstitute.gatk.utils.exceptions.ReviewedGATKException: BUG: requested unknown contig=NC_007605 index=-1
	at org.broadinstitute.gatk.utils.MRUCachingSAMSequenceDictionary.updateCache(MRUCachingSAMSequenceDictionary.java:178)
	at org.broadinstitute.gatk.utils.MRUCachingSAMSequenceDictionary.getSequence(MRUCachingSAMSequenceDictionary.java:109)
	at org.broadinstitute.gatk.utils.GenomeLocParser.validateGenomeLoc(GenomeLocParser.java:306)
	at org.broadinstitute.gatk.utils.GenomeLocParser.createGenomeLoc(GenomeLocParser.java:261)
	at org.broadinstitute.gatk.utils.GenomeLocParser.createGenomeLoc(GenomeLocParser.java:471)
	at org.broadinstitute.gatk.engine.datasources.providers.ReadReferenceView.getReferenceContext(ReadReferenceView.java:98)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano$2.next(TraverseReadsNano.java:140)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano$2.next(TraverseReadsNano.java:128)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano.aggregateMapData(TraverseReadsNano.java:119)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano.traverse(TraverseReadsNano.java:101)
	at org.broadinstitute.gatk.engine.traversals.TraverseReadsNano.traverse(TraverseReadsNano.java:56)
	at org.broadinstitute.gatk.engine.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:107)
	at org.broadinstitute.gatk.engine.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:323)
	at org.broadinstitute.gatk.engine.CommandLineExecutable.execute(CommandLineExecutable.java:123)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:256)
	at org.broadinstitute.gatk.utils.commandline.CommandLineProgram.start(CommandLineProgram.java:158)
	at org.broadinstitute.gatk.engine.CommandLineGATK.main(CommandLineGATK.java:108)

Hi Brad
 
I am getting same contigs errors for GATK as well.  Can you please look into this as well ?

Thanks
Najeeb

**Comment by chapmanb** [comment]
Sorry about the continued problems. GATK is very particular about reference contigs and doesn't handle the case where you're BAM contigs do not match the reference genome. You have a couple of options to push your analysis through (beyond realigning in bcbio):

1. Try using GATK4 to see if it handles this better (`tools_on: [gatk4]`)
2. Use `recalibrate: false` and `realign: false` to skip the failing steps. realignment is not necessary with most downstream callers and realignment only helps with poor data quality.
3. Use `bam_clean: remove_extracontigs` to only keep the standard chromosomes and drop these extras, which should avoid the problem:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

Hope one of these options works for you.
