### ISSUE TITLE
Pipeline stalled with bamsormadup

### ISSUE THREAD

**Issue by gabeng** [chapmanb/bcbio-nextgen#2098]
I seem to keep running into an issue with bamsormadup in bcbio 1.0.5 stable: at some point during alignment 100% of CPU are consumed by bamsormadup processes. This could be related to an issue fixed in the newest release of biobambam2: https://github.com/gt1/biobambam2/releases/tag/2.0.79-release-20171006114010

Am I the only one running into this issue? I am running bcbio on a single machine. bcbio 1.0.3 worked fine for me. The issue persists with the bcbio development branch.

**Comment by gabeng** [comment]
To be more specific: this issue is only with GRCh37 in bcbio 1.0.5. The same job runs through with hg19. I just ran the Exome example: https://bcbio-nextgen.readthedocs.io/en/latest/contents/testing.html#exome-with-validation-against-reference-materials
So it's not something specific to my data.

**Comment by lbeltrame** [comment]
I see this with the latest master and `bamsormadup` myself.

**Comment by lbeltrame** [comment]
I built biobambam 2.0.79 myself and the issue went away. I guess it needs an update in the pipeline.

**Comment by chapmanb** [comment]
Ben and Luca -- thanks so much for the report and sorry about the issue. I could reproduce this as well. It looks like the biobambam recipe got bumped to 2.0.78 a few days ago and that version has this issue. I just updated to 2.0.79 so if you do: `bcbio_conda install -c conda-forge -c bioconda biobambam` you should get the latest which will hopefully avoid the problem. Sorry again about the problem and hope this fixes it for you.

**Comment by phu5ion** [comment]
Hi Brad,

Just to be sure, this update fixes both the bamsormadup as well as the bwa mem freeze?

**Comment by gabeng** [comment]
Brad, just a quick question: so, it depended on the time and date that I installed bcbio 1.0.5 which versions of 3rd party tools were installed? Is there any way to freeze this? Does this apply to all 3rd party software components?

**Comment by chapmanb** [comment]
Ben -- we don't globally pin third party tool versions on each release. We do sometimes pin specific tools that are tied to code in a release and update those pins to match each release:

https://github.com/chapmanb/cloudbiolinux/blob/f944e9c9e3c35b8cf1e152fc7bb075c429773a52/contrib/flavor/ngs_pipeline_minimal/packages-conda.yaml#L48

but don't do it globally as it can be a lot of work to maintain. The improved solution we're working on is to have automated builds of tools and code in containers;

https://github.com/bcbio/bcbio_docker

This supports Docker now and we're hoping to test and use Singularity as well for an HPC friendly approach. This will give us a lot more reproducibility and recovery of exact versions.

Thanks much for the discussion on this.

**Comment by gabeng** [comment]
@chapmanb, I updated biobambam2 in a `bcbio 1.0.5 GRCh37` stable according to your instructions with
```javascript
bcbio_conda install -c conda-forge -c bioconda biobambam
```
The process now finishes without error. However, I am missing average coverage statistics in MultiQC. I understand that you switched tools there, but I can only compare to my previous bcbio 1.0.3 setup. What I can tell so far is that the data files in `<sampleID>/qc/coverage/ ` are missing. I think this was previously created with `sambamba depth region`. I would prefer to keep close to your release, if that is possible. Any hint what I can do to get coverage statistics back?

**Comment by chapmanb** [comment]
Ben;
We replaced sambamba with mosdepth for coverage estimation, to improve speeds and avoid intermittent segfaults folks were seeing with sambamba. It should still provide coverage estimates in `sample/qc/coverage/sample_bcbio_coverage_avg.txt` with the coverage in each sample at different depths. It doesn't have some of the previous interval coverage statistics but we're looking at if we can add that back in (brentp/mosdepth#17). Are there particular statistics you found useful that we're missing? Thanks much for the discussion.

**Comment by gabeng** [comment]
Brad,
I was looking forward to that switch to mosdepth because it speeds up things for me. I would very much like to see the Avg Coverage again, though. `multiqc_bcbio_metrics.txt`only contains zeros in this column.
I am currently checking with the current development version if this was just a glitch with the patch mentioned above.
```
Sample	Mapped_unique_reads	Ontarget_pct	Mapped_reads_pct	Avg_coverage	Duplicates	Mapped_paired_reads	Duplicates_pct	Average_read_length	Sequences_flagged_as_poor_quality	Ontarget_padded_pct	Usable_pct	Mapped_reads	%GC	Total_reads	Offtarget_pct	Average_insert_size	Ontarget_unique_reads
1_S5	4240516.0	65.0066171192	99.8837047496	0.0	840490.0	5077364.0	16.5385837648	145.0	0.0	87.6290998548	54.1797106554	5081995.0	48.0	5087912.0	34.9933828808	249.2	2756616.0
2_S11	4105226.0	63.5321904324	99.8914271408	0.0	801330.0	4903304.0	16.3286939001	144.0	0.0	84.0290887761	53.0883421572	4907496.0	47.0	4912830.0	36.4678095676	243.4	2608140.0
```

**Comment by gabeng** [comment]
It seem this particular issue is not present in the development version. I will go for that now. Thanks for your help.

**Comment by chapmanb** [comment]
Ben -- thanks for the details and heads up that there was a problem in 1.0.5. We'll work on testing the current development and getting a new release out with all the mosdepth integration. Thanks again for all this testing and feedback.
