### ISSUE TITLE
dbsnp-150.vcf.gz truncated 

### ISSUE THREAD

**Issue by snashraf** [chapmanb/bcbio-nextgen#2099]
Hi Brad,

For some reason, /gpfs/home/nsyed/bcbio/genomes/Hsapiens/GRCh37/variation/dbsnp-150.vcf.gz was truncated and hence it was creating problme. I wanted to download it again but update data is not updating this file. 
Any alternate to download this particular file ?

Thanks
Najeeb

**Comment by chapmanb** [comment]
Najeeb;
Thanks for the report and apologies about the issues. If you had an incorrect download and bcbio didn't realize, it will have finalized the install and not re-do it unless you manually edit the versions file:
```
/gpfs/home/nsyed/bcbio/genomes/Hsapiens/GRCh37/version.csv
```
remove `dbsnp,150`, and then re-run `bcbio_nextgen.py upgrade --data`. That should re-download the file. If you still have issues please feel free to reopen.
