### ISSUE TITLE
Bwa-mem freezes

### ISSUE THREAD

**Issue by phu5ion** [chapmanb/bcbio-nextgen#2100]
Hi,

Recently while running bcbio on exome samples the run freezes during bwa-mem alignment. Although I'm using hg38 which takes up more RAM, I don't think it is a memory issue as the fastqs are not that big (about 2-3GB for each of R1/R2) and I should be specifying enough memory.
From log file:
[2017-10-12T01:06Z] Resource requests: bwa, sambamba, samtools; memory: 128.00, 128.00, 128.00; cores: 1, 1, 1
[2017-10-12T01:06Z] Configuring 7 jobs to run, using 1 cores each with 128.00g of memory reserved for each job
From cluster job status:
granted_req.          1:    mem_free=256.000G
usage                 1:    wallclock=4:19:31:15, cpu=15:24:17, mem=71076.48215 GBs, io=81.49602 GB, iow=46.500 s, ioops=6529468, vmem=59.308G, maxvmem=59.308G, rss=43.310G, pss=42.652G, smem=769.391M, pmem=42.559G, maxrss=43.310G, maxpss=42.652G

Sorry for posting here as it could be something about my cluster (perhaps something about the I/O), but I'm just wondering whether any of you experts have seen this issue before or have any idea what's going on here? Perhaps bcbio restricts the amount of memory allocated to bwa-mem, somehow?

Edit: I'm not running out of file space either.

**Comment by gabeng** [comment]
What are you observing exactly? That bcbio freezes and no progess is shown in the log file? Which processes are still running? I ran into an issue with bamsormadup which runs in a pipe after bwa (separate issue).

**Comment by phu5ion** [comment]
Hi @gabeng 

Yes, bcbio freezes and there's no progress in the log file. Usually bwa mem outputs log messages like
```
[2017-10-12T01:17Z] [M::mem_pestat] mean and std.dev: (209.33, 79.31)
[2017-10-12T01:17Z] [M::mem_pestat] low and high boundaries for proper pairs: (1, 583)
[2017-10-12T01:17Z] [M::mem_pestat] skip orientation RF as there are not enough pairs
[2017-10-12T01:17Z] [M::mem_pestat] skip orientation RR as there are not enough pairs
```
but there's been no progress for ages.

I can't tell which processes are still running since I'm running bcbio on a distributed cluster, as a job submission.

As an aside, I ran into an issue with bamsormadup piping after bamcat too. It just freezes...

**Comment by chapmanb** [comment]
Sorry about the problem, I believe this is due to a biobambam bug discussed in #2098. We just pushed a new version of biobambam which should avoid this if you do: `bcbio_conda install -c conda-forge -c bioconda biobambam`. Please let us know if you still have issues after the update.

**Comment by phu5ion** [comment]
Hi Brad,

Just to be sure, this update fixes both the bwa mem and bamsormadup freeze?

**Comment by chapmanb** [comment]
Yes, I believe it's the same issue. bwa pipes into bamsormadup so the hang causes bwa to wait which bamsormadup is indefinitely processing data. Please let us know if you still have problems.
