### ISSUE TITLE
Cancer variant calling

### ISSUE THREAD

**Issue by aadamk** [chapmanb/bcbio-nextgen#2102]
When running tumor-normal variant calling with the below configuration, I only find somatic variants in my output vcf and no associated germline variant file (e.g. no sample-caller-germline.vcf).  However, the output vcf (sample-caller.vcf) retains both tumor and normal sample names and as such is seen as a multi-sample vcf by all subsequent tools that I want to use.  Do you know why 1) no germline variant file was generated, and 2) how I can remove the germline name from the somatic vcf, as I am unable to filter it thus far with vcf tools using a FILTER or INFO tag (because no germline variants are present in the file)?  

Sample yaml:
details:
- algorithm:
    aligner: false
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: false
    recalibrate: false
    realign: false
    remove_lcr: false
    platform: illumina
    quality_format: standard
    variantcaller: [vardict, mutect2]
    indelcaller: mutect2
    bam_clean: fixrg
    ensemble:
      numpass: 2
  analysis: variant2
  description: 98-PBL_control
  files: /project/SN0119031/98-PBL_control.bam
  genome_build: GRCh37
  metadata:
    batch: mel_case18
    phenotype: normal
- algorithm:
    aligner: false
    align_split_size: 5000000
    nomap_split_targets: 100
    mark_duplicates: false
    recalibrate: false
    realign: false
    remove_lcr: false
    platform: illumina
    bam_clean: fixrg
    quality_format: standard
    variantcaller: [vardict, mutect2]
    indelcaller: mutect2
    ensemble:
      numpass: 2
    effects: vep
    tools_off: [gemini]
  analysis: variant2
  description: D14-257_B10
  files: /project/SN0119031/D14-257_B10.bam
  genome_build: GRCh37
  metadata:
    batch: mel_case18
    phenotype: tumor
fc_date: '7.5.2017'
fc_name: mel_case18
upload:
  dir: ../final

**Comment by chapmanb** [comment]
Thanks for the questions. For germline calling you need to specify a set of germline callers in addition to the somatic callers. This behavior changed in 1.0.1 if you were previously using an older version; the new approach does separate calling and does a much better job than the previous attempt to extract these form the combined calls:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#somatic-with-germline-variants

If you want to analyze only the somatic calls downstream and don't want the normal sample included, you can subset it out with `bcftools view -s your_tumor_name`. Generally tools should work on multisample inputs and leaving in the normal sample is useful for later evaluation of low frequency variants to determine if there is any (weaker) evidence in the normal.

Hope this helps.

**Comment by aadamk** [comment]
I see-will adjust.  I had my sample yamls set up according to 'cancer variant calling' as the docs state it will yield a germline file.  
http://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#cancer-variant-calling
"The standard variant outputs (sample-caller.vcf.gz) for tumor calling emphasize somatic differences, those likely variants unique to the cancer. In addition to this file, we also produce a sample-caller-germline.vcf.gz file containing likely germline mutations."

**Comment by aadamk** [comment]
Also, I should clarify - all variants in my ensemble output file (from joint mutect2 and vardict calls) are annotated 'STRONGLY SOMATIC' (no germline variants).  Is this true of all vcfs generated using the above yaml that I posted - only somatic variants are included in the output (despite the germline sample name being retained in the vcf header)?

**Comment by chapmanb** [comment]
Thanks so much for the details on the confusing documentation. I've updated that section to point at the germline documentation, please let us know if anything else at all is unclear or out of date.

You're exactly right that the ensemble outputs only contain somatic variants. The individual caller files will have all called variants with soft filters in the FILTER column so only PASS variants are somatic. Those PASS variants get used to build the ensemble calls. Having the normal sample also present isn't indicative that there is a call there and you should look at the genotype GT field for each sample to determine the call. A majority of the normal samples should be reference (0/0) and the somatics will be heterozygotes (0/1) or homozygotes (1/1). Hope this helps.

**Comment by aadamk** [comment]
Got it. Thanks so much!
