### ISSUE TITLE
Question: GATK4 and bcbio

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2115]
Hi Brad,

I saw Broad announced a release date for the first release version of GATK4 (Jan 9th, 2018). What are your plans regarding migrating to GATK4 as default over GATK3.8? I know you already did some validation work and saw promising results. Do you think GATK4 will be ready for prime time production use?

I'm asking because we'd like to plan ahead for our production deployment. The release of GATK4 more or less lines up with the release for Ensembl 91 and perhaps even a new dbNSFP release. If possible, it would be nice to have all those changes bundled in a new release.

Cheers!
M

**Comment by chapmanb** [comment]
Matthias;
Thanks for checking in on this. From the bcbio side we're happy with the GATK4 integration and all our validations have looked good (https://github.com/bcbio/bcbio_validations/tree/master/gatk4). Right now it's easily turned on by doing `tools_on: [gatk4]` so usage is mostly determined by your appetite for using software that GATK labels as beta. At release time we'll make GATK4 the default and provide a `tools_off: [gatk4]` target for folks who prefer to use the older versions. Hope that works for your planning and thanks again for the discussion.

**Comment by matthdsm** [comment]
Allright! Great to hear everything’s set and looking good.  

Cheers
M
