### ISSUE TITLE
Avoid bcftools when generating gvcf's

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2120]
Hi Brad,

I was wondering if it's possible to tweak the code to avoid using bcftools when generating gvcf files.
This causes some compatibility issues with GATK downstream ( cfr. https://gatkforums.broadinstitute.org/gatk/discussion/10515/combinegvcf-java-lang-classcastexception-java-lang-integer-cannot-be-cast-to-java-lang-double#latest). I don't know when or what was changed, but in the past this worked, but we seem unable to merge the gvcf of our latests runs due to the error above.

Cheers
M

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issue. We had carefully avoided using bcftools for merging to prevent this but introduced a reheader step to fix some issues which apparently also triggers it. I pushed a fix to use picard for reheadering instead of bcftools to avoid causing the issue. Sorry again about this problem and hope this fixes it going forward.

**Comment by matthdsm** [comment]
HI Brad, 

Thanks for the fix! In the meantime, do you know a little magic trick to make the gvcf's we already have GATK compatible? It'd be a shame to have to redo several runs to fix the gvcfs :-/ .

Thanks a lot
M

**Comment by chapmanb** [comment]
Matthias;
We'd probably have to write a small script to convert these over. Do you have a small test case that has the problem? I don't have any files with this problem to test on but it seems like you'd need to be sure that all the problem values are Floats, not integers, so add a `.0` to the problem values. Alternatively do you still have the work directories and could re-do the gVCF merge step while re-using the calls?

**Comment by matthdsm** [comment]
Hi Brad,
which directories would I have to 'remove' to trigger the gVCF merge? I think that'll be the the option with the least hassle to it.

Thanks!
M

**Comment by chapmanb** [comment]
Matthias;
Great, you'd want to remove the merged gVCFs, joint called VCFs and checkpoint files:
```
rm gatk-haplotype/samplename*
rm joint/gatk-haplotype-joint/batchname/batchname*
rm checkpoints_parallel/full.done
rm checkpoints_parallel/multicore2.done
```
then re-run with the updated code. Hope this creates clean gVCFs and VCFs for downstream processing. Please let us know if you run into any problems.

**Comment by matthdsm** [comment]
Hi Brad,

Will do! Thanks for the fix!
M

**Comment by matthdsm** [comment]
Hi Brad, 

I'm sad to report the fix above didn't work :( The partial vcf's are still concatenated using bcftools, so the issue with the changed values remain. Do you think it's viable to use GATK CatVariants or similar instead of bcftools? This will ensure everything stays within the GATK params and the merging will work.

In the future, this issue will be void, since [GATK4 should be able to handle this.](https://gatkforums.broadinstitute.org/gatk/discussion/comment/43443/#Comment_43443)

Thanks
M

**Comment by chapmanb** [comment]
Matthias;
I'm sorry about making you re-run this and still having a bug. I missed this when testing and for GATK3 it should be using bcftools naive concatenation here which will not reformat the file, and is much faster. I pushed a fix which should do this so if you re-run one more time hopefully it will finally be working correctly for you. Sorry again about the issues and thanks for your patience.

**Comment by matthdsm** [comment]
Hi Brad,

No problem, thanks for the fix! I'll give it a go and get back to you.

Cheers
M

**Comment by matthdsm** [comment]
Hi Brad,

Just a little followup. Apparently, the people at samtools have had the same issues, and wrote a script to fix this:
https://github.com/samtools/bcftools/blob/develop/misc/fix-broken-GATK-Double-vs-Integer

Cheers,
M

**Comment by chapmanb** [comment]
Thanks much for the pointer -- it's great to have a fix if we run into any problems with this going forward.
