### ISSUE TITLE
 _get_target_antitarget_bin_sizes is slow and doesn't save results once complete

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2130]
It runs single core, and with 48 exome samples on my machines can take up to 1 hour to run. While this may be a local problem, it shows a second problem: the calculations are repeated *every time* the pipeline runs unless the next step is reached.

As I got bit by a couple of cnvkit issues (one fixed by c662fe10806416d99d245376555789f65c838260), the second patched out manually (https://github.com/etal/cnvkit/pull/262) the pipeline aborted before it could go further. That meant that this long-running calculation was done every time.

**Comment by lbeltrame** [comment]
Looking at the code, the results are never saved anywhere. Would it be worth to cache them at least? I don't think the bin calculation would need to be run on every pipeline rerun (unless inputs change).

**Comment by lbeltrame** [comment]
And if the target and antitarget beds have been written (so `file_exists` returns `True` in `targets_w_bins`, this result is simply discarded. I would suggest to move the check for the target and antitarget bed existence, prior to `_get_target_antitarget_bin_sizes` so that it's not run if not necessary.

**Comment by chapmanb** [comment]
Luca -- thanks much for the detailed report and catching this. This was definitely doing extra unnecessary work and I checked in a fix to delay and cache the calculations which should avoid the re-run issues. Please let me know if you hit any other problems at all and thanks again.
