### ISSUE TITLE
Optitype "Failed to open file" error

### ISSUE THREAD

**Issue by choosehappy** [chapmanb/bcbio-nextgen#2136]
For what i think are 2 "standard" whole exome seq samples, running in paried normal-tumor mode.

I tried both the stable and development releases

Bcbio seems to try to be reading a file which doesn't exist. 

Any ideas?

In fact, that whole tmp subdirectory doesn't exist at all:

> root@725ec8206460:/data/CNV.valid/P2/work# ls -l /data/CNV.valid/P2/work/align/T2/hla/bcbiotx/
> total 0
> root@725ec8206460:/data/CNV.valid/P2/work#
> 

This is the error:

> [2017-11-03T03:36Z] Timing: hla typing
> [2017-11-03T03:36Z] multiprocessing: call_hla
> [2017-11-03T03:36Z] HLA typing with OptiType
> [2017-11-03T03:37Z] Illegal instruction
> [2017-11-03T03:37Z] [E::hts_open_format] Failed to open file /data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh/2017_11_03_03_37_03/2017_11_03_03_37_03_1.bam
> [2017-11-03T03:37Z] mapping with 16 threads...
> [2017-11-03T03:37Z]  0:00:04.05 Mapping OptiType-HLA-A_B_C-input.fq to GEN reference...
> [2017-11-03T03:37Z]  0:00:04.70 Generating binary hit matrix.
> [2017-11-03T03:37Z] Traceback (most recent call last):
> [2017-11-03T03:37Z]   File "/usr/local/bin/OptiTypePipeline.py", line 351, in <module>
> [2017-11-03T03:37Z]     pos, read_details = ht.pysam_to_hdf(bam_paths[0])
> [2017-11-03T03:37Z]   File "/usr/local/share/bcbio-nextgen/anaconda/share/optitype-1.2.1-0/hlatyper.py", line 186, in pysam_to_hdf
> [2017-11-03T03:37Z]     sam = pysam.AlignmentFile(samfile, sam_or_bam)
> [2017-11-03T03:37Z]   File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
> [2017-11-03T03:37Z]   File "pysam/libcalignmentfile.pyx", line 621, in pysam.libcalignmentfile.AlignmentFile._open
> [2017-11-03T03:37Z] IOError: [Errno 2] could not open alignment file `/data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh/2017_11_03_03_37_03/2017_11_03_03_37_03_1.bam`: No such file or directory
> [2017-11-03T03:37Z] Uncaught exception occurred
> Traceback (most recent call last):
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> CalledProcessError: Command 'set -o pipefail; OptiTypePipeline.py -v --dna  -o /data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh -i /data/CNV.valid/P2/work/align/T2/hla/OptiType-HLA-A_B_C-input.fq -c /data/CNV.valid/P2/work/align/T2
> /hla/bcbiotx/tmpkuhkUh/config.ini
> Illegal instruction
> [E::hts_open_format] Failed to open file /data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh/2017_11_03_03_37_03/2017_11_03_03_37_03_1.bam
> mapping with 16 threads...
>  0:00:04.05 Mapping OptiType-HLA-A_B_C-input.fq to GEN reference...
>  0:00:04.70 Generating binary hit matrix.
> Traceback (most recent call last):
>   File "/usr/local/bin/OptiTypePipeline.py", line 351, in <module>
>     pos, read_details = ht.pysam_to_hdf(bam_paths[0])
>   File "/usr/local/share/bcbio-nextgen/anaconda/share/optitype-1.2.1-0/hlatyper.py", line 186, in pysam_to_hdf
>     sam = pysam.AlignmentFile(samfile, sam_or_bam)
>   File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 621, in pysam.libcalignmentfile.AlignmentFile._open
> IOError: [Errno 2] could not open alignment file `/data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh/2017_11_03_03_37_03/2017_11_03_03_37_03_1.bam`: No such file or directory
> ' returned non-zero exit status 1
> Traceback (most recent call last):
>   File "/usr/local/bin/bcbio_nextgen.py", line 234, in <module>
>     main(**kwargs)
>   File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
>     run_main(**kwargs)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
>     fc_dir, run_info_yaml)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
>     for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 133, in variant2pipeline
>     samples = hla.run(samples, run_parallel)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/hla/__init__.py", line 31, in run
>     processed = run_parallel("call_hla", ([x] for x in to_process))
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
>     return run_multicore(fn, items, config, parallel=parallel)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
>     for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
>     while self.dispatch_one_batch(iterator):
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
>     job = ImmediateComputeBatch(batch)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
>     self.results = batch()
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
>     return apply(f, *args, **kwargs)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 274, in call_hla
>     return hla.call_hla(*args)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/hla/__init__.py", line 15, in call_hla
>     data = _CALLERS[hlacaller](data)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/hla/optitype.py", line 39, in run
>     out_file = _call_hla(hla_fq, out_dir, data)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/hla/optitype.py", line 118, in _call_hla
>     do.run(cmd.format(**locals()), "HLA typing with OptiType")
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> subprocess.CalledProcessError: Command 'set -o pipefail; OptiTypePipeline.py -v --dna  -o /data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh -i /data/CNV.valid/P2/work/align/T2/hla/OptiType-HLA-A_B_C-input.fq -c /data/CNV.valid/P2/wo
> rk/align/T2/hla/bcbiotx/tmpkuhkUh/config.ini
> Illegal instruction
> [E::hts_open_format] Failed to open file /data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh/2017_11_03_03_37_03/2017_11_03_03_37_03_1.bam
> mapping with 16 threads...
>  0:00:04.05 Mapping OptiType-HLA-A_B_C-input.fq to GEN reference...
>  0:00:04.70 Generating binary hit matrix.
> Traceback (most recent call last):
>   File "/usr/local/bin/OptiTypePipeline.py", line 351, in <module>
>     pos, read_details = ht.pysam_to_hdf(bam_paths[0])
>   File "/usr/local/share/bcbio-nextgen/anaconda/share/optitype-1.2.1-0/hlatyper.py", line 186, in pysam_to_hdf
>     sam = pysam.AlignmentFile(samfile, sam_or_bam)
>   File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 621, in pysam.libcalignmentfile.AlignmentFile._open
> IOError: [Errno 2] could not open alignment file `/data/CNV.valid/P2/work/align/T2/hla/bcbiotx/tmpkuhkUh/2017_11_03_03_37_03/2017_11_03_03_37_03_1.bam`: No such file or directory
> ' returned non-zero exit status 1
> 
> 
>

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the detailed report. You're getting an error from inside optitype that the alignment file it is meant to generate is missing. The directory it specifies won't be present after the runs fails (it's a transactional directory so gets removed) so having it not present is expected. The best way to debug here is to do two things:

- Look at the input file and fastq directory at `/data/CNV.valid/P2/work/align/T2/hla/`. Do you have HLA reads and reasonable inputs here? The latest development version tries to skip HLA typing if we don't have useful inputs, but may not be detecting this has too few reads or something else that makes OptiType fail.
- Run the failing optitype command outside of bcbio writing to a stable directory to see if you can reproduce:
```
OptiTypePipeline.py -v --dna -o test_outdir -i /data/CNV.valid/P2/work/align/T2/hla/OptiType-HLA-A_B_C-input.fq -c config.ini
```
where the `config.ini` file is:
```
[mapping]
razers3=/usr/local/share/bcbio-nextgen/anaconda/bin/razers3
threads=1
[ilp]
solver=cbc
threads=1
[behavior]
deletebam=true
unpaired_weight=0
use_discordant=false
```
Then you could look at the outputs and try to figure out why things are not working cleanly.

Hope this helps for debugging.

**Comment by choosehappy** [comment]
Thanks for the quick response!

There what appears to be reasonable output to me in the directory:

> root@9dc594a1645c:/data/CNV.valid/P2/work/align/T2/hla# ls -l
> total 9492
> -rw-r--r-- 1 nobody nogroup 3371235 Nov  3 03:36 OptiType-HLA-A_B_C-input.fq
> -rw-r--r-- 1 nobody nogroup  991829 Nov  2 16:51 T2-HLA-A.fq
> -rw-r--r-- 1 nobody nogroup 1409379 Nov  2 16:51 T2-HLA-B.fq
> -rw-r--r-- 1 nobody nogroup  970027 Nov  2 16:51 T2-HLA-C.fq
> -rw-r--r-- 1 nobody nogroup  784868 Nov  2 16:51 T2-HLA-DQA1.fq
> -rw-r--r-- 1 nobody nogroup  697377 Nov  2 16:51 T2-HLA-DQB1.fq
> -rw-r--r-- 1 nobody nogroup 1473768 Nov  2 16:51 T2-HLA-DRB1.fq
> drwxr-xr-x 2 nobody nogroup    4096 Nov  3 03:37 bcbiotx
> root@9dc594a1645c:/data/CNV.valid/P2/work/align/T2/hla#

and running in a separate directory gives the same error:

> mkdir: cannot create directory '/tmp': File exists
> root@9dc594a1645c:/data/CNV.valid/P2/work/align/T2/hla# mkdir /tmp/opti
> root@9dc594a1645c:/data/CNV.valid/P2/work/align/T2/hla# cd /tmp/opti
> root@9dc594a1645c:/tmp/opti# nano config.ini
> root@9dc594a1645c:/tmp/opti# OptiTypePipeline.py -v --dna -o test_outdir -i /data/CNV.valid/P2/work/align/T2/hla/OptiType-HLA-A_B_C-input.fq -c config.ini
> 
> mapping with 1 threads...
> 
>  0:00:04.24 Mapping OptiType-HLA-A_B_C-input.fq to GEN reference...
> Illegal instruction (core dumped)
> 
>  0:00:05.61 Generating binary hit matrix.
> [E::hts_open_format] Failed to open file test_outdir/2017_11_03_15_29_02/2017_11_03_15_29_02_1.bam
> Traceback (most recent call last):
>   File "/usr/local/bin/OptiTypePipeline.py", line 351, in <module>
>     pos, read_details = ht.pysam_to_hdf(bam_paths[0])
>   File "/usr/local/share/bcbio-nextgen/anaconda/share/optitype-1.2.1-0/hlatyper.py", line 186, in pysam_to_hdf
>     sam = pysam.AlignmentFile(samfile, sam_or_bam)
>   File "pysam/libcalignmentfile.pyx", line 444, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 621, in pysam.libcalignmentfile.AlignmentFile._open
> IOError: [Errno 2] could not open alignment file `test_outdir/2017_11_03_15_29_02/2017_11_03_15_29_02_1.bam`: No such file or directory
> root@9dc594a1645c:/tmp/opti#
> 

there are no files in that directory:

> root@9dc594a1645c:/tmp/opti# find .
> .
> ./config.ini
> ./test_outdir
> ./test_outdir/2017_11_03_15_29_02
> root@9dc594a1645c:/tmp/opti#
>

**Comment by choosehappy** [comment]
Actually, although the error is the same, above it i see a new hint 

"Illegal instruction (core dumped)"

which likely explains why that file isn't being generated

**Comment by choosehappy** [comment]
In general the command its trying to execute is this:

/usr/local/share/bcbio-nextgen/anaconda/bin/razers3 -i 97 -m 99999 --distance-range 0 -pa -tc %d -o %s %s %s

which when running at the command line on its own, causes the core dump:

root@9dc594a1645c:/tmp/opti# /usr/local/share/bcbio-nextgen/anaconda/bin/razers3
Illegal instruction (core dumped)


Not sure where to go from there? Reinstall razers3?

**Comment by chapmanb** [comment]
Thanks for the detailed debugging and drilling in on the problem, this is really helpful. Could you try doing:
```
bcbio_conda install -c conda-forge -c bioconda razers3=3.5.0
```
There was a new version of razers3 built on bioconda 5 days ago and I wonder if that's causing issues here. If the 3.5.0 version works cleanly we could pin to that to avoid the problem generally. Thanks again for all the help digging into this.

**Comment by choosehappy** [comment]
congratulations, that was it:

> root@9dc594a1645c:/tmp/opti# OptiTypePipeline.py -v --dna -o test_outdir -i /data/CNV.valid/P2/work/align/T2/hla/OptiType-HLA-A_B_C-input.fq -c config.ini
> 
> mapping with 1 threads...
> 
>  0:00:00.80 Mapping OptiType-HLA-A_B_C-input.fq to GEN reference...
> 
>  0:00:44.47 Generating binary hit matrix.
> 0:00:44.48 Loading test_outdir/2017_11_03_16_02_53/2017_11_03_16_02_53_1.bam started. Number of HLA reads loaded (updated every thousand):
> 1K...2K...3K...4K...
>  0:00:53.73 4016 reads loaded. Creating dataframe...
> 

and then runs to completion!

**Comment by chapmanb** [comment]
Brilliant -- thanks for confirming and all the help figuring out the issue. I pinned the version in the install so any upgrades should also work going forward. Thanks again for report and help fixing this.

**Comment by choosehappy** [comment]
No No, thank you for your hard work. 

Such a great tool, I'm glad to help out where i can :)
