### ISSUE TITLE
bamtools conda update seems to break ngs_disambiguate

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#2137]
Don't know if this is the right place to report it, @chapmanb and @mjafin, but `bamtools` got a conda update to `2.4.1` [a week ago](https://anaconda.org/bioconda/bamtools/files) and that breaks [conda's `ngs_disambiguate`](https://github.com/bioconda/bioconda-recipes/tree/master/recipes/ngs-disambiguate) for me:

> bcbio/lib/anaconda/bin/ngs_disambiguate: error while loading shared libraries: libbamtools.so.2.4.0: cannot open shared object file: No such file or directory

I tried conda-removing `ngs-disambiguate` and `bamtools=2.4.1` and reinstalling both, but to no avail. However, downgrading to conda `bamtools=2.4.0` fixes the issue for me. Is that perhaps something general or does it only pertain to my installation?

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for the heads up on this. I pinned bamtools to 2.4.0 in the install to avoid pulling in the new version. We'd have to re-compile and re-build the conda package against 2.4.1 but not sure if we have other packages compiled against 2.4.0 so this is the most straightforward fix. Thanks again for letting us know.
