### ISSUE TITLE
IPython subtasks run always only with 1 core

### ISSUE THREAD

**Issue by leiendeckerlu** [chapmanb/bcbio-nextgen#2139]
Hi there, this is the script I use to submit bcbio to our cluster with slurm as job scheduler:

> #!/usr/bin/env bash 
> 
> #SBATCH --job-name=bcbio
> #SBATCH --qos=medium
> #SBATCH--output=multithread-%j.out
> 
> export PATH=/bcbio_ii2/local/bin:$PATH
> 
> bcbio_nextgen.py /scratch/slurm/cancer-dream-syn3/config/cancer-dream-syn3.yaml -n 28 -t ipython -s slurm -q work -r qos=medium

And everything runs smoothly except for the fact that all subtasks like bwa etc. are only called with one available core:

> [2017-11-03T19:48Z] cn-12: System YAML configuration: /bcbio_ii2/local/share/bcbio/galaxy/bcbio_system.yaml
> [2017-11-03T19:48Z] cn-12: Resource requests: bwa, sambamba, samtools; memory: 32.00, 32.00; cores: 16, 16, 16
> [2017-11-03T19:48Z] cn-12: Configuring 1 jobs to run, using 1 cores each with 32.00g of memory reserved for each job
> 2017-11-03 20:48:44.640 [IPClusterStart] Using existing profile dir: u'/scratch/slurm/log/ipython'

I especially do not understand whats going on between those two lines:

> [2017-11-03T19:48Z] cn-12: Resource requests: bwa, sambamba, samtools; memory: 32.00, 32.00; cores: 16, 16, 16
> [2017-11-03T19:48Z] cn-12: Configuring 1 jobs to run, using 1 cores each with 32.00g of memory reserved for each job

The first line represents what I defined in the global resources section and then bcbio seems to fall back into a 1-core mode?

Any idea whats going wrong here?

Thank you!

**Comment by roryk** [comment]
Hi @leiendeckerlu,

Further up from the bottom it should tell you what step it is trying to currently do. The first step in the process is to submit a job to the scheduler, so we can figure out what kind of compute the compute nodes have. That might be what you are seeing.

If it is doing a processing step like alignment, then you might have a file in the checkpoint directory that is stopping it from submitting the job.

**Comment by chapmanb** [comment]
Thanks for the example and help debugging all. It looks like your resource specification in bcbio_system.yaml asks for 32Gb of memory per core (along with 16 cores). It seems like then bcbio determines your machine has 32Gb of total memory and scales the core request down to 1 to avoid over-subscribing memory. You want to set the memory in bcbio_system.yaml to be memory per core, so probably 2Gb in this case to maximize cores (assuming I'm understanding your system resources right). Hope this fixes it for you.

**Comment by leiendeckerlu** [comment]
Thanks for your feedback!

@chapmanb  Indeed I'm using cluster nodes that (should) have 32 GB per core available, so that should not be a limitation. My idea behind setting the memory to 32 GB per core was to determine the overall real memory usage for particular steps in the pipeline and thus adjust the core/memory bcbio_systems.yaml for the respective tool. I observe the same phenomena also with 8 GB per core. Why does bcbio think I only have 32 GB in total if I tell him that indeed there are 512 GB available?
@roryk The first step that is not using multiple threads is bwa mem (since I guess the fastq indexing 
 (grabix) is anyway not multithreaded). Even when running the above mentioned commands in a completely fresh directory it does not scale properly.

**Comment by chapmanb** [comment]
Thanks for the additional details. It sounds like bcbio might not be detecting the available memory on your cluster machines. If you look at `provenance/system-ipython-queue.yaml` that should tell you what bcbio thinks each machine has based on submitting a test job. If you have a heterogeneous cluster this might not identify the memory/core allocation you want. You can specify this manually if not:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#determining-available-cores-and-memory-per-machine

Hope this helps explain what is going on and setting it provides a fix.

**Comment by leiendeckerlu** [comment]
Mhm, so this is what my provenance/system-ipython-queue.yaml looks like:

> - cores: 1
>   memory: 0.0009765625
>   name: slurm_machine

and this is what /local/share/bcbio/galaxy/bcbio_system.yaml looks like:

>   default:
>     memory: 4g
>     cores: 16
>     jvm_opts: ["-Xms750m", "-Xmx3500m"]
>   bwa:
>     cores: 16

So it seems like it is not using the settings in bcbio_system.yaml ?

**Comment by chapmanb** [comment]
Thanks for posting all of the details. The `provenance/system-ipython-queue.yaml` file is what bcbio thinks each machine has. Either your SLURM setup is misconfigured in some way or something else is going wrong in looking at the resources.

The `bcbio_system.yaml` setup you have there doesn't tell bcbio what resources a machine has, it tells it what you want to use. To tell it the correct resources, please add a `resources` section to your configuration as I mentioned in the last comment:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#determining-available-cores-and-memory-per-machine

Hopefully that'll fix it for you.

**Comment by leiendeckerlu** [comment]
@chapmanb Ah well, I misunderstood your previous statement, sorry for that! 

Adding a resources section in my config indeed did the job, everything is running nicely now.

Thank you!
