### ISSUE TITLE
Run macs with different p values cut off or broad and narrow 

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2141]
Hi @lpantano,
Would be possible to run macs2 with different parameters in the same bcbio run?
Let's say you have multiple different chip (TF-chip, k27ac, k27me3, h3k4me3). 

Thanks!
Alessandro

**Comment by lpantano** [comment]
Hi,

I think it should be possible, but it needs some change in the code. I’ll talk to Brad this Friday and change it. Bare with me.

Thanks

**Comment by apastore** [comment]
Thanks a lot!!

**Comment by lpantano** [comment]
Hi,

I changed the code to use the resources specified by sample. If you set up resources inside the sample indentation in the YAML file (same level than `analysis`), then it'll take those options.

Let me know if it doesn't work or you have further issues.

**Comment by apastore** [comment]
thanks!
