### ISSUE TITLE
GATK PrintReads is not respecting the -Xmx and -Xms settings in bcbio_system.yaml

### ISSUE THREAD

**Issue by xexpanderx** [chapmanb/bcbio-nextgen#2145]
I have seen that during GATK PrintReads it uses another Xmx value than in bcbio_system.yaml.

Even If I set -Xmx 7000m in the default settings, PrintReads is running with -Xmx 91000m.

Why does GATK PrintReads not respect the java settings in the bcbio_system.yaml?

**Comment by chapmanb** [comment]
Thanks for the question and sorry for any confusion. The settings in `bcbio_system.yaml` are per-core and are used as guides for determining the actual settings to apply to a tool. They can get scaled up and down depending on the process to try and allocate available system memory sensibly: 

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources

If you're running into problems with what bcbio is doing it would help to see the full error traceback you get to understand the step that's running and what is going wrong. Hope this helps.

**Comment by xexpanderx** [comment]
Hi,
This is the command that is running:
`[2017-11-06T22:53Z] compute05: unset JAVA_HOME && export PATH=/sw/pipelines/bcbio-nextgen/1.0.5/anaconda/bin:$PATH && /sw/pipelines/bcbio-nextgen/1.0.5/anaconda/bin/gatk -Xmx91728m -Djava.io.tmpdir=/gluster-storage-volume/projects/wp3/Test_area/SS61_170825/Outputs/bcbio/bcbiotx/tmp7Y4e6h -T PrintReads -R /data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta -I /gluster-storage-volume/projects/wp3/Test_area/SS61_170825/Outputs/bcbio/align/52683/52683-sort.bam -BQSR /gluster-storage-volume/projects/wp3/Test_area/SS61_170825/Outputs/bcbio/align/52683/52683-sort-recal.grp -o /gluster-storage-volume/projects/wp3/Test_area/SS61_170825/Outputs/bcbio/bcbiotx/tmp7Y4e6h/52683-sort-recal.bam -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment`

The problem with that command is that only one core is used, hence the problematic -Xmx setting. However, the most fatal error is that when using that much of memory GATK crashes. Many users encounters the same error here: https://gatkforums.broadinstitute.org/gatk/discussion/10353/gatk-3-8-0-printreads-fatal-error#latest

There seesm to be a fix for that fatal crash by using the flags: -jdk_deflater and -jdk_inflater. Is it possible to use those flags in the GATK option section in the bcbio_system.yaml when GATK PrintReads is running?

**Comment by chapmanb** [comment]
Thanks for the additional details about the problem. What bcbio does in this case is scale up the memory but not use multiple cores since `-nt` and `-nct` were not stable with PrintReads. However it can benefit from the additional memory available. To confirm, does your machine have 7Gb/memory per core and 16 cores allocated to bcbio?

For your error, would you be able to post the full error traceback and core dump file (if it's core dumping) so we can take a look? We've been working around the deflater/inflater issues by avoiding using some java GC options but I'm worried there might be a different/additional problem here that we're missing and seeing how it fails would be very helpful to diagnose those. Thanks much for the help debugging.

**Comment by xexpanderx** [comment]
Hi,

I attach the log files when PrintReads is failing.
[bcbio-nextgen-logs.zip](https://github.com/chapmanb/bcbio-nextgen/files/1463810/bcbio-nextgen-logs.zip)

**Comment by chapmanb** [comment]
Thanks much for the details and helping with this debugging. I wasn't sure what else to try with this core dump and pushed the `-jdk_deflater -jdk_inflater` fixes recommended in the GATK discussion thread you posted earlier. Please let us know if this doesn't fix the issue and we can try other options. Fingers crossed that all will work cleanly with this change.
