### ISSUE TITLE
Running gatk

### ISSUE THREAD

**Issue by arnoldliaoILMN** [chapmanb/bcbio-nextgen#2148]
Is there instruction on how to run just gatk from bam rather than align from fastq and then gatk

**Comment by chapmanb** [comment]
Thanks for the questions. To use prealigned inputs for variant calling you want to set `aligner: false` and likely also want to set `bamclean` depending on how your inputs were prepared:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

Normally `bamclean: fixrg` will handle cases aligned to the same reference genome and contigs, `remove_extracontigs` will handle if the alignment has additional or different contigs than the bcbio references and `picard` will try to fix other problematic cases. Hope this helps.
