### ISSUE TITLE
bamsormadup not found

### ISSUE THREAD

**Issue by markdunning** [chapmanb/bcbio-nextgen#2155]
Hi all,

I'm trying to process some RNA-seq data and I'm getting an error message

/bin/bash: bamsormadup: command not found

This is the particular command that seems to fail

`subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && /usr/local/community/bcbio-nextgen/2017-08/data/galaxy/../anaconda/bin/bowtie2 -s 100000 -u 250000 -q -x /usr/local/community/bcbio-nextgen/2017-08/data/genomes/Mmusculus/mm10/bowtie2/mm10 --sensitive -X 2000 -1 /shared/bioinformatics_core1/User/md1mjdx/test/GSE65267/samples/work/trimmed/SRR1772151_1_Normalrep1.trimmed.fastq.gz -2 /shared/bioinformatics_core1/User/md1mjdx/test/GSE65267/samples/work/trimmed/SRR1772151_2_Normalrep1.trimmed.fastq.gz | bamsormadup inputformat=sam threads=1 tmpfile=/shared/bioinformatics_core1/User/md1mjdx/test/GSE65267/samples/work/bcbiotx/tmp5yL17g/Normalrep1-sort-sorttmp-markdup SO=coordinate indexfilename=/shared/bioinformatics_core1/User/md1mjdx/test/GSE65267/samples/work/bcbiotx/tmp5yL17g/Normalrep1-sort.bam.bai > /shared/bioinformatics_core1/User/md1mjdx/test/GSE65267/samples/work/bcbiotx/tmp5yL17g/Normalrep1-sort.bam
`

Should this have been included as part of the bcbio install? How do we add this tool?

Thanks!

**Comment by drj11** [comment]
This is on the installation I put on our local HPC at sheffield called `sharc`.

I'll update the tools and see if that helps.

@markdunning can you give a link to the command you run and the config yaml file (it's okay if it's on sharc as long as I can see it).

**Comment by drj11** [comment]
me and @markdunning speculate that it might be because a Java runtime isn't configured on the PATH.

**Comment by chapmanb** [comment]
Mark and David;
`bamsormadup` should be installed as part of bcbio and included into the `--tooldir` path you specify during the installation. If it's not present there that would indicate something was problematic during the install. If it is present you need to be sure that directory is present in the user's path when running. Does adding that to your `PATH` fix the issue?

**Comment by drj11** [comment]
it is in `/usr/local/community/bcbio-nextgen/2017-08/tool/bin` (I just checked).

I'm _slightly_ surprised that we need to add that directory to the `PATH` as really quite a lot of stuff works without needing to do that. I'd assumed that `bcbio` adds its tooldir to its own `PATH` when launching tools.

In any case, it's pretty straightforward, so we'll try adding the tooldir to our `PATH`

**Comment by markdunning** [comment]
Thanks! Adding the tool directory to the `PATH` does seem to do the trick, although I'm not really sure why this would be needed for this tool in particular when other components of bcbio seem to run fine :thinking:

**Comment by chapmanb** [comment]
David and Mark;
Thanks for following up and glad to hear that fixed work. Sorry for any confusion, some parts of the pipeline lookup the local tools automatically but it's not applied consistently. We have a change in the latest development version to do this across all tools so hopefully it'll have more homogenous behavior in the future. Hope all runs well now with your analysis.

**Comment by evchambers** [comment]
Hi all,  I also just got this error running bcbio. I will try adding the directory to the PATH as it seemed to work for Mark.

Emily
