### ISSUE TITLE
RNA-seq with old public 454 data, trim adapter and clip at lenght 300?

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2160]
Hi, 

I am trying to process a set of public RNA-seq samples using bcbio. This is data from various years and different public projects. 

Most of the reads are Illumina data, but some of them are 454 data.  The 454 data does adhere to the recent Sanger/Illumina fastq spec. according to a tool that gueses the fastq format. 

The star aligner as installed by bcbio crashes on the 454 data, because it can't handle the lenght above 300bp. 

See this somewhat uninformative error:
`EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length`

And this issue at star:
https://groups.google.com/forum/#!topic/rna-star/vcNIAQScQt8

Also a fastqc analysis of the trimmed and clipped reads shows that the 454 samples still have c.a. 20% over represesnted sequences, I guess 454 adapters. 

Is is possible in bcbio to set a maximum lenght for RNA-seq reads? To do on the fly trimming at 300bp?  I could not find this option in the `atropos trim`  help. The quality of 454 reads after 300bp is very bad anyway, but I rather not delete if from the file that we permanently store. 

The issue at star mentions that the maximum reads for normal star is c.a. 300, (with optimum below 150).  For 300+ bp starLong is recommended (which is compiled using a different flag).

Also I am wondering if it is possible to trim the 454 adapters.  And I wondering if trimming the adapters is needed. 

The Read trimming documention recommends not to trim with RNA-seq data (unless aligning with tophat)
http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#read-trimming

The RNA-seq template specifies adapter trimming (but also specifies tophat for alignment. )
https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/illumina-rnaseq.yaml

Thank you for you help insight on this.

**Comment by chapmanb** [comment]
Neill;
We don't have much recent experience with 454 data but one suggestion would be to try other aligners like hisat2 for the RNA-seq component, or use kallisto/salmon and skip the alignments altogether. If you want to try to trim these to a smaller size outside of bcbio you could try using `seqtk trimfq -L` which sounds like it would do what you want (https://github.com/lh3/seqtk). I believe atropos can only remove reads above a certain size after trimming but not trim to a maximum length. @roryk might have better suggestions but hope this helps some.

**Comment by roryk** [comment]
Brad's suggestions are spot on, I'd trim them outside of bcbio if that is possible and you want to run the full pipeline. You could also run the fast RNA-seq pipeline, which won't do the STAR alignments at all, it will just run Salmon and that's it so it shouldn't have this problem.

**Comment by NeillGibson** [comment]
Ok. Thank you for your suggestions. I will trim the reads with seqtk to 300bp. 

Is adapter trimming by the way needed or required for RNA-seq alignment with STAR?

I know that in whole genome DNA-seq BWA just hard / soft clips the adapters. 

I don't know if adapters are are potential problem with RNA-seq alignment with STAR?

**Comment by roryk** [comment]
Great, sounds like a good plan. STAR also soft clips, so it should not be an issue.

**Comment by NeillGibson** [comment]
Ok. Thank you.

**Comment by roryk** [comment]
Sweet, let us know how that works. Sorry this didn't work out of the box, we don't see much 454 data.
