### ISSUE TITLE
GATK4 RNA-seq: STAR Mapping quality needs to be reassinged from 255 to 60

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2163]
Hi, 

Using bcbio 1.0.6 GATK4 produces full chromosome low quality reference calls. With not a single variant. This is because all STAR mapped reads are filtered out:

```
tSecondaryAlignmentReadFilter) AND NotDuplicateReadFilter) AND PassesVendorQualityCheckReadFilter) AND NonZeroReferenceLengthAlignmentReadFilter) AND GoodCigarReadFilter) AND WellformedReadFilter)
  383409 read(s) filtered by: (((((((MappingQualityReadFilter AND MappingQualityAvailableReadFilter) AND MappedReadFilter) AND NotSecondaryAlignmentReadFilter) AND NotDuplicateReadFilter) AND PassesVendorQualityCheckReadFilter) AND NonZeroReferenceLengthAlignmentReadFilter) AND GoodCigarReadFilter)
      383409 read(s) filtered by: ((((((MappingQualityReadFilter AND MappingQualityAvailableReadFilter) AND MappedReadFilter) AND NotSecondaryAlignmentReadFilter) AND NotDuplicateReadFilter) AND PassesVendorQualityCheckReadFilter) AND NonZeroReferenceLengthAlignmentReadFilter)
          383409 read(s) filtered by: (((((MappingQualityReadFilter AND MappingQualityAvailableReadFilter) AND MappedReadFilter) AND NotSecondaryAlignmentReadFilter) AND NotDuplicateReadFilter) AND PassesVendorQualityCheckReadFilter)
              383409 read(s) filtered by: ((((MappingQualityReadFilter AND MappingQualityAvailableReadFilter) AND MappedReadFilter) AND NotSecondaryAlignmentReadFilter) AND NotDuplicateReadFilter)
                  383409 read(s) filtered by: (((MappingQualityReadFilter AND MappingQualityAvailableReadFilter) AND MappedReadFilter) AND NotSecondaryAlignmentReadFilter)
                      383409 read(s) filtered by: ((MappingQualityReadFilter AND MappingQualityAvailableReadFilter) AND MappedReadFilter)
                          383409 read(s) filtered by: (MappingQualityReadFilter AND MappingQualityAvailableReadFilter)
                              22135 read(s) filtered by: MappingQualityReadFilter
                              361274 read(s) filtered by: MappingQualityAvailableReadFilter

12:25:51.908 INFO  ProgressMeter -      Chr_07:19225501              2.8                639533         229298.6
12:25:51.908 INFO  ProgressMeter - Traversal complete. Processed 639533 total regions in 2.8 minutes.
12:25:52.169 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.0
12:25:52.169 INFO  HaplotypeCaller - Shutting down engine
[November 19, 2017 12:25:52 PM CET] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 2.83 minutes.
Runtime.totalMemory()=1243856896
```

I checked with qualimap and almost all reads in the {Sample}-dedup.splitN.bam files have mapping quality 255.

There is this older GATK post that mentions that GATK considers the STAR mapping quality value 255 invalid, and those values are best reassigned to mapping quality 60. 
https://software.broadinstitute.org/gatk/blog?id=4285

For GATK3.8 reassigning the mapping quality 255 to 60 can be done as follows:
`java -jar GenomeAnalysisTK.jar -T SplitNCigarReads -R ref.fasta -I dedupped.bam -o split.bam -rf ReassignOneMappingQuality -RMQF 255 -RMQT 60 -U ALLOW_N_CIGAR_READS`

For GATK4 SplitNCigarReads  `-rf ReassignOneMappingQuality -RMQF 255 -RMQT 60` are not valid arguments.

 I guess the argument has been renamed, I am trying to find the correct documentation but so far could not find the documentation on how to do this in GATK4.

**Comment by chapmanb** [comment]
Neill -- thanks much for testing out the GATK4 integration with RNA-seq and for the digging into this. Apologies, I implemented the initial support but, like you, got stuck when I realized there is no current way to replicate the suggested GATK3 reassignment commands. I'm not how best to approach this with GATK4 and it might be worth starting a thread on the GATK forum (https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team) to see what they suggest. If they can point us in the right direction I'd be happy to implement them in bcbio. Thanks again for helping to look into this.

**Comment by NeillGibson** [comment]
Ahh I didn't expect to be one of the first people to run into this.  I Opened a ticket at GATK
https://gatkforums.broadinstitute.org/gatk/discussion/10800/gatk4-how-to-reassign-star-mapping-quality-from-255-to-60-with-splitncigarreads/p1?new=1

**Comment by NeillGibson** [comment]
Hi @chapmanb . According to Geraldine_VdAuwera from GATK this functionality won't be implemented in GATK4 because recent versions of STAR have the functionality to output a different value for uniquely mapping reads. 

This indeed seems to be the case according to this quote from the STAR manual:

> The mapping quality MAPQ (column 5) is 255 for uniquely mapping reads, and int(-10*log10(1-
> 1/Nmap)) for multi-mapping reads. This scheme is same as the one used by TopHat and is com-
> patible with Cuinks. The default MAPQ=255 for the unique mappers maybe changed with
> --outSAMmapqUnique parameter (integer 0 to 255) to ensure compatibility with downstream tools
> such as GATK.
https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf

So what is needed I think is just adding `--outSAMmapqUnique 60` in STAR CLI. 

One risk that I see is that this maybe fixed the issue with GATK, but creates an issue with other downstream tools (e.g. Cuinks) that expect 255 as the mapping quality for uniquely mapped reads.

**Comment by roryk** [comment]
Thanks everyone, I swapped STAR to use that parameter, and added a function to set them back to 255 if Cufflinks has to be run.

**Comment by NeillGibson** [comment]
Thank you.

**Comment by noelnamai** [comment]
`--skip-mapping-quality-transform` in **SplitNCigarReads**.
