### ISSUE TITLE
docker-based bcbio installation on a cluster

### ISSUE THREAD

**Issue by PedroBarbosa** [chapmanb/bcbio-nextgen#2165]
Hello,

I'm willing to install bcbio on a HPC machine that is based on a slurm scheduling system, but i'm not sure how to proceed in this specific case. 

I'm not sysadmin, so, as normal users we are just allowed to pull docker images and submit batch jobs. The docker images are processed with shifter,  and that's here my doubts came up.

You mention in the bcbio-nextgen-vm page that something like  "`bcbio_vm.py --datadir=~/install/bcbio-vm/data install --data --tools --genomes GRCh37 --aligners bwa`" should install a dockerized bcbio-nextgen. I believe that with our setup, a "`shifterimg pull bcbio/bcbio`" cmd should do the job , right ?

My other  question lies on how to run it. Would I need to create a docker image that contains bcbio-vm wrapper ? I could try to install bcbio-vm on my home folder, but the tool wouldn't be available to other users. I guess a potential command to generate a sbatch script to run on a scheduler would be:

`shifterimg pull bcbio_vm_docker_image`
`srun shifter --image=bcbio_vm_docker_image bcbio_vm.py ipythonprep --image=bcbio/bcbio ...`

Does this make any sense? 
Thanks in advance,
Pedro

**Comment by chapmanb** [comment]
Pedro;
Thanks for the question and starting this discussion. Unfortunately, bcbio-vm currently doesn't interact with shifter so we don't have a good way to support this.

Does your cluster require Docker usage or can you do a local non-Docker installation? A standard installation, which does not require sysadmin privileges, should work cleanly on SLURM HPC systems (http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated). That would be the most practical way to get bcbio running for your analysis.

Longer term we'd like to support shifter and singularity for HPC container runs but will plan to do that using the Common Workflow Language support in bcbio and external runners such as Toil (http://toil.readthedocs.io/). If you'd like to pursue the shifter path it would be worth opening a discussion there to see about their plans/ideas for supporting this setup.

Thanks again for the questions and hope this helps.

**Comment by PedroBarbosa** [comment]
Brad,

Thanks for the clarifications. My cluster requires Docker usage, so I guess the only solution is to create a Docker image of the standard instalation (that's actually what we do for other tools).  I guess it's feasible right? How would I look to GATK here? Could I run `gatk-register /path/to/GenomeAnalysisTK.tar.bz2`
inside the docker file, or due to the licence restrictions the solution would be to install an older version as you suggest in the installation page ? In my case would something like `srun shifter --image=bcbio_myOwnImage bcbio_nextgen.py upgrade --tools --toolplus gatk=/path/to/gatk/GenomeAnalysisTK.jar`

I want to do an extensive variant calling analysis and compare several callers, that's why I thought bcbio would be very valuable here. If it's too much work to get it working, I may create a docker image for each tool (i think some of them already have docker images in the cluster). A long term support would be perfect, but I definitely need to learn more about the setup you mentioned, this cluster thing is all new for me.

Thank you Brad,
Pedro Barbosa

**Comment by chapmanb** [comment]
Pedro;
Thanks for the additional details. It sounds like to take full advantage of your cluster we'd need to work on having bcbio integrate with shifter. If you don't need to run bcbio in a fully distributed way and can just use it running on single machines with multiple cores, you could make use of the existing docker containers:

https://github.com/bcbio/bcbio_docker

The challenge is around mapping the data into the containers, which is what bcbio-vm (and other tools like Toil or rabix-bunny for CWL) do for you.

For GATK, I'd suggest using GATK4 which is freely available and included inside the bcbio-vc Docker containers. You can run gatk-register if you need GATK3 specifically and bcbio_vm.py has a command to do that (mount the jar, run update inside the container, then build a new version):

https://github.com/chapmanb/bcbio-nextgen-vm#updates

Sorry to not have a solution for this setup in place now but hope this helps some.

**Comment by PedroBarbosa** [comment]
Hello again Brad,

I tried to pull [bcbio-vc](https://quay.io/repository/bcbio/bcbio-vc?tab=tags), but it seems we are unable tu pull images stored at quay registry service. It must be from dockerhub. I could pull the full bcbio/bcbio image from dockerhub, but I guess that one doesn't include the last GATK version, and includes tools I don't need.

Is it easy to migrate the image from quay into docker hub?

Best,
Pedro

**Comment by chapmanb** [comment]
Pedro;
I just rebuilt the bcbio/bcbio image on Docker hub so you can try and use this one. It will have the latest code and tools. It's a bit larger than the bcbio-vc one but is reasonable to use if the quay.io won't work.

Out of curiosity, have you discussed with the cluster admins about the quay.io issue? I'm not sure why they'd exclude builds from there since it's a pretty widely used repository and has a lot of nice hooks for automating builds.

Hope this helps.

**Comment by PedroBarbosa** [comment]
Thank you very much Brad, that's all what I need :)

Yes, I opened a ticket about this topic, but they didn't tell me the reason. This cluster is just some months old, i'm aware that some things are still experimental and new features will be added over time.

Pedro

**Comment by PedroBarbosa** [comment]
Well, I think the build of the image failed :)

**Comment by chapmanb** [comment]
Pedro -- thanks for the heads up and apologies about the build issues. I've rebuilt and the latest is available now, please let us know if you run into any problems.

**Comment by PedroBarbosa** [comment]
Hello again Brad,

I'm finally testing the latest bcbio image in the cluster environment that runs shifter (there were some issues pulling the image due to its big size). However, now I'm facing the same problem reported in #2091 and as I explained above, I need to stick to this running scheme due to the cluster requirements.

Could you provide me some help on how to manually mount the bcbio_system.yaml file into the container ?

Best,
Pedro

**Comment by chowbina** [comment]
I am facing the same issue when trying to run bcbio_nextgen on CentOS 6.9, not sure if this is related. Bcbio was installed using conda manager.

```
../../miniconda/bin/bcbio_nextgen.py var_tumo_only_bcbio.yml

Traceback (most recent call last):
  File "../../miniconda/bin/bcbio_nextgen.py", line 237, in <module>
    main(**kwargs)
  File "../../miniconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/mnt/miniconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 36, in run_main
    config, config_file = config_utils.load_system_config(config_file, workdir)
  File "/mnt/miniconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 69, in load_system_config
    (config_file, os.path.join(base_dir, "galaxy")))
ValueError: Could not find input system configuration file bcbio_system.yaml, including inside standard directory /mnt/galaxy
```

**Comment by chapmanb** [comment]
Pedro -- glad that you've made some progress on the bcbio install in your environment. How are you planning to install and manage the reference data with genome indices and supporting files? In the current scheme we install these outside of the Docker image and then mount them in, which will include the bcbio_system.yaml file. `bcbio_vm.py` can automatically do the install for you: https://github.com/chapmanb/bcbio-nextgen-vm#installation  Would that work with your cluster setup?

Sudhir -- it sounds like you installed just the bcbio wrapper scripts using `conda`, is that correct? If so, you'll need to also install the reference data and associated tools to run analyses. The automated installer (http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated) will handle setting this all up inside an isolated conda environment.

Hope this helps you both get analyses running.

**Comment by PedroBarbosa** [comment]
Well, I was expecting that using the current docker image I would be able to run it as if i was in a singe machine.  I thought that the genome indices would be mounted there already. So, to my naive knowledge I guess there is no harm on creating a docker image of bcbio_vm to run bcbio on my cluster using shifter, but you said before that those two don't interact, so I'm a bit on a deadlock here.

**Comment by chowbina** [comment]
The automated installer worked like a charm. Thank you @chapmanb

**Comment by chapmanb** [comment]
Sudhir -- thanks for reporting back and glad that worked for you.

Pedro -- sorry about the issues, we're not really setup for this type of Docker only environment right now except using the newer CWL support (http://bcbio-nextgen.readthedocs.io/en/latest/contents/cwl.html) but I don't think that'll work on your setup due to using shifter. The challenge you have is to be able to download and prep the data on your filesystem so it can be linked in. We can't include these in the Docker image itself due to size constraints. You could do the install of data using bcbio_nextgen.py itself and then manually mount the output directory into the container but I don't have a good step by step for you.

My practical suggestion at this point would be to use your internal setup to install standard bcbio plus the data you need inside one of your shifter images, using the automated installer: http://bcbio-nextgen.readthedocs.io/en/latest/contents/installation.html#automated. Then hopefully you could build a fat container with the data you need without needing to download, then use this to run your analyses. 

Hope that would work to get things running. Sorry again about not having a good setup for your system.

**Comment by PedroBarbosa** [comment]
Brad,

I gave up on using bcbio for my work. It seems too much effort to get things running, and our cluster has still some issues with large images. I'm installing some tools manually. Hope to have the opportunity to use this great pipeline someday for another project.

Thank you for all the help Brad,
Pedro
