### ISSUE TITLE
Regression from d2b75b3: pre-existing disambiguate files are not accounted for

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2172]
cc @LMannarino

d2b75b3 changed the names of the files during disambiguation. This is a backwards-incompatible change, however, which means that pre-existing runs will have to run through disambiguation again, even if it was done already.

**Comment by chapmanb** [comment]
Luca -- sorry about the extra re-run work here. Do you have an example directory from an old run and what the names we should look for are? Apologies, I'm not very familiar with the disambiguate code and the re-write work from @tetianakh. It looks like she tried to improve the naming of files but we could add a check for the old case to skip all the additional work and limit the re-running. Thanks for starting this discussion.

**Comment by lbeltrame** [comment]
The new files are in `work/align/<name>/disambiguate_bwa` and they have names like `human`, `explant` and `ambiguous`.

The old ones were in the `<name>` folder and they had suffixes like `disambiguatedSpeciesA.sorted`.

**Comment by chapmanb** [comment]
Luca -- thanks for this, I've been reading through the changes more and am thinking about reverting this to the more general previous version. Some of the changes are cleaner but in general it does change things quite drastically which I can to do. 

@schelhorn -- the disambiguation changes came in as part of Tetiana's Ericscript work and I'm not entirely sure if there are specific needs it addresses for you or if it was a general cleanup. Thanks for any background help and I'll work to tackle resolving it.

**Comment by lbeltrame** [comment]
Brad, I would vote for a revert: I just noticed that the presence of BAM indices is not accounted for, so the files aren't indexed (or the index is not correctly symlinked) causing failures due to "missing" BAM indices.

**Comment by schelhorn** [comment]
General cleanup only, I believe. Going back to a previous version should be fine. Thanks for the integration.

**Comment by chapmanb** [comment]
Luca and Sven-Eric;
Thanks so much for the feedback and thoughts. I've reverted this back to the previous version prior to integration. This should now be fully back-compatible and behave as previously. Thanks again for the help talking through the pros and cons here.
