### ISSUE TITLE
RNA-seq transcript_assembler documentation question

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2173]
Hi,

I have a  questions regarding the RNA-seq documentation:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#rna-sequencing
```
RNA sequencing

- transcript_assembler: If set, will assemble novel genes and transcripts and merge the results into the known annotation. Can have multiple values set in a list. Supports [‘cufflinks’, ‘sailfish’].

```

Are  `[‘cufflinks’, ‘sailfish’]` both options for transcript_assembler? I understand from @roryk here https://github.com/chapmanb/bcbio-nextgen/issues/2166 that sailfish just does quantification. So is really then ‘cufflinks’ is the only option for `transcript_assembler`?

Thank you.

**Comment by roryk** [comment]
Heya-- sorry about that, I missed this issue. This is an error in the documentation, it should be stringtie, not sailfish. I fixed the documentation. Thank you!
