### ISSUE TITLE
RNA-Seq gatk-haplotype question

### ISSUE THREAD

**Issue by rdocking** [chapmanb/bcbio-nextgen#2189]
Hi there:

  I have some questions about variant-calling from RNA-Seq data using bcbio - any advice would be greatly appreciated. Here's what I've tried:
  
  1. I tried running the RNA-Seq pipeline with `variantcaller: [gatk-haplotype]` turned on, hoping to get full-transriptome variant calls. The relevant part of my `resources` section looks like:
  
```
resources:
  default:
    memory: 3G  # 3*32 ~= 96G
    cores: 32
    jvm_opts: ["-Xms800m", "-Xmx3600m"]
  gatk:
    jvm_opts: ["-Xms800m", "-Xmx3600m"]
```
  
  ... and submitting with 192 cores on our cluster. While it seems most parts of the RNA-Seq pipeline are nicely parallelized and take advantage of lots of cores, I can't seem to get the `gatk-haplotye` part of the pipeline to run in a more than single-threaded way. Is that expected at present or am I setting something incorrectly here? 
  
  At present, the variant-calling runs, but the time it takes won't make it feasible for the amount of samples I'd like to process. As alternatives, I've tried:

  2. Feeding the STAR BAM files from the RNA-Seq pipeline into the `variant2` pipeline. This works in a nicely parellelized way, but I realized I was getting a ton of false-positive calls from `gatk-haplotype`, since the 'splitN' pre-processing step wasn't present.
  
  3. I then tried running the RNA-Seq pipeline up to the 'splitN' stage, then halting it and using those BAM files for the `variant2` pipeline. This works, but is a bit manual (and still misses some of the extra GATK filtering steps that are present in the RNA-Seq pipeline).
  
  At present, I'm trying to decide between (a) staying with the RNA-Seq pipeline, and calling variants on a more limited subset of genes (~100 genes with known relevance to the disease I'm working on) or (b) Trying to re-implement some of the extra filtering steps so I can use the regular `variant2` pipeline with my STAR BAM files.
  
  Any thoughts here? I'm leaning towards calling variants in the smaller subset, and coming back to the 'whole-transcriptome' variants once some of the work mentioned in #2080 is more mature.
  
  Thanks again for all your help!

**Comment by roryk** [comment]
Thanks Rod.

Sorry for the problems, you ran into one we haven't got to improving. The variant calling in the variant2 pipeline is so fast because it splits the calling into regions based on the alignments and then calls those regions in parallel. We don't do that for the RNA-seq variant calling so it ends up being a lot slower. It should still be running GATK in parallel, though, just not splitting it into many regions, is it not doing even that? Getting that working properly would be good. @chapmanb I see on the Broad site that `-nct` can cause problems with HaplotypeCaller, is there a way to get it to run in parallel without that?

**Comment by rdocking** [comment]
Thanks @roryk ! It does seem like GATK isn't running in parallel. I.e., here are the resource requests I'm seeing in the log:

```
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Resource requests: picard, samtools, star; memory: 2.00, 2.00, 2.00; cores: 16, 16, 16
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Configuring 1 jobs to run, using 16 cores each with 32.1g of memory reserved for each job
...
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Resource requests: cufflinks, samtools; memory: 2.00, 2.00; cores: 16, 16
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Configuring 1 jobs to run, using 16 cores each with 32.1g of memory reserved for each job
...
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Resource requests: dexseq, express; memory: 2.00, 2.00; cores: 1, 1
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Configuring 1 jobs to run, using 1 cores each with 2.00g of memory reserved for each job
...
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Resource requests: gatk; memory: 2.40; cores: 1
[2017-12-18T18:59Z] ccgihpc.hpc.bcgsc.ca: Configuring 1 jobs to run, using 1 cores each with 2.40g of memory reserved for each job
```

**Comment by chapmanb** [comment]
Rod and Rory;
Thanks much for this discussion and your patience while we worked on improving it. In GATK3 the parallel `-nct` option did give problems so we we're able to use it. If you update to the latest development this uses GATK4 HaplotypeCallerSpark for multicore running of each call. When running on a cluster you should get samples allocated in parallel to individual nodes and then have each of these samples however many cores you have set for either `default` or `gatk` in your bcbio_system.yaml resources file:
```
resources:
   default:
      cores: 16
```
with GATK4 the Spark implementation will then parallelize over these cores. The Spark work on the GATK side is still in progress so please let us know if you run into any problems. Thanks again for your patience and suggestions for improving this.

**Comment by rdocking** [comment]
Great - thanks for the update! I'll give this a shot.

**Comment by roryk** [comment]
Thanks Brad, that's awesome.
