### ISSUE TITLE
hisat2-build parameter issue

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#2191]
So I just tried to update to the latest bcbio development build and during update `hisat2-build` was called for `hg19` to make a exon/splice-aware index (I have enabled HISAT2 indexes, so that is expected). 

However, the build commend line is called with `--exons` and `--splicesites` while in the latest HISAT2 conda version that I have (2.1.0 in channel Bioconda), these parameters are called `--exon` and `--ss`. So the automatic command failed but when I ran it manually with the correct parameter names the update worked just fine. 

Please check and align the commend line call and the binary version.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks much for the report and for the detailed investigation into what was going on. This was a huge help for fixing. I've pushed these changes to cloudbiolinux so it should work automatically going forward. Thank you again.
