### ISSUE TITLE
IOError: Could not prepare index hisat2 for phix by any method

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2194]
I use the following command to build the hisat2 index for phix
`bcbio_nextgen.py upgrade --genomes phix --aligner hisat2`
But error occurred, the messages is as below:

> INFO: Preparing genome phix with index hisat2
> INFO: Moving on to next genome prep method after trying raw 
> Traceback (most recent call last):
>   File "/app/smartngs/biotools/bin/bcbio_nextgen.py", line 215, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
>     upgrade_bcbio_data(args, REMOTES)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
>     cbl_deploy.deploy(s)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
>     configure_instance(options, actions)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
>     setup_biodata(options)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
>     install_proc(options["genomes"], ["ggd", "s3", "raw"])
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
>     _prep_genomes(env, genomes, genome_indexes, ready_approaches)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
>     raise IOError("Could not prepare index {0} for {1} by any method".format(idx, gid))
> IOError: Could not prepare index hisat2 for phix by any method

**Comment by chapmanb** [comment]
Thank you for the report and sorry about the issue, the hisat2 indexing code had gotten out of sync with the latest release. We pushed a fix for this to cloudbiolinux so if you remove your cached download (`rm -rf tmpbcbio-install`) and re-run in place it should pick up where it left off and hopefully index this cleanly now. Thanks again for letting us know about the problem.
