### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'bcbio_home/genomes/Cfamiliaris_Dog/canFam3/hisat2/canFam3.exons'

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2198]
when I tried to build the hisat2 index for canFam3, the upgrade process crashed because of this error:

> Traceback (most recent call last):
>   File "/app/smartngs/biotools/bin/bcbio_nextgen.py", line 215, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
>     upgrade_bcbio_data(args, REMOTES)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in upgrade_bcbio_data
>     cbl_deploy.deploy(s)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 65, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 110, in _setup_vm
>     configure_instance(options, actions)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 268, in configure_instance
>     setup_biodata(options)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 250, in setup_biodata
>     install_proc(options["genomes"], ["ggd", "s3", "raw"])
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 338, in install_data
>     _prep_genomes(env, genomes, genome_indexes, ready_approaches)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 485, in _prep_genomes
>     _index_to_galaxy(org_dir, ref_file, gid, genome_indexes, manager.config)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 530, in _index_to_galaxy
>     index_file = get_index_fn(idx)(ref_file)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 425, in decorator
>     return func(*args, **kwargs)
>   File "/root/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 758, in _index_hisat2
>     if os.stat(exons_file).st_size > 0 and os.stat(splicesites_file).st_size > 0:
> OSError: [Errno 2] No such file or directory: '/app/smartngs/bcbio/genomes/Cfamiliaris_Dog/canFam3/hisat2/canFam3.exons'
> 

How to work it out? Thanks

**Comment by chapmanb** [comment]
Sorry about the continued issues, I believe this was due to a typo when applying the fixes earlier. If you remove your temporary download (`rm -rf tmpbcbio-install`) and re-run as before I hope it will work cleanly now. Thanks for the help debugging and testing.
