### ISSUE TITLE
An error occurred writing the index to disk

### ISSUE THREAD

**Issue by theoAlexander** [chapmanb/bcbio-nextgen#2199]
Hi,

I got a memory error, when running the RNAseq pipeline on a single-cell data set with 4000 cells, see below:

Exiting Ebwt::buildToDisk()
An error occurred writing the index to disk.  Please check if the disk is full.
Total time for call to driver() for forward index: 00:12:27
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 --offrate 1 /scratch/kshd061/8848688/tmpeGWyqq.fa /scratch/kshd061/8848688/tmpeGWyqq
Deleting "/scratch/kshd061/8848688/tmpeGWyqq.3.bt2" file written during aborted indexing attempt.
Deleting "/scratch/kshd061/8848688/tmpeGWyqq.4.bt2" file written during aborted indexing attempt.
Deleting "/scratch/kshd061/8848688/tmpeGWyqq.1.bt2" file written during aborted indexing attempt.
Deleting "/scratch/kshd061/8848688/tmpeGWyqq.2.bt2" file written during aborted indexing attempt.
' returned non-zero exit status 1
[15:apply]: IOError: [Errno 28] No space left on device
[15:apply]: SamtoolsError: 'samtools returned with error 1: stdout=, stderr='
.... 2718 more exceptions ...

Apparently the directory /scratch has fixed size on all nodes in my cluster and cannot be increased.
I ran the pipeline on 256 cores like this:

bcbio_nextgen.py ../config/bcbio_rnaseq_kallisto.yaml -t ipython -n 256 -s slurm -q ubique -p Sandberg_Kallisto -r "timelimit=240:00:00" --timeout 1440

So what I am trying at the moment is to reduce the number of cores to 136 and see if that helps, do you have any other tips to prevent this error?

Thanks a lot!

Alexander

**Comment by roryk** [comment]
Hi Alexander,

It looks like the scratch space has been filled up, is there another place where you can run your analysis which will have more space?

**Comment by theoAlexander** [comment]
Hi Rory,

ok then it is not really a problem with the pipeline, but with the cluster where I am running it. Although I ran lots of analysis before and never had that problem. I will try reducing the number of cores I am using ... or splitting the dataset in half and running the two halves consecutively...

Thanks anyways!

Alexander
