### ISSUE TITLE
Can bcbio continue running from the failure step of a previous run?

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2201]
Hi, I wonder if bcbio can start run on the failure step of previous run? For example, I am processing quite a few RNA-seq samples using bcbio, and it has successfully finished the alignment but failed in the  estimate expression step due to some reason. As the alignment is time-consuming, I want bcbio continue to run based on previous finished steps, rather than run from scratch.

**Comment by chapmanb** [comment]
Yes, bcbio will restart runs at the step where they stopped, re-using previous calculations. This happens automatically based on checking for the presence of files in the work directory so you don't need to do anything special other than restart. Thank you for the question and hope this helps.
