### ISSUE TITLE
How bcbio scale jobs to cluster?

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2202]
I am quite confused to the memory usage and job assignment to the cluster. In the bcbio_system.yaml file I configured the cores 16G and memory  3G. According to the bcbio document it means that each core will use 3G memory. Meanwhile, does this configuration also specify that each job will use 16 cores? If so, I use the parameter -n 16 bcbio will only run one job even if I have adequate cores and memory in my cluster?  is my understand right?

**Comment by chapmanb** [comment]
Thanks for the question, the interaction between the bcbio_system specification and `-n` is documented here:

http://bcbio-nextgen.readthedocs.io/en/latest/contents/parallel.html#tuning-core-and-memory-usage

In short, the bcbio_system cores and memory specify how many resources to ask for on each machine in the cluster, and `-n` specifies the total cores to try and allocate. So you're exactly right, if you specify 16 cores in bcbio_system and `-n 16` you'll get one job allocated. If you specify `-n 32` it'll get two jobs with 16 cores, and so on. Hope this helps.
