### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by MurliNair** [chapmanb/bcbio-nextgen#2205]
Hi Brad, 
I installed bcbio on my new genomics server. The installation went fine. The test script also ran successfully. 
The output for the test is here http://bioinformatics.iusb.edu/errors/qsubtest_sh_o490938.txt
When I ran the cancer-normal example it gave a java version error.  The output is here http://bioinformatics.iusb.edu/errors/nohup_cancerNormal_1_3_18.txt
The output of  bcbio_conda list | grep gatk-framework 
gatk-framework            3.6.24                        4    bioconda

java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
I would appreciate your input. 
Thanks ../Murli

**Comment by chapmanb** [comment]
Murli;
Thanks for the questions. I'd suggest removing `mutect` from your `variantcaller` input in the dream-syn3 YAML file. MuTect requires Java 1.7 so needs an external java installation as bcbio ships with java 1.8. If you don't need it for other work and can use other callers like VarDict, strelka2 and MuTect2 you can safely remove it for your tests. Hope this helps.

**Comment by MurliNair** [comment]
Thanks Brad. I changed it to mutect2 in the yaml file and submitted the job. Shall report back on the completion of the job.

**Comment by MurliNair** [comment]
Thanks Brad, the job ran to completion successfully.

**Comment by MurliNair** [comment]
Hi Brad,
I had to reinstall bcbio  but this time I did not install mutect1 and when I ran the run_tests.sh, I did get some errors http://www.bioinformatics.iusb.edu/errors/nohup.out_Jan9_reinstall.txt
Thanks for your help.
Cheers../Murli

**Comment by chapmanb** [comment]
Murli -- this output looks like all of the tests passed so there is nothing to worry about in the outputs. Some tools, like peddy, fail on small datasets but bcbio can recover and just skip over those. Let me know if there is anything in specific that concerns you in the test run.

**Comment by MurliNair** [comment]
Thanks Brad, I will set up a test run  (cancer-normal) from one of my students account and hopefully I have done everything correctly. Shall let you know.
