### ISSUE TITLE
Error in updating the GRCh37 VEP data

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2206]
@chapmanb
Hi, I try to update my bcbio installation, it has successfully download the homo_sapiens_merged_vep_91_GRCh37.tar.gz file (~8G) from the link ftp://ftp.ensembl.org/pub/release-91/variation/VEP/homo_sapiens_merged_vep_91_GRCh37.tar.gz. However, bcbio failed because the following error:

> --2018-01-03 21:22:27--  ftp://ftp.ensembl.org/pub/release-91/variation/VEP/homo_sapiens_merged_vep_91_GRCh37.tar.gz
>   (try: 2) => ‘homo_sapiens_merged_vep_91_GRCh37.tar.gz’
> Connecting to ftp.ensembl.org|193.62.193.8|:21... connected.
> Logging in as anonymous ... Logged in!
> ==> SYST ... done.    ==> PWD ... done.
> ==> TYPE I ... done.  ==> CWD (1) /pub/release-91/variation/VEP ... done.
> ==> SIZE homo_sapiens_merged_vep_91_GRCh37.tar.gz ... 8542340035
> File has already been retrieved.
> 2018-01-03 21:22:29 (0.00 B/s) - ‘homo_sapiens_merged_vep_91_GRCh37.tar.gz’ saved [8542340035]
> Traceback (most recent call last):
>   File "/app/smartngs/bcbio/anaconda/bin/bcbio_nextgen.py", line 222, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 96, in upgrade_bcbio
>     upgrade_bcbio_data(args, REMOTES)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 298, in upgrade_bcbio_data
>     _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 335, in _upgrade_vep_data
>     effects.prep_vep_cache(dbkey, ref_file, tooldir)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 108, in prep_vep_cache
>     do.run("%s && %s" % (perl_exports, " ".join(cmd)), "Convert VEP cache to tabix %s" % ensembl_name)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
>     _do_run(cmd, checks, log_stdout, env=env)
>   File "/app/smartngs/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
>     raise subprocess.CalledProcessError(exitcode, error_msg)
> subprocess.CalledProcessError: Command 'set -o pipefail; unset PERL5LIB && export PATH=/app/smartngs/bcbio/anaconda/bin:$PATH && /app/smartngs/biotools/bin/vep_convert_cache --species homo_sapiens_merged --version 91_GRCh37 --dir /app/smartngs/bcbio/genomes/Hsapiens/GRCh37/vep --force_overwrite --remove
> ERROR: Version 91_GRCh37 not found
> ' returned non-zero exit status 255

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the issue. I think this issue is due to not having an out of date `ensembl-vep`. You'll need to have 91.0 in order to upgrade the data. If you also run `bcbio_nextgen.py upgrade --tools` and then re-run the data upgrade it should pick up where it left off and finish cleanly. Please let us know if you run into any other issues.
