### ISSUE TITLE
How to get the intermediate stage of a running pipeline?

### ISSUE THREAD

**Issue by hliu2016** [chapmanb/bcbio-nextgen#2207]
@chapmanb
Thanks for your wonderful work. I have a question about the bcbio, that is, how can I know which step is currently executed of a running pipeline, and how many steps of a specific pipeline?
Furthermore, if a pipeline failed, Can I receive a signal from bcbio, such as an email or other something message?

**Comment by roryk** [comment]
Hi @hliu2016,

There is progress output written in the log/bcbio-nextgen-debug.log file, and also from whatever scheduler you are running in the stdout file from that. You can have the scheduler you are running send you an email if the job fails, it depends on what scheduler you are using though.
