### ISSUE TITLE
Is GATK4.0 release already included in the latest bcbio. 

### ISSUE THREAD

**Issue by NeillGibson** [chapmanb/bcbio-nextgen#2213]
Hi, 

Thank you for your 3rd party evaluation and collaboration with the Broad on GATK4. 
For example comparisons against freebayes and ensuring  compatibility with other RNA-seq tools etc.  I watched the release event yesterday with great interest. 

I would like to try out the new official GATK4.0 which was released yesterday. 

Is GATK4 final release already included in bcbio? Should I just install the latest bcbio development version?

Thank you.

**Comment by chapmanb** [comment]
Neill;
Thank you for the discussion on this. The latest development version has 4.0beta6 right now and we're hopeful to have the final 4.0.0.0 release in soon. We're working on a bioconda package first and then I'll test with bcbio to ensure there are no incompatibilities relative to the beta6 release. We'll also plan to make gatk4 the default in the development version (so require a `tools_off: [gatk4]` if you want to use GATK version 3 or older) as part of this. I can update this ticket when it's all ready to go.

**Comment by NeillGibson** [comment]
Ok thank you for the information. I look forward to the bcbio release with GATK4.0.0.0 .

**Comment by chapmanb** [comment]
Neill -- thanks again for this discussion. The latest development version now support GATK 4.0, which will also get installed as a conda package if you update. There were some command line parameter changes that 4.0 introduced that required concurrent updates in bcbio. As a last step I'll plan to make GATK4 the default caller and swap to using `tools_off: [gatk4]` but for now if you run with `tool_on: [gatk4]` it will use the latest version. Please let us know if you run into any issues.
