### ISSUE TITLE
running cnvkit with matched normal

### ISSUE THREAD

**Issue by AmandaMilou** [chapmanb/bcbio-nextgen#2215]
I used the bcbio-nextgen pipeline to call SVs with cnvkit on matched tumor-normal WGS samples. When i examine the cnvkit commands, I noticed that although the coverage of the matched normal samples were calculated (*.targetcoverage.cnn and *.antitargetcoverage.cnn), these files were not input into the "reference" command. i.e. the somatic cnvs were called based on a flat reference of neutral copy number. Is there a way to configure the pipeline to use the coverage profile of the matched normal sample as the reference? Please see attached the cnvkit commands called.
[cnvkit_commands.txt](https://github.com/chapmanb/bcbio-nextgen/files/1621888/cnvkit_commands.txt)

**Comment by chapmanb** [comment]
Amanda -- thanks for this discussion and posting your log details. It looks like you're using an older version of bcbio by the commands and the path string (1.0.3?). If so, the most recent release (1.0.7) has a completely reworked CNVkit implementation which is much improved in terms of runtime and implementation. It should use a normal background for any tumor/normal samples present in the same batch, and can now use groupings of normals as the background within a project to provide additional resolution. Would updating and re-running work for your analysis?

**Comment by lbeltrame** [comment]
> and can now use groupings of normals as the background within a project to provide additional resolution.

Sorry for hijacking the issue, but is this documented somewhere? I'm about to start a project with such a setup and I'd like to use that.

**Comment by schelhorn** [comment]
That would be of interest to me as well; there seem now to be multiple options to include normals for `cnvkit`, it it would be great to learn how each is configured, and where to read up which to choose (in the `cnvkit` docs, for instance).

**Comment by chapmanb** [comment]
Luca, Sven-Eric and Amanda;
The pooling of normals within a project is the default in bcbio as of 1.0.6. It will pool all normals with the same BED regions (thus sample capture) in a project and use as the background. This is the recommended approach and was a big improvement over the old approach. There is a `prep_method` metadata (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#sample-information) option you can set if samples should be pooled separately but I expect this won't need to be used often.

So, the idea is to just do the right thing without any configuration/changes. Please let us know if you think it needs tweaking and happy to adjust.

**Comment by AmandaMilou** [comment]
Hi Brad, thanks for the update! Will use the newer release of bcbio for subsequent analyses.
