### ISSUE TITLE
checking from other user account

### ISSUE THREAD

**Issue by MurliNair** [chapmanb/bcbio-nextgen#2216]
Hi Brad,
I am testing bc-bio from other user (student) accounts. To be completely clear bc-bio is installed here
/work/local
 [mnair@genomics local]$ ls -lZ
drwxrwxr-x. mnair mnair unconfined_u:object_r:etc_runtime_t:s0 bin
drwxrwxr-x. mnair mnair unconfined_u:object_r:etc_runtime_t:s0 local_install
drwxrwxr-x. mnair mnair unconfined_u:object_r:etc_runtime_t:s0 share

I ran it from the user account using runuser as follows 

runuser -l mlaskie -c 'nohup /home/mlaskie/bcbio-nextgen/tests/run_tests.sh &'

The following is the output 
Thu Jan 11, 15:45:53 [root@genomics /home/mlaskie]# more nohup.out
============================= test session starts ==============================
platform linux2 -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /work/local/share/bcbio/anaconda/bin/python
cachedir: .cache
rootdir: /home/mlaskie, inifile:
plugins: mock-1.6.3, cov-2.5.1
collecting ... collected 80 items / 1 errors

==================================== ERRORS ====================================
________ ERROR collecting bcbio-nextgen/scripts/utils/test_resources.py ________
ImportError while importing test module '/home/mlaskie/bcbio-nextgen/scripts/utils/test_resources.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
bcbio-nextgen/scripts/utils/test_resources.py:9: in <module>
    from bcbio.distributed import clargs, resources, ipython as ip
bcbio-nextgen/bcbio/distributed/ipython.py:31: in <module>
    from cluster_helper import cluster as ipython_cluster
/work/local/share/bcbio/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py:62: in <module>
    from ipyparallel.apps.ipcontrollerapp import IPControllerApp
/work/local/share/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/apps/ipcontrollerapp.py:35: in <module>
    from zmq.devices import ProcessMonitoredQueue
/work/local/share/bcbio/anaconda/lib/python2.7/site-packages/zmq/devices/__init__.py:7: in <module>
    from zmq.devices import basedevice, proxydevice, monitoredqueue, monitoredqueuedevice
E   ImportError: libzmq.so.5.1.1: cannot open shared object file: No such file or directory
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
============================= 69 tests deselected ==============================
=================== 69 deselected, 1 error in 16.15 seconds ====================

Here is environment from the user account

Thu Jan 11, 15:48:08 [root@genomics /home/mlaskie]# runuser -l mlaskie -c '/home/mlaskie/$PATH'
-bash: /home/mlaskie//work/local/bin:/usr/local/cuda/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/mlaskie/.local/bin:/home/mlaskie/bin: No such file or directory

I am not sure where to begin. It runs fine from my account, also the /work/local has user-group as mnair, would that make a difference when another user is running it?

Thanks ../Murli

**Comment by MurliNair** [comment]
Hi Brad,
Was able to figure it out, so it runs fine now. I had to change the context to usr_t for /work/local , that enabled others users to use it.  I was a little rusty with contexts in SELinux. 
Thanks for all the help. 
Cheers../Murli

**Comment by chapmanb** [comment]
Murli;
Glad you got this figured out. I believe the original issue was due to distributing analyses on a cluster (and thus using IPython) where there was a recent incompatibility with zeromq libraries. If you keep hitting this issue you can fix with:
```
bcbio_conda install -c conda-forge zeromq=4.2.1
```
I'll also work on pinning this during the install to avoid the incompatibility. Thanks again.

**Comment by MurliNair** [comment]
Thanks Brad. I just submitted the cancer-normal job from a students account. Just to make sure everything works fine before I actually have them work on it. Greatly appreciate your help and time. 
Cheers../Murli

**Comment by MurliNair** [comment]
Hi Brad, 
The cancer-normal job was successful without any errors.  Do I still need to run the following 
bcbio_conda install -c conda-forge zeromq=4.2.1

Also, I had a question about the path that is set.  Currently it is set as follows
export PATH=/path_to_bcbio/bin:$PATH

Does it matter if I  append it as follows
export PATH=$PATH:/path_to_bcbio/bin

Cheers../Murli

**Comment by chapmanb** [comment]
Murli -- glad it is working for you. If the libraries are now clean on your install there is no need to adjust anything else. Regarding the PATH, the best advice is to use the bcbio PATH first when running bcbio. If you add it at the end other versions of tools used in bcbio that are in your PATH would take precedence and might not be in sync with what bcbio uses. If you're worried about this, you can only adjust your PATH when actually running bcbio, so add it as a line to the start of your scripts that kick off bcbio. Hope this helps.

**Comment by MurliNair** [comment]
Thanks Brad, greatly appreciate your help.
