### ISSUE TITLE
Speeding up GATK4 RNAseq variant calling by processing regions in parallel

### ISSUE THREAD

**Issue by WimSpee** [chapmanb/bcbio-nextgen#2229]
Hi, 

As far as I can tell bcbio currently does not attempt to run GATK4 for RNAseq variant calling in parallel.  I only see 1 CPU being used in `top` on the execution machine and the log also says that only 1 CPU is used per sample (there is only 1 sample in this analysis).  

```
[2018-01-19T21:56Z] Resource requests: gatk; memory: 3.50; cores: 1
[2018-01-19T21:56Z] Configuring 1 jobs to run, using 1 cores each with 3.50g of memory reserved for each job
[2018-01-19T21:56Z] Timing: RNA-seq variant calling
[2018-01-19T21:56Z] multiprocessing: run_rnaseq_variant_calling
[2018-01-19T21:56Z] De-duplication with biobambam
```

Would it be possible to run the GATK RNAseq variant calling parallel? Just like bcbio does for WGrS GATK4 variant calling by splitting on callable regions?

I can imagine it is more difficult to determine callable regions for RNAseq. Another option would be to run at least all chromosomes (and all samples) in parallel.
 
Thank you.

**Comment by schelhorn** [comment]
I think it may run in parallel if you are using the `CWL` mode, if that's implemented for RNA-Seq variant calling already (it will be at some point, of I'm not mistaken).

**Comment by WimSpee** [comment]
I can confirm that that samples are already running in parallel, in normal bcbio mode on a SGE cluster. 

 It just takes quite long for GATK to process each sample, like more than a day or even multiple days.   

So in cases where you only have a few samples, a lot of CPU are not used, and the analysis could be faster, when more regions could be done in parallel.

Also having these 2 day per sample RNAseq variant calling steps, (ie. transactions), makes a failure and restart quite costly. Since all these 2 day long transaction needs to be restarted. 

Running the analysis in parallel per chromosome should already provide a significant  speed up and decrease of the transaction time.

**Comment by chapmanb** [comment]
Thanks much for the discussion and report. This is also being discussed in #2189 for more information. What bcbio does, in standard non-CWL runs on a cluster, is distribute jobs by sample across a cluster, then each sample in the cluster should get a multicore allocation. In the latest development version these individual runs with use GATK 4.0 HaplotypeCallerSpark, which should parallelize over the available cores.

I hope updating and running in this manner provides a reasonable runtime for the short term. Longer term we wiill look to transition into regional variant calling like in standard DNA-seq analyses as part of the CWL migration.

Thanks again for the feedback and discussion.
