### ISSUE TITLE
vt incorrectly (?) decomposes variants, creates triploid or more sites

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2231]
This is a problem because afterwards `vcf2db` will choke on them with the error:

```python
  File "/opt/bcbio/anaconda/bin/vcf2db.py", line 232, in __init__
    self.load()
  File "/opt/bcbio/anaconda/bin/vcf2db.py", line 317, in load
    i = self._load(self.cache, create=True, start=1)
  File "/opt/bcbio/anaconda/bin/vcf2db.py", line 272, in _load
    arr = v.gt_bases if c == "gts" else getattr(v, c, None)
  File "cyvcf2/cyvcf2.pyx", line 985, in cyvcf2.cyvcf2.Variant.gt_bases.__get__
Exception: gt_bases not implemented for ploidy > 2
```

Example of GT record before decomposition (2 samples, 2 variants, both indels):

```
GT:AD:AF:DP:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB 0/1/2:91,6,3:0.086,0.057:100:91,6,3:0,0,0:32,36:215,1013,974:60,60:32,32:0.04,0.051,0.06:0.022,0.004304,0.974   0/0:138,0,0:0.022,0.02:138:65,0,0:73,0,0:0,0:211,0,0:0,0:0,0:.:.
```
Post decomposition and normalization this becomes (note the GT field):

```
GT:AD:AF:DP:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB  0|1|.:91,6:0.086:100:91,6:0,0:32:215,1013:60:32:0.04,0.051,0.06:0.022,0.004304,0.974       0|0:138,0:0.022:138:65,0:73,0:0:211,0:0:0:.:.

GT:AD:AF:DP:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB  0|.|1:91,3:0.057:100:91,3:0,0:36:215,974:60:32:0.04,0.051,0.06:0.022,0.004304,0.974        0|0:138,0:0.02:138:65,0:73,0:0:211,0:0:0:.:.
```

This gives me a ploidy of 3, which breaks everything down the road.

**Comment by chapmanb** [comment]
Luca;
Thanks for this report. Are you finding this problem with mutect2 calls? Unfortunately they are not compatible with gemini due to this representation. We have an open issue and discussion about fixing the representation (https://github.com/broadinstitute/gatk/issues/3564). This occurs prior to vt normalization, the original record has the `0/1/2` triploid call which triggers the issue. You could either disable GEMINI for your project or we could skip gemini database creation for MuTect2 to avoid the issue until it's fixed upstream.

**Comment by lbeltrame** [comment]
Given this can be a problem to *anyone* using MuTect 2, there are (IMO; feel free to criticize / improve) 3 possible scenarios out of this:

1. Leave the situation as is until the GATK is fixed. Pros: easier maintenance on the code (no changes). Cons: the same analysis done before and after the GATK 4.0 upgrade will not give the same result (one will fail), there's no ETA on getting a fix in the GATK
2. Skip GEMINI loading. Pros: easier code (little changes), will complete analysis even with MuTect 2. Cons: if anyone relies on GEMINI databases they're out of luck or they have to manually adjust the VCFs themselves
3. Save multiallelic records to another VCF, kept during the run, and remove them from the VCF fed into GEMINI. Pros: will also create the GEMINI database. Cons: violates the principle of least surprise (some loci may be missing), higher code complexity

I'd prefer 3, but I'm not the one maintaining this code. ;) Opinions?

**Comment by chapmanb** [comment]
Luca;
Thanks much for looking into this and presenting all the options. In the end I've decided to go with option 2 and skip the actual GEMINI database creation to avoid the issue. We do annotate files with vcfanno so you can use the VCFs directly, but this leaves us without a gemini database to output. Ultimately I don't want to leave out variants, which I think would be confusing and potentially lead to misinterpretation. Our best options to fix cleanly are to ping the Broad GATK team to support this or look for decomposition options which would denormalize these into multiple individual calls. Hopefully we can get the representation improved upstream and re-enable this soon. Thanks again for the discussion and work.
