### ISSUE TITLE
Custom reference: setup_genome fails to create ref-transcripts.gtf

### ISSUE THREAD

**Issue by ethanbahl** [chapmanb/bcbio-nextgen#2234]
Hi,

I'm having an issue with creating a custom reference using bcbio_setup_genomy.py. The fatal error is an IndexError when clean_gtf() is called from within prepare_tx_gff.py, specifically at: `if line.split()[0].strip() not in fa_names:` . I've read my gtf file into python and parsed through it with no errors. It's not the gtf file itself. Upon further inspection, I found that clean_gtf() is using the ref-transcripts.gtf that is placed in the organism/build/rnaseq/ directory. This ref-transcripts.gtf file is not being made properly. It is substantially smaller than the original gtf file and is an archive file.

The genome I'm building is mouse mm10 with a newer annotation (M14), downloaded from GENCODE. I'm going to try again using the the GFF3 file overnight.

Any recommendations for this?
Thanks in advance.

**Comment by chapmanb** [comment]
Ethan;
Sorry about the issue and thanks for the detailed report. It sounds like something is going wrong in processing your initial GFF file; the error reads that there is a blank line it is choking on. Would you be able to share a link to the GENCODE file you're working with -- it looks like there are a few different options here: https://www.gencodegenes.org/mouse_releases/14.html That could help us reproduce and figure out what is going wrong. Thanks much.

**Comment by roryk** [comment]
Hi Ethan,

There's a --gff3 option, do you have that turned on?

Ensembl's annotation is pretty current and includes GENCODE and will definitely work. See http://useast.ensembl.org/Mus_musculus/Info/Annotation and (ftp://ftp.ensembl.org/pub/release-91/gtf/mus_musculus). If you want to specifically use M14, it looks like it lines up with Ensembl release 89 (see https://www.gencodegenes.org/mouse_releases/). Current Ensembl is M16 though.

**Comment by ethanbahl** [comment]
When I used the gtf: 

`bcbio_setup_genome.py -f /ebahl/genomes/mm10_m14/GRCm38.p5.genome.fa.gz -g /ebahl/genomes/mm10_m14/gencode.vM14.annotation.gtf -i star -n Mmusculus -b mm10_m14` 

 the pipeline couldn't properly create the ref-transcripts.gtf file. It seems as though there was an interruption and ref-transcripts.gtf is a 25 MB binary file. However, when I tried the gff3 file, ref-transcripts.gtf is a 765.8 MB text file:

`bcbio_setup_genome.py -f /ebahl/genomes/mm10_m14/GRCm38.p5.genome.fa.gz --gff3 -g /ebahl/genomes/mm10_m14/gencode.vM14.annotation.gff3 -i star -n Mmusculus -b mm10_m14`

Using the gff3, I made it all the way to line 349 of the bcbio_setup_genome.py script.

```
Traceback (most recent call last):
  File "/bcbio-rna/bin/bcbio_setup_genome.py", line 349, in <module>
    loc.update_loc_file(galaxy_base, index, args.build, index_file)
  File "/bcbio-rna/anaconda/lib/python2.7/site-packages/bcbio/galaxy/loc.py", line 86, in update_loc_file
    with open(loc_file, "a") as out_handle:
IOError: [Errno 2] No such file or directory: '/bcbio-rna/galaxy/tool-data/sam_fa_indices.loc'
```
I believe the custom reference has now been generated properly, but .loc files aren't being updated.

Since I've gotten farther with the gff3 file I'd prefer to pursue a solution by going down that route as opposed to the gtf file. The files I am using are: [ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M14/gencode.vM14.annotation.gff3.gz](url) and [ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_mouse/release_M14/GRCm38.p5.genome.fa.gz](url)

Thanks to both of you for your timely assistance,
Ethan

**Comment by roryk** [comment]
Thanks, guh sorry for the delay in getting back to you. Are there no genomes installed at all? Does `/bcbio-rna/galaxy/tool-data/sam_fa_indices.loc` exist? Right now we are opening that file and appending to it which is why the gff3 option is failing at the end. If you do `bcbio_setup_genome.py` with no arguments, does it list the current genomes installed, or give an error?

**Comment by ethanbahl** [comment]
No worries, and I apologize for my delay as well. As it turns out, the `/bcbio-rna/galaxy/` directory was completely empty, although I didn't see any indication of a problem in the installation log files. I was able to copy over the contents of the galaxy directory from a previous installation and everything worked smoothly.

**Comment by roryk** [comment]
Awesome-- thanks for following up, glad that it worked out!
