### ISSUE TITLE
GATK workflow crashes on recalibration 

### ISSUE THREAD

**Issue by danchubb** [chapmanb/bcbio-nextgen#2236]
Hi,

I'm running the bcbio gatk pipeline , threaded on a 20 core node on three germline samples and it seems to be crashing at re-calibration.  I'm hoping it's an obvious problem but I can't figure it out.  Any chance I can get some help? I have attached the error log, it looks like the crash begins at ~ line 2937.

At the end it gives "Exception in thread "main" org.broadinstitute.hellbender.exceptions.UserException: '--java-options' is not a valid command." but I'm not sure if this is the cause or a symptom.

[bcbio-nextgen-debug.log](https://github.com/chapmanb/bcbio-nextgen/files/1660930/bcbio-nextgen-debug.log)

**Comment by chapmanb** [comment]
Sorry about the issue and thank you for the report. The GATK 4.0 release changed a number of command line parameters which made it incompatible with the 1.0.7 release. We're planning a new release soon with the fixes for this but in the meantime you can upgrade to the latest development version:
```
bcbio_nextgen.py upgrade -u development
```
or downgrade the GATK 4 you're using to the last beta release:
```
bcbio_conda install -c conda-forge -c bioconda 'gatk=4.0b6'
```
Hope this helps get it working for you.

**Comment by danchubb** [comment]
bcbio_nextgen.py upgrade -u development did the trick! Thanks a lot for the help.

Dan
