### ISSUE TITLE
fusion_mode and fusion_caller with Oncofuse

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#2244]
Currently it is possible to not set `fusion_mode` (which then equals `false`) but enable Oncofuse via `fusion_caller`. As a result, STAR is incorrectly configured for Oncofuse and no chimeric reads are generated; Oncofuse then exits since the chimeric read file isn't present (it seems to be only present if at least one chimeric read has been found). 

Perhaps bcbio could notify the user about this inconsistency, and also deal with the case of the chimeric output file not being there (which could also happen when STAR is correctly in `fusion_mode`, although it's unlikely to happen in practise)?

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for this report. I dug into this in the context of this debug thread on biovalidation (https://groups.google.com/d/msgid/biovalidation/72b8219b-471c-4811-8b81-0fd50d24c456%40googlegroups.com) and it looks like 1.0.7 and current development correctly handles the `fusion_caller` only case (https://github.com/chapmanb/bcbio-nextgen/commit/597eaf53b078d92716573bb4477864fd2a6a98ef) but things could still error out if not chimeric reads are found. I added a check for this (https://github.com/chapmanb/bcbio-nextgen/commit/174a15fc115abb1546421ae533a05ddf595c65dc) which I believe will resolve the issue. Please let us know if you find it skipping chimeric read detection and happy to dig further. Thanks again.

**Comment by schelhorn** [comment]
Excellent.
