### ISSUE TITLE
sqlalchemy.OperationalError: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by Wixaros** [chapmanb/bcbio-nextgen#2251]
Hi again

We managed to fix our previous problems, however a new one has appeared. It seems that some other people have tried to fix it #1123 however I'm not quite sure what to do. It looks like Gemini is causing the problem, however its running fine on its own outside our grid. However in the grid we get the following error:

`Traceback (most   recent call last):
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py",   line 23, in run
_do_run(cmd, checks, log_stdout, env=env)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py",   line 103, in _do_run
raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o   pipefail; export PATH=/usr/local/share/packages/bcbio/anaconda/bin:$PATH   &&    /usr/local/share/packages/bcbio/anaconda/bin/gemini  load    --passonly --skip-gene-tables --skip-gerp-bp  -v   /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/gemini/batch10-ensemble-nomultiallelic.vcf.gz   -t snpEff --cores 6 --tempdir   /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/bcbiotx/tmpwYQr9D   /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/bcbiotx/tmpwYQr9D/batch10-ensemble.db
CADD scores are being loaded (to skip   use:--skip-cadd).
sqlalchemy.OperationalError:   (sqlite3.OperationalError) database is locked [SQL: u'PRAGMA   table_info("variants")']
Traceback (most recent call last):
File "/usr/local/share/packages/bcbio/anaconda/bin/gemini",   line 7, in <module>
gemini_main.main()
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",   line 1248, in main
args.func(parser, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",   line 311, in loadchunk_fn
gemini_load_chunk.load(parser, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py",   line 910, in load
gemini_loader = GeminiLoader(args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py",   line 100, in __init__
self.vcf_reader = self._get_vcf_reader()
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py",   line 284, in _get_vcf_reader
return vcf.VCFReader(self.args.vcf)
File "cyvcf2/cyvcf2.pyx", line 187, in   cyvcf2.cyvcf2.VCF.__init__
IOError: /dev/stdin if not valid bcf or   vcf
sqlalchemy.OperationalError:   (sqlite3.OperationalError) database is locked [SQL: u'PRAGMA   table_info("variants")']
Traceback (most recent call last):
File "/usr/local/share/packages/bcbio/anaconda/bin/gemini",   line 7, in <module>
gemini_main.main()
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",   line 1248, in main
args.func(parser, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",   line 311, in loadchunk_fn
gemini_load_chunk.load(parser, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py",   line 910, in load
gemini_loader = GeminiLoader(args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py",   line 100, in __init__
self.vcf_reader = self._get_vcf_reader()
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py",   line 284, in _get_vcf_reader
return vcf.VCFReader(self.args.vcf)
File "cyvcf2/cyvcf2.pyx", line 187, in   cyvcf2.cyvcf2.VCF.__init__
IOError: /dev/stdin if not valid bcf or   vcf
Indexing   /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/gemini/batch10-ensemble-nomultiallelic.vcf.gz   with grabix.
Loading 2 variants.
Breaking   /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/gemini/batch10-ensemble-nomultiallelic.vcf.gz   into 2 chunks.
Loading chunk 0.
Loading chunk 1.
Traceback (most recent call last):
File "/usr/local/share/packages/bcbio/anaconda/bin/gemini",   line 7, in <module>
gemini_main.main()
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",   line 1248, in main
args.func(parser, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py",   line 204, in load_fn
gemini_load.load(parser, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py",   line 49, in load
load_multicore(args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py",   line 93, in load_multicore
chunks = load_chunks_multicore(grabix_file, args)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py",   line 264, in load_chunks_multicore
wait_until_finished(procs)
File   "/usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py",   line 359, in wait_until_finished
raise ValueError("Processing failed on GEMINI chunk load")
ValueError: Processing failed on GEMINI   chunk load
' returned non-zero exit status 1
`

I've attached the log files from the run and the yaml file, together with the script we use to queue the command to our servers

Best
Nicolai

[bcbio-nextgen.log](https://github.com/chapmanb/bcbio-nextgen/files/1694684/bcbio-nextgen.log)
[bcbio-nextgen-commands.log](https://github.com/chapmanb/bcbio-nextgen/files/1694685/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/chapmanb/bcbio-nextgen/files/1694686/bcbio-nextgen-debug.log)
[Tp53_targeted_sample10.sh.e12579.txt](https://github.com/chapmanb/bcbio-nextgen/files/1694691/Tp53_targeted_sample10.sh.e12579.txt)
[Tp53_targeted_sample10.sh.txt](https://github.com/chapmanb/bcbio-nextgen/files/1694692/Tp53_targeted_sample10.sh.txt)

**Comment by roryk** [comment]
Hi @Wixaros,

This might be a problem with sqlite over NFS. . https://github.com/chapmanb/bcbio-nextgen/issues/1123 has a description of the issue and a possible resolution. Let us know if that doesn't end up fixing the problem.

**Comment by Wixaros** [comment]
Hi again,

It seems that the nolock solution doesn't make a difference. I have located the error to the following command:
`export PATH=/usr/local/share/packages/bcbio/anaconda/bin:$PATH &&  /usr/local/share/packages/bcbio/anaconda/bin/gemini  load  --passonly --skip-gene-tables --skip-gerp-bp  -v /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/gemini/batch10-ensemble-nomultiallelic.vcf.gz -t snpEff --cores 6 --tempdir /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/bcbiotx/tmpwYQr9D /casa3/nobackup/med-nca/MaNiLa/GATC_MaNiLa_TP53_project/test4/work/bcbiotx/tmpwYQr9D/batch10-ensemble.db`

And the problem being that gemini doesn't seem to have privileges to write/create the tempdir requested, due to me not having access to the do so, when I qsub the script.
However, if I run it with my home directory as a target instead of our storage directory everything runs somewhat smoothly. The issue is that I only have around 30gb of space allocated in my home directory, which limits things a bit. However, can I set up that gemini uses my home directory for the intermediate files? I looked at the configuration page under resources but does the tmp: dir command then apply to all instances run?

Best

Nicolai

**Comment by chapmanb** [comment]
Nicolai;
Thanks for digging into this and identifying the underlying issue. You can set the temporary directory bcbio uses to something where you have access and enough disk space exactly as you say with the tmp directory:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#temporary-directory

It will apply to any temporary directories used during the run. We don't have anything specifically for specific steps of the pipeline since that would be a bit of a configuration mess. Hopefully this will work for what you need.

**Comment by Wixaros** [comment]
Hi again

This resolved the issue however a new one arose with multiqc. Will open a new ticket about that.
