### ISSUE TITLE
Background for CNVkit is calculated regardless if the normal has CNVkit enabled

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2255]
cc @LMannarino

Long and winding title to explain a specific issue. Suppose we have two normal samples as part of a structural variant run, "foo" and "bar". "foo" has `svcallers: cnvkit` in its configuration, bar has not. 

When the pipeline runs, it will try to extract the background bins from **both** samples, and it will fail in `cnvkit_background` (`bcbio/structural/cnvkit.py`), because the `backgound_cnns` in `cnvkit_background` will contain `None` for the target and antitarget of the sample without the explicit CNVkit configuration. 

IOW, we'll end up with something like (paths omitted for clarity).

```python
['foo-target-coverage.cnn', 'foo-antitarget-coverage.cnn', None, None]
```

`_prep_cmd`, called later, will fail because it will try to join strings and `None`.

I see two ways to get out of this:

1. Run the background *regardless* of what is specified in the configuration for all normals
2. Error out in case not all normals are analyzed.

**Comment by chapmanb** [comment]
Luca;
Thanks much for the problem report and sorry about the issue. I pushed a fix to the latest development version that avoids this issue by specifically leaving out non-CNVkit samples in a project from the calling and background. Please let us know if you run into any other issues and thanks again.
