### ISSUE TITLE
multiQC failure in run due to decorator version

### ISSUE THREAD

**Issue by Wixaros** [chapmanb/bcbio-nextgen#2263]
I've almost completed an entire run with the newest developmental build, however we've encountered a problem with multiqc and a call on decorator which seems to be of wrong version. How do we upgrade to the lastest version of decorator in BCBIO? Attached is the output of the run, with the error and the most recent command it tried to run below

`export PATH=/usr/local/share/packages/bcbio/anaconda/bin:$PATH &&  /usr/local/share/packages/bcbio/anaconda/bin/multiqc -f -l /home/med-nca/BCBIO/test4/work/qc/multiqc/list_files.txt  -o /home/med-nca/BCBIO/test4/work/bcbiotx/tmp_T0kz3`

[Tp53_targeted_sample10.sh.e21913.txt](https://github.com/chapmanb/bcbio-nextgen/files/1716405/Tp53_targeted_sample10.sh.e21913.txt)

Furthermore our IT guy attempted to manually install decorator, however this failed, so now there is no decorator present, and the `bcbio_nextgen.py upgrade -u development --tools --data` does not install decorator

**Comment by naumenko-sa** [comment]
Hi!

Try 
```conda update decorator```

SN

**Comment by Wixaros** [comment]
Hi, sadly this does not work.
It comes up with an error that decorator was not found, probably due to our tech guy trying to install it manually. The `bcbio_nextgen.py upgrade -u development --tools --data` command does not install a working copy of decorator, and now we have something lying in /usr/local/share/packages/bcbio/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources that looks like this:

drwxrwxr-x  5 1000 1000     4096 Feb 12 14:30 decorator-4.2.1
-rw-rw-r--  2 root root    16568 Feb 12 14:11 decorator.py

and nothing more. Seems like we have broken the BCbio install as everything has now crashed.

[Tp53_targeted_sample10.sh.e21936.txt](https://github.com/chapmanb/bcbio-nextgen/files/1719373/Tp53_targeted_sample10.sh.e21936.txt)

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for all the work debugging this so far. Apologies, the dependency resolution looks to have broken down on your upgrade and you do need to manually upgrade decorator. The right command to run is:
```
bcbio_conda install -c conda-forge decorator
```
which should give you an up to date version matching the requirements. Please let us know if you run into any other issues and happy to reopen and explore more.

**Comment by Wixaros** [comment]
Thank you! We managed to get it through, however, now we're having the same error as #2261. It seems though that a fix is being pushed. Thank you so much for all the help!

**Comment by chapmanb** [comment]
Glad that fixed it and sorry about the additional problem. That is also fixed now with details about avoiding the problem here: https://github.com/chapmanb/bcbio-nextgen/issues/2261#issuecomment-365292924 Thanks again for all the reports and working through the issues.
