### ISSUE TITLE
Qualimap error message: BAM file is empty or no read alignments are located in exonic regions.

### ISSUE THREAD

**Issue by prxrsp** [chapmanb/bcbio-nextgen#2266]
Hello, 

I have used STAR to align paired-end reads from this sample and the output looks good when I view with samtools. However, I get this error message when I try to run Qualimap:

`Failed to run rnaseq
java.lang.RuntimeException: BAM file is empty or no read alignments are located in exonic regions.
	at org.bioinfo.ngs.qc.qualimap.process.ComputeCountsTask.run(ComputeCountsTask.java:559)
	at org.bioinfo.ngs.qc.qualimap.process.RNASeqQCAnalysis.run(RNASeqQCAnalysis.java:68)
	at org.bioinfo.ngs.qc.qualimap.main.RnaSeqQcTool.execute(RnaSeqQcTool.java:188)
	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:190)
	at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:111)`

Thanks for your help!

**Comment by roryk** [comment]
Thanks @prxrsp, sorry for the problem. It sounds like something is up with your BAM file, is it empty?

**Comment by prxrsp** [comment]
Hi @roryk, 

No, it has a decent size and I have viewed it with samtools. It looks just fine.

**Comment by roryk** [comment]
Thanks, what genome is this on? Does this issue apply to you at all? https://github.com/chapmanb/bcbio-nextgen/issues/2203

**Comment by prxrsp** [comment]
I don't think so, as I have a proper BAM file and am running everything on O2. I use hg19.

**Comment by roryk** [comment]
Oh nice, you are on O2. Thanks, could you email me the directory you are running everything in so I can take a look?

**Comment by roryk** [comment]
Looks like this isn't bcbio related, so closing it here. Thanks!

**Comment by rgranit** [comment]
I have a similar issue, same error on bam file that is not empty.. any suggestion?

**Comment by roryk** [comment]
Hi Roy,

Is this from running bcbio, or are you running qualimap by yourself?

**Comment by rgranit** [comment]
Hi @roryk this happens when running Qualimap by myself on STAR aligner output.

**Comment by roryk** [comment]
Hiya!

Sorry, this repo is for bcbio; we use qualimap but aren't the authors. The qualimap Google groups is probably a better place to ask questions about it: https://groups.google.com/forum/#!forum/qualimap

My guess is, though, if you are seeing "Failed to run rnaseq java.lang.RuntimeException: BAM file is empty or no read alignments are located in exonic regions." on a BAM file that actually has alignments, is that the BAM file you are using has chromosomes named differently than the GTF file you are giving qualimap, so qualimap isn't finding any exons.

Qualimap also needs a specific GTF format which has `gene_id` and `transcript_id` in each entry, along with some other specifics. So your GTF file may not conform to the specifications. The qualimap mailing list would be a good place to get more help though. Hope that helps!

**Comment by rgranit** [comment]
Thanks so much for your reply! I will checkout the group and mailing list.
