### ISSUE TITLE
Mosdepth coverage flags

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#2272]
Hi Brad,

I was looking into the coverage calculations by mosdepth. How would you feel about adding a `tools_on` flag to enable mosdepth's `per-base` output? This would be of great help for us if this was included into the raw qc metrics in de `final` dir. We use the `per-base` output in some downstream analyses, and in the current case we have to rerun mosdepth to get the `per-base`.

Thanks!
M

**Comment by matthdsm** [comment]
I know this implicates a performance hit, but those losses are recuperated by not having to do another mosdepth run. (in our case anyway)

**Comment by chapmanb** [comment]
Matthias -- thanks for the suggestion. The latest development has a`tools_on: [coverage_perbase]`  option which enables this, and will upload the per-base file to the final directory. Let us know if this doesn't provide what you're looking for and thanks again for the feedback and ideas.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks a lot! This will shave a couple of hours of our runtime.

Cheers!
M
