### ISSUE TITLE
GATK (3) version queried repeatedly

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2282]
I've noticed by chance that when the pipeline is in the "testing minimum version of installed programs", there are repeated calls to the GATK version (this is at least with `tools_off: [gatk4]`, each time with slightly different parameters, e.g.:

```
/opt/bcbio/anaconda/bin/java -Xms512m -Xmx1g -jar /opt/bcbio/anaconda/opt/gatk-3.8/GenomeAnalysisTK.jar --version
/opt/bcbio/anaconda/bin/java -Xms128m -Xmx256m -XX:+UseSerialGC -jar /opt/bcbio/anaconda/opt/gatk-3.8/GenomeAnalysisTK.jar -version
```

Should this be consolidated (given that the answer is always the same, unless something else is being tested)?

**Comment by lbeltrame** [comment]
The reason lies in https://github.com/chapmanb/bcbio-nextgen/blob/38301f71f35f64725184a5c6306ca828e2191442/bcbio/provenance/versioncheck.py#L57:

`_needs_java` is queried for every item in the list, which means that a new process is spawned. In my case, where I have 70+ items, this means that this dance can take up to 15 minutes.

**Comment by chapmanb** [comment]
Luca;
Thanks for identifying this issue and the underlying problem. At ths point I think we're safe skipping this sanity check as we're causing a lot of extra work for a rare case that users will probably already have their systems setup for. I pushed a fix to do this which hopefully resolves the extreme delay for you:

https://github.com/chapmanb/bcbio-nextgen/commit/715e2eab3f074cea2d974ebf662db6b093e1f0ac

Please let us know if you run into any other issues.
