### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by jpmtavares** [chapmanb/bcbio-nextgen#2284]
Hello,
I am trying to install bcbio and got this error during the installation of conda packages.

`$ wget https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py`

--2018-02-23 13:28:10--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.16.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.16.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12299 (12K) [text/plain]
Saving to: 'bcbio_nextgen_install.py'

100%[======================================>] 12,299      --.-K/s   in 0s      

2018-02-23 13:28:11 (43.7 MB/s) - 'bcbio_nextgen_install.py' saved [12299/12299]

`$ python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa --isolate --u stable --distribution ubuntu`

Checking required dependencies
Installing isolated base python installation
--2018-02-23 13:29:11--  https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.19.10, 104.16.18.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 39893266 (38M) [application/x-sh]
Saving to: 'Miniconda2-latest-Linux-x86_64.sh'

     0K ........ ........ ........ ........ ........ ........  7% 60.9M 1s
  3072K ........ ........ ........ ........ ........ ........ 15% 99.7M 0s
  6144K ........ ........ ........ ........ ........ ........ 23% 90.6M 0s
  9216K ........ ........ ........ ........ ........ ........ 31%  133M 0s
 12288K ........ ........ ........ ........ ........ ........ 39%  101M 0s
 15360K ........ ........ ........ ........ ........ ........ 47% 96.3M 0s
 18432K ........ ........ ........ ........ ........ ........ 55%  123M 0s
 21504K ........ ........ ........ ........ ........ ........ 63%  119M 0s
 24576K ........ ........ ........ ........ ........ ........ 70%  115M 0s
 27648K ........ ........ ........ ........ ........ ........ 78%  125M 0s
 30720K ........ ........ ........ ........ ........ ........ 86%  110M 0s
 33792K ........ ........ ........ ........ ........ ........ 94%  101M 0s
 36864K ........ ........ ........ ........                  100%  125M=0.4s

2018-02-23 13:29:12 (103 MB/s) - 'Miniconda2-latest-Linux-x86_64.sh' saved [39893266/39893266]

PREFIX=/usr/local/share/bcbio/anaconda
installing: python-2.7.14-h1571d57_29 ...
Python 2.7.14 :: Anaconda, Inc.
installing: ca-certificates-2017.08.26-h1d4fec5_0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-h7cc24e2_2 ...
installing: libstdcxx-ng-7.2.0-h7a57d05_2 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.0-h9df7e31_2 ...
installing: openssl-1.0.2n-hb7f436b_0 ...
installing: tk-8.6.7-hc745277_3 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1-heed3624_0 ...
installing: readline-7.0-ha6073c6_4 ...
installing: sqlite-3.22.0-h1bed415_0 ...
installing: asn1crypto-0.24.0-py27_0 ...
installing: certifi-2018.1.18-py27_0 ...
installing: chardet-3.0.4-py27hfa10054_1 ...
installing: enum34-1.1.6-py27h99a27e9_1 ...
installing: futures-3.2.0-py27h7b459c0_0 ...
installing: idna-2.6-py27h5722d68_1 ...
installing: ipaddress-1.0.19-py27_0 ...
installing: pycosat-0.6.3-py27ha4109ae_0 ...
installing: pycparser-2.18-py27hefa08c5_1 ...
installing: pysocks-1.6.7-py27he2db6d2_1 ...
installing: ruamel_yaml-0.15.35-py27h14c3975_1 ...
installing: six-1.11.0-py27h5f960f1_1 ...
installing: cffi-1.11.4-py27h9745a5d_0 ...
installing: setuptools-38.4.0-py27_0 ...
installing: cryptography-2.1.4-py27h6697b16_0 ...
installing: wheel-0.30.0-py27h2bc6bb2_1 ...
installing: pip-9.0.1-py27ha730c48_4 ...
installing: pyopenssl-17.5.0-py27hcee3be0_0 ...
installing: urllib3-1.22-py27ha55213b_0 ...
installing: requests-2.18.4-py27hc5b0589_1 ...
installing: conda-4.4.10-py27_0 ...
installation finished.
Installing bcbio-nextgen
--2018-02-23 13:29:20--  https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements-conda.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.16.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.16.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20 [text/plain]
Saving to: 'requirements-conda.txt'

100%[======================================>] 20          --.-K/s   in 0s      

2018-02-23 13:29:20 (4.53 MB/s) - 'requirements-conda.txt' saved [20/20]

Solving environment: ...working... **Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 257, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda, args)
  File "bcbio_nextgen_install.py", line 78, in install_conda_pkgs
    "--file", os.path.basename(REMOTES["requirements"])])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/conda', 'install', '--quiet', '--yes', '-c', 'bioconda', '-c', 'conda-forge', '--file', 'requirements-conda.txt']' returned non-zero exit status -9**

Am I missing something?
Thanks for the help!

**Comment by roryk** [comment]
Heya, could this be an intermittent issue? If you try again, does it give the same error? If it gives the same error again, could you run:

```
/usr/local/share/bcbio/anaconda/bin/conda install --yes -c bioconda -c conda-forge --file requirements-conda.txt
```
and see if it gives a more informative error? Thanks!

**Comment by jpmtavares** [comment]
Thanks for the reply! I have tried a couple of times, always with the same error.

`$ /usr/local/share/bcbio/anaconda/bin/conda install --yes -c bioconda -c conda-forge --file `tmpbcbio-install/requirements-conda.txt`
 
Solving environment: - Killed

**Comment by roryk** [comment]
Do you happen to be running this on a head node of a cluster?

**Comment by jpmtavares** [comment]
I was trying to do the installation in a VM with a very small amount of RAM... The installation is now working! Sorry for the trouble, and thanks again.

**Comment by roryk** [comment]
Ah! That makes sense. No worries, glad it is working now. :)
