### ISSUE TITLE
Huge computational burden of BaseRecalibratorSpark and ApplyBQSRSpark

### ISSUE THREAD

**Issue by sangtaekim** [chapmanb/bcbio-nextgen#2285]
I have been running GATK4 and Mutect2 through bcbio-nextgen for >30x WGS data, and noticed that BaseRecalibratorSpark (and possible ApplyBQSRSpark) consumes lots of memory (almost all the available 122 G in AWS r4.4xlarge when #cores = 16). Also, it is very slow, eating up more time than HaplotypeCaller or Mutect2. Is it expected?

**Comment by chapmanb** [comment]
Sangtae;
Apologies about the issue. There is a known regression in the current GATK4 release that we're working on identifying and resolving:

https://github.com/chapmanb/bcbio-nextgen/issues/2252#issuecomment-366614435

In the short term, I'd suggest turning off `recalibrate` for your samples as it's typically not needed and hopefully it's be resolved with the next GATK4 release.
