### ISSUE TITLE
bcbio runtime error

### ISSUE THREAD

**Issue by alongalor** [chapmanb/bcbio-nextgen#2287]
Hello!

I am using bcbio and have encountered an issue I would greatly appreciate any help with!

I executed the following command as a slurm job:

/n/data1/hms/dbmi/park/alon/software/bcbio/bin/bcbio_nextgen.py /n/data1/hms/dbmi/park/DATA/BSMCommonExperiment/ReferenceTissueProject/.Pipeline/PreProcessing/PreProcessing/config/PreProcessing.yaml -t ipython -n 256 -s slurm -q medium

After ~16hrs the job failed.

I am attaching the .log files as well as the .err files.

Thanks so much,

Alon
[bcbio-nextgen-commands.log](https://github.com/chapmanb/bcbio-nextgen/files/1757181/bcbio-nextgen-commands.log)
[bcbio-nextgen-debug.log](https://github.com/chapmanb/bcbio-nextgen/files/1757182/bcbio-nextgen-debug.log)
[bcbio-nextgen.log](https://github.com/chapmanb/bcbio-nextgen/files/1757183/bcbio-nextgen.log)
[bcbio-ipcontroller.err.10051212_4294967294.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757184/bcbio-ipcontroller.err.10051212_4294967294.txt)
[bcbio-ipengine.err.10051233_1.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757188/bcbio-ipengine.err.10051233_1.txt)
[bcbio-ipengine.err.10051233_2.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757189/bcbio-ipengine.err.10051233_2.txt)
[bcbio-ipengine.err.10051233_3.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757190/bcbio-ipengine.err.10051233_3.txt)
[bcbio-ipengine.err.10051233_4.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757191/bcbio-ipengine.err.10051233_4.txt)
[bcbio-ipengine.err.10051233_5.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757192/bcbio-ipengine.err.10051233_5.txt)
[bcbio-ipengine.err.10051233_6.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757193/bcbio-ipengine.err.10051233_6.txt)
[bcbio-ipengine.err.10051233_7.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757194/bcbio-ipengine.err.10051233_7.txt)
[bcbio-ipengine.err.10051233_8.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757195/bcbio-ipengine.err.10051233_8.txt)
[bcbio-ipengine.err.10051233_9.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757196/bcbio-ipengine.err.10051233_9.txt)
[bcbio-ipengine.err.10051233_10.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757197/bcbio-ipengine.err.10051233_10.txt)
[bcbio-ipengine.err.10051233_11.txt](https://github.com/chapmanb/bcbio-nextgen/files/1757198/bcbio-ipengine.err.10051233_11.txt)

**Comment by matthdsm** [comment]
Hi,

Is it possible your job timed out on the queue? Did you set a long enough walltime for initial slurm job?
Seeing there aren't really any errors in your debug log, I'm guessing that might be it.

Alternatively, could you also post the job outputs (stdout/stderr) from slurm? Those might contain more clues.

Cheers
M

**Comment by roryk** [comment]
+1 on it being timed out, it looks like the job was cancelled-- it could be because the job timed out, or it was manually cancelled.

**Comment by roryk** [comment]
I just checked and the default time is set to 24 hours for the medium queue, so I'm guessing that is what happened.

**Comment by alongalor** [comment]
Ah! That makes a lot of sense. Thanks a ton Rory! Just added these parameters to my command and re-ran. No need to delete the files in work right? Will the pipeline will restart from where it failed? Thanks again,
Alon

**Comment by roryk** [comment]
Hi Alon,

Yup, bcbio does the output for every command transactionally, so it only moves the file to its correct place for each step if that step completes properly. So you should be able to restart and it will pick off at the last step it finished and skip ones where the expected file is already there.

**Comment by alongalor** [comment]
amazing. thanks a ton rory!

**Comment by roryk** [comment]
Sweet, let us know if you run into any other issues.
