### ISSUE TITLE
star.py allign cmd += " > {tx_final_out} "

### ISSUE THREAD

**Issue by apastore** [chapmanb/bcbio-nextgen#2289]
Hi @roryk, I have a question on the star.py

on line 90 of the star.py  I am not sure if this is correct       
        cmd += " > {tx_final_out} "

if I remove it star run without problem, otherwise I get a gzip core dump.

Thanks!

**Comment by roryk** [comment]
Hi @apastore,

Hm-- it should be working fine, we use STAR almost every day at the core, so I think something else might be the problem. Do you have any more information to share? Thanks!

**Comment by apastore** [comment]
Sorry I was on the run. I will try.. strangely it work after I comment the line. 
(just seen that other aligner do not have that line). 
I have a new installation of bcbio on a new cluster, and there I see this problem, in the old one it work just fine.
