### ISSUE TITLE
Update gemini, cadd and gnomad

### ISSUE THREAD

**Issue by jich-MCTP** [chapmanb/bcbio-nextgen#2301]
Hi , 

Yesterday when I update gemini, cadd and gnomad, I got the same messages on screen. 
The command lines: 
bcbio_nextgen.py upgrade --data  --genomes GRCh37 --datatarget gemini

bcbio_nextgen.py upgrade --data  --genomes GRCh37 --datatarget cadd

bcbio_nextgen.py upgrade --data  --genomes GRCh37 --datatarget gnomad

No matter datatarget is gemini or cadd, gnomad, I always get:

Upgrading bcbio
Upgrading bcbio-nextgen data files
--2018-03-02 16:05:21--  https://github.com/chapmanb/cloudbiolinux/archive/master.tar.gz
Resolving github.com... 192.30.253.112, 192.30.253.113
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master [following]
--2018-03-02 16:05:21--  https://codeload.github.com/chapmanb/cloudbiolinux/tar.gz/master
Resolving codeload.github.com... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5167560 (4.9M) [application/x-gzip]
Saving to: 'STDOUT'

     0K ........ ........ ........ ........ ........ ........ 60% 9.10M 0s
  3072K ........ ........ ........ ......                    100% 30.9M=0.4s

2018-03-02 16:05:22 (12.6 MB/s) - written to stdout [5167560/5167560]

Setting up virtual machine
INFO: <cloudbio.flavor.Flavor instance at 0x7f059a858680>
INFO: This is a ngs_pipeline_minimal flavor
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /usr/local/share/bcbio-nextgen/anaconda/bin/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
INFO: Distribution __auto__
INFO: Get local environment
[localhost] local: cat /etc/*release | grep DISTRIB_CODENAME | cut -f 2 -d =
INFO: Ubuntu setup
DBG [distribution.py]: Debian-shared setup
DBG [distribution.py]: Source=xenial
DBG [distribution.py]: NixPkgs: Ignored
[localhost] local: echo $HOME
[localhost] local: uname -m
INFO: Now, testing connection to host...
INFO: Connection to host appears to work!
DBG [utils.py]: Expand paths
INFO: List of genomes to get (from the config file at '{'install_liftover': False, 'genome_indexes': ['bwa', 'rtg', 'twobit'], 'genomes': [{'name': 'Human (GRCh37)', 'validation': ['giab-NA12878', 'giab-NA24385', 'giab-NA24631', 'dream-syn3', 'dream-syn4', 'giab-NA12878-NA24385-somatic'], 'annotations': ['gnomad', 'GA4GH_problem_regions', 'capture_regions', 'MIG', 'prioritize', 'dbsnp', 'hapmap', '1000g_omni_snps', 'ACMG56_genes', '1000g_snps', 'mills_indels', 'clinvar', 'cosmic', 'ancestral', 'qsignature', 'genesplicer', 'effects_transcripts', 'vcfanno', 'viral', 'transcripts', 'RADAR', 'mirbase'], 'dbkey': 'GRCh37', 'indexes': ['seq', 'twobit']}], 'install_uniref': False}'): Human (GRCh37)

* downloading https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/dbsnp.b147.20160601.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/dbsnp.b147.20160601.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/clinvar_20170130.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/clinvar_20170130.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/29way_pi_lods_elements_12mers.chr_specific.fdr_0.1_with_scores.txt.hg19.merged.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/29way_pi_lods_elements_12mers.chr_specific.fdr_0.1_with_scores.txt.hg19.merged.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.CpG.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.CpG.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.pfam.ucscgenes.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.pfam.ucscgenes.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.gerp.elements.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.gerp.elements.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.cytoband.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.cytoband.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.dgv.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.dgv.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.gwas.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.gwas.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.rmsk.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.rmsk.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.segdup.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.segdup.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/ESP6500SI.all.snps_indels.tidy.v2.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/ESP6500SI.all.snps_indels.tidy.v2.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/genetic_map_HapMapII_GRCh37.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/genetic_map_HapMapII_GRCh37.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/stam.125cells.dnaseI.hg19.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data                                                                                        [0/26128]

* downloading https://s3.amazonaws.com/gemini-annotations/GRCh37-gms-mappability.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/GRCh37-gms-mappability.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/GRC_patch_regions.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/GRC_patch_regions.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/kegg_pathways_ensembl66 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/kegg_pathways_ensembl67 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/kegg_pathways_ensembl68 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/kegg_pathways_ensembl69 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/kegg_pathways_ensembl70 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/kegg_pathways_ensembl71 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hprd_interaction_edges.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/cse-hiseq-8_4-2013-02-20.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/cse-hiseq-8_4-2013-02-20.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.vista.enhancers.20131108.bed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/hg19.vista.enhancers.20131108.bed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/cosmic-v68-GRCh37.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/cosmic-v68-GRCh37.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/detailed_gene_table_v75 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/summary_gene_table_v75 to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/cancer_gene_census.20140120.tsv to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/gnomad.exomes.r2.0.1.sites.no-VEP.nohist.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/gnomad.exomes.r2.0.1.sites.no-VEP.nohist.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/geno2mp.variants.tidy.vcf.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/geno2mp.variants.tidy.vcf.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/whole_genome_SNVs.tsv.compressed.gz to /usr/local/share/bcbio-nextgen/gemini_data

* downloading https://s3.amazonaws.com/gemini-annotations/whole_genome_SNVs.tsv.compressed.gz.tbi to /usr/local/share/bcbio-nextgen/gemini_data

Gemini data files updated
bcbio-nextgen data upgrade complete.
Upgrade completed successfully.

I think this is not right.

**Comment by chapmanb** [comment]
Thanks for the report and sorry for any confusion. A `--data` upgrade updates any existing data files that are configured in your installation and have been specified previously. So `--datatarget` only potentially adds to new data, it doesn't define a specific set of data to update. So I believe you're just seeing the full upgrade run and this was unexpected? Does that help explain your concern? If you have other practical run issues happy to help debug.

**Comment by jich-MCTP** [comment]
Thanks! I close this issue.
