### ISSUE TITLE
Update CNVkit to 0.9.2

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#2308]
```
cnvkit.py version
0.9.2.dev0
```

I'm not sure at which hash it is currently in bcbio, but an update to the latest release may be in order, in particular because it fixes a problem with mis-identification of BED files (see https://github.com/etal/cnvkit/issues/315).

**Comment by chapmanb** [comment]
Luca -- thanks for the heads up. This is now upgraded and will be included in a `--tools` update. Please let us know if you run into any issues.

**Comment by etal** [comment]
I released the bugfix for `segmetrics` as 0.9.3 just now.

**Comment by chapmanb** [comment]
Eric -- thanks so much for the heads up and the new release. I bumped the bioconda package to 0.9.3 to include your fix.
