### ISSUE TITLE
Dealing with overlapping paired reads

### ISSUE THREAD

**Issue by caddymob** [chapmanb/bcbio-nextgen#296]
Greetings! I was just discussing the issue of overlapping paired reads... If a library has long reads (hello MiSeq!) and/or short inserts, coverage across bases with overlapping pairs are effectively duplicated.  If given mutation has predominantly overlapping reads the counts could be wrong and skew zygosity, or at least give the variant higher quality of the call as its coverage is erroneously inflated. 

There are some tools out there we found to do this kind of thing, wanted to get the community's thoughts on this and any best-practices we might implement.

FLASH: http://ccb.jhu.edu/software/FLASH/
CLIPOVERLAP:  http://genome.sph.umich.edu/wiki/BamUtil:_clipOverlap
PandaSeq (RNA): http://neufeldserver.uwaterloo.ca/~apmasell/pandaseq_man1.html
SeqPrep: https://github.com/jstjohn/SeqPrep 
Some data and methods with SeqPrep: https://banana-slug.soe.ucsc.edu/bioinformatic_tools:bwa#determining_paired-end_insert_size
PEAR: http://www.exelixis-lab.org/pear

GATK HaplotypeCaller looks like it kinda-sorta handles this, but GATK isn't for everyone. STAR handles it correctly if I understand it right, but that's again RNAseq - while awesome, I'm talking more on the DNA side for variant calling. 

Thanks!!

**Comment by roryk** [comment]
Thanks @caddymob, I've used PEAR to handle this before and it seems to work pretty well.

Sad to close this issue out. RIP man.

**Comment by gabeng** [comment]
Hi @roryk, sorry to disturb the peace, but this questions is somewhat undead to me. 
* GATK4 has a procedure to handle overlapping PE reads. 
* Freebayes simply treats them as independent reads. 
* I do not know about vardict. The variant calling landscape seems quite diverse.


I do not know of any evidence that read clipping would provide a gain in variant calling performance. In fact, I get a funny feeling when people talk about removing data to improve results. Still, there are so many people out there (mostly from NGS consumables manufacturers) who advise to clip reads. It seems like cargo cult to me. 
I noticed that bcbio does not support PEAR or any other feature to remove or trim overlapping PE reads, so I guess that you came to the conclusion that it does not improve performance. Is that correct? Could you share some of your experience?

**Comment by gabeng** [comment]
Hi Rory,

yeah, that was me. I am still chewing on that issue from time to time. Mostly because I receive some absurd questions regarding read trimming. I appreciate your comments and I totally agree with you: people focus on the wrong metrics. If I get my hands on some suitable valiadation data, I will give it a try.
