### ISSUE TITLE
RFC: Revisit ensemble calling for paired tumor analyses

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#361]
Rationale for this issue: a few days ago the wet lab people were validating some of the mutations I had found, and while they correctly validated them, it turned out they weren't somatic, but germline. 

The reason is that when I evaluated them after the pipeline, there were some loci in common between the callers I used (MuTect and VarScan), _however_  MuTect (more stringent than VarScan) had rejected them (non-somatic variants). As I only evaluated the passing mutations (and since gemini uses --passonly), I completely skipped over that issue. 

Ensemble calling would be a nice alternative to prevent these kinds of issues.  Perhaps there is no need for enhancements, but at least some rough documentation on how to proceed.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
