### ISSUE TITLE
cosmic v67

### ISSUE THREAD

**Issue by tanglingfung** [chapmanb/bcbio-nextgen#365]
there are many known driver mutations missing in the current download of cosmic v67 (including BRAF.pV600E). cosmic coding mutation v68 is available at ftp://ngs.sanger.ac.uk/production/cosmic/CosmicCodingMuts_v68.vcf.gz

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
