### ISSUE TITLE
Add some tests to exercise pipeline creation

### ISSUE THREAD

**Issue by hammer** [chapmanb/bcbio-nextgen#375]
I've been writing some unit tests to better understand how pipelines are configured. I'll push the tests up to a branch in my fork and create a PR for them.

**Comment by roryk** [comment]
Thanks, we ended up dropping the unit tests entirely and focus on integration tests. Common wisdom said that is a terrible thing to do, but we weren't running them. Thanks for the p/r if we end up deciding that is a super bad plan we'll revisit it.
