### ISSUE TITLE
canfam3 dbSNP - ensembl 75

### ISSUE THREAD

**Issue by caddymob** [chapmanb/bcbio-nextgen#386]
greetings! Can we add the canine dbSNP vcf to the variation resources in 9dcb447, please? I realize recallibration will not be available but getting rsIDs sure would be nice :)

The vcf can be obtained here: ftp://ftp.ensembl.org/pub/release-75/variation/vcf/canis_familiaris/Canis_familiaris.vcf.gz

Only thing is the canine genome for bcbio has "chr" prefixes on contigs where the dbSNP does not... I seem to recal you have a ensembl <--> ucsc conversion method from when we added the rn5 genome, so hoping this is easy without just awk'in on a 'chr' :)

Thanks!

**Comment by roryk** [comment]
Looks like this was continued on and fixed in #445, so closing.
