### ISSUE TITLE
RNA-seq variant calling best practices

### ISSUE THREAD

**Issue by mjafin** [chapmanb/bcbio-nextgen#389]
Hi All,
Collecting some information and opinions around RNA-seq variant calling here. The Broad institute have released best practices for germline variant calling in RNA-seq, http://gatkforums.broadinstitute.org/discussion/3891/best-practices-for-variant-calling-on-rnaseq. 

What they're essentially doing is using a new restricted walker, ```SplitNCigarReads```, to split splice junction reads (```N``` in CIGAR) into multiple reads, as most variant callers (Gatk, FreeBayes too) seem to choke on N-reads. Further, they're doing some trimming of intronic tails, saying they're resulting from poor alignments, but in my opinion they could also be pre-mRNAs. Furthermore in variant calling they're generally lowering the quality thresholds. 

I took a look at the output of ```SplitNCigarReads``` and it's actually producing improper BAM files but the Broad commented that these BAM files must only be used for HaplotypeCaller and not for anything else downstream: http://gatkforums.broadinstitute.org/discussion/comment/12950/#Comment_12950

For a more generic approach, I could maybe look into implementing a proper N-read splitter that would also set the ```FLAG``` correctly and fix some of the tags (like ```NM```) for the split reads, if read splitting was seen as the way to go.

Any thoughts anyone?

**Comment by schelhorn** [comment]
I'd also be interested in having RNA Seq variant calling implemented. Is this topic still of interest to the community, and may a single-run implementation of the vardict approach as a free alternative to the existing GATK implementation make sense?

**Comment by mjafin** [comment]
Hi @schelhorn, you can currently use STAR (or Tophat) aligned bam files from the RNA-seq run in a second pass of bcbio, selecting the variant calling pipeline and `vardict` as the variant caller, to call variants in RNA-seq. All Gatk steps must be disabled, including realignment and recalibration. It works but YMMV.

**Comment by roryk** [comment]
Hi Sven-Eric,

Another option is to stick variantcall: gatk under the algorithm section for your RNA-seq run, and it will call variants as part of your RNA-seq run using GATK. We haven't done very much work with RNA-seq variant calling, so if you have any suggestions about where we can improve, especially at filtering out the false positives, that would be super sweet.

**Comment by schelhorn** [comment]
@mjafin: Thanks, but that two-run approach was something I'd like to avoid, if possible. That's why I was asking if it would make sense to promote Vardict to a first class citizen for RNA Seq variant calling, similar to GATK. Perhaps the intention of my question wasn't clear. @roryk: True, but the GATK walker used in the current implementation is non-drew, AFAIK. I would currently like to avoid shelling out $32k for the GATK commercial license.

**Comment by mjafin** [comment]
I'm not familiar with how @roryk implemented the direct Gatk based RNA-seq variant calling, but if it's possible to skip the Gatk spliced read splitting then VarDict should be able to produce variants fairly easily (it handles spliced reads intrinsically).

**Comment by inti** [comment]
Hi, 
I am interested on this as well. I am currently working as: 
```
1 - HISAT->freebayes->VCF1-> re map with GSNAP with known variation
        '->StringTie->GTF1
2- GSNAP using VCF1 and GTF1->freebayes->VCF2
        '->StringTie->GTF2
```
I am now changing freebayes from the first step for VarDict. The first round of variant calling is done sample-wise and the second round is done using multisample calling on all position identified as likely variation on the first round. 

I choose hisat as first mapper because it is pretty fast (any comments on this welcomed) and GSNAP as second mapper because it is very sensitive and comes out well on evaluation. This was actually somehow inspired by the description of GSTRUCT,a GSNAP/GMAP software family not released yet but described on sup mat of Engström et al (2013 www.nature.com/articles/nmeth.2722).

What option are you using for VarDict on RNA-seq @mjafin (if I can pick your brain)?

**Comment by roryk** [comment]
I kind of forgot about this-- @mjafin have you run VarDict on RNA-seq data? It would be sweet to have a free version implemented instead of having to use GATK.

**Comment by schelhorn** [comment]
Bcbio VarDict support for RNA Seq variant calling would be great, +1!

**Comment by mjafin** [comment]
Ugh, me too.. Yes VarDict runs on Star aligned BAMs out of the box. No Broad tools should be run on the bams between alignment and VarDict. I think @roryk if you can skip the bam splice splitting in the rnaseq pipeline then we could produce VarDict variants readily. We sould use a 15 to 20 percent AF cutoff to get rid of some of the noise plus I should really look into annotating RNA editing sites after calling

**Comment by schelhorn** [comment]
[Han et al., Cancer Cell. (2015)](http://www.sciencedirect.com/science/article/pii/S1535610815003049) have recently published a RNA-editing study on most of the TCGA data (6.2k samples, that is about the number of samples that were screened for _genomic_ mutations). Their approach may be a little _ad-hoc_, but they also use the rnaedit.com database. In any way, having RNA-Seq calling with `vardict` would be awesome, and annotation with (but not filtering of) RNA editing events would be a nice plus.

From the publication:

> We obtained a comprehensive collection of ∼1.4 million A-to-I RNA editing sites from RADAR (http://rnaedit.com) (Ramaswami and Li, 2014). Note that these RNA editing sites were directly called from RNA-seq data from normal tissues and tumor samples, not from the comparison of editing profiles upon ADAR perturbation. We re-annotated them by ANNOVAR (Wang et al., 2010) and then filtered ∼4,000 sites annotated in dbSNP (version 137), COSMIC, and TCGA somatic mutations. On the basis of the RNA-seq reads mapped to the human reference genome (hg19), the editing level at a specific site in a given sample was calculated as the number of edited reads divided by the total number of reads (Ramaswami et al., 2013), and only the nucleotides with base quality ≥20 were used. Those editing sites with at least three edited reads in at least 3 samples per tissue type were considered to be detected RNA editing sites. To ensure adequate statistical power, we further identified the informative RNA editing sites among the detected RNA editing sites by requiring at least 30 samples (including normal samples if available) with coverage ≥ 10 in a tissue/tumor type. Thus, given a cancer type, the tumor samples and their related normal samples had the same set of informative RNA editing sites in our analysis. To further rule out the possibility of potential contamination due to undetected SNPs or somatic mutations, we obtained whole-genome sequencing data from International Cancer Genome Consortium and whole-exome sequencing data from TCGA for the cancer types we surveyed and assessed if there were some potential mutational signals at informative RNA editing sites. We found potential mutational signals at only 310 sites out of 112,572 across the 17 cancer types (0.28%) and excluded them from our analysis.

**Comment by roryk** [comment]
Thanks @schelhorn,

Totally agree, thanks for putting this on our RADAR. I'm slowly working through my list of stuff to implement for bcbio-nextgen and this is on the list.

**Comment by schelhorn** [comment]
Great; take your time, your work is much appreciated.

**Comment by pwaltman** [comment]
@mjafin, I hope you don't mind me re-opening an old thread, but when you said that VarDict could/would handle STAR aligned bams out of the box, can you explain what pre-processing - if any - VarDict requires be applied? Note, I have applied STAR by hand (NOT via the bcbio pipeline), using the 2-pass alignment, as recommended by the Broad; but having provided a GTF to STAR (as recommended by STAR's author). The exact steps I followed are here: https://groups.google.com/d/msg/rna-star/0YGQtuwcmTY/NxgAapIJAwAJ.

Am I correct in assuming, they would need to be sorted & de-duped? Should users also call STAR with the "--outSAMstrandField intronMotif" parameter (necessary to add the XS param to the bams that are generated)?

**Comment by mjafin** [comment]
@pwaltman VarDict is generally unfussy about bam files but it's generally best to avoid using any Broad tools being applied to BAMs. Sorting and indexing is necessary, de-duping is optional. We typically use the BAMs as they come from bcbio. For unstranded data bcbio uses the infronMotif setting, see https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/star.py#L67

**Comment by ekg** [comment]
@mjafin and others, freebayes should now handle the spliced reads. If this isn't the case please ping me over on the freebayes repo. The only problem I remember was during left alignment of indels. I don't have the commit I'd handy but I believe it has been resolved.

**Comment by mjafin** [comment]
Thanks Erik, that should give us plenty of free and commercial options now to run variant calling in RNA-seq. I'll close this issue even though not everything here has been necessarily implemented (RNA-editing)
