### ISSUE TITLE
transfer_info.yaml - must we rsync or can we use in-place? 

### ISSUE THREAD

**Issue by caddymob** [chapmanb/bcbio-nextgen#391]
Hi Brad -

My good friend @jpeden and I are looking at finally bringing galaxy & bcbio together and it looks like you have put a lot of work into this! At the moment I am a little unclear if rsync'ing run data from the `transfer_info.yaml` is a requirement  (looking at fa875d358a). In other words,  our cluster is setup to have the sequencers write directly to the LUSTRE file system - this way we don't have to transfer any data upon run completion, we just compute right there. 

So, is there a way to set the `transfer_info.yaml` to kick off bcbio upon run-completion, in-place without dup'ing to another path on the same disk? Or am I reading the yaml and docs wrong? 

For example, here is how the dir structure looks on our end:

```
-/scratch/illumina_run_folders/huentelman/106_Honeybees_Nextera_as_01142014/
   - 140114_7001452_0106_BD1CAUACXX
   - analysis
```

The `140114_7001452_0106_BD1CAUACXX` is the subdir of the human-named `106_Honeybees_Nextera_as_01142014` where the sequencer is writing, `analysis` is where I have BCL conversion and so on written. 

Once complete, we've been using bcbio to transfer the `final` dir to permanent storage and its awesome :+1: but can you help clarify or point us in the right direction?

Thanks!!

Jason

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
