### ISSUE TITLE
Mac OS 10.9 installation error

### ISSUE THREAD

**Issue by alartin** [chapmanb/bcbio-nextgen#396]
Hi,
I met an error during the installation. 
Installing data and third party dependencies
Upgrading third party tools to latest versions
Cloning into 'cloudbiolinux'...
remote: Reusing existing pack: 9171, done.
remote: Counting objects: 36, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 9207 (delta 19), reused 0 (delta 0)
Receiving objects: 100% (9207/9207), 7.10 MiB | 57.00 KiB/s, done.
Resolving deltas: 100% (4829/4829), done.
Checking connectivity... done.
Setting up virtual machine
INFO: This is a Base Flavor - no overrides
INFO: Reading default fabricrc.txt
DBG [config.py]: Using config file /Users/alartin/Downloads/tmpbcbio-install/cloudbiolinux/cloudbio/../config/fabricrc.txt
DBG [__init__.py]: Minimal Edition 1.8.3
INFO: This is a minimal
INFO: Distribution __auto__
INFO: Get local environment
INFO: MacOSX setup
[localhost] local: ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup

Fatal error: local() encountered an error (return code 1) while executing 'ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"'

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 253, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--data']' returned non-zero exit status 1
--------------------
I've uninstalled the homebrew installed on my laptop before but still got the same error. Could you please help? Thanks!

**Comment by roryk** [comment]
Closing this out for now, there are several tools that won't work so a native OSX version probably isn't going to happen anytime soon but hopefully the Docker approach will work. Thanks!
