### ISSUE TITLE
Skip non-callable regions instead of raising an exception

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#409]
With the latest master, I get (breaks for legibility):

````
 ValueError: No callable regions found from BAM file. 
 Alignment regions might not overlap with regions found in your `variant_regions` BED:
````

This is actually known as some amplicons in my design may be off-target. Early version of the pipeline did not throw an exception, and instead continued. I think that at least for targeted amplicon designs, this should be an error that should not prevent the pipeline from running.

**Comment by roryk** [comment]
Closed because issue #410 was closed.
