### ISSUE TITLE
bedtools runs fail without further details

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#410]
After resuming a failed run, the pipeline breaks in the `combine_sample_regions` step. I'm guessing because empty BED files were made somewhere, however there's no debug or indication of what's going on.

I only get

````
The requested bed file (/mnt/data/projects/<path_to_tmp_file>/pybedtools.oSQrEa.tmp) could not be opened. Exiting!
````

I'll be testing with latest master in a few minutes: if it does not work, I'll revert to latest stable and see if the issue persists (I won't have time for bisecting, unfortunately).

**Comment by roryk** [comment]
Thanks, looks like this got resolved outside of bcbio.
