### ISSUE TITLE
RFC: Recalibration for somatic calling - default to off?

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#461]
In light of Brad's old blog post on FreeBayes performance without the need of BQSR and local indel realignment, I'm wondering whether these steps should be kept, or skipped unless the quality is really bad.

Rationale: they're, in my experience, the step that takes most time in the whole run, at least for targeted sequencing. If this can be removed without side effects, it would be nice.
However I don't have enough experience to figure if it's a good or bad step, hence I'm looking for input.

@mjafin Do you have any experience on using data with / without BQSR and local realignment?

**Comment by roryk** [comment]
This got implemented so it should be all set. Thanks everyone!
