### ISSUE TITLE
rnaseq coverage - missing chanjo symbol 

### ISSUE THREAD

**Issue by kern3020** [chapmanb/bcbio-nextgen#498]
ranseq.py relies on chanjo's  bam.CoverageAdapter symbol.

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/rnaseq/coverage.py#L54

While it still appears in the comments, I am not able to reference the symbol anymore. 

	>>> import chanjo
	>>> print(chanjo.__version__)
	1.1.1
	>>> from chanjo import bam
	>>> bam.CoverageAdapter("foo")
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	AttributeError: 'module' object has no attribute 'CoverageAdapter'
	>>> dir (bam)
	['BamFile', 'Samfile', '__builtins__', '__doc__', '__file__', '__name__', '__package__', 'errno', 'np', 'os', 'path']
	>>>

I'm planning to talk with the chanjo author after the initial integration with it. I can investigate this at that time. 

-jk

**Comment by roryk** [comment]
Thanks John, we dropped chanjo support so this should be all good.
