### ISSUE TITLE
SGE and iPython Array Jobs

### ISSUE THREAD

**Issue by BioInfo** [chapmanb/bcbio-nextgen#532]
I was hoping to open a discussion around how array jobs are handled. I am  honestly not sure if this is an SGE thing or iPython thing. My "research" is making me think iPython, which I know much less about compared to SGE.  Right now an array of jobs is submitted for a specific step.  If there are not enough cores to satisfy the required number of requested slots, it submits the jobs it can, and the other queue up.  But, the jobs that make it into slots don't start processing until all jobs make it into slots.  THe other thing I noticed is that when all jobs make it into slots, it holds all slots until all jobs in the array finish processing, even if some jobs are no longer "processing" anything.  So for example, in RNA-seq, I submitted a run with -n 128, it uses 128 cores to gunzip the fastq files.  It waits till the last job is finished to complete the array, and move on to next step, keeping all 128 slots full until this time.

So couple questions:

1. Could single jobs within the array start processing immediately, even if all jobs haven't been allocated a slot?
2. In tandem, could jobs within an array that finish be "shutdown" and allow for other jobs to move into that slot?  But, only move on to next step in pipeline after the final job in the array completes?

Hope this makes sense.  I can provide more specific detail if need for the discussion.

**Comment by roryk** [comment]
Thanks, I think we handled everything in the thread. Letting the jobs start immediately when a single engine was up was a great suggestion. Thanks @mjafin and @BioInfo.
