### ISSUE TITLE
Installing bcbio on Amazon Cloud with starcluster

### ISSUE THREAD

**Issue by michaelxu2014** [chapmanb/bcbio-nextgen#573]
Hi, 

I am trying to install bcbio on Amazon cloud with starcluster. At first, I created a cluster with starcluster and then I log into the head node to install the isolated version. I found the bcbio installation will temporally download all third party packages to the root volume even thought I specified the path to bcbio to an attached big volume. Unfortunately, the root volume on the head node is only 8GB. When bcbio installation was downloaded GRCh37-bwa.tar.xz, it was failed due to no space. 

Is there anyway to install bcbio on the SGE cluster by starcluster? Or is there anyway to run bcbio on a cluster on amazon cloud? Thanks!

**Comment by roryk** [comment]
Thanks @michaelxu2014, hope you eventually got it up and going.
