### ISSUE TITLE
RFC: Add typical "workflows" to documentation, extending "Pipelines"

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#588]
As the number of tools and features provided by bcbio-nextgen is skyrocketing, I think that the configuration page in the documentation, while necessary, is no longer sufficient for understanding what to do for a general use case (germline variants, somatic variants, RNA-seq....). I would like to know if there's interest in doing so: if so I can probably start adding new things related to somatic mutation calling.

**Comment by roryk** [comment]
Thanks for the suggestion @lbeltrame and @kern3020, we now have a little section with examples for different types of analyses.
