### ISSUE TITLE
Try to provide more information when engines die

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#643]
I have a few tasks dying during runs, but I have no idea why, because all I get is their hash ID. This is problematic because I don't know what happened on the node that failed, in fact I don't even *know* which process on which node died.

I'm not sure it is technically doable, but I'm opening an issue for reference.

When this occurs, restarting the pipeline is not possible due to bug #642.

**Comment by roryk** [comment]
Hi Luca, closing this out because it is pretty old and we don't really have a clear path to making it better. I think we just have to live with this one. Thanks!
