### ISSUE TITLE
pindel dies without any error

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#644]
This is the reason that I'm experiencing issue #643: pindel starts, but exits *without the pipeline noticing*. In fact right now it is stuck, but no process is actually running.

To be precise, pindel stops at "Loading reference genome..."

However, running it manually (on the same node as where this issue occurs) yields no error.

**Comment by roryk** [comment]
Closing this out because it is pretty stale and I'm pretty sure you eventually got it going @lbeltrame. Feel free to reopen if we're wrong.
