### ISSUE TITLE
more issues

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#657]
Hi again!

When doing somatic calls with freebayes (perhaps also other callers), I notice that:

1. Calls are generated outside targeted regions
2. Calls are generated where the coverage is 0 in the normal
3. .. and these calls also become annotated as SOMATIC by bcbio-nextgen, i.e. despite no call data exist for the normal reference. (.:.:.:) to infer status from.

Haven't checked the situation if other callers are used, but I guess that this might be a general thing?

Let me know if you need data for testing. 

//Pär

**Comment by roryk** [comment]
Thanks Pär, closing this out because there hasn't been any action on it in a year-- hopefully in newer versions of bcbio this is okay for you. Feel free to reopen if it is still an issue.
