### ISSUE TITLE
Consider using a lazy loading library

### ISSUE THREAD

**Issue by jwm** [chapmanb/bcbio-nextgen#668]
@chapmanb mentioned lazy loading in https://github.com/chapmanb/bcbio-nextgen/pull/660#issuecomment-62920368, and I agree it's a good idea. It should avoid requiring dependencies unless they're actually used, and should make bcbio startup much faster since it's not statting every library on PYTHONPATH on startup. 

- bazaar's lazy_import: http://people.canonical.com/~mwh/bzrlibapi/bzrlib.lazy_import.html
- mecurial's demandimport: https://pypi.python.org/pypi/demandimport

**Comment by chapmanb** [comment]
jwm -- we finally added a lazy import library. Thanks for this idea. Lazy importing everything turned out to cause too many bugs but we can selectively avoid expensive imports now.

**Comment by jwm** [comment]
Yay! I'm happy our children won't be eaten. :smile_cat:
