### ISSUE TITLE
Wish: Support ensemble for paired analyses

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#67]
This is an approach that has been used in a few recent papers, and I think would be a worthwhile addition to the pipeline. There are some points to make:
- [ ] Ensure there are n > 1 methods available (depends on #65, #66 )
- [ ] Check whether bcbio-variation can work with these OOTB
- [ ] See if the pipeline can handle filtering for these: Somatic Sniper has a SS (somatic score), I need to check for VarScan, and MuTect has REJECT/PASS in the VCF FILTER field.

Would this make sense ti implement?

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. Come back if you find other issues  or want to continue with this one.

cheers
