### ISSUE TITLE
sv failed

### ISSUE THREAD

**Issue by kspham** [chapmanb/bcbio-nextgen#689]
Hi Brad/Rory:
Sorry for reporting too many issues, but seems that the sv pipeline failed :(. It goes through 
cn.mops well, but raised errors in delly/lumpy
5872 [2014-12-09 11:36] samblaster: split and discordant reads : 3s_merged
5873 [2014-12-09 11:36] samblaster: Version 0.1.20
5874 [2014-12-09 11:36] samblaster: Inputting from stdin
5875 [2014-12-09 11:36] samblaster: Outputting to stdout
5876 [2014-12-09 11:36] samblaster: Opening /dev/fd/62 for write.
5877 [2014-12-09 11:36] samblaster: Opening /dev/fd/63 for write.
5878 [2014-12-09 12:47] [bam_sort_core] merging from 624 files...
5879 [2014-12-09 12:47] [W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
5880 [2014-12-09 12:47] samblaster: Loaded 84 header sequence entries.
5881 [2014-12-09 12:47] samblaster: Can't find first and/or second of pair in sam block of length 1 for id: D2FC08P1:238:C27VVACXX:5:1101:1195:59613
5882 [2014-12-09 12:47] samblaster: Are you sure the input is sorted by read ids?
5883 [2014-12-09 12:47] 
5884 [2014-12-09 12:47] samtools: writing to standard output failed: Broken pipe
5885 [2014-12-09 12:47] samtools: error closing standard output: -1
5886 [2014-12-09 12:47] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0122.bam' is truncated. Continue anyway.
5887 [2014-12-09 12:48] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0123.bam' is truncated. Continue anyway.
5888 [2014-12-09 12:48] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0124.bam' is truncated. Continue anyway.
5889 [2014-12-09 12:49] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0126.bam' is truncated. Continue anyway.
5890 [2014-12-09 12:50] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0127.bam' is truncated. Continue anyway.
5891 [2014-12-09 12:50] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0128.bam' is truncated. Continue anyway.
5892 [2014-12-09 12:51] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0129.bam' is truncated. Continue anyway.
5893 [2014-12-09 12:52] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0133.bam' is truncated. Continue anyway.
5894 [2014-12-09 12:54] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0136.bam' is truncated. Continue anyway.
5895 [2014-12-09 12:55] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0139.bam' is truncated. Continue anyway.
5896 [2014-12-09 12:57] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0142.bam' is truncated. Continue anyway.
5897 [2014-12-09 12:57] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0143.bam' is truncated. Continue anyway.
5898 [2014-12-09 12:58] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0144.bam' is truncated. Continue anyway.
5899 [2014-12-09 13:02] [bam_merge_core] '/raid/sonpham/schipairs/sv/pair3/workwithoutduplicate/prealign/3s_merged/3s_merged-ready-namesort.0152.bam' is truncated. Continue anyway.
5900 [2014-12-09 14:56] Uncaught exception occurred
5901 Traceback (most recent call last):
5902   File "/raid/sonpham/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run

**Comment by lpantano** [comment]
Closing this since It seems it ended working someway.

let us know if we can help further.

thanks!
