### ISSUE TITLE
bcbio-nextgen / gemini integration

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#700]
In data from Gemini, loaded by bcbio-nextgen, I notice that multiallelic variants are reported with only a single genotype with a single variant.  What happens to the other variant? Is this an issue with bcbio-nextgen, Gemini, or an issue at all?

**Comment by parlar** [comment]
Hi again,

We are eager to move the bcbio-nextgen pipeline into production in our clinical genetics lab. One principal issues are the "gender problem" where variation can be reported as heterozygotes despite being present on chrX in males. Another other issue concerns Gemini's inability to handle multi-allelic states. The "gender problem" we can handle/cope with. The Gemini issue, however, requires fixing.
I realize that you are a very busy person, can I help you in any way with this? What needs to be done, I guess, is to simply generate temporary vcfs using breakmulti and use those for import into gemini? And then remove the temporary vcfs afterwards?

**Comment by chapmanb** [comment]
Pär;
Thanks much for the patience and helping prioritize the outstanding requests. You have a lot of good requests but all of them are more in-depth development projects so it helps to know which ones are blocking your usage of bcbio.

I pushed an update which will decompose multi-allelic inputs into bi-allelic prior to feeding into GEMINI. I evaluated 4 different approaches to do this and vt's (https://github.com/atks/vt) approach handles the widest range of inputs and correctly resets FORMAT/genotype likelihoods so they match the bi-allelic state. It doesn't re-do other FORMAT annotations like depth, so these are all removed as to not be incorrect in the resulting output.

Hope this works for your usage. Please let us know if you run into any issues and thanks again.
