### ISSUE TITLE
tmp files store in incorrect location

### ISSUE THREAD

**Issue by kspham** [chapmanb/bcbio-nextgen#707]
@roryk  @chapmanb  : I'm running rna-seq and see hundreds of files in the "work" directory. Probably there is some typos in code for paths.
>ls work
hundreds of temp-sorted files: 
temp-sort-003864-327B23C6-CHK00000000-BLK103.bin 
and two sam files:
temp-core-003864-6B8B4567.sam 
 temp-core-003868-6B8B4567.sam

**Comment by lpantano** [comment]
I think is featureCounts, is doing something with the bam file, don't know if it is a regular step though. Maybe one solution would it be to chdir featureCount working directory? if it doesn't do that now.

**Comment by roryk** [comment]
Thanks @kspham, we recently cleaned up the tempfile creation in the RNA-seq parts of bcbio-nextgen so hopefully this is straightened out now. Let us know if it is still an issue. Thanks!
