### ISSUE TITLE
sambamba and piped files 

### ISSUE THREAD

**Issue by inti** [chapmanb/bcbio-nextgen#710]
Hi,
I am running the pipeline on a server and it is crashing when the pipeline runs multiple alignments in parallel. We suspect sambamba is playing funny with the pipes/fifos and use of temps. 

Have you have any experience with this? 

Can you give some hints on where sambamba is storing temp files to guide us in here debugging this error.

thanks a lot in advance and have a great Xmas guys ... please do not assume I expect a answer before xmas :)

**Comment by roryk** [comment]
Closing this out as its pretty stale and we haven't been getting reports of issues like this recently. Please reopen if it is still a problem. Thanks!
