### ISSUE TITLE
move fastqc zip to final?

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#719]
I'm having issues displaying the fastqc report as part of another webpage using .load() or other methods. Not sure if it's the embedded graphcs or what it is, but would be possible to move by default also the zipped fastqc output (with pngs) to the "final" folder? Or allow the user to choose it? 

cheers,
Pär

**Comment by parlar** [comment]
Managed to solve this issue without using the pngs, no urgency to add functionality for me.

**Comment by chapmanb** [comment]
Brilliant, thank you. I'd prefer to move to the single embedded page as it makes all of this much easier downstream, so glad you could get it figured out.
