### ISSUE TITLE
linux install fail - log attached

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#720]
I tried the install script on ubuntu without root access and ran into errors. Any ideas?

command:
`python bcbio_nextgen_install.py /share/PI/euan/apps/bcbio --tooldir=/share/PI/euan/apps   --genomes GRCh37 --aligners bwa --aligners bowtie2`

system:
Linux sh-3-32 2.6.32-431.23.3.el6.x86_64 #1 SMP Wed Jul 16 06:12:23 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

log:
[bcbio_install.log](https://www.dropbox.com/s/q010kd0l61ohcnu/bcbio_install.log?dl=0)

**Comment by chapmanb** [comment]
Daryl;
Thanks for the report and sorry about the issue. The likely problem is that you don't have ruby installed on the machine, which is needed for the linuxbrew package manager. Hopefully installing that will get things going again.

More generally, here is the list of required system dependencies for isolated installations which might help in case anything else is missing:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

Hope this gets you going and please feel free to re-open if you run into any other issues.
