### ISSUE TITLE
vcffixup no longer reads stdin with no arguments

### ISSUE THREAD

**Issue by nhansen** [chapmanb/bcbio-nextgen#721]
I have now completed running the "Exome with Validation Against Reference Materials" pipeline by restarting a run at the "ensemble" stage after upgrading, but when I went to run the whole thing from start to finish, I ran into a problem while calling with freebayes.  It looks like variation/freebayes.py is piping VCF output to vcffixup (called without arguments), but vcflib's latest update now requires you to pass a "-" argument to read stdin (see https://github.com/ekg/vcflib/commit/bc1b41dcdb7dd77d134d46cd39e9a554d51b64c7).

So vcffixup is spitting out a usage statement, and the following commands in the freebayes string of pipes are failing, dumping cores, etc.  Output is below.

--Nancy
(convinced I am jinxed w.r.t. running bcbio-nextgen...)

[2015-01-10T01:40Z] /bin/bash: line 1: 29829 Done                    /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/freebayes -f /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -b /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align/NA12878-2/NA12878-2-sort.bam --ploidy 2 --targets /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/freebayes/1/NA12878-2-1_93298231_108853498-raw-regions.bed --min-repeat-entropy 1 --experimental-gls
[2015-01-10T01:40Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/freebayes -f /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -b /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align/NA12878-2/NA12878-2-sort.bam --ploidy 2 --targets /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/freebayes/1/NA12878-2-1_93298231_108853498-raw-regions.bed --min-repeat-entropy 1 --experimental-gls | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/vcffilter -f 'QUAL > 5' -s | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}' | vcfallelicprimitives --keep-geno | vcffixup | vcfstreamsort | vt normalize -r /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -q - 2> /dev/null | vcfuniqalleles | bgzip -c > /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/freebayes/1/tx/tmpe9YBcP/NA12878-2-1_93298231_108853498-raw.vcf.gz
usage: vcffixup <vcf file>
outputs a VCF stream where AC and NS have been generated for each record using sample genotypes
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Could not find any mapped reads in target region 1:93426610..93427283
/bin/bash: line 1: 29829 Done                    /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/freebayes -f /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -b /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/align/NA12878-2/NA12878-2-sort.bam --ploidy 2 --targets /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/freebayes/1/NA12878-2-1_93298231_108853498-raw-regions.bed --min-repeat-entropy 1 --experimental-gls
     29830                       | /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/bin/vcffilter -f 'QUAL > 5' -s
     29831                       | awk -F'	' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDX]/, "N", $4) } {print}'
     29832                       | vcfallelicprimitives --keep-geno
     29833 Exit 1                  | vcffixup
     29834 Aborted                 (core dumped) | vcfstreamsort
     29835 Exit 1                  | vt normalize -r /cluster/ifs/projects/seqSim/bcbio-nextgen/bcbio/genomes/Hsapiens/GRCh37/seq/GRCh37.fa -q - 2> /dev/null
     29836 Aborted                 (core dumped) | vcfuniqalleles
     29837                       | bgzip -c > /cluster/ifs/projects/seqSim/bcbio_testanalysis/NA12878-exome-eval/work/freebayes/1/tx/tmpe9YBcP/NA12878-2-1_93298231_108853498-raw.vcf.gz
' returned non-zero exit status 134
[2015-01-10T01:40Z] Genotyping with FreeBayes
[2015-01-10T01:40Z] usage: vcffixup <vcf file>
[2015-01-10T01:40Z] outputs a VCF stream where AC and NS have been generated for each record using sample genotypes
[2015-01-10T01:40Z] terminate called after throwing an instance of 'std::out_of_range'
[2015-01-10T01:40Z]   what():  basic_string::substr
[2015-01-10T01:40Z] terminate called after throwing an instance of 'std::out_of_range'
[2015-01-10T01:40Z]   what():  basic_string::substr
[2015-01-10T01:40Z] Genotyping with FreeBayes
[2015-01-10T01:40Z] usage: vcffixup <vcf file>
[2015-01-10T01:40Z] outputs a VCF stream where AC and NS have been generated for each record using sample genotypes
[2015-01-10T01:40Z] terminate called after throwing an instance of 'std::out_of_range'
[2015-01-10T01:40Z]   what():  basic_string::substr
[2015-01-10T01:40Z] terminate called after throwing an instance of 'std::out_of_range'
[2015-01-10T01:40Z]   what():  basic_string::substr

**Comment by chapmanb** [comment]
Nancy;
Glad it got finished once for you and sorry about the continued problems. This is my fault, I should have mentioned to upgrade the code along with the tools as I pushed a fix for this a few days back:

https://github.com/chapmanb/bcbio-nextgen/commit/cb97e10d2ee50983713d65e77690067779f3e731

If you do one more `bcbio_nextgen.py upgrade -u development` you should be good to go. Sorry about all the hassle with the development version. I'm planning to push a new release tomorrow after finishing up some final testing/validation on the current development.

Thanks again for the patience on this.

**Comment by nhansen** [comment]
Ah--now I see!  Thanks!

--Nancy

**Comment by chapmanb** [comment]
Nancy;
Don't hate me, but I pushed one more small fix to handle the latest sambamba version we upgraded to this morning, so just make sure you run the update after this fix was put in: https://github.com/chapmanb/bcbio-nextgen/commit/f50109714863242a63c113374d32c460a6f28af6
Just wanted to give you a heads up so you didn't run into any other issues. Thanks again.

**Comment by nhansen** [comment]
Could never hate you, Brad!  Thanks for all the work you do for this amazing project!
--Nancy

**Comment by tanglingfung** [comment]
I ran into the same issue with bcbio v0.8.7 and latest sambamba, any other clues? (I did not update the tools via bcbio_nextgen.py upgrade though)

**Comment by tanglingfung** [comment]
I am using sambamba v0.5.1

**Comment by tanglingfung** [comment]
it's probably an issue in homebrew, but when I do the tools upgrade with bcbio_nextgen.py, I got an error: 

export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/share/thirdparty/lib/perl5:${PERL5LIB} && /home/share/thirdparty/bin/brew install -v --env=inherit   expat
Error: no such file to load -- irb

**Comment by chapmanb** [comment]
Paul;
Sorry about the issue, you'll definitely need to upgrade the tools in tandem with the code to fix the underlying `vcffixup` error, since the behavior in vcflib changed.

Regarding homebrew it looks like you need to install `ruby-irb` if you're on CentOS, which is required by more recent versions of homebrew. Most ruby installs include it but I believe CentOS and a few others leave it separate:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

Hope this helps.

**Comment by tanglingfung** [comment]
Thanks Brad. It's helpful. Sorry not to have looked into the documentation again. There are many recent changes.
