### ISSUE TITLE
odd genotypes in chrX

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#722]
I looked at genotypes in chrX in a male and found some oddities. Data is from an ensemble-call. Most of the SNPs are hemizygous. However, a few chrX positions are reported as homozygotic or even heterozygotic. As far as I know, they do not reside in paraautosomal regions.

Going back to the vcf files, I notice that the calls appear to have been made without specifying ploidy=1 for chrX. It appears to me that genotypes are cleaned up before loading into gemini using the entered sex, but positions which are called as heterozygous in at least one sample are kept at ploidy=2. 

Would it be possible to use the ploidy settings directly in the callers instead to avoid this situation?

Output from gemini:
chrom   start   end ref alt gt
chrX    31496349    31496350    C   T   T
chrX    31515347    31515348    A   G   G/G
chrX    31676095    31676096    G   A   A
chrX    31893148    31893149    C   G   G

**Comment by chapmanb** [comment]
Par;
Sorry about the issues with sex chromosome calling. This has a number of tricky parts to support generally:

- Some callers do not generally support ploidy-based calling. For instance, Platypus and samtools. Samtools does support some chromosome and ploidy specifications in a different way then the other callers. I just added support for ploidy-based calling in GATK HaplotyperCaller, which is available in the latest 3.3 release.
- Callers that support it don't necessarily have support for calling differently based on items in a family. If you're doing pooled calling with mixed genders, like trios, bcbio will call in the most general way so the males in the pool will have X/X and the females will include Y.

This is something we could work on cleaning up in the bcbio post-processing steps to better improve support. What is your calling setup where you are running into issues? What variant callers and pooling strategy are you using?

Thanks again for all the feedback and sorry about the trickiness of this.

**Comment by parlar** [comment]
Thanks for a speedy response. Currently, I'm using 4 callers: freebayes, gatk-haplotype, platypus, samtools (not joint-calling) but will likely change. Suggestions on other combinations of callers / settings are much appreciated, btw. 

The issue for me is really what do do with calls that indicate heterozygous variation in male/chrX (outside PARs). The safest is, I guess, is to treat it as true and convert them to hemizygous, with the risk of some additional false positives (application is clinic where false negatives are worse since findings are verified).

**Comment by parlar** [comment]
Sorry, I think I misread you. Yes, I do pooled calling, but currently not with the "joint-" setting. The genders vary. I'm running six samples at a time and the and usually both male and female are there. Unfortunately, we will not all the time be able to run all samples having the same gender.

**Comment by chapmanb** [comment]
Par;
That makes sense, thanks for the clarification. We don't yet have a good way to fix ploidy for mixed genders called in a pool. We'd need to write custom code to walk through and fix up each sample based on the gender. As you mention, this is a bit tricky as it's not clear why to do with heterozygote calls and you have to make some determination based on the PLs if you should prefer makes these a homozygous variant or reference call. I don't know of any good datasets to validate this against.

Issue #709 has a discussion on this as well. This is definitely something we'd like to get right but is a bit of a development project to undertake.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. And there is another issue related to this that still is open, so will leave the other one as the main thread.

cheers
