### ISSUE TITLE
snpeff SHA1 mismatch

### ISSUE THREAD

**Issue by mdeboth** [chapmanb/bcbio-nextgen#724]
Hey all - I'm trying to setup an isolated installation and hit a roadblock at snpEff.

```
Error: SHA1 mismatch
Expected: 83e1d2e32bfc8b9104f1856e70f8b1112fa290ab
Actual: ed4460b89bc22cd6873d1ca6a3cde8565bd2f8d8
```

My SHA1 actually matches the SourceForge download at http://sourceforge.net/projects/snpeff/files/

Looks like the SourceForge download was modified yesterday and might have a new SHA1 value?

**Comment by mdeboth** [comment]
Sorry - I think this is probably an upstream issue in homebrew-cbl.

**Comment by chapmanb** [comment]
Matt;
Thanks much for the report. I submitted an upstream patch into homebrew-science to resolve this, and will try to make the behavior more consistent long term working with the author of snpEff. As soon as the patch gets pulled into homebrew-science this'll be good again. Thanks again.

**Comment by mdeboth** [comment]
Thanks, Brad!
