### ISSUE TITLE
cluster_helper module

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#728]
Was cluster_helper meant to be part of the original install?

```
python $BCBIO_PATH/scripts/utils/bcbio_prepare_samples.py --out ../genotype/merged_fastqs/ --csv project_fb_n143.csv

Traceback (most recent call last):
  File "/share/PI/euan/apps/bcbio-nextgen/scripts/utils/bcbio_prepare_samples.py", line 6, in <module>
    from cluster_helper import cluster as ipc
ImportError: No module named cluster_helper
```

**Comment by chapmanb** [comment]
Daryl;
It is installed as part of bcbio but in an isolated Python installation, not your global Python install. If you change the python used to `/path/to/bcbio/anaconda/bin/python` things should work as expected. Hope this helps.

**Comment by dwaggott** [comment]
Ah, yes. works.
