### ISSUE TITLE
Update for bcbio

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#729]
Hi Brad,

How can I update bcbio to latest version?

When I use:

bcbio_nextgen.py upgrade
bcbio_nextgen.py upgrade  --tools
bcbio_nextgen.py upgrade  --tools --data

The version is still 0.8.3a

Thanks!

**Comment by chapmanb** [comment]
Sorry about the issue. Each of the install targets is independent as we like to avoid folks accidentally updating code or tools or data without explicitly wanting to. So you can do:
```
bcbio_nextgen.py upgrade -u development --tools --data
```
to get the latest development version. Hope this helps.
