### ISSUE TITLE
Broken pipe samblaster

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#733]
Not sure if this is related to #710 but I'm getting (a) Broken pipe errors and (b) the pipeline dies near the end of alignment. I'm running the freebayes joint caller on n=143 using slurm. The broken pipes are happening around samblaster.

pipeline call:
```
bcbio_nextgen.py  project_n143-fb/config/project_n143-fb.yaml  -t ipython -n 500 -q normal -s slurm -r "timelimit=48:00:00"
```

logs:
https://www.dropbox.com/s/mw2v9g47qsa7ct9/bcbio-ipcontroller.err.1424502?dl=0
https://www.dropbox.com/s/k1zv4bnaqth23c8/bcbio-ipengine.err.%251424508?dl=0

An example failed line is:

```
set -o pipefail; /share/PI/euan/apps/bin/bwa mem -M -t 16  -R '@RG\tID:126\tPL:illumina\tPU:126_2015-01-22_project_n143-fb\tSM:4_48' -v 1 /share/PI/euan/apps/bcbio/genomes/Hsapiens/GRCh37/bwa/   GRCh37.fa /scratch/PI/euan/projects/athletes/genotype/merged_fastqs/4_48_R1.fastq.gz /scratch/PI/euan/projects/athletes/genotype/merged_fastqs/4_48_R2.fastq.gz | /sharePI/euan/apps/bin/          samblaster --splitterFile >(/share/PI/euan/apps/bin/samtools view -S -u /dev/stdin | /share/PI/euan/apps/bin/sambamba sort -t 16 -m 1G --tmpdir /scratch/PI/euan/projects/athletes/bcbio/tx/       tmp3JCCVc/spl -o /scratch/PI/euan/projects/athletes/bcbio/align/4_48/tx/tmpWc7ayr/126_2015-01-22_project_n143-fb-sort-sr.bam /dev/stdin) --discordantFile >(/share/PI/euan/apps/bin/samtools view -S -u /dev/stdin | /share/PI/euan/apps/bin/sambamba sort -t 16 -m 1G --tmpdir /scratch/PI/euan/projects/athletes/bcbio/tx/tmp3JCCVc/disc -o /scratch/PI/euan/projects/athletes/bcbio/align/4_48/tx/ tmpJr1HBn/126_2015-01-22_project_n143-fb-sort-disc.bam /dev/stdin) | /share/PI/euan/apps/bin/samtools view -S -u /dev/stdin | /share/PI/euan/apps/bin/sambamba sort -t 16 -m 1G --tmpdir /scratch/ PI/euan/projects/athletes/bcbio/tx/tmp3JCCVc/full -o /scratch/PI/euan/projects/athletes/bcbio/align/4_48/tx/tmppH7jpN/126_2015-01-22_project_n143-fb-sort.bam /dev/stdin
```

**Comment by dwaggott** [comment]
It could be a concurrency issue on lustre, the samples with broken pipes and no bam files look random. Can I add env variables to the config for local scratch?

```
resources:
  tmp:
    dir: $LOCAL_SCRATCH
```

**Comment by chapmanb** [comment]
Daryl;
Thanks for the detailed report. I agree with your assessment of the underlying issue. It looks like the local Lustre storage is getting overwhealmed and it having trouble writing to disk, leading to the issue. Hopefully using local scratch will help resolve this. I added support for specifying scratch locations with environmental variables to support your setup, so if you upgrade to the latest development:
```
bcbio_nextgen.py upgrade -u development
```
it should hopefully work with that change. Hope this fixes it for you.

**Comment by dwaggott** [comment]
I changed the resources to use local scratch and the jobs kicked off
without fuss. I wasn't getting output so I logged onto one of the engine
nodes to observe, nothing was running, any ideas?

I'm going to kill and restart.

**Comment by chapmanb** [comment]
Daryl;
Unfortunately I'm not sure how to help without error messages or other ideas of what might be happening. It's possible bcbio was still getting spun up and finding the next point to do alignment at. If you wait a bit longer does it start off?

**Comment by dwaggott** [comment]
Nothing in logs... just jobs kicking off with nothing running and no output
being generated. It's run for about 2 days so let me retry.
