### ISSUE TITLE
Restarting a pipeline

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#734]
If I restart a pipeline that crashed, does it start where things left off or does it restart fresh overwriting some of the completed sections i.e. alignment. If the latter I guess the simplest thing to do is manual tinkering with the yaml config, correct?

**Comment by roryk** [comment]
Hi Daryl,

It starts where it left off, it will check to see if a step has the expected output and skip if it is already done. Everything is transactional so you won't half have written files lying around if it died in the middle as well, you should be good to go.

**Comment by dwaggott** [comment]
Very nice.
