### ISSUE TITLE
jobs not submitted

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#735]
I'm noticing that jobs aren't queueing including the monitoring process. Cluster usage (slurm) is high at the moment. Is there a built in hold on submit based on queue size? 

```
 cat SLURM_controller78826543-733a-4213-b061-214bd39c6761

#!/bin/sh
#SBATCH -p normal
#SBATCH -J bcbio-c
#SBATCH -o bcbio-ipcontroller.out.%j
#SBATCH -e bcbio-ipcontroller.err.%j
#SBATCH -t 7-00:00:00
#SBATCH --cpus-per-task=1
#SBATCH -A euan
#SBATCH --mem=200

/share/PI/euan/apps/bcbio/anaconda/bin/python -E -c 'import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimit(resource.RLIMIT_NOFILE); target_hdls = min(max_hdls, 10240) if max_hdls > 0 else 10240; resource.setrlimit(resource.RLIMIT_NOFILE, (max(cur_hdls, target_hdls), max_hdls)); from cluster_helper.cluster import VMFixIPControllerApp; VMFixIPControllerApp.launch_instance()' --ip=* --log-to-file --profile-dir="/scratch/PI/euan/projects/athletes/bcbio/log/ipython" --cluster-id="ef247c8f-8ee6-425d-a359-8597a5381a0d" --nodb --hwm=1 --scheme=leastload --HeartMonitor.max_heartmonitor_misses=120 --HeartMonitor.period=60000
```

**Comment by roryk** [comment]
Hi Daryl,

Sorry for the issue; so that bcbio-ipcontroller job never gets queued, or does it never start? If it is not queued, the job might be being rejected by the scheduler for some reason. If you just submit that job script with sbatch < SLURM_controller78826543-733a-4213-b061-214bd39c6761, does SLURM give you an error?

**Comment by dwaggott** [comment]
Nice! It looks like the time request was too high. Should that have been
logged somewhere that I missed?

**Comment by roryk** [comment]
Hi Daryl,

Nope, you didn't miss anything-- if the jobs never get queued at all no log files get created, sorry about that, it makes it hard to figure out what went wrong. I added some logic for the SLURM scheduler to ipython-cluster-helper that checks to see if the requested time is more than the maximum time allowed on the cluster, and if it is, sets the time to be the maximum time allowed instead, so at least now the jobs will get queued. 

You can force time to be something else by passing -r “time=1-00:00” in your call to bcbio-nextgen which should get you started. Thanks!
