### ISSUE TITLE
Aligning SE RNAseq reads using Bowtie2 

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#739]
Hi,
 It is a bug in the align_transcriptome function in bowtie2.py when you are mapping SE RNAseq reads. Bowtie2 doesn't start because it assumes that single end reads are using "-U" and not  "-1". The align_transcriptome function (around row 135) needs to be updated to handle the difference between SE (-U) and PE (-1 & -2) reads in a similar way as the genomic align function.

**Comment by roryk** [comment]
Thanks for doing all of the investigation work Andreas, good catch. This should be good to go now.
