### ISSUE TITLE
bcbio using hadoop

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#742]
Is the ipython infrastructure able to work with hadoop clusters? I've got one that lies dormant due to overhead in code migration.

**Comment by chapmanb** [comment]
Daryl;
Unfortunately not. As you mention, the hadoop distribution model is quite different from that used in HPC-style environments, so it would take a lot of work to migate the IPython parallel approach there. Sorry to not have a solution for you in this case.
