### ISSUE TITLE
Upgrade error: seaborn has a conflict with the remaining packages

### ISSUE THREAD

**Issue by druvus** [chapmanb/bcbio-nextgen#743]
Hi Brad
I got the following error when I tried to upgrade my bcbio developmental version today. Seems to be some issues with seaborn. Do you have an idea what happened?  

<pre>
andreas@kaw:/media/data/andreas/ecoli/bcbio/MG1655$ bcbio_nextgen.py upgrade -u development --tools --data
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /media/data/bin/bcbio-nextgen/data/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.8.3                |           py27_0         162 KB

The following packages will be UPDATED:

    conda: 3.8.2-py27_0 --> 3.8.3-py27_0
    numpy: 1.8.2-py27_0 --> 1.9.1-py27_0

Fetching packages ...
conda-3.8.3-py 100% |#########################################| Time: 0:00:00 289.95 kB/s
Extracting packages ...
[      COMPLETE      ] |###########################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |###########################################################| 100%
Linking packages ...
[      COMPLETE      ] |###########################################################| 100%
Fetching package metadata: ...
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
WARNING: This could take a while. Type Ctrl-C to exit.
[      COMPLETE      ] |###########################################################| 100%

Hint: seaborn has a conflict with the remaining packages
Traceback (most recent call last):
  File "/media/data/bin/bcbio-nextgen/tools/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 57, in upgrade_bcbio
    _update_conda_packages()
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 192, in _update_conda_packages
    subprocess.check_call([conda_bin, "install", "--yes"] + channels + pkgs)
  File "/media/data/bin/bcbio-nextgen/data/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/media/data/bin/bcbio-nextgen/data/anaconda/bin/conda', 'install', '--yes', '-c', 'https://conda.binstar.org/bcbio', 'biopython', 'boto', 'cnvkit', 'cpat', 'cython', 'ipython', 'lxml', 'matplotlib', 'msgpack-python', 'nose', 'numpy', 'pandas', 'patsy', 'pycrypto', 'pip', 'pysam', 'pyvcf', 'pyyaml', 'pyzmq', 'reportlab', 'requests', 'scikit-learn', 'scipy', 'seaborn', 'setuptools', 'sqlalchemy', 'statsmodels', 'toolz', 'tornado']' returned non-zero exit status 1
</pre>

**Comment by chapmanb** [comment]
Andreas;
Apologies about the issue. We've been working this weekend to bring the packages up to date, and I think this was a conflict with some of our builds using numpy 1.8 and seaborn asking for numpy 1.9. I updated everything to consistently use numpy 1.9 so hope it will work again if you can re-try. Thanks much for letting us know.

**Comment by druvus** [comment]
Thanks Brad,
that solved the problem.
