### ISSUE TITLE
Update error on Debian Wheezy system

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#746]
Upon updating (after a month or so of hiatus) I was greeted with the following error when trying to install sambamba:

````
/mnt/data/bcbio-tools/Cellar/libconfig/1.4.9: 15 files, 483K, built in 24 seconds
==> Installing sambamba dependency: ldc
==> Downloading https://github.com/ldc-developers/ldc/releases/download/v0.15.1/ldc-0.15.1-src.tar.gz
############################################################################################################################################################################################################################################ 100,0%
Error: The selected compiler doesn't support C++11: gcc
````

**Comment by lbeltrame** [comment]
And what's strange, on a second run, it went through. I'm keeping this open as there's certainly some non deterministic behavior at play here.

**Comment by chapmanb** [comment]
Luca;
Is it possible you had an old cached `tmpbcbio-install/cloudbiolinux` for the first run and used a new one of the second run? `sambamba` got migrated into the main homebrew and builds from scratch, so we now use a `sambamba-binary` build. If you were trying to install `sambamba` this could be from an older CloudBioLinux before the update.

Hope this explains it.

**Comment by lbeltrame** [comment]
Looks like it was the case. Closing.
