### ISSUE TITLE
RFE: Allow setting GATK and similar programs (toolplus) without updating bcbio-nextgen

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#750]
Currently ``--toolplus <tool>`` requires a full upgrade via ``bcbio_nextgen.py upgrade``. Sometimes this is not desirable (network issues, or temporary breakage). It would be nice to set data without having to upgrade (or if it's already doable, document how).

**Comment by chapmanb** [comment]
Luca;
Thanks for the suggestion. I decoupled this so you can now run:
```
bcbio_nextgen.py upgrade --toolplus gatk=/path/to/GATK.jar
```
and it'll only do that update. Hope this works for what you need.
