### ISSUE TITLE
Problem installing pipeline: Statistics Descriptive

### ISSUE THREAD

**Issue by nuin** [chapmanb/bcbio-nextgen#758]
Trying to install on a  new Mac system we got here and found this error:

```
-> Working on Statistics::Descriptive
Fetching http://www.cpan.org/authors/id/S/SH/SHLOMIF/Statistics-Descriptive-3.0608.tar.gz ... OK
Configuring Statistics-Descriptive-3.0608 ... OK
Building Statistics-Descriptive-3.0608 ... FAIL
! Installing Statistics::Descriptive failed. See /Users/nuin/.cpanm/work/1423765811.21092/build.log for details. Retry with --force to force install it.

Fatal error: local() encountered an error (return code 1) while executing '/usr/local/bin/cpanm -i --notest --local-lib=/usr/local 'Statistics::Descriptive''

Aborting.
local() encountered an error (return code 1) while executing '/usr/local/bin/cpanm -i --notest --local-lib=/usr/local 'Statistics::Descriptive''
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 255, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/usr/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

Checking the log file, the error occurred on creating a man dir

```
ERROR: Can't create '/usr/local/man/man3'
mkdir /usr/local/man/man3: Permission denied at /System/Library/Perl/5.18/ExtUtils/Install.pm line 469.
```

In my case the solution was to manually create the directory, and chmod giving access to the group and my user. After, just run the command by itself, installation was fine and re run the pipeline installation afterwards.

**Comment by nuin** [comment]
Just got a similar error with Active::Tor, this case the man directory was man1. Identical solution to the problem above.

**Comment by roryk** [comment]
Hi Paulo,

Sorry about that— the installer doesn’t work on OSX, there are a lot of third party tools that would need to be fixed to work on OSX so it isn’t feasible to fix all of them, it probably will never work on OSX. We have been working on a Docker based approach but that has some issues on OSX too:

https://github.com/chapmanb/bcbio-nextgen-vm#mac-osx-docker-support <https://github.com/chapmanb/bcbio-nextgen-vm#mac-osx-docker-support>

Right now the best recommendation we have for running it on OSX is to install it into a virtual machine running Ubuntu using Vagrant.  

Best,

Rory

**Comment by roryk** [comment]
Hi @nuin,

Going to close this to cut down on our open issues, please reopen it if you can't get it working using a Vagrant VM too and we'll see what we can do to get you going. Thanks for posting the issue, sorry our solution optimal.

**Comment by nuin** [comment]
@roryk That's fine, I have a vagrant VM on another box which was having issues, now solved, and I will stick to that type of deployment.
Thanks

**Comment by roryk** [comment]
@nuin,

Great-- let us know if you run into any more troubles, thanks for following up.
