### ISSUE TITLE
VEP annotations are not loaded

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#766]
Perhaps related to #765, I get errors like

````
: WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
````

I have no idea if it's harmless or real. I should be up to date on everything.

**Comment by lbeltrame** [comment]
I still got over a run I did this today, but I've yet to check the final VCFs to see how they are.

**Comment by lbeltrame** [comment]
Annotations are loaded, at least the ones that interest me. ;) So closing. I'll reopen if needed.

**Comment by chapmanb** [comment]
Luca;
I believe there was an issue when preparing the split multi-allelic inputs which should be fixed in the latest development version. More details here:

https://github.com/chapmanb/bcbio-nextgen/issues/773#issuecomment-76159124

Hope this fixes it for you. Thanks so much for looking into this.
