### ISSUE TITLE
combining batches from joint caller

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#767]
I have multiple batches of samples called using the joint freebayes pipeline. I haven't deleted any of the intermediate files including alignments. Is there a recommended mechanism to consolidate the joint calling across all the batches? The goal is to simplify joint calling as small batches of samples are received.

**Comment by chapmanb** [comment]
Daryl;
Thanks for the questions. The approach is still the same as we discussed in #727:

https://github.com/chapmanb/bcbio-nextgen/issues/727#issuecomment-70874140

So you shouldn't need intermediates, just the final batch VCF files and the individual alignment BAM files for FreeBayes recalling. For GATK gVCF combining we don't have a similarly clean way to do this N+1 calling right now fom a lot of gVCF intermediates, and it would take some development work. Hope this helps.

**Comment by dwaggott** [comment]
Senior moments. Thanks.
