### ISSUE TITLE
output directory clarification

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#768]
Is the `tmp` directory for tx or intermediate directories such as align/provenance/bedprep/regions/freebayes/gemini/qc or both?  

I'd like all the intermediate files located in the common project directory however tmp files can stay on local node scratch. For joint calling I'm assuming I need to keep some of the intermediate files to enable adding additional samples.

**Comment by chapmanb** [comment]
Daryl;
The `tmp` directory is for transactional files only. All of the intermediates get stored inside the work directory. So, the short answer is that it works as you indicated. Hope this helps.

**Comment by dwaggott** [comment]
All the intermediate files are being put in the directory of the calling
shell/batch script i.e. one up from the project directory. How do I get
them into the project directory?

**Comment by chapmanb** [comment]
Daryl;
Sorry, I'm a bit confused here. Can you be more specific about which intermediates you're not finding in the right place, and where they are? In bcbio there are essentially 3 directories:

- The work directory, which contains all the intermediates. This is wherever you run bcbio_nextgen.py from.
- The final directory, where the final outputs get transferred on completion. The idea is that you can then clean up the work directory to remove disk space taken by intermediates.
- The temporary directory, where files are in while being processed. This prevents writing half finished files to the work directory.

Thanks

**Comment by dwaggott** [comment]
Apologies, for the lack of clarity. I rush.

I think you answered the question. I'm running bcbio_nextgen.py from the directory above the one created when I downloaded the pipeline template and setup the config/yaml with all the samples. I assumed the output would be relative to the yaml file not the calling script.

I'll call the script explicitly from the expected work directory.

```
### bcbio directory
$ pwd
~/bcbio

### A number of pipeline scripts 
$ ls *sbatch
merge_fastqs.sbatch  call_variants_fb.sbatch  call_variants_gatk.sbatch  

### A number of project directories that only contain the config file
$ tree project_*
project_n143-fb
├── config
│   └── project_n143-fb.yaml
└── work
project_n143-gatk
├── config
│   └── project_n143-gatk.yaml
└── work

### intermediate files
$ ls -d */
align/  bedprep/  checkpoints_parallel/  freebayes/  gemini/  ipython_logs/  log/  log_slurm/  project_n143-fb/   project_n143-gatk/  provenance/  qc/  regions/  tx/

```
