### ISSUE TITLE
Auto adding vrn_file to yaml config

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#769]
I'm trying to create a yaml file in the format referenced in #767 for a large number of samples.

When using a sample metadata csv would it be possible to:

1. recognize the column header `vrn_file` and add it to correct location in the yaml i.e. not under metadata

2. recognize key word column headers for fastqs/bams and add them to the correct location in the yaml. This is just convenience given you can do it by passing them directly to the bcbio-nextgen script.

**Comment by chapmanb** [comment]
Daryl;
Thanks for the great suggestion. I pushed a fix that will handle both of these cases during templating. Let us know if you run into any other issues or problems.

**Comment by dwaggott** [comment]
Nice!

**Comment by dwaggott** [comment]
Not sure if it's working as expected. If I specify `files` in the metadata file do I still need to pass in the bams/fastqs in the bcbio-nextgen command? Not passing the bams/fastq didn't result in the sample templating and including them along with the `files` column gave errors.

**Comment by chapmanb** [comment]
Daryl;
Sorry, you're right. You'll still need to have them on the command line for `files`. Thinking more about it it's probably best to leave it as is instead of trying to support two parallel ways of doing the same thing. Hope this works okay for you and the other functionality works as expected.
