### ISSUE TITLE
RTG pedigree pipeline

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#770]
I've got someone who is interested in abstracting an RTG pedigree pipeline across multiple architectures.  I'd love to try and do this via bcbio or an implementation of the common workflow language. 

Is bcbio ready for user contribution of pipelines?

**Comment by dwaggott** [comment]
Just close this. I realize you answered it in #738.

**Comment by chapmanb** [comment]
Daryl;
Right, we'd be happy to support RTG baked into bcbio but CWL support isn't ready yet so it would require waiting until we had that in place if you want to go that route. We do have a pretty standard interface for adding variant callers:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/code.html#variant-caller

if you want to go that route. We're happy to have community supported tools built into bcbio. That is the primary goal of the library. #738 was emphasizing that there are probably better choices if you're looking for a tool to parallelize a custom workflow for internal use. Hope this helps.

**Comment by dwaggott** [comment]
Looks like I could get it running that way. The only trick would be
figuring out how to pass pedigree / trio relationships. I'll test a bit.

**Comment by chapmanb** [comment]
Daryl;
We'd be open for suggestions about the best way to do the pedigree information and happy to support this. My general thoughts are:

- Pass in as a metadata target `pedigree`.
- Use a standard format like plink `fam` format for the inputs.

Ideally we've be able to parse `fam` files directly as inputs to the template functionality and add `batch` and `sex` information from the file directly to the input YAML. Then RTG would recieve the trio/family to process and can extract over family relationship information directly from the `fam` file. Happy to hear other suggestions/approaches. Thanks again for looking at this.
