### ISSUE TITLE
conmem

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#772]
I've used `bcbio_nextgen.py upgrade -u development` and am trying to increase the controller memory to 6g (#741) after it failed on 350 samples. It doesn't look to be working as expected.

```
# calling script
bcbio_nextgen.py  --timeout 10000 --retries 2 ../config/project_aric_euro-fb-joint.yaml  -t ipython -n 400 -q normal -s slurm -r "timelimit=2-00:00:00;conmem=6"
```

```
# created SLURM_controller* code
#SBATCH --mem=4000
#SBATCH --conmem=6
/share/PI/euan/apps/bcbio/anaconda/bin/python -E -c 'import resource; cur_proc, max_proc = resource.getrlimit(resource.RLIMIT_NPROC); target_proc = min(max_proc, 10240) if max_proc > 0 else 10240; resource.setrlimit(resource.RLIMIT_NPROC, (max(cur_proc, target_proc), max_proc)); cur_hdls, max_hdls = resource.getrlimi

```

**Comment by roryk** [comment]
Hi Daryl,

It kind of looks like ipython-cluster-helper didn't get upgraded. If you do:

```
/share/PI/euan/apps/bcbio/anaconda/bin/pip freeze | grep ipython-cluster-helper
```

does it show 0.4.0?

**Comment by dwaggott** [comment]
```

$ /share/PI/euan/apps/bcbio/anaconda/bin/pip freeze | grep
ipython-cluster-helper

ipython-cluster-helper==0.4.0

```

**Comment by dwaggott** [comment]
Yes seems so.

```
$ /share/PI/euan/apps/bcbio/anaconda/bin/pip freeze | grep
ipython-cluster-helper

ipython-cluster-helper==0.4.0
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the problem. Could you specify the resources separately:
```
bcbio_nextgen.py ... -s slurm -r "timelimit=2-00:00:00" -r "conmem=6"
```
The semi-colon syntax was partially supported for back compatibility but doesn't work in this special case. Generally we're trying to avoid using it at all and have only one correct way to specify resources. I noticed a remaining example like that in the documentation so removed it. If you find any other documented places that contain that syntax let us know and happy to remove that confusion. Hope this works for you.

**Comment by dwaggott** [comment]
Excellent!
