### ISSUE TITLE
comparing joint vs pooled calling

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#774]
I took a quick look at the vcf and there seems to be 2x variants in the joint vs pooled analysis runs (freebayes, n=143 exomes). Does that seem expected?

I'm tempted to try a hybrid approach. Something that calls small batches of samples via the pooled approach before doing the joint aggregation. The batches could be seeded with a set of common reference samples.

**Comment by chapmanb** [comment]
Daryl;
There are 2x more total variant positions when you run samples joint versus fully pooled (all 143 together)? That doesn't seem right, I'd expect them to be closer than that. The joint approach shouldn't be tons more sensitive than a pooled approach. If you can isolate and provide some differences happy to offer suggestions.

The pooled, then joint approach is what we've done previously for large samples. We called families in batches, then combined and re-called together for the final squared off joint set.

Hope this helps.
