### ISSUE TITLE
RFC: load sample information in GEMINI when doing paired tumor-normal analysis

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#776]
I say "RFC" because I wonder about the cost-benefit ratio, and so I'd like to hear some comments. THis is mostly so that one could use GEMINI's new features like `set_somatic`. However, that may be unnecessary given that the callers already do this screening. 

At a practical level that means building a PED file to load into GEMINI with the two phenotypes (normal-tumor) when the database is being loaded, or afterwards. 

Thoughts?

**Comment by rronen** [comment]
Just to add my 2c: even not using new features like `set_somatic`, this would be cool as it makes it possible to use GEMINI's wildcard query syntax based on sample attributes. E.g., this becomes possible when loading with a PED file that indicates tumor/normal phenotype:
```
"(gt_alt_depths).(phenotype==2).(>10).(any) and (gt_alt_depths).(phenotype==1).(<3).(all)"
```
*rows where ALT is covered by more than 10 reads in any tumor and less than 3 reads in all normals

At the same time, not having it is not too bad -- I think it can be done post-hoc without reloading the DB (something like `update samples` given a PED file that matches the samples in the database)

**Comment by chapmanb** [comment]
Luca and Roy;
Great points, thank you. We definitely want to make it as easy as possible to do GEMINI queries. I added this in so bcbio will now load a PED file with the family, sample, gender and phenotype information from the metadata. It should be directly queryable from GEMINI as you describe for new databases. Let us know if you run into any problems at all and thanks again for the suggestions.

**Comment by lbeltrame** [comment]
Great stuff, Brad! Even more custom code I'm using internally that can go now to the dust bin... ;)

**Comment by rronen** [comment]
+1 @lbeltrame. Thanks for this Brad! This will be great to have.
