### ISSUE TITLE
Rename regions in BED files so that they're unique

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#780]
Given robinandeer/chanjo#125, the name field of the BED file needs to be unique per row. Some commercial kits repeat the gene name, hence this can break things during the run.

**Comment by chapmanb** [comment]
Luca;
bcbio does try to do this right now:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/coverage.py#L23

but perhaps we missed something. Were you getting non-unique names running inside of bcbio or running manually outside of it?

**Comment by lbeltrame** [comment]
I just found this issue when running the pipeline today (but I haven't updated in the past week).

**Comment by lpantano** [comment]
Closing this since I am guessing there are not issues with the current version.

thanks a  lot!
