### ISSUE TITLE
bcbio_nextgen update error for sambamba

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#782]
Hi Brad,

When I update bcbio_nextgen to latest version, I used:

bcbio/anaconda/bin/bcbio_nextgen.py upgrade -u development --tools --data

An error occurred for:

ValueError: Failed to install brew formula: sambamba-binary

I checked the command:

export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/data1/bcbio_tools/lib/perl5:${PERL5LIB} && /data1/bcbio_tools/bin/brew install --env=inherit   sambamba-binary

The error caused by dropbox website could not access, so I download sambamba_02_02_2015 by hand, my question is how can i link the sambamba_02_02_2015 to brew install?

**Comment by chapmanb** [comment]
Sorry about the issue. The dropbox download link was meant to be temporary but it might be experiencing intermittent issues. I added a cached version of this to S3 and updated the formula, so hopefully it will work cleanly if you re-run the installation. Alternatively, you can copy your manually download version into the homebrew cache directory and re-run:
```
cp sambamba_02_02_2015 ~/.cache/Homebrew/sambamba-binary-0.5.2a-2015-02-02
```
Hope this helps resolve it.
