### ISSUE TITLE
bcbio_nextgen vs churchill 2

### ISSUE THREAD

**Issue by junchend** [chapmanb/bcbio-nextgen#783]
Hi Brad,

I noticed that a new software named "churchill" released for NGS data analysis, and it claimed that highest speed than other similar pipeline.

http://churchill.nchri.org/

So what's your opinion? Can I improve the parameters of bcbio_nextgen to speed up?

**Comment by chapmanb** [comment]
Thanks for the discussion. I do know about the paper and am talking with the authors about doing an up to date benchmark. They passed along the exact files used but we still need to find time to run it. It is great work and nice to see these comparisons. Unfortunately there was a mistake in setting up the bcbio configuration for their single sample run. They left the configuration for bwa at the default (16 cores) instead of updating it to the system parameters (32 cores). This accounted for the major speed difference. I provided a bit more detail in this discussion on biostars: 

https://www.biostars.org/p/129293/#129339

Thanks much.

**Comment by MagpiePKU** [comment]
We tested the Churchill pipeline and it was no faster than a home made 
shell script for an exon seq. Also there were bugs in the pipeline such 
that initially we got problems to run it. When we finally got it 
through, we selected GATK_HC but for unknown reason it still used 
GATK_UG (note: the home made script used GATK_HC, and took similar time).

On 03/11/2015 04:49 PM, Brad Chapman wrote:
> Thanks for the discussion. I do know about the paper and am talking with
> the authors about doing an up to date benchmark. They passed along the
> exact files used but we still need to find time to run it. It is great
> work and nice to see these comparisons. Unfortunately there was a
> mistake in setting up the bcbio configuration for their single sample
> run. They left the configuration for bwa at the default (16 cores)
> instead of updating it to the system parameters (32 cores). This
> accounted for the major speed difference. I provided a bit more detail
> in this discussion on biostars:
>
> https://www.biostars.org/p/129293/#129339
>
> Thanks much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chapmanb/bcbio-nextgen/issues/783#issuecomment-78224970>.
>

-- 
No fate but what we made

Zhang, Yi
Room 318, Wang Ke Zhen Building
School of Life Sciences, Peking University
5 Yiheyuan Road
Beijing 100871
China, People's Republic of

**Comment by junchend** [comment]
Thanks for the response, I am running 49 samples which generated by WGS, the size of each sample was about 75G, from the beginning about 30 days passed. 

Now the process is ensmeble combining:

java -Xms25g -Xmx50g -Djava.io.tmpdir=/tmp -jar /usr/local/share/java/bcbio_variation/bcbio.variation-0.2.2-standalone.jar variant-ensemble /AB/work/ensemble/work/CC/config/CC_WGS-ensemble.yaml /usr/local/share/bcbio-nextgen/genomes/Hsapiens/hg19/seq/hg19.fa /AB/work/ensemble/CC_WGS-ensemble.vcf /AB/work/gemini/CC_WGS-gatk.vcf.gz /AB/work/gemini/CC_WGS-freebayes.vcf.gz 

The log info:

2015-03-11 11:55:54,649 [INFO ] State :begin :: {:desc "Starting variation analysis"}
2015-03-11 11:55:54,748 [INFO ] State :clean :: {:desc "Cleaning input VCF: combo"}
2015-03-11 11:55:54,749 [INFO ] State :merge :: {:desc "Merging multiple input files: combo"}
2015-03-11 11:55:54,749 [INFO ] State :prep :: {:desc "Prepare VCF, resorting to genome build: combo"}
2015-03-11 11:55:54,888 [INFO ] State :normalize :: {:desc "Normalize MNP and indel variants: combo"}

2015-03-11 11:59:45,317 [INFO ] State :clean :: {:desc "Cleaning input VCF: gatk"}
2015-03-11 11:59:45,317 [INFO ] State :merge :: {:desc "Merging multiple input files: gatk"}
2015-03-11 11:59:45,318 [INFO ] State :prep :: {:desc "Prepare VCF, resorting to genome build: gatk"}
2015-03-11 11:59:45,455 [INFO ] State :normalize :: {:desc "Normalize MNP and indel variants: gatk"}
2015-03-11 12:03:33,821 [INFO ] State :clean :: {:desc "Cleaning input VCF: freebayes"}
2015-03-11 12:03:33,821 [INFO ] State :merge :: {:desc "Merging multiple input files: freebayes"}
2015-03-11 12:03:33,822 [INFO ] State :prep :: {:desc "Prepare VCF, resorting to genome build: freebayes"}
2015-03-11 12:03:33,973 [INFO ] State :normalize :: {:desc "Normalize MNP and indel variants: freebayes"}

2015-03-11 12:08:03,721 [INFO ] State :combine :: {:desc "Creating merged VCF files for all comparisons"}
2015-03-11 12:08:03,725 [INFO ] State :annotate :: {:desc "Annotate VCFs with metrics"}
2015-03-11 12:08:03,727 [INFO ] State :filter :: {:desc "Post annotation filtering"}

And keep for 5 hours like above.

My computer is not a cluster, something like a local machine, but with 1T memory and 64 intel cores

And I noticed bcbio_nextgen could not use all the resource.

So Brad, do you have some suggestion to speed up ?

**Comment by junchend** [comment]
Thanks MagpiePKU, I just want to evaluate these two pipeline.

According to your results, churchill is not so good as it claimed.

With the development of NGS machine, the analysis pipeline need to keep up with size of the dataset.

**Comment by chapmanb** [comment]
In general you won't see a big improvement in run times for larger infrastructures versus custom shell scripts on smaller genome sizes. Most of the speed advantages come at scale. The other advantage is sharing the work of coding/improving/validating the pipeline, which is where bcbio tries to focus (while also being able to scale).

@junchend Ensemble calling is resource intensive and not parallelized over multiple cores. This is in addition to the overhead of running multiple variant callers. It is really intended for smaller projects or places where you feel like the small improvement in calling is worth the time investment. For your use case, I would suggest calling with a single variant caller: FreeBayes or GATK HaplotypeCaller. This will give you good results without needing to wait for the longer ensemble method. Hope this helps.

**Comment by junchend** [comment]
Thanks Brad, I will accept your suggestion.

**Comment by roryk** [comment]
Closing this issue out as it is pretty old and seems resolved.
