### ISSUE TITLE
RFC: Summary on all samples from a run

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#785]
As the subject says, would it be feasible to have some summary stats on the samples as a whole?

**Comment by chapmanb** [comment]
Luca;
Right now the `project-summary.yaml` file contains stats for each of the samples, but we don't try to provide a final report on that within bcbio. Our thought process is that this is something that could happen downstream of bcbio, since you'll often want to combine/report/query results from multiple runs, so the YAML file is meant to make it easy to parse and upload into a downstream system. Would custom parsing of this file work for you right now?

**Comment by lbeltrame** [comment]
> upload into a downstream system. Would custom parsing of this file work for
> you right now?

That's what I'm doing right now, indeed. I wonder though (if GEMINI enabled) 
to add a few other statistics to each sample that can be gathered by "gemini 
stats" like --vars-per-sample.

OTOH this could increase complexity (also stuff like RNA-seq is different) and 
perhaps it's better to do this downstream (what I'm doing right now).

In other words I'm not necessarily married to the idea, just gathering 
thoughts. ;)

**Comment by chapmanb** [comment]
Luca;
We could definitely add additional GEMINI only stats to this. There is a function that does exactly this right here:

https://github.com/chapmanb/bcbio-nextgen/blob/a30736975bac8612512d9a41fb2f409988f13279/bcbio/pipeline/qcsummary.py#L580

if you want to update it with additional statistics of interest to help in summarizing. Thanks for the ideas.

**Comment by lbeltrame** [comment]
> https://github.com/chapmanb/bcbio-nextgen/blob/a30736975bac8612512d9a41fb2f4
> 09988f13279/bcbio/pipeline/qcsummary.py#L580

This does mostly what I want, however I don't see it being run for somatic 
variants. Am I correct in this regard?

**Comment by chapmanb** [comment]
Luca;
Apologies, you're right. The logic on this was off and it was being skipped. I re-enabled it with the current output structure that handles multiple variant callers, and it should now provide stats. Please let us know if adding any other values would be useful. Thanks again for digging into this.

**Comment by lbeltrame** [comment]
Thanks, Brad. I have a new run scheduled soon, so I'll be able to tell you shortly (hopefully!) if this is what I need or if I need to add a few things myself.

**Comment by roryk** [comment]
Hi Luca, hope you are well. I think we fixed this issue, please reopen if it turns out we didn't. Thanks!
