### ISSUE TITLE
Connection to Frankfurt S3 buckets with boto fails due to S3 region not being set

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#786]
Dear Brad and others,

I am trying to generate an analysis configuration file running `bcbio_nextgen.py -w template  s3://BUCKETNAME/TEMPLATEFILE.yaml s3://BUCKETNAME/SAMPLEDESCRIPTION.csv`and receive a `boto.exception.S3ResponseError: S3ResponseError: 400 Bad Request`. I am using the latest bcbio and boto 2.36.0. The bucket is located in the new S3 Frankfurt datacenter in the `eu-central-1` region, access to which [seems to be problematic using boto](https://github.com/boto/boto/issues/2741). 

After some digging around it appeared to me as if boto cannot connect to buckets in the Frankfurt location using `import boto; s3 = boto.connect_s3(); s3.get_bucket('BUCKETNAME')`. Rather, `import boto; s3 = boto.s3.connect_to_region('eu-central-1'); s3.get_bucket('BUCKETNAME')` seems to be required for a valid connection. 

May I suggest that someone of the bcbio dev team validates this finding and adds the option to set a S3 region to `bcbio_nextgen.py` and the `upload` section of the yaml files, perhaps using a (slightly non-standard) `BUCKETNAME@REGIONNAME/KEY` syntax in the S3 URL that is then parsed in `bcbio.utils`? Alternatively one would have to wait until either boto or Amazon fixes the issue, but that didn't happen at least in the last month or so, and until then I and other central Europeans are left hanging.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the feedback and debugging the underlying issue. We definitely want to better support non-us-east use cases. Apologies, the current backend was not well abstracted so we'll first work on improving that, and then can add support for this. I checked in some initial work to abstract it:

https://github.com/chapmanb/bcbio-nextgen/commit/a30736975bac8612512d9a41fb2f409988f13279

and will continue to work on it. For specifying the region, I'll plan to use either the region-name specified in an s3 URL or the `AWS_DEFAULT_REGION` environmental variable, or fall back to us-east-1 if neither is set.

I'll report more when we have this ready to test but wanted to let you know that we're working on it. Thanks again.

**Comment by schelhorn** [comment]
Great, thanks a lot for the good work. Since you are refactoring the S3 code anyway: I get a `gof3r error: 400: "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."`from bcbio. After some research it seems as if [gof3r does not support  Version 4 AWS signatures](https://github.com/rlmcpherson/s3gof3r/issues/45) (AWS4-HMAC-SHA256) since December 2014, which basically means it is useless for the Frankfurt region (or any other new AWS region, for that matter). So perhaps you could allow automatically downgrading to boto or s3cmd in bcbio for people using the Frankfurt region (or where gof3r throws the exception above)? I realize that gof3r is much more elegant and performant, but the author does not seem to be particularly fast with fixing bugs and I do not speak Go myself. I can open a new issue for that if you like.

**Comment by schelhorn** [comment]
Thanks, the fallback to `aws s3` and the `upload/region` option in the sample yaml seem to work perfectly in the current master - good job. However, I have a remaining issue connected to S3 downloading. I currently specify the paths to the `variant_regions` in the sample yaml as bed files on S3. bcbio correctly tries to copy them from S3 into the local work directory under `./WORKDIR/inputs/BUCKETNAME/BUCKETDIRS/tx/TMPDIR` using `aws`, where TMPDIR is the usual random string for temporary directories. However, only `./WORKDIR/inputs/BUCKETNAME/BUCKETDIRS/tx`seem to exist on my system at the time the `aws` download command is issued. Since `aws` does not generate the parent directories of its output it fails with `OSError: [Errno 2] No such file or directory`. So basically we would bcbio to ensure that the full temporary path including `TMPDIR` exists (`mkdir -p`-style) before the `aws` copy process is started.

**Comment by schelhorn** [comment]
Oups - I take that back. The temporary directory not being there was a side effect of the transaction manager who removes that directory upon earlier failures. The `OSError: [Errno 2] No such file or directory` was referring to `aws` not being installed in my bcbio installation under `BCBIOLIB/anaconda/bin/aws`. Which is strange, since I did a full update of bcbio before. I will investigate this further.

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the problems, most of the parts are in place but I've still been working on testing them on AWS. How are you running bcbio on AWS? With bcbio_vm and docker (https://bcbio-nextgen.readthedocs.org/en/latest/contents/cloud.html) or with a custom setup? With the docker setup everything should hopefully be happening inside docker and the latest build (from 6am ET this morning) should have it. If it's something else happy to help debug it. Thanks again for testing this out.

**Comment by schelhorn** [comment]
Everything works well now, also with vanilla `.bed` files. I suspect that did not have the very latest release from 6 hours ago but the one released some minutes earlier. Apologies for the confusion.
