### ISSUE TITLE
upgrade fails

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#788]
Problem seems to be related to conda (not bcbio).

Here's the output / traceback.

Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
.Could not connect to https://repo.continuum.io/pkgs/pro/linux-64/
.Could not connect to https://repo.continuum.io/pkgs/free/noarch/
.Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
.
Error: No packages found in current linux-64 channels matching: numpy

You can search for this package on Binstar with

    binstar search -t conda numpy

You may need to install the Binstar command line client with

    conda install binstar
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 50, in upgrade_bcbio
    _update_conda_packages()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 192, in _update_conda_packages
    subprocess.check_call([conda_bin, "install", "--yes", "numpy"])
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/conda', 'install', '--yes', 'numpy']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Par;
Thanks for the report, is this still failing for you? I tried and can't replicate this. I wonder if it was a temporary download or if https://repo.continuum.io/pkgs/free/linux-64/ is blocked from your machine for some reason. Sorry to not have a better idea.

**Comment by parlar** [comment]
You're right, it worked on a different machine and disabling ssl for conda solved the problem.

Thanks,

Pär

**Comment by chapmanb** [comment]
Great, glad it worked for you. Thanks for following up.
