### ISSUE TITLE
Option to keep fastqc zip file

### ISSUE THREAD

**Issue by danhalligan** [chapmanb/bcbio-nextgen#792]
I was wondering whether it would be possible to add an option to bcbio to maintain the fastqc output zip file or otherwise maintain the outputted images from fastqc? Currently, the individual fastqc images are only available embedded within the single output html document.

**Comment by chapmanb** [comment]
Apologies, we've been trying to move in the opposite direction since the single HTML file is much easier to pass along and display. Out of curiousity, why do you have the need for the individual images? Are you reformatting/redisplaying the output? Thanks much for the suggestion and discussion.

**Comment by danhalligan** [comment]
Yep, I'm hoping to be able to redisplay the figures from fastqc (so that it's easier to compare samples side by side). It's not a massive issue however, as the fastqc data file seems to contain all the output data necessary for regenerating the plots.

**Comment by danhalligan** [comment]
Hi, I'm just following up on the above issue as I = noticed in your comments for _run_fastqc that you note: "Handles fastqc 0.11+, which use a single HTML file and older versions that use a directory of files + images. The goal is to eventually move to only 0.11". I was just looking at the latest version of fastqc (0.11.2) and it looks to me at least that the zip file (containing the directory of images, data and html output) is produced as standard? Do you know if there are future plans to stop producing the zip file containing individual images? Naively, I would have thought maintaining the zip file would be more useful than the fastqc_data.txt file so users can access individual images. Without direct access to the images, I'm looking at extracting the pngs from the html, replotting the figures from the data file or perhaps rerunning fastqc after bcbio finishes. All solutions are a little hacky so it would be great if this could be avoided :-)

**Comment by chapmanb** [comment]
Dan -- apologies about the delay getting to this. Guillermo just added this support in the latest development version. The zip file should get created and passed along in the final output directory so you can post-process it downstream. Hope this works for what you need.

**Comment by danhalligan** [comment]
OK great!
