### ISSUE TITLE
bam->fastq -- Error: output file unexpectedly small

### ISSUE THREAD

**Issue by rronen** [chapmanb/bcbio-nextgen#793]
Brad,

In the wild running into this on seemingly valid/non-truncated [1] input bam files -- in the first step converting to fastq. Poking around in the source it looks like in `file_reasonable_size()` ([here](https://github.com/chapmanb/bcbio-nextgen/blob/118b350bdaab9b63a07317b147f1c8d1f36d06a2/bcbio/provenance/do.py)) there's a check if the resulting fastq is less than 1/5 of the input bam. 

I think this is reasonable, but fails in my case due to a particularly verbose/long read-group (on every line in the bam). My guess [2] is maybe gzip (in the fastq.gz) is taking much better advantage of this than the compression used in bam? (resulting in unexpectedly smaller file size). 

[1] both `samtools flagstat` and `samtools view file.bam | tail` produce something reasonable for all files this happens on (see example below) -- please advise if this might miss a bad bam (and there's a better way to check)
```
> samtools flagstat file.bam
132741016 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplimentary
6894944 + 0 duplicates
132741016 + 0 mapped (100.00%:-nan%)
132741016 + 0 paired in sequencing
66487463 + 0 read1
66253553 + 0 read2
131592924 + 0 properly paired (99.14%:-nan%)
132494426 + 0 with itself and mate mapped
246590 + 0 singletons (0.19%:-nan%)
730130 + 0 with mate mapped to a different chr
575360 + 0 with mate mapped to a different chr (mapQ>=5)
```
[2] wild guess, for all I know bam compression is gzip underneath, making this a pretty bad guess

Very tangentially related: I noticed just one of the converted fastq files (xxx-1.fq.gz, but not xxx-2.fq.gz) was transactional. The other stuck around in the `align_prep` directory despite the failure. Digging around the source to find the conversion command (running manually for now to bypass this) I think I may have stumbled onto the reason [here](https://github.com/chapmanb/bcbio-nextgen/blob/a30736975bac8612512d9a41fb2f409988f13279/bcbio/broad/picardrun.py) (`fastq_two` not getting it's own `file_trscation`?)

**Comment by rronen** [comment]
As a quick & dirty workaround I changed `ratio = 5.0` to `ratio = 7.0` in`file_reasonable_size()` function and this seems to do it. Though I suspect something more general might be in order :)

**Comment by chapmanb** [comment]
Roy;
Thanks for this. The check is really just a sanity check and 5.0 is picked arbitrarily so happy to adjust to be sure it fits for your case. If the BAMs have huge read groups these won't be present in the output fastq files so that makes sense they'll be smaller.

The transactional issue is not too big of a problem since it will always re-check on the first input, which only gets copied over on completion, so the second will be re-done in partially finished cases. So it won't continue with partially completed inputs, which is the goal of the transactions.

Thanks again for all this.

**Comment by rronen** [comment]
Great!

Right, I see what you mean regarding the transaction -- thanks for explaining that.
