### ISSUE TITLE
Kraken installation fails due to hardcoded version path

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#796]
After upgrading bcbio to install kraken with `bcbio_nextgen.py upgrade -u development --tools --data --toolplus kraken` the installation of kraken fails due to a hardcoded version path in in `bcbio/install.py`. In line `474` it says `shutil.move(os.path.join(kraken, "minikraken_20140330"), os.path.join(kraken, "minikraken"))`; however, the kraken archive seems to contain a newer `minikraken_20141208` instead, resulting in an `IOError: [Errno 2] No such file or directory: 'PATH_TOBCBIO_LIB/genomes/kraken/minikraken_20140330'`. Perhaps one could do the directory move on a wildcard basis instead?

**Comment by lpantano** [comment]
Hi @schelhorn, thanks so much to find this. I quick fix with the new date, but I am working to get a smarter update function. Will let you know when I get it, but meanwhile it should work with the last update.
thanks!

**Comment by lpantano** [comment]
I update with a new function that will check the date of the tar file and the current kraken folder and will update if it is older. d59e2b1
If there is any problem, let me know. thanks!
