### ISSUE TITLE
Sambamba is programmatically disabled for name-sorting BAM files

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#800]
In [`bcbio/bam/__init__.py`](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/__init__.py#L314) in the function `sort()` it says in line `314`:
```
if not utils.file_exists(sort_file):
  sambamba = _get_sambamba(config)
  sambamba = None
  ...
```

effectively deactivating the use of sambamba and thus falling back to single-threaded samtools. Is this expected behaviour?

**Comment by chapmanb** [comment]
Good catch. Thank you. It looks like a mistake but @roryk made the change so would love to have him weigh in:

https://github.com/chapmanb/bcbio-nextgen/commit/955ee432ca54b61ace67e07454fc72bd1df0040c

**Comment by roryk** [comment]
We were having some issues with sambamba sorting very large files, so I disabled it, but I think the issue has since been fixed upstream, so it should be good to go again. Thanks for catching it.
