### ISSUE TITLE
import into gemini fails for some variants

### ISSUE THREAD

**Issue by parlar** [chapmanb/bcbio-nextgen#801]
I upgraded to bcbio-nextgen,0.8.8a0-b2fb8ba from 0.8.4. Now the import of variants into gemini sometimes fails. The variant is there (chr/start/end/ref/alt) but gene symbol, impact, ref transcript and perhaps other fields are empty (=None). Most of the imported variants seem ok, however.

I also noted an example where the genotype field was incorrect (ref = A, alt = AAAC but gt = AAAC|AAAC).

Kind regards,

Pär

**Comment by chapmanb** [comment]
Pär;
Sorry about the issues. What version of GEMINI are you running? The latest version (0.12.2) has a lot of fixes for ALT allele support, so it might be worth updating that as well by adding `--tools and --data` to your bcbio upgrade command. If you still have issues and could pass along some examples of small VCFs that fail I'd be happy to dig into it more. Sorry again about the problems.

**Comment by parlar** [comment]
Sorry for leaving this hanging, I've had too much to do lately. I'll take a closer look at this asap.

**Comment by lpantano** [comment]
Closing this since probably new versions of gemini handles better this.

let us know if it happens again.

thanks
