### ISSUE TITLE
Explant disambiguation can be parallelized

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#804]
I noted that explant/xenograft disambiguation (triggered by `disambiguate` in the config yaml) is currently undertaken on a single core, which doesn't seem to be very scalable. However, this processing step could easily (at least conceptually) be parallelized using the split-combine aproach that is currently applied in read mapping (if `align_split_size` is set). 

Since disambiguation is relying on comparing alignments against references of source (human) and host (mouse) species which are based on the same set of mapped reads (as identified by query name), it would be perfectly fine to use each output chunk of the split read mapping (identical chunks for source and host species mappings, of course), order them by query name, and feed them into the disambiguation script. Since each chunk of aligned reads is based on the same input reads (although mapped to different reference genomes), and the disambiguation script does no global comparison across all reads, disambiguation can easily work on the single chunks without changes to the disambiguate script.

After processing, the implicitly name-sorted output chunks of the disambiguate script would have to be merged and then position-sorted as before. The only additional change would have to implemented in the tab-delimited summary file (containing counts for quality control) that the disambiguate scripts generates: these counts would then be based on each chunk, and would have to be summed up across all chunks.

If this change is comparatively easy to implement I'd appreciate someone to undertake it since disambiguation is currently a limiting factor in our analyses, especially for whole-genome data.

**Comment by mjafin** [comment]
Hi @schelhorn, 
Many thanks for the feedback on disambiguation. It's great to hear other people are using it too. To be perfectly honest, disambiguation hasn't received the TLC it needs. We also implemented the algorithm in C++ (https://github.com/mjafin/disambiguate) with significant single thread speedups but it never got integrated into bcbio. Out of academic interest, may I ask what kind of samples you are processing? Xenografts, primary tumour explants, ...?

Parallelising disambiguation further would require splitting the name sorted bam files into roughly equal blocks, primary species first and then the disambiguation species based on matching read names. If you have any ideas around how to do it in practice (like a samtools one-liner) so that the overhead of splitting doesn't eat into the speed up gains, that'd be most welcome. I can't promise any timelines of when I could look into implementing the parallelisation but I'll do my best to get this rolling.

**Comment by chapmanb** [comment]
Sven-Eric and Miika;
Thanks for the ideas and following up on this. Parallelizing by region with the existing infrastructure as initially suggested is going to be tricky as the alignment parallelization happens separately from disambiguation to avoid making the alignment step too complex. I like the idea of trying to use the faster C++ approach. We have a wrapper in bcbio but have never really tested it out:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/disambiguate/__init__.py#L91
 
I'd defer to Miika about how best to handle this as I've never run a real disambiguation sample so don't have much experience on run time expecations. Thanks so much for helping with this.

**Comment by schelhorn** [comment]
Miika and Brad,

thanks for chiming in. We are running quite a number of PDX exomes (and some whole genomes) for practicaly all commercially available tumor explant mouse models for an international consortium. I believe more people will use that kind of data in the future since it probably will be used in the mid-term as a standardized assay for pharma research as well as for personalized medicine (explant your personal tumor to ten mice and run combination treatments against them, observe tumor response, then take the treatment with the highest efficacy back to the patient). 

It's good that there is a C++ implementation and I value the work that went into ot, but a constant speed-up of two or five (I image that's the range) isn't cutting it for WGS data - we would really need something that scales with the number of available compute nodes. (As a side note, we also have our own Python version of a PDX cleaning algorithm which solves some tricky special cases and is based on our experience with the data. I currently sideload it into bcbio by emulating the interface of the disambiguate script. But of course that's entirely my problem. I'll try hard to convince management to free the code for bcbio).

However, I would like to make my point about parallelization again since I suspect that I did not manage to communicate it well. We do not require any parallelization _by region_ of the alignment, or any re-splitting of the the alignments into equal blocks. The chunks that go into the disambiguation algorithm are fully defined by the FASTQ _input_ chunks, regardless of where they map to. Since the current chunking approach just takes lines from the FASTQ files (in a IO-smart manner, of course) and produces BAMs from them, we could directly feed these BAM chunks into the disambiguation script, no change other than name-sorting required. Also, since the inputs for the two alignments (one against human, one against the explant host) are based on the same FASTQ inputs, and the same chunking parameters apply, it is already guaranteed that two chunks `n` of alignments (one against each reference) contain the same aligned reads. So you basically just take each pair of aligned chunks independently, feed them into disambiguate, and merge the resulting output chunks. 

I realize that this may not be too easy to pull of in the code since alignment may be piped into the postprocessing etc, but it is really quite simple conceptually if directly applied to the aligned chunks prior to any alignment postprocessing (other than name-sorting). Postprocessing would then run based on the merged disambiguated alignment.

**Comment by mjafin** [comment]
Hi @schelhorn, thanks for the discussion. If you have an improved disambiguation algorithm that works with bwa, star and tophat, I think everyone would be excited to incorporate it into bcbio. I would ask you to license it under the MIT license and release the code in Github.

Regarding your suggestion to split the fastq inputs, aligning them and piping to disambiguation sounds great but would require quite significant re-engineering of bcbio. I'll try to think of the least disruptive way of implementing parallel disambiguation over the weekend.

**Comment by schelhorn** [comment]
Great, thanks a bunch. For clarification: splitting the FASTQs and aligning the chunks is how bcbio is currently doing it, isn't it? So at least that part wouldn't be new in my eyes. It's "just" that we have to stop processing after aligning the chunks, do the disambiguation, and continue with the disambiguated alignment for downstream, post-alignment processing. Is that about right or am I missing something?

**Comment by chapmanb** [comment]
Sven-Eric and Miika;
Thanks for all the thoughts on this. I did some work on it over the weekend and enabled disambiguation parallelization by split FASTQ chunk, as Sven-Eric described. This will first do the disambiguation, then merge the correctly split chunks back into the final on-target BAM file for further processing. This will allow us to distribute chunks over more processors on a cluster, although we could still use local speed ups to make the disambiguation on each part faster or make use of multiple cores. Hopefully the step improves speeds practically and makes it more do-able to run through bigger batches of disambiguation variant calling. Thanks again for the suggestions.

**Comment by mjafin** [comment]
Awesome, thanks Brad!

**Comment by schelhorn** [comment]
Great, thanks a lot! I really appreciate it.

**Comment by mjafin** [comment]
@schelhorn I believe with the new implementation not all the parallelisation problems have been solved, but alleviated a bit by the running in blocks. You may want to set bwa cores to 1 or 2 as disambiguation still uses the number of slots assigned to bwa/alignment.

**Comment by lbeltrame** [comment]
I'm quite interested in this myself as I'll have to handle xenograft samples rather soon. Nice to see improvements in the area!

**Comment by schelhorn** [comment]
Thanks to anyone involved; @mjafin noted remaining issues with the slot-sharing of the alignment and disambiguation steps. Still, I think the main issues has been resolved and I am therefore closing the issue.
