### ISSUE TITLE
tumor only calling

### ISSUE THREAD

**Issue by tanglingfung** [chapmanb/bcbio-nextgen#806]
is there a suggested template for tumor only calling? Thanks!

**Comment by chapmanb** [comment]
Paul;
We don't have a separate template but there are no special options for tumor-only calling. You only need to follow a paired template (https://github.com/chapmanb/bcbio-nextgen/blob/master/config/templates/tumor-paired.yaml) or example configuration (https://github.com/chapmanb/bcbio-nextgen/blob/master/config/examples/cancer-dream-syn3.yaml) and leave out the normal sample. Hope this helps get you started.

**Comment by tanglingfung** [comment]
thanks Brad, let me try.. 

another slide issue, after I manually updated gemini, I got the following error when I start bcbio_nextgen.py, any idea?

File "/media/bigdata/bcbio-nextgen/anaconda/lib/python2.7/site-packages/pysam/__init__.py", line 125, in <module>
    [ "SamtoolsError", "SamtoolsDispatcher" ] + list(SAMTOOLS_DISPATCH) +\
AttributeError: 'module' object has no attribute '__all__'

**Comment by tanglingfung** [comment]
oh, that's solved after updating pysam, conda install -c https://conda.binstar.org/collections/chapmanb/bcbio  pysam

Thanks.
