### ISSUE TITLE
Final upload to S3 fails, possible due to trivial bug in upload.s3

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#807]
I noted that the final upload of the results from the working directory to S3 fails; I seem to have fixed it by changing `upload_file()` in [upload.s3](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/upload/s3.py#L37):
```
region = "@%s" % config["region"] if config.get("region") else ""
fname = "s3://%s%s/%s" % (config["bucket"], region, to_transfer[0][1])
conn = objectstore.connect(region)
```

where the last line should be:

```
conn = objectstore.connect(fname) # Fix here
```

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks so much for the patch and fix. Sorry about the mistake, I'm not sure what I did there. Much appreciated.
