### ISSUE TITLE
gfortran seems to be missing from cloudbiolinux/homebrew installation procedure, leading to failing R package compilations

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#810]
In my recent re-installation of bcbio, `gfortran` does not seem to be installed by the cloudbiolinux/homwbrew installation procedure (at least it's not mentioned in my logs and also not present as a binary or in the  `PATH`). This results in failing installations for R packages that are built from source by `gfortran`, such as `cghFLasso`, `acepack`,  `RcppArmadillo`, `statmod`,  and `genefilter`, which in turn are hard dependencies of `Hmisc`, `DESeq2`, and `DEXSeq` which then also fail to install. I also get an `ERROR: dependency ‘DNAcopy’ is not available for package ‘PSCBS’` during the R package installation, but that may be a seperate issue. 

I am using an R 3.1.1. on x86_64 if that is of importance (bcbio does not ssem to specify the R version it needs in its requirements). I also get the same errors when trying to install the problematic packages directly using R (without the bcbio `PATH` components etc), so it seems as if it's definitly the missing `gfortran` that is the culprit. Since `gfortran` is not an external dependency of bcbio I suggest it should be added to the bcbio installation procedure. In that respect I noted that `gfortran` is part of the _minimal_ flavor (or how that is called) of cloudbiolinux, but apperantly not part of the _ngs_pipeline_minimal_ flavor that bcbio is installing, so there may be value in revisiting the difference between the two.

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the installation problems. `gfortran` is a system level dependency for bcbio, but was not documented. I added this to the details of things that need to be pre-installed. We try not to install system level dependencies in bcbio to avoid the pain of needing to make these work in a cross-platform way (all of the tools are hard enough). bcbio will install this if you give it root permissions with the `--sudo` flag, although it's probably easier just to install it from system packages manually.

Having fortran should hopefully fix all of your R issues. We generally test on the latest R but 3.1.1 should work if you have gfortran, which DNAcopy also requires. Hope this gets it going for you.

**Comment by schelhorn** [comment]
Thanks for looking into it, I'll add it to our nodes then. I wasn't aware of the fact that it was difficult to install or requiring root permissions, and I very much support the idea of not adding everything to the installer.
