### ISSUE TITLE
Pipeline passes wrong chanjo arguments

### ISSUE THREAD

**Issue by LMannarino** [chapmanb/bcbio-nextgen#813]
(CC @lbeltrame)

When running chanjo, it looks like the program arguments are not being sent correctly. Here is the log (single-core run):

````
subprocess.CalledProcessError: Command 'set -o pipefail; /mnt/data/bcbio/anaconda/bin/chanjo annotate -s 21184-blood -g  -c 4 /mnt/data/projects/OV198/OV198/work/align/21184-blood/90_2015-04-02_OV198-sort.bam /mnt/data/projects/OV198/OV198/work/coverage/panelAB.sorted-unames.bed | /mnt/data/bcbio/anaconda/bin/chanjo --db /mnt/data/projects/OV198/OV198/work/coverage/tx/tmpvcoQLR/-coverage.db import
Usage: chanjo annotate [OPTIONS] BAM_PATH [IN_STREAM]

Error: Invalid value for "bam_path": Path "4" does not exist.
````

I last updated the pipeline last Friday (Apr 3th 2015).

**Comment by chapmanb** [comment]
Thanks for the report and sorry about the problem. It looks like bcbio didn't find a non-empty shared batch name for a group of samples so output the command line with an empty group for the `-g` argument. This consumed the following `-c` argument and confused chanjo into thinking `4`, the input to `-c` was a fine to load.

I pushed a fix which should be more flexible in getting the name and hopefully avoid this in the future. Hope this fixes it for you.
