### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by szuszmok** [chapmanb/bcbio-nextgen#814]
Hi,
I started to run a pipeline (whole genome variant calling) from the university server while I was logged in via SSH, and it ended up here:  

File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 148, in run
    samples = run_parallel("process_alignment", samples)
Write failed: Broken pipe

What could be the problem? Perhaps some python package are missing, I didn't find anything related to this error in the log.
Thanks!

**Comment by chapmanb** [comment]
Sorry about the issue. This error message doesn't provide much to debug on so unfortunately it's hard to guess the underlying issue. Typically the causitive error message is earlier in the output traceback. Could you try re-running in single core mode and save the output to a log file with the script command:
```
$ script bcbio-debug.log
Script started, file is bcbio-debug.log
$ bcbio_nextgen.py ...
$ exit
```
Then make `bcbio-debug.log` available as a Gist (https://gist.github.com/). That could help us try to guess the issue if you can't spot it in the log. Thanks for the help debugging.

**Comment by szuszmok** [comment]
It was just a typo in the sample yaml file...
Sorry for the issue and thank you very much!
