### ISSUE TITLE
Specific doc section for publications

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#815]
http://dx.doi.org/10.1093/annonc/mdv164 has been released and mentions bcbio-nextgen heavily in the methods (full disclosure: both me and Brad are co-authors): I was going to make a PR to the docs to add it (and to encourage others to do the same if they have), however there's no specific section there.

"Presentations" doesn't look that good to me, and adding it in "users" makes it seem a bit too "local". 
Should we add a section related to publications? If so, I'll make a PR.

**Comment by chapmanb** [comment]
Luca;
It would be great to see this added to the users section of the docs (https://github.com/chapmanb/bcbio-nextgen/blob/master/docs/contents/introduction.rst#users). The case-study/testimonial approach is a nice way to highlight how bcbio is useful in other's research, and hopefully papers (or blog posts, or patents...) are tangible outcomes we could link in the usage. Having the background, motivations, usage and papers together in one place makes a great story, and it would be awesome if you want to include your paper there. Congrats again and thanks for this.

**Comment by lpantano** [comment]
Closing this since that section seems to work for this issue.

thanks a lot for this suggestion!
