### ISSUE TITLE
Unable to install ensembl VEP from behind http proxy

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#818]
I am trying to install an isolated bcbio install on a dedicated VM (ubuntu 12.4), which gets its incoming internet connection from a http proxy. During the installation I am unable to install ensembl VEP because of a time-out during the connection with the FTP server.
It seems the Net::FTP perl package used in the script does not support http proxies. I already scoured the existing issues and found a workaround using curl, but this doesn't seem to work for me.

Any help?

Thx

**Comment by chapmanb** [comment]
Sorry about the issues (and closing this incorrectly -- dealing with two things at the same time).

The installer should now use curl by default for the install part of the process. Are you seeing timeouts when installing the initial script or the data? Do you get any kind of error tracebacks or anything else that would be useful to pinpoint exactly where it happens?

Sorry about the issue and hope this helps some.

**Comment by matthdsm** [comment]
I'm getting my issue when downloading the cache and fasta files. I've added the traceback in this comment. In the mean time I have solved the issue by following a tip you gave in this thread: 'https://groups.google.com/forum/#!topic/cloudbiolinux/-6aKBGbiVL4'

thanks for the reaction. I'm currently testing bcbio and plan to try to contribute in the future.
keep up the good work!

[2015-04-09 08:21:22.125675] ERROR: bcbio-nextgen: Uncaught exception occurred
Traceback (most recent call last):
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'vep_install.pl -a c -s homo_sapiens -c /mnt/bcbio/genomes/Hsapiens/GRCh37/vep

Hello! This installer is configured to install v75 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.
It will also download and install cache files from Ensembl's FTP server.

The VEP can either connect to remote or local databases, or use local cache files.
Using local cache files is the fastest and most efficient way to run the VEP
Cache files will be stored in /mnt/bcbio/genomes/Hsapiens/GRCh37/vep
Getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Net::FTP: connect: Connection timed out
' returned non-zero exit status 110
Traceback (most recent call last):
  File "/mnt/bcbio/anaconda/bin/bcbio_nextgen.py", line 199, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 241, in upgrade_bcbio_data
    _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 275, in _upgrade_vep_data
    effects.prep_vep_cache(dbkey, ref_file, tooldir)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 102, in prep_vep_cache
    do.run(cmd, "Prepare VEP directory for %s" % ensembl_name)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/mnt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'vep_install.pl -a c -s homo_sapiens -c /mnt/bcbio/genomes/Hsapiens/GRCh37/vep

Hello! This installer is configured to install v75 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.
It will also download and install cache files from Ensembl's FTP server.

The VEP can either connect to remote or local databases, or use local cache files.
Using local cache files is the fastest and most efficient way to run the VEP
Cache files will be stored in /mnt/bcbio/genomes/Hsapiens/GRCh37/vep
Getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Net::FTP: connect: Connection timed out
' returned non-zero exit status 110
Traceback (most recent call last):
  File "/mnt/bcbio/bcbio_nextgen_install.py", line 259, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "/mnt/bcbio/bcbio_nextgen_install.py", line 41, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir', '/mnt/bcbio/tools/', '--aligners', 'bwa', '--genomes', 'GRCh37', '--isolate', '--data']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Thanks for following up with the details. Looking at the Perl script, it is still hardcoded to use Net::FTP to fetch the cache files, which is what appears to cause the issue. I'm glad you managed to get it running but if you want to dig more and find a proper fix it might be worth asking on the Ensembl development list to see if they have suggestions for using VEP behind a proxy:

http://useast.ensembl.org/info/about/contact/index.html?redirect=no

If there is anything we can do in bcbio to avoid it happy to push this in. Thanks again.

**Comment by chdem** [comment]
Hello,

We can change default URL used by VEP installation script with the option -u :
```
-u | --CACHEURL    Override default cache URL; this may be a local directory or a remote (e.g. FTP) address.
```

Users with http:proxy FTP limitations can download VEP files required in a folder and use this folder with the -u option to install VEP. After that, bcbio_nextgen_install.py is ok !

For the vm_install, I do not found any way to manage this. :(

**Comment by chapmanb** [comment]
Following up on this in #1080
