### ISSUE TITLE
Sambamba is not configured for natural name-sort, breaking comatibility with samtools and probably also with disambiguation

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#821]
After triggering reactivation of parallel name-sorting by sambamba in issue #800, I noticed that the order of query name sorting of sambamba is different from samtools' ordering. While samtools [uses "natural", i.e. mixed-sort ordering](http://sourceforge.net/p/samtools/mailman/message/25715432/), sambamba uses lexicographic ordering (likely due to sambamba's use of an external D library that has no implementation for natural ordering).

This is generally not much of an issue, but it is problematic in one special case: disambiguation of human from mouse reads (for instance, in Xenograft settings) where one compares competetive alignments of the same set of reads against the reference of each species _by read order_. As noted [before](https://github.com/chapmanb/bcbio-nextgen/issues/804), we have our own implementation of such a disambiguation algorithm which validates the ordering of the input files and tripped over this issue when switching from samtools to sambamba, so I adapted it to sample reads and infer the ordering from the data. In parallel, I [asked](https://github.com/lomereiter/sambamba/issues/132) the developers of sambamba to implement mixed sort, which has been [completed](https://github.com/lomereiter/sambamba/issues/109) a couple of days ago by [specifying the `-N` parameter](https://github.com/lomereiter/sambamba/commit/9df21c23805e294d609f5df3b3b8fbfd0e5f7929) rather than the `-n` parameter to sambamba. 

I mention this issue here because bcbio's [disambiguate.py](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/disambiguate/run.py#L35) does not seem to be aware of this subtle difference since it likely has been designed for samtools only. As a consequence, I believe it may erroneously throw away reads by assuming natural ordering during the pairing process. Bcbio could adopt natural ordering for all name-sorting sambamba calls to fix this issue. This will also generate output files identical to samtools' ones, which increases transperency and may prevent future bugs of this kind.

**Comment by mjafin** [comment]
Thanks @schelhorn, this is incredibly helpful for us and I had not noticed it.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks so much for identifying the issue, tracking this down, and proposing the fixes upstream to sambamba. I pulled in the latest sambamba version and updating to use `--natural-sort` so we should now be compatible and avoid future issues. I appreciate all the work digging into this.
