### ISSUE TITLE
Support temporary directory configuration also for GEMINI

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#833]
(CC @LMannarino)

I'm not sure this is doable due to the architecture, but it would be nice to have given the high disk I/O GEMINI can cause when loading samples from multiple batches. I've had jobs fail due to them taking too much to run and hitting the cluster's time limit.

**Comment by chapmanb** [comment]
Luca;
Sorry about the issues. We do support temporary directory usage for GEMINI but for parallel runs it doesn't respect the output temporary directory and will write intermediates in the current working directory. This would take some refactoring/fixes on the GEMINI side. This is something we can explore fixing but maybe it's worth opening an issue for GEMINI and referencing this so we can track it over there. Thanks much.

**Comment by chapmanb** [comment]
Luca;
Thanks again for this report. I pushed a fix to GEMINI which uses temporary directories for chunks and added the corresponding update to bcbio. This should now use temporary directories correctly with the next release of GEMINI. Thanks again.
