### ISSUE TITLE
Per-run definition of genomes directory

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#835]
One of the few remaining issues that currently limit scalability for us is the somewhat inflexible location of the genome resource and GEMINI directories. Especially for many concurrent analyses it would be convenient if we could define the location of that directory as a resource, similar to the tmp directory that can be defined system-wide or per-sample in the yaml configuration files. Is there an officially supported way (or a hack) that would allow us to do the same for the genome and index resources? In that way we could provision the compute nodes' local disk storage with these resources at startup by copying over the genomes directory and would save a lot of network IO, especially for STAR.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the ideas. Bringing reference data locally is something we'd like to support as we move away from requiring a shared filesystem. The tricky parts are that we need a way to distribute it to all of the computational nodes. This is something we were hoping to tackle as we moved to using infrastructure like Arvados to do the parallelization, since they have methods to do this.

In the short term, the best hack I can think of is to put the reference data in the same local directory on all the compute nodes and then adjust the `*.loc` files in `/path/to/bcbio/galaxy/tool-data` to point to that. Hopefully that will work with your setup.

**Comment by schelhorn** [comment]
That sounds very workable. However, I haven't found a loc file for STAR in my installation. Is that a particularity of my installation or was that expected? Secondly, can I specify the location of the tools-data directory in the system config YAML?

**Comment by chapmanb** [comment]
Sven-Eric;
For STAR and other aligners that don't have a native galaxy .loc file we remap it relative to the reference directory:

https://github.com/chapmanb/bcbio-nextgen/blob/74b3c80106fdeb4bc85a99c35fb1d617ffb6d22f/bcbio/ngsalign/star.py#L103

So changing the reference locations will fix this. This ties us to our internal installation structure but also saves editing a ton of .loc files by hand to change things.

You can specify an alternative directory using `galaxy_config` in your `bcbio_system.yaml` file:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#reference-genome-files

Hope this helps get it working for you.

**Comment by schelhorn** [comment]
Thanks Brad, that setup went really well. For reference: we're now rsyncing the genomes directory to the local nodes) at startup together with a tool-data directory that contains modified .loc files that point at the synced genomes directory. We then start bcbio with a bcbio_system.yaml as parameter that in turn point at the tool-data directory. All this is encapsulated in a script that automatizes the process and allows per-analysis configuration of all file locations. This setup really took some load from our cluster file system, especially for STAR indexes (which we will probably also keep in memory using the STAR --genomeLoad parameter, but that requires a high shared memory setting on the nodes and may thus not suited as a default for bcbio).
