### ISSUE TITLE
can I interest you in the letter 'm'?

### ISSUE THREAD

**Issue by kern3020** [chapmanb/bcbio-nextgen#840]
Hello,

I was running the shinny, new bcbio 0.8.8 and ran into an error. 
```
/opt/bcbio/bin/gatk-framework org.broadinstitute.gatk.tools.CatVariants -R /data/trialOne/input/project/work/inputs/data/genomes/GRCh37/seq/GRCh37.fa -V /data/trialOne/input/project/work/freebayes/gz040215-files.list -out /data/trialOne/input/project/work/freebayes/tx/tmp4BGvCz/gz040215.vcf.gz -assumeSorted -Xms750 -Xmx2000m -XX:+UseSerialGC

Error occurred during initialization of VM
Too small initial heap
```

Looks like the defaults jvm options are missing an 'm'. 
jvm_opts: ["-Xms750", "-Xmx2000m"]

So, they are interpreted as bytes. Looks like there is a typo in the bcbio_system.yaml file. Is that right? I made the change locally and things are progressing. 

-jk

**Comment by sxv** [comment]
Thanks! Kept hitting the wall with this one..

**Comment by chapmanb** [comment]
John -- thanks so much for catching this. My apologies, we even diagnosed this in #832 but I didn't catch on that this was a mistake in the default installer YAML. Sorry to everyone for the bad initial set of defaults and thanks again.
