### ISSUE TITLE
Error of unknown provenance in GEMINI vcf preparation workflow

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#841]
I have an error of unknown (or at least, complicated) provenance and would appreciate some help. I am working on non-batched Exome-Seq samples with the Freebayes pipeline and GRCh37. Effects with `vep`, no realignment/recalibration/phasing and only pre-alignment quality binning. After Freebayes did its thing, GEMINI complains upon importing the post-processed Freebayes VCFs that the `DPB` fields in the imported VCF chunks are not of the correct data type (float). It then cancels the import for that chunk (without stopping the pipeline, which just continues to 'complete' and upload the broken data, but that is a separate issue that could be addressed).

Upon closer inspection, it becomes clear that the imported `*-freebayes-nomultiallelic.vcf.gz` file (* denotes the sample name which is of no importance here) is broken. Specifically, some variant rows (case 1) contain a valid `CSQ` (the VEP effect annotation) but a missing `DPB` (depth) field, while other variant rows (case 2) contain a `DPB` field label in the variant rows that point to information of the `CSQ` field: `DPB=synonymous_variant|tcA/tcG|S|ENSG00000186092|OR4F5|ENST00000335137|1/1|||60/305|protein_coding|YES|CCDS30547.1|||;`

Case 2 is a serious error where GEMINI rightly throws its exception, since `DPB` here contains `string` information (the `CSQ` data) rather than a `float` (the depth). Closer inspection reveals that case 1 entries originate from `*-freebayes-multiallelic-decompose-vepeffects.vcf.gz` while the case 2 entries originate from `*-freebayes-biallelic.vcf.gz`. Both are merged into  `*-freebayes-nomultiallelic.vcf.gz` by the `merge_sorted()` method.

I tried to backtrack where things may have gone wrong, now in chronological order as orchestrated by [variation.multiallelic.to_single](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/multiallelic.py#L32) that seems to do the post-processing of Freebayes VCFs for GEMINI:

The annotated Freebayes VCF `*-freebayes.vcf.gz` is well-formated and contains both `DPB` and `CSQ` header definitions; for biallelic variants `DPB` entries are present in the variant rows while for multiallelic variants they are not (I assume they are not defined for multiallelic variants?)

[_split_mulitallelic()](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/multiallelic.py#L63) takes `*-freebayes.vcf.gz` and produces `*-freebayes-biallelic.vcf.gz` and `*-freebayes-multiallelic.vcf.gz`. Here we may already see the possible source of the error. `*-freebayes-biallelic.vcf.gz` is well-formated, but `*-freebayes-multiallelic.vcf.gz` has a `DPB` entry only in the header (as an `INFO` definition) but not in any of the variant rows.

[_decompose()](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/multiallelic.py#L48) takes the `*-freebayes-multiallelic.vcf.gz` and produces a `*-freebayes-multiallelic-decompose.vcf.gz`, which has good `CSQ` definition/row entries but is missing `DPB` completely from header or variant rows.

[add_to_vcf()](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/effects.py#L25) (which delegates to [run_vep()](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/effects.py#L112)) takes `*-freebayes-multiallelic-decompose.vcf.gz` and produces `*-freebayes-multiallelic-decompose-vepeffects.vcf.gz`, which has good `CSQ` definition/row entries as well as a `DPB` INFO header definition but an empty entry `;;` where the `DPB` definition should be placed in the variant rows (so both key and value are missing, but there is an empty spot marked by the semicolon field separators for them). This may or may not be VCF standard compliant.

[merge_sorted()](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/vcfutils.py#L363) then takes that broken (?) `*-freebayes-multiallelic-decompose-vepeffects.vcf.gz` and the well-formated `*-freebayes-biallelic.vcf.gz` and produces the erroneous output described at the top of this post, probably by merging in the multiallelic data into the biallelic data and somehow having problems with field ordering due to the `;;` entry that results in the mislabeled `CSQ` entry. Notably, merge_sorted() always uses the header of the first input file (`*-freebayes-multiallelic-decompose-vepeffects.vcf.gz`) as the header of the resulting output file without checking for header identity, which may or may not have an influence on this issue.

So the question is, which of the outputs is the first malformated VCF, and why is it generated that way? Second, could we perhaps stop the whole pipeline when GEMINI cannot read in a VCF chunk? Else these kinds of errors will not be noticed since they are burried in the logs since chunks that do not have problematic entries are read in okay while problematic chunks are skipped, so there is a output file if at least one chunk was okay and users may not notice that an error has occurred.

**Comment by schelhorn** [comment]
Update: So I ran run_vep() manually, removed the double semi-colon (`;;`) and then merged again manually using the merge_sorted() code in bcbio. Still the malformated output of merge_sorted()  persists. When I try to use the header of the second input file instead (so using the header of `*-freebayes-biallelic.vcf.gz`) I get a core dump of the python interpreter.

**Comment by schelhorn** [comment]
Update 2: I replaced `merge_sorted()` with GATK CombineVariants (using parameters --assumeIdenticalSamples --genotypemergeoption UNSORTED, both of which are probably insufficient to produce a sorted VCF, but that was not the point) and the resulting file is well-formated and should be readable by GEMINI just fine. I had to remove the `;;` (by `sed 's/;;/;/g' `) since otherwise GATK complains about an undefined field. I therefore suggest that the `merge_sorted()` function should not be trusted (likely due to an error in pysam.VariantFile) and that it should be replaced by an external tools such as GATK or bcftools followed by sorting (there is a newer version of bcftools out with different parameters than the older version that bcbio ships).

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks for the report and I'll the detective work on this. I'll definitely have a look and try to figure out what pysam.VariantFile is doing wrong. We specifically avoid `CombineVariants` or bcftools alternatives as those merge the biallelic variants we split with `vt` back together.

The best fix is to avoid all the split/combine logic and use `vt decompose` on the full file directly. I'd avoided this earlier just to prevent potentially causing issues on non-biallelic variants when decomposing. But by adding all this complexity it seems like I've introduced new issues. I'll work on pushing a simplification of this workflow.

Regarding GEMINI not failing if a part fails, that is worrisome. We'll have to debug it on the GEMINI side as it should be failing out with error code instead of making a partial database (and then bcbio thinks things went well). I'll see if I can reproduce and fix as well.

Thanks again for the work trying to sort these out.

**Comment by schelhorn** [comment]
Thanks a lot for looking into it, Brad. Of course, simplifying the workflow could be best in the end to avoid hassles and in the future and increase maintainability. Naive question regarding bcftools, though: isn't [bcftools concat](https://samtools.github.io/bcftools/bcftools.html#concat) just a dump concatenator that doesn't actually merge the variants? There's also [bcftools merge](https://samtools.github.io/bcftools/bcftools.html#merge), so they're different beasts, aren't they? 

Regarding GEMINI, this is the stack trace for one of the chunks (this repeats for all of the problematic chunks): 
```python
[2015-05-04T13:07Z] ip-172-31-2-5: Traceback (most recent call last):
[2015-05-04T13:07Z] ip-172-31-2-5:   File "/cluster/software/bcbio_dev/app/bin/gemini", line 6, in <module>
[2015-05-04T13:07Z] ip-172-31-2-5:     gemini.gemini_main.main()
[2015-05-04T13:07Z] ip-172-31-2-5:   File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1076, in main
[2015-05-04T13:07Z] ip-172-31-2-5:     args.func(parser, args)
[2015-05-04T13:07Z] ip-172-31-2-5:   File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 271, in loadchunk_fn
[2015-05-04T13:07Z] ip-172-31-2-5:     gemini_load_chunk.load(parser, args)
[2015-05-04T13:07Z] ip-172-31-2-5:   File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 733, in load
[2015-05-04T13:07Z] ip-172-31-2-5:     gemini_loader.populate_from_vcf()
[2015-05-04T13:07Z] ip-172-31-2-5:   File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 130, in populate_from_vcf
[2015-05-04T13:07Z] ip-172-31-2-5:     for var in self.vcf_reader:
[2015-05-04T13:07Z] ip-172-31-2-5:   File "parser.pyx", line 1063, in cyvcf.parser.Reader.__next__ (cyvcf/parser.c:19124)
[2015-05-04T13:07Z] ip-172-31-2-5:   File "parser.pyx", line 1112, in cyvcf.parser.Reader.parse (cyvcf/parser.c:19838)
[2015-05-04T13:07Z] ip-172-31-2-5:   File "parser.pyx", line 894, in cyvcf.parser.Reader._parse_info (cyvcf/parser.c:16800)
[2015-05-04T13:07Z] ip-172-31-2-5:   File "parser.pyx", line 47, in cyvcf.parser._map (cyvcf/parser.c:2191)
[2015-05-04T13:07Z] ip-172-31-2-5: ValueError: could not convert string to float: missense_variant|Tgt/Cgt|C/R|ENSG00000166359|WDR88|ENST00000355868|7/11|benign(0)|tolerated(1)|310/472|protein_coding|YES|CCDS12429.1|||
```

**Comment by schelhorn** [comment]
Regarding GEMINI: I believe [this part](https://github.com/arq5x/gemini/blob/a19b832f950a18c5e407b459365bf6a234baa56f/gemini/gemini_load.py#L239) may be responsible for error checking of the parallel chunk loading, but it does not look at error codes at all. So from GEMINI's perspective, it cannot differentiate a successful chunked load from a failed one and will probably always exit with status code `0`. Perhaps that is something that ahs to be solved upstream.

**Comment by chapmanb** [comment]
Sven-Eric;
Thank you for all of this debugging. I pushed fixes to bcbio to avoid the problematic merge and use vt decompose directly on the full file. I hope this simplified workflow will now work cleanly for you. Please re-open if you still find issues.

I also pushed a fix upstream to GEMINI to catch and report errors in chunks so any future issues will be more obvious and not proceed through with a truncated database.

Thanks again.

**Comment by schelhorn** [comment]
Great, thanks a lot for the quick implementation!
