### ISSUE TITLE
version number parsing during VEP installation

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#844]
Hi Brad,

I am trying to install a fresh version of BCbio on a local system, but I keep getting errors when installing VEP. I noticed that the filename of the newest version of the cache files for VEP is formatted as following: homo_sapiens_vep_79_GRCh37.tar.gz as opposed to homo_sapiens_vep_75.tar.gz.
After the installation of the cache files, a script is initiated to convert the cache to tabix format.
I see however that the options that are given to this script do not work. the cache files are installed as version "79_GRCh37" whereas the python scripts parse the version as just "79", which results as an error saying "version not found".
For example:
- command issued by script : 
vep_convert_cache.pl -species homo_sapiens_vep_79_GRCh37 -version 79 -d /mnt/bcbio/genomes/Hsapiens/GRCh37/vep
- command that does work: vep_convert_cache.pl -species homo_sapiens -version 79_GRCh37  -d /mnt/bcbio/genomes/Hsapiens/GRCh37/vep

I think the issue can be found somewhere in the installation scripts, just wanted to let you know.

Greetings and keep up the good work
Matthias

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issue. We just upgraded to the new VEP this morning in preparation for a new release (hopefully tomorrow, if all the validation tests pass tonight). The new VEP supports GRCh38 but now has the notion of both Ensembl versions as well as build versions, which causes the issue you're seeing.

This is fixed in the latest development so if you run either `bcbio_nextgen.py upgrade -u development --data` or pass `-u development` to your `bcbio_nextgen_install.py` arguments it should work cleanly.

Thanks again for the heads up and sorry about the issue.

**Comment by matthdsm** [comment]
Hi Brad,

Thanks for the quick response! I am currently trying to install the upgrade with the development code.
I do have another request, in the install script, the git repo url is defined as git://github.com/…, which creates an issue when installing from behind a proxy. Could you change the git url with the https clone url? This fixed the issue for me.

Thanks in advance
Matthias

Op 7-mei-2015, om 18:37 heeft Brad Chapman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Matthias;
Sorry about the issue. We just upgraded to the new VEP this morning in preparation for a new release (hopefully tomorrow, if all the validation tests pass tonight). The new VEP supports GRCh38 but now has the notion of both Ensembl versions as well as build versions, which causes the issue you're seeing.

This is fixed in the latest development so if you run either bcbio_nextgen.py upgrade -u development --data or pass -u development to your bcbio_nextgen_install.py arguments it should work cleanly.

Thanks again for the heads up and sorry about the issue.

**Comment by chapmanb** [comment]
Matthias -- thanks for the heads up about the proxy issues here. I swapped this over to https now so hopfully it works cleanly now. Thanks again.

**Comment by matthdsm** [comment]
Wow, thanks.
Works perfectly. Now I only need to bug Ensembl to make them ditch net::FTP in their vep_install script.

Thanks again
Matthias

Op 8-mei-2015, om 11:29 heeft Brad Chapman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Closed #844<https://github.com/chapmanb/bcbio-nextgen/issues/844>.
