### ISSUE TITLE
GATK java version issues

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#850]
Hi Brad,

I finally succeeded get a working installation of bcbio, but now I ran into another problem. I'd like to use our cluster system to perform the analysis (using iPython), but keep running into java issues. Our nodes run on a Ubuntu 12 LTS system with a torque resource manager. The default system java is 1.6, but we also have 1.7 installed. I modified $PATH and $JAVA_HOME in my personal environment en the environment of the node to point to the java 1.7 version, but I keep getting errors when starting GATK because bcbio only seems to detect the 1.6 version in usr/bin.
When I try to run an analysis locally everything works flawless and I get no errors.

Any suggestions? Is there any way I can configure bcbio/iPython to use java 1.7?

Thanks!
Matthias

**Comment by chapmanb** [comment]
Matthias;
Sorry about the issues. I'm not sure exactly what to suggest as bcbio doesn't do anything fancy to find java beyond what you describe. The bash scripts look for `$JAVA_HOME`/bin/java and if that doesn't exist default to the first java on your PATH. There isn't anything different about this for a remote environment versus local. It sounds like maybe your environmental variables or modules aren't loaded for cluster submissions. If you manually start an interactive job on your cluster, do you have the environmental set as you expect based on your local variables? Sorry to not be able to offer something more concrete but hope this helps.

**Comment by matthdsm** [comment]
Hi Brad,

Turns out this was a non issue, we edited the path, but forgot to restart the  torque engine. Sorry to waste your time!

Matthias
