### ISSUE TITLE
Ensemble structural variation calling seems to be disabled for non-batched samples

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#851]
During a run of the `variant2` pipeline in a _non-batched_ sample setting using multiple structural callers like

```yaml
details:
- algorithm:
    svcaller:
    - lumpy
    - delly
    - cnvkit
```

it occurred to me that only the last of these callers `cnvkit`, is actually run during the analysis. Since I believe that also the other two callers, `lumpy` and `delly`, are able to run in unpaired/non-batched mode, this seems to be a bug (or else I have misunderstood the documentation, which may be well possible).

Upon digging a little in [bcbio.structural](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/structural/__init__.py), it further occurred to me that in [line 99](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/structural/__init__.py#L99), 

```python
to_process[tz.get_in(["rgnames", "sample"], x)] = [x]
```

data entries for multiple callers seem to overwrite themselves: in contrast to batched mode, where the dictionary key consists of both the sample name and the variant caller name, in non-batched mode it only consists of the sample name (see code snippet below) and subsequent entries for other callers _replace_ prior instructions rather than being _appended_ to them. As a result, run instructions are prepared for all structural variation callers but only the instructions for the last structural variation caller in the list actually make it to execution, explaining why only the last variant caller runs. 

So I assume that the referred line should be changed into a structure similar to [line 94](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/structural/__init__.py#L94) in the same file which says (note that I am not absolutely sure if the semantics are correct, so someone would have to counter-check this):

```python
 try:
     to_process[(svcaller, b)].append(x)
except KeyError:
    to_process[(svcaller, b)] = [x]
```
On a related question, I noted that none of the specified `indelcaller` are applied in the `variant2` pipeline if `variantcaller: freebayes`. I assume that this is intentional since freebayes is supposed to call indels itself. Still, the behavior of the `indelcaller` parameter in this setting is not very well documented (in my opinion) and I was wondering if I have overlooked an existing way to re-activate the indel callers for `variant2` and merge their results into the freebayes VCF, perhaps as part of the variant ensemble mode?

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for catching this and apologies for the oversight. You were right on with the diagnosis: we should have been including the svcaller in the key as well for the single sample mode, causing this issue. If you grab the latest development this should be working cleanly.

For `indelcaller` it is only available for MuTect now. We haven't worked yet on having it be a separate mode that could be merged back in, as it's more of an experiment right now. There is more detail on this in the configuration documentation:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#variant-calling

but happy to expand anything that is not clear. Sorry for the confusion there and thanks again for the detailed report.
