### ISSUE TITLE
joint calling - size of compute blocks

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#852]
Is there any documentation on (a) what units of the analysis are checkpointed and (b) the very approximate maximum run time for anyone unit.

I'm trying to figure out if it would be practical to use the pipeline spanning a large number of cores that aren't guaranteed to be stable i.e. the new google setup. This would require a large number of small checkpoints to avoid getting stuck and wasting cycles.

http://googlecloudplatform.blogspot.com/2015/05/Introducing-Preemptible-VMs-a-new-class-of-compute-available-at-70-off-standard-pricing.html

**Comment by roryk** [comment]
Hi Daryl,

There's a couple levels of checkpointing. For each tool that is run the checkpoint is a completed file; so if that file exists the step will get skipped. This is transactional so if in the middle of a tool being run the job is killed, restarting it will just skip that step. There is also checkpointing at the level of the spinning up the different sized IPython cluster; some steps have much different resource requirements than other steps, so we tear down and build up the IPython cluster when large changes in requirements occur between steps.

It is this last part that is problematic for the type of compute environment that you are describing, the actual IPython cluster is pretty fragile and if engines keep dying then the entire IPython cluster falls apart, so these types of spot-instance type cluster setups won't work well. We're hoping to get out of the infrastructure business entirely and use a third party setup for handling these tricky type of compute environments, most likely built on top of the common workflow language.

**Comment by roryk** [comment]
Short answer is we don't meet the 'fault tolerant' part of the requirement at all.

**Comment by dwaggott** [comment]
Ah thanks very much. If you need help on attacking this I know people that
are interested. Fault tolerant is the dream.

**Comment by lpantano** [comment]
Closing this since we are moving to CWL that probably will handle this much  better.

thanks a lot!
