### ISSUE TITLE
joint calling - efficient nof1 adding

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#853]
How's the roadmap for improving the joint calling inputs for efficient adding of small sets of samples to large precalled sets? It still seems pretty heavy for FB. I haven't tried the GATK.

I'm guessing the the squared off intervals are already pretty firm after a few hundred joint called samples of a standard capture. 

Could the pipeline jump right to the joint calling step using a priori regions? 

Were any of the pipelines using gVCFs for block merge instead of joint calling? I know it's not perfect.

**Comment by chapmanb** [comment]
Daryl;
We haven't done any additional work on this recently, as we haven't had any big partial projects driving it on our side. Most recent work has focused on build 38 support and cancer calling as we have projects needing that functionality. Practically, FreeBayes is not likely to change much from the current workflow, which is still heavy for the n+1 problem and requires BAM files + squaring off. Erik is now focusing on graph-based approaches, where you could use the prior information to inform the full process. He has done some nice work but it is still in development:

https://github.com/ekg/vg

Our plan would be to migrate a FreeBayes n+1 workflow to this as the work progresses to be more production ready.

You could do gVCF recombining but the status would still be manual post-bcbio as we discussed in #767. I'm not sure about the best way to inject all of the prior gVCFs into a current pipeline. We'd be happy to accept usage suggestions or patches if you have the opportunity to work on this. Sorry to not have a more up to date status but hope this helps.

**Comment by dwaggott** [comment]
Ah good, I guess the answer is to get my hands dirty with the code!

**Comment by lpantano** [comment]
Hi @dwaggott 

I will close this guessing you got it working. 

Thanks!
