### ISSUE TITLE
Possible off-by-1 error in grabix

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#854]
I am getting a lot of malformed FASTQ files in `grabix` processed FASTQ files that bcbio utilizes to allow parallel mapping of the same FASTQ file. The error occurred since the latest `grabix` update and may be due to erroneous chunking. I have [submitted a bug report](https://github.com/arq5x/grabix/issues/21) upstream and open an issue here to track the original issue.

If this issue is valid (and not only a fluke on my system, which may of course be the case) then setting `align_split_size` should be considered dangerous and the erroneous chunking may also lead to missing variants in `grabix` processed VCF files.

**Comment by schelhorn** [comment]
The issue has been acknowledged and [fixed](https://github.com/arq5x/grabix/pull/22) upstream. I recommend that bcbio should require grabix 0.16 from now on and use of 0.15 should be discouraged.

**Comment by chapmanb** [comment]
Sven-Eric, @brentp and @arq5x -- thanks so much for the debugging and quick fix. I updated the homebrew-science recipe and sent upstream so we'll have the fixed version as soon as that gets in. Brent, thanks for updating the CBL repo already. Much appreciated.
