### ISSUE TITLE
incorrect version is being used for biolinux repository

### ISSUE THREAD

**Issue by ssvbio** [chapmanb/bcbio-nextgen#857]
During installation, cloudbiolinux.list is added to /etc/apt/sources.list.d. sources inside are:

================================================

deb http://us.archive.ubuntu.com/ubuntu/ trusty universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates universe
deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
deb http://archive.canonical.com/ubuntu trusty partner
deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen
deb http://cran.fhcrc.org/bin/linux/ubuntu trusty/
deb http://archive.cloudera.com/debian maverick-cdh3 contrib
deb http://ppa.launchpad.net/freenx-team/ppa/ubuntu precise main
deb http://ppa.launchpad.net/nebc/bio-linux/ubuntu precise main
deb [arch=amd64 trusted=yes] http://research.cs.wisc.edu/htcondor/debian/stable/ squeeze contrib
deb http://nebc.nerc.ac.uk/bio-linux/ unstable bio-linux
deb http://download.virtualbox.org/virtualbox/debian trusty contrib

====================================================
Please note that biolinux repositories point to precise instead of trusty. When checked manually, repositories for trusty exist. Biolinux should use trusty repositories instead of precise unless trusty packages are not up to date compared to precise and at the time of installation (i.e 22/05/2015)

However, package size in  /nebc/bio-linux/ubuntu/dists/trusty/main/binary-amd64 (183 k) differs from http://ppa.launchpad.net/nebc/bio-linux/ubuntu/dists/precise/main/binary-amd64/ (267 k). Does this mean biolinux packages in trusty repositories are not on par with precise repositories?

regards
vs

**Comment by chapmanb** [comment]
Sorry about the issues, these repositories haven't gotten updates recently. We've been working on running bcbio installations without requiring sudo and this is the more common mechanism of installation so it's a bit less invasive on the overall system. Did you find issues running without sudo, or just wanted bcbio to install the system packages for you?

I pushed fixes to bring Bio-Linux up to date and remove stale repos we no longer use as part of the installation. If you remove `cloudbiolinux.list` and the locally cached CloudBioLinux (`rm -rf tmpbcbio-install`), a re-run should hopefully provide a more up to date set of packages.

Thanks again for the report and hope this fixes things for you.
