### ISSUE TITLE
RSEM is not using disambiguated reads but original inputs for transcriptome mapping

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#859]
When running with `disambiguate` and `rsem`, is occured to me that RSEM is not using the disambiguated reads as inputs for the transcriptome mapping, but the original FASTQ files that still contain explant contamination. As a result, the RSEM results are not reliable in this `disambiguate` setting. This behavior is not transparent to the user (and also rather unexpected) and may therefore lead to false conclusions in downstream analyses.

I suggest that either RSEM transcriptome mapping uses the disambiguated BAM file as an input (preferably directly without prior conversion to FASTQ, however the latter does not seem possible in the [default transcriptome mapper, bowtie2](https://github.com/chapmanb/bcbio-nextgen/blob/96542d8f5fa9ef3f19df78a45a2a12609bffa956/bcbio/pipeline/rnaseq.py#L70)), or that RSEM processing is disabled for the time being if disambiguation is set (by throwing an exception or skipping RSEM with a warning). 

@roryk, perhaps you could have a look since you seem to be the primary author of the RSEM functionality. Thank you.

**Comment by roryk** [comment]
Hi Sven-Eric,

Thanks, that is definitely an oversight. RSEM needs transcriptome-only BAM files, and we a) don't disambiguate that file if it is made and b) if it is not made, create it from the disambiguated reads, so we fail both ways. I disabled RSEM for now until I can fix one or both of those and do the right thing.

**Comment by schelhorn** [comment]
Excellent, thanks. Shall we leave open the issue for later enhancements or shall I close it? In the end out would be best to extract the disambiguated reads from the genomic alignment and remap them to the transcriptome - in that manner the two mappings are coherent with regard to replant filtering.

**Comment by schelhorn** [comment]
Coming back to this issue (no pressure), it seems as if all the functionality to extract paired FASTQs from a BAM is already [nicely encapsulated in a function](https://github.com/chapmanb/bcbio-nextgen/blob/36a7ad760a75b45039e73a8265eef4db1cd71c23/bcbio/ngsalign/alignprep.py#L299). I'm not totally sure of it, but I would assume that it only requires a check for a disambiguated human BAM in the global data structure followed by a function call to the BAM to FASTQ function [prior to calling the bowtie mapping](https://github.com/chapmanb/bcbio-nextgen/blob/96542d8f5fa9ef3f19df78a45a2a12609bffa956/bcbio/pipeline/rnaseq.py#L70) to resolve this issue quite elegantly in about three lines of code. Any takers?

**Comment by schelhorn** [comment]
Alright, I came back to this issue and implemented what I believe should enable RSEM for disambiguated BAMs without breaking anything else. I would appreciate if @roryk or @chapmanb could have a look and integrate the code if appropriate. It seems that RSEM is not really used in bcbio anyway, but these fixes also re-enable the transcriptome BAM fir eXpress, so it should be generally useful.

[bcbio.ngsalign.alignprep line 299](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/alignprep.py#L299):

```python
def _bgzip_from_bam(bam_file, dirs, config, is_retry=False, output_infix=''):
``` 
[bcbio.ngsalign.alignprep line 310](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/alignprep.py#L310):

```python
    out_file_1 = os.path.join(work_dir, "%s%s-1.fq.gz" % (os.path.splitext(os.path.basename(bam_file))[0]), output_infix)
```
[bcbio.pipeline.rnaseq line 56 ff](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/rnaseq.py#L56) (The import belongs to the top of that file, of course):

```python
from bcbio.ngsalign import alignprep
def generate_transcript_counts(data):
    """Generate counts per transcript and per exon from an alignment"""
    data["count_file"] = featureCounts.count(data)

    if dd.get_fusion_mode(data, False):
        oncofuse_file = oncofuse.run(data)
        if oncofuse_file:
            data = dd.set_oncofuse_file(data, oncofuse_file)

    if dd.get_rsem(data) and not dd.get_transcriptome_bam(data):
        file1, file2 = None, None

        if dd.get_disambiguate(data):
            bam_path = data["work_bam"]
            fastq_paths = alignprep._bgzip_from_bam(bam_path, data["dirs"], data["config"], is_retry=False, output_infix='-transcriptome')
            if len(fastq_paths) == 2:
                file1, file2 = fastq_paths
            else:
                file1, file2 = fastq_paths[0], None
        else:
            file1, file2 = dd.get_input_sequence_files(data)

        ref_file = dd.get_ref_file(data)
        logger.info("RSEM was flagged to run, but the transcriptome BAM file "
                    "was not found. Aligning to the transcriptome with bowtie2.")
        data = bowtie2.align_transcriptome(file1, file2, ref_file, data)
    return [[data]]
```

**Comment by chapmanb** [comment]
Sven-Eric -- thanks so much for this. Would you be able to submit the changes as a pull request and we can pull it in? That would actually give you credit for your work in the history. Thanks again for doing this.

**Comment by schelhorn** [comment]
Hi Brad, that's a great idea in general, however I suggest that we could clearify the RSEM/eXpress YAML parameter question first (see comment above) to see if I have interpreted the code correctly. If not, then perhaps @roryk could take over the code from this comment directly and integrate it in an own patch that also fixes the YAML parameter from `rsem: true` to `transcriptome_based_quantitation: true`, or to `transcriptome_alignment: true`, or something like that.

**Comment by schelhorn** [comment]
@roryk, are you listening in on this discussion and could help us out with your input? Thanks!

**Comment by roryk** [comment]
Thanks for the ping @schelhorn, sorry this slipped off of my radar. Your changes look good to me, I can roll them into a patch. I also agree with swapping the parameter name to something more correct.

**Comment by schelhorn** [comment]
Great, I'd appreciate it if you could do exactly that. Thanks!

**Comment by roryk** [comment]
Thanks @schelhorn, sorry that this took so long to get to. I went with transcriptome_align as the flag to set instead of RSEM.
