### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by anthonysoprano** [chapmanb/bcbio-nextgen#861]
Hi, 
I am trying to install bcbio-nextgen by running the installation script as mentioned on your instructions page : 
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local \
  --genomes GRCh37 --aligners bwa --aligners bowtie2

I am getting the following error : 
Collecting pycurl>=7.19.5.1 (from arvados-python-client>=0.1.1405019228.4a7ca04->-r https://raw.githubusercontent.com/chapmanb/bcbio-nextgen/master/requirements.txt (line 20))
  Downloading pycurl-7.19.5.1.tar.gz (142kB)
    100% |████████████████████████████████| 143kB 891kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-uIyseU/pycurl/setup.py", line 634, in <module>
        ext = get_extension(split_extension_source=split_extension_source)
      File "/tmp/pip-build-uIyseU/pycurl/setup.py", line 392, in get_extension
        ext_config = ExtensionConfiguration()
      File "/tmp/pip-build-uIyseU/pycurl/setup.py", line 65, in __init__
        self.configure()
      File "/tmp/pip-build-uIyseU/pycurl/setup.py", line 100, in configure_unix
        raise ConfigurationError(msg)
    __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-uIyseU/pycurl
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 261, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 36, in main
    bcbio = bootstrap_bcbionextgen(anaconda, args, remotes)
  File "bcbio_nextgen_install.py", line 73, in bootstrap_bcbionextgen
    subprocess.check_call([anaconda["pip"], "install", "-r", remotes["requirements"]])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/bcbio/anaconda/bin/pip', 'install', '-r', 'https://raw.github.com/chapmanb/bcbio-nextgen/master/requirements.txt']' returned non-zero exit status 1

Any ideas on what might be going wrong ?

**Comment by roryk** [comment]
Hi Raghavendra,

It looks like your system is missing curl. Here is a list of requirements that bcbio-nextgen doesn't install that you have to have up front to do the non-sudo installation:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

If you get those installed you shoud be good to go.

**Comment by anthonysoprano** [comment]
Thanks got it fixed

**Comment by roryk** [comment]
Great!
