### ISSUE TITLE
Chunking error in S3 object store results in duplicated/truncated streamed data

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#862]
There seems to be a (bad) chunking bug in the S3 object store code that results in duplicated/truncated results for all _streamed_ data (in contrast to _downloaded_ data, which is fine) from S3 that is parsed line-by-line. This error affects all such data that is long enough to span a chunk and seemed to be in the code for quite some time without anyone noticing (not complaining, just wondering). The bug can in principle result in seemingly spurious errors or undetected data corruption downstream.

The bug likely (please validate) results from an indentation error in the [object store chunk iterator](https://github.com/chapmanb/bcbio-nextgen/blob/4f5dae32dd5f2755d383b1a6a89c617817ecad3c/bcbio/distributed/objectstore.py#L209) that results in yielding the last line from _each chunk_ even it is incomplete (i.e., the line was cut off by the chunking):

```python
            buf = ""
            search_offset = 0
            for chunk in self._chunk_iter():
                buf += chunk
                start = 0
                while True:
                    end = buf.find("\n", start + search_offset) + 1
                    if end:  # if find() returned -1, end would be 0
                        yield buf[start:end]
                        start = end
                        # reset the search offset
                        search_offset = 0
                    else:
                        # this will happen eventually
                        buf = buf[start:]
                        # set search offset so we do not need to scan this part of the buffer again
                        search_offset = len(buf)
                        break
                if buf: <--- ERROR HERE
                    yield buf + '\n'
```
Since that last line is correctly completed in the next iteration of the loop anyway (by concatenating it to the next chunk), the buffer should only be cleared for the very _last_ chunk instead for each chunk. As a consequence of the faulty yielding of the buffer, the truncated last line is followed by the correct 'merged' line in the output. To fix this issue, I suggest that the last section of the code shown above should be indented one less (is there an elegant way to say this?) to only return the remainder of the very last chunk:

```python
            buf = ""
            search_offset = 0
            for chunk in self._chunk_iter():
                buf += chunk
                start = 0
                while True:
                    end = buf.find("\n", start + search_offset) + 1
                    if end:  # if find() returned -1, end would be 0
                        yield buf[start:end]
                        start = end
                        # reset the search offset
                        search_offset = 0
                    else:
                        # this will happen eventually
                        buf = buf[start:]
                        # set search offset so we do not need to scan this part of the buffer again
                        search_offset = len(buf)
                        break
            if buf: <--- FIX HERE
                yield buf + '\n'
```

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for the report and detailed diagnosis. You're exactly right, this is a copy/paste error from the code that was lifted over from mrjob:

https://github.com/Yelp/mrjob/blob/9e212d0b8742eb7ba2e8586ebbeadfc42c92c573/mrjob/util.py#L98

We don't actually make much use of this since the streaming approach did not work great in practice, so I think that's why we haven't seen any reported issues. I appreciate you saving us future debugging. Thanks again.
