### ISSUE TITLE
Attribute error of unknown provenance in variation.prioritize

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#864]
When running bcbio with the latest GEMINI development version 0.15.1 (which likely is unsupported as of yet by bcbio) I get a warning:

```shell
indexing all columns execpt 'gts'; to index that column, run gemini bcolz_index SAMPLENAME-vepeffects-ploidyfix-filter.db --cols gts
```

and later a critical error for each sample:

```shell
File "bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.py", line 92, in _prep_priority_filter
    ref_depth = row.gt_ref_depths[sidx]
AttributeError: 'GeminiRow' object has no attribute 'gt_ref_depths'
```
Perhaps these two are related; of course I am not expecting bcbio to support upstream development versions of GEMINI, but I thought it may be worth the heads up.

**Comment by schelhorn** [comment]
Hmm, I am getting the same error with the current GEMINI master installed by the bcbio installer (which is supposed to be stable, as far as I have understood). I am running in tumor-only mode with variant2/Freebayes. Full traceback is:

```python
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 39, in _setup_logging
    yield config
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 146, in postprocess_variants
    return ipython.zip_args(apply(variation.postprocess_variants, *args))
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/pipeline/variation.py", line 28, in postprocess_variants
    data["vrn_file"] = prioritize.handle_vcf_calls(data["vrn_file"], data)
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.py", line 35, in handle_vcf_calls
    priority_file = _prep_priority_filter(gemini_db, data)
  File "/cluster/software/bcbio_dev/lib/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.py", line 92, in _prep_priority_filter
    ref_depth = row.gt_ref_depths[sidx]
```

Does anyone have an insight why this is happening? Everything went fine in the run from last week that used the bcbio development version from that time.

**Comment by schelhorn** [comment]
I guess I will have to get a look at the GEMINI and cyvcf code to see what happens with my VCF file here. It's strange though that GEMINI can be queried but does not fill in that attribute.

**Comment by schelhorn** [comment]
Alright, found it. But it's a weird error that I assume must result from some upstream changes in GEMINI. The error originated in [bcbio.variation.prioritize](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/prioritize.py#L92) where it says:

```python
ref_depth = row.gt_ref_depths[sidx]
alt_depth = row.gt_alt_depths[sidx]
```

`row` is a [GeminiRow](https://github.com/arq5x/gemini/blob/master/gemini/GeminiQuery.py#L383) here. While brief inspection of the GeminiRow sources did not reveal where the key-to-attribute magic takes place, it seemed likely that something went amiss in that mapping based on the error message. When I changed the code snippet in bcbio.variation.prioritize to work with keys instead of attributes, everything ran fine:

```python
ref_depth = row['gt_ref_depths'][sidx]
alt_depth = row['gt_alt_depths'][sidx]
```

So unfortunately I could not track it further down; still, I would appreciate @chapmanb to have a look since he knows both code bases well. In any event, I'd appreciate the fix to make it into bcbio if no further disadvantages of using keys here present themselves.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks so much for the debugging and apologies in the delay in getting back to you on this. You are exactly right with the fix, although I'm also not sure what happened with the GEMINI API.

I pushed this so if you update things should work cleanly going forward. Sorry again about the issue.

As an FYI, the bcolz warning is not an issue. Brent doesn't generally recommend indexing `gts` with bcolz so it is more of a heads up when designing queries than anything to worry about:

http://gemini.readthedocs.org/en/latest/content/genotype_query_engines.html#bcolz-indexes

Thanks again.
