### ISSUE TITLE
Setting pybedtools tmp folder when using bcbio on cluster

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#866]
Hi Brad

I am trying to analyze an exome through bcbio. I submit the bcbio_nextgen.py command to the cluster and let iPython handle the further parallelization of the analysis. This all works fine to some point.

When the analysis starts pybedtools, it assigns the tmp folder to the local disk. On our cluster system this disk is only 10GB, which is not big enough to hande a 30GB exome. Is it possible to change the default tmp folder for pybedtools? I know pybedtools itself supports this option through "pybedtools.set_tempdir(tempdir)", but is there an option to let bcbio know to use another tmp folder instead of the default?

Thx!
Greetings,
Matthias

**Comment by schelhorn** [comment]
Hi Matthias,

if pybedtools uses the global tmp in bcbio then [this part of the documentation](https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#temporary-directory) my help you.

**Comment by matthdsm** [comment]
I cannot believe I overlooked this option, as you said, even after reading the readthedocs you still miss things.

Thanks for the tip
Closing

Matthias
