### ISSUE TITLE
Two defects in _extract_split_and_discordants limit scalability

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#868]
There are two smaller defects in [bcbio.structural.shared. _extract_split_and_discordants()](https://github.com/chapmanb/bcbio-nextgen/blob/74b3c80106fdeb4bc85a99c35fb1d617ffb6d22f/bcbio/structural/shared.py#L197) that limit scalability. 

The more critical of the bunch is a wrong application of `os.path.join`. For `os.path.join`, if you want to join two paths and the second path starts with a `/`, the paths are not joined at all [but the second path is taken as the result of the function, no warnings issued](http://stackoverflow.com/questions/1945920/os-path-join-python/1945930#1945930). As a consequence in [line 215 of that function](https://github.com/chapmanb/bcbio-nextgen/blob/74b3c80106fdeb4bc85a99c35fb1d617ffb6d22f/bcbio/structural/shared.py#L215), since `in_bam` is a absolute path, the temporary directory is not actually used for the sorted chunks by `samtools sort`, but all the sorted temporary data is written in the working directory where the input BAM file resides. If that happens to be on NFS and you have  10 nodes or so all sorting in parallel, then your NFS will likely crash (happened to me). The obvious fix here is to get rid of the leading directories in the variable `in_bam` using `os.path.basename`. In addition, I strongly suggest to check all occurrences of `os.path.join` in bcbio to make sure that this did not happen somewhere else. It's very easy to  make the mistake of using an absolute path as the second argument since the resulting path (the second argument) is usually existing and writable, so no IOError will be triggered. Still, I do not know what Guido van Rossum was smoking when he wrote that function.

The second issue is [line 205](https://github.com/chapmanb/bcbio-nextgen/blob/74b3c80106fdeb4bc85a99c35fb1d617ffb6d22f/bcbio/structural/shared.py#L205) where all the resource specs for the calls are from the `sambamba` entry of the resource config. Since that does not exist in the resource YAML, I believe it will always default to the 2G. Other calls of `sambamba` in bcbio use the `samtools` resource config instead, and I believe that is what should be done here.

**Comment by schelhorn** [comment]
I may also add that the `samtools` call in that command is using the old `samtools sort` syntax. The [other occurrence](https://github.com/chapmanb/bcbio-nextgen/blob/36a7ad760a75b45039e73a8265eef4db1cd71c23/bcbio/ngsalign/postalign.py#L91) where bcbio is using name sorting by `samtools` is using the new syntax. Perhaps it can make sense to refactor the functionality into an extra function or at least standardize the command line call format.

**Comment by schelhorn** [comment]
So, another observation that has to do with that function: I am running several `svcaller` and the discrodant read extraction seems to happen for _each of them_ for the same sample. They go in `structural/SAMPLENAME/delly`, `structural/SAMPLENAME/lumpy` and so forth, each with its own command to sort the main input BAM file and store the same set of discordant reads. Could we please change this so that this expensive operation is done only once?

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the issues and thanks for the detailed diagnosis. This code hasn't gotten any love in a while since I don't often do SV calling from pre-aligned inputs. I pushed several fixes which I think will resolve the issues you were seeing. Apologies for this being so terrible before and hope it behaves better now.

**Comment by schelhorn** [comment]
Thanks a bunch, I'll test. The input wasn't pre-aligned, though - full pipeline from FASTQ.

**Comment by chapmanb** [comment]
That makes sense since the output of disambiguation doesn't have paired/split analysis applied to it. Hopefully the updated version will deal with this better.

**Comment by schelhorn** [comment]
Sorry, Brad, but the issue is not closed yet. The function still sorts in the global working directory, and not in the node-local tmp directory. The line

```python
out_base = os.path.join(tmpdir, "%s-namesort" % os.path.splitext(os.path.dirname(in_bam))[0])
cmd = ("{samtools} sort -n -@ {cores} -m {mem} -O sam -T {out_base} {in_bam} | ")
```

again tells `samtools` to use the path of the input BAM for the temporary data since it is an absolute path. Would using `basename` make more sense? Else I will have NFS problems again. Thanks!

**Comment by chapmanb** [comment]
Sven-Eric -- sorry, that is my mistake. Thanks for catching that typo. I pushed that fix which will hopefully actually resolve the issue. Let me know if you run into anything else at all. Thanks again.
