### ISSUE TITLE
Include additional FASTQC statistics into project-summary.yaml

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#871]
This is an enhancement (feature) request. As it stands right now it is difficult to compare the sequence qualities of multiple samples since the most important QC report for that purpose, generated by `fastqc`, is only stored per-sample and not included into `project-summary.yaml` in a more complete manner (only some single-value statistics are extracted from `fastqc_data.txt`). Since generally the more complex, XY-plot `fastqc` statistics are most usable if compared across multiple samples, I suggest that the raw `fastqc` values from `fastqc_data.txt` could be parsed and included into `project-summary.yaml` as a dictionary of dictionaries to allow access by downstream multi-sample QC plotting. This could be done without writing an extra parser for accessing `fastqc_data.txt` by using an [externally developed parser `fastqc` parser](https://github.com/fadapa/fadapa/tree/master/fadapa) that could replace [the existing parser](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/qcsummary.py#L255).

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for the thoughts. We've got some other open requests to better handle fastqc output (#792) so this is definitely a project we want to tackle. Generally, I'd avoid piling more information into project-summary.yaml since that is really only a stop gap. Typically projects can get broken across multiple bcbio runs (and multiple project summaries) and it would be nice to have something that generates summaries based on parsing output directories and sample qc files. This would let people develop custom summary functions independent of bcbio itself.

I know @lpantano has done some initial work on this. Lorena, do you have thoughts on the best way to handle these and do a better job of exposing metrics for summarizing?

**Comment by lpantano** [comment]
Hi Sven-Eric, 
I have some code that take some of the metrics, like quality per position and nt content and put all samples together in a matrix.  This is what sometimes I plot in the reports to get all samples in the same figure. If this sounds good to both, I can port that into bcbio and make this file goes to the final directory inside the project folder.

I can use that module that you point plus my code to merge all samples together.

**Comment by lpantano** [comment]
Hi,

I just pushed some code to create inside the `qc` folder for each sample one file per FASTQC section adding a column with the sample name. 

I don't know if you as well agree/like to add a file for each section with all sample in the final `project` folder at the same level of `project_summary.yaml` or not. Let me know what you think about this.

**Comment by schelhorn** [comment]
Thanks - great work! However, I get a `ImportError: No module named fadapa` after updating bcbio to the latest development release and running a sample. Also, the module was not installed by Anaconda during the update.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for testing. I'm confused as to why it fails to add fadapa since it's listed in the requirements.txt. While we debug, I made the module optional so it won't cause other issues with bcbio in general. You can fix your in-place installation by doing:
```
/path/to/bcbio/anaconda/bin/pip install fadapa
```
Thanks again.

**Comment by schelhorn** [comment]
Excellent. I will finish my test run and am happy to close this issue once it has completed successfully.

**Comment by mjafin** [comment]
I saw the fadapa error too when trying to upgrade. Pip install fixed it though.

**Comment by schelhorn** [comment]
Finished successfully on a larger batch - thank you @lpantano. Closing.
