### ISSUE TITLE
fail to upgrade bcbio-nextgen

### ISSUE THREAD

**Issue by drtamermansour** [chapmanb/bcbio-nextgen#875]
Hi,
I successfully installed bcbio using 
```python bcbio_nextgen_install.py /disk/bcbio --tooldir=/disk/tools \
       --genomes GRCh37 --aligners bwa --aligners bowtie2 -u development```

I changed the PATH as described 
```export PATH="/disk/tools/bin:/disk/bcbio/anaconda/bin:${PATH}"```

and I ran the pipeline 
```bcbio_nextgen.py ../config/NA12878-exome-methodcmp.yaml -n 8```

The pipeline failed for the lack of GATK. So I am trying to update to install GATK using:
``` bcbio_nextgen.py upgrade -u development --tools --tooldir=/disk/tools --toolplus gatk=/disk/GenomeAnalysisTK-3.4-0.tar ```

But this fails. Here is the last couple lines of the debug:

[localhost] local: /disk/tools/bin/brew info rna-star
Fatal error: local() encountered an error (return code 1) while executing '/disk/tools/bin/brew info rna-star'
Aborting.
local() encountered an error (return code 1) while executing '/disk/tools/bin/brew info rna-star' 


Can you help me with this? 
Thank you

**Comment by roryk** [comment]
Hi Tamer,

homebrew-science just added this formula which might have been causing a conflict. I deleted the formula we were maintaining from homebrew-cbl, so hopefully this problem will be resolved. If you type:

```
/disk/tools/bin/brew unlink rna-star
```

it should fix it. Let me know if that doesn't do the trick.

**Comment by drtamermansour** [comment]
Thanks @roryk,
I just re-run the update command after your commit and it completed successfully. 
But it worth to mention that the debug of the update command showed couple warnings of failed commands. 

[localhost] local: /disk/tools/bin/brew unlink openssl
Error: No such keg: /disk/tools/Cellar/openssl
Warning: local() encountered an error (return code 1) while executing '/disk/tools/bin/brew unlink openssl'
[localhost] local: /disk/tools/bin/brew unlink curl
Error: No such keg: /disk/tools/Cellar/curl
Warning: local() encountered an error (return code 1) while executing '/disk/tools/bin/brew unlink curl'
 
Hopefully this is not affecting the performance of the software.

Thanks again

**Comment by roryk** [comment]
Hi Tamer,

Great, thanks for following up, glad that fixed your problem. Those errors are from trying to uninstall formula that aren't installed already, so they are harmless.
