### ISSUE TITLE
Wrong reference to genome Danio rerio

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/bcbio-nextgen#876]
Hi Brad,

When trying to install the reference genome for Danio rerio through the upgrade option "--genomes Zv9", the python script tries to download ftp://ftp.ensembl.org/pub/release-78/fasta/danio_rerio/dna/Danio_rerio.Zv9.78.dna.toplevel.fa.gz however, the reference at the Ensembl ftp server is named Danio_rerio.Zv9.dna.toplevel.fa.gz.

just a heads up

Greetings
Matthias

**Comment by chapmanb** [comment]
Matthias -- thanks much for the heads up on the problem. I updated the Ensembl based genomes to use the latest releases and also conform to the new file naming, so they should hopefully work cleanly for you now. Let us know if you run into any other issues at all and thanks again.
