### ISSUE TITLE
"bcbio_nextgen.py upgrade --tools" makes brew error

### ISSUE THREAD

**Issue by yong27** [chapmanb/bcbio-nextgen#877]
I'm upgrading bcbio-nextgen, 

    $ bcbio_nextgen.py upgrade --tools

It makes brew error like follows and stopped.

    ....
    [localhost] local: /home/isg/tools/bin/brew info vcflib
    
    Fatal error: local() encountered an error (return code 1) while executing '/home/isg/tools/bin/brew info vcflib'
    
    Aborting.
    local() encountered an error (return code 1) while executing '/home/isg/tools/bin/brew info vcflib'

brew command result is like follows.

    $ /home/isg/tools/bin/brew info vcflibError: Formulae found in multiple taps:
     * homebrew/science/vcflib
     * chapmanb/cbl/vcflib
    
    Please use the fully-qualified name e.g. homebrew/science/vcflib to refer the formula.   

How can I resolve this problem?

**Comment by chapmanb** [comment]
Hyungyong;
Sorry about the issue and thanks for letting us know about the problem. It looks like vcflib made it into homebrew-science and was conflicting with the CloudBioLinux copy. I removed the CBL specific one so if you re-run the update it should now proceed cleanly. Thank you again for the report.

**Comment by yong27** [comment]
I confirmed the error was fixed. 

Thank you for quick fix and great program.
