### ISSUE TITLE
Uncaught exception occurred during installation

### ISSUE THREAD

**Issue by wangx677** [chapmanb/bcbio-nextgen#880]
My computer system is Ubuntu 14.04.2 LTS. I attached the screenshots which shows the most recent calls. It seems to me the installation is completed and only the cleanup procedure is left. The line 41 of ""bcbio_nextgen_install.py" is:
subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))

![screenshot](https://cloud.githubusercontent.com/assets/12767795/8014503/07bf8e94-0b97-11e5-9dc9-eab10e2426ba.png)

**Comment by lpantano** [comment]
Hi wangx677,

sorry about that, I think I know the error, but could you try to do this command to get the complete error.

`vep_install.pl -a c -s homo_sapiens_vep_79_GRCh37 -c ...` mainly the command you see at the beginning of the screenshot, just below Prepare VEP directory.

You can copy/paste the terminal output here.

**Comment by wangx677** [comment]
It's working ... thank you!
I can see "homo_sapiens_vep_79_GRCh37.tar.gz" is being downloading to vep/tmp folder. What should I do to continue after this is finished?

bcbio/bin/vep_install.pl -a c -s homo_sapiens_vep_79_GRCh37 -c /project/csbio/wwang/NGS/bcbio/genomes/Hsapiens/GRCh37/vep
Getting list of available cache files
Could not get current species list - using predefined list instead
For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
 - downloading ftp://ftp.ensembl.org/pub/release-79/variation/VEP/homo_sapiens_vep_79_GRCh37.tar.gz

**Comment by lpantano** [comment]
wait until the end, this command is the one that fails, so it should fail again. If not, it's something else. Let us know if that command finishes without problem.

**Comment by wangx677** [comment]
hi lpantano, the command is finished without any problem. What's your suggestion for next step? Thank you!

**Comment by lpantano** [comment]
Hi,

when this happened to me, the command alone failed as well, so should be another thing. In my case the tool could not download the file due to some misplaces of the certificates.

did you try to run again the installation after the last command?

so sorry not to have an idea right now,  but let's see if the error changes now.

thanks!

**Comment by chapmanb** [comment]
Sorry about all the problems. This looks like the same issue resolved here: https://github.com/chapmanb/bcbio-nextgen/issues/863#issuecomment-105898916 You can either grab the latest development version (add `-u development` to the install command) or add the installation directory to your PATH. Hope this helps finish the installation cleanly.

**Comment by wangx677** [comment]
Hi Brad,

Adding the installation directory to my PATH solved the problem. Thank you!

Wen
