### ISSUE TITLE
Q: Python 3 support?

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#883]
So I read in the docs that Python 2.7 is needed. Is this a minimum and Python 3 is also supported or is only Python 2.x working so far?

**Comment by chapmanb** [comment]
Michael;
Only Python 2.7 is supported, we haven't done any work to port to Python 3. It would be a fairly large project as we'd need to be sure all of the dependencies have up to date Python 3 ports, then convert over the code and work off a codebase that supports both. Practically, we're not planning this in the near term. Do you specifically need 3 for a specific reason, or just curious? Thanks for looking into bcbio.

**Comment by mpschr** [comment]
Hi, Thanks for your answer

Well I was thinking about calling bcbio pipelines from a python3 environment, as the pipeline for further processing is in Python3 environments.

I think I can still do it by changing loading a different conda environment temporally. Nevertheless it is not very elegant and forces me to install many libraries twice (Py2 & Py3) with each pipeline install.

It's a pity that the dependencies make it more difficult, as Py3 has lots to offer - May it fit into a GSOC project? 'Translator' scripts may help the initial adaption.
I don't know really how tedious it is to support both Py2 and Py3 at the same time,but I think large projects as Pandas manage to do so.

Best,
Michael
