### ISSUE TITLE
Installation from conda-environment fails

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#884]
Hi

So my computer is set up that python3 is the default python, via an anaconda installation. Therefore I created an anaconda env for python2, called `py2`, in order to be able to install bcbio_nextgen. Once I am in my `py2` environment, I follow the automatic setup guide with the following command:
```python bcbio_nextgen_install.py ~/bin/bcbionextgen/data/ --tooldir ~/bin/bcbionextgen/tools/ --genomes hg38 --aligners star --aligners bwa```

This is followed by an error, raised by conda itself complaining as follows: `Error: environment does not exist: ~/bin/bcbionextgen/data/anaconda/envs/py2`. 

I am not sure if this is a problem of the installer script or the anaconda environment. Has somebody succeeded isntalling bcbio_nextgen from a conda environment? 

For completion, below the full terminal output

```
Checking required dependencies
git version 1.9.1
Installing isolated base python installation
--2015-06-11 09:46:59--  http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh

[..]

Proxy request sent, awaiting response... 200 OK
Length: 20736312 (20M) [application/octet-stream]
Saving to: ‘Miniconda-3.5.5-Linux-x86_64.sh’

100%[================================================================================================================>] 20.736.312  6,09MB/s   in 4,0s   

2015-06-11 09:47:04 (4,96 MB/s) - ‘Miniconda-3.5.5-Linux-x86_64.sh’ saved [20736312/20736312]

PREFIX=~/bin/bcbionextgen/data/anaconda
installing: python-2.7.7-0 ...
installing: openssl-1.0.1h-0 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_0 ...
installing: readline-6.2-2 ...
installing: requests-2.3.0-py27_0 ...
installing: sqlite-3.8.4.1-0 ...
installing: system-5.8-1 ...
installing: tk-8.5.15-0 ...
installing: yaml-0.1.4-0 ...
installing: zlib-1.2.7-0 ...
installing: conda-3.5.5-py27_0 ...
Python 2.7.7 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Installing bcbio-nextgen
Fetching package metadata: ..
Error: environment does not exist: ~/bin/bcbionextgen/data/anaconda/envs/py2
#
# Use 'conda create' to create an environment before installing packages
# into it.
#
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 261, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 35, in main
    install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 99, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes", "numpy"])
  File "~/bin/anaconda3/envs/py2/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['~/bin/bcbionextgen/data/anaconda/bin/conda', 'install', '--yes', 'numpy']' returned non-zero exit status 1
```

**Comment by mpschr** [comment]
FIY: I found a way using another python2 (from the system) and can use the installer script. You can close the isssue if you feel it doesn't really concern bcbio_nextgen, but is rather an anaconda (setup) problem

**Comment by chapmanb** [comment]
Michael;
Thanks for the report and sorry about the issues. I don't believe you can use conda inside conda with environments set, since it uses environmental variables and will then expect to be using the external environmental inside of the internal one.

I know you already got this sorted out, but I also adjusted the install script so it'll work with Python 3.x and not need special setups. I definitely like Python 3 and want to keep moving towards it, but we haven't found the time to do a full port. At least this way it's easier to bootstrap bcbio from multiple Python environments. Thanks again for the reports and discussion.

**Comment by mpschr** [comment]
That's already great news!
Thanks
