### ISSUE TITLE
Automatic installation fails at installing VEP

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#885]
At this step, the installation fails

```export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/mpschr/bin/bcbionextgen/tools/lib/perl5:${PERL5LIB} && /home/mpschr/bin/bcbionextgen/tools/bin/brew install -v --env=inherit vep```

It seems that there may be a problem with the proxy or the firewall where I'm sitting behind as it seems a file is not downloaded correctly. I have seen other people have reported similar problems, but I'm not sure how to tackle the problem.

The log file of the command above as well as the terminal output can be found [here](https://gist.github.com/mpschr/8431320be88edbd9851e#file-log-file) and [here](https://gist.github.com/mpschr/8431320be88edbd9851e#file-terminal-output)

**Comment by lpantano** [comment]
Hi Michael,

sorry about that. I had a similar problem. In my case I am in ubuntu and 
needed to do this:

http://askubuntu.com/questions/342484/etc-pki-tls-certs-ca-bundle-crt-not-found

this post talk about issue related to anaconda:

https://bbs.archlinux.org/viewtopic.php?id=186138

Don't know if will solve it, but you can check if these posts are useful.

**Comment by mpschr** [comment]
Hi Lorena!

You nailed it. The three commands below fixed the problem

`sudo mkdir /etc/pki/tls`
`sudo mkdir /etc/pki/tls/certs`
`ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt`

Would there be away to tell curl to look in the other directory, in case the flat `--distribution ubuntu` is set? I'm thinking of users without sudo rights..

**Comment by mpschr** [comment]
According to http://curl.haxx.se/docs/manpage.html, the `--cacert /path/to/ca-bundle.crt` may fix the problem. I didn't verify that myself though (still installing all the software)

**Comment by chapmanb** [comment]
Michael;
Where is the curl you're using coming from? The system or an anaconda package installed by bcbio? We try not to install curl or get it into the PATH to avoid all this and rely on the underlying system. The tough thing about working around this is that curl is called here by the VEP installer so we could have to do a bunch of hacks to generalize this by figuring out where the certificates are on the user's system and patching the installer to point to them. I worry this will be pretty kludgy and the source of more errors. Our thought process is rather to say that we expect a working version of curl on the system and try not to accidentally break it with the bcbio install.

**Comment by mpschr** [comment]
Hi,
How do I find out which curl was being used from the installation call? In any case, the problem was the underlying system dependencies (ca-bundle in wrong place).

But if curl is called by VEP it is a VEP bug/problem then.

**Comment by chapmanb** [comment]
Michael;
It uses the first curl in your PATH, so `which curl` should tell you. I want to make sure we're not introducing a problematic curl at some point in the installation process, and generally try to improve things however we can. Thanks again.

**Comment by mpschr** [comment]
Hi Brad

So, if I open the terminal and type `which curl`, it indeed points to the anaconda version of curl, but from my own anaconda installation `~/anaconda3/bin/curl`. Maybe this is the origin of the problem?

**Comment by chapmanb** [comment]
Michael;
That makes sense, and is likely the origin of the problem. The anaconda curl seems to expect a RedHat/CentOS directory structure for certificates so won't work properly on Ubuntu/Debian style systems. Your best bet might be to `~/anaconda3/bin/conda uninstall curl` and use the system one to avoid issues. Thanks for the help tracking this down.

**Comment by mpschr** [comment]
Yes. For general info (people that land here), here is somebody describing and explaining this error in the last [post](https://bbs.archlinux.org/viewtopic.php?pid=1450557#p1450557), a year ago. I quote:

> However, the issue was caused by the Python distribution from 'Anaconda' (https://store.continuum.io/cshop/anaconda/). 
> Following their instruction I added the "bin" folder contained in the Anaconda package to my PATH variable.
> The Anaconda distribution comes with an older version of curl that searches for the certificates in the non existing path /etc/pki/tls/certs/ca-bundle.crt.
