### ISSUE TITLE
Sample upload to S3 does not occur in parallel

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#886]
This issue relates to `multicore2` parallel environment step in the `variant2` workflow. At the end of that environment, the final data is uploaded to the `upload` target via [the code](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/main.py#L192):

```python
            with profile.report("upload", dirs):
                for sample in samples:
                    run_parallel("upload_samples", [sample])
```

Due to the `for` loop, this process seems to be entirely sequential in nature (as regards parallelism over samples). Although the `multicore2` parallel environment keeps all IPython engines running that were provisioned for the previous steps, only one of that engines (i.e., one node) is actually working. This is bad news in two ways: firstly we have to pay for the full parallel environment since the engines persist on the idle nodes (which can be a hundred or so in our case), and second only a minute fraction of the available upload bandwidth is actually used (again limited to the network IO of single node, even if `aws s3` is configured perfectly).

I am well aware that this issue is again specific to the cloud users (similar to issue #874) who may be able to stomach a lot of storage IO and network IO due the use of distributed file systems and/or direct S3 archival, the latter of which is ridiculously parallel only if you compute on EC2. Other users with a shared setup and limited aggregate storage IO/network IO may not enjoy these advantages and may thus want to forego parallel FASTQ download/bgzip prep/results upload.

However, for people who would like to scale the process to hundreds of samples on a regular basis, these three steps (FASTQ download/bgzip prep/results upload) are rate-limiting since they are now the only ones left in bcbio that are not well parallelized. At least for the upload case, it would be simple (I believe) to truly parallelize upload by removing the for loop and submit all samples at once to `run_parallel`. While there are obviously ways to patch the code for yourself and remove the safeties, this is not very maintainable and also doesn't help other users in solving the same problem. 

So, is there anything you guys could do for us snobby cloud users, pretty please?

**Comment by chapmanb** [comment]
Sven-Eric;
Sorry about the issues and upload slowness. This code also suffers from being developed for handling uploads from a single machine. The tricky part is that the code also handles uploads of shared project data, so we need to avoid doing this in parallel to prevent partial/over-writing uploads.

I tried to improve it by splitting the sample loading across multiple machines, which will parallelize the larger BAM file uploads. Project specific uploads happen in a second run which isn't fully parallelized by should be smaller file. Hope this works for you and prevents the bottlenecks. Thanks again for all the feedback and suggestions.

**Comment by schelhorn** [comment]
Excellent; thank you very much for supporting my request.
