### ISSUE TITLE
'cmake' problem again

### ISSUE THREAD

**Issue by yji1983** [chapmanb/bcbio-nextgen#887]
[localhost] local: wget --continue --no-check-certificate -O cmake-3.2.3.x86_64-linux.bottle.tar.gz 'https://s3.amazonaws.com/cloudbiolinux/brew_bottles/cmake-3.2.3.x86_64-linux.bottle.tar.gz'
--2015-06-16 10:24:38--  https://s3.amazonaws.com/cloudbiolinux/brew_bottles/cmake-3.2.3.x86_64-linux.bottle.tar.gz
Resolving s3.amazonaws.com... 54.231.17.184
Connecting to s3.amazonaws.com|54.231.17.184|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-06-16 10:24:38 ERROR 404: Not Found.

Warning: local() encountered an error (return code 8) while executing 'wget --continue --no-check-certificate -O cmake-3.2.3.x86_64-linux.bottle.tar.gz 'https://s3.amazonaws.com/cloudbiolinux/brew_bottles/cmake-3.2.3.x86_64-linux.bottle.tar.gz''

[localhost] local: rm -rf /home/ec2-user/.cache/Homebrew/f80958f9-20fd-3c3f-a912-480e3532b539
[localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/lib/perl5:${PERL5LIB} && /home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/bin/brew install --env=inherit  --without-docs  cmake

Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/lib/perl5:${PERL5LIB} && /home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/bin/brew install --env=inherit  --without-docs  cmake'

Traceback (most recent call last):
  File "/home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", line 231, in _install_pkg_latest
    cmd.replace("brew install", "brew install -v"))
ValueError: Failed to install brew formula: cmake
To debug, please try re-running the install command with verbose output:
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/lib/perl5:${PERL5LIB} && /home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/bin/brew install -v --env=inherit  --without-docs  cmake
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 265, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 45, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/home/ec2-user/externalEBS/amidc83b9b4/python/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ec2-user/externalEBS/amidc83b9b4/ngsworkflow/bcbio/data/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir', './bcbio', '--aligners', 'bowtie', '--aligners', 'bowtie2', '--aligners', 'bwa', '--aligners', 'novoalign', '--aligners', 'snap', '--aligners', 'star', '--aligners', 'ucsc', '--distribution', 'centos', '-u', 'stable']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Sorry about the issue and thanks for the heads up on the problem. I pushed a bottle for the new 3.2.3 so installs should be able to use this instead of needing to build from scratch. Hope this gets the install working for you.
