### ISSUE TITLE
No main function in bcbio.workflow.xprize module

### ISSUE THREAD

**Issue by alexandrucoman** [chapmanb/bcbio-nextgen#890]
The ```main``` function is missing from the [bcbio.workflow.xprize](https://github.com/chapmanb/bcbio-nextgen/blob/30c48f194a2031986b57cf210cc2e37fea9ae2c0/bcbio/workflow/xprize.py#L81-82) module.

```
if __name__ == "__main__":
    main(*sys.argv[1:])
```

**Comment by chapmanb** [comment]
Thanks for the heads up on the old code. I pulled this out so it's no longer an issue. Much appreciated.
