### ISSUE TITLE
--downsample_to_coverage ERROR

### ISSUE THREAD

**Issue by jpmtavares** [chapmanb/bcbio-nextgen#894]
Hi,

I'm getting this error while trying to call variants in DNA-seq data:

 ##### ERROR MESSAGE: Invalid command line: Cannot use -dcov or --downsample_to_coverage for ActiveRegionWalkers, use another downsampling argument
##### ERROR ------------------------------------------------------------------------------------------

Am I doing something wrong?

**Comment by chapmanb** [comment]
Joana;
Sorry about the issue. If you're using GATK 3.4 you need the latest development version of bcbio which avoids setting `-dcov`:

https://github.com/chapmanb/bcbio-nextgen/commit/5729b2714a6d865aa3b53bafbdf8748134fa8399

You can upgrade with `bcbio_nextgen.py upgrade -u development`. We hope to have a new release soon with this fix. Hope this gets things running cleanly for you.
