### ISSUE TITLE
Gemini TypeError: 'sqlite3.Row' object does not support item assignment

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#904]
Hi,

bcbio somehow fails when trying to run the task 'Prioritize' part.

I not sure what more details I could give. Just ask if there is some important piece missing

```
/home/mpschr/bin/bcbionextgen/data/anaconda/lib/python2.7/site-packages/bcbio/variation/prioritize.pyc
     34             if gemini_db:
---> 35                 priority_file = _prep_priority_filter(gemini_db, data)
...........................................................................
     90                 writer.writerow(cheader)
     91                 for row in gq:
     92                     ref_depth = tz.get_in(["gt_ref_depths", sidx], row, 0)
     93                     alt_depth = tz.get_in(["gt_alt_depths", sidx], row, 0)
     94                     try:
---> 95                         row.row["freq"] = "%.2f" % (float(alt_depth) / float(ref_depth + alt_depth))
     96                     except ZeroDivisionError:
     97                         row.row["freq"] = "0.00"
     98                     row.row["filter"] = _calc_priority_filter(row, pops)
     99                     if row["chrom"] not in ref_chroms and _hg19_to_GRCh37(row["chrom"]) in ref_chroms:

TypeError: 'sqlite3.Row' object does not support item assignment
```

**Comment by mpschr** [comment]
I just realized, that altough this error occurs, gemini is running in the background - and the command seems to go just fine. But bcbio exits because of the above shown error

**Comment by chapmanb** [comment]
Michael;
Apologies, this is a problem with the latest GEMINI/sqlite where rows no longer allow assignment. I pushed a fix which creates a separate dictionary to collect results and avoids this issue. If you update to the latest development (`bcbio_nextgen.py upgrade -u development`) it should now work cleanly. Sorry again about the problem and thanks for the report.

**Comment by mpschr** [comment]
Hi Brad,
I can confirm that the fix works. Again, thanks for the quick reaction!
