### ISSUE TITLE
Add-on CNV calling

### ISSUE THREAD

**Issue by pengxiao78** [chapmanb/bcbio-nextgen#905]
I have finished the regular cancer somatic variants analysis for tumor-normal paired samples. But now I need to get CNV structural variants. Can I just input the svcaller: [lumpy, cnvkit] in the algorithm of yaml file without the previous vcaller: [mutect, vardict, varscan] in the add-on analysis to save time?
Thank you!

**Comment by chapmanb** [comment]
Absolutely. If you run in the same work directory add in the `svaller` arguments, remove the `checkpoints_parallel` directory to tell bcbio to parallelize analyses again, then re-run and it will only run the SV calling steps and move past all the completed steps. Hope this helps.

**Comment by pengxiao78** [comment]
I am running this with adding svaller: cnvkit. The running still ongoing. My question is whether I can also get somatic CNV vcf file when I use tumor and normal paired samples. Thanks.

**Comment by chapmanb** [comment]
Yes, bcbio provides somatic calls with subtraction of events present in the normal. For CNVkit this is done by using the normal as the background and reporting events present relative to it in the tumor. Hope this helps.
