### ISSUE TITLE
Full conda based install?

### ISSUE THREAD

**Issue by kyleabeauchamp** [chapmanb/bcbio-nextgen#909]
I noticed that you guys have lots of useful conda packages, but the primary installation involves downloading of a separate anaconda installation (AFAIK).  Is there an installation pathway that uses an existing conda installation?  Presumably it would be possible to build, e.g., the aligners using a conda recipe and dump their binaries in a conda environment.  Just curious.

**Comment by chapmanb** [comment]
Kyle;
bcbio-vm (https://github.com/chapmanb/bcbio-nextgen-vm) takes this installation approach. All of the Python dependencies get installed via conda in any Anaconda distribution, and the external dependencies like aligners are isolated inside Docker containers. The build process for bcbio now uses multiple package managers, including a lot of recipes from the Homebrew science community, so moving all external packages to conda isn't a target we have in mind. The long term vision is to move more and more to a pre-built containerized set of tools with a conda wrapper that drives them. Hope this helps explain the general plans, happy to answer more specific questions. Thanks again.

**Comment by kyleabeauchamp** [comment]
Thanks, makes sense.
