### ISSUE TITLE
out of memory in the gatk part of piped_bamprep

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#912]
Where might I up the memory for the following step? I didn't see anything obvious in bcbio_system.yaml.

`gatk-framework -Xms250m -Xmx666m -XX:+UseSerialGC -U LENIENT_VCF_PROCESSING --read_filter BadCigar --read_filter NotPrimaryAlignment`

[log](https://gist.github.com/1fd8737306f028326000)

**Comment by lpantano** [comment]
Hi,

I think you can increase gatk tag inside bcbio_system.yaml. But will 
affect any step where GATK is used.

**Comment by dwaggott** [comment]
Not sure, that points to the system gatk not the MIT components that gatk-framework uses. Also, the defaults are already `-Xmx3500m` which is quite a bit higher than what's in the logs.

**Comment by lpantano** [comment]
i see. Some times we change the memory according to some other values. You can try to add gatk-framework to the bcbio_system and add a higher memory to see if with 6Gb still you see 666m.
sorry no to have a better solution right now.

**Comment by dwaggott** [comment]
Okay, seems to work now. Maybe a line in the docs informing the user that gatk and gatk-framework require different resource requests.

```
resources:
  gatk-framework:
    jvm_opts: ["-Xms2g", "-Xmx4g"]
```

**Comment by chapmanb** [comment]
Daryl and Lorena;
Sorry about the issues and glad you got it figured out. You can use `gatk-framework` if you choose, but if that is not present in your `bcbio_system.yaml` file it will fall back to `gatk`. It is meant to allow flexibility but not require it. You can see the logic here:

https://github.com/chapmanb/bcbio-nextgen/blob/60493e5fee849cf19e7f4a315c9ba09491cfe7b6/bcbio/broad/__init__.py#L54

Some of these steps use a lot of items in parallel so the memory gets scaled down to avoid memory issues as GC gets cleaned up. Your solution will certainly work, or you can just leave `gatk` only and increase the memory there. Hope this helps.
