### ISSUE TITLE
bad zip file dbNSFPv2.9.zip

### ISSUE THREAD

**Issue by YiChingTang** [chapmanb/bcbio-nextgen#913]
Hi, wondering is there any way i fix the following problem?

Archive:  dbNSFPv2.9.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [dbNSFPv2.9.zip]:  4090128276 extra bytes at beginning or within zipfile
  (attempting to process anyway)
   skipping: dbNSFP2.9_variant.chr1  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr2  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr20  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr21  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr22  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr3  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr4  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr5  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr6  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr7  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr8  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chr9  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chrX  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP2.9_variant.chrY  need PK compat. v4.5 (can do v2.1)
   skipping: LICENSE.txt             need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP29.class   need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP29.java    need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP29.readme.pdf  need PK compat. v4.5 (can do v2.1)
   skipping: try.vcf                 need PK compat. v4.5 (can do v2.1)
   skipping: tryhg18.in              need PK compat. v4.5 (can do v2.1)
   skipping: tryhg19.in              need PK compat. v4.5 (can do v2.1)
   skipping: tryhg38.in              need PK compat. v4.5 (can do v2.1)
file #1:  bad zipfile offset (local header sig):  4090128276
  (attempting to re-compensate)
replace dbNSFPv2.9/dbNSFP2.9.readme.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

Fatal error: local() encountered an error (return code 2) while executing 'unzip dbNSFPv2.9.zip -d dbNSFPv2.9'

**Comment by chapmanb** [comment]
Apologies about the issue. I bumped the download to the latest dbNSFP release and it should hopefully now download and install cleanly. When you restart remove the cached cloudbiolinux (`rm -rf tmpbcbio-install`) and it will grab the latest version. Hope this gets everything installed for you.

**Comment by YiChingTang** [comment]
thank you for the quick reply and the solution.

I restarted the installation, and it works....(?!)
the confusions is I still get the same err msg yet followed by the installation complete  msg
don't know if I successfully installed the dbNSFP this time, should I update my bcbio_nextgen.py script and restart again?

**Comment by YiChingTang** [comment]
forget to paste the installation log....

2015-07-01 09:33:36 (1000 KB/s) - “dbNSFPv3.0b2c.zip” saved [6281431546]

Archive:  /opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [/opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip]:  1986460357 extra bytes at beginning or within zipfile
  (attempting to process anyway)
   skipping: dbNSFP3.0b2c_variant.chr1  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr4  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr5  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr6  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr7  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr8  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr9  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chrM  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chrX  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chrY  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2_gene        need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2_gene.complete  need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP30b2c.class  need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP30b2c.readme.pdf  need PK compat. v4.5 (can do v2.1)
   skipping: try.vcf                 need PK compat. v4.5 (can do v2.1)
   skipping: tryhg18.in              need PK compat. v4.5 (can do v2.1)
   skipping: tryhg19.in              need PK compat. v4.5 (can do v2.1)
   skipping: tryhg38.in              need PK compat. v4.5 (can do v2.1)
file #1:  bad zipfile offset (local header sig):  1986460357
  (attempting to re-compensate)
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c.readme.txt  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr10  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr11  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr12  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr13  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr14  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr15  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr16  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr17  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr18  
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr19  
Fatal error: local() encountered an error (return code 2) while executing 'unzip /opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip -d dbNSFPv3.0b2c'

Aborting.
nux/install_packages.R)"
[localhost] local: echo '
        bioc.pkgs <- c("BiocInstaller", "BubbleTree", "cn.mops", "DEXSeq", "DNAcopy", "GenomicRanges", "IRanges", "rtracklayer")
        bioc.installer = repo.installer(biocinstallRepos(), biocLite, NULL)
        lapply(bioc.pkgs, bioc.installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        std2.pkgs <- c("PSCBS")
        lapply(std2.pkgs, std.installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: Rscript /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: rm -f /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: rm -rf /root/tmp/cloudbiolinux
[localhost] local: rm -rf .cpanm
[localhost] local: rm -f /var/crash/*
[localhost] local: rm -f ~/*.dot
[localhost] local: rm -f ~/*.log
Creating manifest of installed packages in /opt/pipelines/bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: echo $HOME
[localhost] local: uname -m
[localhost] local: pwd
[localhost] local: mkdir -p '/opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation/9e5abf75-1cb7-3e48-84fd-7817f48269a1'
[localhost] local: wget --continue --no-check-certificate -O dbNSFPv3.0b2c.zip 'ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFPv3.0b2c.zip'
[localhost] local: mv dbNSFPv3.0b2c.zip /opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation
[localhost] local: rm -rf /opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation/9e5abf75-1cb7-3e48-84fd-7817f48269a1
[localhost] local: mkdir -p dbNSFPv3.0b2c
[localhost] local: unzip /opt/pipelines/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip -d dbNSFPv3.0b2c

**Comment by mdeboth** [comment]
Looks like I'm encountering the same error...
```
2015-07-01 16:44:25 (994 KB/s) - “dbNSFPv3.0b2c.zip” saved [6281431546]

Archive:  /packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [/packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip]:  1986460357 extra bytes at beginning or within zipfile
  (attempting to process anyway)
   skipping: dbNSFP3.0b2c_variant.chr1  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr4  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr5  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr6  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr7  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr8  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chr9  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chrM  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chrX  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2c_variant.chrY  need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2_gene        need PK compat. v4.5 (can do v2.1)
   skipping: dbNSFP3.0b2_gene.complete  need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP30b2c.class  need PK compat. v4.5 (can do v2.1)
   skipping: search_dbNSFP30b2c.readme.pdf  need PK compat. v4.5 (can do v2.1)
   skipping: try.vcf                 need PK compat. v4.5 (can do v2.1)
   skipping: tryhg18.in              need PK compat. v4.5 (can do v2.1)
   skipping: tryhg19.in              need PK compat. v4.5 (can do v2.1)
   skipping: tryhg38.in              need PK compat. v4.5 (can do v2.1)
file #1:  bad zipfile offset (local header sig):  1986460357
  (attempting to re-compensate)
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c.readme.txt
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr10
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr11
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr12
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr13
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr14
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr15
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr16
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr17
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr18
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr19
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr2
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr20
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr21
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr22
  inflating: dbNSFPv3.0b2c/dbNSFP3.0b2c_variant.chr3

Fatal error: local() encountered an error (return code 2) while executing 'unzip /packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip -d dbNSFPv3.0b2c'

Aborting.
ges/bcbio/v0.8.8/tooldir/bin/brew info rna-star
[localhost] local: /packages/bcbio/v0.8.8/tooldir/bin/brew info tophat-binary
[localhost] local: /packages/bcbio/v0.8.8/tooldir/bin/brew info cmake
[localhost] local: /packages/bcbio/v0.8.8/tooldir/bin/brew info pkg-config
[localhost] local: /packages/bcbio/v0.8.8/tooldir/bin/brew link --overwrite pkg-config
[localhost] local: /packages/bcbio/v0.8.8/tooldir/bin/brew info s3gof3r
[localhost] local: /packages/bcbio/v0.8.8/tooldir/bin/brew info cpanminus
[localhost] local: /packages/bcbio/v0.8.8/bcbio/anaconda/bin/conda install -y -c https://conda.binstar.org/bcbio phylowgs pyloh
[localhost] local: mkdir -p '/scratch/mdeboth/tmp/cloudbiolinux'
[localhost] local: touch /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R
[localhost] local: mkdir -p /packages/bcbio/v0.8.8/tooldir/lib/R/site-library
[localhost] local: chown -R mdeboth /packages/bcbio/v0.8.8/tooldir/lib/R/site-library
[localhost] local: echo '
    .libPaths(c("/packages/bcbio/v0.8.8/tooldir/lib/R/site-library"))
    library(methods)
    cran.repos <- getOption("repos")
    cran.repos["CRAN" ] <- "http://cran.fhcrc.org/"
    options(repos=cran.repos)
    source("http://bioconductor.org/biocLite.R")
    ' >> "$(echo /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
    repo.installer <- function(repos, install.fn, pkg_name_fn) {

        update.packages(lib.loc="/packages/bcbio/v0.8.8/tooldir/lib/R/site-library", repos=repos, ask=FALSE)

      maybe.install <- function(pname) {
        check_name <- ifelse(is.null(pkg_name_fn), pname, pkg_name_fn(pname))
        if (!(is.element(check_name, installed.packages()[,1])))
          install.fn(pname)
      }
    }
    ' >> "$(echo /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
    std.pkgs <- c("cghFLasso", "devtools", "ggplot2", "gsalib", "matrixStats", "snow", "RColorBrewer")
    std.installer = repo.installer(cran.repos, install.packages, NULL)
    lapply(std.pkgs, std.installer)
    ' >> "$(echo /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        bioc.pkgs <- c("BiocInstaller", "BubbleTree", "cn.mops", "DEXSeq", "DNAcopy", "GenomicRanges", "IRanges", "rtracklayer")
        bioc.installer = repo.installer(biocinstallRepos(), biocLite, NULL)
        lapply(bioc.pkgs, bioc.installer)
        ' >> "$(echo /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        std2.pkgs <- c("PSCBS")
        lapply(std2.pkgs, std.installer)
        ' >> "$(echo /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: Rscript /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R
[localhost] local: rm -f /scratch/mdeboth/tmp/cloudbiolinux/install_packages.R
[localhost] local: rm -rf /scratch/mdeboth/tmp/cloudbiolinux
[localhost] local: rm -rf .cpanm
[localhost] local: rm -f /var/crash/*
[localhost] local: rm -f ~/*.dot
[localhost] local: rm -f ~/*.log
Creating manifest of installed packages in /packages/bcbio/v0.8.8/bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: echo $HOME
[localhost] local: uname -m
[localhost] local: pwd
[localhost] local: mkdir -p '/packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/3b1a9efa-2984-30b4-a807-d646ab58eb2e'
[localhost] local: wget --continue --no-check-certificate -O dbNSFPv3.0b2c.zip 'ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFPv3.0b2c.zip'
[localhost] local: mv dbNSFPv3.0b2c.zip /packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation
[localhost] local: rm -rf /packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/3b1a9efa-2984-30b4-a807-d646ab58eb2e
[localhost] local: mkdir -p dbNSFPv3.0b2c
[localhost] local: unzip /packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip -d dbNSFPv3.0b2c
local() encountered an error (return code 2) while executing 'unzip /packages/bcbio/v0.8.8/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip -d dbNSFPv3.0b2c'
```

**Comment by chapmanb** [comment]
Sorry about the continued problems. It looks like some older versions of unzip can't correctly handle the new dbNSFP archives, which is causing this error. I pushed a fix to install and use p7zip, which appears to cleanly handle the new zip files. If you remove the temporary cloudbiolinux directory (`rm -rf tmpbcbio-install`) and previous partial installation (`rm -f /path/to/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFP_v3.0b2c.gz*`) and re-run, it should hopefully work cleanly now. Thanks for following up and testing this and hope it works for you both now.

**Comment by mdeboth** [comment]
Thanks, Brad. Works for me!

**Comment by YiChingTang** [comment]
I think the dbNSFP problem solved. 
don't know if it's ok to post here, I think I encountered python2/python3 issue this time(?!)
(btw, I use python3.4 for bcbio_nextgen.py and python2.7 for bcbio_nextgen.py)

here's the error msg after I remove and rerun dbNSFP installation.
* downloading https://s3.amazonaws.com/gemini-annotations/whole_genome_SNVs.tsv.compressed.gz to /opt/bcbio/gemini_da

Curl failed with non-zero exit code 18. Retrying
Curl failed with non-zero exit code 56. Retrying
Curl failed with non-zero exit code 56. Retrying
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 179, in <module>
    install_annotation_files(args.anno_dir, args.dl_files, args.extra)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 101, in install_annotation_file
    to_dl, anno_dir, cur_config)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 133, in _download_anno_files
    cur_config.get("versions", {}).get(orig, 1))
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 160, in _download_to_dir
    raise ValueError("Failed to download with curl")
ValueError: Failed to download with curl
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1121, in main
    args.func(parser, args)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 996, in update_fn
    gemini_update.release(parser, args)
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 68, in release
    subprocess.check_call([sys.executable, _get_install_script(), config["annotation_dir"]] + extra_args)
  File "/opt/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/bcbio/anaconda/bin/python', '/opt/bcbio/anaconda/lib/python2.7/site-pa
[localhost] local: touch /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: mkdir -p /opt/bcbio/tools/lib/R/site-library
[localhost] local: chown -R root /opt/bcbio/tools/lib/R/site-library
[localhost] local: echo '
    .libPaths(c("/opt/bcbio/tools/lib/R/site-library"))
    library(methods)
    cran.repos <- getOption("repos")
    cran.repos["CRAN" ] <- "http://cran.fhcrc.org/"
    options(repos=cran.repos)
    source("http://bioconductor.org/biocLite.R")
    ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
    repo.installer <- function(repos, install.fn, pkg_name_fn) {

        update.packages(lib.loc="/opt/bcbio/tools/lib/R/site-library", repos=repos, ask=FALSE)

      maybe.install <- function(pname) {
  check_name <- ifelse(is.null(pkg_name_fn), pname, pkg_name_fn(pname))
        if (!(is.element(check_name, installed.packages()[,1])))
          install.fn(pname)
      }
    }
    ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
    std.pkgs <- c("cghFLasso", "devtools", "ggplot2", "gsalib", "matrixStats", "snow", "RColorBrewer")
    std.installer = repo.installer(cran.repos, install.packages, NULL)
    lapply(std.pkgs, std.installer)
    ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        bioc.pkgs <- c("BiocInstaller", "BubbleTree", "cn.mops", "DEXSeq", "DNAcopy", "GenomicRanges", "IRanges", "rt
        bioc.installer = repo.installer(biocinstallRepos(), biocLite, NULL)
        lapply(bioc.pkgs, bioc.installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: echo '
        std2.pkgs <- c("PSCBS")
        lapply(std2.pkgs, std.installer)
        ' >> "$(echo /root/tmp/cloudbiolinux/install_packages.R)"
[localhost] local: Rscript /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: rm -f /root/tmp/cloudbiolinux/install_packages.R
[localhost] local: rm -rf /root/tmp/cloudbiolinux
[localhost] local: rm -rf .cpanm
[root@Rome bcbio]# htop
[root@Rome bcbio]# less -S bcbio.toolplus.install.cadd.dbnsfp.log
[localhost] local: rm -f ~/*.dot
[localhost] local: rm -f ~/*.log
Creating manifest of installed packages in /opt/bcbio/manifest
Third party tools upgrade complete.
Installing additional tools
Upgrading bcbio-nextgen data files
Setting up virtual machine
[localhost] local: echo $HOME
[localhost] local: uname -m
[localhost] local: pwd
[localhost] local: mkdir -p '/opt/bcbio/genomes/Hsapiens/GRCh37/variation/9e5abf75-1cb7-3e48-84fd-7817f48269a1'
[localhost] local: wget --continue --no-check-certificate -O dbNSFPv3.0b2c.zip 'ftp://dbnsfp:dbnsfp@dbnsfp.softgeneti
[localhost] local: mv dbNSFPv3.0b2c.zip /opt/bcbio/genomes/Hsapiens/GRCh37/variation
[localhost] local: rm -rf /opt/bcbio/genomes/Hsapiens/GRCh37/variation/9e5abf75-1cb7-3e48-84fd-7817f48269a1
[localhost] local: mkdir -p dbNSFPv3.0b2c
[localhost] local: 7za x /opt/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip -y -odbNSFPv3.0b2c
[localhost] local: cat dbNSFPv3.0b2c/dbNSFP*_variant.chr* | bgzip -c > dbNSFP_v3.0b2c.gz
[localhost] local: rm -f dbNSFPv3.0b2c/* && rmdir dbNSFPv3.0b2c
[localhost] local: rm -f /opt/bcbio/genomes/Hsapiens/GRCh37/variation/dbNSFPv3.0b2c.zip
[localhost] local: tabix -s 1 -b 2 -e 2 -c '#' dbNSFP_v3.0b2c.gz
Traceback (most recent call last):
  File "./tools/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/opt/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
:

**Comment by chapmanb** [comment]
Glad to hear dbNSFP is now working cleanly. It looks like your reported issues is from a failure to download the GEMINI CADD file:
```
* downloading https://s3.amazonaws.com/gemini-annotations/whole_genome_SNVs.tsv.compressed.gz to /opt/bcbio/gemini_da

Curl failed with non-zero exit code 18. Retrying
```
This is a huge file (35Gb) so it's likely timing out or having other issues. CADD files are optional since they have such a big download. You'll need to retry or manually download depending on your network connection.

bcbio will only work with Python 2.7 (although the installer should be fine with Python 3.x as well) but that doesn't influence your actual problem here.

Hope this helps.

**Comment by YiChingTang** [comment]
thank you so much for the quick reply, as always!
quite a relieve to heard that timing out issue (we do have internet problem....)
Other than that, should I rm -r tmpbcbio-install, would it be also remove the installed dbNSFP?
Or would the analysis pipeline be affected?

I am asking that because I have an "samblaster: Unrecognized option: -M" problem now that I didn't see before with the same input files.

**Comment by chapmanb** [comment]
The latest release of bcbio handles the new samblaster and should only be passing the `-M` argument when you have that version:

https://github.com/chapmanb/bcbio-nextgen/blob/fd0bcdeaef2eea59825dcfa3bdfcc8c2561a4114/bcbio/ngsalign/postalign.py#L82

When you run `samblaster --version` and `which samblaster`, are you finding version 0.1.22 installed by bcbio?

Right now there appears to be something wrong with your installation where bcbio thinks you have the most recent version but you're getting an older version on your PATH.

Hope this helps.

**Comment by YiChingTang** [comment]
Oops, I do have a older version on my PATH, already fix this. Big thanks!
