### ISSUE TITLE
Always use HTTP during installation when retrieving APT keys

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#917]
Any port that's not standard is blocked here, which means requests time out infinitely. Specifically:

````
[localhost] local: sudo http_proxy=$http_proxy https_proxy=$https_proxy  bash -c "apt-key adv --keyserver subkeys.pgp.net --recv D018A4CE"
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.wOwvs2VieG --no-auto-check-trustdb --trust-model always --k
eyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/jtaylor-ipython.gpg --keyring /etc/apt/trusted.gpg
.d/marutter-c2d4u.gpg --keyring /etc/apt/trusted.gpg.d/nebc-bio-linux.gpg --keyring /etc/apt/trusted.gpg.d/x2go-stable.gpg --keyserver subkeys.pgp.net
 --recv D018A4CE
gpg: requesting key D018A4CE from hkp server subkeys.pgp.net
````

**Comment by chapmanb** [comment]
Luca;
My best suggestion would be to avoid using `--sudo` on these systems and just install any dependencies you need by hand:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html#isolated-installations

The apt and package installation is more a convenience for bootstrapping Docker or AWS images from bare machines but might be too many moving parts for a very locked down system. Hope the basic installation works cleanly with those in place.

**Comment by lbeltrame** [comment]
In the end I work-arounded it by installing the key from keyserver.ubuntu.com (that might work, if you change it in the install code, as it fetches from HTTP normally), then aborting the hung GPG process. The rest of the install went on without issues.
