### ISSUE TITLE
Empty mpileup files during VarScan run cause samtools mpileup to return with code 1, halting the run

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#918]
This came in recently when I wanted to run VarScan on an old data set. 

I get errors like

````
CalledProcessError: Command 'set -o pipefail; /mnt/data/bcbio-tools/bin/samtools mpileup -f /mnt/data/bcbio/genomes/Hsapiens/hg19/seq/hg19.fa -d 1000 -L 1000 -l /mnt/data/projects/OV198/OV198_varscan_full_2/work/varscan/chr7/20614-tumor_vs_normal-chr7_0_19156658-raw-regions.bed /mnt/data/projects/OV198/OV198_varscan_full_2/work/bamclean/20614-tumor/20614-tumor-reorder-fixrgs-gatkfilter.bam | grep -v -P ' 0               $' 
> /home/shared-tmp/bcbiotx/2af28321-e314-4b7b-9709-92ef3cac557b/tmpSk5ASb/20614-tumor_vs_normal-chr7_0_19156658-raw.mpileup
[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
' returned non-zero exit status 1
````

The reason is that the mpileup file generated is empty. I re-ran the command manually to a `tmp.mpileup` file and then

````
[einar@uni01 /mnt/data/projects/OV198/OV198_varscan_full_2/work] cat tmp.mpileup 
[einar@uni01 /mnt/data/projects/OV198/OV198_varscan_full_2/work]
````

The issue is however not in the empty mpileup file, but in the fact that `samtools` returns 1 as error code. I tried looking in the man page, but there isn't any indication of when 1 is returned in case of no errors (there aren't any).
I'm not sure if ``samtools`` changed its *modus operandi* since last time I touched this code (htslib didn't even exist at the time), or if the BAM file is wrong (it doesn't look to me, though).

EDIT: I re-checked the code and I had already thought of the empty mpileup case. How to handle `samtools` though? `do.run` always checks for return codes != 0. 

I'll also file an issue with samtools, but in the mean time, pointers for workarounds are welcome. ;)

**Comment by chapmanb** [comment]
Luca -- we could try to skip this by doing a try/except on the do.run call, but from the samtools thread it sounds like there might be something wrong with the BAM file leading to the issue. In that case I'd rather have bcbio error out instead of silently producing truncated files. What do you think? Can you identify an issue with the input files causing the problem?

**Comment by lbeltrame** [comment]
In the end it turned out that the batches had missing metadata and that caused this silent issue. I'm closing this BR here but I'll keep the samtools one open as there was no error nor any notification and yet the return code was 1.
