### ISSUE TITLE
qsignature could not find main class error

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#919]
I found this in my logs.

```
qsignature -Xms750m -Xmx2g org.qcmg.sig.SignatureGenerator
Error: Could not find or load main class org.qcmg.sig.SignatureGenerator
```

**Comment by lpantano** [comment]
Hi,

sorry about this. I tried to reproduce but in my case is working.

Do you remember if it worked before?

Would you mind to tell me the java version using in this case?

Also you can look at the `qsignature` script and see what is calling exactly.

**Comment by dwaggott** [comment]
Ah I see, I had to move the bcbio installation and thought I got most of the hard coded paths. The qsignature script has the old path to the jar in it. I'll fix. Thanks!
