### ISSUE TITLE
RFC: Amplicon mode of VarDict Java

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#922]
I just read that VarDictJava has an amplicon mode for amplicon sequencing. As a heavy user of amplicon kits, this would be extremely interesting to use. At the same time, I understand that bcbio should provide an acceptable set of defaults for its normal usage.

Therefore I see two ways here:
1. Bake support into bcbio
2. Allow specifying additional options to VarDictJava (like `jvm_opts`)

1 looks cleaner to me. Opinions?

**Comment by mjafin** [comment]
Hi Luca,
If you provide bcbio an amplicon bed file (unmerged) with the inserts in the 7th and 8th columns, VarDict will automatically pick up amplicon calling mode. This only works in unpaired analyses (feature of VarDict).

**Comment by mjafin** [comment]
The bed file lines look like this:
```
chr7    55209934        55210075        EGFR    1       .       55209957        55210054
```
You can see that the interval in the 7th and 8th columns is a subset of 2nd and 3rd.

**Comment by lbeltrame** [comment]
> If you provide bcbio an amplicon bed file (unmerged) with the inserts in the
> 7th and 8th columns, VarDict will automatically pick up amplicon calling

By inserts, you mean the amplicon coordinates (given that the designs I use 
are often tiled)? If so, that would be easy to do, indeed.

**Comment by mjafin** [comment]
Hi Luca, this is from a GeneRead Lung panel and I believe we got the bed file from the vendor:
```
chr7    55209934        55210075        EGFR    1       .       55209957        55210054
chr7    55210034        55210194        EGFR    2       .       55210054        55210175
```
You can see the amplicons are overlapping. The 2nd and 3rd columns are the intervals including the primers and the 7th and 8th columns excluding the primers.

**Comment by lpantano** [comment]
Hi all,

I will close this guessing everything is fine now. 

Thanks!
