### ISSUE TITLE
Fresh Install Fails - CentOS 7

### ISSUE THREAD

**Issue by mjharrigan** [chapmanb/bcbio-nextgen#923]
A fresh install fails on a CentOS 7 system. Command used to install is

```
python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local \
    --aligners star --nodata --distribution centos
```

The failure occurs at yum package 'ant-nodeps' install initiated from the cloudbiolinux cloned from github repo. This package is not found in the CentOS 7 repository: http://mirror.rit.edu/centos/7.1.1503/os/x86_64/Packages/. It seems this used to be provided under CentOS 6: http://mirror.rit.edu/centos/6.6/os/x86_64/Packages/ant-nodeps-1.7.1-13.el6.x86_64.rpm.

**Comment by chapmanb** [comment]
Matthew;
Sorry about the issues on CentOS 7. I pushed fixes which should let this build cleanly now. If you remove any cached cloudbiolinux builds (`rm -rf tmpbcbio-install`) and re-run it should pull the latest and hopefully build cleanly for you now. Thanks much for the report and hope this gets you going.
