### ISSUE TITLE
ped file clarification

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/bcbio-nextgen#925]
Hello!

I'd like to rerun a pooled analysis using a ped file for gemini. 

1. Do I specify the ped file under each samples metadata section? I wasn't sure given it would be the same ped file for all samples. 
 
2. If I specify fid/iid/pid/mid/sex/affected tags under metadata, do these get used to build the ped file?

3.  If I want to solely rebuild the gemini db after updating the config/ped file, what's the recommended process?

http://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html?highlight=gemini

**Comment by chapmanb** [comment]
Daryl;
Thanks for the questions:

1. bcbio supports PED file support is for a `ped` file in the input metadata of your samples. It will be smart and pick up any PED file within a batch of samples so you only need to specify it in one sample in a batch if you are manually adding it.

2. It will fill in family ID, sample ID, gender and affected status (https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/population.py#L91) from your metadata if you don't have a PED line for a sample in a family. Conversely, the template functionality can read these from the PED file when building the sample YAML:

https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#automated-sample-configuration

3.  GEMINI allows you to update a database with a new PED file. It's a quick process as this information is all stored in a separate table in GEMINI:

http://gemini.readthedocs.org/en/latest/content/preprocessing.html#updating-the-samples-table-in-a-database

Hope this helps.

**Comment by dwaggott** [comment]
Thanks!
