### ISSUE TITLE
Java 1.7 not found when running in parallel mode

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#932]
gist: https://gist.github.com/funnell/95c0dbb43f987dd596d4

This happens when JAVA_HOME is set to a Java 1.7 path, or when it is not set. The test cases seem to pass though.

**Comment by chapmanb** [comment]
Tyler;
Many job submission systems sanitize or reset environmental variables on submission. It might be worth setting this correctly in your batch script, if you're not already doing that. If you have local HPC support folks you could also inquire about how environmental variables get passed along. bcbio doesn't do anything special here, so hopefully it's something easy to figure out in your environment. Hope this helps.

**Comment by funnell** [comment]
Hello,
Thanks for the response. I probably should have included more info.
I'm not using a batch script just 
```
bcbio_nextgen.py config/test.yaml -t ipython -n 48 -s sge -q "comp1.q" -q "comp2.q"
```
Usually I set -V (export environment variables) when submitting jobs to SGE clusters. In fact, on the cluster I'm using now I have qsub aliased to `qsub -cwd -V'. The -V option should be enough to allow the jobs to select the correct java executable (the one in my path). 
I suppose what I'd be looking for, is how to do something similar with bcbio_nextgen.

**Comment by chapmanb** [comment]
Tyler;
The submission scripts bcbio creates (which should be in sge_controller* and sge_engine*) have all of the details about what we pass along. These are created and qsubbed onto the cluster, so you can test them directly. They should have the `-V` flag now:

https://github.com/roryk/ipython-cluster-helper/blob/0a930970f7a77220d30360ef8f1a7377207c52f9/cluster_helper/cluster.py#L254

so that might not be the underlying issue. Maybe the cluster is resetting some of the variables on submission?

If you need to pass additional resources (SGE `-l` flags) you can with the `-r` resources specification to bcbio, documented here: https://bcbio-nextgen.readthedocs.org/en/latest/contents/parallel.html#ipython-parallel 

Hope this helps some with sorting things out.

**Comment by funnell** [comment]
I've dug a bit further. When I run:
```
$ bcbio_nextgen.py config/test.yaml -t ipython -n 1 -s sge -q all.q
```
Having modified the _get_check_program_cmd(fn) function as follows:
```
def _get_check_program_cmd(fn):

    def wrap(name, config, default):
        program = expand_path(fn(name, config, default))
        is_ok = lambda f: os.path.isfile(f) and os.access(f, os.X_OK)
        if is_ok(program): return program

        # MODIFIED
        if name == 'java':
            raise OSError(str(os.environ['PATH'].split(":")))

        for adir in os.environ['PATH'].split(":"):
            if is_ok(os.path.join(adir, program)):
                return os.path.join(adir, program)
        else:
            raise CmdNotFound(" ".join(map(repr, (fn.func_name, name, config, default))))
    return wrap
```
The relevant output looks like:
```
['/usr/java/latest/bin', '/tmp/2752107.1.all.q', '/share/data/apps/bcbio-nextgen/bin', ...
```
While:
```
$ echo $PATH
/share/data/apps/bcbio-nextgen/bin:...
```
So it looks like a java path and some tmp path are being prepended to my PATH environment variable at some point. I suppose I should point out that
```
echo "java -version 2> /home/tfunnell/foo.txt" | qsub
```
Prints the version information for java 1.7 into foo.txt on my machine.
Thank you for being so responsive thus far. If you could point me in the direction of where the PATH prepending action might be happening I can continue to dig!

**Comment by chapmanb** [comment]
Tyler;
Thanks for debugging further. As far as I know, neither bcbio or IPython do this PATH prepending. When I run your same test on an SGE cluster here I get a `/tmp` path prepended as well but no additional path pointing to java. I believe the temporary directory addition is a SGE addition.

So I'm a bit stumped. As some next ideas, if you edit the `sge_engine*` script produced by bcbio to remove the bcbio specific commands and just run `echo $PATH` and `which java`, do you get the correct version you expect? I'm trying to identify if some other directive in there creates the difference compared to when you do your `qsub -V -cwd` command test. There is a shell setting there to use /bin/sh -- maybe that's triggering something like `.profile` that is changing the PATH?

Sorry to not have definite answers again but hope this helps.

**Comment by mjafin** [comment]
Hi @funnell,
I've had similar woes in the past and they typically revolve around either your current shell not being bash or `/bin/sh` not pointing to bash. 

If you do (in interactive mode on your submission host) 
```
echo $SHELL
```
does it point to bash?

If you do
```
/bin/sh
echo $SHELL
```
do you still get `/bin/bash`?

**Comment by funnell** [comment]
I'm using zsh, and running sh:
```
$ /bin/sh
sh-3.2$ echo $SHELL
/share/lustre/tfunnell/local/bin/zsh
```
Also in /etc/profile.d/java.sh 
```
export JAVA_HOME=/usr/java/latest
export PATH=$JAVA_HOME/bin:$PATH
```
which looks like it might be the culprit! I had no idea using zsh would cause these sorts of issues. Out of curiousity, why is /bin/sh specified as the shell for SGE jobs?

As a workaround, I've realized that I can set the java path in the resources section of my config file.

**Comment by funnell** [comment]
Following Brad's suggestion, running an SGE job using a bcbio script as template I get
```
/usr/java/latest/bin:/tmp/2755765.1.all.q:/share/data/apps/bcbio-nextgen/bin...
```
for PATH, and
```
/usr/java/latest/bin/java
```
for `which java`

**Comment by chapmanb** [comment]
Tyler;
Glad this helped identify the underlying cause. For /bin/sh we tried to follow standard practice in using a vanilla shell for running, specifically to try and avoid these issues. Typically /bin/sh won't trigger a lot of extra tweaking, although it it totally system dependent. Thanks for the patience debugging this and hope things run cleanly for you now.
