### ISSUE TITLE
Error creating seq index during setup genome

### ISSUE THREAD

**Issue by nstongcelmatix** [chapmanb/bcbio-nextgen#935]
Ran into this error.  GRCH37_hs37d5  was given as the build name (-b)

`Creating the seq index.
usage: prepare_tx_gff.py [-h] [--gtf GTF] org_build
prepare_tx_gff.py: error: unrecognized arguments: GRCH37_hs37d5
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_setup_genome.py", line 193, in <module>
    subprocess.check_call(cmd.format(**locals()), shell=True)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/share/bcbio/anaconda/bin/python /mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py --gtf /usr/local/share/bcbio/genomes/HSapiens/GRCH37_hs37d5/rnaseq/ref-transcripts.gtf /usr/local/share/java/picard GRCH37_hs37d5' returned non-zero exit status 2`

**Comment by roryk** [comment]
Hi @nstongcelmatix,

Sorry for the problem. Could you run

```usr/local/share/bcbio/anaconda/bin/python /mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py --gtf /usr/local/share/bcbio/genomes/HSapiens/GRCH37_hs37d5/rnaseq/ref-transcripts.gtf /usr/local/share/java/picard GRCH37_hs37d5
```

by itself on the command line, that might throw a more helpful error so we can figure out what is going on?

**Comment by nstongcelmatix** [comment]
Hi Rory,
  Thanks for your help.  Running it on it's own
```bash
/usr/local/share/bcbio/anaconda/bin/python /mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py --gtf /usr/local/share/bcbio/genomes/HSapiens/GRCh37_hs37d5/rnaseq/ref-transcripts.gtf /usr/local/share/java/picard GRCh37_hs37d5
usage: prepare_tx_gff.py [-h] [--gtf GTF] org_build
prepare_tx_gff.py: error: unrecognized arguments: GRCh37_hs37d5
```
removing /usr/local/share/java/picard runs but throws an error
```bash
/usr/local/share/bcbio/anaconda/bin/python /mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py --gtf /usr/local/share/bcbio/genomes/HSapiens/GRCh37_hs37d5/rnaseq/ref-transcripts.gtf GRCh37_hs37d5
Traceback (most recent call last):
  File "/mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py", line 672, in <module>
    main(args.org_build, args.gtf)
  File "/mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py", line 251, in main
    db = _get_gtf_db(gtf_file)
  File "/mnt/GRCh37/seq/cloudbiolinux/utils/prepare_tx_gff.py", line 634, in _get_gtf_db
    return gffutils.FeatureDB(db_file)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/gffutils/interface.py", line 130, in __init__
    ''')
sqlite3.OperationalError: database is locked

**Comment by roryk** [comment]
Hi @nstongcelmatix,

Thanks for finding the issue, I fixed it so the bcbio_setup_genome.py script doesn't call out with that extra argument anymore. Regarding the gffutils db being locked, it could be due to a couple different reasons. It would be easiest to blow away what has been made already and re-run the script.

**Comment by roryk** [comment]
I reopened until we can make sure this is working.

**Comment by nstongcelmatix** [comment]
It worked properly after first installing GRCh37 through the normal installation.  There are some paths that are created that it needed, but after that there were no more issues.  Thanks
