### ISSUE TITLE
novoalign step: Did not find non-empty output file

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#938]
Running `bcbio_nextgen.py config/test.yaml -t ipython -n 24 -s sge -q comp2.q` I get the following error after aligning a chunk of a fastq:

```
Did not find non-empty output file .../align/C6736ANXX_5_1_chastity_passed/split/tx/tmpqVdxNE/1_2015-07-07_test-sort-1_20000000.bam
[2015-07-19T05:55Z] compute-2-1.local: Uncaught exception occurred
```

The file `1_2015-07-07_test-sort-1_20000000.bam` exists in .../align/split/ and was never present in the tmp directory as far as I could tell.

**Comment by chapmanb** [comment]
Tyler;
Sorry about the issues. bcbio is failing a sanity check and not finding the output BAM file it expects from alignment. It's tough to tell from this snippet what failed since the errors are typically upstream in the log file. Can you reproduce if you run in non-distributed mode with `-n 1`? If so, it might be easier to identify the underlying issue with the alignment and suggest a fix. Hope this helps.

**Comment by funnell** [comment]
I'll give it a try. This is a little unrelated, but for the purpose of speeding up debugging this issue I'll bring it up anyway. At the very top of my config file I'd put `test_run: True`. However it seems as though the input file is not being downsampled, judging by the output files so far:
```
-rw-r--r-- 1 tfunnell users 498M Jul 18 22:55 1_2015-07-07_test-sort-1_20000000.bam
-rw-r--r-- 1 tfunnell users 344M Jul 20 14:03 1_2015-07-07_test-sort-20000001_40000000.bam
```
Am I missing something? Is there another way to ask bcbio to only run with a small sample of reads?
Also, despite specifying -n 48 originally, each of these alignments seemed like they were being performed serially.

**Comment by funnell** [comment]
Anyways, I just changed the split size to something small and re-ran. Here is a gist:
https://gist.github.com/funnell/a27fc91196e75fdb6beb

**Comment by funnell** [comment]
This seems to be related to #936. In novoalign.py, the tobam_cl part of
```
cmd = cmd.format(**locals()) + tobam_cl
```
contains {out_file}. However, the checking that is giving me the error is looking for tx_out_file. I suppose one possible fix would be to replace {out_file} with {tx_out_file} in the output from tobam_cl. But I'm not sure if this should be done in tobam_cl, or as a string replacement in the novoalign file, or maybe the tx_out_file checking should be changed to out_file checking... I hope you can give some guidance.

**Comment by funnell** [comment]
From this commit, it looks like the command string should contain {tx_out_file}
https://github.com/chapmanb/bcbio-nextgen/commit/0358f5fe2b6bbd5450ac520cae540d951e4c7db1

**Comment by chapmanb** [comment]
Tyler;
Thanks for the detailed report and the fixes. I pushed some additional changes which clean up the header as well, so if you update with `bcbio_nextgen.py upgrade -u development` it should pull these in and hopefully work cleanly now. Apologies for all the issues with novoalign, I should have tested this better after the latest round of refactoring. We primarily use bwa so it hadn't gotten as much love.

As an aside, you'll want to have a license for novoalign if you're planning to use it. I'm not sure if your example is just from a test machine without a license, but the logs indicate you're using the unlicensed version. That is limited to a single core so will be pretty slow to run.

Thanks again for the patience and hope this fixes everything for you.
