### ISSUE TITLE
Process one sample run across multiple lanes/multiple libraries

### ISSUE THREAD

**Issue by tcezard** [chapmanb/bcbio-nextgen#939]
Hi all,
I'm looking for a way of specify lane/barcode/library information when running bcbio-nextgen from multiple fastq file.
The only info I could find is documented there https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#multiple-files-per-sample, but it essentially means merging all the files together and thus masking any lane/library specific information.
Is there a way of resolving this?
Cheers
Tim

**Comment by lpantano** [comment]
Hi @tcezard,

Could you tell us exactly how you want to have this information?

Normally we join the fastq files for the same sample together. You have the same samples done in different lanes and library  etc ... ?

I guess you want to detect the effect of the lane/library after the analysis? If it is that, I would run the pipeline for each file, and add in the metadata all variables you want to keep. Then you can compare among lane ... and if everything is ok you can run again merging first. 

Is this for RNAseq?

I am just guessing, if you tell us more about the experiment design maybe we have more ideas.

thanks!

**Comment by roryk** [comment]
Hi Timothy,

There isn't a great way of resolving this; if you think that there shouldn't be anything systematically different between the libraries then merging them together before running makes sense. On the other hand if you think there might be a batch effect, then running them separately is the way to go. If this is the same library run across multiple lanes of sequencing machines then it is pretty safe to assume the batch effect will be minimal and you can merge them together. If they are different library preparations though, then normally you would treat them separately throughout the whole process because the preps can have a large batch effect.

Or what Lorena said.

**Comment by tcezard** [comment]
Thanks for the quick responses.
I actually had resequencing/variant calling in mind although this is also (even more so) applicable to RNA-Seq.
Intrinsically, I like the idea of keeping the metadata alongside the bam file and library and lane have an obvious place there.
From a more technical point of view:
 - GATK base recalibration will treat reads from different lanes separately considering that they might have different error profiles. 
 - We might have mixture of libraries (that very hypothetical) such as PCR free and Truseq nano and still want to call genotype on the merged dataset keeping the library info intact.

On top of that it seems odd to me to merge fastq files together to then split them to increase alignment speed.

Cheers
Tim

**Comment by chapmanb** [comment]
Tim;
This would be good to have, although we haven't prioritized it over other work like build 38 support, better parallelization and improved SV and cancer calling. So unfortunately it's not a likely goal in the near future for us, although happy to support community contributions. It would take some work to decide how to define the inputs, and then be able to manage and merge the samples inside bcbio.

Practically, we haven't found a big benefit in running BQSR (http://bcb.io/2013/10/21/updated-comparison-of-variant-detection-methods-ensemble-freebayes-and-minimal-bam-preparation-pipelines/). I also wouldn't suggest combining multiple technologies and calling in a pool. As Rory mentioned you're going to get hard to resolve batch effects from taking that approach.

Sorry to not have this integrated but hope the explanation helps.

**Comment by lpantano** [comment]
Hi 

I am closing this because it seems an old issue. And it seems that Brad explained the reason.

cheers

**Comment by alongalor** [comment]
Would like to add that this would be helpful for us too! Currently working on a big project where pre-processing needs to be done for multiple samples where fastq's are split by lanes.

**Comment by alongalor** [comment]
Thanks for the swift reply Brad! Very helpful to know! Much appreciated,
Alon
