### ISSUE TITLE
Error in detecting galaxy_dir in Docker installation

### ISSUE THREAD

**Issue by a113n** [chapmanb/bcbio-nextgen#941]
I got the following error after a fresh Docker installation, despite having specified the **--workdir** parameter. Initially I thought it was due to the missing **work_dir** argument in line 87 of  bcbio/pipeline/run_info.py. But it turns out the issue is actually due to the incorrectly parsed galaxy_dir in line 82 of bcbio/pipeline/run_info.py. 

The call to ** _get_full_paths** function returned the directory of merged yaml config which resides in the work_dir, instead of /usr/local/share/bcbio-nextgen/galaxy/. Therefore the genome data can't be located successfully.

Error log:

```python
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 226, in <module>
    main(**kwargs)
  File "/usr/local/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 37, in run_main
    fc_dir, run_info_yaml)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 73, in _run_toplevel
    dirs = run_info.setup_directories(work_dir, fc_dir, config, config_file)
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/run_info.py", line 87, in setup_directories
    _, config_file = config_utils.load_system_config()
  File "/usr/local/share/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/config_utils.py", line 67, in load_system_config
    assert work_dir is not None, "Need working directory to merge docker config"
AssertionError: Need working directory to merge docker config
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
```

**Comment by a113n** [comment]
I can confirm adding the following override allows the pipeline to run successfully. Proper fix requires modifications of upstream function calls.

```python
def setup_directories(work_dir, fc_dir, config, config_file):
    fastq_dir, galaxy_dir, config_dir = _get_full_paths(flowcell.get_fastq_dir(fc_dir)
                                                        if fc_dir else None,
                                                        config, config_file)
    #Manual override
    galaxy_dir = "/usr/local/share/bcbio-nextgen/galaxy/"

    # check default install for tool data if not found locally
    if not os.path.exists(os.path.join(galaxy_dir, "tool-data")):
        _, config_file = config_utils.load_system_config(work_dir=work_dir)
        if os.path.exists(os.path.join(os.path.dirname(config_file), "tool-data")):
            galaxy_dir = os.path.dirname(config_file)
    return {"fastq": fastq_dir, "galaxy": galaxy_dir,
            "work": work_dir, "flowcell": fc_dir, "config": config_dir}
```

**Comment by chapmanb** [comment]
Sorry about the issues and thanks for all the details. Could you provide a bit more information about how you installed the data and the command line you're using to run bcbio with docker? It's meant to be run with `bcbio_vm.py` (https://github.com/chapmanb/bcbio-nextgen-vm) which handles installing the biological data so there is a correct galaxy file pointing to the reference data. Is that how you're running it, or in some different way? Happy to try and help debug, thanks again.

**Comment by a113n** [comment]
I wasn't aware of bcbio-nextgen-vm, and I built the docker image using the bcbio-nextgen Dockerfile directly (https://github.com/chapmanb/bcbio-nextgen/blob/master/Dockerfile). Could that explain the issue?

**Comment by chapmanb** [comment]
That does make sense. The Dockerfile is only meant to build bcbio in a way that you can run it with bcbio-nextgen-vm. Standalone is still a bit hard to do in an automated way because you have to mount in all the reference data, which is what bcbio-vm automates for you.

We're working on making this a better process by integrating bcbio with the common workflow language, although that is still work in progress.

Hope the bcbio-vm approach works for you.

**Comment by lpantano** [comment]
Closing this since Brad's explanation seemed to work, feel free to re-open if you have further issues.
