### ISSUE TITLE
bcbio_nextgen_install.py fails during brew install of samtools

### ISSUE THREAD

**Issue by djhshih** [chapmanb/bcbio-nextgen#945]
This issue is different from issue #944.

Fresh install with bcbio_nextgen_install.py:

    python bcbio_nextgen_install.py /usr/local/share/bcbio --tooldir=/usr/local/opt/bcbio --genomes GRCh37 --aligners bwa --aligners bowtie2

This fails during `brew install` of `samtools-library-0.1`.

    [localhost] local: export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=$usr/local/opt/bcbio/lib/perl5:${PERL5LIB} && /usr/local/opt/bcbio/bin/brew install --env=inherit   sa$tools-library-0.1

    Warning: local() encountered an error (return code 1) while executing 'export CC=${CC:-`which gcc`} &$ export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/opt/bcbio/lib/perl5:${PERL5LIB} && /usr$local/opt/bcbio/bin/brew install --env=inherit   samtools-library-0.1'

    Traceback (most recent call last):
      File "/home/davids/builds/bioinf/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/brew.py", li$e 269, in _install_pkg_latest
        cmd.replace("brew install", "brew install -v"))
    ValueError: Failed to install brew formula: samtools-library-0.1
    To debug, please try re-running the install command with verbose output:
    export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export PERL5LIB=/usr/local/opt/bcbio
    /lib/perl5:${PERL5LIB} && /usr/local/opt/bcbio/bin/brew install -v --env=inherit   samtools-library-0.1

So I tried to brew install samtools-library-0.1 with verbose output.

    /usr/local/opt/bcbio/bin/brew install -v samtools-library-0.1 

results in

    ...
    gcc -fPIC -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_sta.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2deth.o padding.o bedcov.o bamshuf.o bam_tview_curses.o bam_tview_html.o -L/usr/local/opt/bcbio/lib -Wl,rpath,/usr/local/opt/bcbio/lib libbam.a -Lbcftools -lbcf  -lcurses  -lm -lz -lpthread
    padding.o: In function `bam_pad2unpad':
    padding.c:(.text+0xe1c): undefined reference to `update_posmap'
    padding.c:(.text+0xf3d): undefined reference to `update_posmap'
    padding.c:(.text+0x1888): undefined reference to `update_posmap'
    padding.c:(.text+0x195d): undefined reference to `update_posmap'
    collect2: error: ld returned 1 exit status
    Makefile:57: recipe for target 'samtools' failed
    make[1]: *** [samtools] Error 1
    make[1]: Leaving directory '/tmp/samtools-library-0.120150724-40377-vra7ru/samtools-0.1.20'
    Makefile:34: recipe for target 'all-recur' failed
    make: *** [all-recur] Error 1
    ...
    ==> ENV
    CC: /usr/bin/gcc-4.8 => /usr/bin/gcc-4.8.4
    CXX: /usr/bin/g++-4.8 => /usr/bin/g++-4.8.4
    OBJC: /usr/bin/gcc-4.8
    OBJCXX: /usr/bin/g++-4.8
    CFLAGS: -Os -w -pipe -march=core2
    CXXFLAGS: -Os -w -pipe -march=core2
    CPPFLAGS: -isystem/usr/local/opt/bcbio/include
    LDFLAGS: -L/usr/local/opt/bcbio/lib -Wl,-rpath,/usr/local/opt/bcbio/lib
    MAKEFLAGS: -j32
    CMAKE_PREFIX_PATH: /usr/local/opt/bcbio
    PKG_CONFIG_PATH: :/opt/mpich2/lib/pkgconfig:/opt/mpich2/lib/pkgconfig
    PKG_CONFIG_LIBDIR: /usr/local/opt/bcbio/lib/pkgconfig

I downloaded samtools-0.1.20 from github.com/samtools, and I am able to compile successfully with gcc-5.1, gcc-4.8, and gcc-4.5. So I am a little stumped...

Additionally,  `/usr/local/opt/bcbio/bin/brew install` does not appear to be responding to environmental variables CC. In the below command, brew refuses to use gcc-4.5 unless gcc-4.8 is uninstalled.

     CC=/usr/bin/gcc-4.5 /usr/local/opt/bcbio/bin/brew install -v samtools-library-0.1

I am using Archlinux with kernel 3.16.3-1-ARCH. My compilers include gcc-5.1, gcc-4.8, and gcc-4.5.

**Comment by djhshih** [comment]
I edited `Library/Taps/chapmanb/homebrew-cbl/samtools-library-0.1.rb` and changed the make line to:

    system "make CFLAGS='-g -Wall -O2 -fPIC'"

I preserved all the flags from the original samtools-0.1.20 Makefile and added -fPIC as required for building Bio-SamTools-1.41.

At least `brew install samtools-library-0.1` now runs successfully...

**Comment by chapmanb** [comment]
David;
Apologies about the build issue, and thanks for the debugging and fix. I pushed this to the homebrew recipe so it'll now be available generally. Please let us know if you run into any other issues. Thanks again.
