### ISSUE TITLE
upgrade/install 404 error: new cmake version

### ISSUE THREAD

**Issue by andersjacobsen** [chapmanb/bcbio-nextgen#946]
Looks like a new cmake version (3.3) was released a couple of days ago, the install/upgrade procedure fails accordingly:

[localhost] local: wget --continue --no-check-certificate -O cmake-3.3.0.x86_64-linux.bottle.tar.gz 'https://s3.amazonaws.com/cloudbiolinux/brew_bottles/cmake-3.3.0.x86_64-linux.bottle.tar.gz'
--2015-07-29 12:43:52--  https://s3.amazonaws.com/cloudbiolinux/brew_bottles/cmake-3.3.0.x86_64-linux.bottle.tar.gz
Resolving s3.amazonaws.com... 54.231.2.32
Connecting to s3.amazonaws.com|54.231.2.32|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-29 12:43:53 ERROR 404: Not Found.

**Comment by chapmanb** [comment]
Anders;
Thanks much for the heads up. I pushed a new bottle so this shold hopefully work cleanly again now, and also fixed a bug that prevented it from compiling when the bottle is not found. Much appreciated, hope this gets things working cleanly for you now.
