### ISSUE TITLE
Bedtools cannot find input BED file - bug in delly exclude file preperation workflow

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#947]
In the `delly` exclude file preparation workflow triggered by the [main `delly` workflow](https://github.com/chapmanb/bcbio-nextgen/blob/30c48f194a2031986b57cf210cc2e37fea9ae2c0/bcbio/structural/delly.py#L59), a chromosome name (such as "`1`") [is passed to sshared.prepare_exclude_file()](https://github.com/chapmanb/bcbio-nextgen/blob/30c48f194a2031986b57cf210cc2e37fea9ae2c0/bcbio/structural/delly.py#L29) which in turn calls [pybedtools in bcbio.structural.shared.prepare_exclude_file()](https://github.com/chapmanb/bcbio-nextgen/blob/37a362153d99926f1223a251cad29d5abc3ebd4b/bcbio/structural/shared.py#L93). Since the chromosome name is not a valid path to a BED file, I get a `ValueError: File "1" does not exist` and `delly` cannot complete. It seems as if someone may have switched a parameter there.

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for the heads up and sorry about the issue. We reworked this section but were not properly handling chromsome subsetting at all. I fixed this up so it should work cleanly for delly now as well. Let us know if you run into anything else at all. Thanks again.
