### ISSUE TITLE
Disambiguation statistics are false if disambiguation is run over split input BAM

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#948]
In case disambiguation is parallelized over multiple split BAM files (due to `align_split_size`), a text file with disambiguation statistics is generated that looks like this:

```
sample  unique species A pairs  unique species B pairs  ambiguous pairs
1_150728_SAMPLENAME-sort-100000001_120000000  4928769 67227   4016
1_150728_SAMPLENAME-sort-1_20000000   4928996 67018   3993
1_150728_SAMPLENAME-sort-120000001_129829368  2422153 33163   2032
1_150728_SAMPLENAME-sort-80000001_100000000   4929652 66420   3939
1_150728_SAMPLENAME-sort-20000001_40000000    4928909 67034   4066
1_150728_SAMPLENAME-sort-40000001_60000000    4928909 67069   4028
1_150728_SAMPLENAME-sort-60000001_80000000    4929021 66981   4009
```
However, only the first row of this file makes it into `project-summary.yaml` into the `summary/metrics/Disambiguated*` fields. This is false since the field values would have to be added across the sample splits (sum all `unique species A pairs`, sum all `unique species B pairs`, sum all `ambiguous pairs`). The faulty function is [bcbio.pipeline.qcsummary._parse_disambiguate()](
https://github.com/chapmanb/bcbio-nextgen/blob/30c48f194a2031986b57cf210cc2e37fea9ae2c0/bcbio/pipeline/qcsummary.py#L201). The fix should be simple, just iterate through the lines of that file and add the values, such as this (also a little more compact):

```python
def _parse_disambiguate(disambiguatestatsfilename):
    """Parse disambiguation stats from given file.
    """
    disambig_stats = [0, 0, 0]
    with open(disambiguatestatsfilename, "r") as in_handle:
        for i, line in enumerate(in_handle):
            fields = line.strip().split("\t")
		    if i == 0:
                assert fields == ['sample', 'unique species A pairs', 'unique species B pairs', 'ambiguous pairs']
            else:
                disambig_stats = [x + int(y) for x, y in zip(disambig_stats, fields[1:])]        
    return disambig_stats
```

**Comment by schelhorn** [comment]
Addendum: I have tested the bug fix on a test set and am moving it into production at our installation. So perhaps @chapmanb could include it into the next batch of bug fixes if it's not too much of a hassle.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks much for this. I pulled this in as-is, please let me know if you run into any issues testing it. In the future, definitely feel free to send pull requests for these so you can get proper credit for your improvements and debugging in the repo history. Thanks again.
