### ISSUE TITLE
Absolute qualimap statistics in project-summary.yaml are based on downsampled numbers 

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#949]
Currently, if you enable the `qualimap` tool its results will be parsed and inserted into `project-summary.yaml` without further comment. This is dangerous since qualimap results are based on downsampled (to 10M reads) BAM files, [as shown here](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/qcsummary.py#L573). 

As a result, all absolute read count numbers in `project-summary.yaml` that were generated by `bamtools` (which uses the full number of reads in the BAM file, so the "correct" value) are significantly off compared to the `qualimap` results that are based on downsampled input. Of course, all relative `qualimap` statistics such as percentages are still okay - although they remain only estimates. 

This is really confusing for the end user, since now the `project-summary.yaml` fields `Mapped reads` and `mapped` which should report the same number are different. If sampling in `qualimap` remains as it is, I suggest scaling the absolute numbers by the fraction of reads used for the sampling and clearly indicating that these scaled numbers and the `qualimap` relative numbers are just estimates - perhaps by adding am `_est` suffix to the field names. For fields where correct numbers are available (such as `mapped`), the `qualimap` estimates should best be omitted, in my opinion.

**Comment by schelhorn** [comment]
Alternatively, one could allow the user to turn off `qualimap` downsampling. In that case the `qualimap` results would make sense again. Or bcbio just exposes the relative values, and not the absolute ones to `project-summary.yaml`.

**Comment by lpantano** [comment]
Thanks for the comments!

I am completely agree with that. We turn on qualimap to test in some 
samples and see if downsampling results make sense. Doing qualimap with 
the original bam file it seems that needs a lot of memory and time, so 
difficult to asses the resources depending on the bam file. I will try 
to fix the labels so it is clear is an estimation and not the absolutes 
values.

thanks again!

**Comment by schelhorn** [comment]
Splendid - thanks, Lorena.

**Comment by lpantano** [comment]
Hi,

I change the labels to: `qualimap_1e7reads_est` to be clear about what this value says (652c3c33). Thanks a lot!
