### ISSUE TITLE
Export chanjo coverage file

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#950]
This is a feature request; I'd appreciate it if the annotated Chanjo coverage BED file could be part of the final `upload` results. I am referring to an unfiltered (!) version of the temporary BED file generated [here](https://github.com/chapmanb/bcbio-nextgen/blob/c45b7cfe069e3703ee44c298fa02de46cee3399c/bcbio/variation/coverage.py#L130). The Chanjo database is much less accessible and requires SQLite to get the same data. I would like to use these data to get at the number of regions with at least 20x (or 1x) sequencing coverage.

**Comment by roryk** [comment]
Hi Sven-Eric,

Your timing is impeccable, I just added this last night, I'll push the changes in a bit. I'm just going to drop the incomplete regions file and just keep the unfiltered one.

**Comment by schelhorn** [comment]
Well, Rory, I guess it's your timing that is impeccable then. Thank you. If by any chance you were also interested in 20x coverage ratios, I suggest that these could be added to qcsummary.py - but I can do that in post processing, too.

**Comment by roryk** [comment]
Thanks-- what do you mean by coverage ratios? Any suggestions you have about what would be useful to report would be awesome.

**Comment by schelhorn** [comment]
Thanks for asking; I guess what I was thinking about are the usual quality metrics used to quantify the success of targeted region enrichment, such as whole exome library prep & sequencing, or amplicon seq etc. As I am sure you know, with these technologies you get rather non-uniform coverage due to both stochastic effects (poisson or lander-waterman noise, whatever) and biological properties of the enrichment and sequencing processes (amplification and capture biases, GC-content and the like). 

   Due to this non-uniform coverage, some targeted genomic regions may soak up all your reads during sequencing while other regions are not covered well or at all. As a result, one usually has to oversample the targeted genomic regions (such as 54Mbp aggregated exon regions for a off-the-shelf WES-kit) quite a bit to 100x (or up to 150x for clinical variants, or 250x for subclonal variants) in sequencing in order to cover as many of these regions with at least a minimum callable coverage C. Usually, C is chosen to be 20x, although arguments for both lower and higher values can be made depending on subclonality etc.

   So what I am looking for from the Chanjo output (and in project-summary.yaml) is the percentage (or ratio) of number of bases within target regions (and/or ratio of the number of target regions themselves) that are covered with at least a coverage (or average coverage in the case of regions) of C=20x. Perhaps also an additional metric for C=1x may make sense to see which regions did not get reads at all. At the same time, we could use Chanjo also to compute the average coverage across all targeted regions; bcbio right now uses qualimap to get at these values, but these are wrong since qualimap is configured to work on a downsampled BAM files of 10M reads if I interpreted the code correctly. Doing all coverage calculations with Chanjo instead would be more efficient.

   Given these values, bcbio users can go back to the library prep or sequencing service providers and point out samples with failed library prep, and/or insufficient sequencing coverage, so there is an immediate practical benefit to measuring these things (at least until WGS is the norm, but even then we could still continue to look on the numbers of callable exons).

**Comment by ohofmann** [comment]
We have some of that already for internal reports (the X coverage per region in different plots) thanks to work from @roryk and @lpantano. Let me re-run some recent samples and generate reports for them that include those plots and problematic regions as a starting point.

**Comment by schelhorn** [comment]
@ohofmann: sounds great. I'll run with a simpler approach that just uses summary metrics for database ingestion. The following (trivial) code seems to be suitable for the gzipped Chanjo coverage BED file that bcbio now generates:

```python
class CoverageReader(object):
    
    def __init__(self, coverage_bed_gz_path):
        
        self.input_path   = coverage_bed_gz_path
        
        self.num_regions  = 0.0
        self.num_callable = 0
        self.num_20x      = 0
        self.sum_coverage = 0
        
        with gzip.open(self.input_path, 'rb') as bed_handler:
            
            for line in bed_handler:
                
                fields         = line.strip().split('\t')
                foldx_coverage = fields[4]
                bases_complete = fields[5]
                
                self.num_regions  += 1
                self.sum_coverage += float(foldx_coverage)
                
                if float(bases_complete) >= 1:
                    self.num_callable += 1
                
                if float(foldx_coverage) >= 20:
                    self.num_20x += 1
                
        self.avg_coverage   = self.sum_coverage / self.num_regions
        self.ratio_callable = self.num_callable / self.num_regions
        self.ratio_20x      = self.num_20x      / self.num_regions
```
