### ISSUE TITLE
SGE cluster hanging?

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#951]
Hello,

I had gotten the pipeline working and started to align, but stopped to adjust a parameter (decreased align_split_size). Since then, I haven't been able to get the alignment to run. I'll get to the point where the output says something like:
```
[2015-07-30T02:22Z] node0188: Resource requests: ; memory: 1.00; cores: 1
[2015-07-30T02:22Z] node0188: Configuring 1 jobs to run, using 1 cores each with 1.00g of memory reserved for each job
```
a number of times, then will just sit there for hours. I couldn't see anything in the logs that would suggest what is wrong except the occasional No heartbeat message. I was trying to run with 1000 cores previously, but now I'm trying with just 1 core and the sge log is full of No heartbeat messages (48 in a row currently). The out gets to ipython: disambiguate_split now and has been there for almost an hour.

Likely something is wrong on my end, but I'm not sure how to diagnose at this point.

`python -c 'import socket; print socket.gethostbyname(socket.gethostname())'` returns an IP address.

**Comment by chapmanb** [comment]
Tyler;
Sorry about the issue. Hanging without any output is frustrating. I'm not sure what is happening but can offer some suggestions:

- When you run in non-distributed mode (`-n 1`) on a local machine, does it still hang?
- How many samples are you running together? Since you mention 1000 cores, I'm assuming it's a lot. You might want to batch them up into smaller chunks (<100 together) as the iPython framework can get overwhelmed with a ton of messages.
- Changing `align_split_size` in the middle of an alignment may not work cleanly if some blocks already got aligned. bcbio will re-run all of the `split` alignments since the endpoints changed, so you'll end up with a larger number of total BAM files.

Hope these help some with diagnosing the issue.

**Comment by funnell** [comment]
Hi Brad,

Thanks for the suggestions. I think the issue was related to the number of alignment jobs submitted. I got things running again with a larger align_split_size (with alignments starting over). Do you have an idea of the upper limit on the number of jobs ipython parallel can handle?

**Comment by chapmanb** [comment]
Tyler;
Thanks for following up. That makes sense, as there is a limit to the scalability of the IPython controller and messages. I've used 100 samples x 250 regions = 25k concurrent messages without issues but you can probably push a bit more. The major issue becomes memory limitations on the controller machine so it is somewhat machine specific. We're actively working to integrate with the common workflow language (CWL) where we can run on alternative schedulers that hopefully won't have these limits. Thanks again.

**Comment by funnell** [comment]
It sounds like you are able to align more than one sample at a time, but my run seems to be running less than half as many alignment jobs as requested cores. Is there a parameter I can fiddle with to see if I can get more jobs running? Maybe amount of memory on the controller machine (I'm assuming this is where the bcbio-c job is running)?
When I was having issues bcbio was running 1 sample split over <1000 cores.

**Comment by chapmanb** [comment]
Tyler;
`align_split_size` is the right command to give you more chunks to process on. I haven't tried splitting up a single sample this dramatically but it should be possible. Generally what bcbio tries to do is use as many cores as possible on a single machine (set in `bcbio_system.yaml`) so if you have 32 cores/machine, you'd want to target 1000 / 32 ~= 32 splits, so divide the number of reads in your fastq files by 32 and use this as `align_split_size` to maximize cores.

Practically the splits all need to get merged together in the second step so there may not be a huge advantage of splitting more aggressively than that. Hope this helps.
