### ISSUE TITLE
manta SV caller broken by last commit

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#952]
Commit c9f72a5 broke manta SV calling; a sample that ran fine before is now failing since the sample name in the `diploidSV.vcf.gz` file is `SAMPLE`, and not `TUMOR` as believed by bcbio. This is strange since I am running in unpaired mode, and the commit code should be reacting correctly to that. So somehow the `paired` variable is not set correctly in the commit code. Anyway, the `sed`-replacement pipe fails [about here](https://github.com/chapmanb/bcbio-nextgen/blob/c9f72a5a06c84bffb05d0353f8cc4bdff8324cdf/bcbio/structural/manta.py#L54) with a `bcftools` error `Error: subset called for sample that does not exist in header`.

**Comment by schelhorn** [comment]
Hmm, it seems as if the [bcbio.variation.vcfutils.get_paired()](https://github.com/chapmanb/bcbio-nextgen/blob/c9f72a5a06c84bffb05d0353f8cc4bdff8324cdf/bcbio/variation/vcfutils.py#L36) function will always return a non-False or non-None object, so `paired` as [determined by the manta code](https://github.com/chapmanb/bcbio-nextgen/blob/c9f72a5a06c84bffb05d0353f8cc4bdff8324cdf/bcbio/structural/manta.py#L17) is never False/None, and that code [later always decides](https://github.com/chapmanb/bcbio-nextgen/blob/c9f72a5a06c84bffb05d0353f8cc4bdff8324cdf/bcbio/structural/manta.py#L51) that we have a paired/normal pair even if it is tumor only. Could that be the culprit?

**Comment by chapmanb** [comment]
Sven-Eric;
Thanks much for the heads up. I pushed a fix that should address this: you were right on, I should have checked for both paired and having a normal_bam for the tumor/normal case. Thanks for being so on top of the new changes. I'm hoping to have manta ready for the new release and write up results. It's quite fast and validates well. Here are the latest validation results:

http://imgur.com/a/Gajsg

Thanks again.

**Comment by schelhorn** [comment]
Thanks, Brad. From the validation results it surely looks like as if `manta` blows the competition out of the water, especially precision-wise.
