### ISSUE TITLE
Installation failure on CentOS 7.1

### ISSUE THREAD

**Issue by verdurin** [chapmanb/bcbio-nextgen#955]
Hello

I'm trying my first test installation on a CentOS 7.1 OpenStack instance. Here's the command I'm using:

./bcbio_nextgen_install.py ~/bcbio --tooldir ~/bbcio --isolate --genomes GRCh37 --aligners bwa --aligners bowtie2

following the instructions for an isolated, non-root installation at:

http://bcbio-nextgen.readthedocs.org/en/latest/contents/installation.html

with the requirements listed there installed.

I'm seeing an error relating to SSLeay:

Configuring IO-Socket-SSL-2.016 ... OK
==> Found dependencies: Net::SSLeay, Mozilla::CA
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.70.tar.gz ... OK
Configuring Net-SSLeay-1.70 ... OK
Building Net-SSLeay-1.70 ... FAIL
! Installing Net::SSLeay failed. See /home/centos/.cpanm/work/1438595671.29191/build.log for details. Retry with --force to force install it.
--> Working on Mozilla::CA
Fetching http://www.cpan.org/authors/id/A/AB/ABH/Mozilla-CA-20141217.tar.gz ... OK
Configuring Mozilla-CA-20141217 ... OK
Building Mozilla-CA-20141217 ... OK
Successfully installed Mozilla-CA-20141217
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.016.
! Installing the dependencies failed: Module 'IO::Socket::SSL' is not installed
! Bailing out the installation for LWP-Protocol-https-6.06.
1 distribution installed

Fatal error: local() encountered an error (return code 1) while executing ' /home/centos/bbcio/bin/cpanm -i --notest --local-lib=/home/centos/bbcio  'LWP::Protocol::https''

Aborting.
Traceback (most recent call last):
  File "./bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/centos/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir', '/home/centos/bbcio', '--isolate', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1

**Comment by verdurin** [comment]
Looks like this was the result of missing OpenSSL headers:

less /home/centos/.cpanm/work/1438596209.30340/build.log

Building Net-SSLeay-1.70
cp lib/Net/SSLeay.pm blib/lib/Net/SSLeay.pm
AutoSplitting blib/lib/Net/SSLeay.pm (blib/lib/auto/Net/SSLeay)
blib/lib/Net/SSLeay.pm: some names are not unique when truncated to 8 characters:
 directory blib/lib/auto/Net/SSLeay:
  do_https3.al, do_https2.al, do_https4.al, do_https.al truncate to do_https
  do_httpx3.al, do_httpx2.al, do_httpx4.al truncate to do_httpx
  get_https.al, get_https3.al, get_https4.al, get_http.al, get_http3.al, get_http4.al, get_httpx.al, get_httpx3.al, get_httpx4.al truncate to get_http
  head_https.al, head_https3.al, head_https4.al, head_http.al, head_http3.al, head_http4.al, head_httpx.al, head_httpx3.al, head_httpx4.al truncate to head_htt
  post_https.al, post_https3.al, post_https4.al, post_http.al, post_http3.al, post_http4.al, post_httpx.al, post_httpx3.al, post_httpx4.al truncate to post_htt
  put_https.al, put_https3.al, put_https4.al, put_http.al, put_http3.al, put_http4.al, put_httpx.al, put_httpx3.al, put_httpx4.al truncate to put_http
  ssl_read_all.al, ssl_read_until.al, ssl_read_CRLF.al truncate to ssl_read
  ssl_write_all.al, ssl_write_CRLF.al truncate to ssl_writ
  tcp_read_all.al, tcp_read_until.al, tcp_read_CRLF.al truncate to tcp_read
  tcp_write_all.al, tcp_write_CRLF.al truncate to tcp_writ
cp lib/Net/SSLeay.pod blib/lib/Net/SSLeay.pod
cp lib/Net/SSLeay/Handle.pm blib/lib/Net/SSLeay/Handle.pm
/usr/bin/perl "-Iinc" /usr/share/perl5/vendor_perl/ExtUtils/xsubpp  -typemap /usr/share/perl5/ExtUtils/typemap -typemap typemap  SSLeay.xs > SSLeay.xsc && mv SSLeay.xsc SSLeay.c
gcc -c   -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic   -DVERSION=\"1.70\" -DXS_VERSION=\"1.70\" -fPIC "-I/usr/lib64/perl5/CORE"   SSLeay.c
SSLeay.xs:163:25: fatal error: openssl/err.h: No such file or directory
 #include <openssl/err.h>
                         ^
compilation terminated.
make: *** [SSLeay.o] Error 1
-> FAIL Installing Net::SSLeay failed. See /home/centos/.cpanm/work/1438596209.30340/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Module 'Net::SSLeay' is not installed
-> FAIL Bailing out the installation for IO-Socket-SSL-2.016.
-> FAIL Installing the dependencies failed: Module 'IO::Socket::SSL' is not installed
-> FAIL Bailing out the installation for LWP-Protocol-https-6.06.

**Comment by chapmanb** [comment]
Adam -- thanks for the report and isolating the problems. If you can let us know what SSL packages you needed to install on CentOS 7 we'd be happy to include this in the documentation to make it easier for folks in the future. Hope doing this gets the install working cleanly. Thanks again.

**Comment by verdurin** [comment]
Brad - I've just submitted a PR to fix this:

https://github.com/chapmanb/bcbio-nextgen/pull/956

**Comment by chapmanb** [comment]
Adam -- thanks much for the PR. I pulled this in and adjusted slightly since we need both openssl and libcurl-ssl development libraries, but hopefully it has all the right components now. Thanks again.

**Comment by verdurin** [comment]
Brad - Thanks for merging this. However, there is no such package "libcurl4-openssl-devel" on CentOS 7.1. There is a general "openssl-devel" package and a "libcurl-devel" package.
