### ISSUE TITLE
Re-running one caller does not update ensemble results

### ISSUE THREAD

**Issue by mpschr** [chapmanb/bcbio-nextgen#957]
Hi

I have rerun some samples with the new mutect minimum cell fraction option. Meanwhile the results for mutect have changed, the ensembl calling set has not changed at all.

Investigating, I found a variant in the new ensemble set which was called by mutect & vardict in the old run, and in the new run only by war dict - which is a case which should have been eliminated in the new ensemble set

```
$ zcat bAL02_ID-ensemble.vcf.gz | cut -f7 | grep -v '#' | sort | uniq -c
      1 FILTER
   1765 PASS
$ zcat backup.bAL02_ID-ensemble.vcf.gz | cut -f7 | grep -v '#' | sort | uniq -c
      1 FILTER
   1765 PASS
$ zcat bAL02_ID-mutect.vcf.gz | cut -f7 | grep -v '#' | sort | uniq -c 
      1 FILTER
    467 PASS
 582391 REJECT
$ zcat backup.bAL02_ID-mutect.vcf.gz | cut -f7 | grep -v '#' | sort | uniq -c
      1 FILTER
    751 PASS
 582107 REJECT
$ diff  bAL02_ID-ensemble.vcf.gz  backup.bAL02_ID-ensemble.vcf.gz

$
```

**Comment by chapmanb** [comment]
Michael;
If you'd like to re-calculate the ensemble calls after changing, you need to remove the ensemble directory in the work folder as part of the re-prep process. bcbio only chooses to re-run based on the presence/absence of files, and isn't smart enough to know that you changed a parameter so specific sections need to be re-run. If you remove the directory and re-run hopefully it'll give you results consistent with the new calls.

**Comment by mpschr** [comment]
Oh so simple - thanks.
