### ISSUE TITLE
An unexpected error occurred while tokenizing

### ISSUE THREAD

**Issue by linuxpham** [chapmanb/bcbio-nextgen#958]
Hi,

I have this YAML file (human_56e29c7f-8a86-443b-8bfc-d7141c8d6bc8_analysis.yaml) :

![screen shot 2015-08-04 at 4 26 28 am](https://cloud.githubusercontent.com/assets/154762/9048150/0e68c32a-3a61-11e5-949b-b835bc6b0408.png)

When i run the " sudo bcbio_nextgen.py ../config/human_56e29c7f-8a86-443b-8bfc-d7141c8d6bc8_analysis.yaml -n 32" , i got these errors:

![screen shot 2015-08-04 at 4 22 59 am](https://cloud.githubusercontent.com/assets/154762/9048180/39f27e5a-3a61-11e5-8072-8c9bf171cb67.png)

![screen shot 2015-08-04 at 4 23 32 am](https://cloud.githubusercontent.com/assets/154762/9048179/39f262a8-3a61-11e5-9bea-bb37583facb5.png)

Please help me, thank you !!!

**Comment by chapmanb** [comment]
Sorry about the problems. This looks like a filesystem problem where it might be overworked during processing. The main error here is being unable to create a symlink, which is unexpected. If you re-run, does it still error out at the same location? Hope a re-run fixes the problem.

**Comment by linuxpham** [comment]
Hi,
I still get the same errors when rerunning.
Please help me, thank you !!!

**Comment by linuxpham** [comment]
Hi Admin,

I store these samples at : /media/store1 (a NFS mount point)

Are there any issues with NFS file system  ?

Thanks !!!

**Comment by roryk** [comment]
Hi @linuxpham,

I'm not sure why this symlink is failing. As a workaround I added some code to check for that exception when it tries to create the symlink and failback to copying the file over rather than linking it. It would be good to find the root cause though;  can you make symlinks on that NFS mount no problem?

**Comment by linuxpham** [comment]
hi @chapmanb and @roryk,

I fixed temporary by following these step :
- store FASTQ files at NFS system
- run bcbio_nextgen in local HDD

It is success now. Thanks for all supporting.

@roryk  : I posted some issues at : https://github.com/roryk/bcbio.rnaseq/issues/15. Please support me !!!

Nice a day . Thanks !!!
