### ISSUE TITLE
Checksum mismatch during installation?

### ISSUE THREAD

**Issue by verdurin** [chapmanb/bcbio-nextgen#960]
I'm seeing a repeatable checksum mismatch error during installation:

Fetching packages ...
cpat-1.2.2-py2 100% |############################################################################################################################################################################################################################################################################################################################| Time: 0:00:00 279.48 kB/s
cpat-1.2.2-py2 100% |############################################################################################################################################################################################################################################################################################################################| Time: 0:00:00 694.94 kB/s
cpat-1.2.2-py2 100% |############################################################################################################################################################################################################################################################################################################################| Time: 0:00:00   1.38 MB/s
cpat-1.2.2-py2 100% |############################################################################################################################################################################################################################################################################################################################| Time: 0:00:00   1.36 MB/s
Error: MD5 sums mismatch for download: https://conda.anaconda.org/bcbio/linux-64/cpat-1.2.2-py27_0.tar.bz2 (9c57f19dbe69da8d6557c402bcc3a336 != 7413facd23d07e8a17e0bb9019934e71)
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 40, in main
    install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 105, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes"] + channels + pkgs)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/centos/bcbio/anaconda/bin/conda', 'install', '--yes', '-c', 'bcbio', 'azure', 'biopython', 'boto', 'cnvkit', 'cpat', 'cython', 'gffutils', 'ipython', 'joblib', 'lxml', 'matplotlib', 'msgpack-python', 'nose', 'numpy', 'openssl', 'pandas', 'patsy', 'pycrypto', 'pip', 'progressbar', 'python-dateutil', 'pybedtools', 'pysam', 'pyvcf', 'pyyaml', 'pyzmq', 'reportlab', 'requests', 'scikit-learn', 'scipy', 'seaborn', 'setuptools', 'sqlalchemy', 'statsmodels', 'toolz', 'tornado']' returned non-zero exit status 1

I downloaded the cpat file then tried again and the same failure occurred. 

This is on a CentOS 7.1 instance, the command-line being:

python bcbio_nextgen_install.py ~/bcbio --tooldir=~/bcbio --isolate --genomes GRCh37 --aligners bwa --aligners bowtie2

**Comment by roryk** [comment]
Thanks for posting this issue. I get the same issue, but I haven't been able to figure out yet why the md5sum suddenly changed.

**Comment by chapmanb** [comment]
Adam and Rory -- sorry about the problem. I'm not sure what happened to the CPAT conda package but I uploaded an updated one that seems to install cleanly now. If you re-run the install command it should hopefully proceed cleanly now. Thanks much for reporting this.

**Comment by verdurin** [comment]
Yes, I can confirm that the problem with this package has been fixed.

Thanks.
