### ISSUE TITLE
During re-run of stopped bcbio analysis, coverage_summary does not enter parallel mode

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#965]
I am re-running a stopped bcbio analysis from the working directory. As resource manager I use a torque which assigns jobs to a couple of worker nodes. In the beginning, bcbio (correctly) runs through all the files in local mode to see from where it has to continue the previously stopped analysis run. Everything runs fine until the analysis arrives at the Chanjo part `Timing: coverage` `multiprocessing: coverage_summary`, the first part where bcbio would have to do some new processing (I assume, anyway it decided to to some heavy local processing). Here, bcbio does not submit the jobs to the parallel backend but continues in local mode, effectively dumping all the coverage BED file in the `tmp` directory of the job submit node (the node where I run `bcbio_nextgen.py` from) during the BED cleaning step. That's bad because it concentrates all the IO and processing on one node, which in this case is not equipped to do so (mostly due to `/tmp` storage limitations of the submit node). 

If bcbio at least would use the working directory for dumping the files that would be okay (still not parallel, though), but I suspect there is a deeper reason why bcbio does not use the parallel environment here (or why it thought it was okay to run in local mode even if there was some heavy lifting to do). The next set in the pipeline, `Timing: structural variation initial` is correctly run in parallel mode again, using the torque cluster.

**Comment by schelhorn** [comment]
Okay, so re-ran everything with another host, completed `Timing: coverage multiprocessing: coverage_summary`, and passed the next checkpoint. Then I stopped everything and re-ran again from the working directory. It's the same _spiel_: bcbio does not recognize that the Chanjo stuff has already been completed, and tries to redo everything in local mode on the submit node.

**Comment by roryk** [comment]
Thanks @schelhorn,

Sorry about that, we were memoizing based on a BED file that should have been temporary, which lead to this problem. Thanks for figuring out exactly what was going wrong, you are awesome.

**Comment by schelhorn** [comment]
Thanks for the quick fix, @roryk!
