### ISSUE TITLE
Manta fails with old illumina FASTQ qualities

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#967]
I had the misfortune to run `manta` on a couple of outdated FASTQ files with the old illumina (+64) format FASTQ qualities. `manta` complained about  quality scores `>70` (the old illumina qualities ran up to 72) and terminated with an exception (which I found in the `manta` workflow output, as part of the `manta` error logs in the `structural` subfolder of the working directory). `manta`, although developed by Illumina, does not provide a command line option for old quality formats:

> Alignments with basecall quality values greater than 70 are rejected (these are not supported on the assumption that this indicates an offset error) --[`manta` readme](https://github.com/Illumina/manta/blob/master/src/markdown/mantaUserGuide.md)

While I know that's possible to specify to bcbio that  inputs have old qualities, I forgot about these particularities of my input data in that run and did not do so. However, when looking into the bcbio sources it seemed as if there were no special provisions for quality score conversion prior to calling `manta` in either case. So I guess that problem would have occurred even if I had informed bcbio of the old quality format (?) 

I got around the issue by converting the input FASTQs to Sanger qualities external to bcbio. But perhaps someone could look into the code and see if I am right - and in that case add some of the conversion code that can be found elsewhere in bcbio to the `manta` wrapper so that other users won't have to face the same problem? (BTW, although I forgot to specify the quality format in the bcbio configuration,  `bwa` and `vardict` just processed the old illumina quality inputs without complaining, probably silently screwing up the results).

**Comment by chapmanb** [comment]
Sven-Eric;
bcbio handles conversion of the quality scores during alignment if you specify `format: illumina`. This either happens during preparation of a bgzipped fastq input:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/alignprep.py#L66

or in bwa directly:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/ngsalign/bwa.py#L126

The downstream tools then assume the alignments have the standard format so there won't be anything specific in those.

bcbio should error out in these cases to give you a warning that something is wrong:

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/pipeline/run_info.py#L385

so I'm surprised you didn't get an error message when parsing the input YAML file. Is this using remote fastqs in S3 or something else that would prevent this check being run?

Sorry about the issues and hope this helps.

**Comment by schelhorn** [comment]
Yep, from S3. That explains it and thank you for clearing up the matter. In that case everything is fine, closing.
