### ISSUE TITLE
bamtools fail to patch

### ISSUE THREAD

**Issue by djhshih** [chapmanb/bcbio-nextgen#968]
I found a referral from linuxbrew to bcbio regarding an earlier issue with bamtools, so I am posting the issue and solution here.

    $ export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export SHELL=${SHELL:-/bin/bash} && export PERL5LIB=/home/davids/bcbio/lib/perl5:${PERL5LIB} && /home/davids/bcbio/bin/brew install --env=inherit  --ignore-dependencies bamtools
    ==> Installing bamtools from homebrew/homebrew-science
    ==> Downloading https://github.com/pezmaster31/bamtools/archive/v2.4.0.tar.gz
    Already downloaded: /home/davids/.cache/Homebrew/bamtools-2.4.0.tar.gz
    ==> Downloading https://github.com/sjackman/bamtools/commit/3b6b89d.diff
    Already downloaded: /home/davids/.cache/Homebrew/bamtools--patch-de9438e932884a3f941a683984bed32b2eaca5c5483642c5a2253074f4a559ff.dif
    ==> Patching
    Error: Failure while executing: patch -g 0 -f -p1 -i /tmp/bamtools--patch20150810-9280-17goqdz/3b6b89d.diff

I looked at the *.diff file and found that the file was malformed. It probably was a Linux vs. Mac new line character issue.

Rather than creating a new .diff file, I decided to use sed to make the change instead, as shown below. I deleted out the patch lines and added `system "sed..."`.

    #-  patch do
    #-    # Install libbamtools in /usr/local/lib.
    #-    # https://github.com/pezmaster31/bamtools/pull/82
    #-    url "https://github.com/sjackman/bamtools/commit/3b6b89d.diff"
    #-    sha256 "de9438e932884a3f941a683984bed32b2eaca5c5483642c5a2253074f4a559ff"
    #-  end
    
      def install
        system "sed 's|lib/bamtools|lib|g' -i src/api/CMakeLists.txt"
        mkdir "build" do
          system "cmake", "..", *std_cmake_args
          system "make", "install"
        end
      end

I am running Fedora 22.

$ uname -a
Linux mdt3 4.1.2-200.fc22.x86_64 #1 SMP Wed Jul 15 20:12:12 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chapmanb** [comment]
Thanks for the report and fix. Apologies to keep moving you around, but the right place to report this is in homebrew-science:

https://github.com/Homebrew/homebrew-science

Those are the folks maintaining the recipe and might have some idea why you're having this behavior. I can't reproduce your issue on Ubuntu and CentOS, as the patch seems to work fine on both. Hope this helps get your more help and resolve the underlying problem.
