### ISSUE TITLE
Mutect jar filename

### ISSUE THREAD

**Issue by sarmadym** [chapmanb/bcbio-nextgen#970]
bcbio looks for "muTect" as the jar file prefix whereas latest version is spelled "mutect-1.1.7.jar". Received an error that jar file cannot be found. When I renamed my file to "muTect-1.1.7.jar" it worked.

**Comment by chapmanb** [comment]
Thank you for the report. I pushed a fix which should handle both cases for the jar files so the newer jars can work without needing to rename them. Please let us know if you run into any other problems and thanks again.
