### ISSUE TITLE
Dangerous use of string object comparisons

### ISSUE THREAD

**Issue by schelhorn** [chapmanb/bcbio-nextgen#977]
I am not aiming to talk down other people's coding style or anything, but when looking at the BAM sorting code I was noticing some dangerous Python syntax in string comparisons. Basically it isn't a very good idea to compare string identity with the `is` keyword as [here](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/__init__.py#L334):

```python
order_flag = "-n" if order is "queryname" else ""
```

The `is` keyword compares objects (in Python, everything is an object) by memory address (as can be checked by `id()`). Two separate string instances `"a"` and `"a"` will have different memory addresses, so comparing them with `is` would always return `false` if not for the reason that python [uses string interning](http://guilload.com/python-string-interning/) behind the scenes to globally cash strings.

However,  interning is not guaranteed to always work (since it is done heuristically and only on short strings, AFAIK), so comparing strings like this may fail randomly, in principle. As a result, strings should better be compared with `==`, else we may see random errors during BAM sorting that are near impossible to track down. 

Perhaps it would make sense to search globally through the bcbio code to see if this is done somewhere else, too.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for catching this. I pushed fixes for all the cases I could identify in the code. Please let us know if you find any other places this is causing issues. Much appreciated.
