### ISSUE TITLE
Bio-SamTool-1.41 install fail

### ISSUE THREAD

**Issue by reddpoint** [chapmanb/bcbio-nextgen#981]
I am trying to run the automatic install on a Mac. I see that others have had trouble with this installation.

! Installing Bio::DB::Sam failed. See /Users/cooperjam/.cpanm/work/1440098847.84407/build.log for details. Retry with --force to force install it.

Fatal error: local() encountered an error (return code 1) while executing 'export SAMTOOLS=/usr/local/share/samtools-0.1 &&  /usr/local/bin/cpanm -i --notest --local-lib=/usr/local --build-args='--config lddlflags=-shared' 'Bio::DB::Sam''

**Comment by chapmanb** [comment]
Apologies for the issue. bcbio currently doesn't work on Mac systems and requires a Linux-y machine to build all of the dependencies. The bcbio code is fine on Mac but most of the dependencies are not tested to build on Mac. Long term we're looking at using Docker to run bcbio on Mac with the dependencies isolated inside a Docker container, but this currently has some technical blockers on sharing folders to Docker instances on OSX.

Sorry about the issue. Hopefully you can get access to a Linux machine either locally or on AWS if you're like to run bcbio on your samples.

**Comment by lpantano** [comment]
Closing this since it seems the question was solved.

thanks for your time and let us know if there is something else we can do.
