### ISSUE TITLE
ValueError: Specified MuTect calling but 'tumor' phenotype not present in batch

### ISSUE THREAD

**Issue by funnell** [chapmanb/bcbio-nextgen#985]
Hello,

This is my own fault I think. I typed 'tumour' instead of 'tumor', but it would be nice to have this checked at the beginning of the bcbio run, rather than partway through.

**Comment by chapmanb** [comment]
Tyler -- sorry about the late error message and thanks for reporting the difficulties. I pushed a fix to catch this earlier in the process to hopefully provide more useful feedback about mistakes like this in the configuration. Hope this helps.
