### ISSUE TITLE
Isolate install Errors: Compilation failed

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#986]
Greetings! Still working through an isolated install on our computing cluster. After loading a module for Ruby 2.1.5, and re-running the install command `python bcbio_nextgen_install.py /home/bwubb/bcbio-nextgen/ --tooldir=/home/bwubb/bcbio-tools --isolate --genomes GRCh37 --genomes mm10 --aligners bwa`, I am presented with a garble of errors, for which I have yet to find an understandable solution.

...
  inflating: data/GRCm38.78/sequence.Y.bin
  inflating: data/GRCm38.78/snpEffectPredictor.bin
Traceback (most recent call last):
  File "/home/bwubb/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py", line 207, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 94, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 258, in upgrade_bcbio_data
    _upgrade_vep_data(s["fabricrc_overrides"]["galaxy_home"], tooldir)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 293, in _upgrade_vep_data
    effects.prep_vep_cache(dbkey, ref_file, tooldir)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/effects.py", line 95, in prep_vep_cache
    do.run(cmd, "Convert VEP cache to tabix %s" % ensembl_name)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 21, in run
    _do_run(cmd, checks, log_stdout)
  File "/home/bwubb/bcbio-nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 95, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command '/home/bwubb/bcbio-tools/bin/vep_convert_cache.pl -species homo_sapiens -version 81_GRCh37 -d /home/bwubb/bcbio-nextgen/genomes/Hsapiens/GRCh37/vep
Can't locate parent.pm in @INC (@INC contains: /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib /home/bwubb/bcbio-tools/lib/perl5/x86_64-linux-thread-multi /home/bwubb/bcbio-tools/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/SeqUtils.pm line 192.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/SeqUtils.pm line 192.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/Tools/CodonTable.pm line 191.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/Tools/CodonTable.pm line 191.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/PrimarySeqI.pm line 124.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/PrimarySeqI.pm line 124.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Slice.pm line 74.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Slice.pm line 74.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Feature.pm line 83.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Feature.pm line 83.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 57.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 57.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/VariationFeature.pm line 96.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/VariationFeature.pm line 96.
Compilation failed in require at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 65.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm line 65.
Compilation failed in require at /home/bwubb/bcbio-tools/bin/vep_convert_cache.pl line 41.
BEGIN failed--compilation aborted at /home/bwubb/bcbio-tools/bin/vep_convert_cache.pl line 41.
' returned non-zero exit status 2
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 275, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 46, in main
    subprocess.check_call([bcbio["bcbio_nextgen.py"], "upgrade"] + _clean_args(sys_argv, args, bcbio))
  File "/opt/software/python/2.7.5/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/bwubb/bcbio-nextgen/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/bwubb/bcbio-tools', '--isolate', '--genomes', 'GRCh37', '--genomes', 'mm10', '--aligners', 'bwa', '--data']' returned non-zero exit status 1

I have been trying to find some sort of related post with these errors, but the posts I have seen do not appear applicable, but Im probably wrong. Please advise, thank you very much.

-bwubb

**Comment by chapmanb** [comment]
Thanks for the report and apologies about the issue. It looks like your Perl installation is missing parent.pm:
```
Can't locate parent.pm in @INC
```
that's typically included with most Perl distributions but perhaps your local install is pretty minimal. I pushed a fix for this that will install parent.pm as part of the install process. If you remove the temporary directory (`rm -rf tmpbcbio-install`) and re-run the install command it'll hopefully finish smoothly now. Hope this gets it working for you.

**Comment by bwubb** [comment]
I believe that did work. After removing the tmpbcbio-install and re-running the install script, it appeared to hang after right before completion, where is lists what genomes are available. I re-ran the install once more and it went all the way through with no observable issues. Thank you for the assistance!
