### ISSUE TITLE
New support for MetaSV isnt part of the stable release although the NA12878-sv-eval example pipeline

### ISSUE THREAD

**Issue by pwaltman** [chapmanb/bcbio-nextgen#987]
the latest copy of the NA12878-sv-eval pipeline includes metasv in the list of svcallers, although support for it isn't in the stable release for bcbio (I've checked the /path-to-bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py and see metasv listed, but not as in the ENSEMBLE_CALLERS list).

Upgrading to the development branch has resolved the problem, but it probably would be best to remove the metasv from the NA12878-sv-eval pipeline until metasv makes it into the stable branch.

**Comment by chapmanb** [comment]
Peter -- sorry about the confusion. We just pushed a 0.9.2 stable release with support for MetaSV, so this should match what is in the structural variant evaluation pipeline now. Thanks again.
