### ISSUE TITLE
Running the Indelcallers

### ISSUE THREAD

**Issue by bwubb** [chapmanb/bcbio-nextgen#992]
I was able to successfully run bcbio_nextgen on one of my sample data. For the most part everything looks great, except I do not seem to have any calls or vcf files from scalplel and pindel. I set indelcaller: [scalpel, pindel] in my config.yaml as other examples showed. I have yet to find any error or mention of either in the log files. Is there any additional installation instructions required for those two tools?

The data is from a smaller targeted dna seq design so it is possible there simply were not any indels in that sample, but again I didnt see any mention of either tool during calling.

On a slightly related note, can this pipeline call indels using vardict as well? I did not see it as an option for indelcaller, but the latest bcbio post shows that is does a good job calling them. Thank you.

**Comment by chapmanb** [comment]
Brad;
Glad things ran well on the sample data. `indelcaller` is experimental and a bit different than other options since the goal was to add indel calls to MuTect output (which only has SNP calling). You should only select a single caller there and be sure you have mutect in your variantcallers. VarDict calls indels by default (as do all other callers) so there is nothing special you need to do. A configuration like:
```
algorithm:
   variantcaller: [mutect, vardict]
   indelcaller: scalpel
```
Should get you calls from VarDict plus combined calls from MuTect and Scalpel. Scalpel is the better indel option as we've not done much work tuning Pindel.

Hope this helps.

**Comment by chapmanb** [comment]
Yes, it does ensemble calling on all call types so will include both of those. If you're doing ensemble calling you want at least 3 callers so would want to include `freebayes` in the `variantcaller` list above. Hope this helps.

**Comment by bwubb** [comment]
Do Scalpel calls get added to the mutect vcf or does it form its own?

**Comment by chapmanb** [comment]
Brad -- they'll be added to the MuTect VCF output. Hope this helps.

**Comment by bwubb** [comment]
Thank you.

**Comment by razZ0r** [comment]
Ah, I just realized why pindel was not running for me.  I couldn't figure out the issue. There were no errors or anything. It would be nice to add some clarification to the [docs](https://bcbio-nextgen.readthedocs.org/en/latest/contents/configuration.html#variant-calling).

**Comment by chapmanb** [comment]
Endre;
Sorry about the confusion, I know the pindel/scalpel support for supplementing MuTect SNP-only support is a bit different. I'd be happy to improve the docs on this. How were you using pindel that provided no errors and no output and I'll think of ways to add more clarification? Thanks much.

**Comment by razZ0r** [comment]
I was using the following config:

<pre>
    variantcaller: [mutect, vardict, varscan, samtools]
    indelcaller: [scalpel, pindel]
</pre>

and did not understand why pindel did not run, until I discovered this thread. Based on the the documentation it was not clear to me that I can only define one indelcaller, and in this case only Scalpel runs.

**Comment by chapmanb** [comment]
Endre;
Thanks for the details, this is a big help to understand how to best document and fix this. The latest development version will now raise an error for multiple indelcallers. Sorry again about the confusion and thanks so much for the feedback.

**Comment by Smeds** [comment]
What is version of bcbio is needed to be able to run indelcaller? I have added 
indelcaller:scalepl
to my config file. But cannot find any evidence of scalpel having  been run.

**Comment by chapmanb** [comment]
Sorry for any confusion. `indelcaller: scalpel` only works with `variantcaller: mutect`, which is the only somatic caller lacking indel calls as well. Generally we now recommend using more recent methods that call both: GATK HaplotypeCaller for germline and VarDict for somatic calls are two good choices. Hope this helps.
