### ISSUE TITLE
lumpy-sv install fails during upgrade

### ISSUE THREAD

**Issue by lbeltrame** [chapmanb/bcbio-nextgen#995]
````
export CC=${CC:-`which gcc`} && export CXX=${CXX:-`which g++`} && export SHELL=${SHELL:-/bin/bash} && export PERL5LIB=/mnt/data/bcbio-tools/lib/perl5:${PERL5LIB} && /mnt/data/bcbio-tools/bin/brew install -v --env=inherit  --ignore-dependencies  lumpy-sv
````
[...]
````
  * linking lumpy

Error: undefined local variable or method `pkgshare' for #<Formulary::FormulaNamespacee8587c89fd5254636f23ba8c1cb04fb9::LumpySv:0x000000011180b8>
Please report this bug:
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
````

**Comment by chapmanb** [comment]
Luca;
Sorry about the issue. I'm not sure what is causing this but it looks like something is wrong with your homebrew install. It's not finding one of the standard variables when linking. Google doesn't really turn up any options for this, so how about removing your current Homebrew installation and re-running the upgrade to get a clean install:
```
rm -rf /mnt/data/bcbio-tools/Library
bcbio_nextgen.py upgrade --tools
```
Hope this fixes it for you.

**Comment by lbeltrame** [comment]
Turns out that it wasn't that deterministic: after updating brew, it started working. ;) Case closed!
